### ISSUE TITLE
Please add overrideWithValue method to FutureProviderFamily and StreamProviderFamily

### ISSUE THREAD

**Issue by MichaelTamm** [rrousselGit/riverpod#1009]
This would be very helpful for testing. 

Here is the workaround for the `StreamProviderFamily`, which I am currently using:
```
extension OverrideWithValue<State, Arg> on StreamProviderFamily<State, Arg> {
  Override overrideWithValue(State value) {
    return overrideWithProvider((_) => Provider((_) => AsyncValue.data(value)));
  }
}
```

**Comment by rrousselGit** [comment]
You can do:

```dart
myFamily(param).overrideWithValue(...)
```

It's not obvious how complex use-cases would work with the sample you gave.

**Comment by rrousselGit** [comment]
I don't plan on adding this, as there are some tricky edge-cases (overrideWithValue needs to handle value changes).

If someone can come-up with a complete idea on how this would work, I'm happy to change my mind 😄
