### ISSUE TITLE
Does different parameter in Provider.family create new instance?

### ISSUE THREAD

**Issue by BigGitWorld** [rrousselGit/riverpod#1018]
Hi.
I have a ``StateNotifier`` (A) and its corresponding ``StateNotifierProvider`` (B).
I wanna pass a simple string to the A class. So I used ``.family`` in B.
Question:
When I change passed parameter to my provider, constructor of class A is called again and therefore I have a new instance of A.
is this expected behavior? because I don't want to have different instances for different passed parameters and I wanna have a singleton class that I'm able to change its parameter.
What do I have to do?

```
class A extends StateNotifier<AsyncValue<MyObject>> {

    Reader read;
    String? data;

     //constructor:
    A(this.read, this.data) : super(AsyncValue.loading());  
}

final B = StateNotifierProvider.family<A, AsyncValue<MyObject>, String>(ref, data) => A(ref.read, data);

```

**Comment by 7mada123** [comment]
Yeah it's the expected behavior, `.family` constructor is used to have different instances of the same provider.

you can use `.overrideWithValue` or implement a function inside the `StateNotifier` class to change a value as you need.

**Comment by rrousselGit** [comment]
This is expected, yes. If you don't want that, you should not use `family`

**Comment by esodot** [comment]
Btw sometimes I pass 20 different Params to get the data from family, therefore having many instances. Does it negatively affect the overall performance of the app? Thank you

**Comment by rrousselGit** [comment]
Docs about passings args to provider should cover this
