### ISSUE TITLE
add example Navigator 2.0 with  Riverpod

### ISSUE THREAD

**Issue by samithe7** [rrousselGit/riverpod#1023]
raywenderlich.com book Flutter Apprentice    use  Routes & Navigation    with provider package  . it will be great  if there is a example 

with riverpod package

**Comment by PavelPZ** [comment]
An example with StateNotifierProvider can be found [here](https://github.com/PavelPZ/riverpod_navigator/tree/main/examples/riverpod_navigator_idea).

**Comment by rrousselGit** [comment]
I'm a bit skeptical about this. I don't want to promote ChangeNotifier

Riverpod is all about using StateNotifier, and ChangeNotifier exists primarily for a smooth transition for folks coming from Provider.
Therefore having an example about how to use it feels incorrect to me. It should use StateNotifier instead IMO

**Comment by samithe7** [comment]
thanks .

**Comment by PavelPZ** [comment]
https://dartpad.dev/?id=970ba56347a19d86ccafeb551b013fd3

**Comment by neckaros** [comment]
Closed? Where can we find this example please @samithe7
