### ISSUE TITLE
Support generic family

### ISSUE THREAD

**Issue by JensHor** [rrousselGit/riverpod#1119]
**Describe what scenario you think is uncovered by the existing examples/articles**
I'm trying to create a `StateNotifier` which is generic, but this seems to be hard because providers are defined globally. Therefore, I do not have access to the type which is 'injected' by another class. 

This is what i tried

```
final exampleProvider = StateNotifierProvider<ExampleNotifier<HowToDoThis>,
    ExampleState<HowToDoThis>>(
  (ref) {
    return ExampleNotifier<HowToDoThis>();
  },
);

class ExampleState<T> {
  ExampleState({this.item});

  final T? item;
}

class ExampleNotifier<T> extends StateNotifier<ExampleState<T>> {
  ExampleNotifier()
      : super(
          ExampleState(),
        );
}
```

Am i using this wrong? Is there a way to do this? 
**Describe why existing examples/articles do not cover this case**
[family](https://riverpod.dev/docs/concepts/modifiers/family/) describes how to use external parameters but no generics.

**Comment by rrousselGit** [comment]
This isn't supported at the moment, no.

Maybe in the future

**Comment by JensHor** [comment]
Ok. Good to know. I'll look out for updates 👍🏻

For everybody looking for a workaround for this problem, I did it like this:

late Object _provider;

StateNotifierProvider< ExampleNotifier <T>, ExampleState<T>>
    getProvider<T>() {
  return _provider
      as StateNotifierProvider< ExampleNotifier <T>, ExampleState<T>>;
}

void initializeProvider<T>() {
  _provider =
      StateNotifierProvider< ExampleNotifier <T>, ExampleState<T>>(
    (ref) {
      return ExampleNotifier<T>();
    },
  );
}

Since it's not a pretty solution, i only recommend to use this if absolutely necessary.

**Comment by rrousselGit** [comment]
I don't plan on working on this. Maybe once we have metaprogramming, but not before.

**Comment by JoshPark1** [comment]
Dear Remi,

I hope this message finds you well. I am reaching out as a user and enthusiast of the Riverpod plugin, seeking your assistance regarding the support for generic data types with providers.

Firstly, I want to express my gratitude for your incredible work on Riverpod. It has proven to be an invaluable tool for state management in my projects, and I appreciate the effort you have put into maintaining and evolving the plugin.

I have recently encountered a challenge while working with Riverpod and would greatly appreciate your guidance and support. Specifically, I am facing difficulties in utilizing generic data types with providers within the framework.

From my understanding, Riverpod supports powerful state management capabilities for various data types. However, when attempting to utilize generic types with providers, I encountered issues with type compatibility, resulting in errors during compilation.

I believe that enabling support for generic data types with providers would further enhance the flexibility and usability of Riverpod. It would allow developers to handle a wider range of data structures and promote code reuse in complex projects.

If possible, I kindly request your assistance in addressing this matter. It would be immensely helpful if you could provide guidance on any existing solutions, workarounds, or potential plans for supporting generic types with providers in future updates of Riverpod.

Additionally, if there are any specific details or code examples that would be useful for you to understand the challenges I am facing, please let me know, and I will gladly provide them.

Once again, thank you for your dedication to maintaining and improving the Riverpod plugin. Your expertise and support are highly valued within the community, and I look forward to any insights or assistance you can offer regarding generic data types with providers.

Thank you for your time and consideration.

Best regards,
Joshua Park

**Comment by Gustl22** [comment]
This issue seems doable, the generator does not support this by default, but with a little tweaking generic families work quite well :)

**Comment by rrousselGit** [comment]
This has already been added to the code-generator.

But it's not possible outside of code-generation.

**Comment by realDiegoR** [comment]
Great news! Thank u a lot. Sorry if I'm lost but, is there an ETA for the next stable release?

**Comment by BenjiFarquhar** [comment]
@rrousselGit  I have a provider that can return 2 possible sibling subtypes. Can I allow the caller to specify the expected return type in a generic (maybe in 3.0-dev)? Getting a build error. 

```
part 'vgn_itm_search_params_repo.g.dart';

@Riverpod(dependencies: [searchLocalityVm])
T vgnItmSearchParamsRepo<T extends LocalRepo<BaseVgnItmSearchParams>>(
  VgnItmSearchParamsRepoRef ref,
) {
  if (ref.read(searchLocalityVmProvider).isOnline) {
    return OnlineVgnItmSearchParamsRepo(ref.read(localDataSourceProvider)) as T;
  } else {
    return LocalVgnItmSearchParamsRepo(ref.read(localDataSourceProvider)) as T;
  }
}
```

Here, I am in the area of the app that I know I will receive a `LocalVgnItmSearchParamsRepo`:

```
      final vgnItmSearchParamsRepo =
          ref.read<LocalVgnItmSearchParamsRepo>(vgnItmSearchParamsRepoProvider);
```

The classes involved (you might not need to see this):

```
class LocalVgnItmSearchParamsRepo with LocalRepo<LocalVgnItmSearchParams> {
  final dbValue = 'localVgnItmSearchParamsValue';
  @override
  LocalDataSource localDataSource;
  @override
  String localStorageKey = 'localVgnItmSearchParams';

  LocalVgnItmSearchParamsRepo(this.localDataSource);

  @override
  LocalVgnItmSearchParams fetchLocal() {
    final savedParams = localDataSource.fetch<LocalVgnItmSearchParams>(
      keyToRead: localStorageKey,
    );
    LocalVgnItmSearchParams? vgnItmSearchParams;
    if (savedParams.isNotEmpty) {
      vgnItmSearchParams = LocalVgnItmSearchParams.fromJson(
        Map<String, dynamic>.from(
          savedParams,
        ),
      );
    } else {
      vgnItmSearchParams = LocalVgnItmSearchParams(
        categories: [
          Category(
            name: 'GroceryItm',
            selected: true,
            tags: GroceryItmTag.options.map((e) => e.value.value).toList(),
          ),
          Category(
            name: 'MenuItm',
            selected: true,
            tags: MenuItmTag.options.map((e) => e.value.value).toList(),
          ),
          const Category(
            name: 'GroceryStoreItm',
            selected: true,
            tags: [],
          ),
          Category(
            name: 'RestaurantItm',
            selected: true,
            tags: MenuItmTag.options.map((e) => e.value.value).toList(),
          ),
          const Category(
            name: 'EventItm',
            selected: true,
            tags: [],
          ),
          Category(
            name: 'FashionItm',
            selected: true,
            tags: FashionItmTag.options.map((e) => e.value.value).toList(),
          ),
          Category(
            name: 'RecipeItm',
            selected: true,
            tags: MenuItmTag.options.map((e) => e.value.value).toList(),
          ),
        ],
      );
    }

    return vgnItmSearchParams;
  }
}


class OnlineVgnItmSearchParamsRepo with LocalRepo<OnlineVgnItmSearchParams> {
  final dbValue = 'onlineVgnItmSearchParamsValue';
  @override
  LocalDataSource localDataSource;
  @override
  String localStorageKey = 'onlineVgnItmSearchParams';

  OnlineVgnItmSearchParamsRepo(this.localDataSource);

  @override
  OnlineVgnItmSearchParams fetchLocal() {
    final savedParams = localDataSource.fetch<OnlineVgnItmSearchParams>(
      keyToRead: localStorageKey,
    );
    OnlineVgnItmSearchParams? vgnItmSearchParams;
    if (savedParams.isNotEmpty) {
      vgnItmSearchParams = OnlineVgnItmSearchParams.fromJson(
        Map<String, dynamic>.from(
          savedParams,
        ),
      );
    } else {
      vgnItmSearchParams = OnlineVgnItmSearchParams(
        categories: [
          Category(
            name: 'RecipeItm',
            selected: true,
            tags: MenuItmTag.options.map((e) => e.value.value).toList(),
          ),
        ],
      );
    }

    return vgnItmSearchParams;
  }
}

abstract class BaseVgnItmSearchParams implements SearchParamsEntity {
  List<Category> get categories;
}

@freezed
class OnlineVgnItmSearchParams
    with _$OnlineVgnItmSearchParams
    implements BaseVgnItmSearchParams {
  const factory OnlineVgnItmSearchParams({
    @Default(DefaultSearchParams.defaultCategories) List<Category> categories,
    @Default(DefaultSearchParams.defaultSearchTerm) String searchTerm,
    @Default(DefaultSearchParams.defaultPage) int page,
    @Default(DefaultSearchParams.defaultPageSize) int pageSize,
  }) = _OnlineVgnItmSearchParams;

  factory OnlineVgnItmSearchParams.fromJson(Map<String, dynamic> json) =>
      _$OnlineVgnItmSearchParamsFromJson(json);

  const OnlineVgnItmSearchParams._();
}

@freezed
class LocalVgnItmSearchParams
    with _$LocalVgnItmSearchParams
    implements BaseVgnItmSearchParams {
  const factory LocalVgnItmSearchParams({
    @Default(DefaultSearchParams.defaultCategories) List<Category> categories,
    @Default(DefaultSearchParams.defaultSearchTerm) String searchTerm,
    @Default(DefaultSearchParams.defaultLocation) VpLocation location,
    @Default(DefaultSearchParams.defaultPage) int page,
    @Default(DefaultSearchParams.defaultPageSize) int pageSize,
  }) = _LocalVgnItmSearchParams;

  factory LocalVgnItmSearchParams.fromJson(Map<String, dynamic> json) =>
      _$LocalVgnItmSearchParamsFromJson(json);

  const LocalVgnItmSearchParams._();
}
```

**Comment by umersaddiq** [comment]
@rrousselGit When can we expect these [changes](https://github.com/rrousselGit/riverpod/issues/1119#issuecomment-1890783265) to be released? I prefer not to use development versions of packages.

**Comment by celvinren** [comment]
> This has already been added to the code-generator (the 3.0-dev release)
> 
> But it's not possible outside of code-generation.

When will this be released? I wait for a year to see this.

**Comment by galacticgibbon** [comment]
> > This has already been added to the code-generator (the 3.0-dev release)
> > But it's not possible outside of code-generation.
> 
> When will this be released? I wait for a year to see this.

I think it's released now
