### ISSUE TITLE
Examples of go_router using riverpod

### ISSUE THREAD

**Issue by jamolina2021** [rrousselGit/riverpod#1122]
Hi,

Currently, the go_router library is gaining popularity for navigation, as it is very powerful, and at the same time makes it easier to use Navigator 2.0.
It would be great if you could transform the examples that go_router has to use riverpod, so those of us who are starting to use riverpod could see how to use both together. 

Thank you very much for your wonderful library. 🥇 

Regards,
Jose

**Comment by PavelPZ** [comment]
Do  you think something like this?

[go_route](https://github.com/csells/go_router/blob/main/go_router/example/lib/main.dart) x [riverpod_navigator](https://github.com/PavelPZ/riverpod_navigator/blob/v0.10.0/examples/go_router/lib/main.dart)

I agree that ```go_route``` is a bit less verbose (70 go_route lines x 84 riverpod_navigator lines). I think that's the price for strictly typed navigation (```go ('/page2')``` x ```navigate([Page2Segment()])```).

**Comment by rddewan** [comment]
Yes please add the documentation to use with go_router. I am stuck with go router

**Comment by lucavenir** [comment]
This has been closed with #1356 and can be closed
