### ISSUE TITLE
No longer need of ! operation for SchedulerBinding.instance

### ISSUE THREAD

**Issue by chunghha** [rrousselGit/riverpod#1156]
**Describe the bug**
On flutter master channel, "flutter run" shows the warning below which is by this binding API clean-up.

https://github.com/flutter/flutter/pull/89451

**To Reproduce**

Just "fluttter run" for app using riverpod. Might now only affect apps with master channel so at least I'd like to give a note about the warning.

**Expected behavior**
No warning below appears on console as flutter run.

```
../../../../../.pub-cache/hosted/pub.dartlang.org/flutter_riverpod-1.0.3/lib/src/framework.dart:275:26: Warning: Operand of null-aware operation '!' has type
'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../../tools/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
```

**Comment by chunghha** [comment]
@rrousselGit I thought same. Fair enough.

**Comment by kenzieschmoll** [comment]
Can we remove the `!` operation now?

**Comment by rrousselGit** [comment]
@kenzieschmoll afaik Flutter's stable channel has yet to receive this change

Maybe it'll change post Google IO though.

**Comment by fpbouchard** [comment]
Stable now.

**Comment by felipecastrosales** [comment]
@rrousselGit is now stable, what can we do to resolve this warning?

**Comment by Hans1208** [comment]
flutter 3.0.0 just made this stable

**Comment by rrousselGit** [comment]
Done. There's both a stable and dev release fixing this issue.

**Comment by urrvesh** [comment]
If you are getting warnings like below

pub-cache/hosted/pub.dartlang.org/flutter_riverpod-1.0.3/lib/src/framework.dart:275:26: Warning: Operand of null-aware operation '!' has type
'SchedulerBinding' which excludes null.

Find the package name from that warning
For Example=> in the above case **flutter_riverpod** is the library that need to upgrade in **pubspec.yaml**

Got to that library doc page (https://pub.dev/packages/<package_name>)
and that latest version to your  **pubspec.yaml** and then **flutter pub get packages**

**Comment by rrousselGit** [comment]
Use 1.0.4
