### ISSUE TITLE
add ListenableProvider

### ISSUE THREAD

**Issue by funwithflutter** [rrousselGit/riverpod#119]
From the examples/docs it's not clear what the equivalent is for ListenableProvider (from Provider): https://pub.dev/documentation/provider/latest/provider/ListenableProvider-class.html

Or ValueListenableProvider:
https://pub.dev/documentation/provider/latest/provider/ValueListenableProvider-class.html

Basically, how can I use Riverpod to expose a regular Listenable or ValueListenable?

Also, what is ValueProvider (Riverpod) and when should that be used?

**Comment by rrousselGit** [comment]
What are you referring to by ValueProvider? There is no such class

There's no built-in Provider for listening to Listenable at the moment.

**Comment by funwithflutter** [comment]
Referring to this: https://github.com/rrousselGit/river_pod/blob/master/packages/riverpod/lib/src/framework/value_provider.dart

**Comment by rrousselGit** [comment]
It isn't exported and is an implementation detail

**Comment by funwithflutter** [comment]
Seems to be exported through hooks_riverpod. That's how I stumbled on it. I was looking for ValueListenableProvider, and found ValueProvider.

**Comment by rrousselGit** [comment]
That's a mistake. I will hide it

**Comment by Omeiza17** [comment]
Hello @rrousselGit any updates on the status of this issue( ListenableProvider)

**Comment by rrousselGit** [comment]
No

**Comment by X-Wei** [comment]
Something like a `ValueListenableProvider` would be helpful to watch `ValueListenable` objects.

For example hive provides `box.listenable()` such that the local DB changes trigger a widget rebuild: https://docs.hivedb.dev/#/basics/hive_in_flutter?id=valuelistenable it would be nice if we can have providers watching the `box.listenable()` rather than using `ValueListenableBuilder`

**Comment by iamarnas** [comment]
If someone want provide `Listenable` value and use it with Riverpod use `ChangeNotifierProvider` and convert it to `Listenable`: 

```dart
/*... */
listenableValue: ref.watch(counterProvider.notifier), 
/*... */
```

**Comment by rrousselGit** [comment]
I'll close this, as Riverpod is actively trying to reduce its API surface. People complain about having too many providers. 
Adding more would be counter-productive, especially considering it is fairly niche and with some workarounds available.
