### ISSUE TITLE
ProviderOrFamily not exposed

### ISSUE THREAD

**Issue by erabti** [rrousselGit/riverpod#1266]
Could you please expose ProviderOrFamily so we can reference it?
We need it in some implementation of writing custom state notifier provider builder, the generics can get too long so we are writing these helper to shorten that, but then we cannot  declare the type of '  List<ProviderOrFamily>? dependencies'.

**Comment by rrousselGit** [comment]
Could you expand on the reason why you need it?

**Comment by erabti** [comment]
Let's say that we have a StateNotifier<Some<Really<Nested<State>>>> that is used super frequently.
When creating provider with:
StateNotifierProvider<Notifier, State>, it's kind of unnecessary to repeat it if the state type and notifier are unified through out some major functionalities of the app. We do understand the Dart limitation of type inference and the need of two generics. But It's not possible instantiate a StateNotifierProvider fully if you can't add dependencies when needed to conform with riverpod API.

I believe exposing this will allow more flexibility according to the user's architecture and needs.

**Comment by rrousselGit** [comment]
But how does this relate to ProviderOrFamily?

**Comment by rrousselGit** [comment]
Oh I see. I forgot that it's used by "dependencies". Fair enough then, it not being exposed is a mistake.
