### ISSUE TITLE
Not so sure about how StateProvider.family works

### ISSUE THREAD

**Issue by manuel-plavsic** [rrousselGit/riverpod#1270]
**Describe what scenario you think is uncovered by the existing examples/articles**
I created a class called `AppLocalizations` that handles all app translations. I followed Reso Coder tutorial on YouTube for that. A written tutorial can be found here: https://resocoder.com/2019/06/01/flutter-localization-the-easy-way-internationalization-with-json/

I want to use Riverpod to manage the language, so that I don't have to write `(AppLocalizations.of(context)?.translate('some json key'))!` all over the place. I am aware I could use a method that only takes `context` and `key` as parameters, however I would like to use a provider for this. This way I can also optimize the code a bit, e.g., avoid passing the context each single time to infer the right `AppLocalization` instance, e.g., `AppLocalization(Locale('de'))`.

**Describe why existing examples/articles do not cover this case**
I tried to solve this issue by looking at the API, but I found no solution.

**Additional context**
My current code:

```dart
final selectedTranslationsProvider =
    StateProvider.family<AppLocalizations, Locale>(
        (ref, locale) => AppLocalizations(Locale('en')));
```

If I want to switch to italian, I am very unsure if I should write `ref.read(selectedTranslationsProvider.create(Locale('it')));`, `ref.read(selectedTranslationsProvider.call(Locale('it')));` or maybe use `overrideWithProvider`. The API and the website don't have much documentation regarding what problems these methods try to solve. It would be cool if also important differences between them could be described. I know it would become obvious what their purpose is once someone delves in, however they don't seems intuitive to me at the moment.

Without `.family` it is a bit more straightforward, as I would have simply updated its state, i.e., (`ref.read(selectedTranslationsProvider.state).update...`).

**Additional question**: If I change the state, will Riverpod automatically erase the values held in the map by the previous `AppLocalizations` instance? Or should I explicitly dispose of the provider's state (previous language), somehow?

**Comment by rrousselGit** [comment]
> If I want to switch to italian, I am very unsure if I should write `ref.read(selectedTranslationsProvider.create(Locale('it')));`, `ref.read(selectedTranslationsProvider.call(Locale('it')));`

Do:

```
ref.watch(family(key))
```

which is strictly identical to:

```
ref.watch(family.call(key));
```

> **Additional question**: If I change the state, will Riverpod automatically erase the values held in the map by the previous `AppLocalizations` instance? Or should I explicitly dispose of the provider's state (previous language), somehow?

If you use autoDispose too, yes.

Otherwise the state associated to the previous locale will stay active.

**Comment by rrousselGit** [comment]
These should be covered by the doc of family: https://riverpod.dev/docs/concepts/modifiers/family#prefer-using-autodispose-when-the-parameter-is-not-constant
