### ISSUE TITLE
Explain why WidgetRef and Ref are voluntarily dissociate

### ISSUE THREAD

**Issue by 0xpussycat** [rrousselGit/riverpod#1281]
The functionality wise looks the same. 

Why can't we have just Ref for everything? Basically, what WidgetRef gives in addition to Ref that it can't do?

**Comment by rrousselGit** [comment]
WidgetRef doesn't _add_ features, it removes some.

There's no life-cycle hooks such as onDispose/keepAlive/onCancel/...

**Comment by pranavo72bex** [comment]
In Riverpod 2.0 migration due to WidgetRef & Ref  issue it sucks. 😢

**Comment by FaFre** [comment]
For my scenario I found following solution by using fpdart:

```dart
void propagateItemChanges(Either<WidgetRef, Ref> ref) {
  final read = ref.fold((l) => l.read, (r) => r.read);

  ...
}
```

This comes in handy since `WidgetRef` and `Ref` are not sharing any common super class.

**Comment by rrousselGit** [comment]
You're still not meant to do something like this.

Using WidgetRef means you're effectively putting your logic in the UI.

**Comment by rrousselGit** [comment]
Planned to add this to the upcoming FAQ page https://github.com/rrousselGit/riverpod/issues/2623
