### ISSUE TITLE
2.0-dev "listenSelf" on StateNotifier should track the state not notifier

### ISSUE THREAD

**Issue by rich-j** [rrousselGit/riverpod#1286]
2.0.0-dev.4 introduces `listenSelf` on providers. When used with a `StateNotifierProvider` the arguments to the `listenSelf` function are typed for the notifier and not the state. We were expecting that the `listenSelf` would track state changes - especially since a likely pattern already provides access to the notifier.

```dart
final aProvider = StateNotifierProvider<ANotifier, AState>((ref) {
  final aNotifier = ANotifier();
  ref.listenSelf((ANotifier? previous, ANotifier notAState) {});  // <-- expecting this to track state, have the notifier in scope
  return aNotifier;
});
```

**Comment by vishnuagbly** [comment]
@rrousselGit When will this be published? I need this feature in my app.
