### ISSUE TITLE
Scoped (overridden) provider causes depending providers to rebuild even if the value didn't change.

### ISSUE THREAD

**Issue by MarcinusX** [rrousselGit/riverpod#1298]
**Describe the bug**
When there is a rebuilt widget that has a `ProviderScope.overrides`, then it provides a new Provider value, which causes all Providers that have the overridden as a dependency to rebuild.

**To Reproduce**
You can see that we have a `dependentProvider` which uses `scopedProvider`.
In `ParentWidget` we can click a button, to rebuild a `Container` with the key which also rebuilds `ProviderScope` with overrides.
The value in the override is always the same, so I'd expect that print in `dependentProvider` would happen only once.
But it happens on every click.
You can copy the whole code, run it, click the button, and see multiple prints in the logs, even though the value is always the same.
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final scopedProvider = Provider<String?>((ref) => null);    //<--- this will be overridden

final dependentProvider = Provider(
  (ref) {
    final text = ref.watch(scopedProvider);
    print('--building dependentProvider for $text');   //<--- I want this to recreate only when text changes
    return '$text $text';
  },
  dependencies: [scopedProvider],
);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const ParentWidget(),
      ),
    );
  }
}

class ParentWidget extends StatefulWidget {
  const ParentWidget({Key? key}) : super(key: key);

  @override
  State<ParentWidget> createState() => _ParentWidgetState();
}

class _ParentWidgetState extends State<ParentWidget> {
  int counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () => setState(() => counter++),   //<--- rebuilding on click
            child: const Text('Change state'),
          ),
          Container(
            key: Key(counter.toString()),                //<--- a key changed
            child: ProviderScope(
              overrides: [
                scopedProvider.overrideWithValue('Foo'),  //<--- therefore new override was created
              ],
              child: const ChildWidget(),
            ),
          ),
        ],
      ),
    );
  }
}

class ChildWidget extends ConsumerWidget {
  const ChildWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final combinedText = ref.watch(dependentProvider);
    return Text(combinedText);
  }
}
```
Using `flutter_riverpod: ^1.0.3`

**Expected behavior**
I'd expect that if the overridden value didn't change, it shouldn't cause the depending providers to rebuild.
If there is any workaround, I'd also highly appreciate it.

**Why does it matter?**
In my app, I depend on the value from the overridden provider to make API calls. So each reconstruction of the `dependentProvider` is causing a request which has the same parameters as the previous one meaning it's totally unnecessary.

**Comment by rrousselGit** [comment]
Hello!

Sorry for the late reply. 

Your problem is caused by your key. Since the `Key(counter.toString())` is a parent of your `ProviderScope` that contains the override, whenever `counter` changes, you are effectively disposing the previous ProviderScope and creating a new one.

As such, you are disposing the previous scoped provider and creating a new one too.

Performing a "swap with child" refactoring fixes the issue:

```dart
class _ParentWidgetState extends State<ParentWidget> {
  int counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () =>
                setState(() => counter++), //<--- rebuilding on click
            child: const Text('Change state'),
          ),
          ProviderScope(
            overrides: [
              scopedProvider.overrideWithValue('Foo'),
            ],
            child: Container(
              key: Key(counter.toString()), // the key is a child of ProviderScope
              child: const ChildWidget(),
            ),
          ),
        ],
      ),
    );
  }
```

**Comment by rrousselGit** [comment]
It could be that you misunderstood what `dependencies` does.

Since you specified `dependencies`, by scoping `scopedProvider`, this also scopes `dependentProvider`.

As such that's as if you did:

```dart
ProviderScope(
  overrides: [
    scopedProvider.overrideWithValue('Foo'),
    dependentProvider,
  ]
)
```

As such of course dependentProvider is disposed if that scope is disposed.
