### ISSUE TITLE
A better tutorial for the basic ChangeNotifier workflow

### ISSUE THREAD

**Issue by esDotDev** [rrousselGit/riverpod#130]
Following the usage examples of riverpod are hard because it references a lot of advanced use cases, like mixing with hooks, or the state_notifier package, it also adds more ambiguity because of it's discussion about usage outside of Flutter. 

As a Flutter dev using Provider, looking to migrate, I would just like to see a more flutter focused / classic usage example:
1. A ChangeNotifier model with multiple properties
2. Views that interact/bind to that model in the most succinct way (read, watch, select)
3. Lookup of that model from an out-of-tree layer (no context lookup)

Is there such an end-to-end example out there? This shgould be like <20 lines of code to demonstrate? I also think the main doc page on pub.dev could benefit from highliting this as it's initial example. And then subsequently, dive into more esoteric use cases.

Generally the docs feel like the author was really excited to talk about all the advanced use cases that are enabled, but vaults over the primary use case that devs want with riverpod, which is just decoupling from the `context` for reads.

**Comment by esDotDev** [comment]
Some other feedback, is I don't think this is a very good code snippet: 
http://screens.gskinner.com/shawn/chrome_2020-09-16_10-23-13.png

It assumes a bunch of pre-knowledge about what StateNotifier is, and does not even include the import. This leads one to assume this package is part of riverpod, and be confused when the class can not be found. 

I would think if you want to use this as a primary snippet in the header of the website, this package needs to be there out of the box?

**Comment by joanofdart** [comment]
Hey @esDotDev 

I had some time to work this one out and I can tell you... been there done that! :P 

This is how I've been using it so far, do let me know if I can be of any more service!
I'm mostly using Hooks, but you can just switch it up with a consumer widget or a consumer builder!

Using hooks:

some_view.dart
```dart
final someViewProvider = Provider.autoDipose<SomeViewModel>((ref) => SomeViewModel());

class SomeView extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final _someViewModel = useProvider(someViewProvider );

    return Scaffold(
      appBar: AppBar(
        title: const Text('SomeView!'),
      ),
      body: Text(_someViewModel.title),
    );
  }
}
```

some_view_model.dart
```dart
class SomeView {

  final title = 'SomeView!!! Yikes :)';

}
```

**Comment by joanofdart** [comment]
This is from another issue I posted  (mostly when i was learning about riverpod), you might find it useful! 
This one is using StateNotifier.

```dart

final authenticationServiceProvider = Provider<AuthenticationService>((ref) => AuthenticationService());
final firestoreServiceProvider = Provider<FirestoreService>((ref) => FirestoreService());


class ProfileStateNotifier extends StateNotifier<AsyncValue<AppUser>> {
  final Reader _reader;

  ProfileStateNotifier() : super(const AsyncValue.loading()) {
    _fetch();
  }

  _fetch() {
    final userId = _reader(authenticationServiceProvider).currentUser.uid;
    _reader(firestoreServiceProvider).getUserRecordAsStream(userId).listen((event) {
      state = AsyncValue.data(event);
    });
  }

  void updateUser(AppUser updatedUser) async {
    state = AsyncValue.data(updatedUser);
    await _reader(firestoreServiceProvider).updateUserData(updatedUser);
  }
}
```

then I'm calling this through a statenotifierProvider in the consumerWidget like this:

```dart
final profileStateNotifierProvider = StateNotifierProvider((ref) => ProfileStateNotifier());

class ProfileView extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final _profileModel = watch(profileStateNotifierProvider.state);

    return _profileModel .when(
      data: (user) {
        return Scaffold(
          backgroundColor: Colors.lightBlue[900],
          appBar: AppBar(
            actions: [
              IconButton(
                icon: Icon(Icons.search),
                color: Colors.white,
                onPressed: () {},
              )
            ],
            backgroundColor: Colors.lightBlue[900],
            title: Text('Profile'),
            centerTitle: true,
            textTheme: TextTheme(
              headline6: TextStyle(
                color: Colors.white,
              ),
            ),
            elevation: 4,
          ),
          body: ListView(
            children: [
              CircleAvatar(
                backgroundColor: Colors.black87,
                radius: 101,
                child: CircleAvatar(
                  radius: 100,
                  backgroundImage: AssetImage(user.photoURL),
                ),
              ),
              Center(child: Text(user.displayName)),
              RaisedButton(
                color: Colors.lightBlue[900],
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  'Read More',
                  style: TextStyle(
                    color: Colors.white,
                  ),
                ),
                onPressed: () {
                  final modifiedUser =
                      user.copyWith(aboutMe: 'testing if this updates using Riverpod');
                  _profileModel.updateUser(modifiedUser);
                },
              ),
            ],
          ),
        );
      },
      loading: () => Center(
        child: CircularProgressIndicator(),
      ),
      error: (error, stack) => Center(
        child: Text('Error $error'),
      ),
    );
  }
}
```

Do bare in mind I just edited this here BUT it should be close if not, working : )

**Comment by esDotDev** [comment]
Interesting, thanks for the examples. 

So if I'm reading this right... 
* To consume: we are supposed to extend ConsumerWidget and then call `watch`, is there a `select` equivalent?
* To read, we instantiate this `reader` object, and use it (why?)

**Comment by rrousselGit** [comment]
That "reader" object is just `ref.read`.
It's not an object but a typedef

select isn't implemented yet for ConsumerWidget/Consumer.

**Comment by campanagerald** [comment]
> This is from another issue I posted (mostly when i was learning about riverpod), you might find it useful!
> This one is using StateNotifier.
> 
> ```dart
> final authenticationServiceProvider = Provider<AuthenticationService>((ref) => AuthenticationService());
> final firestoreServiceProvider = Provider<FirestoreService>((ref) => FirestoreService());
> 
> 
> class ProfileStateNotifier extends StateNotifier<AsyncValue<AppUser>> {
>   final Reader _reader;
> 
>   ProfileStateNotifier() : super(const AsyncValue.loading()) {
>     _fetch();
>   }
> 
>   _fetch() {
>     final userId = _reader(authenticationServiceProvider).currentUser.uid;
>     _reader(firestoreServiceProvider).getUserRecordAsStream(userId).listen((event) {
>       state = AsyncValue.data(event);
>     });
>   }
> 
>   void updateUser(AppUser updatedUser) async {
>     state = AsyncValue.data(updatedUser);
>     await _reader(firestoreServiceProvider).updateUserData(updatedUser);
>   }
> }
> ```
> 
> then I'm calling this through a statenotifierProvider in the consumerWidget like this:
> 
> ```dart
> final profileStateNotifierProvider = StateNotifierProvider((ref) => ProfileStateNotifier());
> 
> class ProfileView extends ConsumerWidget {
>   @override
>   Widget build(BuildContext context, ScopedReader watch) {
>     final _profileModel = watch(profileStateNotifierProvider.state);
> 
>     return _profileModel .when(
>       data: (user) {
>         return Scaffold(
>           backgroundColor: Colors.lightBlue[900],
>           appBar: AppBar(
>             actions: [
>               IconButton(
>                 icon: Icon(Icons.search),
>                 color: Colors.white,
>                 onPressed: () {},
>               )
>             ],
>             backgroundColor: Colors.lightBlue[900],
>             title: Text('Profile'),
>             centerTitle: true,
>             textTheme: TextTheme(
>               headline6: TextStyle(
>                 color: Colors.white,
>               ),
>             ),
>             elevation: 4,
>           ),
>           body: ListView(
>             children: [
>               CircleAvatar(
>                 backgroundColor: Colors.black87,
>                 radius: 101,
>                 child: CircleAvatar(
>                   radius: 100,
>                   backgroundImage: AssetImage(user.photoURL),
>                 ),
>               ),
>               Center(child: Text(user.displayName)),
>               RaisedButton(
>                 color: Colors.lightBlue[900],
>                 shape: RoundedRectangleBorder(
>                   borderRadius: BorderRadius.circular(20),
>                 ),
>                 child: Text(
>                   'Read More',
>                   style: TextStyle(
>                     color: Colors.white,
>                   ),
>                 ),
>                 onPressed: () {
>                   final modifiedUser =
>                       user.copyWith(aboutMe: 'testing if this updates using Riverpod');
>                   _profileModel.updateUser(modifiedUser);
>                 },
>               ),
>             ],
>           ),
>         );
>       },
>       loading: () => Center(
>         child: CircularProgressIndicator(),
>       ),
>       error: (error, stack) => Center(
>         child: Text('Error $error'),
>       ),
>     );
>   }
> }
> ```
> 
> Do bare in mind I just edited this here BUT it should be close if not, working : )

I could not see where you initialize the _read variable. hehehe! It could be like this right?

```
  class ProfileStateNotifier extends StateNotifier<AsyncValue<AppUser>> {
  final Reader _reader;
 
  ProfileStateNotifier(Reader read) : super(const AsyncValue.loading()) {
     _reader = read; 
     _fetch();
  }

    ...
 }
```

**Comment by yaymalaga** [comment]
I would like to see more complete examples using StateNotifierProvider, as the one from @joanofdart which includes network calls and etc. I wasn't really sure if it was better to create a FutureProvider for doing the http calls and then watch it inside the StateNotifierProvider.

**Comment by joanofdart** [comment]
Hey 👋🏼 

To initialize the Reader variable, you pass it through the provider builder, e.g:
```dart
final someProvider = Provider<T>((ref) => T(ref.read));
```

As @rrousselGit stated above, its just a typedef.

@yaymalaga perhaps I can do a simple/advanced example using network calls. Let me know what do you guys think?

**Comment by yaymalaga** [comment]
@joanofdart Sound great! I was also taking a look to the bloc examples and this one seems a perfect candidate: https://bloclibrary.dev/#/flutterweathertutorial as it is using two endpoints and one depends on the other. 

For example in that case, I was thinking about using a FutureProvider for getting the location, then another FutureProvider watching that location for getting the forecast, so we could finally watch it in a StateNotiferProvider to handle the state using freezed unions (same behavior as using bloc+cubits). Maybe this is overkill and you should just do everything inside the StateNotiferProvider or handle directly the state using the FutureProvider.

**Comment by joshminton** [comment]
@esDotDev For what it's worth, I've come to Riverpod after reading the general Flutter 'intro to state' doc that uses ChangeNotifier, and your example was super helpful and I suspect would be similarly appreciated by others. Thank you!

**Comment by esDotDev** [comment]
Thanks! I'll add a PR to the doc and also write a blog post on this next week.

**Comment by rivella50** [comment]
@esDotDev Do you have a link to that blog post? I would be very interested in reading it.

**Comment by rrousselGit** [comment]
A doc for ChangeNotifierProvider was added, so I'll close this https://riverpod.dev/docs/providers/change_notifier_provider
