### ISSUE TITLE
ref.refresh with AutoDisposeFutureProvider.future disposes / throws instantly even though the original provider itself is watched

### ISSUE THREAD

**Issue by ko16a46** [rrousselGit/riverpod#1302]
Hello, I'm trying to use the pattern described in `WidgetRef.refresh` docs but I'm running into the following behavior:

**Describe the bug**
- Calling `ref.refresh(myAutoDisposeProvider.future)` throws because the provider state is disposed instantly, even if the original provider is watched via `ref.watch(myAutoDisposeProvider)`
- As a workaround, I have to call `ref.watch(myAutoDisposeProvider.future)` in the build method, even though I don't use the value

**To Reproduce**

Riverpod / Flutter riverpod version: ^2.0.0-dev.5

Relevant sample code:
```dart
class HomePage extends ConsumerWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Workaround: watch the .future provider directly
    // ref.watch(dataProvider.future);

    final value = ref.watch(dataProvider).value;

    return RefreshIndicator(
      onRefresh: () => ref.refresh(dataProvider.future), // throws
      child: ListView.builder(
        itemCount: value?.length ?? 1,
        itemBuilder: _valueItemBuilder(value),
      ),
    );
  }
}

final dataProvider = FutureProvider.autoDispose((ref) async {
  await Future.delayed(const Duration(seconds: 3));

  final random = Random();
  return List.generate(20, (index) => random.nextInt(100).toString());
});
```

Working sample repo:
https://github.com/ko16a46/riverpod_refresh_bug

Note: I haven't tried reproducing the issue in vanilla riverpod. The above issue appears in flutter_riverpod

**Observed behavior**
Pulling to refresh results in a future that completes with the following error:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: The provider AutoDisposeFutureProvider<List<String>>#a2223 was disposed before a value was emitted.
```

**Expected behavior**
- Pulling to refresh the `.future` shouldn't immediately dispose / throw because the original provider is watched.
- I would expect the refresh call to work if either the original provider or the `.future` provider are watched. If neither are watched, then throwing is expected.

-----

If the above behavior is actually expected, let me know how to workaround the issue. I need to call `ref.refresh(provider.future)` because I'm using `RefreshIndicator`. Refreshing the provider itself works but I can't access the future. Thank you!

**Comment by daniellampl** [comment]
I'm experiencing the same error. I tried to find an explanation for that in riverpod's implementation, but I wasn't able to do so. 

What I think is weird though is when you `keepAlive` the autoDispose provider (either by calling `ref.keepAlive()` or by adding a very small `disposeDelay` - it keeps alive the state for the given `disposeDelay` time behind the scenes) this error disappears during refreshing.

**Comment by abegehr** [comment]
+1, also running into this issue.
According to the docs it is correct to watch the provider and call refresh on provider.future: https://pub.dev/documentation/flutter_riverpod/2.0.0-dev.9/flutter_riverpod/WidgetRef/refresh.html
Whereas that triggers the uncaught exception and there is another problem in the docs: `final Products products = ref.watch(productsProvider);` should be `final Products products = ref.watch(productsProvider).value;`.

**Comment by rrousselGit** [comment]
This shouldn't be an issue anymore on 2.0, so closing.

The release is coming soon!
