### ISSUE TITLE
Defining providers that return interfaces and not real classes

### ISSUE THREAD

**Issue by dgaedcke** [rrousselGit/riverpod#1308]
I have a package (dependency of my main project) that contains a provider that will be overridden in the host project (provider in the sub-project simply throws ... doesn't return anything) 

I first tried defining that provider using an abstract class (interface), and Riverpod complained that what I was returning was not a valid value for override.

I'd like to learn more about this and understand the issue and any possible workarounds?

I'd also like more details & clarity on this comment from your main docs:

> You should not use StateProvider if:
> 
> your state needs validation logic
> your state is a complex object (such as a custom class, a list/map, ...)
> the logic for modifying your state is more advanced than a simple count++.

Specifically, I'd like to understand WHEN and WHY it won't work if I share an actual object (custom class) ... I've seen it work at least once, and in another thread, you've mentioned that == defaults to reference equality ... so as long as I replace the ENTIRE object, I would think it would work just like a simple data-type.

Can you explain why not??

**Comment by rrousselGit** [comment]
Hello!

Your problem is unclear. Could you share some code and your error?

**Comment by dgaedcke** [comment]
I did have a problem, but I switched the value my provider returned from abstract to concrete, and then I return a subclass (of the concrete class) in my provider.overrideWithValue() and everything works now.  Perhaps it was user error but I don't want to waste your time chasing it since I've got it solved.

But I'm REALLY interested in the documentation question which follows my issue above!
... can you teach us a bit more about WHEN and WHY state providers won't work if the rebuild-logic is based on == and the reference to the state object changes ... that seems like it would work find and so I'm unclear why you tell us we must use StateNotifierProvider???

**Comment by rrousselGit** [comment]
The documentation of StateProvider already explains the reasoning of why StateNotifierProvider is preferred.

What exactly is it that you would like to be improved?

**Comment by rrousselGit** [comment]
Since there's no clear way to make this issue go forward, I'll close it.

If you still have a problem, feel free to open a new one with a more specific request of what you'd like to see changed! :smile:
