### ISSUE TITLE
[Discussion] A new provider for complex object?

### ISSUE THREAD

**Issue by ash0080** [rrousselGit/riverpod#1311]
This idea was inspired by what I read the doc of [binding library](https://pub.dev/documentation/binding/latest/#:~:text=name%20string/constant-,propertyChanged,-(propertyName%3A%20countPropertyName)%3B%0A%20%20%7D%0A%7D)

Currently, basically all riverpod Providers return a single value or a single List, and while there are workarounds to return a complex object (usually a DataModel + .copyWith()), there seems to be a lack of a convenient way to return an observable object. Also such a workaround has some obvious drawbacks, such as performance issues, such as nested references or passing values. and of course the more boilerplate code that emerges.

In many cases, we need a complex object that is observable, rather than a fragmented set of observable single values, such as to implement a ViewModel.

[NotifyPropertyChanged](https://pub.dev/documentation/binding/latest/binding/NotifyPropertyChanged-class.html) gave me some inspiration about the possibility of designing a special Provider that notifies not by updating a value, but by a property name path ( or  path mask? .* ,  .timer.[^is] etc.. )

If it works, I think it will fill the last gap of riverpod and make it easier to create various architectures

**Comment by rrousselGit** [comment]
There's ChangeNotifierProvider if you want.

Having to make a model + a copyWith is not a workaround, that's the expected solution.
Once we have Metaprogramming that should become a lot easier to use

**Comment by ash0080** [comment]
> There's ChangeNotifierProvider if you want.
> 
> Having to make a model + a copyWith is not a workaround, that's the expected solution. Once we have Metaprogramming that should become a lot easier to use

I know that in many cases ChangeNotifier can achieve indistinguishable notifications with ``notifyListeners({})``, and in fact a similar thing can be simulated in stateNotifier, but both lose the opportunity to use .select() for performance optimization.

Currently, there are times when the data source Class itself comes from package, we must then abstract a DataModel class on the data source and then create a new instance each time it is updated, and even then, if there is a nested case, the nested object has to be recreated.It is too tedious and error-prone. And for the nested object processing also divided into two cases, sometimes may not be updated, but if copyWith() has been making deep copy, then the object .select() performance optimization and lost meaning

**Comment by rrousselGit** [comment]
> I know that in many cases ChangeNotifier can achieve indistinguishable notifications with `notifyListeners({})`, and in fact a similar thing can be simulated in stateNotifier, but both lose the opportunity to use .select() for performance optimization.

No it doesn't
ChangeNotifier works with select too.

**Comment by rrousselGit** [comment]
Closing since ChangeNotifierProvider should take care of this

If there's an issue with select, please consider making a new issue specific to that instead :smile:
