### ISSUE TITLE
[2.0.0-dev.5] Is it an intentional change that `.value` access to `AsyncError` now returns null instead of throwing error?

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/riverpod#1336]
**Describe the bug**

Is it an intentional change that `.value` access to `AsyncError` now returns null instead of throwing error?
In version 1, an error was returned, but in version 2, null is returned, making it easier to overlook an unintended error.

I agree with https://github.com/rrousselGit/river_pod/issues/270#issuecomment-938522658 and I think [this change](https://github.com/rrousselGit/river_pod/commit/02d2f52b30ca27b206d7610ddbac01ea97242dc2) in version 1 is good.

I know I can check for errors with `.hasError`, etc., but I would appreciate it if `.value` access throws an exception as well for reducing programming mistakes.
Or even an alias, I would like a property like `.valueXxx` that throws an error on error as in version 1.

**To Reproduce**

```dart
import 'package:riverpod/riverpod.dart';
import 'package:test/test.dart';

void main() {
  final errorValue = AsyncError(42);
  // test(
  //   'AsyncValue.value (v1)',
  //   () {
  //     expect(
  //       () => errorValue.value,
  //       throwsA(42),
  //     );
  //   },
  // );
  test(
    'AsyncValue.value (2.0.0-dev.5)',
    () {
      expect(
        () => errorValue.value,
        isNot(throwsA(42)),
      );
      expect(
        errorValue.value,
        isNull,
      );
    },
  );
}

```

**Expected behavior**

`AsyncError.value` throws the errror.

**Comment by rrousselGit** [comment]
That is because now an AsyncError can have a "value"

If a provider emits a data, then emits loading/error, the data will still be available in "value".


We could still throw though. I'll think about it.

**Comment by rrousselGit** [comment]
Fixed

Note that if you emit a data then an error. AsyncValue.value will not throw. That is because the previous value is conserved, in which case you'll obtain it.

**Comment by mono0926** [comment]
@rrousselGit 

Thank you very much 🙏 
The changes are exactly as I imagined 👍 

> Note that if you emit a data then an error. AsyncValue.value will not throw.

I think it's usually the first time an unexpected error comes in, so I don't think it's a problem 👌
