### ISSUE TITLE
[2.0.0] Behavior when both cacheTime and disposeDelay are specified is unclear.

### ISSUE THREAD

**Issue by Wishmater** [rrousselGit/riverpod#1358]
The new cacheTime and disposeDelay features are really great in a lot of scenarios, and it is clear what they do separately. If cacheTime=10 sec, the provider will be automatically refreshed if read more than 10 seconds after the previous refresh. If disposeDelay=10 sec, the provider will wait 10 seconds after the last listener is removed to dispose itself. This is clear.

Now, if BOTH cacheTime and disposeDelay are set to 10 seconds, which of them will take priority? Will the provider be invalidated/disposed 10 seconds after it is loaded, OR 10 seconds after the last listener is removed?

**Comment by Wishmater** [comment]
Ok, thank you, that makes a lot of sense. So if you set both to 10 sec, only the disposeDelay will really take effect, since the removal of listeners will always happen after the refresh, it will always be disposed 10 seconds after the last listener is removed. CacheTime only really makes sense if it is bigger than disposeDelay, am I correct here?

**Comment by rrousselGit** [comment]
Pretty much, yes.

Generally cacheTime can be set to a few minutes, while disposeDelay is more about a few seconds
