### ISSUE TITLE
Provider body use watch not rebuild

### ISSUE THREAD

**Issue by HXiaoMing** [rrousselGit/riverpod#1367]
**Describe the bug**

testCountProvider body watch countViewModelProvider , the countViewModelProvider value repeat change after 10s, but 
 testCountProvider not rebuild;

**source code :**
```dart
final countViewModelProvider =
    StateNotifierProvider<_CountStateNotifier, CountData>(
        (ref) => _CountStateNotifier());

class CountData {
  final int count;
  final String msg;
  CountData({required this.count, required this.msg});

  CountData copy({int? count, String? msg}) {
    return CountData(count: count ?? this.count, msg: msg ?? this.msg);
  }

  @override
  String toString() {
    return 'count $count';
  }
}

class _CountStateNotifier extends StateNotifier<CountData> {
  final _tag = '_CountStateNotifier';

  _CountStateNotifier() : super(CountData(count: -1, msg: '-1')) {
    repeatCount();
  }

  void repeatCount() {
    Future.delayed(const Duration(milliseconds: 10000), () {
      state = state.copy(count: state.count + 1);
      repeatCount();
    });
  }

  @override
  void dispose() {
    super.dispose();
    print('$_tag dispose');
  }
}


/// **testCountProvider watch countViewModelProvider** 
final testCountProvider = Provider((ref) {
  final value = ref.watch(countViewModelProvider);
  print('testCountProvider change $value');
});





///  **IMWidget** 
class IMWidget extends ConsumerStatefulWidget {
  const IMWidget({Key? key}) : super(key: key);

  @override
  ConsumerState<ConsumerStatefulWidget> createState() {
    return _IMState();
  }
}

class _IMState extends ConsumerState<IMWidget> {
  @override
  void initState() {
    super.initState();
    ref.read(testCountProvider);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter architecture',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('IM'),
        ),
        body: const Text('IM'),
      ),
    );
  }
}
```

**Comment by TimWhiting** [comment]
Nothing is listening to testCountProvider, so it technically does not have to rebuild. Try `ref.watch` or `ref.listen` in the widget instead of `ref.read`.

**Comment by HXiaoMing** [comment]
if change testCountProvider to StateProvider , it will rebuild. why ?
///change to StateProvider

final testCountProvider = StateProvider((ref) {
  final value = ref.watch(countViewModelProvider);
  print('testCountProvider change $value');
});

**Comment by HXiaoMing** [comment]
> if change testCountProvider to StateProvider , it will rebuild. why ? ///change to StateProvider
> 
> final testCountProvider = StateProvider((ref) { final value = ref.watch(countViewModelProvider); print('testCountProvider change $value'); });

if change testCountProvider to StateProvider , it will rebuild. why ?
///change to StateProvider

final testCountProvider = StateProvider((ref) {
final value = ref.watch(countViewModelProvider);
print('testCountProvider change $value');
});

**Comment by HXiaoMing** [comment]
> Nothing is listening to testCountProvider, so it technically does not have to rebuild, I agree this behavior could be confusing. Try `ref.watch` or `ref.listen` in the widget instead of `ref.read`.

if change testCountProvider to StateProvider , it will rebuild. why ?
///change to StateProvider

final testCountProvider = StateProvider((ref) {
final value = ref.watch(countViewModelProvider);
print('testCountProvider change $value');
});

**Comment by TimWhiting** [comment]
I don't know. I know @rrousselGit was interested in changing `ref.read` in the widget tree to listen to providers while the widget is in widget tree which would for sure fix this. However, I agree that your example should work regardless of any future changes. My suggestion was more of a workaround than an explanation of behavior. I think this is actually a bug.

**Comment by HXiaoMing** [comment]
> I don't know. I know @rrousselGit was interested in changing `ref.read` in the widget tree to listen to providers while the widget is in widget tree which would for sure fix this. However, I agree that your example should work regardless of any future changes. My suggestion was more of a workaround than an explanation of behavior. I think this is actually a bug.

as you said, difference behaviors make me confuse.

**Comment by rrousselGit** [comment]
Providers that aren't listened do not rebuild.  
As such this is expected.

What exactly are you trying to do here? Why would you want this provider to rebuild?

**Comment by HXiaoMing** [comment]
> Providers that aren't listened do not rebuild. As such this is expected.
> 
> What exactly are you trying to do here? Why would you want this provider to rebuild?

I have an question why Provider cannot rebuild, but StateProvider can rebuild ？Occur Different behaviors?

I exactly want to do:

**Comment by rrousselGit** [comment]
It's likely a bug due to another issue
