### ISSUE TITLE
Document how to scope providers

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1369]

**Comment by Abdelrahman-Sherif** [comment]
Hi @rrousselGit , is there a way to scope a provider for all "upcoming" widgets in the widget tree?
I tried that using ProviderScope and overriding the provider, but it only worked for one widget, and the screen after that was not reading the overridden value.
By "upcoming" I meant widgets/screens that are pushed on top of the current one.

**Comment by rrousselGit** [comment]
In 2.0, there's a "parent" parameter on ProviderScope

When pushing new routes, make sure that the new route uses a ProviderScope that specifies "parent", where "parent" is the route that pushes this new route.

**Comment by rrousselGit** [comment]
There is technically already a page on the topic of scoping
