### ISSUE TITLE
add fireImmediately argument to WidgetRef.listen

### ISSUE THREAD

**Issue by SamiAlsubhi** [rrousselGit/riverpod#1374]
While this argument is present in `Ref.listen,` somehow it is not available in `WidgetRef.listen`.
Because of the need to capture the first value, I am using `WidgetRef.read` in the `initState`.

**Comment by SamiAlsubhi** [comment]
I resorted to using
```dart
Function? removeListener;
@override
void initState(){
    super.initState()
    removeListener = ref.read(provider).addListener((state){print(state)}, fireImmediately:true);
}

@override
void dispose(){
    super.dispose()
    removeListener?.call()
}

```
Is this a valid workaround to listen without refreshing the widget while also firing immediately?

**Comment by rrousselGit** [comment]
The parameter is not supported. You'll have to use initState yes
