### ISSUE TITLE
ref.listen don't listen to first state of state notifier provider

### ISSUE THREAD

**Issue by thisisyusub** [rrousselGit/riverpod#1381]
### Discussed in https://github.com/rrousselGit/riverpod/discussions/1380

<sup>Originally posted by **thisisyusub** April 26, 2022</sup>
## I want to call some api when provider is initialized. This is the following:
<img width="581" alt="Screen Shot 2022-04-26 at 22 05 36" src="https://user-images.githubusercontent.com/44983544/165363957-e8fcf42e-cf0b-46fa-971e-731f91b28b12.png">

## When I write `await Future.delayed(Duration.zero)` it works, listener working and dialog showing
<img width="703" alt="Screen Shot 2022-04-26 at 22 06 42" src="https://user-images.githubusercontent.com/44983544/165364126-5b5e8f55-8b00-474b-b662-76aff015c3fc.png">

## UI code looks like this:
<img width="615" alt="Screen Shot 2022-04-26 at 22 07 52" src="https://user-images.githubusercontent.com/44983544/165364324-11e2abe0-7685-48b3-a0d8-de6b239ffdad.png">

## But when delay is removed, listener is not working anywhere.
Otherhand, when I listen to `postFrameCallback` it is working as an expected.
<img width="662" alt="Screen Shot 2022-04-26 at 22 11 10" src="https://user-images.githubusercontent.com/44983544/165364869-a8a23acd-2b59-4f55-b8fe-5748b751a4bb.png">

###  How can I handle this situation in other way? I think these solutions are not good one. I think, `ref.watch, ref.listen` should take the latest state and move it to ui link `bloc state management`.

**Comment by rrousselGit** [comment]
Closing since there's already a discussion about it.
