### ISSUE TITLE
Watching a selected state properties does not rebuild the widget when item is removed from the list

### ISSUE THREAD

**Issue by rddewan** [rrousselGit/riverpod#1382]
**Describe the bug**
watching a selected state properties does not rebuild the widget when item is removed from the list

watching for state update :
`final images = ref.watch(createSendWasteControllerProvider.select((value) => value.images));`

remove item from list
```
void removeSelectedImages(int index) {
    state.images.removeAt(index);    
    state = state.copyWith(images: state.images);
        
  }
```

**To Reproduce**
This work perfectly if use 
`final images = ref.watch(createSendWasteControllerProvider);`  or
`final images = ref.watch(createSendWasteControllerProvider).images;`

**Expected behavior**
Widget should rebuild when value is removed for list

**Comment by rrousselGit** [comment]
That's expected. The selected value should be immutable, but you're using mutable state (list)

So:

```dart
state = state.copyWith(images: List.from(state.images)..removeAt(index));
```
