### ISSUE TITLE
Visualising provider dependency chains, transitive dependencies, multiple dependencies

### ISSUE THREAD

**Issue by davebound** [rrousselGit/riverpod#1388]
Hi

My app is getting quite complex. I have about 20 providers, and they all depend on each other in various ways, sometime conditionally.

Understanding these dependency chains is critical to app development, esp to avoid unnecessary processing and widget rebuilds, so I've just manually done the following dependency graph:

![image](https://user-images.githubusercontent.com/18735591/166112256-261c3844-8995-4a0c-a884-9887cfa3974f.png)

Are there any tools available to help with this?

A couple of related questions
- What is best practice for dealing with transitive dependencies e.g. gProvCurrRowlist at the bottom of the diagram watches gProvPageType, which means it will rebuild when gProvPageType changes. But a change to gProvPageType will also cause a ton of other stuff top on which it depends to rebuild (the green area), so it will unnecessarily get rebuilt multiple times.
- Doesn't it make sense to debounce a provider when it depends on multple providers to avoid multiple rebuilds?

Thx

**Comment by rrousselGit** [comment]
Hello!

Such graph could definitely be generated. I'm not aware of a good-enough Dart graph library for doing it though.

One thing I was considering though is to generate a graph using Mermaid syntax like, because Github supports it now:

````
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
````

which renders:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by davebound** [comment]
Thanks Remi, hadn't heard of mermaid - that's pretty cool.

Any thoughts on my other questions?

**Comment by rrousselGit** [comment]
> Doesn't it make sense to debounce a provider when it depends on multple providers to avoid multiple rebuilds?

No, use `select` or `selectAsync` instead.

> What is best practice for dealing with transitive dependencies 

Same thing, use select/selectAsync. They will filter rebuilds to only rebuild what matters

**Comment by rrousselGit** [comment]
As for generating the graph, I'm pushed a WIP project for generating a mermaid graph https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_graph

It's not on pub, but you can clone the project to run it if you want.

**Comment by ejlevin1** [comment]
@rrousselGit I think this will be awesome!  I tried pulling down master and ran that command on my projects lib directory and it shows this:

```
Analyzing /Users/myusername/Development/myproject/mobile/lib ...
Unhandled exception:
Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      ProviderDependencyVisitor.visitArgumentList (package:riverpod_graph/src/analyze.dart:444:46)
#2      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:398:50)
#3      InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7673:19)
#4      RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:1266:10)
#5      ProviderDependencyVisitor.visitInstanceCreationExpression (package:riverpod_graph/src/analyze.dart:580:20)
#6      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:15)
#7      ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11703:18)
#8      RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1582:10)
#9      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11699:50)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9721:20)
#11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1259:17)
#12     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:852:10)
```

Any thoughts?

**Comment by IanNelson159** [comment]
@ejlevin1 were you able to solve this issue?

**Comment by Doldrums** [comment]
@rrousselGit Got same problem here

**Comment by SylvainHocq** [comment]
@rrousselGit I think this will be awesome too !
I install it in the global dart cache
  
And when I run on my project,  I've got this error : 


`Unhandled exception:
Unsupported operation: unknown expression zoiListProviderWithArgs SimpleIdentifierImpl
#0      parseProviderFromExpression (package:riverpod_graph/src/analyze.dart:753:3)
#1      ConsumerWidgetVisitor.visitMethodInvocation (package:riverpod_graph/src/analyze.dart:369:32)
#2      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:12156:50)
#3      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18473:19)
#4      RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1794:10)
#5      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:18468:50)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12915:20)
#7      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18597:16)
#8      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1800:10)
#9      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:18591:15)
#10     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18653:19)
#11     RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1806:10)
#12     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:18649:15)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12915:20)
#14     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2029:17)
#15     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:878:10)
#16     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:2025:50)
#17     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1985:12)
#18     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:884:10)
#19     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1977:50)
#20     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11979:10)
#21     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1400:10)
#22     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11971:50)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12915:20)
#24     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2918:13)
#25     analyze (package:riverpod_graph/src/analyze.dart:70:14)
<asynchronous suspension>`
