### ISSUE TITLE
Add event to StateNotifier to execute on state change

### ISSUE THREAD

**Issue by galimpic** [rrousselGit/riverpod#1391]
**Is your feature request related to a problem? Please describe.**
Additional logic is often needed when state is directly changed from outside (or inside) `StateNotifier`.

**Describe the solution you'd like**
A  method that fires automatically when state property is set.

**Describe alternatives you've considered**
A workaround is to have a `void setState(T value) { <custom logic here>; state = value;}` method and call it instead of desired `state = value` with a custom event method implemented.

**Comment by rrousselGit** [comment]
You can override the setter or updateShouldNotify

There's also ref.listenSelf (although there's an issue in the dev release about it not listening to the correct value).

**Comment by galimpic** [comment]
Overriding the setter worked perfectly, thank you, I didn't think of that before I rushed to ask. Wow, 2 min response time, that is really extraordinary! You can retag this as a general question if you prefer.
