### ISSUE TITLE
autoDispose StateNotifierProvider is call when read

### ISSUE THREAD

**Issue by rddewan** [rrousselGit/riverpod#1395]
**Describe the bug**
I am calling `ref.read` to make a API call before navigating from Screen A to Screen B on button tab but when i navigate to Screen B autoDispose  on StateNotifierProviders was called which made it unusable , Screen A and B both depends on different StateNotifierProviders

**To Reproduce**

If removed autoDispose on StateNotifierProviders it work without issue

**Expected behavior**
`ref.read` should not autoDispose the StateNotifierProviders

**Comment by rrousselGit** [comment]
That's expected. If the provider isn't listened, it'll get disposed

Since it isn't (at least until the new page appears), then it is disposed.

**Comment by rddewan** [comment]
which means we need to pass `arg` from Screen A to Screen B to make it work, I thought with Riverpod  we don't have to pass  `arg` anymore

**Comment by rrousselGit** [comment]
Riverpod has various solutions to this. For example you can specify `disposeDelay`/`cacheTime` if you are using the dev release of 2.0

**Comment by scopendo** [comment]
What's the latest thinking here given that these didn't make it it into Riverpod 2.x?  Is it to implement cacheTime ourselves per the guidance given on https://github.com/rrousselGit/riverpod/issues/1664#issuecomment-1257177901

**Comment by rrousselGit** [comment]
There are still plans for those. They only have been delayed
