### ISSUE TITLE
2.0.0-dev.6 issue: Tried to read a provider from a ProviderContainer that was already disposed

### ISSUE THREAD

**Issue by s9th** [rrousselGit/riverpod#1400]
**Describe the bug**
After updating to 2.0.0-dev.6 the error in title occurs for top-level UncontrolledProviderScope when an underlying ProviderScope used for overriding provider(s) is disposed. This behavior started with dev.6 and is not present in dev.5

**To Reproduce**

1. Have a ProviderScope inside widget tree with an overriden auto-dispose provider over a separate screen
2. Navigate to said screen
3. Navigate back - error occurs
![image](https://user-images.githubusercontent.com/15362801/167591392-adb3bbca-c096-41bb-8796-d389133047bb.png)

 ```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final container = ProviderContainer(observers: []);

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const App(),
    ),
  );
}

class Item {
  const Item();
}

final localeProvider = Provider((ref) {
  return const Locale('en', 'US');
});

final createItemProvider =
    StateProvider.autoDispose<Item>(((ref) => throw UnimplementedError()));

class App extends ConsumerWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final locale = ref.watch(localeProvider);

    return MaterialApp(
      home: const HomePage(),
      locale: locale,
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(
              context,
              MaterialPageRoute(
                  builder: (BuildContext context) => ProviderScope(
                        overrides: [
                          createItemProvider.overrideWithProvider(
                            StateProvider.autoDispose(
                              (ref) => const Item(),
                            ),
                          )
                        ],
                        child: const CreateItem(),
                      )));
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

class CreateItem extends StatelessWidget {
  const CreateItem({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
    );
  }
}

```

**Expected behavior**
Error doesn't occur

**Comment by rrousselGit** [comment]
Hello!

Could you update your snippet such that it compiles? There are widgets that don't exist in there

**Comment by s9th** [comment]
I tried to minimize the code of my app for this issue to be reproduced, but now I cannot reproduce it minimized code (still reproduced in my app). I'm gonna try and recreate it on a completely new project and let you know when I encountered it and under which conditions.

Thanks.

**Comment by s9th** [comment]
I did find that in my app it actually throws here
![image](https://user-images.githubusercontent.com/15362801/167615530-b26332a0-b8c9-4256-a67b-41b5738a7c5d.png)

Don't know if that helps it or not. I will continue digging.

**Comment by s9th** [comment]
I still cannot reproduce the issue on minimal code. I've updated it so it does compile just to be prudent, but it's not reproducible there.

However, I found in my app that if I add disposeDelay of even 1 millisecond to the underlying ProviderScope, the issue does not appear. But it's strange that wasn't the case in dev.5.

Unfortunately I cannot share my app code because of the NDA. If there is a way to show it without publishing it here, please let me know. @rrousselGit

**Comment by rrousselGit** [comment]
I'd love to help. But without a clear way to reproduce the problem, it's hard for me to do anything.

**Comment by s9th** [comment]
Understandable.
For what it's worth, I managed to narrow it down to mayNeedDispose() being executed in auto_dispose.dart, but I have no idea why it's being executed when there are still listeners in the container.

**Comment by s9th** [comment]
if this helps you, this is the debug snapshot of mayNeedDispose call
First one doesn't throw an error
![image](https://user-images.githubusercontent.com/15362801/167672022-b21428bf-a66d-4aec-b63e-abef87860227.png)
Immediately after it throws one 
![image](https://user-images.githubusercontent.com/15362801/167672120-f3159f0c-eedf-4eb8-ad2f-1746d1334ab8.png)

**Comment by s9th** [comment]
Unfortunately, I lack the skill to determine the root cause on my end. For the time being I rolled back to dev.5 to avoid this. I hope someone more skillful than me will bring this up in the future with accurate STR.

**Comment by s9th** [comment]
@rrousselGit 
I went backwards and decided to check riverpod commits. I managed to pinpoint the issue to this change
https://github.com/rrousselGit/riverpod/commit/6c9535c2f9a2d8d1b9f11ef4e2007d12ed844966

I am not sure exactly why or how, but when I readded the !element.mounted condition in pub cache and rebuilt the app, the issue stopped

**Comment by rrousselGit** [comment]
Could you maybe tell me which line is causing the exception and how that exception is triggered?

Is it a Consumer reading a widget on pressed? A provider reading another provider inside onDispose? ...

**Comment by s9th** [comment]
I basically navigate from a page with an overridden autodispose provider at the top back to the main page (via a BackButton widget on the appbar). There are no rebuilds on the main page at all. This is the stack trace I get.
![image](https://user-images.githubusercontent.com/15362801/168042764-987563b8-a9eb-438e-ad82-1e0a8225352b.png)

If it helps, my MaterialApp widget looks like this, but I tried the same structure in the code to reproduce and it didn't help.
![image](https://user-images.githubusercontent.com/15362801/168042983-a67ead8d-f88d-43ce-893a-7307ee2c91e7.png)

For now, the workaround seems to be adding a 1 millisecond disposeDelay to top-level ProviderContainer, so maybe there is a race condition that results in it being disposed.

**Comment by rrousselGit** [comment]
What's troubling to me is, I don't see how that's possible at all.

Both ProviderContainer and _Scheduler have a dispose check and do nothing when they are disposed.

I've tried a few scenarios but can't reproduce it.
So you are likely doing special that bypasses those checks

**Comment by s9th** [comment]
I was bashing my head the whole day yesterday against this, but I didn't have much progress.
What's notable is that I have two providers being overridden - one for items in the list and one for create item screen. The issue reproduces in both scenarios when I either go to item details and back or open create dialog and go back

**Comment by appano1** [comment]
@s9th Did you override `AutoDisposeProvider`..?

In my case, the error occurred after overrode `AutoDisposeStateNotifierProvider`.

**Comment by appano1** [comment]
Here is my example code

```dart
void main() {
  runApp(const ProviderScope(child: App()));
}

final counterProvider = StateNotifierProvider.autoDispose<CounterNotifier, int>(
  (ref) => CounterNotifier(),
);

class CounterNotifier extends StateNotifier<int> {
  CounterNotifier() : super(0);

  void increase() => ++state;
  void decrease() => --state;
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: InitialPage(),
    );
  }
}

class InitialPage extends ConsumerWidget {
  const InitialPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.watch(counterProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Initial Page')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () => Navigator.pushAndRemoveUntil(
                context,
                MaterialPageRoute(builder: (context) => const HomePage()),
                (route) => false,
              ),
              child: const Text('Go to Home Page'),
            ),
          ],
        ),
      ),
    );
  }
}

class HomePage extends HookConsumerWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final controller = usePageController();
    final pageIndexNotifier = useState(0);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: PageView(
        controller: controller,
        onPageChanged: (index) => pageIndexNotifier.value = index,
        children: const [
          Page1(),
          Page2(),
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: pageIndexNotifier.value,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'HOME',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'SETTINGS',
          ),
        ],
        onTap: (index) {
          controller.animateToPage(
            index,
            duration: const Duration(milliseconds: 300),
            curve: Curves.easeInOut,
          );
        },
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      overrides: [counterProvider],
      child: Consumer(builder: (_, ref, __) {
        final number = ref.watch(counterProvider);
        return Center(
          child: Text(
            number.toString(),
          ),
        );
      }),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      overrides: [counterProvider],
      child: Consumer(builder: (_, ref, __) {
        final number = ref.watch(counterProvider);
        return Center(
          child: Text(
            number.toString(),
          ),
        );
      }),
    );
  }
}
```

**Exception**
```bash
════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building UncontrolledProviderScope(dirty):
Bad state: Tried to read a provider from a ProviderContainer that was already disposed

The relevant error-causing widget was
ProviderScope
lib/main.dart:6
When the exception was thrown, this was the stack
#0      ProviderContainer.readProviderElement
package:riverpod/…/framework/container.dart:474
#1      ProviderContainer._disposeProvider
package:riverpod/…/framework/container.dart:377
#2      _ProviderScheduler._performDispose
package:riverpod/…/framework/scheduler.dart:85
#3      _ProviderScheduler._task
package:riverpod/…/framework/scheduler.dart:42
#4      _UncontrolledProviderScopeElement.build
package:flutter_riverpod/src/framework.dart:382
#5      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4754
#6      Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#7      BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2659
#8      WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#9      RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:363
#10     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#11     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1081
#12     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:995
#16     _invoke (dart:ui/hooks.dart:151:10)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#18     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by Ali1Ammar** [comment]
i have same error 
- it happens  with  StateProvider/StateNotifierProvider    ( doesn't happens with Provider / FutureProvider)
- only when using autoDispose
- the error happens when the page with 'ProviderScpoe' get dispose ( Navigate back)
- same with overrideWithProvider or overrideWithValue

code

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main(List<String> args) {
  runApp(const MyWidget());
}

final testProvider = StateProvider.autoDispose((_) => 'test');

class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(home: Builder(builder: (context) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('Home'),
          ),
          body: ElevatedButton(
              child: const Text("go"),
              onPressed: () {
                Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => const OtherPage()));
              }),
        );
      })),
    );
  }
}

class OtherPage extends StatelessWidget {
  const OtherPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
        overrides: [testProvider],
        child: Consumer(
          builder: (context, ref, _) {
            final txt = ref.watch(testProvider);
            return Scaffold(
              appBar: AppBar(),
              body: Text(txt),
            );
          },
        ));
  }
}
```

**Comment by s9th** [comment]
@appano1 yes, correct

**Comment by rich-j** [comment]
Yes, upgrading to either `2.0.0-dev.6 or .7` breaks for us. We did find a workaround - add to the nested `ProviderScope` a `disposeDelay: Duration(seconds: 1),`. This appears to *temporarily* mask this issue until it is fixed.

**Comment by ablbol** [comment]
I am using hooks_riverpod: ^2.0.0-dev.7 and running into the same exact problem.  When I downgraded to ^1.0.4, the problem disappeared.

**Comment by rrousselGit** [comment]
I'll look into this and the breaking Freezed issue tomorrow.

**Comment by rrousselGit** [comment]
Thanks for your example @Ali1Ammar. I'm able to easily reproduce the issue

Will fix it as soon as I understand the issue.
