### ISSUE TITLE
Can't view provider tab in devtools

### ISSUE THREAD

**Issue by msarkrish** [rrousselGit/riverpod#1409]
**Describe the bug**
My app is using latest stable riverpod and latest devtools.
I can't view provider tab in devtools.
I'm using Flutter 2.10.5 versions

**Expected behavior**
Displaying provider tab in devtools

**Comment by rrousselGit** [comment]
There is no such thing yet with Riverpod.

**Comment by msarkrish** [comment]
@rrousselGit 

I'm mentioning this feature https://invertase.io/blog/state-inspector-devtool

**Comment by rrousselGit** [comment]
It isn't available yet

**Comment by msarkrish** [comment]
Is Devtool feature will be available with stable Riverpod 2.0 release @rrousselGit ?
