### ISSUE TITLE
How can we refresh loading in 2.0.0 dev?

### ISSUE THREAD

**Issue by imprecis** [rrousselGit/riverpod#1411]
In 2.0.0 there was a change that when we refresh a provider, and it had already finished loading before, it won't refresh loading state (won't show loading again).

How can we refresh the loading when we refresh the provider? In most cases, not refreshing loading is good, but in some scenarios it's easier to give feedback to the user that the data has been refreshed.

**Comment by TimWhiting** [comment]
There are `AsyncValue.isRefreshing` and `AsyncValue.isLoading` booleans. 
isRefreshing is true any time the value is refreshed after the first time. isLoading is true even the first time.

**Comment by imprecis** [comment]
Hello, thank you for your reply. Do I need to declare it like this, or is it a better way:

```
 !provider.isRefreshing
              ? provider.when(
                  data: (provider) => someData,
                  error: (err, stack) => someError,
                  loading: () => someLoading
                )
              : someLoading,
```

**Comment by rrousselGit** [comment]
If you want to use "when", you can use "unwrapPrevious"

ref.watch(p).unwrapPrevious().when(
...
)

**Comment by rrousselGit** [comment]
Alternatively, you can use `family` to pass some values instead of `ref.watch`

When `family` parameters change, you'll get `AsyncLoading` instead of `AsyncData` with the previous value.
So going from:

```dart
ref.watch(myFamily(42))
```
to
```dart
ref.watch(myFamily(21))
```

will not show the data of `myFamily(42)` while `myFamily(21)` is loading
