### ISSUE TITLE
ref merges the previous and next AsyncValue of a StateNotifier

### ISSUE THREAD

**Issue by lotusgate** [rrousselGit/riverpod#1414]
**Describe the bug**
Maybe this behaviour is intended, but it seems weird to me. I have a `StateNotifier<AsyncValue>`, where its state starts of as `AsyncLoading` and is later changed to `AsyncData`. I noticed that when I refresh/invalidate the provider (with the `FloatingActionButton` in the given example), the value that I read in the next build isn't `AsyncLoading`, but `AsyncData` with the `isLoading` field set to true.

**To Reproduce**
`riverpod 2.0.0-dev.7`
<details>
<summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() => runApp(const ProviderScope(child: MaterialApp(home: Home())));

class MyNotifier extends StateNotifier<AsyncValue<void>> {
  MyNotifier() : super(const AsyncValue.loading()) {
    _init();
  }

  Future<void> _init() async {
    print('state $state');
    state = await AsyncValue.guard(() async {
      await Future.delayed(const Duration(seconds: 2));
      return;
    });
    print('state $state');
  }
}

final provider = StateNotifierProvider<MyNotifier, AsyncValue<void>>(
  (ref) {
    print('create');
    return MyNotifier();
  },
);

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Consumer(
          builder: (context, ref, child) {
            print('widget ${ref.watch(provider)}');

            return ref.watch(provider).when(
                  loading: () => const Text('Loading'),
                  error: (_, __) => const Text('Error'),
                  data: (_) => const Text('Data'),
                );
          },
        ),
      ),
      floatingActionButton: Consumer(
        builder: (context, ref, _) => FloatingActionButton(
          onPressed: () => ref.refresh(provider),
        ),
      ),
    );
  }
}
```
</details>

**Expected behavior**
I was expecting to get `AsyncLoading`, which is supposed to be the state of the new `StateNotifier` instance. The current behaviour may seem somewhat logical, as this is a "refresh" and it could make sense for a `FutureProvider`, but in the `StateNotifier`, where I can define the logic I need, this seems more like a weird quirk.
Is this intended or is it a bug?
If it's intended, perhaps the documentation on `refresh` needs to be reworded? It currently says: "Forces a provider to re-evaluate its state immediately, and return the created value.", but the new value should be `AsyncLoading` then.

**Comment by rrousselGit** [comment]
This is indeed intended. 

That's a behavior of AsyncValue. Your consumers can ignore this by using `value.unwrapPrevious()`
