### ISSUE TITLE
Widget requiring the package `riverpod_hooks` and extending `HookConsumerWidget` gets undefined error for reference to `useState` or `useMemoized` within its build function

### ISSUE THREAD

**Issue by dorontal** [rrousselGit/riverpod#1419]
**Describe the bug**
I have a widget that extends `HookConsumerWidget`. Its build method calls `useState()` and `useMemoised()`. The `pubspec.yaml` file includes just the `hooks_riverpod` package.

In my widget file, if I only have this import
```dart
import 'package:hooks_riverpod/hooks_riverpod.dart';
```
then the functions `useState()` or `useMemoized()` become undefined in red and VSCode complains that they are undefined - I believe this is a bug.

I have a workaround: If you add the import
```dart
import 'package:flutter_hooks/flutter_hooks.dart';
```

then the "undefined" error messages described above go away, but the added import line gets a blue-squiggly-line under it warning that if we are importing a package we should have that package listed in the `pubspec.yaml` - it is not there currently, for obvious reasons (it's not supposed to be there if `hooks_riverpod` is there already, because `hooks_riverpod` subsumes `flutter_hooks`).  

**To Reproduce**

1) Create a widget that extends `HookConsumerWidget` 
2) Make sure the widget you create references `useState()` or `useMemoized()` in its build method 
3) In `pubspec.yaml`, and in the widget file's imports section, include `hooks_riverpod` but not `flutter_hooks`

**Expected behavior**
I expected the import of `hooks_riverpod` to define `useState()` and `useMemoized()` inside a widget that extends HookConsumerWidget.

I expected not to ever have to import `flutter_hooks` if I am importing `riverpod_hooks` - i.e, I expected all things that are defined by `flutter_hooks` to be subsumed by `riverpod_hooks`.

**NOTE**: Using Flutter 3.0.0, `hooks_riverpod` 1.0.4, and other packages are up to date.

**Comment by rrousselGit** [comment]
These are from a separate package: flutter_hooks

you need to import both hooks_riverpod and flutter_hooks

**Comment by dorontal** [comment]
Sure, that's what I did. It works fine if you  import both packages, but it's not 100% fine because of this:

If you import both packages, then you get a complaint / warning for the package named `flutter_hooks` - that it is not in `pubspec.yaml`. It is available because `hooks_riverpod` uses it but the warning says that it is bad style to import packages that are used "internally" by another package. 

To avoid this warning, you have to import both libraries in your `pubspec.yaml`.

But then it brings into question whether we need `hooks_riverpod` at all - might as well use `riverpod` with `flutter_hooks` if both packages have to be in `pubspec.yaml`

I just wanted to bring this to your attention - I believe that this warning only showed up recently after some upgrades to either Flutter or `flutter_lints`.

**Comment by rrousselGit** [comment]
You definitely should have both in your pubspec.
That's what the install doc tells you to do https://riverpod.dev/docs/getting_started


You need hooks_riverpod. Without it, you don't have a HookConsumerWidget.

**Comment by abdullah-cse** [comment]
1️⃣  In document v2, the command is `flutter pub add hooks_riverpod dev:custom_lint dev:riverpod_lint riverpod_annotation dev:build_runner dev:riverpod_generator`  add only **hooks_riverpod**  not **flutter_hooks**

![image](https://github.com/rrousselGit/riverpod/assets/58176575/a929ba24-fde7-4c69-8f33-303ab17ecd90)


2️⃣ In document v1,  it says that only **hooks_riverpod** is sufficient to deal with **flutter_hooks** and **riverpod** together.


![image](https://github.com/rrousselGit/riverpod/assets/58176575/34a00262-6d26-41c7-ac37-92dd6d5da1df)

**Comment by AhmedLSayed9** [comment]
@abdullah-cse The switch is enabled :)

**Comment by abdullah-cse** [comment]
@AhmedLSayed9 Yes, I would like to use **flutter_hooks && riverpod.** . For that if I use **hooks_riverpod**  and extend **HookConsumerWidget**,  **useState** isn't recognized by Flutter.

But if I use `import 'package:flutter_hooks/flutter_hooks.dart';` then **useState** is recognized, flutter_lints complain 


⚠"The imported package 'flutter_hooks' isn't a dependency of the importing package.Try adding a dependency for 'flutter_hooks' in the 'pubspec.yaml' file."

**Comment by AhmedLSayed9** [comment]
> 1️⃣ In document v2, the command is `flutter pub add hooks_riverpod dev:custom_lint dev:riverpod_lint riverpod_annotation dev:build_runner dev:riverpod_generator` add only **hooks_riverpod** not **flutter_hooks**

Ah I got confused by this. I think you meant to say `hooks_riverpod and riverpod_generator`.

I agree. I think it's reasonable to add `flutter_hooks` too.

**Comment by rrousselGit** [comment]
Good catch, it was missing. I've added it
