### ISSUE TITLE
ref.onDispose is also called when a provider depends on some other provider and a new create is called.

### ISSUE THREAD

**Issue by splangi** [rrousselGit/riverpod#1420]
**Describe what scenario you think is uncovered by the existing examples/articles**
ref.onDispose is also called when a provider depends on some other provider and a new create is called. I think current documentation does not cover this. 

**Describe why existing examples/articles do not cover this case**
Currently the documentation suggests that onDispose is called when the autoDispose modified provider is no longer listened or the providerContainer itself is being destroyed. I was a bit confused when it suggested that onDispose is called on these two cases. I expected that there is means to dispose of old value when create is called again. 

> This typically happen when a provider marked with `.autoDispose` is no-longer used, or when [ProviderContainer.dispose] is called.

**Additional context**
Below is the code i tested this behaviour:

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

class Pseudo with ChangeNotifier {

  int _value;

  Pseudo(this._value);

  set value(int newValue){
    _value = newValue;
    notifyListeners();
  }

}


final parentProvider = ChangeNotifierProvider((ref) => Pseudo(0));
final childProvider = Provider((ref){

  print("create called");

  final pseudo = ref.watch(parentProvider);

  ref.onDispose(() {
    print("onDispose called");
  });

  return pseudo._value;
});


void main() {

  test("ProviderTest", () {
    final container = ProviderContainer();

    final pseudo = container.read(parentProvider);

    container.read(childProvider);

    pseudo.value = 1;

    container.read(childProvider);

    pseudo.value = 2;

    container.read(childProvider);

    pseudo.value = 3;

    container.dispose();
  });

}
```

And the output of this code:

```
Testing started at 10:00 ...

create called
onDispose called
create called
onDispose called
create called
onDispose called

```

This actually is the behaviour I was looking for, so I hope this is not a bug.

**Comment by fpoppinga** [comment]
> This actually is the behaviour I was looking for, so I hope this is not a bug.

We are facing the same behavior, but hope that this is a bug, because this is not the behavior we are looking for.

**Comment by rrousselGit** [comment]
That's indeed expected. I'll add it to the doc

**Comment by fpoppinga** [comment]
Hi @rrousselGit, thanks for the clarification. 

So maybe as a follow-up question: Is there a way to register a callback which is only called, when the provider is actually disposed?

Alternatively probably something as suggested in #1404 would address my requirements.

**Comment by rrousselGit** [comment]
What does "actually disposed" mean?

I also don't see how #1404 relates to this discussion.
