### ISSUE TITLE
Clarify behaviour regarding family (when same parameter is entered a second time)

### ISSUE THREAD

**Issue by manuel-plavsic** [rrousselGit/riverpod#1421]
**Describe what scenario you think is uncovered by the existing examples/articles**
When using a family provider, the documentation explains that the value returned is sort of "dynamic" because it depends also on the argument sent. This made me wonder if I use provider.family with the same argument multiple times, what happens? will it return a new instance or the same value that was already returned the first time that provider was read? I know the website states _"Providers are a complete replacement for patterns like Singletons, Service Locators, Dependency Injection or InheritedWidgets."_, however, especially for a beginner, a clearer explanation would be helpful.

**Questioned behaviour quickly tested on Dart**
```dart
import 'package:dartx/dartx.dart';
import 'package:riverpod/riverpod.dart';

void main(List<String> args) {
  // This object is where the state of our providers will be stored.
  final container = ProviderContainer();

  // Thanks to "container", we can read our provider.
  final value = container.read(myClassProvider);

  // Again
  final value2 = container.read(myClassProvider);

  print(value.hashCode);
  print(value2.hashCode);
  print(MyClass(3, 3).hashCode);

  print('');

  final famValue = container.read(myClassFamilyProvider(Pair(9, 9)));
  print(famValue.hashCode);
  final famValue2 = container.read(myClassFamilyProvider(Pair(9, 9)));
  print(famValue2.hashCode);
  final famValue3 = container.read(myClassFamilyProvider(Pair(1, 9)));
  print(famValue3.hashCode);

  print('');

  final ignoredFamValue =
      container.read(myClassIgnoredFamilyProvider(Pair(9, 9)));
  print(ignoredFamValue.hashCode);
  final ignoredFamValue2 =
      container.read(myClassIgnoredFamilyProvider(Pair(9, 9)));
  print(ignoredFamValue2.hashCode);
  final ignoredFamValue3 =
      container.read(myClassIgnoredFamilyProvider(Pair(1, 9)));
  print(ignoredFamValue3.hashCode);

  print('');

  final MyClass myClassInstance1 = MyClass(8, 4);
  final MyClass myClassInstance2 = MyClass(8, 4);

  final instanceFamValue =
      container.read(myClassInstanceFamilyProvider(myClassInstance1));
  print(instanceFamValue.hashCode);
  final instanceFamValue2 =
      container.read(myClassInstanceFamilyProvider(myClassInstance1));
  print(instanceFamValue2.hashCode);
  final instanceFamValue3 =
      container.read(myClassInstanceFamilyProvider(myClassInstance2));
  print(instanceFamValue3.hashCode);
}

final myClassProvider = Provider<MyClass>((ref) {
  return MyClass(3, 3);
});

final myClassFamilyProvider = Provider.family<MyClass, Pair>((ref, pair) {
  return MyClass(pair.first, pair.second);
});

final myClassIgnoredFamilyProvider =
    Provider.family<MyClass, Pair>((ref, pair) {
  return MyClass(3, 3); // pair is ignored
});

// Instances are checked.
final myClassInstanceFamilyProvider =
    Provider.family<MyClass, MyClass>((ref, myClass) {
  return myClass;
});

class MyClass {
  MyClass(this.field1, this.field2);
  int field1;
  int field2;
}
```

**Output**
706818280
706818280
65704687

263054036
263054036
896184068

665591436
665591436
852379949

499118682
499118682
280657750

**Comment by UCetinkaya94** [comment]
@manuel-plavsic you have to override the `==` operator and `hashCode` of `MyClass`, otherwise your instances will be treated as being different, even if they hold the same values. Alternatively you can use the [equatable package](https://pub.dev/packages/equatable)

**Comment by manuel-plavsic** [comment]
@UCetinkaya94 Thanks, that was my guess as well, which was confirmed after testing with Dart. My point is just that it might be very helpful for other people as well if this behavior is explicitly mentioned in the docs.

**Comment by UCetinkaya94** [comment]
@manuel-plavsic it is mentioned in the docs 😅 https://riverpod.dev/docs/concepts/modifiers/family#parameter-restrictions

**Comment by manuel-plavsic** [comment]
@UCetinkaya94 You are right, it is mentioned. Those lines are also pretty clear 😅 I don't how I managed to not see that 😂
