### ISSUE TITLE
Add option to StreamProvider to buffer messages for new listeners

### ISSUE THREAD

**Issue by Norbert515** [rrousselGit/riverpod#1432]
**Is your feature request related to a problem? Please describe.**

In an architecture where the data is the single source of truth, it is common to derive app state from one or multiple streams. Streams are often necessary because the data might originate from Firebase.

### Consider the following example:

```dart
import 'dart:async';
import 'package:riverpod/riverpod.dart';
import 'package:rxdart/rxdart.dart';

var firebaseController = StreamController<DateTime>();
/// Mock of a firebase document/ collection snapshots reference
final firebaseStreamProvider = StreamProvider<DateTime>((ref) {
  firebaseController.add(DateTime.now());
  return firebaseController.stream;
});


final greeterProviderProvider3 = StreamProvider<String>((ref) {
  return ref.watch(firebaseStreamProvider.stream).map((e) {
    return 'Hi, the time is ${e.toString()}';
  });
});


final norbertGreeterProvider = StreamProvider<String>((ref) {
  return ref.watch(greeterProviderProvider3.stream).map((msg) {
    return 'For Norbert: $msg';
  });
});

final remiGreeterProvider = StreamProvider<String>((ref) {
  return ref.watch(greeterProviderProvider3.stream).map((msg) {
    return 'For Remi $msg';
  });
});

void main() {
  var providerContainer = ProviderContainer();

  providerContainer.listen(remiGreeterProvider, (_, val) {
    /// Prints AsyncData<String>(value: For Remi Hi, the time is 2022-05-30 15:23:46.351022)
    print(val);
  });

  Future.delayed(const Duration(seconds: 1)).then((value) {
    providerContainer.listen(norbertGreeterProvider, (_, val) {
      /// Never prints anything
      print(val);
    });
  });

  Future.delayed(const Duration(seconds: 2)).then((value) {
    firebaseController.close();
  });
}

```

A base `StreamProvider` is augmented with different transformations (these transformations could be more complex, such as a combination of multiple streams using flatMap or other stream features). If multiple clients rely on the a same base `StreamProvider` the following issue occures:

1. The first provider listens to the original (firebase) stream provider
2. A new stream is created, and one or more events (loading -> data) are added
3. The stream is cached (converted into a broadcast stream) - subsequent listeners listen to the same stream
4. Next listener is registered, the stream doesn't currently hold any value. In the case of firebase, it doesn't fire any event unless the data in the database changes.
5. Other listeners do not receive any value

This is especially problematic when nesting StreamBuilders/ ref.watch(streamProvider.stream) because the second call to a StreamProvider that depends on the same as the first one never receives any data!

**Describe the solution you'd like**

There should be a Provider or option to buffer the last value of new listeners. Currently, this type of architecture doesn't work in combination with firebase.

This would effectively convert the `Stream<T>` to a `ValueStream<T>` from RX. Because Riverpod buffers the returned Stream as a `BroadcastStream` I don't see a reason why this wouldn't work from a technical perspective.

**Describe alternatives you've considered**

Currently, the only alternative I could think of are:

- Don't use Riverpod for any logic which is a Stream or transitively depends on a Stream (which is most of the state in an App where the database is the single source of truth)

- Bridge the stream into a synchronous world (listening to the Stream and putting it into a StateNotifier) -> this breaks the ability to await a value using `ref.read(myStreamProvider.future)` and would introduce tremendous complexity into actions where a value is needed.

---
If this is something that could result in a PR, I'd be happy to contribute!

**Comment by Norbert515** [comment]
Just say the 2.0 release, I suppose 

```
Breaking After a provider has emitted an AsyncValue.data or AsyncValue.error, that provider will no longer emit an AsyncValue.loading.
Instead, it will re-emit the latest value, but with the property AsyncValue.isRefreshing to true.
```

should solve exactly this, right?

**Comment by rrousselGit** [comment]
.stream isn't meant to be used at broad scale. It's there for the sake of it, but it's pretty much never used besides for testing

If you want to chain async providers, you likely want to use await ref.watch(provider.future).



> ```dart
> 
>   Future.delayed(const Duration(seconds: 1)).then((value) {
>     providerContainer.listen(norbertGreeterProvider, (_, val) {
>       /// Never prints anything
>       print(val);
>     });
>   });
> ```

Maybe you're looking for fireImmediately: true?

container.listen(provider, handler, fireImmediately: true)

This calls the listener with the latest value. Otherwise the listener is only called on change, and since the value never changes after this listener is added, it's never called.



Overall, you need to keep in mind that Riverpod uses a mental model different than that of Streams. In Riverpod, there's no event per say.  It's only a value which changes over time.
