### ISSUE TITLE
StreamProvider chain syntax sugar

### ISSUE THREAD

**Issue by Norbert515** [rrousselGit/riverpod#1433]
**Is your feature request related to a problem? Please describe.**

Currently, chaining `StreamProviders` together is pretty cumbersome (which it doesn't have to be!). 
Riverpod has a very declarative and reactive way of combining data, the same could be achieved for `StreamProviders`

### Consider the following example:

```dart
import 'dart:async';
import 'package:riverpod/riverpod.dart';
import 'package:rxdart/rxdart.dart';

final timerProvider= StreamProvider<DateTime>((ref) async* {
  while(true) {
    yield DateTime.now();
    await Future.delayed(Duration(seconds: 1));
  }
});

/// Very verbose, complexity increases exponentially with additional streams
final greeterProvider = StreamProvider<String>((ref) {
  var controller = StreamController<String>();
  ref.watch(timerProvider.stream).listen((event) {
    controller.add( 'Hi from VERBOSE approach, the time is ${event.toString()}');
  });
  return controller.stream;

});

/// Currently the best option,
///
/// This doesn't feel very Riverpod-ish, this is pretty much a standart RX archecture
/// because you need to understand the complexity of streams to implement more complex
/// data interactions (such as flatMap, switchMap, etc.)
final greeterProvider2 = StreamProvider<String>((ref) {
  return ref.watch(timerProvider.stream).map((e) {
    return 'Hi from RX approach, the time is ${e.toString()}';
  });
});

/// Cleanest and easiest to understand -> Currently not supported
/// because if the parent stream [timerProvider] emits, a new stream is created
/// for [greeterProvider].
///
/// This approach would allow for very easy data access, and more importantly, way
/// easier debugging than native streams.
final greeterProvider3 = StreamProvider<String>((ref) async* {

  /// Potential for lots of syntax sure (such as require data which only executes
  /// following lines if data is available, early interrupt can be done with an
  /// exception that is caught before propagation)
  var data = ref.watch(timerProvider).asData;

  if(data != null) {
    yield 'Hi from PROPOSED approach, the time is ${data.value.toString()}';
  }
});

void main() {
  var providerContainer = ProviderContainer();

  providerContainer.listen(greeterProvider, (_, next) {
    print(next);
  });

  providerContainer.listen(greeterProvider2, (_, next) {
    print(next);
  });

  providerContainer.listen(greeterProvider3, (_, next) {
    print(next);
  });
}
```

**Describe the solution you'd like**

My proposition is to support the syntax from `greeterProvider3` to easily combine multiple `StreamProviders` together. To achieve this the following behavior would need to be changed:

StreamProvider doesn't return a new stream when rebuilt but instead adds all the events from that new stream to the original one (similar to Bloc's `mapEventToState`).

This would be a breaking change, therefore an option or a potential new provider type could be added.

This would allow drastically simplify working with stream in riverpod.

**Comment by rrousselGit** [comment]
Hello Norbert!

Riverpod doesn't recommend any of the options you suggested. 
Instead the official solution is to use .future like so:

```dart
final greeterProvider = FutureProvider<String>((ref) async {
   final timer = await ref.watch(timerProvider.future);
   return 'Hi from RX approach, the time is ${e.toString()}';
});
```

I assume that the reason you're doing all of that is because you don't want the AsyncLoading event? But the 2.0 dev released changed how AsyncLoading is handled, which should solve your issue.

AsyncLoading is now only emitted during the very first build of a provider.
After that, subsequent rebuilds will instead return the last AsyncData/AsyncError (with AsyncValue.isRefreshing=true, for folks who want to handle the loading state anyway)

**Comment by rrousselGit** [comment]
As for if you wanted to listen to only a few specific properties of your timer (like the seconds), you could do:

```dart
final greeterProvider = FutureProvider<String>((ref) async {
   // listen only to hour change, skipping second/minute changes
   final hours = await ref.watch(timerProvider.selectAsync((timer) => timer.hours));
   ....
});
```

**Comment by Norbert515** [comment]
Thanks for the quick response - I didn't know about version 2.0!

Is this behavior the same for `StreamProvider`?

**Comment by rrousselGit** [comment]
It applies to any provider that emits an AsyncValue

This includes StateNotifierProvider too. If you do  `StateNotifier<AsyncValue<anything>>`, then after the first AsyncLoading, subsequent AsyncLoadings will be converted to AsyncDatas/AsyncErrors

**Comment by Norbert515** [comment]
You mentioned that Riverpod doesn't recommend any suggestion I described above. How would you go about creating a new `StreamProvider` which is based on another `StreamProvider`?

I believe https://github.com/rrousselGit/riverpod/issues/826 talked about a similar issue, but didn't really solve it

**Comment by rrousselGit** [comment]
That's the thing: Most of the time, you only need one StreamProvider. That provider ewposes Firestore. And from there on, most other providers will be simple FutureProviders instead

There's no need to make a StreamProvider simply because it's depending on another StreamProvider


So unless you have a specific use-case, I'm not sure how to answer your question

**Comment by Norbert515** [comment]
An example:

I have a `StreamProvider` that holds my user ID, and I have another `StreamProvider.family` that holds a `Stream` based on a userID.

For easy access, I'd like to have a `StreamProvider` that holds the user stream (which is a combination of my user id stream + the stream that needs a user ID)

**Comment by rrousselGit** [comment]
Something like this?


```dart
final userIdProvider = StreamProvider<String>((ref) => FirebaseAuth.something);

final family = StreamProvider.autoDispose.family<Result, Param>((ref, param) async* {
  final userId=  await ref.watch(userIdProvider.future);

  yield* createSomeStream(userId, param);
});
```

**Comment by Norbert515** [comment]
Oh, I think now I understand!

```
await ref.watch(userIdProvider.future);
```

basically, _listens_ to the stream as the provider refreshes every time the source stream re-emits?

**Comment by rrousselGit** [comment]
Yes. It's basically similar to ref.watch(userIdProvider). But instead of returning an AsyncValue, which cannot be awaited, it returns a Future

**Comment by rrousselGit** [comment]
It's ultimately similar to what you're suggesting, without the need for that if(asyncValue.asData == null)

**Comment by Norbert515** [comment]
I've been looking for exactly this! I experiment with `StreamProvider` because I wasn't able to bride from the source `StreamProvider` back into a _sane_ Riverpod world! Thank you very much - as far as I understood this works in the 1.0 version but 2.0 makes this more convenient?

**Comment by rrousselGit** [comment]
2.0 isn't about making this more convenient. It's about improving the default behaviour to better match how UIs behaves, in particular around things like pull-to-refresh

If you do

```dart
ref.watch(asyncProvider).map(
  loading: (_) => CircularProgressIndicator(),
  data: (_) => RefreshIndicator(
    onRefresh: () => ref.refresh(asyncProvider.future),
  ),
)
```

then before, during the pull-to-refresh, your UI would show a spinner once-again (on top of the pull-to-refresh indicator). Whereas in 2.0, you'd see the data (and still see the pull-to-refresh indicator).

**Comment by Norbert515** [comment]
So I just checked.

```
final userIdProvider = StreamProvider<String>((ref) => FirebaseAuth.something);
final otherStream= StreamProvider.family<String, String>((ref, id) => Database.something);

final resultProvider = FutureProvider.autoDispose<Result>((ref) async {
  final userId=  await ref.watch(userIdProvider.future);
  final result = await ref.watch(otherStream(userId).future);
  return result;
});
```

Before 2.0 this would lose data between rebuilds (which would result in flicking in the UI), post 2.0 it retains the data - so that should work.

Is the above code valid Riverpod code according to its intentions?

**Comment by rrousselGit** [comment]
Your code and your ewplanation of 1.0 vs 2.0 are correct.

Although make sure that your family is also autoDispose

**Comment by Norbert515** [comment]
Awesome, this also solves https://github.com/rrousselGit/riverpod/issues/1432

Thanks for the assistance - Riverpod rocks! 🤟
