### ISSUE TITLE
A disposed StreamProvider delivers old data when listened again

### ISSUE THREAD

**Issue by rivella50** [rrousselGit/riverpod#1452]
**Describe the bug**
I use this stream provider in a view model against a Firebase database collection, where i'm interested in docChanges:
```
final contractorAccountsStreamProvider = StreamProvider.family
    .autoDispose<List<Account>, String>((ref, contractorId) {
  final database = ref.watch(databaseProvider)!;
  return database.contractorAccountsStream(contractorId);
});
```
When i'm leaving the view, this provider is disposed. Now i change an attribute in one of the previously loaded accounts in Firebase database. Next i open the same view again, where the stream provider starts listening again. And here comes the problem: I am notified twice about changes: First i get the "old" data (list of Account objects) before my manual changes and next i get the changed single Account object in another notification.
But since the provider was disposed i would expect only one notification which includes the list of Account objects including my manual changes.
I have the same phenomenon when logging out and in with a different user, where i use this documentStream provider:
```
final accountStreamProvider = StreamProvider.autoDispose((ref) {
  final database = ref.watch(databaseProvider)!;
  return database.accountStream();
});
ref.listen<AsyncValue<Account>>(accountStreamProvider, (previous, next) {
      // checking for id solves the problem of letting the old account once
      // through after log in with another user account
      if (next.hasValue && Globals().authId == next.value!.id) {
        account = next.value;
        determinePageState(ChangeType.account);
      }
})
Stream<Account> accountStream() => _service.documentStream(
  path: FirestorePath.userAccount(uid),
  builder: Account.fromSingleMap,
);
Stream<T> documentStream<T>({
    required String path,
    required T Function(Map<String, dynamic>? data, String documentID) builder,
  }) {
    final DocumentReference<Map<String, dynamic>> reference =
      FirebaseFirestore.instance.doc(path);
    final Stream<DocumentSnapshot<Map<String, dynamic>>> snapshots =
      reference.snapshots();
    return snapshots.map((snapshot) => builder(snapshot.data(), snapshot.id));
}
```
Here it's even worse: After successful login the listener again gets 2 notifications, where the first one contains the account data of the logged out user, and only the second notification then contains the data of the new logged in user.

That behaviour is quite problematic if a view relies on this data in its initState method, i.e. where it only has access to the data which was received in the first notification, which is then either wrong or not the current one anymore.

I use flutter_riverpod version 2.0.0-dev.9 and Flutter version 3.0.1.

**Expected behavior**
Not to retrieve too old or wrong data.
If that's the expected behaviour could you please tell me how i need to change my code in order not having to bother about notifications which don't represent the most recent data. Thanks a lot.

**Comment by rrousselGit** [comment]
It's not a bug. This is part of the 2.0 changes: while new data is fetching, you retain access to the previous data


I assume you simply want to handle the loading state. Cf AsyncValue.isLoading/isRefreshing

**Comment by rivella50** [comment]
Yes, but when i'm interested in previous data (which i'm not here) i would check the previous object.
But here the wrong or too old data is received in the next object.

**Comment by rrousselGit** [comment]
You're listening to an AsyncValue here

The event that was triggered is the transition from data to loading state.
If you check "next.isLoading", it is true

"next.hasValue" isn't enough anymore, you need to check "next.isLoading" too.

**Comment by rivella50** [comment]
I just added the check for next.isLoading to the listener handler of the first example and it's false for both events when relistening to the provider:
```
_ref.listen<AsyncValue<List<Account>>>(
  contractorAccountsStreamProvider(contractorId), (previous, next) {
      print('has value: ${next.hasValue}   isLoading: ${next.isLoading}   isRefreshing: ${next.isRefreshing}' );
      _handleContractorAccountsUpdate(next.value!);
   }
);
```

**Comment by rivella50** [comment]
Regarding the second example (logout and login again) you're right: The first event has next.isLoading==true which i skip now and only consider the second event with the new user account data.
In comparison to the first example the accountStreamProvider isn't disposed and relistened.

**Comment by rivella50** [comment]
Here is an example which i extracted from my project and which shows the problem of receiving 2 notifications when relistening to the contractorAccountsStreamProvider (after performing some manual changes in Account collection data).
It actually doesn't matter if i'm listening to docChanges or docs.
Please let me know if you need additional information.
[main.dart.txt](https://github.com/rrousselGit/riverpod/files/8885499/main.dart.txt)

**Comment by rivella50** [comment]
Interesting: When calling .refresh on the stream provider when it is disposed then i get exactly (the expected) one notification event on relistening to it (containing ALL changes performed in the database meanwhile):
```
_ref.onDispose(() {
   print('disposing...');
   _ref.refresh(contractorAccountsStreamProvider('accountId'));
});
```
Does that somehow make sense to you? I'm not sure if this would be a good approach.

**Comment by rivella50** [comment]
I read this sentence on the StreamProvider [page](https://riverpod.dev/docs/providers/stream_provider):

- it caches the latest value emitted by the stream, ensuring that if a listener is added after an event is emitted, the listener will still have immediate access to the most up-to-date event.

Could it be that this cache is not cleared on disposing the provider and therefore be the reason why i'm getting the last value again on relistening the provider?

**Comment by rivella50** [comment]
Ok it seems that this effect is a feature and not an issue.
I've tested it with Creator and got the same behaviour.
When disabling Firebase persistence (as a test) the issue is also gone, therefore the old data delivered on relistening comes from Firebase caching.

**Comment by rrousselGit** [comment]
Right, but I don't understand your feature request either. So I'm a bit at loss

**Comment by rrousselGit** [comment]
@rivella50 Have you raised an issue on the flutterfire repo about the problematic behavior? Maybe this needs a Firebase fix.

**Comment by rivella50** [comment]
@rrousselGit Yes i did: https://github.com/firebase/flutterfire/issues/8961
They look at it as an enhancement.
