### ISSUE TITLE
Arguments not listed for .family

### ISSUE THREAD

**Issue by hunterpp** [rrousselGit/riverpod#1467]
The arguments that family can expect are not listed or explained at https://riverpod.dev/docs/concepts/modifiers/family

**Comment by rrousselGit** [comment]
Could you clarify what this is about?

What argument are you talking about specifically? And what you like to see listed?

**Comment by hunterpp** [comment]
I am confused as to both the expected generics and the flexibility of the arguments allowed.

Doing some research it seems that only 1 additional argument to family is allowed, meaning that if you want to pass more than 1 arg you need to pass a custom class containing the args you intend to pass to family as done here:

As I have done here: 
`final fidModelProvider = Provider.family<FidModel?, FidModelArgs>((ref, args) {`

I was also able somehow to create a 3 generic to family here, however it still also expects 1 argument. 

`StateNotifierProvider.family<FeedStateNotifier, FeedState, FeedStateType>(
        (ref, type) {`

So some clarification of the kinds of generics allowed, and also the kinds of arguments allowed is what would be very helpful.

**Comment by rrousselGit** [comment]
Family always have one parameter. The document already mentions using a class to pass multiple values

StateNotifierProvider has 3 generic parameters, but only one of them is for family.

By default, StateNotifierProvider without family has 2 generic parameters. So family still adds only 1

**Comment by rrousselGit** [comment]
Closing as this was answered
