### ISSUE TITLE
refreshAndListen for Providers

### ISSUE THREAD

**Issue by rivella50** [rrousselGit/riverpod#1468]
**Is your feature request related to a problem? Please describe.**
Yes, see my meanwhile closed issue [here](https://github.com/rrousselGit/riverpod/issues/1452).
In short: With Firestore persistenceEnabled and relistening to a StreamProvider gives me as first value the cached (and probably not current anymore) value and only in a second event the current docs or its changes.
In some cases however i need the most recent value from database in the first event.
I already mentioned that calling
```
ref.refresh(contractorAccountsStreamProvider('contractorId'));
```
on disposing the provider seems to solve the issue (invalidate does not work), but you told me not to do that at this point.

**Describe the solution you'd like**
What about a new function call 'refreshAndListen' which does refreshing (and therefore not deliver a cached value as first event) and after that listen to the mentioned provider in one step?
Since the listen action then gets the most recent value from the database the refresh performed before does not have to retrieve that value as well, it just should make sure that the provider does not deliver a cached value and therefore behaves as if it was listened to for the first time.

**Describe alternatives you've considered**
Mentioned above but not advised to do that.

**Additional context**
If you have another and/or easier way to handle it please let me know.

**Comment by rrousselGit** [comment]
I'm really struggling to understand the problem here.

And since I don't understand the problem, there's no way for me to evaluable whether this proposal makes sense.

Could you please reformulate the problem in something clear, not firebase specific?

**Comment by rivella50** [comment]
It also took me quite some time to understand it.
Since the problem is tied to Firestore's caching feature i have to explain my problem by including it.

When disposing a stream provider (marked with .autoDispose) on e.g. leaving a view and therefore the provider has no listeners anymore the connected stream of a Firestore collection is not reset/disposed as well, which means that on relistening the stream provider (by entering the view again) it gives me in the first notification the cached list of elements from when the disposal happened (.isLoading is false btw.) and only in a second notification the current list of elements (or changes when i'm interested in docChanges).

This seems to be normal behaviour, therefore i've closed the other ticket.
But in my case for certain views i have to rely on that i get the most recent list of elements in the first notification of the relistened stream provider (as if a would listen to it for the very first time) and not in one of the subsequent notifications.
That's why i tried e.g. to refresh the mentioned stream provider in order to get rid of a cached version when relistening it.
Since doing that when disposing it is not a good idea i thought why not doing that right before (re-)listen the stream provider (and where a view needs it), and here we are with my feature request.

I hope you understand now my problem.

**Comment by rrousselGit** [comment]
I'm sorry but I still don't understand what you've described.

To begin with, I don't understand how to use your example. So I can't follow what you say

It'd _really_ help me if you could do a normal "bug" report, with steps to reproduce. Abstract explanations of the problem in English won't help.

**Comment by rivella50** [comment]
Hmmmmm, well it's not a (Riverpod) bug anymore to me, that's why i've switched to this feature request.
I "just" need a way to tell a stream provider's underlying stream to behave as if it was started again when relistening the provider. This is what ref.refresh(myStreamProvider) seems to do, that's why i came up with this request.

If you have Firebase available on your side i could send you a list of steps to do.

**Comment by rivella50** [comment]
Ok i guess that my feature request can be skipped.
Today i debugged my test application and also entered Riverpod's code.
For some reasons the stream provider doesn't seem to be disposed when the view (model) is disposed, although i see it in the list of providers to be disposed.
Only when i manually call mayNeedDispose() in the view model (which i probably also shouldn't do) it works:
```
_ref.onDispose(() {
    print('disposing...');   _ref.container.readProviderElement(contractorAccountsStreamProvider('contractorId')).mayNeedDispose();
    });
```
If i do that i see these 4 states to be disposed:
![Screenshot 2022-06-21 at 17 10 34](https://user-images.githubusercontent.com/54292/174836886-1254b82a-bcd9-4c56-b9a4-59e446fc335f.png)

The stream provider appears twice there. I don't know if something goes wrong while disposing the first one or if there are actually two stream providers which need to be disposed.
