### ISSUE TITLE
Unexpected behavior when using AsyncValue .when function in Riverpod 2 (inconsistent with Riverpod 1)

### ISSUE THREAD

**Issue by cesarParra** [rrousselGit/riverpod#1469]
**Describe the bug**
I am not sure if this is by design or a regression issue between Riverpod 1 and 2 (or maybe me doing something wrong). I'm seeing some inconsistent and unexpected behavior when using AsyncValue with a StateNotifier, changing for changes and using `.when` to react to those changes.

**To Reproduce**

Here's a a very simplified example of the problem:

Have a StateNotifier that looks as follows:
```
class MyNotifier extends StateNotifier<AsyncValue<void>> {
  MyNotifier() : super(AsyncValue<void>.data(null));

  Future<void> doSomething() async {
    state = const AsyncLoading();
    await Future.delayed(Duration(seconds: 5));
    state = AsyncData(null);
  }
}
```

A provider for it 
```
final myNotifierProvider = StateNotifierProvider.autoDispose<MyNotifier, AsyncValue>((ref) {
  return MyNotifier();
});
```

And finally a widget using it:
```
class SampleWidget extends ConsumerWidget {
  const SampleWidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final myTestValue = ref.watch(myNotifierProvider);
    print('Runtime type ${myTestValue.runtimeType}');

    return myTestValue.when(
        data: (_) => Row(
              children: [
                Text('Data ${myTestValue.isLoading}'), // Riverpod 2 has the isLoading property available
                // Text('Data'), // if using Riverpod 1, which doesn't have the isLoading property
                TextButton(
                    onPressed: () =>
                        ref.read(myNotifierProvider.notifier).doSomething(),
                    child: Text('Execute'))
              ],
            ),
        error: (e, st) => Text('Error'),
        loading: () => Text('LOADING'));
  }
}
```

** Behavior **
What I'm seeing is that it never goes into the `loading` section, it always returns the data widget. But the value does correctly updates to reflect that it is loading (isLoading is `true`), so the text that I have in that data widget does update correctly.

I have added a print to the console that shows the `runtimeType` of the AsyncValue and it is always `AsyncData`.

**Expected behavior**

I would have expected the runtimeType to be of type `AsyncLoading`, so that when using `.when` it would return the Loading widget.

This behavior is also inconsistent with Riverpod 1, where the type is in fact `AsyncLoading`, so the `loading` widget is returned as expected.

![image](https://user-images.githubusercontent.com/2524257/174615991-6c85fa24-0f31-4590-9795-c24baec2105b.png)

**Comment by rrousselGit** [comment]
That's what the 2.0 is about

It gives you the previous data during loading state.

**Comment by cesarParra** [comment]
I see. So would the correct way of handling loading states now be to avoid using the `.when` and using the `isLoading` property instaead?

**Comment by rrousselGit** [comment]
It depends. The `when` behavior is often a bit more intuitive for users: They see the previous data during loading state instead of a "pointless" spinner

An alternative could be to keep using `when`, and show _both_ the spinner and a progress indicator

**Comment by cesarParra** [comment]
I see. Yeah that makes sense to have that kind of flexibility. Thanks!

**Comment by Shahmirzali-Huseynov** [comment]
@cesarParra How did you solve the problem? I want to show the loading widget but show previous data.

**Comment by rrousselGit** [comment]
This behavior will not be part of the stable 2.0.

On master, if a provider changed from a `ref.watch`, it's now showing "loading" correctly.
The "isRefreshing" logic now applies only to cases where a provider rebuilds **only** due to a `ref.refresh(provider)`/`ref.invalidate(provider)` call.

**Comment by Shahmirzali-Huseynov** [comment]
@rrousselGit actually I'm using `hooks_riverpod: ^2.0.0-dev.9` version. Do you say in the 1.0.3 version it's not like that or? What solution suggests to me now for showing loading When I'm using StateNotifierProvider?

**Comment by rrousselGit** [comment]
It's not like that in 1.0, no.
And the stable 2.0 release won't be like that either.

**Comment by rrousselGit** [comment]
Inside your widgets, you can do `ref.watch(myProvider).unwrapPrevious()`

**Comment by Shahmirzali-Huseynov** [comment]
Thanks for the answer. When I use unwrapPrevious it works as I expected.

**Comment by Shahmirzali-Huseynov** [comment]
@rrousselGit  my last question, can We use autoDispose in StateNotifier refreshing data?
