### ISSUE TITLE
StateProvider name return null 

### ISSUE THREAD

**Issue by murataksuu** [rrousselGit/riverpod#1470]
State provider appears to be null in the didUpdateProvider call. didDisposeProvider and didUpdateProvider also work fine.

> didAddProvider: -myprovidername.notifier: Provider started with value: Instance of 'StateController\<int\>'
> didUpdateProvider: - null: Provider started with value: Instance of 'StateController\<int\>'
> didUpdateProvider: - null: previousValue: Instance of 'StateController\<int\>'

```
final myProvider = StateProvider.autoDispose<int>((ref) {
  return 0;
}, name: "myprovidername");
```

version: 2.0.0-dev.9

**Comment by rrousselGit** [comment]
Could you \share how you came up with these logs?

**Comment by murataksuu** [comment]
> Could you \share how you came up with these logs?

class Logger extends ProviderObserver with ProviderObserverLoggy {
  @override
  void didUpdateProvider(ProviderBase provider, Object? previousValue,
      Object? newValue, ProviderContainer container) {
    loggy.info("${provider.name}: previousValue: ${newValue}");
    super.didUpdateProvider(provider, previousValue, newValue, container);
  }

  @override
  void didAddProvider(
      ProviderBase provider, Object? value, ProviderContainer container) {
    loggy.info("${provider.name}: Provider started with value: ${value}");
    super.didAddProvider(provider, value, container);
  }

  @override
  void didDisposeProvider(ProviderBase provider, ProviderContainer container) {
    loggy.info("${provider.name} Disposed.");
    super.didDisposeProvider(provider, container);
  }
}
