### ISSUE TITLE
ref.listenSelf in StateNotifierProvider listen to Notifier changed instead of it's state changed

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/riverpod#1480]
**Describe the bug**
ref.listenSelf in StateNotifierProvider listen to Notifier changed instead of its state changed.

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**
The previous and next parameters should be State instead of Notifier.

**Comment by rrousselGit** [comment]
Closing as duplicate of https://github.com/rrousselGit/riverpod/issues/1480
