### ISSUE TITLE
refresh with nested provider: StateError (Bad state: Tried to use Notifier after `dispose` was called.

### ISSUE THREAD

**Issue by hunterpp** [rrousselGit/riverpod#1481]
First the code:
```dart
final pittieProvider = StateNotifierProvider<DogStateNotifier, DogState>((ref) {
  ref.onDispose(() {
    log("DISPOSED causes error");
  });
  return ref.watch(dogStateProvider(DogType.pittie).notifier);
});

final simplePittieProvider =
    StateNotifierProvider<DogStateNotifier, DogState>((ref) {
  ref.onDispose(() {
    log("DISPOSED SIMPLE no error");
  });
  return PittieNotifier();
});

final dogStateProvider =
    StateNotifierProvider.family<DogStateNotifier, DogState, DogType>(
        (ref, type) {
  ref.onDispose(() {
    log("DISPOSED DSP");
  });
  if (type == DogType.pittie) {
    PittieNotifier pittieNotifier = PittieNotifier();
    return pittieNotifier;
  } else {
    return PittieNotifier();
  }
});
```

In above code from https://github.com/hunterpp/riverpod_child_provider/blob/main/lib/dogs.dart, when pullToRefresh happens here: https://github.com/ftognetto/riverpod_infinite_scroll/blob/80c076c34fa26ff2e3da4be81d1602c755e83146/lib/src/river_paged_builder.dart#L183  it errors with pittieProvider as shown below: 

![Screen Shot 2022-07-02 at 3 24 06 AM](https://user-images.githubusercontent.com/772917/176991016-390ce37f-42e7-4e73-aa12-2930ff417150.png)

![Screen Shot 2022-07-01 at 3 21 14 AM](https://user-images.githubusercontent.com/772917/176991021-39eeca59-c369-4a75-8dd7-5385a1b6b46f.png)

However, it does not error with `simplePittieProvider` 
i've tried:
1.  ref.read, 
2. ref.watch
3. riverpod 2.0.0-dev9
4. stateful/stateless

And same error still occurs

any idea why? both pittieProvider and simplePittieProvider call onDispose yet only pittieProvider errors.

**Comment by rrousselGit** [comment]
Providers should not return an existing state. They should create a new one.
This rule applies to StateNotifierProvider too. You shouldn't return an existing StateNotifier, but a new one instead.

So this behavior is expected.
