### ISSUE TITLE
user ref.write and ref.update instead of ref.read(prov.notifier).state and ref.read(prov.notifier).update 

### ISSUE THREAD

**Issue by Alexqwesa** [rrousselGit/riverpod#1484]
1) The
```ref.read(prov.notifier).state = new_state;```
is a clymsy way of writing, why not just use?:
```ref.write(prov) = new_state```

Thit way we don't care is it state provider or just usuall provider, less code for writing, easier to read. 

2) And
```ref.read(prov.notifier).update((state) => state = state+1);```
convert to:
```ref.update(prov)( (state) => state = state+1) );```

3) and the last one: why is there 
```ref.read(prov.notifier)```
but not the:
```ref.notifier(prov)```

BTW: Thanks for great state manager)

**Comment by rrousselGit** [comment]
Hello!

`ref.write` is not something reasonable. That'd work only for StateProvider (as it doesn't make sense for other providers, StateNotifierProvider included)
Same goes for the update variant.


`ref.notifier`, while doable, is not something I want to do. The current syntax is designed to allow also allow:

`ref.watch(provider.notifier)`and `ref.listen(provider.notifier)`, both of which can be useful.

**Comment by rrousselGit** [comment]
Closing as this isn't something I plan to implement
