### ISSUE TITLE
Debugger Breaks on Unhandled Exception in FutureProvider

### ISSUE THREAD

**Issue by abegehr** [rrousselGit/riverpod#1488]
**Describe the bug**
I have a FutureProvider that is defined by an async function. The FutureProvider is watched in a HookConsumerWidget. When the await statement in the FutureProvider body fails, it calls an Unhandled Exception and my VSC debugger breaks since I have break on "Uncaught Exceptions" enabled.

**To Reproduce**
I'm adding this later. Just wanted to check if this might be expected first.
<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**
I would expect it not to break on "Uncaught Exception" since the exception is caught in the AsyncValue in the frontend: `value.hasError ? value.error : null`.

**Comment by rrousselGit** [comment]
This is expected. Although Riverpod catches the error, it explicitly tells the debugger that this is considered uncaught. 

This helps the debugging, as exceptions inside providers are unexpected.

**Comment by abegehr** [comment]
Thank you for the details, @rrousselGit!
It might be nice to be able to mark a providers exceptions as caught in case they are caught and handled in the frontend. One example would be a provider which gets some data and throws when the user does not have sufficient access rights which could then be shown in the frontend (aka request access). Currently, would you recommend achieving this by having one boolean provider hasAccessToDocument and one Stream- or FutureProvider for fetchDocument instead?

**Comment by rrousselGit** [comment]
I would recommend for you to catch purposeful exceptions and expose a "Result"/union as data

As in, exceptions should only be for uncaught exceptions. If some state is desired, don't use an exception for it.

**Comment by abegehr** [comment]
I don't agree that exceptions should only be uncaught exceptions since exceptions can be a great way to propagate problems to the frontend and handle them there but understand the design choice made in RiverPods on this. Thanks again for the help, @rrousselGit!

**Comment by rrousselGit** [comment]
You're definitely free to keep throwing. I wouldn't say that's bad/wrong

But I don't think removing the described behavior would be a win. I think it's better for the IDE to stop on purposeful exceptions than for the IDE to ignore undesired exceptions.
