### ISSUE TITLE
ref.refresh(p.future) does not work on v1.0

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1489]
Latest versions as in v2 onwards? I tested this on 1.0.4, there's no `refetching` printed.

```dart
final userProfileProvider = FutureProvider<UserProfile>((ref) async {
  final userProfile = ref.watch(userProfileServiceProvider);
  print('refetching');
  return userProfile.getProfile();
});

// ...

RefreshIndicator(
  onRefresh: () => ref.refresh(userProfileProvider.future),
)
```

_Originally posted by @alvinthen in https://github.com/rrousselGit/riverpod/issues/1485#issuecomment-1175016633_

**Comment by rrousselGit** [comment]
I don't plan on fixing that. 2.0 is going to become stable by the end of August. I'd suggest migrating instead

Alternatively you can doL:

```dart
ref.refresh(userProfileProvider);
return ref.read(userProfileProvider.future);
```

**Comment by alvinthen** [comment]
Great to know that 2.0 is going stable. I'm going to migrate to it. Thanks!
