### ISSUE TITLE
CANCELLED Using camelCase route names seems to be broken in 2.0+

### ISSUE THREAD

**Issue by jeff9315** [rrousselGit/riverpod#1492]
I have a route name that's mainMenu. While using that, I get the following error. When I change it to all lowercase, it works fine. I'm using 2.0.0-dev.9

```
The following assertion was thrown while handling a gesture:
Assertion failed:
file:///L:/development/sdks/flutter/.pub-cache/hosted/pub.dartlang.org/go_router-4.1.0/lib/src/go_route_information_parser.dart:97:12
..\…\src\go_route_information_parser.dart:97
_nameToPath.containsKey(name)
"unknown route name: mainMenu"
```

Here's other reports on issueHint https://issuehint.com/issue/flutter/flutter/106163

**Comment by rrousselGit** [comment]
Hello!

What does this have to do with riverpod?
