### ISSUE TITLE
Using ref.watch() inside stateNotifier constructor function

### ISSUE THREAD

**Issue by MkamaMakoko** [rrousselGit/riverpod#1501]
I want to obtain and monitor the state of the provider from another provider

Is it safe to use watch or listen methods inside a constructor function? Or should I pass the other provider state from the provider function as a parameter? Which is more recommend?

**Comment by rrousselGit** [comment]
ref.watch/listen inside the constructor specifically is safe

Inside methods, it's not.

**Comment by MkamaMakoko** [comment]
> ref.watch/listen inside the constructor specifically is safe
> 
> Inside methods, it's not.

Which do you recommend the most? Watch state inside constructor? or passing state through parameter from provider function?
