### ISSUE TITLE
FutureProvider with MaterialApp cause "Null check operator used on a null value"

### ISSUE THREAD

**Issue by kice** [rrousselGit/riverpod#1503]
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const ProviderScope(child: MyApp()));
}

final delayProvider = FutureProvider<String>((ref) => Future.value("App"));

class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final delayedValue = ref.watch(delayProvider);
    return delayedValue.when(
      data: (title) => MaterialApp(routes: <String, WidgetBuilder>{
        '/': (context) => Scaffold(appBar: AppBar(title: Text(title)))
      }),
      error: (error, s) => const MaterialApp(home: Text("error")),
      loading: () => const MaterialApp(home: Text("loading")),
    );
  }
}
```

The code here will throw an error since `widget.home` is `null`:

https://github.com/flutter/flutter/blob/f1875d570e39de09040c8f79aa13cc56baab8db1/packages/flutter/lib/src/widgets/app.dart#L1352-L1354

If the `MaterialApp` in `error` and `loading` change to other widgets will be fine.

Using flutter 3.0.5 and tested with riverpod 1.0.3 and 2.0.0-dev.9.

Maybe I am using this wrong?

**Comment by iamarnas** [comment]
You code is wrong. You should put your `delayedValue` to the `MaterialApp` home section and return news screens with Scaffold widgets. To break all Material components on the loading it is very bad practice. Don't do that. `MaterialApp` widget must be on the top widget three.

**Comment by kice** [comment]
So it does not replace with a new "object" with new "data", just replace the state/data if the widgets return from the build method is the same type.

Closing for now, since it has nothing to do with riverpod.
