### ISSUE TITLE
Handling empty lists with AsyncValue/.when

### ISSUE THREAD

**Issue by floodoo** [rrousselGit/riverpod#1504]
When calling RESTful API's it is quite common to see empty arrays returned instead of null.
What is the best solution to handle this in Riverpod with AsyncValue?
Currently there is `.whenOrNull`and `.when` with data, error and loading. What I am missing is a `empty` function. As often developers forget to implement this state.

**Describe the solution you'd like:**
```dart
.when(
      data: (data) => print(data),
      empty: () => print('No results found.'),
      loading: () => print('loading'),
      error: (e, st) => print('Error: $e'),
    );
```

**This is what i am doing currently:**

```dart
.when(
      data: (data) {
        if (data.isEmpty) {
          print('No results found.');
        }

        print(data);
      },
      loading: () => print('loading'),
      error: (e, st) => print('Error: $e'),
    );
```

**Comment by rrousselGit** [comment]
What you're currently doing is the expected solution.

**Comment by floodoo** [comment]
Thanks for your fast response. Do you find the suggestion useful for Riverpod 2.0? It would make apps more fail save, when handling data.

**Comment by rrousselGit** [comment]
:wave:
I don't agree with this change.

AsyncValue doesn't know what the data is. There's no way for it to know what "empty" could be. And the data is not restricted to being a List

I don't think there's anything wrong with the current syntax.

**Comment by floodoo** [comment]
Yes you are right. There are too many variations of data.

Thanks 👍
