### ISSUE TITLE
Providers are not allowed to modify other providers during their initialization.

### ISSUE THREAD

**Issue by purutechno** [rrousselGit/riverpod#1505]
I have a use case in which a provider is required to update the state of another provider during it's initialization.  This is done during the initialization of one provider. 

Question : 
Why is one provider not allowed to update another provider during it's initialization, And Why does it work if we place some delay before updating another provider ?

Inspiration :
I've observed Providers are allowed to communicate with other provider during initialization but it's not allowed to update other provider.

**To Reproduce**

Create two provider :
i) StateProvider and a StateNotifier Provider,
ii) try to update your stateProvider while initializing your StateNotifierProvider 

**Expected behavior**
I've found a workaround to tackle this issue, We can use certain delays before we update another provider during the initialization.
But how do we know that it's an ideal delay duration. Is it possible to have those delays in providers by default so that the use case can be much more simpler.

<img width="1415" alt="Screen Shot 2022-07-21 at 23 00 54" src="https://user-images.githubusercontent.com/44781006/180274248-a5bf0d88-271f-4e17-add6-d23ecf872478.png">

<img width="1352" alt="Screen Shot 2022-07-21 at 22 50 53" src="https://user-images.githubusercontent.com/44781006/180274380-70bce6b1-defa-4d8e-88ba-a470f7e5fdb3.png">

**Comment by rrousselGit** [comment]
Modifying other providers during init is the wrong architecture 

Providers are designed with this restriction in mind, and it cannot be lifted. 
Think about it: You could quickly end-up in an infinite loop of provider rebuilding


Adding a delay is simply cheating. Riverpod can't yell you you're violating the constraints of providers in this situation, but it's still equally bad to do.

**Comment by purutechno** [comment]
Agreed!
I've done the update for the second provider once the initialization of first is completed by giving a body to the super class.
Not sure if this is a good way but closing this issue.

@rrousselGit  Thank You for the help!

<img width="466" alt="Screen Shot 2022-07-22 at 14 03 28" src="https://user-images.githubusercontent.com/44781006/180395942-9d8b8e98-d669-423f-ac91-a7709920af61.png">
irst provider is done.
