### ISSUE TITLE
Incorrect docs for `AsyncValue.value`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/riverpod#1508]
The docs for [`AsyncValue.value`](https://github.com/rrousselGit/riverpod/blob/2586b40929aeede23d92dbadb9ff4701a2de8de8/packages/riverpod/lib/src/common.dart#L160) state:

> When reading [value] during loading state, null will be returning.

They also state:

> See also [valueOrNull], which does not throw during loading state.

Which is contradictory and therefore incorrect.

---

I would improve these docs, but I am actually not sure if `value` throws or does indeed return `null` in the loading state.

**Comment by rrousselGit** [comment]
Ha, it was "does not throw during error state", not loading

Thanks!
