### ISSUE TITLE
Update on "state hydration" 

### ISSUE THREAD

**Issue by cgutierr-zgz** [rrousselGit/riverpod#1511]
**Is your feature request related to a problem? Please describe.**
I'm struggling a bit with getting riverpod state to persist after app shutdown and I've the Rodamap states "state hydration" as one of its points
I was wondering if this refers to this kind of issue, and if so I was wondering if it's part of the 2.0 update

Thanks a lot!

**Describe the solution you'd like**
I'd like to have a documented implementation for the issue stated above

**Comment by rrousselGit** [comment]
It will be, yes. It's still wip
