### ISSUE TITLE
Tiny typo in document

### ISSUE THREAD

**Issue by monkeydaichan** [rrousselGit/riverpod#1512]
**Describe what scenario you think is uncovered by the existing examples/articles**

**Describe why existing examples/articles do not cover this case**

**Additional context**
Add any other context or screenshots about the documentation request here.

```
 data: (value) => Text('Hello ${user.name}'), // incorrect
 data: (value) => Text('Hello ${value.name}'), // correct
```

https://pub.dev/documentation/riverpod/latest/riverpod/AsyncValue-class.html
<img width="709" alt="Screen Shot 2022-07-26 at 20 57 39" src="https://user-images.githubusercontent.com/20509967/181137569-09a1b67d-2d8a-4bc9-bbdd-39cbd6f3fa76.png">

**Comment by rrousselGit** [comment]
This is fixed on master. I guess the doc fix wasn't deployed
