### ISSUE TITLE
The FAQ sub-links on pub.dev don't render properly

### ISSUE THREAD

**Issue by ValentinVignal** [rrousselGit/riverpod#1513]
**Describe what scenario you think is uncovered by the existing examples/articles**
On [pub.dev](https://pub.dev/packages/riverpod) the doc doesn't render properly in the Index for the FAQ (see screenshot)

<img width="827" alt="image" src="https://user-images.githubusercontent.com/32538273/181472596-4b79c6a4-c2d6-4820-9403-bf2e264f2d4c.png">

**Comment by rrousselGit** [comment]
This is fixed in the 2.0-dev readme

1.0 is simply out of date. With 2.0 becoming stable soon, I won't bother making this change :) 

![Uploading Screenshot 2022-07-31 at 15.21.35.png…]()
