### ISSUE TITLE
Mistake in code snippet on the riverpod docs website

### ISSUE THREAD

**Issue by ojm-it** [rrousselGit/riverpod#1515]
In [this section](​https://riverpod.dev/docs/concepts/combining_providers#how-to-test-an-object-that-receives-read-as-a-parameter-of-its-constructor) of the riverpod.dev website, there is a mistake in the code snippet. 

```dart
// Current :
addTearOff(container.dispose);

// Should be :
addTearDown(container.dispose);
```

https://riverpod.dev/docs/concepts/combining_providers#how-to-test-an-object-that-receives-read-as-a-parameter-of-its-constructor

**Comment by rrousselGit** [comment]
Thanks for the report!
