### ISSUE TITLE
Wrong string substitutions

### ISSUE THREAD

**Issue by flutterrausch** [rrousselGit/riverpod#1518]
**Describe the bug**
Tried to migrate a project, got errors in some files, like so:

class ProviderConsumerWidgetatelessWidget {

  Widget build(BuildCo, WidgetRef refntext context) {

            firef.watchumber = watch(numberProvider).toString();

**To Reproduce**
Migrate https://github.com/JohannesMilke/riverpod_modifiers_example
Did 'y' once, then 'A'. Needed to do one more 'y' (also a bug :)
Check provider_page.dart, state_provider_page, maybe others are affected, too. future_provider_page is fine.

Thanks for your work, Remi :-)

**Comment by rrousselGit** [comment]
I'll close this. I have no plan to fix the remaining bugs for the migration tool as it's been quite a while now since the breaking change happened.
