### ISSUE TITLE
hello，in https://riverpod.dev/. Can you make a simplified Chinese document for learning?

### ISSUE THREAD

**Issue by pheromone** [rrousselGit/riverpod#1522]
你好，在in https://riverpod.dev/ 里面，你能做一个简体中文的学习文档吗?
hello，in https://riverpod.dev/. Can you make a simplified Chinese document for learning?
<img width="246" alt="image" src="https://user-images.githubusercontent.com/14305431/182087718-7408f89e-1e40-48da-b42e-d29459bca06b.png">

**Comment by rrousselGit** [comment]
Hello

I don't speak simplified Chinese.
If you want such language, feel free to find someone who could translate the website 😊

**Comment by laiiihz** [comment]
hi, i translated the webside in Simplified Chinese whitch on branch docs-v2. #2129 
我在docs-v2分支上添加了简中的翻译 #2129
