### ISSUE TITLE
Export an abstract `StateProviderBase` (like `ProviderBase`) 

### ISSUE THREAD

**Issue by ValentinVignal** [rrousselGit/riverpod#1523]
**My issue**

When I'm writing a widget/method which would work for any provider (`Provider`, `FutureProvider` etc) I can use the abstract type `ProviderBase`:

```dart
void doSomethingWithAProvider(ProviderBase provider);
```

Now if I want to write an method that does something with a `StateProvider`, there is no abstract common class I can use

```dart
void doSomethingWithAStateProvider(/*What type?*/ provider) {
  provider.state;
  provider.notifier;
}
```

At the moment I'm using `StateProviderOverrideMixin` but it is not exported in `lib/riverpod.dart` so it is not ideal as I have the lint `Don't import implementation files from another package.`:

```dart
void doSomethingWithAStateProvider(StateProviderOverrideMixin provider) {
  provider.state;
  provider.notifier;
}
```

**Describe the solution you'd like**

If it is fine, export `StateProviderOverrideMixin` in `lib/riverpod.dart`.
If it is not, create an abstract class (ex: `StateProviderBase`) that `StateProvider` , `StateProviderFamily`, `AutoDisposeStateProvider` and `AutoDisposeStateProviderFamily` would implement.

**Describe alternatives you've considered**

I'm using `StateProviderOverrideMixin` and importing it from `'src/state_provider.dart'`.

**Comment by rrousselGit** [comment]
This is not something desirable.


You're not supposed to build logic that is provider specific.
Instead use the return type

Maybe you want to create some logic that uses and depends on a StateNotifier. And you'd manually listen to it.

**Comment by ValentinVignal** [comment]
Maybe a more concrete example would help to illustrate:

Let's say I'm implementing filters for a list of objects in my app.
- One of the filter is a `StateProvider` (because it needs to persist through the entire user session).
- One is a `AutoDisposeStateProvider` (Because it doesn't need to persist if not listened to).

```dart
final longLivedFilterProvider = StateProvider.autoDispose<int>((ref) {
  return const {};
});

final shortLivedFilterProvider = StateProvider.autoDispose<int>((ref) {
  return const {};
});
```

Now, I'm displaying a `FilterBar` which I give a list of filters:

```dart
/// Takes the list of filters and display them.
class FilterBar extends StatelessWidget {  // <- This doesn't need to be ConsumerWidget.
  const FilterBar({
    this.filters = const [],
  });
  
  final Iterable<StateProviderBase<int>> filters; // <- Where I would need this abstract/common type.

  Widget build(BuildContext context) {
    return Row(
      children: filters.map((filterProvider) => FilterWidget(filterProvider: filterProvider)).toList(),  
    );
  }
}

/// Takes a single filter, displays it and allows the user to modify it.
class FilterWidget extends ConsumerWidget {
  const FilterBar({
    required filterProvider,
  });
  
  final StateProviderBase<int> filterProvider; // <- Where I would need this abstract/common type.

  Widget build(BuildContext context) {
    final filter = ref.watch(filterProvider);
    return TextButton(
      onPressed: () {
        final filterNotifier = ref.watch(filterProvider.notifier); // This is why I need to know it is a StateProvider.
        filterNotifier.state = {...state, state.length}; // Some business logic. 
      },
      child: Text(filter.join(', ')),
    );
    return Row(
      children: filters.map((filterProvider) => Filter(filter: filterProvider)).toList(),  
    );
  }
}
```

What I was trying to do was to write `ref.watch` as low as possible in the widget tree to be as performant as possible (our app is a web app and performance is kind of an issue).
And also trying not to carry around a bunch of `onPressed` (used in the `TextButton` in my example).


So in your opinion, you suggest I only pass a `ProviderBase<int>` with a bunch of `onPressed`s for the `TextButton`s ?

**Comment by ValentinVignal** [comment]
Ok, so if I understood correctly, this is what you recommend:

```dart
/// Takes the list of filters and displays them.
class FilterBar extends StatelessWidget {
  const FilterBar({
    this.filters = const [],
  });
  
  final Iterable<StateController<Set<int>>> filters;

  Widget build(BuildContext context) {
    return Row(
      children: filters.map((filterStateController) => FilterWidget(filterStateController: filterStateController)).toList(),  
    );
  }
}

/// Takes a single filter, displays it and allows the user to modify it.
class FilterWidget extends StatelessWidget {
  const FilterBar({
    required filterStateController,
  });
  
  final StateController<Set<int>> filterStateController;

  Widget build(BuildContext context) {
    // I cannot watch anything here.
    return TextButton(
      onPressed: () {
        filterStateController.update(/* ... */);
      },
      child: Text(filter.state.join(', ')), // <- This is not watched.
    );
  }
}
```

And then I would have to watch all the filters all together at the top of my widget tree:

```dart
FilterBar(
  filters: [
    ref.watch(longLivedFilterProvider.state);
    ref.watch(shortLivedFilterProvider.state);
  ],
);
```

---

But doing this forces me to watch all the providers at the top of the widget tree, and the goal is usually to watch/listen as low as possible in the widget tree. So isn't it an issue?

**Comment by rrousselGit** [comment]
No, don't do `ref.watch(provider.state)`
Do `ref.watch(provider.notifier)`

Then you can use the flutter_state_notifier package with its StateNotifierBuilder to listen to the StateController inside the leafs of your widget tree

**Comment by ValentinVignal** [comment]
Thank you for the support @rrousselGit !
