### ISSUE TITLE
Multiple calls to pump() needed when combining state of async providers

### ISSUE THREAD

**Issue by knaeckeKami** [rrousselGit/riverpod#1539]
**Describe the bug**

When testing the behaviour of a provider that combines the state of multiple FutureProviders using
`await ref.watch(futureProvider.future)`, multiple calls to `providerContainer.pump()` are necessary until the provider returns 
`AsyncData` instead of `AsyncLoading`.

**To Reproduce**

```dart
import 'package:riverpod/riverpod.dart';

final futureProvider1 = FutureProvider((ref) async {
  return Future.value(1);
});

final futureProvider2 = FutureProvider((ref) async {
  return Future.value(2);
});

final combiningProvider = FutureProvider((ref) async {
  return await ref.watch(futureProvider1.future) +
      await ref.watch(futureProvider2.future);
}, dependencies: [
  futureProvider1.future,
  futureProvider2.future,
]);
void main() async {
  final providerContainer = ProviderContainer();

  final sub = providerContainer.listen(combiningProvider, (_, __) {});

  while (sub.read() is AsyncLoading<Object?>) {
    print("pump");
    await providerContainer.pump();
  }

  print(sub.read());
  sub.close();
  providerContainer.dispose();
}
```

This snipped will print "pump" 4 times.  (using the stable version of riverpod).

Note: when rewriting the combiningProvider to be synchronous, like 

```dart
final combiningProvider2 = Provider((ref) {
  final value1 = ref.watch(futureProvider1);
  final value2 = ref.watch(futureProvider2);

  if (value1 is! AsyncData) {
    return value1;
  }
  if (value2 is! AsyncData) {
    return value2;
  }
  return value1.value! + value2.value!;
});
```

Only one call to pump() is needed.

**Expected behavior**

I would expect some way to pump until all providers are settled without calling `pump()` in a loop.

In my opinion, it should be an implementation detail on how many other providers one providers listens to and adding additional providers should not make we having to rewrite my tests (by adding additional calls to pump)).

**Comment by rrousselGit** [comment]
The pump itself isn't doing anything here. Rather you're awaiting until the provider completes.

You should be able to instead do:

```dart
final sub = container.listen(combiningProvider.future, ...);

print(await sub.read());
```

**Comment by knaeckeKami** [comment]
Thanks for the quick response.

using .future solves this issue, indeed.
