### ISSUE TITLE
DevTools: ProviderScope.state.container.overrideForProvider._bucket shows a grey widget

### ISSUE THREAD

**Issue by ValentinVignal** [rrousselGit/riverpod#1541]
**Describe the bug**
When opening `ProviderScope.state.container.overrideForProvider._bucket` in the devtool, there is a grey (I guess flutter error) widget (see image)

I'm not too familiar with the dev tool implementation so maybe it is an issue with the flutter devtool itself.
**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      child: MaterialApp(
        title: 'Flutter Demo',
        home: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text(
          'Riverpod',
        ),
      ),
    );
  }
}
```

You can also checkout https://github.com/ValentinVignal/flutter_app_stable/tree/riverpod/devtool

**Expected behavior**

There should not be any grey/error widget

<img width="665" alt="image" src="https://user-images.githubusercontent.com/32538273/183333515-fe55dc57-06d0-45f6-b6df-6ecc7892d266.png">

**Comment by rrousselGit** [comment]
That's not specific to Riverpod. It's a generic tool that applies to any dart code and isn't maintained by me

I'd suggest making an issue on the devtool for this. Ideally with a way to reproduce it without Riverpod.
