### ISSUE TITLE
Does `copyWithPrevious` not work automatically with StateProvider/StateNotifierProvider anymore?

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/riverpod#1551]
**Describe the bug**

`copyWithPrevious` doesn't work automatically with StateProvider/StateNotifierProvider on master latest (73e656f).

I noticed that `copyWithPrevious` of https://github.com/rrousselGit/riverpod/blob/e72c30d83ed37a9727fba5d47682f63f60481142/packages/riverpod/lib/src/framework/provider_base.dart#L301 was removed by https://github.com/rrousselGit/riverpod/commit/f36e968f995d7ce9da2db61f0d580f7c5ffa9a63#diff-7c816cec9b846943e23c9577fcb45a6bdeed95a20b7a87f333f24f28e8201b7aL301.

**To Reproduce**

```dart
import 'package:riverpod/riverpod.dart';
import 'package:test/test.dart';

void main() {
  test('StateProvider preserves previous value', () {
    final container = ProviderContainer();
    addTearDown(container.dispose);

    final read = container.read;

    expect(read(fooProvider).isLoading, isFalse);
    expect(read(fooProvider).hasValue, isTrue);

    read(fooProvider.notifier).update((_) => const AsyncLoading());
    expect(read(fooProvider).isLoading, isTrue);
    // Succeeds on v2.0.0-dev.9 but fails on master latest (73e656f)
    expect(
      read(fooProvider).hasValue,
      isTrue,
      reason: 'Preserve previous value',
    );
  });
}

final fooProvider = StateProvider<AsyncValue<int>>((ref) => const AsyncData(1));
```

**Expected behavior**

The test above succeeds on master latest and next release.

**Comment by mono0926** [comment]
Sorry, I overlooked the CHANGELOG 🙏 

> Providers other than FutureProvider/StreamProvider no-longer override AsyncValues to set AsyncValue.isRefreshing when an AsyncLoading is emitted.
https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/CHANGELOG.md#unreleased-major

I've figured out this is an intentional change 👌 

---

Also, if I write it this way, I can make it behave similarly as before:

```diff
-    read(fooProvider.notifier).update((_) => const AsyncLoading());
+    read(fooProvider.notifier).update(
+      (previous) => const AsyncLoading<int>().copyWithPrevious(previous),
+    );
```

**Comment by rrousselGit** [comment]
This is indeed expected.
It's less magical

It's not very natural that some specific values behave differently from others.

We'll have an Async variant of StateNotifierProvider, so that should cover the use-case
