### ISSUE TITLE
Changing values in nested objects produces so much boilerplate

### ISSUE THREAD

**Issue by MiroLiebschner** [rrousselGit/riverpod#1558]
Problem
Changing values in nested objects produces a lot of boilerplate code. 
This example uses freezer and riverpod. 

Solution 
A way to conveniently change a single value in a nested object.
Is there a way that I am not aware of?. 

Below is the code to change a single bool in a nested object.

<img width="608" alt="Screenshot 2022-08-14 at 19 04 10" src="https://user-images.githubusercontent.com/56092186/184547414-0ba40232-71db-4561-bfbc-6e453f7d5d29.png">

As code: 
```void addOrUpdateSingleScheduledRemidner(
      ScheduledReminderModel scheduledReminderModel) {
    state = state!.copyWith(
        reminder: state!.reminder.copyWith(
            categories: state!.reminder.categories.map((reminderCategoryModel) {
      if (reminderCategoryModel.id !=
          scheduledReminderModel.reminderCategoryId) {
        return reminderCategoryModel;
      } else {
        return reminderCategoryModel.copyWith(scheduledReminders: [
          ...reminderCategoryModel.scheduledReminders.map((e) {
            if (e.id == scheduledReminderModel.id) {
              return scheduledReminderModel.copyWith(
                  seenAt: e.seenAt, active: !e.active);
            }
            return e;
          }).toList(),
          // add the reminderCategoryModel to list if the reminderCategoryModel does not contain a scheduledReminderModel with the same id
          if (reminderCategoryModel.id ==
                  scheduledReminderModel.reminderCategoryId &&
              !reminderCategoryModel.scheduledReminders
                  .any((e) => e.id == scheduledReminderModel.id))
            scheduledReminderModel
        ]);
      }
    }).toList()));
  }

**Comment by TimWhiting** [comment]
I recommend using https://pub.dev/packages/fast_immutable_collections for immutable updates to collections. More optimized than manual updates of built in lists / maps and less boilerplate.

**Comment by rrousselGit** [comment]
This isn't really an issue with Riverpod, but rather an issue with immutable structures.

I assume you're using Freezed? I've been considering adding the following to Freezed:

```dart
var value;
value = value.update((valueBuilder) {
  valueBuilder.someList.add(42);
});
```

Kind of like built_value


In any case, there's not much Riverpod can do here. It's not directly at fault. So I'll close this.

You could either follow https://github.com/rrousselGit/freezed/issues/185 or https://github.com/rrousselGit/freezed/issues/685
