### ISSUE TITLE
Watching StateProvider triggers rebuild despite state being equal

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/riverpod#1560]
**Describe the bug**
I'm unsure if this is a bug or intended behaviour that needs some documentation.

When I use a StateProvider, I would expect that if the provider updated/refreshed with the same value, providers watching the StateProvider would NOT rebuild.

e.g.

```
final sourceProvider = StateProvider((ref) => 0);

final watchProvider = FutureProvider<int>((ref) async {
  // I would expect that this provider would only update when the value of sourceProvider
  // changes.
  // Instead it updates whenever the sourceProvider updates, even when the value is equal to the previous
  // value
  final source = ref.watch(sourceProvider);
  await Future.delayed(const Duration(seconds: 2));
  return source;
}, dependencies: [
  sourceProvider,
]);
``` 

If I use select on the sourceProvider, it works as intended; dependent providers do not update if the value is equal to the previous value.

```
final source = ref.watch(sourceProvider.select((v) => v));
```

**To Reproduce**

Here is a dart pad that demonstrates the issue: https://dartpad.dev/?id=5184e6b4702f5d82040194cab308bc46

**Expected behavior**
I would expect that I can simply watch a StateProvider and by default it should filter out any duplicate updates.
If that is not the intended behaviour, it is not obvious.

**Comment by rrousselGit** [comment]
Thanks for the clear report, that was very helpful!
