### ISSUE TITLE
Refreshing provider while using UseEffect to initialize its value throws an Exception

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#1564]
I have a large list of Widgets in Screen A, each widget have an object that I'm passing to screen B.
After navigating to Screen B, I initialize the passed object to an `AutoDisposeStateProvider` by using `useEffect` to only call it once inside the build (I need to use that StateProvider as i'll use that object in other nested screens/components down the tree). 

Everything works fine until I try to refresh that StateProvider then I get an exception `Unhandled Exception: setState() or markNeedsBuild() called during build`.

I understand that the exception is occurred because when refreshing the provider we're trying to update its value inside the build (inside the useEffect) But I'm unable to find another solution to initialize that object to the provider. Also, I found the useEffect solution recommended [here](https://github.com/rrousselGit/flutter_hooks/issues/302#issuecomment-1124732760).

I've made a simulated sample code for the issue using a simple counter example:

```
final counterProvider = StateProvider.autoDispose<int>((ref) => 0);

class CounterListScreen extends StatelessWidget {
  const CounterListScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const CounterItemScreen(initialCount: 5),
                  ),
                );
              },
              child: const Text('Go To Counter Page'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const CounterItemScreen(initialCount: 3),
                  ),
                );
              },
              child: const Text('Go To Counter Page'),
            ),
          ],
        ),
      ),
    );
  }
}

class CounterItemScreen extends HookConsumerWidget {
  const CounterItemScreen({
    required this.initialCount,
    Key? key,
  }) : super(key: key);

  final int initialCount;

  @override
  Widget build(BuildContext context, ref) {
    final _counterNotifier = ref.watch(counterProvider.notifier);
    useEffect(() {
      _counterNotifier.state = initialCount;
      return null;
    }, [_counterNotifier]);

    final _currentCount = ref.watch(counterProvider);

    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'current count: ' + _currentCount.toString(),
              style: const TextStyle(
                color: Colors.red,
              ),
            ),
            ElevatedButton(
              onPressed: () {
                ref.refresh(counterProvider);
              },
              child: const Text('Reset Counter'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Describe the bug**
```
E/flutter (30227): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (30227): This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
```

**Comment by rrousselGit** [comment]
Hello! That's expected. This error exists on purpose to tell that you're doing something wrong

You should not modify providers while widgets are building. Say a widget previously built using `_counterNotifier`, and another widget later updates it: For some frames, you'll have an incoherent rendering. One widget will show one thing, and another one will show another thing.

Hence, that's not allowed.

Either put that logic in a place where it is not executed when widgets are building, or execute it asynchronously.

**Comment by AhmedLSayed9** [comment]
Thanks for the fast response!

so, the useEffect solution mentioned [here](https://github.com/rrousselGit/flutter_hooks/issues/302#issuecomment-1124732760) isn't recommended as it could produce the same issue?

and if so, where could I put that logic for example? I've thought of putting it inside onPressed of each item but that won't work as I'm using an AutoDisposeStateProvider.

**Comment by rrousselGit** [comment]
The example you linked is different. It's not synchronously modifying the state. It's triggering a network request, which resolves asynchronously

What you did is synchronously modifying a provider, that's a different story.


Putting the logic inside an onPressed should be fine. I don't see why autoDispose would be an issue.

**Comment by AhmedLSayed9** [comment]
You're right. So, behind the scenes synchronously modifying the state inside didUpdateWidget(didUpdateHook) is what causing the issue.

Putting the logic inside the onPressed (Which is inside CounterListScreen) isn't fine with the AutoDisposeStateProvider (which is first watched at CounterItemScreen). It'll instantly call and dispose the Provider before navigating to CounterItemScreen

**Comment by rrousselGit** [comment]
You didn't asynchronous modified the state though. You still synchronously modified it

Asynchronous modification would be after the await

**Comment by AhmedLSayed9** [comment]
Oh yes, It's the same at the end.

I think I'll stick with just initializing the provider through initHook and avoid modifying it in didUpdateHook by passing empty list of keys. Can't find a better approach for this case. Thanks!

**Comment by AhmedLSayed9** [comment]
Note: initializing the provider through initHook will also through exception if that provider is used already in the widget tree, which will make no sense in my case as I'm using it at CounterItemScreen for the first time otherwise i'd initialized it in the onPressed of the previous screen using ref.read. So, It'll work fine but I'm still confusing if it's a right way.

Also, I've thought of using ref.watch in the prev screen and initializing the provider inside the onPressed, but that would cause the prev screen (a big list in my case) to unnecessary rebuild when calling ref.refresh. here's the example:
```
final counterProvider = StateProvider.autoDispose<int>((ref) => 0);

class CounterListScreen extends ConsumerWidget {
  const CounterListScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ref) {
    print('unnecessary rebuild');
    final _counterNotifier = ref.watch(counterProvider.notifier);

    return Scaffold(
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                _counterNotifier.state = 5;
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const CounterItemScreen(),
                  ),
                );
              },
              child: const Text('Go To Counter Page'),
            ),
            ElevatedButton(
              onPressed: () {
                _counterNotifier.state = 3;
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const CounterItemScreen(),
                  ),
                );
              },
              child: const Text('Go To Counter Page'),
            ),
          ],
        ),
      ),
    );
  }
}

class CounterItemScreen extends HookConsumerWidget {
  const CounterItemScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ref) {
    final _currentCount = ref.watch(counterProvider);

    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'current count: ' + _currentCount.toString(),
              style: const TextStyle(
                color: Colors.red,
              ),
            ),
            ElevatedButton(
              onPressed: () {
                ref.refresh(counterProvider);
              },
              child: const Text('Reset Counter'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by AhmedLSayed9** [comment]
After some research and reading the great discussion in https://github.com/rrousselGit/riverpod/issues/1329, I've ended up with initializing the data in `onPressed` and delaying the auto dispose for milliseconds using `disposeDelay` parameter.

Also, I liked the suggested idea of ref.listen + close after popping Screen B like following:
```
final _initSelectedTimesheetAndNavigate = useCallback(() async {
  final container = ProviderScope.containerOf(context);
  final _sub = container.listen<TimesheetModel?>(
      selectedTimesheetProvider, (prev, value) {});
  ref.read(selectedTimesheetProvider.notifier).state = timesheetModel;
  await NavigationService.push(
    isNamed: true,
    page: RoutePaths.timesheetDetails,
  );
  _sub.close();
}, []);
```
But that's a lot of code and in my case I've two different ways of navigating to screen B, one with push and one with pushReplacement. so I've to double that callback or make an if statement to push/push replacement. I like the idea but I'll wait for more simplified way, maybe the one mentioned [here](https://github.com/rrousselGit/riverpod/issues/1329#issuecomment-1091224116)
