### ISSUE TITLE
Introduce `when(isRefreshing)` to `AsyncValue` as an optional parameter.

### ISSUE THREAD

**Issue by krjw-eyev** [rrousselGit/riverpod#1570]
As discussed in #1568 I think there are use cases to do the following:

```dart
counter.when(
  data: (data) => Text(
      '$data',
      style: Theme.of(context).textTheme.headline4,
    ),
  error: (error, stackTrace) => const Text('error'), 
  loading: () => const CircularProgressIndicator(),
  isRefreshing: () => const CircularProgressIndicator());
```

Instead of:

```dart
if (counter.isRefreshing) {
  return Loading();
}

return counter.when(
  data: (data) => Text(
      '$data',
      style: Theme.of(context).textTheme.headline4,
    ),
  error: (error, stackTrace) => const Text('error'), 
  loading: () => const CircularProgressIndicator());
```

Especially in cases when the `AsyncValue` is encapsulated in a styling which should also apply to the `isRefreshing` part.

I think `isRefreshing` could be an optional parameter which adds the desired behaviour.

**Comment by rrousselGit** [comment]
We'd probably have to pass the `data` and `error/stack` to the callback

**Comment by rrousselGit** [comment]
About this, I have an alternate proposal:

```dart
asyncValue.when(
  optimistic: false,
  error: ...,
  data: ...,
  loading: ...,
)
```

This would forcibly go into `loading` even during `isRefreshing`
And if you want to access the previous data/error, you could do:

```dart
asyncValue.map(
  optimistic: false,
  error: ...,
  data: ...,
  loading: (AsyncLoading<T> loading) {
    print(loading.value);
    print(loading.error);
  },
)
```

**Comment by rrousselGit** [comment]
And this could be used in the opposite way too, to skip showing the "loading" when a provider rebuilds because of `ref.watch`.
Currently if a provider rebuilds because of ref.watch, the UI will enter "loading" even for a split second.


But with such flag, the UI could do:

```dart
asyncValue.when(
  // forcibly loading
  optimistic: true,
  error: ...,
  data: ...,
  loading: ...,
)
```

**Comment by rrousselGit** [comment]
By default, `optimistic` would be `null`. This would mean "default to whatever the provider tells you".

So:
- if a provider rebuilds because of `ref.watch` -> optimistic: false
- if the rebuild is caused by `ref.refresh` -> optimistic: true


This would allow having a good default behavior while allowing users to opt-in to whatever fits their case.

**Comment by AhmedLSayed9** [comment]
I think there should be an easy option to allow going into `loading` during `isRefreshing` only when the prev state is `error`.

It'd be more helpful to show prev data to user when refreshing but when prev state is `error` go into `loading`.

i.e: if `optimistic` is set to `true` and the user couldn't fetch data at first time, I'm showing him an Error widget with a `Retry` button. When pressing that button the user won't be able to know that i'm retrying to fetch data.

**Comment by AhmedLSayed9** [comment]
> if a provider rebuilds because of ref.watch

Can you elaborate when this can happen?

**Comment by rrousselGit** [comment]
> I think there should be an easy option to allow going into loading during isRefreshing only when the prev state is error.

You're free to do:

```dart
asyncValue.when(
  optimistic:!asyncValue.hasError
 ...
)
```

**Comment by rrousselGit** [comment]
But the behavior you're describing is the default when using "ref.invalidate(provider)"

**Comment by AhmedLSayed9** [comment]
Current the behavior when I'm doing `ref.refresh`:
* if state is data: keep showing the latest data
* if state is error: keep showing the latest error

What I'm looking for is when doing `ref.refresh`:
* if state is data: keep showing the latest data
* if state is error: show loading

I think `optimistic:!asyncValue.hasError` will do the trick.

**Comment by rrousselGit** [comment]
Could you explain why?

**Comment by AhmedLSayed9** [comment]
This will allow me to do:
```
asyncValue.when(
  instant: true,
  optimistic: !asyncValue.hasError, 
  error: ...,
  data: ...,
  loading: ...,
)
```
I'll be able to show loading only when refreshing from a `Retry` button when prev state is `error`.

**Comment by rrousselGit** [comment]
I don't understand. How is that different from without this `instant` flag?

**Comment by AhmedLSayed9** [comment]
It'll skip loading when the provider rebuilds from `ref.watch`

**Comment by rrousselGit** [comment]
Yes, but again, how is that any different from without the flag?

Doing:

```dart
asyncValue.when(
  optimistic: !asyncValue.hasError, 
  error: ...,
  data: ...,
  loading: ...,
)
```

should already skip `loading` during a refresh after a data, while showing loading during a refresh after an error

**Comment by AhmedLSayed9** [comment]
but how to show loading during a refresh by `ref.refresh` after an error. and to skip loading if a refresh was by `ref.watch`.

**Comment by rrousselGit** [comment]
That's what this snippet does. Doesn't it?

**Comment by AhmedLSayed9** [comment]
I think that snippet will show loading if a provider rebuilds because of both `ref.refresh` or `ref.watch` after an error

**Comment by AhmedLSayed9** [comment]
My point is this:

**Relying on 1 param `optimistic`:**
* `default null`:
  * rebuilds because of ref.watch -> back to loading
  * rebuilds because of ref.refresh -> showing latest data/error
* `true`:
  * rebuilds because of ref.watch -> showing latest data/error
  * rebuilds because of ref.refresh -> showing latest data/error
* `false`:
  * rebuilds because of ref.watch -> back to loading
  * rebuilds because of ref.refresh -> back to loading

* 1 case missing here which is the reverse of default null.


**This can be solved by relying on 2 params:**

`instant`:
* `default false`:
  * rebuilds because of ref.watch -> back to loading
* `true`:
  * rebuilds because of ref.watch -> showing latest data/error
  
`optimistic `:
* `default true`:
  * rebuilds because of ref.refresh -> showing latest data/error
* `false`:
  * rebuilds because of ref.refresh -> back to loading 
 
This will cover all cases and allow users to fully control this.
Hope I'm not missing something that invalidates all my point 🫠

**Comment by rrousselGit** [comment]
> I think that snippet will show loading if a provider rebuilds because of both ref.refresh or ref.watch after an error


I see. This can be tweaked without a new flag using `is AsyncLoading`

If rebuilding by `ref.watch`, then the AsyncValue is an AsyncLoading (hence why it defaults to `when(loading)`). If it rebuilds from `refresh`, then it's obtained as `AsyncError` (hence the `when(error)`)

You could do:

```dart
optimistic: asyncValue is AsyncLoading && !asyncValue.hasError
```

**Comment by rrousselGit** [comment]
Of course, this is obviously more complex than a simple boolean.

If there's a better solution, I'm open for it. But I'll admit, I'm still very confused by what exactly this parameter does. Its name is a big issue I think.   
At a glance, it sounds like both flags do the same thing.

If two flags make things simpler, I'm up for it. But we'll need to find a new name for that flag I think. Possibly renaming both flags too (as `optimitic` as a name might not make sense anymore).

**Comment by AhmedLSayed9** [comment]
I think two flags is simpler.

i.e: this will achieve what I was trying to discuss:
```
optimistic: asyncValue is AsyncLoading || !asyncValue.hasError
```
It's tricky and very hard to understand, while with two flags:
```
instant: true
optimistic: !asyncValue.hasError
```

I agree with renaming both flags. It would make this more understandable.

**Comment by rrousselGit** [comment]
I'm personally very confused with your proposal, as you can see.  
For now, I don't find it simpler. I still fail to see what this `instant` variable exactly does.

I understand the problem. I just fail to see how the proposal maps to the problem.

**Comment by rrousselGit** [comment]
First, I think an obvious thing to do is to add an `isReloading` flag, such that we have:

```dart
asyncValue.isRefreshing; // whether the provider rebuilt due to ref.refresh/invalidate
asyncValue.isReloading; // did the provider rebuild because of ref.watch
```

I think "isReloading" is a decent name for that.

___

Then we need to find all the scenarios we need to support.
I can think of a few scenarios:

```
Case 1 (default, typically combined with RefreshIndicator)
Show loading on recomputation
during refresh, keep showing the previous state/error

Case 2
Show data during data refresh
Show loading on recomputation
Show loading on error refresh

Case 3
Always loading during either refresh or reload

Case 4
Always show value if available, even if there's an error
```

Am I missing a case?

**Comment by rrousselGit** [comment]
If I'm not missing a case, we could have:

```dart
when(
  skipLoadingOnRefresh: true,
  skipLoadingOnReload: false,
)
```
And maybe have an optional shorthand:

```dart
when(
  skipAllLoading: // appies to both onRefresh/onReload
)
```

Then maybe do the same for `skipErrorOnRefresh/Reload`/`skipAllError`. WIth possibly a unique `skipResolvedErrors` (to skip actual errors if a valid data was emitted before)

That could be more in line with the use-cases that people have.

**Comment by AhmedLSayed9** [comment]
Exactly. isRefreshing/isReloading is needed to achieve this (one of them is enough to cover all cases).

I think case 2 is inappropriate. It should be just the opposite of case 1, so:
Show loading during refresh
keep showing the previous data/error on recomputation

as we consider the data/error as a unit and loading as a unit.
In my case above, I'll just do handle it by `!asyncValue.hasError`.

to clear this more let's rename the 2 params:
* optimistic: `showLatestWhenRefresh` 
* instant: `showLatestWhenWatch` 

`showLatestWhenRefresh`: controls if latest data/error will show when rebuild because of ref.refresh (default is true)
`showLatestWhenWatch`: controls if latest data/error will show when rebuild because of ref.watch (default is false)

so, Here's the application of this on `when` method:
```
R when<R>({
  bool showLatestWhenRefresh = true,
  bool showLatestWhenWatch = false,
  required R Function(T data) data,
  required R Function(Object error, StackTrace stackTrace) error,
  required R Function() loading,
}) {
  if (showLatestWhenRefresh && !showLatestWhenWatch) {
    //rebuilds because of ref.refresh -> showing latest data/error
    //rebuilds because of ref.watch -> back to loading
    return map(
      data: (d) => data(d.value),
      error: (e) => error(e.error, e.stackTrace),
      loading: (l) => loading(),
    );
  } else if ((!showLatestWhenRefresh && showLatestWhenWatch)) {
    //rebuilds because of ref.refresh -> back to loading
    //rebuilds because of ref.watch -> showing latest data/error
    if (isRefreshing) {
      if (isLoading) return loading();
      if (hasError) return error(this.error!, stackTrace!);
      return data(requireValue);
    } else { //isReloading
      if (hasError) return error(this.error!, stackTrace!);
      if (hasValue) return data(requireValue);
      return loading();
    }
  } else if (showLatestWhenRefresh && showLatestWhenWatch) {
    //rebuilds because of ref.refresh -> showing latest data/error
    //rebuilds because of ref.watch -> showing latest data/error
    if (hasError) return error(this.error!, stackTrace!);
    if (hasValue) return data(requireValue);
    return loading();
  } else {
    //if (!showLatestWhenRefresh && !showLatestWhenWatch)
    //rebuilds because of ref.refresh -> back to loading
    //rebuilds because of ref.watch -> back to loading
    if (isLoading) return loading();
    if (hasError) return error(this.error!, stackTrace!);
    return data(requireValue);
  }
}
```

**Comment by AhmedLSayed9** [comment]
Alright. `skipLoading` name is more clear than `showLatest`. Will just need to reverse the conditions above 🤪

**Comment by AhmedLSayed9** [comment]
**Case 1** (default, typically combined with RefreshIndicator)
Show loading on recomputation
during refresh, keep showing the previous state/error
To Achieve: 
```
  skipLoadingOnRefresh: true, //Default
  skipLoadingOnReload: false, //Default
```

Case 2
Show loading during refresh
keep showing the previous data/error on recomputation
To Achieve: 
```
  skipLoadingOnRefresh: false,
  skipLoadingOnReload: true,
```

Case 3
Always loading during either refresh or reload
To Achieve: 
```
  skipLoadingOnRefresh: false,
  skipLoadingOnReload: false,
```

Case 4
Always show value if available, even if there's an error
To Achieve: 
```
  skipLoadingOnRefresh: true,
  skipLoadingOnReload: true,
```
or
```
  skipAllLoading:: true,
```

**Comment by AhmedLSayed9** [comment]
**Case 5**
Show previous data (if hasData) when in error state. or else, show error.

To Achieve:

`  skipError: true, //Default is false`

**Comment by AhmedLSayed9** [comment]
I don't get the idea of `skipErrorOnRefresh/Reload` / `skipAllError` / `skipResolvedErrors`.
skip them and show what instead?

I think just `skipError` to prioritize data if there's data is enough. In addition to `skipLoadingOnRefresh` & `skipLoadingOnReload`.

**Comment by rrousselGit** [comment]
> I don't get the idea of skipErrorOnRefresh/Reload / skipAllError / skipResolvedErrors.
skip them and show what instead?

Show data of course 😊

**Comment by rrousselGit** [comment]
Good call. I've added it to the documentation plan #1762

**Comment by kafendt** [comment]
Quick feedback: I think the flags are great but the defaults are exactly opposite to what I expected and also felt like a breaking change compared to version `2.0.x`. In `2.0.x` the provider by default kept the last value on a reload (without invalidation). In `2.1.x` the value was not cached by default as `skipLoadingOnReload = false` is the new default. This lead to my app now flashing everywhere when providers updated.

In my opinion
```
  skipLoadingOnRefresh: false,
  skipLoadingOnReload: true,
```
would be a saner default as it then only shows the loading state when the provider is actually refreshed/invalidated.

**Comment by rrousselGit** [comment]
Good catch. It should've been that way. Not sure how it ended up reversed

I'll fix it

**Comment by rrousselGit** [comment]
Wait no, I misread your post. The current values are correct

Why is your app flashing when providers are updated? Are they updated with ref.watch?
Not skipping ref.watch updates by default is desired, because the old data may be unrelated to the new data. In which case this could lead to an inconsistent UI

**Comment by rrousselGit** [comment]
At the same time, skipping loading on refresh in on by default, as the most common usage is with RefreshIndicator, which already shows a progress indicator.
So with it true by default, during refresh, it'd end-up showing two spinners at once.

**Comment by kafendt** [comment]
I know now why the behaviour was confusing for me. In my project we used the `2.0.0-dev.9` version. And in this version a e.g. `FutureProvider` didn't go into loading on reload. Obviously this is a dev version so my bad here that I though it was a breaking change. 

For further explanation, when you run the code below with version `2.0.0-dev.9` the UI did not flash when changing the value in the `TextFormField`. With any `2.x.x` it does, which I now understand is the desired behaviour.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ExampleApp());
}

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      child: MaterialApp(
        home: HomePage(),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Example')),
      body: const SomeWidget(),
    );
  }
}

final listProvider = FutureProvider((ref) async {
  await Future.delayed(const Duration(seconds: 1));
  return ["foo", "bar", "baz"];
});

final stringProvider = StateProvider((ref) => "");

final filteredListProvider = FutureProvider((ref) async {
  final list = await ref.watch(listProvider.future);
  final filterString = ref.watch(stringProvider);
  return list.where((it) => it.contains(filterString));
});

class SomeWidget extends ConsumerWidget {
  const SomeWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final filteredListAsync = ref.watch(filteredListProvider);

    return Column(
      mainAxisSize: MainAxisSize.max,
      children: [
        TextFormField(
          onChanged: (value) => ref.read(stringProvider.notifier).state = value,
        ),
        Expanded(
          child: filteredListAsync.when(
            data: (filteredList) => ListView(
              children: filteredList.map((it) => Text(it)).toList(),
            ),
            loading: () => const CircularProgressIndicator(),
            error: (error, stack) => const Text("Error"),
          ),
        ),
      ],
    );
  }
}
```

To be honest, for me the default behaviour should still be that the provider doesn't go into the loading state such that the UI doesn't flash in the default case. I will now add the `skipLoadingOnReload: true` to almost all of my `when` calls. Do you think it might be possible to override the default somewhere globally? E.g. in the `ProviderScope` like so:

```dart
class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      defaultSkipLoadingOnReload: true,
      child: MaterialApp(
        home: HomePage(),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
Feel free to make your own `when` if you don't like the current behavior. An extension on `AsyncValue` should make this easy

Having ref.watch updates skip the loading and instead show previous data would be dangerous. That's the reason why the dev version was reverted.   
There were some complaints where some people did something among the lines of :

```dart
final user = FutureProvider<User>((ref) async {
  final userId = ref.watch(userIdProvider);
  return fetch(/users/$userId);
})
```

This meant that when the user ID changes, the screen will keep showing information about the previous user instead.
This makes no sense as now a different user is signed in. The consequences of that can be pretty bad

**Comment by switches-01** [comment]
ref.listen(secureEntryLoginStateNotifierProvider, (previous, next) {
      final loginFailed = ((previous?.isLoading ?? false) &&
          !(next.valueOrNull?.isLoggedIn ?? false));
      if (loginFailed) {
        ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text("Incorrect Credential")));
      }
    });

i don't know if for AsyncValue should have both isLoading and hasData true simultaneously.
i am trying to know if the data logging in failed by checking if the pervious state was loading and the next state is not logged in, or am i doing it wrong?
