### ISSUE TITLE
Am I allowed to `ref.watch` in a `FutureProvider` across async gap?

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/riverpod#1603]
For example,

```
final myProvider = FutureProvider<Something>((ref) async {
  final a = ref.watch(aProvider);
  final b = await fetchNetworkData(a);
  final c = ref.watch(cProvider); // <---- NOTE this line
  return ...;
});
```

If it is supported, maybe the doc can mention it a little bit, because I am familiar with MobX which *does not* support this. Given popularity of MobX, I guess many people will have the same confusion as me, so doc is helpful.

If it is not supported, then this issue is a feature request :)

**Comment by TimWhiting** [comment]
Yes, it is supported.

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by rrousselGit** [comment]
There are no constraints on when to call `ref.watch`/`ref.read`, only good/bad practices.  

For example, you can call `ref.read` inside `build`. It's considered a bad idea, but you can. Same goes for `ref.watch` inside a button's `onPressed`.

**Comment by levi956** [comment]
But could those bad practices cause breakage/exceptions or unnecessary widget rebuilds?

**Comment by rrousselGit** [comment]
No that should be fine

It'll behave as you would expect: if the watched provider changes, the
widget/provider will rebuild.


Le sam. 10 sept. 2022 à 01:38, Nifesi Odumirin ***@***.***> a
écrit :

**Comment by iLoveDocs** [comment]
@rrousselGit 

As you mentioned, 

> if the watched provider changes, the widget/provider will rebuild.

But it doesn't seem to be working as expected. Could you please take a look at [this question on StackOverflow](https://stackoverflow.com/q/73843189/12483095)?
