### ISSUE TITLE
Apparently there is missing lines to be pushed in master branch

### ISSUE THREAD

**Issue by kranfix** [rrousselGit/riverpod#1605]
**Describe the bug**

StateNotifierProviderElement.runOnDispose is broken in compile time because the method `updateShouldNotify` is applied to a notifier instead of a provider.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/1251381/188483414-dfa95bdd-a8f6-4c76-91e9-cdbd52531296.png">

**To Reproduce**

- Clone master branch from scratch.
- Run `flutter pub get` in `packages/riverpod`
- Open the file `packages/riverpod/lib/src/state_notifier_provider/base.dart`
- Go to line 140.

The function is broken.

**Expected behavior**
It must not be broken and the code must compile.

**Comment by rrousselGit** [comment]
It's not broken, no.

That's probably your local environment the issue.

updateShouldNotify has been moved to the Element on all providers.

**Comment by kranfix** [comment]
But the `requireState` extends StateNotifier
<img width="741" alt="image" src="https://user-images.githubusercontent.com/1251381/188509893-50f1f4bb-2ba2-438f-ae4b-16c57e022c20.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1251381/188509946-e4020b3f-a1b8-45c1-a163-56d9e9ff3fcb.png">

**Comment by rrousselGit** [comment]
StateNotifier does have an updateShouldNotify method

**Comment by rrousselGit** [comment]
StateNotifier does have an updateShouldNotify method

**Comment by kranfix** [comment]
Yup, you are right. My `pubspec.lock` was using `state_notifier:0.7.0` instead of `0.7.2`. Thank you
