### ISSUE TITLE
create new provider like ChangeNotifier, but for dart only code

### ISSUE THREAD

**Issue by jibbers42** [rrousselGit/riverpod#1623]
**Is your feature request related to a problem? Please describe.**
I have an app that has a cli and a gui (flutter) with common code backing them. I did a feature in the gui first and used `ChangeNotifier` since it seemed to be the easiest for that need - which worked fine. I ran into a compiler crash issue when I updated the cli side to use the common code. When I looked further, I realized `ChangeNotifier` comes from flutter and attempting to use that code with dart would crash (`dart run .\bin\my_cli_entry_point.dart`).

**Describe the solution you'd like**
I'd like a mutable state alternative to `ChangeNotifier` that works in dart only code, perhaps `MutableStateNotifier`.

**Describe alternatives you've considered**
I rewrote it using `StateNotifier`, but it seems a bit awkward compared to the `ChangeNotifier` implementation (for this use case).

**Additional context**
I'm using `StorageBox` to store some simple settings locally. Their internals write to a local file without an obvious way to mock out for testing, so I make a `StorageBoxWrapper` that I can fake for tests.
```dart
class StorageBoxWrapper {
  StorageBoxWrapper() : _sb = _initStorageBox();

  final StorageBox _sb;

  String operator [](String key) {
    return tryCast(_sb[key], '');
  }

  void operator []=(String key, String value) {
    _sb[key] = value;
  }

  static StorageBox _initStorageBox() =>
      StorageBox('settings', configPathPrefix: productId);
}
```

My original code basically just delegated to the wrapper:
```dart
class Settings extends ChangeNotifier {
  Settings({StorageBoxWrapper? storageBoxWrapper})
      : _sbw = storageBoxWrapper ?? GetIt.I<StorageBoxWrapper>();

  @visibleForTesting
  static const String key_apiKey = 'apiKey';

  final StorageBoxWrapper _sbw;

  String get apiKey {
    return _sbw[key_apiKey];
  }

  void setApiKey(String newApiKey) {
    final oldApiKey = apiKey;

    if (newApiKey != oldApiKey) {
      _sbw[key_apiKey] = newApiKey;
      notifyListeners();
    }
  }
}
```

My `StateNotifier` code:
```dart
@freezed
class Settings with _$Settings {
  factory Settings({required String apiKey}) = _Settings;
}

class SettingsNotifier extends StateNotifier<Settings> {
  SettingsNotifier({StorageBoxWrapper? storageBoxWrapper})
      : _sbw = storageBoxWrapper ?? GetIt.I<StorageBoxWrapper>(),
        super(Settings(apiKey: storageBoxWrapper?[key_apiKey] ?? ''));

  final StorageBoxWrapper _sbw;

  @visibleForTesting
  static const String key_apiKey = 'apiKey';

  void setApiKey(String newApiKey) {
    final oldApiKey = state.apiKey;

    if (newApiKey != oldApiKey) {
      _sbw[key_apiKey] = newApiKey;
      state = state.copyWith(apiKey: newApiKey);
    }
  }
}
```

In the new code, state is separate from the wrapper, but both need to be updated and maintained. Also, the client needs to get a different object depending on if they are reading or writing. During creation, I need to supply `super` with an initial state object which is just what the wrapper already knows.

All that said, it's entirely possible I could have done things in a better way, if I knew more, and then not felt like the new solution was more awkward.

**Comment by jibbers42** [comment]
Sorry, this is my first time using Riverpod and I don't immediately understand how I would use that. Would it be like my original `Settings` class, but it takes a `ref` object in constructor and does not extend `ChangeNotifier`? Then I could call `ref.notifyListeners()` in the same place I had called `notifyListeners()` before? Where does the `ref` come from?

**Comment by rrousselGit** [comment]
It's be like the StateNotifier variant, but you would do:

```dart
  void setApiKey(String newApiKey) {
    final oldApiKey = state.apiKey;

    if (newApiKey != oldApiKey) {
      _sbw[key_apiKey] = newApiKey;
      state.apiKey = newApiKey;
      ref.notifyListeners();
    }
  }
```

That "ref" would be passed to the constructor of the class by the provider.

**Comment by jibbers42** [comment]
If I'm following correctly, I think that would be fine. Thanks for quick response!
