### ISSUE TITLE
Wrong capitalization of providers by riverpod_generator

### ISSUE THREAD

**Issue by Quijx** [rrousselGit/riverpod#1624]
So i was taking a look at the pub example which uses riverpod_generator and noticed that the generated providers are all in upper camel case. These should be lower camel case because they are not classes and also to be consistent with the capitalization of handwritten providers.

**Comment by rrousselGit** [comment]
That would make the capitalization inconsistent, as sometimes the generated providers could be classes.

**Comment by Quijx** [comment]
Hmm... what do you mean by "generated providers could be classes"? So would you put the type of a class inside `ref.watch()`? as in
```dart
class SomeProvider extents ... {
...
}
```
and then `ref.watch(SomeProvider)`? How would that even work, since `SomeProvider` is of type `Type` and not of `ProviderListenable`?

**Comment by rrousselGit** [comment]
It's about providers with parameters.  
We may do `ref.watch(MyProvider(param))`

In which case `MyProvider` should be a class:

```dart
class MyProvider extends Provider<int> {
  MyProvider(param): super(...);
}
```

**Comment by Quijx** [comment]
Oh. ok. but then I would still argue that it is better to stay consistent with the dart convention, because they also behave differently. The classes you need to call and the others you don't. Otherwise it might be confusing and some people might try to do `ref.watch(NonClassProvider())` instead of `ref.watch(NonClassProvider)`. (To be fair, that would be a compile time error, so not that big of a deal.)
Alternatively you could generate an additional top level function
`MyProvider myProvider(params) => MyProvider(params);`. That way it would be both, consistent with the dart convention and in capitalization. It would still mean some providers need to be called and others don't, but again, compile time error, so no big deal.

**Comment by rrousselGit** [comment]
To be fair, I was already considering changing it.

Although for the fun fact, a function doesn't work. As there are multiple APIs that can do something like:

```dart
ref.invalidate(provider)
ref.invalidate(family)
ref.invalidate(family(param))
```
