### ISSUE TITLE
WidgetRef and Ref common interface

### ISSUE THREAD

**Issue by Zekfad** [rrousselGit/riverpod#1625]
**Is your feature request related to a problem? Please describe.**
I want to pass `ref` to function and I want to have common interface for `ref` from Widgets, Providers, Future Providers, etc.

**Describe the solution you'd like**
Make a common abstract class that all refs must implement.

**Describe alternatives you've considered**
Make all refs implement `Ref` class.

**Comment by rrousselGit** [comment]
Hello!

This has been requested before, but will not be implemented. WidgetRef is voluntarily dissociated from Ref.   
They aren't interchangeable, as there are subtle differences in behavior between them.

To begin with, you shouldn't use WidgetRef too much. Instead try to obtain a "real" Ref, one from a provider.

**Comment by Zekfad** [comment]
Hello!

Thank you for response.
