### ISSUE TITLE
Can `AutoDisposeStreamProvider<State>.originProvider`'s type be `AutoDisposeProviderBase<AsyncValue<State>>` instead of `ProviderBase<AsyncValue<State>>`?

### ISSUE THREAD

**Issue by ValentinVignal** [rrousselGit/riverpod#1634]
**Is your feature request related to a problem? Please describe.**

In `AutoDisposeStreamProvider<State>`, the type of the getter `originProvider` is `ProviderBase<AsyncValue<State>>`.
This was an issue when I wanted to override a `StreamProvider` with another one:

```dart
final streamProvider = StreamProvider.autoDispose<int>((ref) => Stream.value(0));

final mockStreamProvider = StreamProvider.autoDispose<int>((ref) => Stream.value(1));

ProviderScope(
  overrides: [
    streamProvider.overrideWithProvider(mockStreamProvider.originProvider),  // The argument type 'ProviderBase<AsyncValue<int>>' can't be assigned to the parameter type 'AutoDisposeProviderBase<AsyncValue<int>>'
  ],
),
```

**Describe the solution you'd like**

Is it possible to make `AutoDisposeStreamProvider<State>.originProvider`'s type be `AutoDisposeProviderBase<AsyncValue<State>>`?

**Describe alternatives you've considered**

Right now, I'm casting the type:

```dart
ProviderScope(
  overrides: [
    streamProvider.overrideWithProvider(mockStreamProvider.originProvider as AutoDisposeProviderBase<AsyncValue<int>>),
  ],
),
```

**Comment by rrousselGit** [comment]
What are you trying to do with this exactly? Why do you read `originProvider`?

**Comment by ValentinVignal** [comment]
I have a `StreamProvider.autoDispose` I want to override (for a test) with a `Stream`.
I want to verify the data on screen (or in the other providers that depend on this `StreamProvider` are correct) are correctly updated when the streams gets new data.

I'm trying to do something like that:

```dart
final streamController = StreamController<int>();

final streamProviderMock = StreamProvider.autodispose<int> ((ref) => streamController.stream);

tester.pumpWidget(
  ProviderScope(
    overrides: [
      myStreamProvider.overrideWithProvider(/** Whatever is correct */),
    ],
    child: const MyWidget(),
  ),
),

// Dump some data in the stream.

streamController.add(1);
await tester.pump();

expec(/** What I need to verify */);

// Dump new data in the stream.

streamController.add(2);
await tester.pump();

expec(/** Verify the data are being correctly updated */);

```

So what I want to do is to override the stream provider using data from a `SreamController` that I'm controlling.

**Comment by rrousselGit** [comment]
But why pass `originProvider`? Why not just do:

```dart
      myStreamProvider.overrideWithProvider(streamProviderMock),
```

**Comment by ValentinVignal** [comment]
That is a good question...

I thought I already tried but apparently not because it worked...

I don't know what I did but when I tried, the static analysis was passing, but at runtime, I was having a casting issue. It was throwing an error saying a `XxxProvider` couldn't be used as a `YyyProvider`. But I can't to reproduce it.

Thank you.
