### ISSUE TITLE
Fix a misspelled word in the code

### ISSUE THREAD

**Issue by skreborn** [rrousselGit/riverpod#1637]
The word "fourth" (meaning number four in a list) is consistently misspelled as "forth" (meaning onward) in the code. I've gone ahead and replaced all occurrences with no issue, but I'm afraid it's a little more complicated than that, as there are a few parallel branches being worked on at the time, so I thought the next best thing was to let you know.

```dart
final AutoDisposeProvider<String> futureProvider = provider;

expect(provider.first, 42);
expect(provider.second, 'x42');
expect(provider.third, .42);
expect(provider.forth, false); // <--- here
expect(provider.fifth, ['x42']);

final String result = container.read(
  FamilyProvider(
    42,
    second: 'x42',
    third: .42,
    forth: false, // <--- here
    fifth: ['x42'],
  ),
);

expect(
  result,
  '(first: 42, second: x42, third: 0.42, forth: false, fifth: [x42])', // <--- and here
);

// and a bunch more just like it
```

---

_Let's face it; most likely nobody cares about this. It's not a bug, it's not a missing feature, it's barely even noticeable if you look hard enough, and it most definitely isn't an issue for end-users of the library. I was just going through the recent changes for the codegen component and it was simply bothering me._

**Comment by rrousselGit** [comment]
Thanks for the report!
