### ISSUE TITLE
.dispose() not triggering the didDisposeProvider method in ProviderObserver

### ISSUE THREAD

**Issue by TreyThomas93** [rrousselGit/riverpod#1641]
**Describe the bug**
Calling _ref.read(myStateProvider.notifier).dispose()_ does not trigger the didDisposeProvider method in ProviderObserver.

**To Reproduce**

***State Provider***
```
final weeklistFacilitiesProvider =
    StateProvider.autoDispose<List<String>>((ref) {
  final facilities = getIt<CacheService>()
      .weeklists
      .values
      .map((e) => e.facility)
      .toSet()
      .toList();

  return facilities;
}, name: "WeeklistFacilitiesProvider");
```

***State Notifier***
```
class WeeklistsNotifier extends StateNotifier<DataStatus> {
  WeeklistsNotifier(this.ref) : super(const DataStatus.loading()) {
    fetchWeeklists();
  }

  final Ref ref;

  final _cacheService = getIt<CacheService>();
  final _loggerService = LoggerService(WeeklistsNotifier);

  @override
  void dispose() {
    ref.read(weeklistFacilitiesProvider.notifier).dispose();
    super.dispose();
  }
}
```

***ProviderObserver***
```
class RiverPodLogger extends ProviderObserver {
  final _loggerService = LoggerService(RiverPodLogger);

  @override
  void didAddProvider(
      ProviderBase provider, Object? value, ProviderContainer container) {
    if (provider.name?.contains(".notifier") == true) return;
    _loggerService
        .v("[Riverpod] Adding ${provider.name ?? provider.runtimeType}");
  }

  @override
  void didDisposeProvider(ProviderBase provider, ProviderContainer containers) {
    if (provider.name?.contains(".notifier") == true) return;
    _loggerService
        .d("[Riverpod] Disposing ${provider.name ?? provider.runtimeType}");
  }
}
```

**Expected behavior**
I expect the method to be called just like when .autoDispose is added. 
.autoDispose triggers this no problem.

**Comment by rrousselGit** [comment]
Hello!

This is expected. Rather than disposing the StateNotifier, you want to dispsoe the provider.

**Comment by TreyThomas93** [comment]
@rrousselGit Thanks for the fast response! What should the syntax be then instead of ref.read(myStateProvider.notifer).dispose()?

Thanks!

**Comment by TreyThomas93** [comment]
@rrousselGit The issue with autoDispose is that when I assign a value to the stateprovider and then go to read the new value elsewhere, my data is reset to default value. So I am unable to use autoDispose and have to resort to manually doing it. I want to dispose all the unused providers to ease my memory consumption within the app.

And I believe you had stated that ref.invalidate will be included in version 2.0.0. When will that be released and will it accomplish what I am trying to do?

Thanks

**Comment by rrousselGit** [comment]
A dev release of the 2.0 is already available. A stable release should come soon

**Comment by TreyThomas93** [comment]
Upgrade to 2.0.0-dev.9 and called _ref.invalidate(weeklistFacilitiesProvider)_, but the _didDisposeProvider_ method in ProviderObserver did not trigger until I attempted to read the provider again.

**Comment by rrousselGit** [comment]
Could you maybe raise a separate issue about this with a way to reproduce the described behavior?

From my tests, calling `ref.invalidate` does call `didDidsposeProvider`.

**Comment by rrousselGit** [comment]
In the meantime, I'll close this issue, as the behavior described by this issue is expected.
