### ISSUE TITLE
`.update()` for the new `AsyncNotifier` only work for first time, the previous `state` from the callback never change

### ISSUE THREAD

**Issue by yeyaowei** [rrousselGit/riverpod#1643]
**How to reproduce**

I just basically copied the code from the pull request for the new syntax #1565 
```dart
class CounterNotifier extends AsyncNotifier<int> {
  @override
  FutureOr<int> build() async {
    return 0;
  }

  Future<int> increment() {
    return update((state) => state + 1);
  }
}

final counterProvider = AsyncNotifierProvider<CounterNotifier, int>(CounterNotifier.new);
```
And I call the `increment` method like usual
```dart
ref.read(counterProvider.notifer).increment();
```

After I first call the method, the state successfully turned in to `1`. But then I call it again the state will never change, it always stays in `1`.

The previous `state` from the callback parameter is always `0`, which is not the state I updated from the first increment call.

Am I using it wrong? For the synchronous version `Notifier` it's working fine.

**Comment by rrousselGit** [comment]
The Notifier API isn't released yet as it's still WIP.
There are still some bugs to fix.
