### ISSUE TITLE
Add ability to listen to a provider weakly.

### ISSUE THREAD

**Issue by MiloszFilimowski** [rrousselGit/riverpod#1645]
**Is your feature request related to a problem? Please describe.**
I'd like to listen to an autodispose provider but allow it to dispose when not used anymore by strong listeners. Such a case for me is for example when I listen with another provider and it needs to update itself. 

```
final provider = StateNotifierProvider.autoDispose<GetData1Controller, State1>((ref) {
    
   // Suggested solution.
   ref.listenWeak(someOtherProvider, (prev, next) {
      ref.notifier.refresh();
    });

    return GetData1Controller();
});
```

**Describe the solution you'd like**
I have implemented a solution using `ProviderObserver` and `Expando` but I'd like to first see your thoughts about this and if it's a good idea after all.

With some more tweaking, this could also be useful when listening to all families at once. When we don't care about parameters and only about that something had happend.

My solution:

```
import 'package:flutter_riverpod/flutter_riverpod.dart';

class WeakProviderObserver extends ProviderObserver {
  WeakProviderObserver();

  final _expando = Expando<List<ObserveCallback>>();

  void _observe<T>(ProviderBase<T> provider,
      void Function(T? previousValue, T? newValue) callback) {
    final currentProviders = _expando[provider] ?? [];
    castedCallback(Object? previousValue, Object? newValue) {
      callback(previousValue as T?, newValue as T?);
    }

    _expando[provider] = [...currentProviders, castedCallback];
  }

  @override
  void didUpdateProvider(
    ProviderBase provider,
    Object? previousValue,
    Object? newValue,
    ProviderContainer container,
  ) {
    final callbacks = _expando[provider] ?? [];
    for (var callback in callbacks) {
      callback(previousValue, newValue);
    }
  }
}

extension WeakListener on Ref {
  void listenWeak<T>(
      ProviderBase<T> provider, void Function(T? previous, T? next) listener) {
    weakProviderObserver._observe(provider, listener);
  }
}

final weakProviderObserver = WeakProviderObserver();

typedef ObserveCallback = void Function(
    Object? previousValue, Object? newValue);
```

**Comment by rrousselGit** [comment]
Hello!

Could you describe the problem? Here you're describing one possible solution, but the problem isn't quite clear. Maybe there's a better solution available.

**Comment by MiloszFilimowski** [comment]
Hey! Thanks for the answer. 

Let's say I have `notesListProvider` and `addNoteProvider`. One is resposible for fetching the list of notes and the other for adding a note. I'd like the `notesListProvider` to react to an action of adding a note by  `addNoteProvider` but allow it to be dispose once for example AddNoteScreen is closed and it's no longer needed.

**Comment by rrousselGit** [comment]
It sounds like the relationship is inverted.

Instead of having notesListProvider listen to addNoteProvider, what about having addNoteProvider notify notesListProvider?

**Comment by MiloszFilimowski** [comment]
This is my intention here. `notesListProvider` is interested in this change and has it's own private method to handle this case. Exposing some public method to the outside would mean that anything, not only `addNoteProvider`, could trigger this side effect.

**Comment by rrousselGit** [comment]
Then have `addNoteProvider` and `notesListProvider` in the same dart file/part. Riverpod is very strict in the direction in which providers can listen to each other.

**Comment by MiloszFilimowski** [comment]
I don't think this is a good solution in terms of scale and code separation. Anyway, thanks for your input!
