### ISSUE TITLE
Prevent refresh when invalidate() called.

### ISSUE THREAD

**Issue by TreyThomas93** [rrousselGit/riverpod#1652]
Is there a way to prevent refresh when calling invalidate. I keep getting the _StateError (Bad state: Tried to use SessionsHistoryNotifier after `dispose` was called.)_ error after calling invalidate because I call a method upon initialization of the state notifier and it's obviously unmounted. And I don't want to have to check if it's mounted within the methods if I am trying to invalidate the notifier anyways.

**Comment by rrousselGit** [comment]
I see nothing wrong with that.

Sounds like your provider got disposed while it was doing stuff, so you need to cancel the pending operation or check "mounted".

**Comment by TreyThomas93** [comment]
@rrousselGit But isn't invalidate supposed to dispose and refresh per the docs? It would be nice to be able to dispose without the refresh.

```
void invalidate(ProviderBase<Object?> provider)
Type: void Function(ProviderBase<Object?>) package:flutter_riverpod/src/consumer.dart

Invalidates the state of the provider, causing it to refresh. < --- BYPASS THIS?

As opposed to [refresh], the refresh is not immediate and is instead delayed to the next read or next frame.

Calling [invalidate] multiple times will refresh the provider only once.

Calling [invalidate] will cause the provider to be disposed immediately. < --- ONLY DO THIS.
```

**Comment by rrousselGit** [comment]
The provider will refresh if and only if it is still used.

It sounds like you're trying to dispose something that is still being used.

**Comment by TreyThomas93** [comment]
@rrousselGit By used do you mean being watched somewhere?

**Comment by rrousselGit** [comment]
Yes, or "ref.listen" too.

**Comment by TreyThomas93** [comment]
@rrousselGit Awesome thanks!
