### ISSUE TITLE
Support query mutation

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1660]
A common use case is to trigger side-effects and have the UI listen to the status of that side-effect (such as showing a spinner/snackbar on error)

I don't think there is a neat way to support this without code-generation that wouldn't have fundamental flaws (like the inability to pass parameters).  
But with the new code-generation syntax for providers, Riverpod should be able to support this

In particular, we could have:

```dart
@riverpod
class Example extends _$Example {
  @override
  Future<List<Todo>> build() => fetchTodoList();

  @mutation
  Future<void> addTodo(Todo todo) async {
    await http.post(...., todo.toJson());
  }
}
```

which would then be used inside widgets by doing:

```dart
Consumer(
  builder: (context, ref, child) {
    // as usual, nothing special
    List<Todo> todos = ref.watch(exampleProvider);

    // our UI listens to "addTodo" side-effects.
    // The returned AddTodoMutation object contains things like loading/error/result
    // of the mutation, similar to that of AsyncValue.
    AddTodoMutation addTodo = ref.watch(exampleProvider.addTodo);

    return SomeButton(
      // invoke the Example.addTodo method
      onTap: () => addTodo(Todo())
    );
  },
)
```

Mutations would also receive a custom `ProviderObserver` event for start/completion/failure, with an `Invocation` corresponding to the method invocation.

And of course, riverpod_graph & the devtool should be updated to show mutations

**Comment by rrousselGit** [comment]
Tagged as "2.1" but likely will come after. Consider this as a "planned"

**Comment by TimWhiting** [comment]
As a side note, the linter is too aggressive about read vs watch in provider definitions when you are using `FutureProvider` for mutations. (you don't want to rerun a mutation when things change always), in some cases it might make sense, but not always.

**Comment by rrousselGit** [comment]
You're not supposed to use FutureProvider for mutations to begin with.

**Comment by AhmedLSayed9** [comment]
Will this solve use cases when the call is not a side effect of the provider but instead it's the initial value itself?

i.e: a LoginProvider use case which might be a FutureProvider.
It will be triggered through `onPressed` later while you need to pre watch/listen to show a spinner/snackbar on error.

Currently, This can be handled by 3 approaches:

1- Using StateNotifier or now AsyncNotifier with `AsyncValue<void>` or `nullable` AsyncValue.

2- Creating 3 providers:
1. The main `FutureProvider` that trigger the call.
2. `StateProvider` that hold the login parameters which will be initially null.
3. Basic `Provider` that return AsyncValue which will be initially AsyncData(null) and it watch for the second provider (login params) and will trigger the call when login parameters is submitted.

3- Similar to second approach but instead of creating 3 provider, create just the main provider and handle the second/third provider in the widget itself using Hooks or StatefulWidget.

I'd prefer 3rd approach but It still looks complicated for a simple use-case and there might be a better solution.

**Comment by AhmedLSayed9** [comment]
This an example of the 2nd approach using the 3 providers (which was recommended before on Discord):
```
final selectedProfileImageProvider = StateProvider.autoDispose<File?>((ref) {
  return null;
});

final updateProfileImageStatusProvider =
    Provider.autoDispose<AsyncValue<void>>((ref) {
  final selectedImage = ref.watch(selectedProfileImageProvider);
  if (selectedImage == null) return const AsyncData(null);

  return ref.watch(updateProfileImageProvider(selectedImage));
});

final updateProfileImageProvider =
    FutureProvider.autoDispose.family<void, File>((ref, imageFile) async {
  final result = await updateProfileImageCall(imageFile);
});

class UserProfileExample extends HookConsumerWidget {
  const UserProfileExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ref) {
    ref.listen<AsyncValue<void>>(
      updateProfileImageStatusProvider,
      (prevState, newState) {
        prevState?.unwrapPrevious().whenOrNull(
              loading: () => DismissDialog(context),
            );
        newState.unwrapPrevious().whenOrNull(
              loading: () => ShowLoadingDialog(context),
              error: (err, st) => ShowErrorDialog(err),
            );
      },
    );

    final pickImage = useCallback((PickSource pickSource) async {
      final bool canSubmit =
          !ref.read(updateProfileImageStatusProvider).isLoading;
      if (canSubmit) {
        try {
          //This is unrelated provider responsible for picking the image locally
          final image =
              await ref.read(pickProfileImageProvider(pickSource).future);
          
          //Update SelectedProfileImageProvider which will trigger the call
          ref.read(selectedProfileImageProvider.notifier).state = image;
        } catch (_) {}
      }
    }, []);

    return ImagePickComponent(
      pickFromCameraFunction: () {
        pickImage(PickSource.camera);
      },
      pickFromGalleryFunction: () {
        pickImage(PickSource.gallery);
      },
    );
  }
}
```
**Result:**

https://user-images.githubusercontent.com/70890146/204165587-031c8b6a-bee3-4819-be06-f5b940e71be7.mov


This is same as login/register/logout/et. use cases.
It works great but looks like too much work to pre watch/listen a callable Future and act upon its result.

**Comment by ruanwenfeng** [comment]
When can we use this amazing feature, very much looking forward to.

**Comment by RodolfoSilva** [comment]
Whats is the best alternative until we have the `@mutation`? @rrousselGit ?
Right now I'm using the approach showed by @AhmedLSayed9.

**Comment by RodolfoSilva** [comment]
We could also use this approach using flutter_hooks, like is made in the React world.

```dart
import 'package:flutter/material.dart';

final mutating = useState<bool>(false);
final mutatingError = useState<String?>(null);

final addTodoMutation = useCallback(async () {
  try {
    mutating.value = true;
    mutatingError.value = null;
    // PUT YOU ASYNC LOGIC HERE...
    http.post(....)
    ref.refresh(todosProvider);
  } catch (e) {
    mutatingError.value = e.toString();
  } finally {
    mutating.value = false;
  }
}, [ref]);

if (mutating.value) {
  return Text('Mutating');
} else {
  return ElevatedButton(
    child:  Text('Loading'),
    onPressed: () => addTodoMutation(),
  );
}
```

But I think this could always return a generic instance of Mutation:

```dart
class MutationState<T> {
  MutationState._(this._loading, [this._data, this._error]);

  final bool _loading;
  final T? _data;
  final dynamic _error;

  T? get data => _data;
  bool get isEmpty => _data == null;
  bool get isNotEmpty => _data != null;
  bool get isLoading => _loading;
  bool get isError => !_loading && _error != null;

  factory MutationState.error(dynamic error) {
    return MutationState._(false, null, error);
  }
 
  factory MutationState.success(T data) {
    return MutationState._(false, data);
  }
 
  factory MutationState.loading() {
    return MutationState._(true);
  }
 
  factory MutationState.idle() {
    return MutationState._(false);
  }
}
```

And refactor the code like that:

```dart
import 'package:flutter/material.dart';

final state = useState<MutationState<dynamic>>(MutationState.idle()); 

final addTodoMutation = useCallback(async () {
  try {
    state.value = MutationState.loading();
    // PUT YOU ASYNC LOGIC HERE...
    final result = await http.post(....)
    ref.refresh(todosProvider);
    state.value = MutationState.success(result);
  } catch (e) {
    state.value = MutationState.error(e);
  } 
}, [ref]);

if (state.value.isLoading) {
  return Text('Mutating');
} else {
  return ElevatedButton(
    child:  Text('Loading'),
    onPressed: () => addTodoMutation(),
  );
}
```

I've not run this code, but I don't think this is working. The point here is to have an Idea of an workaround.

**Comment by TekExplorer** [comment]
I currently use this provider for mutations
```dart
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'mutation_provider.g.dart';

@riverpod
class Mutation extends _$Mutation {
  @override
  // FutureOr<MutationEnum> build(Symbol functionId) => MutationEnum.initial;
  FutureOr<MutationEnum> build(Object? key) => MutationEnum.initial;

  Future<void> call(Future<void> Function() callback) async {
    state = const AsyncValue.loading();
    final result = await AsyncValue.guard<void>(() => callback());
    if (result is AsyncData) {
      state = const AsyncValue.data(MutationEnum.success);
    } else if (result is AsyncError) {
      state = AsyncValue.error(result.error, result.stackTrace);
    }
  }
}

enum MutationEnum {
  initial,
  success;

  bool get isInitial => this == MutationEnum.initial;
  bool get isSuccess => this == MutationEnum.success;
}
```

i then use it by providing the family with `final mutationKey = useMemoized(Object.new)`

you can also add whatever convenience methods you like, such as a `when` on the enum, or creating a `mutationWhen` on `AsyncValue<MutationEnum>` which replaces `data` with `initial` and `success`

**Comment by TekExplorer** [comment]
you can always try and adjust it to return the success data if you want, but ideally you should be calling notifier methods from other providers that handle the data for you.

its used by
```dart
final mutationKey = useMemoized(Object.new);
final mutationState = ref.watch(mutationProvider(mutationKey));

// later
final mutation = ref.read(mutationProvider(mutationKey).notifier);
//call
mutation(() async {
  ref.read(someProvider.notifier).someMutation();
});
```

**Comment by AhmedLSayed9** [comment]
> Whats is the best alternative until we have the `@mutation`? @rrousselGit ?
> Right now I'm using the approach showed by @AhmedLSayed9.

I've enhanced my approach a bit to be able to recall the `mutation` with the same parameters or if it has no parameters at all, without the need to manually invalidating some providers. Also, migrated all providers to code-gen.

Here's an example on a sign-out use-case (Option is from fpdart, you can use nullable type instead):
```
/// Reusable class for all event providers
@freezed
class Event<T> with _$Event<T> {
  const factory Event({
    Key? key,
    required T arg,
  }) = _Event<T>;

  factory Event.unique(T arg) => Event(
        key: UniqueKey(),
        arg: arg,
      );
}

enum SignOutState {
  idle,
  success,
}

@riverpod
AsyncValue<SignOutState> signOutState(SignOutStateRef ref) {
  final event = ref.watch(signOutEventProvider);
  return event.match(
    () => const AsyncData(SignOutState.idle),
    (event) {
      return ref
          .watch(signOutProvider(event))
          .whenData((_) => SignOutState.success);
    },
  );
}

@riverpod
class SignOutEvent extends _$SignOutEvent {
  @override
  Option<Event<void>> build() => const None();

  // You can make mixin for this
  void update(Option<Event<void>> Function(Option<Event<void>>) cb) =>
      state = cb(state);
}

@riverpod
Future<void> signOut(
  SignOutRef ref,
  Event<void> event,
) async {
  return ref.watch(signOutUCProvider).call();
}
```

now, at UI you can do:
```
ref.listen(signOutStateProvider, (prevState, newState) {
      ...
    });

onPressed: (){
  final bool canSubmit = !ref.read(signOutStateProvider).isLoading;
  if (canSubmit) {
    ref
        .read(signOutEventProvider.notifier)
        .update((_) => Some(Event.unique(null)));
  }
},
```

It's clean & declarative that way.
Also, I'm not sure how/if @mutation will be the ideal solution for this cases as `build` method will be ignored. I'm thinking of something like:
```
@riverpod
class SignOut extends _$SignOut {
  @override
  FutureOr<void> build() => null;

  @mutation
  Future<void> signOut() async {
    await apiCall();
  }
}
```

**Comment by TekExplorer** [comment]
I've improved my approach a lot, with some suggestions by remi.
This mirrors the approach that the code gen solution will have, at least as far as api is concerned
https://github.com/TekExplorer/riverpod_mutations

it also includes a generic mutations provider.

**Comment by chimon2000** [comment]
An interesting solution I discovered last week

https://pub.dev/packages/rivertion

**Comment by TekExplorer** [comment]
> An interesting solution I discovered last week
> 
> https://pub.dev/packages/rivertion

missing github link == yeet

**Comment by chimon2000** [comment]
https://github.com/BreX900/query/rivertion

On February 24, 2023, GitHub Notifications ***@***.***>
wrote:
> > An interesting solution I discovered last week
> >
> > <https://pub.dev/packages/rivertion>
> >
>
> missing github link == yeet
>

—
Reply to this email directly, view it on GitHub
<https://github.com/rrousselGit/riverpod/issues/1660#issuecomment-
1444843882>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABUWPFLMQX7ZSASNIKZL5CLWZFLE7ANCNFSM6AAAAAAQSJ7QEU>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by njwandroid** [comment]
any update?
i see this https://docs-v2.riverpod.dev/docs/essentials/side_effects and it seems related but still not quite clear.

**Comment by TekExplorer** [comment]
For those who care to try early code, consider trying out this generator
```yaml
dependencies:
  riverpod_mutations_annotation:
    git:
      url: https://github.com/TekExplorer/riverpod_mutations_annotation
dev_dependencies:
  riverpod_mutations_generator:
    git:
      url: https://github.com/TekExplorer/riverpod_mutations_generator
```
It should be functional. I just need some feedback before i go to publish as a package

**Comment by neiljaywarner** [comment]
@TekExplorer isn't this the same as https://pub.dev/packages/riverpod_mutations which is already published as a package? is it working well? has anyone else tried it?

@rrousselGit  can you confirm this is the api you are planning to take? this seems promising to me...

**Comment by rrousselGit** [comment]
That's not the API I want, no.

The API I want is already in the top post.

**Comment by neiljaywarner** [comment]
Thanks for clarifying. I'm definitely looking forward to it!

**Comment by neiljaywarner** [comment]
Can you please check/update the readme when you get a chance?
Unless I'm confused.. it looks different to me..

....sent from my phone

**Comment by TekExplorer** [comment]
@njwandroid 

i've updated the generator's readme. You literally use it as demonstrated in the main message of this issue

**Comment by TekExplorer** [comment]
I've published the generator and annotation as packages on pub.dev!

It not only supports this api, it also supports marking some of your method's parameters as family keys! That allows you to listen on multiple calls (say, you were deleting multiple books by their id and wanted to show a loading indicator for each one, which was not possible before)

https://pub.dev/packages/riverpod_mutations_generator << see the readme
https://pub.dev/packages/riverpod_mutations_annotation

**Comment by ewilliams-zoot** [comment]
I think I saw hints in @TekExplorer 's comments about using mutation keys, which is essential for lists of items that each trigger the same mutation but should only react to UI changes individually. Is that being considered in the solution for this? For example, how would a `deleteTodo` mutation look in your syntax, @rrousselGit ? Something like this?
```dart
  @mutation(useKey: true)
  Future<void> deleteTodo(String todoUid) async {
    await http.delete(...., todoUid);
  }

// in Widget user interaction, only listens to mutations with a key of "this" todo item
AddTodoMutation addTodo = ref.watch(exampleProvider.deleteTodo(todoUid));
```

**Comment by TekExplorer** [comment]
Not likely. It's possible to have multiple parameters that want to be keys. My solution uses an additional annotation called `@mutationKey` on the parameters in question that does this.

**Comment by ewilliams-zoot** [comment]
That actually makes sense - like a compound key for a database table. An additional annotation would seem to make the most sense in a solution like this then.

**Comment by mrverdant13** [comment]
I really find the initial @rrousselGit's proposal quite useful

Being able to discriminate among different mutation methods is currently not possible within a `ProviderObserver`, which is often essential to register/post the mutation intent (as well as its payload and metadata) to an analytics manager/provider/service.

In the meantime, the approach that best suits my requirements is the use of one `Notifier` per each mutation method.
The `Notifier` manages a custom variation of an `AsyncValue`, where the `AsyncLoading` subclass encloses the metadata related to the ongoing mutation.
As a result, any `ProviderObserver` can be fully aware of the mutation state as well as of its corresponding metadata/payload.
Even better, the use of an `AnalyticsEvent` mixin class to mark those custom classes as such, which later on can be easily identified by the observer.

My guess is that, one of the potential benefits that entails the introduction of the `@mutation` annotation, is the capability to track them in a similar fashion as described above, but with the additional advantage of the proper automatic update of the root `AsyncNotifier` state.

---

I opened [a discussion entry](https://github.com/rrousselGit/riverpod/discussions/3263) looking for existing options for the specific use case I mention here, where I also included a simple example description, in case more context is required.

**Comment by rrousselGit** [comment]
Yes, tracking what triggered a state change is in the scope of this issue.
I specifically am working on that for the devtool, but logging is another one.

**Comment by RodolfoSilva** [comment]
Hook alternative:

```dart
typedef Mutation = FutureOr<dynamic> Function();

(AsyncSnapshot<void>, Mutation) useMutation(
  Mutation callback, [
  List<Object?> keys = const <Object>[],
]) {
  final pendingMutation = useState<Future<void>?>(null);
  final snapshot = useFuture(pendingMutation.value);

  final mutate = useCallback(() {
    pendingMutation.value = Future.microtask(() => callback());
    return pendingMutation.value;
  }, keys);

  return (snapshot, mutate);
}

typedef MutationFamily<T> = FutureOr<dynamic> Function(T params);

(AsyncSnapshot<void>, MutationFamily<T>) useMutationFamily<T>(
  MutationFamily<T> callback, [
  List<Object?> keys = const <Object>[],
]) {
  final pendingMutation = useState<Future<void>?>(null);
  final snapshot = useFuture(pendingMutation.value);

  final mutate = useCallback((params) {
    pendingMutation.value = Future.microtask(() => callback(params));
    return pendingMutation.value;
  }, keys);

  return (snapshot, mutate);
}
```

@rrousselGit do you have any suggestion?

**Comment by masreplay** [comment]
I created this simple package using Riverpord and Hook [riverpod_hook_mutation](https://pub.dev/packages/riverpod_hook_mutation)

Define
```dart
final addTodo = useMutation<TODO>();
```

Call
```dart
addTodo(ref.read(provider.notifier).addTodo())
```

Usage
```dart
addTodo.maybeWhen(
  loading: () => const CircularProgressIndicator(),
  orElse: () => const Icon(Icons.add),
)
```

**Comment by TekExplorer** [comment]
I wouldn't have named it that. It's not riverpod specific.

**Comment by rrousselGit** [comment]
'tis done

So closing :)

**Comment by dm-finvest** [comment]
Hey @rrousselGit, is this part of the latest 3.0 prerelease? I tried upgrading all the Riverpod packages to the latest 3.0 prerelease versions but the annotation `@mutation` isn't detected.

**Comment by TekExplorer** [comment]
> Hey @rrousselGit, is this part of the latest 3.0 prerelease? I tried upgrading all the Riverpod packages to the latest 3.0 prerelease versions but the annotation `@mutation` isn't detected.

It's not published.

**Comment by rrousselGit** [comment]
I've stopped publishing dev releases because they are too taxing for me. I'll likely make one after offline and some critical bugfixes

**Comment by dickermoshe** [comment]
I don't see anyway of doing debouce which is a pretty basic requirement for mutations

**Comment by rrousselGit** [comment]
That's not the purpose of mutations. But if we want those things, make a feature request :)
