### ISSUE TITLE
Support more types of values in the generator

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1663]
Currently supported:

- [x] plain objects
- [x] futures
- [x] class variants of the above two

Currently unsupported type:
- [ ] Streams
- [ ] legacy object types (StateNotifier/ChangeNotifier)

It'd be nice to support:

```dart
@riverpod
Stream<T> example(ExampleRef ref) { ...
}

@riverpod
class Example 
  Stream<T> example(ExampleRef ref) { ...
  }
}
```

And for the sake of migration, we could also support:

```dart
@riverpod
Counter counter(CounterRef) => Counter();

class Counter extends StateNotifier/ChangeNotifier {
...
}
```

**Comment by linxydmhg** [comment]
I've been using StateNotifier a lot, may I ask if it's marked as legacy, what its replacement will be with the riverpod codegen?

**Comment by rrousselGit** [comment]
It's annotating `@riverpod` on a class with a build method

**Comment by wstrange** [comment]
I noticed that annotating: 
```
@riverpod
Stream<Foo>  getFooStream(..)
```

Results in code generation where the Stream type (`Foo`) gets lost and replaced with `Stream<dynamic>` 

Or am I doing it wrong?

**Comment by rrousselGit** [comment]
That's unlikely. You're likely doing something else that causes this, but haven't included the revelant about what's going on

For example maybe "Foo" is a generated class.

**Comment by wstrange** [comment]
I am generating some classes for firestore odm. I'll see if I can create a reporoducible example.

**Comment by wstrange** [comment]
I have not yet created a standalone example, but if it helps,  the Stream class is being generated from my model by the firestore ODM generator:

```dart
@riverpod
Stream<EventQuerySnapshot> currentEvents(CurrentEventsRef ref, {DateTime? dateTime,
            List<EventCategory> categoryFilter = const [] }) {
    var db = ref.watch(databaseProvider);
    return db.getCurrentEventStream(date: dateTime, categoryFilter:categoryFilter );
}
```

In the above, `EventQuerySnapshot` is generated via `@firestoreSerializable` annotation on my `Event`  class.

So this has something to do with the order in which annotations are processed by build runner?

**Comment by rrousselGit** [comment]
Ah yes, you can't do that unfortunately.

**Comment by rrousselGit** [comment]
I'll see if generated types can be supported. It probably should be doable with a reasonable amount of work.

Although the true fix would be static metaprogramming.

**Comment by wstrange** [comment]
This isn't a show stopper for me, so If you prefer to wait for static metaprogramming that's cool ;-)

**Comment by Quijx** [comment]
@rrousselGit When you add support for stream providers with code gen, can you maybe also add a flag to the annotation that treats the return types of the annotated functions like any other class? So for example
```dart
@Riverpod(rawTypes: true)
Stream<String> eventStream(EventStreamRef ref) => ...;
```
would generate a `Provider<Stream<String>>` and not a `StreamProvider<String>`. The same would hold for futures.

I have found myself needing that because I want to provide a stream of events, so a `StreamProvider` holding the newest event doesn't make sense. Also the same event could be triggered twice, which would prevent an update if `StreamProvider` would be used.

**Comment by rrousselGit** [comment]
I don't think I'll add support for the "old" StateNotifier/ChangeNotifier types.  
You should use the `@riverpod class` syntax anyway

It does make the migration a bit more painful, but long term it's better I think. Otherwise people likely would keep using StateNotifier/CHangeNotifier with the generator when they should use the class syntax


But support for `@riverpod Stream<T> fn()` & a class variant is coming

**Comment by ajonno** [comment]
> But support for `@riverpod Stream<T> fn()` & a class variant is coming
> 
> 

Any eta for this? We're starting a new client project so keen to know, thanks!

**Comment by arnab** [comment]
It’s already available on the `2.3.0` release in pub. Thanks @rrousselGit !

**Comment by ajonno** [comment]
oh sweet! note to self; check pub.dev first.... ;-0

**Comment by Pingear** [comment]
@arnab  It can't be, why don't I know about it? I'm just using version 2.3. And there is no mention of this in the documentation. Can you show where you found out about this?

**Comment by arnab** [comment]
@Pingear see the `2.3.0` release notes: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/CHANGELOG.md

If you are using that version, just add `@riverpod` like it shows there. I’m using it already (but it’s not an open source app, so can’t link here).

**Comment by Pingear** [comment]
@arnab As far as I understand, now the code generation can be considered complete, since it covers all the types of providers necessary for work. It's strange that no one has announced this)
So this is really cool!!

**Comment by krishnatejakanchi** [comment]
@rrousselGit I am trying to create provider to get GoRouter instance, which is extending ChangeNotifier. From the lint warning, I understood that I am doing something wrong. But I didn't understood what is the correct approach. Please help me out. 

Lint warning: The riverpod_generator package does not support ChangeNotifier

**Comment by rrousselGit** [comment]
The lint is only here to tell you that the GoRouter won't be disposed and that changes won't be listened.
If you don't care, you can ignore the lint here

**Comment by krishnatejakanchi** [comment]
@rrousselGit As `ChangeNotifier` was mentioned as Legacy, may I know its alternative in flutter? As many third party packages i am using are still extending with ChangeNotifier.

**Comment by rrousselGit** [comment]
I will offer a more official way to silence the lint in scenarios where this is voluntary.
It's landing very soon.
