### ISSUE TITLE
Immediately call `ref.onCancel` after the initialization of a provider if it isn't currently listened

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1665]
Currently, calling `ref.read` on a provider that isn't listened yet (no ref.watch/listen) does not trigger `ref.onCancel`.
Yet at the same time, that provider is considered to be paused, as it isn't currently in use.

This issue is about fixing the inconsistency, and invoking `ref.onCancel` listeners if the provider is initialized but not listened

**Comment by rrousselGit** [comment]
An alternative would be to expose a `Ref.hasListeners`, and have that value be true during the provider initialization if it is initialized from a `ref.watch`/`ref.listen`

**Comment by rrousselGit** [comment]
I have no plan to make this change at the moment

**Comment by timcreatedit** [comment]
@rrousselGit could you maybe elaborate why this is not planned? It seems to me like managing provider lifecycles is now easily broken by `ref.read`.

We want to implement something similar to `ref.disposeDelay`, as discussed in https://github.com/rrousselGit/riverpod/issues/1664

Given the following providers 
```dart
const duration = Duration(seconds: 2);

final stateProvider = StateProvider.autoDispose((ref) => 0);

final cachedProvider = Provider.autoDispose((ref) {
  final state = ref.watch(stateProvider);
  final link = ref.keepAlive();
  Timer? timer;

  ref
    ..onCancel(() {
      timer?.cancel();
      timer = Timer(duration, link.close);
    })
    ..onDispose(() {
      timer?.cancel();
    })
    ..onResume(() {
      timer?.cancel();
    });
  return state;
});
```

I would expect these tests to pass:
```dart

void main() {
  late ProviderContainer container;
  setUp(() {
    container = ProviderContainer();
  });
  tearDown(() {
    container.dispose();
  });

  group('disposeDelay', () {
    test('disposes after duration', () async {
      fakeAsync((async) {
        expect(container.read(cachedProvider), 0);
        container.read(stateProvider.notifier).state++;
        expect(container.read(cachedProvider), 1);
        async.elapse(duration);
        expect(container.read(cachedProvider), 0);
      });
    });

    test('holds the cached value in between', () async {
      fakeAsync((async) {
        expect(container.read(cachedProvider), 0);
        container.read(stateProvider.notifier).state++;
        // If provider is read before duration passes, the timer should restart
        for (var i = 0; i < 20; i++) {
          async.elapse(duration ~/ 10);
          expect(container.read(cachedProvider), 1);
        }

        // Only once the duration has passed fully should the value be gone
        async.elapse(duration);
        expect(container.read(cachedProvider), 0);
      });
    });
  });
}
```

The issue is not only that the provider doesn't delay it's disposal properly, but that it actually never gets disposed if it is read even once, but never watched or listened. Thus, I feel like not calling `onCancel` for `ref.read` is unintuitive and error-prone, but I would love to learn something here!

**Comment by rrousselGit** [comment]
Don't continue discussion in closed issues. There's a big chance I won't see your message. Open new issues if you have problems.

But anyway:
I don't want to call `onCancel` on `ref.read`, because the provider isn't getting "cancelled". It was never active to begin with.
It sounds to me like you want a new property on `ref`: `Ref.isActive` or something
