### ISSUE TITLE
Marvel example doesn't handle DioError in the UI

### ISSUE THREAD

**Issue by RobertBrunhage** [rrousselGit/riverpod#167]
**Describe what scenario you think is uncovered by the existing examples/articles**
In the `home.dart` file the `.when` error case doesn't handle DioError, for example doing this:

```
 if (err is DioError) {
      return Text(err.message);
 }
```

**Describe why existing examples/articles do not cover this case**
For now you are doing the following which will just print "Instance of..."
```
error: (err, stack) {
   return Scaffold(
     appBar: AppBar(title: const Text('Error')),
     body: Center(
       child: Text('$err'),
     )
  );
},
```

**Comment by msarkrish** [comment]
Hi @rrousselGit , Can you assign this issue to me?

**Comment by rrousselGit** [comment]
Just raise a PR :)

**Comment by msarkrish** [comment]
@rrousselGit I have raised a PR. I am waiting for your comments.
