### ISSUE TITLE
StateProvider disposeDelay is adding some delay by itself. 

### ISSUE THREAD

**Issue by iLoveDocs** [rrousselGit/riverpod#1696]
### Describe the bug
`disposeDelay` isn't disposing at the right time. 

### To Reproduce
Navigate to the `BarPage` and press the back button to come back to the `FooPage`. The `ref.onDispose()` doesn't get called after 5 seconds but 11 seconds (tried many times), but if I choose the duration to `Duration(seconds: 1 or 2)` it seems to call dispose at the right time. 

This issue only happens with `StateProvider`, if I use the regular `Provider`, then the dispose takes place after 5 seconds. 

```dart
final fooProvider = StateProvider.autoDispose<int>(
  cacheTime: Duration.zero,
  disposeDelay: const Duration(seconds: 5),
  (ref) {
    print('created');
    ref.onDispose(() => print('disposed'));
    return 0;
  },
);

class FooPage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => BarPage())),
        child: Icon(Icons.arrow_forward_ios),
      ),
    );
  }
}

class BarPage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.watch(fooProvider);
    return Scaffold(appBar: AppBar());
  }
}
```

### Expected behavior
The `print('dispose')` code should print after 5 seconds.

**Comment by rrousselGit** [comment]
Hello!

`disposeDelay` has been removed and will not be part of the 2.0 release, so this probably can be closed.

If you want to use it, you'll have to implement it on your own using `ref.onCancel`/`ref.onResume` & `ref.keepAlive()`

**Comment by iLoveDocs** [comment]
Alright, no problem, thanks for the update. 
May I know where I can see these types of information, like `disposeDelay` won't be a part of 2.0 release, etc...

@rrousselGit 
PS: 
I was preventing myself from using Riverpod for such a long time because how hard it was (in comparison to your all weather `provider`) but after reading the crystal clear docs I must say Riverpod is probably the best if not the best state management approach. Kudos buddy! Keep up the great work
