### ISSUE TITLE
Reading a provider inside extensions

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#1706]
**Describe what scenario you think is uncovered by the existing examples/articles**

It is a simple use case. I want to read a provider (basic provider which act as a singleton) inside an extension. I could inject ref through extension methods but that would be redundant and unnecessary as I might use it in places where I don't need ConsumerWidgets and also as this extension should rely only on context and it's used through the whole app.

```
final _responsiveService = mainContainer.read(responsiveServiceProvider);

extension ResponsiveExtension on num {
  double w(BuildContext context) =>
      _responsiveService.scaleWidth(context) * this;

  double h(BuildContext context) =>
      _responsiveService.scaleHeight(context) * this;

  double r(BuildContext context) =>
      _responsiveService.scaleRadius(context) * this;

  double sp(BuildContext context) =>
      _responsiveService.scaleText(context) * this;
}
```
```
final responsiveServiceProvider = Provider((ref) => ResponsiveService());

class ResponsiveService {
  ResponsiveService({MediaQueryData? flutterWindowMediaQuery}) {
    _flutterWindowMediaQuery =
        flutterWindowMediaQuery ?? MediaQueryData.fromWindow(window);
  }

  late MediaQueryData _flutterWindowMediaQuery;
  final Size designSize = const Size(428, 860);
  
  ...
}
```

**Describe why existing examples/articles do not cover this case**

I can make my ProviderContainer instance a global variable and use it as the code above but as said before it's not recommended to do that.
Alternatively, I could use patterns like Singletons or maybe another Service Locator package but as the docs say, Provider should be complete replacement for these patterns. so, I'm wondering if there's a better solution for scenarios like this.

**Comment by rrousselGit** [comment]
You should pass a ref. It's not even a debate 😜

Don't randomly create ProviderContainers.

**Comment by AhmedLSayed9** [comment]
I agree we normally should pass a ref. but in this case, passing a ref will make almost every widget a ConsumerWidget and the ref to be used at every few lines of codes (as this is a text extension and text is everywhere).

While I'm sure the responsiveServiceProvider is created only once in the app, I'd go with another pattern/package for this instead of filling my app with unnecessary refs in all widgets.

I've a solution for this case or similar cases in my mind instead of using a global container but I don't know the ability to achieve it. It's to make a new Provider Type which is:
1. Similar to the basic Provider in usage but maybe called `StaticProvider`.
2. It can't be overridden by nested ProviderScopes so It'll always belong to the main ProviderScope.
3. It doesn't have the `.autoDispose` modifier.
4. It can be accessed directly without ref.
5. Maybe a caution should be documented to it that it should be avoided as possible and only used with providers that won't change.

**Comment by rrousselGit** [comment]
I don't think what you're suggesting is reasonable

Instead I'd question your architecture.
As I said before, your class should most likely be hosted in a provider, so it would have a ref.

**Comment by AhmedLSayed9** [comment]
I'll try to elaborate more. This is how it'll be If I'm going to pass ref from widgets:

```
//This is my responsive service (single class)
final responsiveServiceProvider = Provider((ref) => ResponsiveService());

class ResponsiveService {
  ResponsiveService({MediaQueryData? flutterWindowMediaQuery}) {
    _flutterWindowMediaQuery =
        flutterWindowMediaQuery ?? MediaQueryData.fromWindow(window);
  }

  late MediaQueryData _flutterWindowMediaQuery;
  final Size designSize = const Size(428, 860);
  
  double scaleHeight(BuildContext context) => MediaQuery.of(context).size.height / designSize.height;
  double scaleWidth(BuildContext context) => MediaQuery.of(context).size.width / designSize.width;
}

//This is my extension that need to access (just read) that responsiveServiceProvider
extension ResponsiveExtension on num {
  double w(BuildContext context, WidgetRef ref) =>
      ref.read(responsiveServiceProvider).scaleWidth(context) * this;

  double h(BuildContext context, WidgetRef ref) =>
      ref.read(responsiveServiceProvider).scaleHeight(context) * this;
}

//This is how I'll use it in almost every widget, will need to pass ref which isn't necessary in this case
class SomeWidget extends ConsumerWidget {
  const SomeWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ref) {
    return Column(
      children: [
        Container(
          height: 1.h(context, ref),
          width: 2.w(context, ref),
        ),
        Container(
          height: 1.h(context, ref),
          width: 2.w(context, ref),
        ),
        Container(
          height: 1.h(context, ref),
          width: 2.w(context, ref),
        ),
      ],
    );
  }
}
```

As said, the `ResponsiveService` is not going to overridden or disposed. It just work as a singleton. so passing ref from every place like above example will be redundant.

**Comment by AhmedLSayed9** [comment]
What I'm suggesting here is to provide a way to access provider without ref (Maybe new Type of provider).
In order to access them without ref, they can't have .autoDispose modifier or the ability to be listened to but that won't make an issue in this case.
This will solve the above unnecessary need to pass ref across many places for a long lived class that only acts as a singleton and no object will be interested to listen to it. 
I've seen many using get_it with riverpod to solve cases like this while Provider should be a replacement for these patterns.

**Comment by TimWhiting** [comment]
The thing about depending on a provider is that you need to make any widget that depends on a provider a `ConsumerWidget` & use a ref to get it. You say that you will need to "pass ref which isn't necessary in this case", but it is totally necessary - you are depending on a provider!

It really isn't as much overhead as you might think.

If you are going to be using something like this where the `ResponsiveService` has nothing to do with application state, maybe just go with a global singleton class, or an `InheritedWidget`.

**Comment by AhmedLSayed9** [comment]
Thanks @TimWhiting for your replay.
Exactly as you mentioned `ResponsiveService` has nothing to do with application state. So, I think I'll go with another pattern/package instead of defining global ProviderContainer, until an improvement for cases like this happens.

What do you think of defining ResponsiveService globally instead of making ProviderContainer instance as global variable:
```
class SingleServices {
  static late final ResponsiveService responsiveService;
}

void main() {
  final ProviderContainer mainContainer = ProviderContainer();
  SingleServices.responsiveService = mainContainer.read(responsiveServiceProvider);
  runApp(
    UncontrolledProviderScope(
      container: mainContainer,
      child: const MyApp(),
    ),
  );
}
```
