### ISSUE TITLE
Slider list rendering error in pub example (`ListView.custom`)

### ISSUE THREAD

**Issue by iamsahilsonawane** [rrousselGit/riverpod#1707]
**Describe the bug**
While scrolling down (when items are still loading to a greater extent) the `ListView.custom` throws an error.

**Error**
```shell
'package:flutter/src/rendering/sliver_list.dart': Failed assertion: line 186 pos 16: 'earliestUsefulChild != null': is not true.
```

**To Reproduce**

Scroll to the bottom beyond the expected results count and then when data is fetched and is less than the count of scrolled offset, it throws the error.

Sharing a video demo as well.

https://user-images.githubusercontent.com/47249618/193222468-c11ced86-ca54-4ef8-a517-d9c85ab7c6f9.mov

**Expected behavior**
Should not throw the error.

**Comment by rrousselGit** [comment]
That's probably a bug in Flutter itself

**Comment by iamsahilsonawane** [comment]
But I am not sure how to reproduce it without using Riverpod to add an issue on the flutter/flutter repo.

**Comment by rrousselGit** [comment]
Flutter is the one that fails. Nothing I can do
