### ISSUE TITLE
StateNotifierProvider with .family modifier not updating its notifier state

### ISSUE THREAD

**Issue by mateendev3** [rrousselGit/riverpod#1710]
**Describe the bug**
While using StateNotifierProvider with .family modifier not updating its Notifier state for listeners.

**To Reproduce**

Video of bug.
<a href="https://www.veed.io/view/a909b7b0-d370-45ba-b536-50574fa5d2a5/showcase">VIDEO OF THE BUG</a>

**Expected behavior**
I think the expected behavior should be the same without the .family modifier. I want to pass data to the provider that's why I used the .family modifier. and this happened to me (watch video).

**Comment by mateendev3** [comment]
I even passed primitive values and family behavior is identical.

**Comment by TimWhiting** [comment]
Passing any two different values will result in separate StateNotifiers being created for each.

**Comment by mateendev3** [comment]
Got it. Problem solved. My whole day passed finding the solution. Thank you. Remi and Tim. <3
