### ISSUE TITLE
selectAsync for StateNotifierProvider<AsyncValue<T>> missing

### ISSUE THREAD

**Issue by claudius-kienle** [rrousselGit/riverpod#1711]
**Describe the bug**
In version 2.0.0-dev.9 it was possible to use the `selectAsync` function on an `StateNotifierProvider<AsyncValue<T>>`, analog to the usage on `FutureProvider<T>`. On master, `selectAsync` does not exist for an instance of a `StateNotifierProvider<AsyncValue<T>>`.

**Comment by rrousselGit** [comment]
This isn't a thing anymore.

**Comment by claudius-kienle** [comment]
Do you then have a suggestion how to do following:
```dart
class LargeProvider extends StateNotifier<AsyncValue<SomeData>> {
...
}

final largeProvider = StateNotifierProvider<LargeProvider, AsyncValue<SomeData>>((ref) => LargeProvider());

final smallProvider = FutureProvider<SmallData>((ref) 
  => ref.watch(largeProvider.selectAsync((data) => data.relevant_attribute));
```

**Comment by claudius-kienle** [comment]
Alright. Thanks for your help:)
