### ISSUE TITLE
2.0.1 overrideWithValue not found.

### ISSUE THREAD

**Issue by HaijunWei** [rrousselGit/riverpod#1714]
The method 'overrideWithValue' isn't defined for the type 'AutoDisposeChangeNotifierProvider'.

**Comment by rrousselGit** [comment]
See the changelog, it is temporarily not available.

**Comment by HaijunWei** [comment]
sorry, where can i find the changelog.

**Comment by HaijunWei** [comment]
When can overrideWithValue come back? I used the v2.0.0-dev.9 version before, and now there is no official version that can be used normally.
