### ISSUE TITLE
AsyncValue doesn't enter the loading state after the initial loading on refresh/invalidate

### ISSUE THREAD

**Issue by Constans** [rrousselGit/riverpod#1719]
**Describe the bug**
AsyncValue when used with `.when` enters the `loading` state only the first time. Second reloads fail to enter the `loading` state.

This seems to be introduced in v. 2.0.x

A workaround is to use the AsyncValue `.isLoading` or `.isRefreshing` properties in the `data` state as they are picked correctly.

**To Reproduce**
Create a FutureProvider and use its returned AsyncValue with `.when` as described here: https://pub.dev/documentation/riverpod/latest/riverpod/AsyncValue-class.html

**Expected behavior**
The AsyncValue enters the loading state each time the `.refresh` or `.invalidate` are called on the provider.

**Comment by rrousselGit** [comment]
This isn't a bug. This is a feature.

That's part of the 2.0 change.

**Comment by Constans** [comment]
Ok. Didn't got that part reading through the change log. Just updated from 1.0.3 and now I see also the mention of this change. 
Sorry about wasting your time and thank you for the quick turnaround!
