### ISSUE TITLE
[website]: Automatically add an "outdated" banner to translated pages if they are out of sync with English

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1727]
## Problem
A difficult problem with dealing with docs translated into multiple languages is keeping all the languages in sync
It can be common for a page to receive new content, and another language to not have it yet.
Yet users looking at the translated page might not realize that this translation is possibly outdated.

## Proposal
One possible solution could be to add an optional version number in the metadata of MD docs. For example:

```md
// docs/getting_started.md
---
title: Getting started
doc-version: 2
---
```

Then, translations of this document should also specify the version number:

```md
// i18n/fr/getting_started.md
---
title: Débuter
doc-version: 1
---
```

From there, we could update the website to compare translated pages with the English one and compare their version number.

And if English version > Translated version, then we'd show a banner at the top of the page saying something among the lines of "This translation is possibly out of date. See [link to english] for up-to-date information"

**Comment by rrousselGit** [comment]
For info, the website is built using docusaurus. https://docusaurus.io/

So to implement this. we'd likely have to "swizzle" some components to inject custom code in the page. Their docs should be a good start

**Comment by Thesmader** [comment]
Hi @rrousselGit, I would like to help with this. I read the docs and tried swizzling the `DocItem/Content` component to display an `Admonition` component above the heading of the page as you can see below:
<img width="1440" alt="Screenshot 2022-10-10 at 5 35 35 PM" src="https://user-images.githubusercontent.com/34758667/194862579-ddbd7d79-2d02-4f51-87c4-c0e333e774f1.png">

Would something like this work?

**Comment by rrousselGit** [comment]
Oh, I'm sorry, this was implemented yesterday. But I forgot to close this
Example:
https://docs-v2.riverpod.dev/fr/docs/getting_started
