### ISSUE TITLE
Is `AutoDispose` prefix is needed for `(Async)Notifier` of `NotifierProvider.autoDispose`?

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/riverpod#1731]
**Describe the bug**

Is `AutoDispose` prefix is needed for `(Async)Notifier` of `NotifierProvider.autoDispose`?

**To Reproduce**

Run this:

```dart
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('', () async {
    final container = ProviderContainer();
    addTearDown(container.dispose);

    expect(container.read(counterProvider), 0);
  });
}

final counterProvider = NotifierProvider.autoDispose<Counter, int>(Counter.new);

class Counter extends Notifier<int> {
  @override
  int build() => 0;
}
```

Error log:

> Error: Type argument 'Counter' doesn't conform to the bound 'AutoDisposeNotifier<State>' of the type variable 'NotifierT' on 'AutoDisposeNotifierProviderBuilder.call'.

This resolved the error:

```diff
- class Counter extends Notifier<int> {
+ class Counter extends AutoDisposeNotifier<int> {
```

**Expected behavior**

I think it would be more natural`AutoDispose` prefix isn't needed for the `(Async)Notifier` of `NotifierProvider.autoDispose`, like StateNotifier, etc.
Is the AutoDispose prefix really needed?

**Comment by rrousselGit** [comment]
Yes, the prefix is needed. `AutoDisposeNotifier` wouldn't exist otherwise 😄.
It changes the `ref` type. 

That's why the code generator is a decent improvement. Because it removes this issue

**Comment by mono0926** [comment]
@rrousselGit 

Thanks, for the quick response 🙏 
I understand 👌
