### ISSUE TITLE
[riverpod_generator] Request: Add overrideWithValue & overrideWithProvider to generated family providers

### ISSUE THREAD

**Issue by GregoryConrad** [rrousselGit/riverpod#1738]
**Is your feature request related to a problem? Please describe.**
Creating a provider with the following will not add `overrideWithValue` & `overrideWithProvider` to the generated provider:
```dart
@riverpod
FooBar fooBar(FooBarRef ref, dynamic param) => throw UnimplementedError();
// ...
fooBar.overrideWithProvider(someOtherFamilyProviderWithSameParameters) // error; no method exists
```

**Describe the solution you'd like**
It would be nice if the code generator generated the above overrideWithX methods.

**Describe alternatives you've considered**
Manually defining the family provider works as-expected, but the syntax is not as elegant as the new code generator.

**Comment by GregoryConrad** [comment]
Looks like this will soon be solved with the new `overrideWith` functionality. Thanks Remi!

**Comment by rrousselGit** [comment]
overrideWith is present on all provider. So closing

There's a separate issue for overrideWithValue specifically
