### ISSUE TITLE
Continuous benchmark in CI?

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/riverpod#1740]
Hi, I see the `benchmark` folder and it looks quite good. I wonder whether it is possible to let it be in CI so we can continuously measure the performance?

I have done a bit research but seems no. But hope you have some approaches :)

**Comment by rrousselGit** [comment]
Maybe? Flutter does it.

But I don't have the time to do it. If someones wants to do it, that'd be lovely

**Comment by fzyzcjy** [comment]
> Flutter does it

Using their own device pool instead of public-available services :/

**Comment by rrousselGit** [comment]
We don't really care about devices.

**Comment by fzyzcjy** [comment]
You are right. I was thinking about https://github.com/fzyzcjy/flutter_smooth (Achieve 60 FPS, no matter how heavy the tree is to build/layout) - which does need real devices to test.

**Comment by rrousselGit** [comment]
We don't really need this here. Our benchmarks are pretty simple and don't need flutter

**Comment by fzyzcjy** [comment]
Sure, I just mean I wrongly thought about it :)

**Comment by rrousselGit** [comment]
Closing. No need to have an issue just for this and nothing actable in the short term
