### ISSUE TITLE
Flutter with Riverpod, Failed assertion: line 4610 pos 12: '!_dirty': is not true.

### ISSUE THREAD

**Issue by karlhp** [rrousselGit/riverpod#1748]
Flutter throws an assertion when building the following Android app with flutter_riverpod 2.0.0, 2.0.1 and 2.0.2.

<pre>
 The following assertion was thrown building ProviderScope(state: ProviderScopeState#5fd9f):
 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4610 pos 12: '!_dirty': is not true.
</pre>

**No assertion is thrown with flutter_riverpod 2.0.0-dev.9.**

Because I am not sure whether this is a bug in flutter or flutter_riverpod I report this issue on both sides.
(https://github.com/flutter/flutter/issues/113189)

## Steps to Reproduce

1. Add `flutter_riverpod:  2.0.2' to your pubspec.yaml, `pub upgrade`
2. Execute `flutter run` on the code sample (Connected device is Android)

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final demoValueProvider = StateProvider<String>((ref) => '');

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerStatefulWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends ConsumerState<MyApp> {
  @override
  void initState() {
    super.initState();
    ref.read(demoValueProvider.notifier).state = 'ABC';
  }

  @override
  Widget build(BuildContext context) {
    final String demoValue = ref.watch(demoValueProvider);

    return MaterialApp(
      title: 'Flutter Project',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Home Page'),
        ),
        body: Center(child: Text(demoValue)),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Logs for `flutter run --verbose`  attached
```

```
Analyzing flutter_project...
No issues found! (ran in 18.7s)

```

```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19044.2006], locale de-AT)
    • Flutter version 3.3.4 on channel stable at C:\Users\info\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (4 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\info\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • M2006C3LG (mobile) • MVONRKOF7LVCGIMN • android-arm    • Android 10 (API 29)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2006]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

[flutter_run_verbose_logs.txt](https://github.com/rrousselGit/riverpod/files/9742035/flutter_run_verbose_logs.txt)

**Comment by alper-efe-sahin** [comment]
@karlhp does it only valid for an Android app?

**Comment by karlhp** [comment]
@alper-efe-sahin

It's almost the same error message on web.

<pre>The following assertion was thrown building ProviderScope(state: ProviderScopeState#84dce):
Assertion failed: file:///C:/Users/info/Documents/flutter/packages/flutter/lib/src/widgets/framework.dart:4610:12
!_dirty
is not true
</pre>

Hope that helps.
I have no possibility to build for iOS.

**Comment by rrousselGit** [comment]
It's a bug in your app
You're not allowed to modify providers inside `initState`.

Do the initialization inside the provider instead:

```dart
final demoValueProvider = StateProvider<String>((ref) => 'ABC');
```

**Comment by karlhp** [comment]
@rrousselGit , thanks for your help and info.

It sounds a bit strange to me. I am aware that I shouldn't set any state or ref.read() the state inside the build method but could set and modify the state in all other methods inside a ConsumerState class.

It would be convenient in initState(), for example if main() provides some arguments for MyApp() and in other cases where parameters are passed to widget constructors.

Does the initState() limit apply to all kinds of providers?

**Comment by rrousselGit** [comment]
If you have parameters coming from your widget, then maybe you're looking for "family"

This allows passing parameters to providers.

**Comment by rrousselGit** [comment]
Modifying providers while widgets are building is voluntarily not allowed.

Allowing it would lead to bad states

**Comment by karlhp** [comment]
> If you have parameters coming from your widget, then maybe you're looking for "family"
> 
> This allows passing parameters to providers.

So far I have used "family" to select single values only. Where would I use family to provide parameters received from the widget, in initState() or in another place?

Thank you!

**Comment by karlhp** [comment]
> If you have parameters coming from your widget, then maybe you're looking for "family"

That may work in some case. Yet I am wondering if it is possible to set some default provider values, for example data saved on disk, at the ProviderScope level, respectively inside main().  As far as I know this isn't possible because I dont't have access to "ref" inside main(), nor can I set any provider state default values in ProviderScope().

Thank you and sorry for the many questions!

**Comment by benjamincombes** [comment]
I have the same problem here; the only problem is that it started occurring after updating dependencies, and the error stack doesn't say anything about where the error occurs, so I'm having a hard time fixing this in hundreds of classes... I have a pretty large codebase now, if this is the intended behavior, do you think it would be possible to add as many details  as possible in the error message, to be able to fix the issue quickly when it occurs? Thanks for your help!

**Comment by joshminton** [comment]
Agreed, having the same problem but diagnosing the exact cause of it is very difficult without further info, all I know is that one of my 'initState' methods somewhere in the app is modifying a state....?
