### ISSUE TITLE
ConcurrentModificationError (Concurrent modification during iteration: Instance of '_LinkedListIterator<_ListenerEntry<File?>>'.)

### ISSUE THREAD

**Issue by TreyThomas93** [rrousselGit/riverpod#1750]
**Describe the bug**
Adding ref.onDispose to FutureProvider with .autoDispose that is watching a StateProvider is throwing the following error when the state of the state provider changes:

```
ConcurrentModificationError (Concurrent modification during iteration: Instance of '_LinkedListIterator<_ListenerEntry<File?>>'.)
```
When I remove ref.onDispose(), the error goes away. Is this a bug or am I using this wrong?

**To Reproduce**
```
final selectedFileProvider =
    StateProvider<File?>((_) => null, name: "selectedFileProvider");

final xmlDataProvider = FutureProvider.autoDispose<XmlDocument?>((ref) async {
  final file = ref.watch(selectedFileProvider);

  ref.onDispose(() {
    ref.invalidate(selectedFileProvider);
  });

  if (file == null) return null;

  final contents = await file.readAsString();

  final document = XmlDocument.parse(contents);

  await Future.delayed(const Duration(milliseconds: 1500));

  return document;
}, name: "xmlDataProvider");
```

**Expected behavior**
I am attempting to invalidate the state provider when the future provider is auto disposed of.

**Comment by rrousselGit** [comment]
You're not allowed to modify providers within `onDispose`, which includes not invalidating them

**Comment by TreyThomas93** [comment]
@rrousselGit But I do that throughout the rest of my code not problem.

**Comment by rrousselGit** [comment]
No problem until there is a problem :p 

This is not something supported. The behavior is unspecified and with a bunch of dangerous edge-cases. You shouldn't do it

**Comment by TreyThomas93** [comment]
@rrousselGit I think its the fact that I am attempting to invalidate a provider that I am also watching all in the same future provider. Like recursion or something?

**Comment by rrousselGit** [comment]
Probablu. But as I said, you shouldn't do that.

If anything, you should hit an assertion error saying you're not allowed to do it.
