### ISSUE TITLE
StateNotifier is dispose when provider value change

### ISSUE THREAD

**Issue by HXiaoMing** [rrousselGit/riverpod#1751]
i want to watch roomIdProvider in roomDetailProvider, but when roomIdProvider value change, _RoomDetailStateNotifier will dispose.  behaviors make me confuse, i has not use autoDispose, why _RoomDetailStateNotifier was dispose?

source code:
https://github.com/HXiaoMing/riverpod_issue.git

```
final roomDetailProvider =
    StateNotifierProvider<_RoomDetailStateNotifier, int>((ref) {
  final roomId = ref.watch(roomIdProvider);
  return _RoomDetailStateNotifier(roomId);
});

class _RoomDetailStateNotifier extends StateNotifier<int> {
  final int _roomId;

  _RoomDetailStateNotifier(this._roomId) : super(0) {
    print('RoomDetailStateNotifier init roomId $_roomId');
    requestRoomDetail(_roomId);
  }

  void requestRoomDetail(int roomId) {
    ///use roomId do something, such requestRoomDetail
  }

  @override
  void dispose() {
    print('RoomDetailStateNotifier dispose roomId $_roomId');
    super.dispose();
  }
}

final roomIdProvider = StateNotifierProvider<_RoomIdStateNotifier, int>((ref) {
  return _RoomIdStateNotifier();
});

class _RoomIdStateNotifier extends StateNotifier<int> {
  Timer? _timer;
  int _roomId = 0;

  _RoomIdStateNotifier() : super(0) {
    _timer = Timer.periodic(const Duration(milliseconds: 1000), (timer) {
      state = (_roomId++);
    });
  }

  @override
  void dispose() {
    _timer?.cancel();
    _timer = null;
    super.dispose();
  }
}
```

**Comment by rrousselGit** [comment]
That's expected. When `watch` returns a new value, the provider is re-executed. Therefore a new StateNotifier instance is created. So the old one is disposed

If you used `Notifier` instead of `StateNotifier` (which is new with the 2.0 and replaces StateNotifier), that wouldn't be a problem though

**Comment by HXiaoMing** [comment]
however, new StateNotifier instance is not created, just disposed the old one.

**Comment by HXiaoMing** [comment]
> That's expected. When `watch` returns a new value, the provider is re-executed. Therefore a new StateNotifier instance is created. So the old one is disposed
> 
> If you used `Notifier` instead of `StateNotifier` (which is new with the 2.0 and replaces StateNotifier), that wouldn't be a problem though

however, new StateNotifier instance is not created, just disposed the old one.

i want to launch a  global  roomDetailProvider to listen roomIdProvider, when roomId change, roomDetailProvider can 
requestRoomDetail by current roomId.  should i use listen or watch to  launch a  global  roomDetailProvider? and have any good idea to do like this?

source code:
https://github.com/HXiaoMing/riverpod_issue.git
