### ISSUE TITLE
Future.wait fails inside a provider, due to SynchronousFuture

### ISSUE THREAD

**Issue by ChristianGaertner** [rrousselGit/riverpod#1764]
**Describe the bug**
Using `Future.wait` to combine multiple providers silently fails, due to the semantic differences between `SynchronousFuture` and `Future`.

**To Reproduce**

```dart
final innerProvider = FutureProvider.family((ref, String id) => Future.delayed(const Duration(milliseconds: 100), () => 'computed-$id'));

final idProvider = FutureProvider((ref) => ['a', 'b', 'c']);

final combinerFlawedProvider = FutureProvider((ref) async {
  final ids = await ref.watch(idProvider.future);

  return Future.wait(ids.map((id) => ref.watch(innerProvider(id).future)));
});

// produces => `[]`

final combinerWorkingProvider = FutureProvider((ref) async {
  final ids = await ref.watch(idProvider.future);
  final List<String> res = [];
  for (final id in ids) {
    res.add(await ref.watch(innerProvider(id).future));
  }
  return res;
});

// produces => `['computed-a', 'computed-b', 'computed-c']`
```

**Expected behavior**
I expect that both `combinerFlawedProvider` and `combinerWorkingProvider` would behave the same from an output perspective. The API returns objects implementing `Future`, so I would assume that they follow the same semantics.

Or have I missed something in the documentation about using iteration inside of providers? If so, this should maybe be highlighted under [Combining Provider States](https://riverpod.dev/docs/concepts/combining_providers).

**Further notes**
This happens, because `SynchronousFuture` calls the callback passed to `then` in the same tick. `Future.wait` however relies on the fact, that the callback is *not* being executed in the same tick, as it does essentially this:

```dart
var remaining = 0;
for (final future in futures) {
  remaining++;
  future.then(() {
    remaining--;
  });
}
if (remaining == 0) {
  return [];
}
```

and since `then` is being called in the same tick for `SynchronousFuture` this boils down to:

```dart
var remaining = 0;
for (final future in futures) {
  remaining++;
  remaining--;
}
if (remaining == 0) {
  return [];
}
```

I see how `SynchronousFuture` has advantages for avoiding extra loading state frames... but this has caused some very annoying all day long debugging session, figuring out what's going on and narrowing it down to this minimal example. Mainly because we assumed that the objects returned would adhere to the `Future` contract. [Flutter issue](https://github.com/flutter/flutter/issues/71554)

Additionally using something like this to workaround this problem:
```dart

Future<Iterable<T>> waitSynchronousFutureAware<T>(Iterable<Future<T>> futures) async {
  return Future.wait([
    for (final f in futures)
      if (f is SynchronousFuture)
        Future.sync(() {
          late T t;
          f.then((v) => t = v);
          return t;
        })
      else
        f,
  ]);
}
```

does *not work*, since it will use the `SynchronousFuture` from `package:flutter/foundation.dart` which is a different type from the implementation in this repository.

**Comment by rrousselGit** [comment]
Thanks for the report! This is unexpected, of course.
First, a quick workaround is to do:

```dart
Future.wait([
  for (final id in ids) 
    Future.value(ref.watch(someProvider(id).future),
]);
```


I'm not super fond of the idea of removing `SynchronousFuture`. Ideally `Future.wait` should be patched to fix this. I don't see a reason not to accept a fix for that.

**Comment by rrousselGit** [comment]
https://github.com/dart-lang/sdk/issues/50204

**Comment by rrousselGit** [comment]
Solving the problem globally is fairly simple, by making a custom Future.wait

```dart
List<T> futureWait<T>(Iterable<Future<T>> futures) {
  return Future.wait(futures.map((f) => Future.value(f));
}
```

Then you can do a global `Future.wait` -> `futureWait` replace. This fixes the problem everywhere at once.

**Comment by rrousselGit** [comment]
But yes I agree that this is a problematic issue. I'm not really sure on what the ideal solution is though. I don't like either solution.

New APIs won't really fix the issue of it silently failing. Removing the SynchronousFuture makes the code worse for all correct usages. And keeping it as it is problematic on its own.

**Comment by TimWhiting** [comment]
I know FutureOr<T> is problematic. But if we have to create a workaround because of a language issue maybe we could create a helper like this. Of course it would need to be documented. But it would result in better behavior than resulting in errors due to a language issue, or being delayed a frame.

```dart
extension FutureOrMap<T> on FutureOr<T> {
  FutureOr<X> map<X>(FutureOr<X> Function(T) mapping) {
    if (this is T) {
      return mapping(this as T);
    }
    return mapping(await this);
  }
}
```

**Comment by rrousselGit** [comment]
FutureOr  doesn't work.

The issue is about making `await future` execute synchronously when possible. Which does not work with `FutureOr`

**Comment by ChristianGaertner** [comment]
I think having official apis to deal with this has two major advantages:

1. having one clear way to solve the problem of iterating over ref.watch futures makes it easy to enforce
so no discussions about using the custom futureWait function or doing a synchronous`[for (final f in futures) await f]`, which brings me to
2. having a `waitForAll` allows for optimising the loading of multiple futures.

say ref.watch returns 7 sync. futures and two async ones. a fast solution would be this:

```dart
final syncs = [ for (final f in futures.take(5)) await f ]; // all sync
final asyncs = await Future.wait(futures.skip(5));
return [...syncs, ...asyncs];
```

but this of course breaks down with interleaved futures, etc. So `waitForAll` could solve these cases and even be fully sync if needed.

But I cannot implement this helper myself currently in user land, as `SynchronousFuture` is not exposed (and I think it shouldn't either).

so something like:

```dart
final syncs = futures.whereType<SynchronousFuture>();
```

can currently only be implemented by a riverpod api.

I agree that having a fully sync provider can be really important for an UI, so the only solution we have right now is sequentially iterating over the futures and sacrificing a lot of performance in the async case (due to no parallelism which `Future.wait` provides).

Hopefully this was clear enough to understand :D

**Comment by rrousselGit** [comment]
> so something like:
> 
> ```dart
> final syncs = futures.whereType<SynchronousFuture>();
> ```

You wouldn't do that though
You'd use `Future.then`

This can be implemented outside of Riverpod, without `SynchronousFure` being public. 


___



The problem with having a custom `Future.wait` is that it's not intuitive. People would have to hit this issue first before they understand why they should use Riverpod's `Future.wait` instead of the one from the SDK.

That's a pretty bad user experience.  

There's also the issue of interacting with packages. If a package internally uses `Future.wait`, using that package + Riverpod could break, silently too.

So I don't think this truly solves the problem.

**Comment by rrousselGit** [comment]
For info:
I'll revert `ref.watch(provider.future)` returning a `SynchronousFuture`.

Instead I'll make `AsyncValue` always contain a reference to the previous data/error, and offers ways tp customize `when` to decide what to pick.
This should offer an alternate pack to fix the issue.
