### ISSUE TITLE
Document AsyncNotifier

### ISSUE THREAD

**Issue by h-unterp** [rrousselGit/riverpod#1767]
I did some experimenting with AsyncNotifier. Here are some of the resources I used to get to this point:

**The API page:** https://pub.dev/documentation/riverpod/latest/riverpod/AsyncNotifier-class.html

**The implementation with comments that are private (and useful)** https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/async_notifier/base.dart

**The unit tests:** https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/test/providers/async_notifier/async_notifier_test.dart

**Some comments that are relevant:** 
https://github.com/rrousselGit/riverpod/issues/57#issuecomment-1273293066
https://github.com/rrousselGit/riverpod/issues/1032#issuecomment-1205554145
https://github.com/rrousselGit/riverpod/issues/875#issuecomment-1272536326
https://github.com/rrousselGit/riverpod/issues/1404#issuecomment-1250355335

And my working example of using the new `ref.watch` inside build in order to combine two provider states:
https://github.com/h-unterp/async_notifier_test/blob/main/lib/async_notifier_test.dart

AsyncNotifier is a new provider type.

`The expected solution now is to use the new AsyncNotifier instead of StateNotifier. That's basically the fusion of FutureProvider & StateNotifier` from 
https://github.com/rrousselGit/riverpod/issues/875#issuecomment-1272536326

**Comment by h-unterp** [comment]
@FXschwartz asks:

> What's the recommended approach to accessing state inside of an AsyncNotifier?

@rrousselGit replies
> You can directly read `this.state.when`
> You can read `this.future` (equivalent of `ref.read(provider.future)`)
> Or you can use `this.update((T data) => data + 1)`

**Comment by h-unterp** [comment]
### Updating State
@FXschwartz asks:

> Very cool!
> So calling update((state) => state.copyWith(myValue: newValue)); should work just fine and trigger the rebuild?

@rrousselGit replies:

> `update` is equivalent to:

```dart
final data = await this.future;
final newState = cb(data);
state = AsyncValue.data(newState);
return newState;
```

> So it'll await build
> And if build throws, your update will throw too.

**Comment by h-unterp** [comment]
### Update

This is a working example of update: https://github.com/h-unterp/async_notifier_test/blob/041b0dc2a43fef222744860736366d1956fd29f3/lib/async_notifier_test.dart#L13

**Comment by l-7-l** [comment]
how to do listen AsyncNotifier  in another StateNotifierProvider for update StateNotifierProvider's State?

**Comment by rrousselGit** [comment]
You can call `ref.listen` inside `AsyncNotifier.build`

**Comment by l-7-l** [comment]
Thank you for your great work, I want to avoid state having AsyncValue and splitting API response data into many small, independent StateNotifierProviders, I don't understand how to do it

**Comment by otto-dev** [comment]
> You can call `ref.listen` inside `AsyncNotifier.build`

Is there a problem with calling `ref.listen` presumably over and over again on the same providers, every time `build` is called after a `watched` variable changed?

**Comment by VirtualAstronaut** [comment]
Hello isLoading is not getting true when i call my api call in build method override in my AsyncNotifier.
state is updating with new data but isLoading or loading property in when() does not get update.

is this expected behavior? is there any other way isLoading gets Update?

```
final leaveListNotifier =
    AsyncNotifierProvider<LeaveViewModel, LeaveStateModel>(
        () => LeaveViewModel());

class LeaveViewModel extends AsyncNotifier<LeaveStateModel> {
 
  Future<void> getLeaves() async {
    state = const AsyncLoading();
    apiService.getLeaves().then((value) {
      final leaveList = (value.response.data['data']['leave'] as List)
          .map((e) => LeaveModel.fromJson(e))
          .toList();
      final grantLeaveList =
          (value.response.data['data']['getGrantLeave'] as List)
              .map((e) => GrantLeaveModel.fromJson(e))
              .toList();
      state = AsyncData(LeaveStateModel(
          leaveList: leaveList, grantLeaveList: grantLeaveList));
    }).catchError((e) {
      if (e is DioError && e.response?.data == null) {
        showCenterDialog().then((value) {
          getLeaves();
        });
      }
    });
  }

  @override
  FutureOr<LeaveStateModel> build() {
    getLeaves();
    return state.value!;
  }
}
```

so currently i am calling my function call in initState like this that way it getsUpdate

```
SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
      ref.read(leaveListNotifier.notifier).getLeaves();
    });
```

**Comment by rrousselGit** [comment]
Tracking for documentation work moved to https://github.com/rrousselGit/riverpod/issues/2625 and https://github.com/rrousselGit/riverpod/issues/2630
