### ISSUE TITLE
[riverpod_generator] Stream returns AutoDisposeProvider instead of AutoDisposeStreamProvider

### ISSUE THREAD

**Issue by iLoveDocs** [rrousselGit/riverpod#1791]
### Minimal reproducible code: 

```dart
@riverpod
Stream<int> fooStream(FooStreamRef ref) => Stream.value(0);
```

### Problem: 

The generated `fooStreamProvider` is of type `AutoDisposeProvider` instead of `AutoDisposeStreamProvider`. 
That means listening to this provider no longer returns a `AsyncValue<int>` instead it returns the `Stream<int>`

```dart
var value = ref.read(fooStreamProvider); // `value` is of type `Stream<int>`
```

### Version: 
```
flutter_riverpod: 2.0.2
riverpod_annotation: 1.0.4
riverpod_generator: 1.0.4
```

**Comment by rrousselGit** [comment]
It's just not supported yet

See https://github.com/rrousselGit/riverpod/issues/1663
