### ISSUE TITLE
Add refreshing as state case in when

### ISSUE THREAD

**Issue by khari998** [rrousselGit/riverpod#1793]
Since `isRefreshing` was added to AsyncValue https://github.com/rrousselGit/riverpod/discussions/1600 here,
we have to account for it when refreshing a FutureProvider in the `data` property of `.when()` 

```dart
final someNetworkResult = ref.watch(someFutureProvider);

return someNetworkResult.when(
   data: (_) {
      return someNetworkResult.isRefreshing ? CircularProgressIndicator() : ActualWidget()
   }, 
   loading: () => CircularProgressIndicator(),
   error: ...,
)
```

This seems a bit clunky as refreshing is now its own separate state. If that's the case, it seems like it would make more sense to change `.when()` to add that state as well.

i.e: 
```dart
final someNetworkResult = ref.watch(someFutureProvider);

return someNetworkResult.when(
   data:...,
   loading: () => CircularProgressIndicator(),
   refreshing: () => CircularProgressIndicator(),
   error: ...,
)
```

**Comment by rrousselGit** [comment]
Closing as dupp of https://github.com/rrousselGit/riverpod/issues/1570
