### ISSUE TITLE
Explain more about why StateNotifier is preferred over ChangeNotifier

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1797]
(and within the same logic why the new `Notifier` is preferred over `StateNotifier`)

Some reference https://twitter.com/remi_rousselet/status/1583093751445999616

**Comment by huzaifansari54** [comment]
hello can i work on this issue

**Comment by rrousselGit** [comment]
Sure

**Comment by huzaifansari54** [comment]
thank  you sir can you guide me on that any reference, articles?

**Comment by rrousselGit** [comment]
This doesn't really make sense anymore with Notifier
