### ISSUE TITLE
Provide a way to manually set AsyncError when using AsyncNotifier

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#1808]
**Is your feature request related to a problem? Please describe.**
I'm using TDD architecture and I'm catching exceptions in the repo and return a Failure object.
When using `AsyncNotifier` I can't find a way to manually set AsyncError to my Failure object.

This is an example of what I'm trying to achieve:
```
class CitiesNotifier extends AsyncNotifier<List<City>> {
  @override
  Future<List<City>> build() {
    getCitiesUC = ref.watch(getCitiesUCProvider);
    return getCities();
  }

  late GetCitiesUC getCitiesUC;

  Future<List<City>> getCities() async {
    final _result = await getCitiesUC();
    return _result.fold(
      (failure) {
        //// Can't return or throw AsyncError here
        return AsyncError(failure, failure.stackTrace);
      },
      (orphansList) {
        return orphansList;
      },
    );
  }
}
```

Note: Throwing a new Exception is not suitable to the architecture as there're multiple or different ways of try catch handled in the repo already that return a parent class (Failure) at the end. Here's how the repo look like:
```
  Future<Either<Failure, List<City>>> getCities() async {
    if (await networkInfo.hasInternetConnection) {
      try {
        final cities = await remoteDataSource.getCities();
        await localDataSource.cacheCities(cities);
        return Right(cities);
      } on ServerException catch (e, st) {
        return Left(ServerFailure.fromException(e, st));
      }
    } else {
      try {
        final cities = await localDataSource.getCities();
        return Right(cities);
      } on CacheException catch (e, st) {
        return Left(CacheFailure.fromException(e, st));
      }
    }
  }
```

**Describe the solution you'd like**
I think providing a way to manually set AsyncError would be helpful to allow custom try catch implementations

**Describe alternatives you've considered**
I've tried to use `Notifier<AsyncValue>` instead of `AsyncNotifier` to be able to manually set AsyncError, but I'll not be able to asynchronously initialize it inside build().

**Comment by rrousselGit** [comment]
Throwing should be the correct solution.

But you can also do `state = AsyncError(...)`

**Comment by AhmedLSayed9** [comment]
> But you can also do `state = AsyncError(...)`

I need to return something in the build, so How `state = AsyncError(...)` will be used?

**Comment by rrousselGit** [comment]
Either throw or change the return type of your function.

**Comment by AhmedLSayed9** [comment]
Changing the return type of the function won't work. as I'm returning it in the `build()` which have a return type Future<List> 🙃

**Comment by AhmedLSayed9** [comment]
```
class CitiesNotifier extends AsyncNotifier<List<City>> {
  @override
  Future<List<City>> build() {
    getCitiesUC = ref.watch(getCitiesUCProvider);
    return getCities();
  }

  late GetCitiesUC getCitiesUC;

  getCities() async {
    final _result = await getCitiesUC();
    return _result.fold(
      (failure) {
        state = AsyncError(failure, failure.stackTrace);
      },
      (orphansList) {
        return orphansList;
      },
    );
  }
}
```

Making getCities() function dynamic will compile but it's not correct and will throw errors in run time .

**Comment by AhmedLSayed9** [comment]
```
class CitiesNotifier extends AsyncNotifier<List<City>> {
  @override
  Future<List<City>> build() {
    getCitiesUC = ref.watch(getCitiesUCProvider);
    return getCities();
  }

  late GetCitiesUC getCitiesUC;

  Future<List<City>> getCities() async {
    final _result = await getCitiesUC();
    return _result.fold(
      (failure) {
        throw failure;
      },
      (orphansList) {
        return orphansList;
      },
    );
  }
}
```

Throwing `Failure` and let AsyncError catch it has worked. Thanks!

I'm wondering if re-throwing the `Failure` object instead of assigning it to AsyncError has an impact on performance.

**Comment by AhmedLSayed9** [comment]
>         throw failure;

Re-throwing `Failure` object directly will reset the stack trace.
I was able to solve this by using [Error.throwWithStackTrace](https://api.dart.dev/be/185382/dart-core/Error/throwWithStackTrace.html) method as following:
```
Error.throwWithStackTrace(failure, failure.stackTrace);
```
