### ISSUE TITLE
Can't use AsyncNotifierProvider with .family

### ISSUE THREAD

**Issue by Fraa-124** [rrousselGit/riverpod#1817]
![Screenshot 2022-10-26 at 13 33 19](https://user-images.githubusercontent.com/82762789/198015826-e4c64689-74c8-405a-977a-27390679b549.png)

**Comment by rrousselGit** [comment]
You need to sublass `AsyncNotifierFamily`

**Comment by rrousselGit** [comment]
https://github.com/rrousselGit/riverpod/discussions/1813
