### ISSUE TITLE
Got Issue on latest commit on master

### ISSUE THREAD

**Issue by arjundevlucid** [rrousselGit/riverpod#1829]
**Describe the bug**
Cannot start app

**To Reproduce**

![image](https://user-images.githubusercontent.com/96035930/198495562-ab44c807-2831-4fde-a95c-611d56384c42.png)

**Expected behavior**
Should run

#1816 this commit may cause this one to fail

**Comment by rrousselGit** [comment]
I assume you're using git dependencies?
If so, it sounds like you didn't setup the dependencies properly.


You need to do:

```dart
# Using dependency_overrides is necessary due to flutter_riverpod depending on riverpod
dependency_overrides:
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod/
      ref: master
      path: packages/hooks_riverpod
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod/
      ref: master
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod/
      ref: master
      path: packages/riverpod
```

**Comment by Shreemanarjun** [comment]
> I assume you're using git dependencies? If so, it sounds like you didn't setup the dependencies properly.
> 
> You need to do:
> 
> ```dart
> # Using dependency_overrides is necessary due to flutter_riverpod depending on riverpod
> dependency_overrides:
>   hooks_riverpod:
>     git:
>       url: https://github.com/rrousselGit/riverpod/
>       ref: master
>       path: packages/hooks_riverpod
>   flutter_riverpod:
>     git:
>       url: https://github.com/rrousselGit/riverpod/
>       ref: master
>       path: packages/flutter_riverpod
>   riverpod:
>     git:
>       url: https://github.com/rrousselGit/riverpod/
>       ref: master
>       path: packages/riverpod
> ```

Yes right. Thanks will check with latest. 👍
