### ISSUE TITLE
Generate a reader for each provider

### ISSUE THREAD

**Issue by hamishjohnson** [rrousselGit/riverpod#1840]
**Is your feature request related to a problem? Please describe.**

It's quite verbose writing ref.read(xxxProvider) anytime you want to read a provider - and this probably leads to people abusing `ref.watch` when they should be using `ref.read`

**Describe the solution you'd like**

Riverpod generator would also generate a read function.

So the generator below would also generate a global read function that could be consumed like so `fetchProductProviderReader(ref, page: 1)` anywhere where there's a ref.

```
@riverpod
Future<List<Product>> fetchProducts(FetchProductRef ref, {required int page, int limit = 50}) async {
   ...
}
```

**Comment by hamishjohnson** [comment]
This could also be called `fetchProductProviderGetter` as I've seen online some people being confused that you have to read a provider. i.e. some people report finding it weird that you have to do `ref.read(xxxProvider).state = value`

**Comment by rrousselGit** [comment]
I don't mind the verbosity. Most of it gets auto-completed anyway. 

I prefer that over an inconsistent syntax. 
Currently no matter how you want to interact with a provider, the syntax always looks similar.


Also, to begin with, one of Riverpod's goal is to remove the need for "read". The issue about mutations would remove a lot of read usages for example. 
People should use reactive variants like watch/listen instead, not read.

Your suggestion goes against that by trying to make people use read more.

**Comment by hamishjohnson** [comment]
On a second look of the docs, I believe I might have been using riverpod wrong. I was under the impression that when reading a provider to access a method, it should be done as ref.read within an event callback. So every time i've needed to access a method, I've been using ref.read, rather than using the reference passed from ref.watch
