### ISSUE TITLE
[riverpod_generator] ability to change "Provider" postix to something else

### ISSUE THREAD

**Issue by dJani97** [rrousselGit/riverpod#1851]
**Is your feature request related to a problem? Please describe.**

When using `riverpod_generator`, all providers are generated with the "Provider" postfix. For example:

```dart
@riverpod
Dio dio(DioRef ref) => Dio();
```

in the generated `.g.dart` file, this creates the following provider definition:
```dart
final dioProvider = AutoDisposeProvider<Dio>( ... );
```

Since reading https://github.com/rrousselGit/riverpod/issues/197, I got into the habit of calling my providers "Pods", so in my projects, this would be called `dioPod`, which is 5 letters shorter.

**Describe the solution you'd like**

A parameter in `build.yaml` to change the "Provider" postfix. For example:
```yaml
builders:
  riverpod_generator:
    options:
      providerPostfix: "pod"
```

This may be a niche problem, but it would allow me to transition to `riverpod_generator` with less code refactoring.

**Comment by rrousselGit** [comment]
Sounds good. It's a low priority for me though. If someone wants that, I'd suggest making a pull request. I'd be more than happy to review it

**Comment by dJani97** [comment]
Thank you, I understand that it's a low priority.

This may sound obvious, but I realized that I could do:

```dart
@riverpod
Dio dio(DioRef ref) {
  return Dio();
}

final dioPod = dioProvider;
```

Although this solution is quite fragile, as there are now two different ways to reference said provider. It would be nicer if somehow I could scope the original reference, but again, that would require modifying it's name and adding a `_` prefix to it.
