### ISSUE TITLE
On the web side, if the size of the web is scaled, will the re-rendering of the interface occur? ? ?

### ISSUE THREAD

**Issue by pheromone** [rrousselGit/riverpod#1854]
**Describe the bug**
在web端上，如果缩放web的大小时，会发生界面的再次渲染？？？
On the web side, if the size of the web is scaled, will the re-rendering of the interface occur? ? ?
**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>
```
class ConveniencePage extends ConsumerWidget {
  ConveniencePage({Key? key}) : super(key: key);

  final convenienceStoreProvider = FutureProvider((ref) {
    return getconvenienceStoreData();
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: Colors.white70,
      appBar: _appBarWidget(context),
      resizeToAvoidBottomInset: false,
      body: SafeArea(
        child: Consumer(
          builder: (context, ref, child) {
            final state = ref.watch(convenienceStoreProvider);
            return state.when(
              data: (data) {
                return data.success == true && data.result!.isNotEmpty
                    ? EasyRefresh(
                        onRefresh: () async {
                          ref.refresh(convenienceStoreProvider);
                        },
                        onLoad: () async {},
                        child: ListView.builder(
                          itemCount: data.result!.length,
                          itemBuilder: (BuildContext context, int index) {
                            return _convenienceStoreItem(context, index);
                          },
                        ),
                      )
                    : const EmptyDataWidget();
              },
              error: (o, s) {
                return const NetErrorWidget();
              },
              loading: () {
                return const LoadingWidget();
              },
            );
          },
        ),
      ),
    );
  }
......
```

**Expected behavior**

**Comment by rrousselGit** [comment]
Hello!

I don't understand what this is about. Could you clarify?

**Comment by pheromone** [comment]
@rrousselGit  
hello，
For example, on the web, if you enter a page and a network request occurs, if you shrink the web browser again at this time, the network request will occur again. Android and iOS are good, I use   flutter_riverpod: 2.1.0  # state  2.0.0 有bug，web无法使用

**Comment by rrousselGit** [comment]
Do you have a complete example to reproduce this? There's probably more to it that causes this to happen, which you haven't shared.

**Comment by pheromone** [comment]
@rrousselGit   
这是完整的代码
Here is the complete code
点击 push push 
Click push push

https://github.com/pheromone/Flutter_learn_demo/tree/master/%E5%85%B6%E4%BB%96/%E6%A1%88%E4%BE%8B/riverpod_pro
https://github.com/pheromone/Flutter_learn_demo/blob/master/%E5%85%B6%E4%BB%96/%E6%A1%88%E4%BE%8B/riverpod_pro/result1.gif

**Comment by rrousselGit** [comment]
Sorry but I cannot reasonably read an entire project.


Please create a new minimal project, separate from your work, to reproduce the problem without having to learn your project.
