### ISSUE TITLE
 Riverpod family is having issue when returning http calls, the state stays in loading state not changed/refreshed to data or error /// Same code UI code is working without the family 

### ISSUE THREAD

**Issue by raghavan-mookiah** [rrousselGit/riverpod#1855]
**Describe the bug**
 Riverpod family is having an issue when returning HTTP calls, the state stays in the loading state not changed/refreshed to data or error /// Same code UI code is working without the family 
**To Reproduce**

//// Riverpoad family is having issue when returing http calls, the state stays in loading state not changed/refreshed to data or error
/// Same code UI code is working without the family 
final horoscopeDetailsProvider =
    FutureProvider.autoDispose.family<String, MyParameters>((
  ref,
  myParameters,
) async {
  var dio = Dio();

  const String url = 'https://aztro.sameerkumar.website/?sign=aries&day=today';

  Response response = await dio.post(url);
  var data = await response.data;

  var resultMap = (data as Map);

  //Example->  https://aztro.sameerkumar.website/?sign=aries&day=tod
  return resultMap['description'];
  });

final myFutureProviderWithHttpService = FutureProvider<String>((ref) async {
  //Request for http api calls

  var dio = Dio();

  const String url = 'https://aztro.sameerkumar.website/?sign=aries&day=today';

  Response response = await dio.post(url);
  var data = await response.data;

  var resultMap = (data as Map);
  log.debug(resultMap['description']);

  //Example->  https://aztro.sameerkumar.website/?sign=aries&day=tod
  return resultMap['description'];
});
Consumer(builder: (context, ref, child) {
      /*

       NOT WORKING WHEN FAMILY IS USED
      final futureAstro = ref.watch(
        horoscopeDetailsProvider(
          MyParameters(sign: sign, dayString: dayString),
        ),
      );
      */

      ///Same UI code is working when family is not used
      final futureAstro = ref.watch(myFutureProviderWithHttpService);

      log.info('result.isLoading${futureAstro.isLoading}');

      return Center(
        child: futureAstro.when(
            skipLoadingOnRefresh: true,
            skipLoadingOnReload: true,
            data: (data) => Text('5B.Future Provider with HTTP CA:: $data'),
            error: (error, stacktrace) => Text('error $error'),
            loading: () => CircularProgressIndicator()),
      );
    });

**Expected behavior**
The provider should behave the same for family or without a family provider. Seems like bug in the family implementation

**Comment by rrousselGit** [comment]
You most likely didn't respect the `family` constraints.

See https://riverpod.dev/docs/concepts/modifiers/family#passing-multiple-parameters-to-a-family

**Comment by raghavan-mookiah** [comment]
> You most likely didn't respect the `family` constraints.
> 
> See https://riverpod.dev/docs/concepts/modifiers/family#passing-multiple-parameters-to-a-family

Thanks, it worked when I changed my parameter class with equatable (see below).

Even though it is in the documentation, it is not very clear to me, tough learning path. I believe this should be caught in compile time or runtime or some warning instead of stuck on the loading. 

You can close this bug, please see if it can be improved by any chance in the future.



```
import 'package:equatable/equatable.dart';

class MyParameters extends Equatable {
  final String dayString;
  final String sign;

  const MyParameters({
    required this.sign,
    required this.dayString,
  });
  @override
  List<Object?> get props => [sign, dayString];
}
```

**Comment by rrousselGit** [comment]
There's a linter that is in progress. It would definitely show a warning in that scenario.

Until then, not much I can do.
