### ISSUE TITLE
riverpod_generator: Provide a way to create non-AutoDispose providers.

### ISSUE THREAD

**Issue by eggnstone** [rrousselGit/riverpod#1857]
Currently
```
@riverpod
class SomeNotifier extends _$SomeNotifier
```
creates
`final someNotifierProvider = AutoDisposeNotifierProvider<SomeNotifier>`

I need a non-AutoDipose provider, therefore I would appreciate an option to trigger the creation of such.

Current workaround:
Use `ref.keepAlive();` in `build()`.

**Comment by rrousselGit** [comment]
```dart
@Riverpod(keepAlive: true)
...
```

**Comment by eggnstone** [comment]
Thanks!
I didn't find it in the documentation. Maybe I'm blind or it may be missing.

**Comment by rrousselGit** [comment]
That's normal. Docs are pending :)
