### ISSUE TITLE
riverpod_generator: Have dispose() as an overridable method.

### ISSUE THREAD

**Issue by eggnstone** [rrousselGit/riverpod#1858]
Currently in a notifier created in the following way
```
@riverpod
class SomeNotifier extends _$SomeNotifier
```
I need to create my own onDispose method and announce it in the `build()` method:
```
@override
void build()
{
  ref.onDispose(_dispose);
}

void _dispose()
{
  // do stuff
}
```
I would prefer/expect the following way:
```
@override
void dispose()
{
  // do stuff
  super.dispose();
}
```

**Comment by rrousselGit** [comment]
The current design is voluntary, for consistency and to prevent misleading people.

"onDispose" doesn't quite behave like a "MyNotifier.dispose", as a provider reuses the notifier instance for the entire lifetime of the provider.  Yet `onDispose` may be invoked multiple times.

A `dispose` method would mislead people into thinking that they can do:

```dart
final someObject = SomeObject();

build() {
  ref.watch(something);
}

void dispose() {
  someObject.dispose();
}
```

This would incorrectly cause `someObject` to possibly be disposed multiple times.

**Comment by eggnstone** [comment]
Hm, I'm not sure if I fully understand.
But I'm ok with it being called multiple times.
I use it in the following way to clean up subscriptions.
Is this the recommended way then?
```
@Riverpod(keepAlive: true)
class UserNotifier extends _$UserNotifier
{
    StreamSubscription<DocumentSnapshot<UserModel>>? _streamSubscription;

    @override
    AsyncValue<UserModel> build()
    {
        ref.onDispose(_dispose);
		
        _streamSubscription = FirebaseFirestore.instance.doc(path).snapshots().listen(...);

        return const AsyncLoading<UserModel>();
    }

    void _dispose()
    {
        _streamSubscription?.cancel();
        _streamSubscription = null;
    }
}

```

**Comment by eggnstone** [comment]
Thank you!
