### ISSUE TITLE
Additional generic interfaces for families and async providers

### ISSUE THREAD

**Issue by Zekfad** [rrousselGit/riverpod#1864]
**Is your feature request related to a problem? Please describe.**
It's not easy for now to operate with families and `AsyncSelector` descendants in a generic way because `AsyncSelector` is internal interface.

For families I have a workaround now, but its's still a problem that `.call` is defined in `_FamilyMixin` instead of `Family` itself:
```dart
typedef GenericFamily<T, Arg> = ProviderListenable<T> Function(Arg);
typedef AsyncFamily<T, Arg> = GenericFamily<AsyncValue<T>, Arg>;
```

**Describe the solution you'd like**
* Make `AsyncSelector` public.
* Add generic interfaces.

I'd like to be able to do something like that (notice that you can access `selectAsync` without necessary knowing async notifier or future provider it is):
```dart
final AsyncProviderListenable<T> example = ...; // or some  other name idk
ref.watch(example.selectAsync(...));

final AsyncFamily<T, Arg> example = ...;
ref.watch(example(...).selectAsync(...));

final Family<T, Arg> example = ...;
ref.watch(example(...));
```

**Comment by rrousselGit** [comment]
What does "operating asyncSelector in a generic way" mean?

**Comment by rrousselGit** [comment]
Note that you're not meant to abstract the providers. So you shouldn't have "just" the listenable interface.

Providers should never me passed as parameter and only be global variables. In which case your problem probably wouldn't happen. Would it?

**Comment by Zekfad** [comment]
In my case providers are indeed global variables, but I pass them into special widget to minimize rebuilds to simply updatable `Text`s or some simple layout dependent on provider:

<details>
<summary>Part of Loadabale&lt;T&gt;</summary>

```dart
class Loadable<T> extends ConsumerWidget {
  const Loadable({
    required this.provider,
    required this.builder,
    required this.loadingBuilder,
    super.key,
  });
  // ...
  /// [Loadable] with text shimmer.
  Loadable.text({
    required this.provider,
    required this.builder,
    String? loadingText,
    List<String>? loadingTexts,
    bool expandLoadingWidth = true,
    super.key,
  }) : loadingBuilder = (
    () => loadingTexts != null
      ? ShimmerText.multiline(
        texts: loadingTexts,
        expandWidth: expandLoadingWidth,
      )
      : ShimmerText(
        text: loadingText,
        expandWidth: expandLoadingWidth,
      )
    );
  // ...
  final ProviderListenable<AsyncValue<T>> provider;
  final Widget? Function(T data) builder;
  final Widget Function() loadingBuilder;

  @override
  Widget build(BuildContext context, WidgetRef ref) =>
    ref.watch(provider).when(
      data: (data) => builder(data) ?? const SizedBox.shrink(),
      error: ErrorText.onErrorHandler,
      loading: loadingBuilder,
    );
}
```
</details>

<details>
<summary>Example use case</summary>

This widget is showing loading skeleton while data isn't ready, and text otherwise (name here is some object with fallback capabilities).
```dart
class BookName extends StatelessWidget {
  const BookName({
    required this.id,
    super.key,
  });

  final int id;

  @override
  Widget build(BuildContext context) =>
    Loadable.text(
      provider: bookNameProvider(id),
      builder: (name) => Text(name.value),
    );
}

```
</details>

Basically in my use case  `Loadabale<T>` is some neat way to handle errors and have an in-place provider widget, localizing rebuild only to actually updatable parts.

And there's an actually edge case, where I have 2 classes descendant from single parent, but has different way to obtain them (different API calls) and require generic (static typing) for that:
<details>
<summary>sample</summary>

```dart
// ignore: invalid_use_of_internal_member
AsyncSelector<T?> personProvider<T extends Person>(int id) {
  Person.throwOnUnboundType<T>();
  if (T == Author)
    // ignore: invalid_use_of_internal_member
    return authorProvider(id) as AsyncSelector<T?>;
  if (T == Reader)
    // ignore: invalid_use_of_internal_member
    return readerProvider(id) as AsyncSelector<T?>;
  throw DeadCodeError();
}
```
</details>

**Comment by Zekfad** [comment]
Regarding "operating asyncSelector in a generic way" is that:
```dart
// ignore: invalid_use_of_internal_member
typedef AsyncProviderListenable<T> = AsyncSelector<T>;

typedef GenericFamily<T, Arg> = ProviderListenable<T> Function(Arg);
typedef AsyncFamily<T, Arg> = AsyncProviderListenable<T> Function(Arg);

/// Returns new wrapper provider based on [providerFamily] with value selected
/// via [selector].
AsyncFamily<OutFamilyType, Arg> createSelectorProvider<OutFamilyType, InputFamilyType, Arg>(
  AsyncFamily<InputFamilyType, Arg> providerFamily,
  OutFamilyType Function(InputFamilyType data) selector,
) =>
  FutureProvider.autoDispose.family<OutFamilyType, Arg>(
    (ref, arg) async => ref.watch(providerFamily(arg).selectAsync(selector)),
  );
```

**Comment by rrousselGit** [comment]
I would recommend using `Consumer` instead
And maybe use an extension on `AsyncValue` to make a custom `when` with the default loading/error handling you desire.

**Comment by Zekfad** [comment]
@rrousselGit, thanks for your reply, still what about this one: https://github.com/rrousselGit/riverpod/issues/1864#issuecomment-1299815128 ?

**Comment by rrousselGit** [comment]
My answer stays the same. I'd recommend using Consumer or an AsyncValue extension instead

**Comment by Zekfad** [comment]
Thanks for your reply, I'm sorry to trouble you again.
I do understand what you meant by using Consumer and AsyncValue extension in context of Loadable<T>, but I'm missing how it can help in the 2nd scenario. There is basically a function to create wrapper __provider__ around existing provider (that impements `AsyncSelector`), it's really has nothing to do with `AsyncValue` or `Consumer` on it's own, so I'm quite lost here.

Let's say I could do the same with .`select` that is exposed via `ProviderListenable`, and that would be ok, but `AsyncSelector` is private API, so it is not very good to reference it, but there's no other way to get access to `.selectAsync` in general except for knowing exact type of provider you deal with (Future, AsyncNotifier, etc).

If you meant to move `.selectAsync` stuff to builder function of `Consumer`, that will make multiple repeating code parts (for example I have Book provider, but I want to reference name of the book in multiple widgets with different contexts and lauouts, so I'll have repeating `.selectAsync` with the same selector function in multiple locations, instead of having 1 neat "pre-selected" family provider).

**Comment by rrousselGit** [comment]
You're not supposed to create "wrapper providers" though. If you want reusable code between providers, you should make code that depends on `Ref` instead of the provider

**Comment by Zekfad** [comment]
Thanks for your reply, what about the case when I need code to be reusable across `Ref` and `WidgetRef`, they are distinct classes by design as was said in #1625?

**Comment by rrousselGit** [comment]
As said in #1625, you should not make code that depends on either Ref or WidgetRef.

Refactor WidgetRef cases into Refs instead, by extracting the logic into new providers.

**Comment by Zekfad** [comment]
> Refactor WidgetRef cases into Refs instead, by extracting the logic into new providers.

This is exactly creating a wrapper provider isn't it?

**Comment by rrousselGit** [comment]
No, it's not.  

You did:

```dart
final provider = myFunction(((ref) {

});
```

I'm saying to do:

```dart
final provider = Provider((ref) {
  final state = ref.myFunction();
  <possibly do something with state>
  return state;
});
```

**Comment by rrousselGit** [comment]
I'll close this as I have no plan on making such feature.

Providers should not be passed around. This problem is only one because that rule wasn't respected.
