### ISSUE TITLE
ConsumerWidget: Instead of changing the build() method signature, use extension methods to access "ref".

### ISSUE THREAD

**Issue by eggnstone** [rrousselGit/riverpod#1865]
I am sure you made the change voluntarily / on purpose but I can't help myself to wonder:

Why does ConsumerWidget need a different build() signature than StatelessWidget and StatefulWidget and ConsumerStatefulWidget?
I often start with StatelessWidget and refactor it to ConsumerWidget which then needs a change of the build() method.
Then sometimes I see I need a state, so I refactor to ConsumerStatefulWidget, and need to change build() again.

Why not use something like this:
```
extension Ref on BuildContext
{
    WidgetRef ref()
    => this as WidgetRef;

    T read<T>(ProviderListenable<T> provider)
    => ref().read(provider);
}

class SomeWidget extends ConsumerWidget
{
    @override
    Widget build(BuildContext context)
    {
        final provider = context.read(someProvider);
    }
}
```

**Comment by spydon** [comment]
This extension would be invalid anywhere where it is imported and you have a widget that isn't made to use a `WidgetRef` right?

**Comment by rrousselGit** [comment]
That's far less efficient, as it requires casting.

**Comment by rrousselGit** [comment]
The inconvenience of refactoring from StatelessWidget to ConsumerWidget could be solved by a refactoring option in the IDE. That's planned

At which point, the new signature is strictly superior

**Comment by rrousselGit** [comment]
Also it's confusing as people might be tempted to use those APIs in a `StatelessWidget`. This wouldn't work and throw at runtime.

The extra build parameter makes it compile safe.

**Comment by eggnstone** [comment]
I'm not happy about it but I understand your point better now.
Thank you for taking the time!
