### ISSUE TITLE
Listened StreamProvider is called with null value before being disposed

### ISSUE THREAD

**Issue by rivella50** [rrousselGit/riverpod#1871]
**Describe the bug**
I've just updated to flutter_riverpod version 2.1.1 (from 2.0.0-dev.9) and get now this error when logging out (which navigates the user to the login page) for both watched view models which listen to autodispose stream providers:
```
Null check operator used on a null value
package:riverpod/src/common.dart 446:7                                AsyncError.value
package:mrcleaner/app/home/contracts/contracts_view_model.dart 20:37  new ContractsViewModel.<fn>
package:riverpod/src/framework/element.dart 749:42                    ProviderElementBase._listenElement.<fn>
```

This is how a StreamProvider is listend to:
```
_ref.listen<AsyncValue<List<Contract>>>(contractsStreamProvider, (previous, next) =>
        _handleDocumentUpdates(next.value!),
    );
```
The streams are against Firestore docChanges.

It seems that both listeners receive a null value in next parameter before being disposed which didn't occur in version dev.9 and therefore didn't need to be treated.
There is no rebuild performed on the connected page which is watching the view models.

**Expected behavior**
This error shouldn't happen for the mentioned logout case, as it didn't occur in version dev.9.

When the listener handler is called this is the stack:
![Screenshot 2022-11-03 at 10 15 06](https://user-images.githubusercontent.com/54292/199686246-590cced6-288d-4adc-95fa-30f57afeedb0.png)

And this is the stack trace:
![Screenshot 2022-11-03 at 10 16 03](https://user-images.githubusercontent.com/54292/199686357-684030da-4940-4fbe-a0fc-74073a01fa9c.png)

**Comment by rrousselGit** [comment]
Your code doesn't handle errors, yet you appear to have an error. So I'd lean toward saying that this is expected

I'd suggest checking `AsyncValue.error`/`AsyncValue.stackTrace` to see why your code throws. Maybe your Stream emits an error.

**Comment by rivella50** [comment]
I just wonder why the error only happens after the Riverpod update - and this was the only update i did.
So why didn't this error occurr in version 2.0.0-dev.9 too?

This is the stacktrace i get:
```
#0      new Trace.current (package:stack_trace/src/trace.dart:96:39)
#1      throwErrorWithCombinedStackTrace (package:riverpod/src/stack_trace.dart:9:11)
#2      AsyncError.value (package:riverpod/src/common.dart:446:7)
#3      new ContractsViewModel.<anonymous closure> (package:mrcleaner/app/home/contracts/contracts_view_model.dart:21:37)
#4      ProviderElementBase._listenElement.<anonymous closure> (package:riverpod/src/framework/element.dart:749:42)
#5      _rootRunBinary (dart:async/zone.dart:1415:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1307:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1217:7)
#8      ProviderElementBase._notifyListeners.<anonymous closure> (package:riverpod/src/framework/element.dart:542:24)
#9      ResultData.map (package:riverpod/src/result.dart:60:16)
#10     ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:532:14)
#11     ProviderElementBase._performBuild (package:riverpod/src/framework/element.dart:371:7)
#12     ProviderElementBase.flush (package:riverpod/src/framework/element.dart:322:7)
#13     _ProviderScheduler._performRefresh (package:riverpod/src/framework/scheduler.dart:62:41)
#14     _ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:50:5)
#15     _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:392:12)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#24     _rootRun (dart:async/zone.dart:1391:13)
#25     _CustomZone.run (dart:async/zone.dart:1293:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#27     _invoke (dart:ui/hooks.dart:150:10)
#28     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#29     _drawFrame (dart:ui/hooks.dart:115:31)
```

What i don't understand is why there is a notifyListeners happening, nothing has changed in the data stream - ok null is also a change, but it doesn't evolve as new data from the stream.

**Comment by rrousselGit** [comment]
Who knows why this didn't happen in the -dev version. It could very well be that the -dev had a bug (it had many) for example.

Unless you give me a proper way of reproducing the problem, I don't think I can give you an answer.

**Comment by rrousselGit** [comment]
Another alternative is that while you updated Riverpod, you also upgraded another package. And that other package led to this error.  
Or since it's related to Firebase, maybe something changed with your Firebase setup.

There's too many possibilities for me to truly know what's going on.

**Comment by rivella50** [comment]
Reproducing may be difficult.
In `pubspec.yaml` and `pubspec.lock` i only see the changes regarding `riverpod` and `flutter_riverpod`.
The Firebase setup didn't change.
So i will just check for a null value in next param then.
Thanks for your thoughts.

**Comment by rivella50** [comment]
I use now this check which works fine:
```
_ref.listen<AsyncValue<List<Contract>>>(
      contractsStreamProvider, (previous, next) {
        if (next is! AsyncError) {
          _handleDocumentUpdates(next.value!);
        }
    },
);
```
