### ISSUE TITLE
AsyncValue.when should ignore rebuild when data is the same

### ISSUE THREAD

**Issue by Fraa-124** [rrousselGit/riverpod#1883]
**Is your feature request related to a problem? Please describe.**
When using AsyncValue.when to build my widget, when setting the state with the same data, the widget rebuilds.

**Describe the solution you'd like**
It should ignore the rebuild when data is equal, as providers do.

I have built this little example. 
https://dartpad.dev/?id=a795c1797c39e406ee2368b1c86d6979

It consist of an asyncNotifier with the state 'String' Fran.

When tapping a method 'reset', setting the state to 'Fran'. I think the widget shouldn't rebuild because the state is the same.

**Comment by rrousselGit** [comment]
Feel free to override `updateShouldNotify` if that's what you want.
