### ISSUE TITLE
[riverpod_generator] Some types get resolved to `dynamic`

### ISSUE THREAD

**Issue by Reprevise** [rrousselGit/riverpod#1894]
**Describe the bug**
Some of the types that I have as parameters get resolved to `dynamic`.

**To Reproduce**

Run the generator with this code. Instead of the `Locale` type, it'll use `dynamic` instead.

```dart
import 'package:flutter/material.dart';

part 'file.g.dart';

@Riverpod(keepAlive: true)
Future<Map<String, String>> fetchLocalizations(
  FetchLocalizationsRef ref, {
  required Locale locale,
}) async {
  return <String, String>{};
}
```

**Expected behavior**
I expect the generator to have generated with the type `Locale` instead of `dynamic`.

**Comment by rrousselGit** [comment]
I just tested, and the generator correctly generates `Locale`. 
So it works for me

**Comment by Reprevise** [comment]
@rrousselGit Ah, it appears to be an issue in Flutter 3.0.5/Dart 2.17. Is there anyway you can do a workaround or is the only solution here just to upgrade?

**Comment by rrousselGit** [comment]
There's nothing I can do, no
