### ISSUE TITLE
[riverpod_generator] doesn't work well with [cloud_firestore_odm_generator]

### ISSUE THREAD

**Issue by iLoveDocs** [rrousselGit/riverpod#1925]
**Describe the bug**

The `riverpod_generator` generates `dynamic` type provider when the provided type is the one generated from `cloud_firestore_odm_generator`.   

**To Reproduce**

Run the builder for this code:

```dart
import 'package:cloud_firestore_odm/cloud_firestore_odm.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

part 'foo.g.dart';

@JsonSerializable(createFieldMap: true)
class User {}

@Collection<User>('users')
final usersRef = UserCollectionReference();

@Riverpod(keepAlive: true)
class Foo extends Notifier<UserQuery> {
  @override
  UserQuery build() => usersRef;
}
```

The generated provider (in `foo.g.dart` file) and other part of it have `dynamic` type: 

> final fooProvider = NotifierProvider<Foo, dynamic>(...)
> ..
> dynamic build();

**Expected behavior**
It should have `UserQuery` type. 

#### Versions: 

```
  json_annotation: ^4.7.0
  cloud_firestore_odm: ^1.0.0-dev.38
  riverpod_annotation: ^1.0.6

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  cloud_firestore_odm_generator: ^1.0.0-dev.38
  riverpod_generator: ^1.0.6
```

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/riverpod/issues/1782

It's not really an issue with riverpod_generator. Rather it's a problem with build_runner.
There are possible workarounds possible in riverpod_generator, which is what https://github.com/rrousselGit/riverpod/issues/1782 is about. 

But ultimately the true solution is Static metaprogramming, once it becomes available

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/riverpod/issues/1782

It's not really an issue with riverpod_generator. Rather it's a problem with build_runner.
There are possible workarounds possible in riverpod_generator, which is what https://github.com/rrousselGit/riverpod/issues/1782 is about. 

But ultimately the true solution is Static metaprogramming, once it becomes available

**Comment by iLoveDocs** [comment]
@rrousselGit 

> There are possible workarounds possible in riverpod_generator

I'm sorry but I couldn't find it. Can you please tell me what that workaround is?
