### ISSUE TITLE
Ref and WidgetRef should have a common base class

### ISSUE THREAD

**Issue by dancojocaru2000** [rrousselGit/riverpod#1939]
Currently, I wrote this function:

```dart
void invalidateAllProviders(Ref ref) {
  [provider1, provider2].forEach(ref.invalidate);
}
```

However, because `Ref` and `WidgetRef` don't have a common base class, I need to either write 2 functions, or instead pass the invalidate method itself as parameter.

I think `Ref` and `WidgetRef` should have a common base class.

**Comment by rrousselGit** [comment]
It has been requested in other issues before.   
It is voluntary that they don't have a shared interface.


If you have logic that sometimes depends on Ref and sometimes on WidgetRef, it should be refactored to always use Ref

**Comment by dancojocaru2000** [comment]
Well, how would I refactor to always use Ref when it's not possible to get a ref from widgets?

**Comment by rrousselGit** [comment]
Put the logic in a provider.

For example do:

```dart
final myLogicProvider = Provider(MyLogic.new);
class MyLogic {
  MyLogic(this.ref);
  final Ref ref;
  void invalidateAll() {
      [provider1, provider2].forEach(ref.invalidate);
  }
}

...

ref.read(myLogicProvider).invalidateAll();
```

**Comment by dancojocaru2000** [comment]
I see.

Feels a tiny bit odd though. Perhaps it should be added to documentation.

Thanks!
