### ISSUE TITLE
[riverpod_generator] ability to change "Provider" postix to something else #1851

### ISSUE THREAD

**Issue by ju851zel** [rrousselGit/riverpod#1946]
**Is your feature request related to a problem? Please describe.**

When using riverpod_generator, a providers that is created by annotating a class has the explicit type of that class. Add the ability to change the return type of the provider to a super or sub type, 

The use case I'm thinking about is an abstraction layer via an interface.
Example:
```dart
abstract class HomeControllerInterface {
    void foo();
}

@riverpod(returnedType=HomeControllerInterface)
class HomeController extends _$HomeController implements HomeControllerInterface {
    @override
    HomeModel build => HomeModel();

    @override
    void foo() {}
}
```

This should change the type of the provider to the interface and have the concrete implementation of the annotated class.
```dart
final homeControllerProvider =
    AutoDisposeNotifierProvider<HomeControllerInterface, HomeModel>(
  HomeController.new,
  name: r'homeControllerProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : $HomeControllerHash,
);
typedef HomeControllerRef
    = AutoDisposeNotifierProviderRef<HomeModel>;

```

This may be a niche problem, but we are heavily using interfaces for abstraction and therefore a feature like that would be nice..

**Comment by rrousselGit** [comment]
First, your code wouldn't work. `HomeControllerInterface` doesn't respect the constraints of `AutoDisposeNotifierProvider`

Secondly, what's the use-case?

**Comment by ju851zel** [comment]
You're right this would be a problem, sorry I didn't notice.

The use case would be to make abstraction via interfaces possible with the generator.
So that the provider does only expose an Interface and not the concrete implementation.

This was possible when using the StateNotifierProvider and the manual provider definition. like so:

Defining an interface as an abstraction layer.
```dart
abstract class HomeController extends StateNotifier<HomeModel> {
  HomeController(HomeModel state) : super(state);
}
```

Define the provider that only exposes the interface and inject the dependencies in the provider definition
```dart
final StateNotifierProvider<HomeController, HomeModel>
      homeControllerProvider = StateNotifierProvider<HomeController, HomeModel>(
    (StateNotifierProviderRef<HomeController, HomeModel> ref) =>
        HomeControllerImplementation(
      authenticationService: ref.read(providers.authServiceProvider),
    ),
  );
```

```dart
class HomeControllerImplementation extends HomeController {
  final HomeAuthenticationService _homeAuthenticationService;

  HomeControllerImplementation({
    required HomeAuthenticationService authenticationService,
    required HomeModel model,
  })  : _homeAuthenticationService = authenticationService,
        super(model) {
  }
```

The two main benefits are that components that use the HomeControllerProvider only need to know about the HomeController interface and not the concrete implementation maintaining the "program to interfaces, not implementations" principle.
Also the HomeController can be used and tested without any reference to any providers or riverpod itself which makes riverpod only neccessary in the view and the provider definition not other parts of the app.

**Comment by rrousselGit** [comment]
> Also the HomeController can be used and tested without any reference to any providers or riverpod itself which makes riverpod only neccessary in the view and the provider definition not other parts of the app.

Your code would still be bound to Riverpod. You shouldn't use Notifier without going through its provider. It has "ref" in it and various life-cycles

> The two main benefits are that components that use the HomeControllerProvider only need to know about the HomeController interface and not the concrete implementation maintaining the "program to interfaces, not implementations" principle.

The provider already should be a source of abstraction. It feels redundant to me.

But you could use a `factory`:

```dart
@riverpod
abstract class Foo extends _$Foo {
  factory Foo() = Impl;
  @override
  int build();
}

class Impl extends Foo {
...
}
```

**Comment by ju851zel** [comment]
I think I'm mixing two things here.
Because the generator is only a shorter solution than writing the provider itself I need to find a solution for my underlaying problem first and then find a solution to make it work with the generator.

The underlaying problem is that with the StateNotifierProvider API when creating a instance of my HomeControllerImplementation I already got a ref object.
Therefore I can read other providers and inject them into the HomeControllerImplementation.
So the HomeControllerImplementation itself doesn't know about provider and therefore can be testet simply by mocking the other providers  it depends on as basic object of plain dart classes.

Like so.
```dart
final StateNotifierProvider<HomeController, HomeModel> homeControllerProvider =
    StateNotifierProvider<HomeController, HomeModel>(
  (StateNotifierProviderRef<HomeController, HomeModel> ref) =>
      HomeControllerImplementation(
    authenticationService: ref.read(providers.authServiceProvider),
  ),
);

test() {
  HomeControllerImplementation(
    authenticationService: mockAuthenticationService,
  );
  verifyNever(mockAuthenticationService.getFirstName());
}
```
When now using the Notifier API the instantiation (by hand, without the generator) looks like that.


```dart
final NotifierProvider<HomeController, HomeModel> homeControllerProvider =
    NotifierProvider<HomeController, HomeModel>(
      () => HomeControllerImplementation.instance(
        authenticationService: ???, // here the ref is missing
      ),
);
```

Because the HomeControllerImplementation must override the `build` method which gets re executed when a depending provider changes, and not the first parameter of the StateNotifierProvider as before where I used the ref.

I must instantiate the HomeControllerImplementation first and read my depending providers in the build method.
Making the injection of dependencies not possible via the constructor, anymore.

**Comment by rrousselGit** [comment]
You're supposed to do that inside `build`

**Comment by rrousselGit** [comment]
I think you missed what I said before: You're not supposed to use the Notifier without its provider

Your `test` does not make sense. That's not something you should do. You should instead use a ProviderContainer and read the provider

**Comment by ju851zel** [comment]
I understand that I'm supposed to do that inside the build method when using the Notifier API.
But before that API existed we used the StateNotifier API.

When using the StateNotifier API it made sense for me to read depending providers A,B,C of a provider X when creating the provider X and injecting the read objects provided by the providers of A,B and C inside the construction of X. (like described above when creating the `homeControllerProvider`)

The benefits of that pattern (if you can call it like that) are that classes that are provided via a provider (like the class `HomeControllerImplementation` which is provided via the provider `StateNotifierProvider<HomeController, HomeModel>` can be tested without having to know that they are used in production inside of a provider.

This made it possible to unit test all classes, that are exposed via a provider in the production code, without having to instantiate a provider container and override all dependencies.
Because the dependencies where injected via the constructor and therefore the concrete implementation didn't  need to know about riverpod.

This sure did not test e.g. if a provider was rebuild correctly because not the provider itself, but the object it provides was unit tested, but it enabled the unit testing of all the logic inside a class without the overhead of having to create a provider container for every class.

I don't see a flaw in this process yet, and therefore don't understand I'm
> not supposed to use the Notifier without its provider
in e.g. unit tests.

Because this made something like that possible without the HomeControllerImplementaiton having to know that it is used in production inside a provider.
```dart
test('First name is saved to state after init', () async {
    const String testFirstName = 'Test';
    when(mockAuthenticationService.getFirstName())
        .thenAnswer((_) => Task.value(testFirstName));
    HomeControllerImplementation controller = HomeControllerImplementation(
      authenticationService: mockAuthenticationService,
    );
    await Future<void>.delayed(Duration.zero);
    expect(
      controller.debugState.firstName,
      equals(testFirstName),
    );
  });
```
So It basically makes dependency injection possible.

My problem is, that I couldn't make dependency injection possible with the new Notifier API yet.

But I'm very open to new suggestions on how to use the new Notifier API, which uses the build method where dependencies are referenced and make it impossible (to my current knowledge) to inject dependencies via the constructor.

By the way, thanks for the discussion and help ❤️

**Comment by rrousselGit** [comment]
Like I said, you're not supposed to do that. 

A `Notifier` is Riverpod-specific. You cannot use it independently.  The class depends on `ref`, and trying to manually instantiate the class means it'll be in an invalid state.  
To begin with, `Notifier` shouldn't have a public constructor. Once we have static metaprogramming, you won't be able to instantiate the Notifier yourself anymore. 

You should put your logic in `build` and write your test by reading the provider.   

Trying to test the class in isolation is not a good idea, because the provider is an integrant part of the logic of the notifier.  
By testing the notifier without its provider, you are testing it in a scenario that is not realistic, and you're bound to face issues.


You should give up on the idea of using the notifier directly. That's not something that makes sense with `Notifier`.

**Comment by rrousselGit** [comment]
Closing. As I've said, Notifier/AsyncNotifier are bound to Riverpod and should not be instantiated without going through a Provider.

The fact that you can do so right now is merely a language limitation.
