### ISSUE TITLE
AsyncValue as a seperate package

### ISSUE THREAD

**Issue by mohamed-yahyaoui** [rrousselGit/riverpod#1952]
I think that sperating AsyncValue as an indepedent library will be great idea for people who cannot use riverpod. It really helps to reduce a lot of boilerplate

**Comment by rrousselGit** [comment]
Feel free to copy the source.   
Alternatively you can still depend on `riverpod`. It's a pure dart package, and dart has tree-shaking.

I don't plan on making a package for this.
