### ISSUE TITLE
StateProvider not refresh UI, updateShouldNotify return from set state also when the previous and current are different

### ISSUE THREAD

**Issue by giandifra** [rrousselGit/riverpod#1969]
**Describe the bug**
All my StateProvider not refresh the UI. 
One of my case: I have a simple StateProvider linked to a CheckBox, when i update the state UI is not refreshed.
I attach a video to show that the `updateShouldNotify` every time return from set state also when the previous and current are different;

**To Reproduce**

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final pageControllerProvider =
    Provider.autoDispose<PageController>((ref) => PageController());

final confirmExportProvider = StateProvider.autoDispose<bool>((_) => true);

class MyWidget extends ConsumerWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final confirm = ref.watch(confirmExportProvider);
    return Checkbox(
        value: confirm,
        onChanged: (value) {
          if (value == null || value == confirm) return;
          ref.read(confirmExportProvider.notifier).update((state) => !state);
          // OR
          // ref.read(confirmExportProvider.notifier).state = !confirm;
        });
  }
}

class MigrationScreen extends ConsumerWidget {
  const MigrationScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: PageView(
        controller: ref.watch(pageControllerProvider),
        children: [
          PageThree(),
        ],
      ),
    );
  }
}

class PageThree extends ConsumerWidget {
  const PageThree({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            Row(
              children: [
                MyWidget(),
                Flexible(
                  child: Text('Lorem ipsum....'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```
I'm testing on Android with Flutter 3.3.7, 3.3.9  and: 

```
flutter_hooks: ^0.18.5+1
hooks_riverpod: ^2.1.1
riverpod_annotation: ^1.0.6
```
I also tried on dart pad and the behavior is correct respect my test.

https://user-images.githubusercontent.com/44344581/205282657-56611581-ecb5-49fb-8240-a67f960298be.mov

**Comment by giandifra** [comment]
> Could you share a minimal reproducible example? Not much I can do with what you shared.

I inserted a complete example. Thank you

**Comment by jeiea** [comment]
Video seems to use old version of state_notifier. It is different with [the line](https://github.com/rrousselGit/state_notifier/blob/75caa3ef4837df9a1639bbb7b6a28759c46b4fae/packages/state_notifier/lib/state_notifier.dart#L215) of current version.
`if (!updateShouldNotify(previousState, value)) {`

So how about checking the riverpod version? I think you can solve the problem by upgrading the riverpod or overriding the state_notifier version.

**Comment by trantrongkim98** [comment]
> Video dường như sử dụng phiên bản cũ của state_notifier. Nó khác với [dòng](https://github.com/rrousselGit/state_notifier/blob/75caa3ef4837df9a1639bbb7b6a28759c46b4fae/packages/state_notifier/lib/state_notifier.dart#L215) của phiên bản hiện tại. `if (!updateShouldNotify(previousState, value)) {`
> 
> Vậy làm thế nào về việc kiểm tra phiên bản riverpod? Tôi nghĩ bạn có thể giải quyết vấn đề bằng cách nâng cấp riverpod hoặc ghi đè phiên bản state_notifier.

It's worked for me. thanks

**Comment by trantrongkim98** [comment]
Hi @rrousselGit when i use StateNotifier for my state UI does not refresh
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// A Counter example implemented with riverpod

void main() {
  runApp(
    // Adding ProviderScope enables Riverpod for the entire project
    const ProviderScope(child: MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Home());
  }
}

/// Providers are declared globally and specify how to create a state
final counterProvider = StateProvider((ref) => CounterState(0));

class CounterState extends StateNotifier<int>{
  CounterState(int count):super(count);

  void increment(){
    state++;
  }
}
class Home extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter example')),
      body: Center(
        // Consumer is a widget that allows you reading providers.
        child: Consumer(
          builder: (context, ref, _) {
            final count = ref.watch(counterProvider.notifier).state;
            return Text('${count.state}');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // The read method is a utility to read a provider without listening to it
        onPressed: () => ref.read(counterProvider.notifier).state.increment(),
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
That's not how StateProvider works. You can't return a `StateNotifier` inside `StateProvider`. Use `StateNotifierProvider` instead

**Comment by rrousselGit** [comment]
I have tested the shared example and everything seems to be working as intended. 

Chances are you were using an outdated version of state_notifier with a bug. There are some of those :)
