### ISSUE TITLE
Using a riverpod generated Notifier that depends on an overridden Provider breaks.

### ISSUE THREAD

**Issue by hamishjohnson** [rrousselGit/riverpod#1992]
**Describe the bug**
I have an overridden userProvider which is then passed around in an authenticated app.

```
return ProviderScope(
   overrides: [
      userProvider.overrideWithValue(user),
   ],
   child: AuthenticatedApp(),
);
```
When I depend on the userProvider in another provider, I have to declare the dependency in the dependencies array or it throws.

With the new riverpod generator (at least for Notifier, haven't tested any other providers), it doesn't add dependencies to the array, and it breaks when depending on `userProvider`. I was able to confirm that it gets fixed when adding the correct dependencies to the generated file `.g.dart`.

**Expected behavior**
Riverpod generator should add correct dependencies to the dependencies array

**Comment by rrousselGit** [comment]
Not a bug. It's just that there's currently no way to specify `dependencies`. But the generator won't automatically generate that.

Once implemented, you should do `@Riverpod(dependencies: [...])`

There's already an issue for this and a WIP PR
