### ISSUE TITLE
Flutter Widget.when (loading ...) is called only once and never again even if invalidate/refresh is called

### ISSUE THREAD

**Issue by YiannisBourkelis** [rrousselGit/riverpod#2002]
**Describe the bug**
I am using a future provider the execute an asynchronous operation and I want to display a circular progress indicator like in the riverpod example here:[https://riverpod.dev/docs/providers/future_provider]( https://riverpod.dev/docs/providers/future_provider)

Here is my future provider code:
```
final myFutureProvider = FutureProvider<String>((ref) async {
  await Future.delayed(const Duration(seconds: 2));
  var s = DateTime.now().toString();
  return s;
});
```
and here is how I use it inside the build method:
```
  Widget build(BuildContext context) {
    final myfuturep = ref.watch(myFutureProvider);

    Widget futureWidget() {
      return myfuturep.when(
        loading: () => const CircularProgressIndicator(),
        error: (err, stack) => Text('Error: $err'),
        data: (config) {
          return Text(config);
        },
      );
    }
.
.
.
```

The problem is that the CircularProgressIndicator appears when the application is executed for the first time and never again, even when I call invalidate or refresh.

.
**To Reproduce**
Here is a project to reproduce the issue. Clicking on the "Invalidate future provider" button will execute the code of the future provider but the loading path will never be called.
[https://github.com/YiannisBourkelis/flutter-issues/tree/main/src/future_provider_no_loading](https://github.com/YiannisBourkelis/flutter-issues/tree/main/src/future_provider_no_loading)

![flutter-future-provider-no-loading](https://user-images.githubusercontent.com/2575796/207390274-2a5cccf2-7e07-47fc-b313-71eaf2b9c149.png)

Environment:
mac OS 13.0.1
VS Code  1.74.0
Flutter 3.3.9
flutter_riverpod: ^2.1.1

**Expected behavior**
Clicking on the "Invalidate future provider" button should display the CircularProgressIndicator until the future completes.

**Comment by rrousselGit** [comment]
That's expected.

See AsyncValue.isRefreshing/isReloading and AsyncValue.when(skipLoadingOnRefresh: bool)

**Comment by YiannisBourkelis** [comment]
thank you @rrousselGit . Setting skipLoadingOnRefresh: false did the trick. I was a bit confused with the parameter name because I was calling Invalidate.
