### ISSUE TITLE
Add an example for `StreamProvider`

### ISSUE THREAD

**Issue by exaby73** [rrousselGit/riverpod#2004]
Currently, `StreamProvider` in the docs only explains why you should use it and not how you should use it.

File in question: https://github.com/rrousselGit/riverpod/blob/cf1974eb873c9e5372f10c3b8d202a404bb180f4/website/docs/providers/stream_provider.mdx

**Comment by huzaifansari54** [comment]
hello can i contribute here ?

**Comment by rrousselGit** [comment]
Sure

**Comment by huzaifansari54** [comment]
i add example docs for stream provider
