### ISSUE TITLE
Generated Family class not const

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#2005]
**Describe the bug**

I've been messing around with generated providers, and one of them was family parameters. i noticed, when looking through the generated file (to try and understand more of whats happening) that the generated Family classes were not given const constructos, when the superclass itself is const.

**To Reproduce**

```dart
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'file.g.dart';

final f = _serverListPageProvider;
const c = _serverListPageProvider; // does not compile

@riverpod
class _ServerListPage extends _$ServerListPage {
  @override
  build({required int profileIndex}) => 1;
}
```
generated:
```dart
...
typedef _ServerListPageRef = AutoDisposeNotifierProviderRef<dynamic>;

/// See also [_ServerListPage].
final _serverListPageProvider = _ServerListPageFamily();

class _ServerListPageFamily extends Family<dynamic> {
  _ServerListPageFamily();  // <<<<<<<<<<< not const, even though the superclass *is* const, and setting it to const seems to be fine

  _ServerListPageProvider call({
    required int profileIndex,
  }) {
    return _ServerListPageProvider(
      profileIndex: profileIndex,
    );
  }
  ...
}
...
```
**Expected behavior**
I generally expect code that can be const, _should_ be const. it makes sense here too, as the family system doesnt exactly hold any state until you actually use it to get the provider within

**Comment by rrousselGit** [comment]
Not a bug. Generated providers are voluntarily not const, as this otherwise breaks the hot-reload mechanism in place.


The superclass is const because I tried implementing `const` providers at some point. Didn't work :p

**Comment by TekExplorer** [comment]
makes sense. might be worth adding that as a comment on the superclass, or just making the superclass not const
