### ISSUE TITLE
bug: build is called every-time any function from the provider is called

### ISSUE THREAD

**Issue by varunbhalerao56** [rrousselGit/riverpod#2016]
**Describe the bug**
After changing state of **AutoDisposeAsyncNotifierProvider** the value goes back to null. I am not sure if this is a bug or something I am doing wrong.

Using `riverpod 2.1.1`

**To Reproduce**

This is the provider code.
```dart
@riverpod
class SingleAddressController extends _$SingleAddressController {
  @override
  FutureOr<AddressInfo?> build() {
    return state.value;
  }

  Future<void> onSave(GlobalKey<FormState> formKey, context) async {
    log(state.value.toString()); // <--- Here value is null

    if (formKey.currentState!.validate() && !state.value.isNull()) {
      await ref.read(addressServiceProvider.notifier).addOrUpdateAddress(state.value!);
      Navigator.pop(context);
    }
  }

  void newAddressSetup() {
    final _uuid = ref.read(uuidProvider);
    ref.read(addressFormControllerProvider.notifier).clearSgLocateData();
    state = AsyncData(AddressInfo(addressId: _uuid.v4()));
  }

  void updateAddressDetails(AddressInfo address) {
    state = AsyncData(state.value!.updateAddressDetails(address));
  }
}
```
I am calling the `newAddressSetup` before going to the page. But the value always resets back to null.
```dart
       onPressed: () {
          ref.read(singleAddressControllerProvider.notifier).newAddressSetup();
          Navigator.of(context).push(AddOrEditAddressView.route(false));
        },
```

**Expected behavior**
I am trying to set up an address before I go to the `AddOrEditAddressView` and when `onSave` is called, it will save the address to my database.

**Comment by AhmedLSayed9** [comment]
This is not a bug. It’s the expected behavior.
You might need to check https://github.com/rrousselGit/riverpod/issues/1329 for more details and alternative solutions.
