### ISSUE TITLE
AutoDisposeProvider does not expose .notifier

### ISSUE THREAD

**Issue by serendipity1004** [rrousselGit/riverpod#2018]
AutoDisposeProvider that gets created when we use code generation on simple StateNotifier like function do not expose .notifier hence cannot update value.

if we generate code with following sample

```dart
@riverpod
int gState(GStateRef ref) {
  return 0;
}
```

we get below generated code

```dart
/// See also [gState].
final gStateProvider = AutoDisposeProvider<int>(
  gState,
  name: r'gStateProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : $gStateHash,
);
typedef GStateRef = AutoDisposeProviderRef<int>;
String $gFutureHash() => r'8b42b166fb6ea9f075f8811f6c7dbb6ce81c34dc';
```

when we try to modify the state of gStateProvider like below, I cannot get access to .notifier which means I cannot change the state. Is there something that I am doing wrong or is it a bug?

```dart
// .notifier does not exist!
ref.read(gStateProvider.notifier).update...;
```

**Comment by rrousselGit** [comment]
Provider does not have a `.notifier`, that's normal.

If you want a value which can be updated, make a class instead
