### ISSUE TITLE
`setState() or markNeedsBuild() called during build` errors after recreating container

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/riverpod#2022]
**Describe the bug**
This a bit of a tricky issue and has been hard to track down. I will try and create a reproducible sample but for now here is what I'm seeing.

My app is working 100% fine on first run, and when restarted at an a OS level. But if I [restart](https://stackoverflow.com/a/50116077) my app using a RestartWidget technique, I start seeing many `setState() or markNeedsBuild() called during build` errors throughout the app.

It seems to me like perhaps some subscriptions/listeners are not being cleaned up, and builds are being triggered unexpectedly.

### Some background
I use `GetIt` to store a `ProviderContainer`, provide that to a `UncontrolledProviderScope` and use it throughout the app.

**ProviderContainer registered in GetIt:**
```
inject.registerSingleton<ProviderContainer>(
    ProviderContainer(
      observers: [
        RiverpodLogger(),
      ],
      overrides: providerContainerOverrides,
    ),
    dispose: (it) => it.dispose(),
  );
```

**runApp with RestartWidget, UncontrolledProviderScope**
```
  runApp(
    RestartWidget(
      child: UncontrolledProviderScope(
      	container: inject<ProviderContainer>(),
		      child: _MyApp(),
    		),
    ),
  );

```

**How I 'restart' the app:**
```
Future<void> restartApp(BuildContext context) async {
  final container = inject<ProviderContainer>();
  // dispose of old ProviderContainer
  container.dispose();

 // Dispose the GetIt dependency tree
  inject.reset();

 // Setup new GetIt dependency tree (and ProviderContainer)
  await bootstrapDependencies();

// Trigger new app
  RestartWidget.restartApp(context);
}
```

### Expected behavior
I expect to restart the app and create the ProviderContainer, and not see setState errors.

 - Is there anything obviously wrong with this approach?
 - Are there any suggested ways to debug why this is happening?

**Comment by rrousselGit** [comment]
I'd need a wait to reproduce the error. You haven't shared it :)

**Comment by josh-burton** [comment]
Yes I haven't got a reproducible sample yet - its going to take a while to recreate one.

But do you see anything fundamentally wrong with how I'm creating/disposing/recreating the provider container above?

**Comment by josh-burton** [comment]
@rrousselGit I've managed to reduce my app down to a small reproducible sample:

https://github.com/josh-burton/riverpod-issue-2022

To Reproduce the issue:

1. Run the app (I'm running on iOS simulator)
2. Press Restart button (app restarts ok, not sure why because in my 'full' app the issue appears after a single restart).
3. Press Restart button again 
4. In the logs, see the following error:

`flutter: app restarted
flutter: app restarted
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_riverpod/src/framework.dart': Failed assertion: line 325 pos 12: '_task == null': Only one task can be scheduled at a time
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _UncontrolledProviderScopeElement._flutterVsync (package:flutter_riverpod/src/framework.dart:325:12)
#3      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:42:10)
#4      _ProviderScheduler.scheduleProviderRefresh (package:riverpod/src/framework/scheduler.dart:36:5)
#5      ProviderElementBase.invalidateSelf (package:riverpod/src/framework/element.dart:294:27)
#6      ProviderElementBase._markDependencyChanged (package:riverpod/src/framework/element.dart:599:5)
#7      ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:565:30)
#8      ProviderElementBase.setState (package:riverpod/sr<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This HomeScreen widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  HomeScreen
The widget which was currently being built when the offending call was made was:
  _DashboardBody
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4549:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4564:6)
#2      ConsumerStatefulElement.watch.<anonymous closure>.<anonymous c<…>
`


**Summary**
The issue seems to be caused by this particular combination of providers and where they are watched, and only after the app/container is restarted twice.

**Comment by josh-burton** [comment]
I've pushed an update to the bug repo with simplified code and a work around.

# Updated Bug Summary

There seems to a bug in Riverpod where calling runApp to re-create the app will cause the following error to be thrown:

```
Unhandled Exception: setState() or markNeedsBuild() called during build.
This HomeScreen widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  HomeScreen
The widget which was currently being built when the offending call was made was:
  _DashboardBody
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4549:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4564:6)
#2      ConsumerStatefulElement.watch.<anonymous closure>.<anonymous c<…>
```

### Work around

Calling runApp twice seems to fix the issue.

e.g. before calling main/runApp of the app, call a temporary `runApp(MaterialApp())` and then call main. The errors no
longer appear.

**Comment by hcanyz** [comment]
@rrousselGit @josh-burton I also encountered the same stack information, but I'm not sure if it's the same problem.

![image](https://github.com/rrousselGit/riverpod/assets/8407922/0bfa7d25-eee3-4cc3-bc19-484385682a32)

This is the smallest reproducible sample:

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const SafeArea(child: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var value1 = "123";

  var value2 = "321";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          Expanded(
            child: TestWidget.keyed(
              value: value2,
            ),
          ),
          Expanded(
            child: TestWidget.keyed(
              value: value1,
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {
          setState(() {
            final tmp = value1;
            value1 = value2;
            value2 = tmp;
          });
        },
      ),
    );
  }
}

final provider = Provider<String>((ref) => throw UnimplementedError());

final asyncProvider =
    AutoDisposeAsyncNotifierProvider<Notifier, String>(() => Notifier());

class Notifier extends AutoDisposeAsyncNotifier<String> {
  @override
  FutureOr<String> build() {
    final data = ref.watch(provider);
    return Future.delayed(const Duration(seconds: 2), () => "$data async");
  }
}

class TestWidget extends StatelessWidget {
  TestWidget.keyed({required this.value}) : super(key: ValueKey(value));

  const TestWidget({super.key, required this.value});

  final String value;

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
        overrides: [provider.overrideWithValue(value)],
        child: Consumer(
            builder: (BuildContext context, WidgetRef ref, Widget? child) {
          return ref.watch(asyncProvider).when(
              data: (Object data) {
                return Text(data.toString());
              },
              error: (Object error, StackTrace stackTrace) {
                return Text('Error: $error');
              },
              loading: () => const Center(child: CircularProgressIndicator()));
        }));
  }
}
```

Clicking the button twice will reappear.

I found two key points in this example:

1. It can be reproduced using ```TestWidget.keyed()```, but not ```TestWidget()```, And TestWidget cannot be at the same children level
2. asyncProvider must be AutoDispose

**Comment by rrousselGit** [comment]
I can confirm there's an issue here. But it's happening in an inconsistent manner, so it's going to be tricky to figure out what's happening.

It appears that a provider rebuilds twice in the same frame though

**Comment by rrousselGit** [comment]
It appears that when `UserProviders.currentUser` emits its current user, there is a chance that the `DashboardPage` widget will rebuild but `providerOfAppModel` provider won't.

So when `DashboardPage` rebuilds, it rebuilds `_DashboardBody`, which forcibly rebuilds `providerOfAppModel`. But `HomeScreen` haven't updated yet

I'm not sure how that's possible quite yet though.

**Comment by rrousselGit** [comment]
My theory is that it's a race condition which happens when the root ProviderScope is remounted.
Chances are the rebuild of `providerOfAppModel` is swallowed because of "vsync"/"scheduler" issues. But since `serProviders.currentUser` is unrelated to vsync/scheduler, its notification correctly rebuilds `DashboardPage`

**Comment by josh-burton** [comment]
Thank you for the fix ❤️🙏
