### ISSUE TITLE
Add an equality check parameter to `select` 

### ISSUE THREAD

**Issue by plammens** [rrousselGit/riverpod#2035]
Related to a piece of discussion found in #239.

**Is your feature request related to a problem? Please describe.**
I'm using `.select()` to optimize rebuilds. The return value of the selector is a list. I want my widget to rebuild only when the value of the list changes (where by value I mean its items and the order, not the list object's identity). Currently `.select()` uses `==`, which in `List`'s case compares identity.

**Describe the solution you'd like**
Add an `equality` parameter to `.select()` that allows users to customize how old and new values are compared for equality. Perhaps this should be a function or an `Equality` object.

**Describe alternatives you've considered**
The current workaround is to implement a list wrapper—or worse, a subclass—that overrides `==`, which is cumbersome.

**Comment by rrousselGit** [comment]
> The current workaround is to implement a list subclass that overrides ==, which is cumbersome.

This is the expected solution. There are various packages offering list implementations with an == override. And it moves the logic to the state owner rather than the UI

It also remove possible duplicates. Say the same list is "selected" in two different widget: With a custom list impl, both select use the same == logic by default. Whereas by having options on `select`, you'd have to customize both

**Comment by plammens** [comment]
> It also remove possible duplicates. Say the same list is "selected" in two different widget: With a custom list impl, both select use the same == logic by default. Whereas by having options on `select`, you'd have to customize both

The thing is that the consumers don't actually need the wrapper / subclass, they just need a regular list. So by using say, a wrapper, you're forcing them to do `wrapper.list` to extract what they actually need just because it is the only way to implement the desired codition for considering two states equal for the purpose of rebuilding the widget.

Furthermore, this rules out another use case, in which a widget still needs the entire object provided by a provider but needs to rebuild only when a certain function of the object changes, and where different widgets might need different conditions (all on the same provider). 

For example, consider a restaurant app with a restaurant details page, and suppose that the desired behaviour is that the restaurant page doesn't update in real-time unless the restaurant has been deleted. The widget still needs the entire restaurant object to display all of the relevant fields, like `restaurant.title`, `restaurant.description`, etc, but it only needs to rebuild when `restaurant.deleted` changes. Watching the provider as-is doesn't work because it would cause rebuilds when _any_ part of the restaurant changes. Using `provider.select((restaurant) => restaurant.deleted)` would also not be a solution because this would just return the boolean, and there would be no way to access the rest of the restaurant object. Even worse would be the strategy discussed above, where we implement `==` on `Restaurant` so that it just compares `restaurant.deleted`—this doesn't make sense from the business logic perspective, and we would be polluting state code with what is essentially UI code—or where we implement a wrapper around `Restaurant` that implements this condition inside `==`: what if there's another widget that needs to rebuild on a different condition, perhaps when `restaurant.title` changes, or anything else? We would need one wrapper for every condition (and again, we're building wrappers in the model that are just used for UI purposes).

In contrast, with this proposal the solution would be as simple as something like `provider.select((r) => r, key: (r) => r.deleted)` or `provider.select((r) => r, equality: (r1, r2) => r1.deleted == r2.deleted)`—like this it's very clear we're requesting the entire restaurant object but only require an update when the `deleted` property changes.

As I hope I have argued convincingly, there are workarounds to the above situations, but they're just that, workarounds, not actual solutions. To me it seems the most straightforward solution is to add a parameter to `select`.

**Comment by plammens** [comment]
I've made a draft PR to show one way this proposal could be implemented

**Comment by BreX900** [comment]
@plammens Another solution, more correct in my opinion, would be to port this implementation to the main package
This solution would cover your problem

https://github.com/kranfix/riverbloc/blob/master/packages/riverbloc/lib/src/listenable_provider_whenable.dart

**Comment by rrousselGit** [comment]
> So by using say, a wrapper, you're forcing them to do wrapper.list to extract what they actually need just because it is the only way to implement the desired codition for considering two states equal for the purpose of rebuilding the widget.

Doing `wrapper.list` shouldn't be needed. The custom list can implement `List<T>` (cf Dart's ListView). Then the wrapper would behave like a normal list

There are various packages doing this.

> Furthermore, this rules out another use case, in which a widget still needs the entire object provided by a provider but needs to rebuild only when a certain function of the object changes, and where different widgets might need different conditions (all on the same provider).

You're not supposed to do that. You're instead supposed to select all the properties you need.

Like:

```dart
final a = ref.watch(provider.select((obj) => obj.a));
final b = ref.watch(provider.select((obj) => obj.b));
```

Or maybe use tupples/records once we have them

So I disagree with your example. The whole point of `select` is to discourage doing such a thing. You shouldn't render a property in your UI if you're not listening to changes on that property.

**Comment by plammens** [comment]
> There are various packages doing this.

By the way, could you point me to a package with a class that implements `List` that overrides `==` with value equality?

I have been searching for one but haven't found it. So far I'm using my own custom wrapper but I'd prefer an actual `List` (which is a bit more cumbersome to mantain if I code it myself).

**Comment by BreX900** [comment]
@plammens You can use built_collection, fast_immutable_collections or kt_dart packages

**Comment by JulianBissekkou** [comment]
I would also love to see a equality check. In our case we have a `freezed` state that holds a list of items. In our `listen` we only select the list of items to make sure we don't call the function to often.
In that case the exact oposite happens.

Our workaround was this:
```dart
ref.listen<List<MyItem>>(
    provier.select((value) => value.someListValue), (last, next) {
  final isEquals = const ListEquality<MyItem>().equals(last, next);

  if (isEquals) return;

// continue
}
```

**Comment by raufer** [comment]
I've been battling with a similar situation. 

The only solution I could come up with to control unnecessary rebuilds was to use `.listen` :

```python
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.listen<List<Msg>>(counterProvider, (Msg? prev, Msg new) {
      if (condition) {
          setState(() {...})
      }
    });
```

**Comment by rrousselGit** [comment]
As said before, use a class which overrides ==.

You're free to define a generic class overriding == and deferring its implementation to a callback:

```dart
@immutabl
class Equal<T> {
  Equal(this.value, this._equal, [this._hashCode]);
  final T value;
  final bool Function(T value, Object other) _equal
  final int Function(T value)? _hashCode;

  @override
  bool operator ==(Object other) => _equal(value, other);

  @override
  int get hashCode => _hashCode(value) ?? super.hashCode;
}
```

Then used as:

```dart
provider.select(
  (value) => Equal(value, DeepCollectionEquality().equals),
);
```

That behaves exactly as a custom `equal` parameter on `select`.

**Comment by rrousselGit** [comment]
I don't plan on adding a custom equal parameter on select for the reasons mentioned above.
So I'll close this
