### ISSUE TITLE
Missing `as prefix` in generated code by `riverpod_generator`.

### ISSUE THREAD

**Issue by aoisensi** [rrousselGit/riverpod#2036]
**To Reproduce**

My code:
![image](https://user-images.githubusercontent.com/1350990/209932896-bbbd667b-8999-4507-8586-914fa1c6bd64.png)
Generated code:
![image](https://user-images.githubusercontent.com/1350990/209933376-672b3c1d-fc8f-4f62-bf1c-4e7f13c5c0e8.png)

Please let me know if you do not reproduce it.
I will paste the whole code and details.

**Comment by rrousselGit** [comment]
Import aliases aren't supported. Many generator don't support them

I don't plan on supporting it before Metaprogramming

**Comment by aoisensi** [comment]
Okay
