### ISSUE TITLE
riverpod_generator package should be installed under dev_dependency 

### ISSUE THREAD

**Issue by zigapovhe** [rrousselGit/riverpod#2038]
Documentation on installation on pub.dev is wrong. It is missing `--dev` flag. 
Command for package installation should be `dart pub add riverpod_generator --dev`

Readme is actually stating that package should be in dev_dependencies, but installing tab doesn't.

[Screenshot](https://i.imgur.com/2G7kipx.png)

**Comment by rrousselGit** [comment]
That's not something I have control over. The "install" tab on pub is auto generated by pub.dev, with no mean for package authors to customize it.
