### ISSUE TITLE
Search bar in the documentation website does not work

### ISSUE THREAD

**Issue by felipe-xavier** [rrousselGit/riverpod#2058]
If you try to search for content in the search bar of the riverpod documentation, it just does not work like in the pictures below. 

Used chrome and safari to test.
Both on https://riverpod.dev and https://docs-v2.riverpod.dev

Also, I kindly ask for a link that describes the refresh and invalidate methods if there is one.

Search bar:
<img width="484" alt="Screenshot 2023-01-05 at 20 11 11" src="https://user-images.githubusercontent.com/11222002/210861912-b8ef7c6c-9b5f-4206-9fc3-131384899363.png">

<img width="598" alt="Screenshot 2023-01-05 at 20 04 34" src="https://user-images.githubusercontent.com/11222002/210861947-4e7373e2-50d3-4060-8ffe-8e5431909c60.png">

<img width="586" alt="Screenshot 2023-01-05 at 20 04 23" src="https://user-images.githubusercontent.com/11222002/210861953-9d27e4e7-6d53-4a86-b40f-c586e12fd29b.png">

<img width="612" alt="Screenshot 2023-01-05 at 20 03 56" src="https://user-images.githubusercontent.com/11222002/210862023-82380fb8-8565-4d88-93dc-26076b8962a1.png">

**Comment by cbenhagen** [comment]
The algolia backends responds with a 403: `Invalid Application-ID or API key`.

**Comment by rrousselGit** [comment]
Thanks for the report. Fixed :)
