### ISSUE TITLE
Broken "Getting started" link on documentation website

### ISSUE THREAD

**Issue by zigapovhe** [rrousselGit/riverpod#2066]
Hi! I just noticed that "getting started" hyperlink has invalid URL and clicking on it shows "Page not found" error page.

You can find this "getting started" hyperlink at that [LINK](https://docs-v2.riverpod.dev/docs/about_code_generation/)

[Screenshot1](https://i.imgur.com/IAMbHdw.png)
[Screenshot2](https://i.imgur.com/2R6xjCq.png)

Thanks!

**Comment by rrousselGit** [comment]
Thanks! Fixed :)
