### ISSUE TITLE
Make dart:async optional in the generator

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2077]
The code-generator when writing:

```dart
@riverpod
class Foo extends _$Foo {
  @override
  Future<T> build() async => T();
}
```

generates code using `FutureOr`. As such, this requires importing `dart:async`, which is a bit confusing.

The code-generator could detect that `future` is returned instead of `futureor` and therefore generate replace `futureor` instances with `future` in the generated code

**Comment by TekExplorer** [comment]
"good first issue"
 -- is the maintainer

i admit, thats kind of funny.

**Comment by rrousselGit** [comment]
The tag is for folks looking at an easy issue to contribute to :)

Fixing this should be reasonably simple and with a very quick review.

**Comment by Timbwa** [comment]
Hi, would you mind me contributing to this? I can see the mentioned draft PR has not been updated for some time now.

**Comment by rrousselGit** [comment]
It's more my fault tbh as I was slow to reply.

I'd wait a bit more. But to begin with I'm making a large refactoring of the generator which should be published somewhere this week.
This likely would conflict.

It's probably best to wait one week

**Comment by Timbwa** [comment]
Alright. Thanks for the response. I'd also like to contribute more to 'good first issues'.

**Comment by rrousselGit** [comment]
riverpod_annotation currently exports FutureOr so this is fixed
