### ISSUE TITLE
Ability to get current state of FutureProvider as if it were an object/manipulatable data

### ISSUE THREAD

**Issue by 31Carlton7** [rrousselGit/riverpod#2078]
In Riverpod, you're able to create a FutureProvider as shown:

```
final helloWorldProvider = FutureProvider<String>((ref) async {
  await Future.delayed(Duration(seconds: 3));
  return "Hello world";
});
```
In Riverpod 2.0+ or Riverpod Generator, one can achieve this simply by using:
```
@riverpod
Future<String> helloWorld(HelloWorldRef ref) async {
  await Future.delayed(Duration(seconds: 3));
  return "Hello world";
}

// Or you can do something like this:

@riverpod
class HelloWorld extends _$HelloWorld{
  FutureOr<String> build() async {
    await Future.delayed(Duration(seconds: 3));
    return "Hello world";
  }
}
```

However, in these examples, when using the provider, you always have to obtain its current state with the `.when(...)` function. After running it once, it should be able to return its current state without having to run the entire future again, and if I haven't run it once, it should be able to return null. Ex:

```
ref.watch(helloWorldProvider).currentState; // null

ref.watch(helloWorldProvider).when(...)

// Somewhere else in the UI
ref.watch(helloWorldProvider).currentState; // "Hello World"

// Does not enable a refresh
ref.watch(helloWorldProvider).currentState = "Hello Riverpod";

ref.watch(helloWorldProvider).currentState; // "Hello Riverpod"
```

So effectively it should have the same capability as a StateProvider where the user can access the current state of it and manipulate it.

```
@riverpod
class HelloWorld extends _$HelloWorld{
  String build() {
    return "Hello World";
  }
}

ref.watch(helloWorldProvider); // Hello World
```

One thing I tried was using both a NotifierProvider and an AsyncNotifierProvider (In Riverpod 2.0 & Generator, however, this is also equivalent to using a StateNotifierProvider and a FutureProvider). In the following example I get an error saying that the value returned must be of type String and not AsyncValue<String>.

```
@riverpod
class HelloWorld extends _$HelloWorld{
  FutureOr<String> build() async {
    await Future.delayed(Duration(seconds: 3));
    return "Hello World";
  }

  String getHelloWorld() {
    return state; // Returns exception because the function's return type is String but the state is equal to AsyncValue.
  }
}
```

Because of this I end up writing lengthier files and find myself passing objects between Widgets because I cannot access them directly through the provider. For example: If I wanted to use my hello world provider on both screen 1 and 2, I would have to pass my string into the second screen after I obtain it from the first screen in a `.when(...)` function. However, when doing this with a StateProvider or NotifierProvider, you don't have to pass in the state at all, but instead you can simply call: `ref.watch(helloWorldProvider)`.

A current workaround for this was provided by [Adnan](https://github.com/adnanjpg) on [Stackoverflow](https://stackoverflow.com/questions/70639862/how-to-use-riverpod-by-combing-futureprovider-with-stateprovider/74800558?noredirect=1#comment132497685_74800558) which uses a StateProvider in addition to the FutureProvider and uses `Future.microtask(...)` to set the value of the StateProvider in the `.when(...)` function. Ex from Stackoverflow:

```
// this will obtain the future/initial value
final _futureCounterProv = FutureProvider(
  (ref) async {
    Future.delayed(
      Duration(seconds: 3),
    );
    return Random().nextInt(100);
  },
);

// this provider will provide the current value of the counter
final _counterProv = StateProvider((ref) => 0);

class Body extends ConsumerWidget {
  const Body({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ref.watch(_futureCounterProv).when(
      loading: () {
        return const Center(
          child: CircularProgressIndicator(),
        );
      },
      error: (error, stackTrace) {
        return Text(error.toString());
      },
      data: (data) {
        Future.microtask(
          () {
            // Assigning the future value to the `StateProvider`
            return ref.read(_counterProv.notifier).state = data;
          },
        );
        return Consumer(
          builder: (context, ref, _) {
            final count = ref.watch(_counterProv);

            return Column(
              children: [
                IconButton(
                  onPressed: () {
                    ref
                        .read(_counterProv.notifier)
                        .update((value) => value + 1);
                  },
                  icon: const Icon(Icons.add),
                ),
                Text(
                  count.toString(),
                ),
              ],
            );
          },
        );
      },
    );
  }
}
```
If you do not use `Future.microtask(...)` then you will get an exception saying that you tried to change the state of a provider as it was building inside of the `build()` or `initState()` or `didUpdate()` etc.

**Comment by rrousselGit** [comment]
Hello!

Are you looking for `AsyncValue.requireValue`?


```dart
FutureProvider<String> provider


build(context, ref) {
  String value = ref.watch(provider).requireValue;
}
```

**Comment by 31Carlton7** [comment]
Thanks for this. This solves the issue of retrieving the value, but I'm still not able to set the value like how you can set the NotifierProvider state. Will there be functionality for this in the future?

**Comment by 31Carlton7** [comment]
With an AsyncProvider, I don't believe there is the ability to set the state of it the same way you can with a StateProvider/NotifierProvider, unless I'm understanding it wrong. Should I continue using the workaround or, if you can, please provide and example of how to do this.

**Comment by rrousselGit** [comment]
You can freely call `state = AsyncValue.data(newState)` in AsyncNotifier

**Comment by adnanjpg** [comment]
I was a part of the conversation on stackoverflow that led to opening this issue. 

After a small demo, I found out that `AsyncNotifier` actually solves this.

In my case, I had a list screen where elements had ids related to other entities. In order to build the update form I needed to use the data already in hand and fetch the other entities from the server.

a simple example that uses `AsyncNotifier` to achieve this functionality:

##### (initializing the app)
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      child: MaterialApp(
        home: MyHomePage(),
      ),
    );
  }
}
```

##### the provider code
```dart
class Foo {
  // sync
  final int bar;
  // async
  int? baz;

  Foo(
    this.bar, {
    this.baz,
  });
}

Future<int> getBaz() async {
  return Future.value(1);
}

class FooController extends AsyncNotifier<Foo> {
  Foo foo;
  FooController(this.foo);

  @override
  FutureOr<Foo> build() async {
    foo.baz ??= await getBaz();
    return foo;
  }
}

final fooProv = AsyncNotifierProvider<FooController, Foo>(
  () => FooController(Foo(0)),
);
```

##### consuming the data
```dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Consumer(
        builder: (context, ref, _) {
          final fooAsync = ref.watch(fooProv);

          return fooAsync.when(
            data: (foo) => Text('bar: ${foo.bar}, baz: ${foo.baz}'),
            loading: () => const CircularProgressIndicator(),
            error: (err, stack) => Text(err.toString()),
          );
        },
      ),
    );
  }
}
```

**Comment by 31Carlton7** [comment]
Can confirm that this implementation works. I believe the documentation for this should be a bit more clear, as I couldn't find any guides or ways to achieve this especially for Riverpod 2.0 + Generator. I may add a guide to my blog on how to achieve this and how to use Riverpod 2.0 + Generator, as it will _eventually_ be the standard.

I reconstructed @adnanjpg's script so hopefully this can get added.

Running the app:
**main.dart**
```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      child: MaterialApp(
        home: MyHomePage(),
      ),
    );
  }
}
```

Creating the foo class and provider:
**foo.dart**
```dart
part 'foo.g.dart';

class Foo {
  final int bar;
  int? baz;

  Foo(
    this.bar, {
    this.baz,
  });
}

@riverpod
class FooController extends _$FooController {
  FooController(this.foo);

  Foo foo;

  @override
  FutureOr<Foo> build() async {
    foo = await getFoo();
    return foo;
  }

  Future<Foo> getFoo() async {
    await Future.delayed(const Duration(seconds: 1));
    return Foo(1);
  }
}
```

Implementation using Async capabilities:
**home.dart**
```dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Consumer(
        builder: (context, ref, _) {
          // Get the provider and watch it
          final fooAsync = ref.watch(fooControllerProvider);

          // Use .when to render UI from future
          return fooAsync.when(
            data: (foo) => Text('bar: ${foo.bar}, baz: ${foo.baz}'),
            loading: () => const CircularProgressIndicator(),
            error: (err, stack) => Text(err.toString()),
          );
        },
      ),
    );
  }
}
```

Implementation using Notifier capabilities:
**home.dart**
```dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Consumer(
        builder: (context, ref, _) {
          // Get Foo provider and set the state of it.
          // Use it as if it were a State Provider.
          ref.watch(fooControllerProvider.notifier).foo = Foo(3);

          // Use Foo in UI
          final foo = ref.watch(fooControllerProvider.notifier).foo!;
          // Use .when to render UI from future
          return Text('bar: ${foo.bar}, baz: ${foo.baz}');
        },
      ),
    );
  }
}
```

**Comment by 31Carlton7** [comment]
I do also recall having to update the foo.g.dart file to accommodate for the generated provider:

```dart
final fooControllerProvider = AutoDisposeAsyncNotifierProvider<FooController, Foo>(
  () => FooController(Foo(1)),
  name: r'fooControllerProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product') ? null : $FooControllerHash,
);
```

**Comment by adnanjpg** [comment]
I've updated the [answer](https://stackoverflow.com/a/74800558/12555423) on stackoverflow to include the latest result we've came up with.

**Comment by michaelsof47** [comment]
is possible if we have stored data or something data into riverpod ? because when i used stateprovider. there's not i'm found a option to write a new data. thx u in advance

**Comment by adnanjpg** [comment]
@michaelsof47 the problem is not really understandable from what you've said. please provide more details and provide a code example if possible

**Comment by michaelsof47** [comment]
ouwhh, i see.. so, i think to give a example...

Page1.class
`
class Page1 extends ConsumerStatefulWidget {

  @override
  ConsumerState<Page1> createState() => Page1State();
}

class Page1State extends ConsumerState<Page1> {

…

@override
void initState() {
  super.initState();

  ref.read(_argumentsData.notifier).state = “Done”;
 
}

…

}`

also, i create a custom provider class that use as bridge between two class

`final _argumentsData = StateProvider<String>((ref) => “”);`

and at page 2 class, i have called data like this

`class Page2 extends ConsumerStatefulWidget {

  @override
  ConsumerState<Page2> createState() => Page2State();
}

class Page2State extends ConsumerState<Page2> {

…

@override
void initState() {
  super.initState();

  var value = ref.watch(_argumentsData);
  print(value);
}

…

}`

but, when i try with this step. it give me error like this :

The following assertion was thrown building Builder:
dependOnInheritedWidgetOfExactType<UncontrolledProviderScope>() or dependOnInheritedElement() was
called before VerifyOTPPageState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively,
initialization based on inherited widgets can be placed in the didChangeDependencies method, which
is called after initState and whenever the dependencies change thereafter.

**Comment by adnanjpg** [comment]
it is not healthy to be updating a `StateProvider`'s state in `initState`, in the example you have provided it is not clear why you have the need to update the state inside `initState`, I need a more real example to understand why you need to do this, and if there's a more stable way to do this
