### ISSUE TITLE
Regression: StreamProvider depending on another StreamProvider is no longer working in riverpod 2.x

### ISSUE THREAD

**Issue by MichaelTamm** [rrousselGit/riverpod#2079]
**Describe the bug**
A `StreamProvider`, which depends on another `StreamProvider` like this:
```
final provider2 = StreamProvider<String>((ref) async* {
  yield* ref.watch(provider1.stream).map((event) => ...);
});
```
does no longer work, when it is used for the first time, and the other provider has already been used in another widget.

I stumpled over this bug when I tried to upgrade riverpod in a project from version 2.0.0-dev9 to 2.1.3

**To Reproduce**
I have extracted a test to demontrate the issue:
https://gist.github.com/MichaelTamm/5e4f9e8602455448e9426e9fe8484140#file-test_issue_2079-dart

If you add this test in the folder _packages/hooks_riverpod/test_ you can execute it.

The test is green when I checkout `v1.0.3` or `v2.0.0-dev9`, but turns red when I checkout `riverpod-v2.0.0`

**Expected behavior**
I think the test demonstrates a valid usage of riverpod and should therefore be green.
Please correct me, if this is not a valid way to define stream providers.

**Comment by rrousselGit** [comment]
This is expected. Your sample was never supposed to work, at least not reliably.

The gist of the issue is, you shouldn't rely on `.stream` for combining providers. Rather than:

```dart
final provider2 = StreamProvider<String>((ref) async* {
  yield* ref.watch(provider1.stream).map((event) => 'New value $event');
});
```

Instead do:

```dart
final provider2 = FutureProvider((ref) async {
  final event = await ref.watch(provider1.future);
  return 'New value $event';
});
```


The documentation of .future (or `.last` in 1.0.0) should explain the reasoning:

https://pub.dev/documentation/riverpod/1.0.3+1/riverpod/AutoDisposeAsyncProviderX/future.html

**Comment by rrousselGit** [comment]
The difference in behavior is induced by some 2.0.0 changes, where the stream returned by `StreamProvider.stream` is created at the same time that the `StreamProvider` is initialized.

Whereas in 1.0.0, the stream was created on first read of `.stream` with the latest provider's value as initial value.


This is a voluntary change, and is done for everything else too. Like `.future`, `.notifier`, ...

**Comment by MichaelTamm** [comment]
Thank you very much. That helped. :)
