### ISSUE TITLE
Generated updateShouldNotify

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#2081]
**Is your feature request related to a problem? Please describe.**
Currently, there is no consistent way to tell Riverpod if a value has changed. (or rather, _how_ it should tell if it changed)
This is especially relevant for Lists and Sets 

**Describe the solution you'd like**
Add an annotation field to tell Riverpod whether the value has changed.
For example (suggested by remi himself in discord)
```dart
@Riverpod(updateShouldNotify: function)
```

**Describe alternatives you've considered**
Directly overriding updateShouldNotify in generated classes, which does not have a function alternative

**Additional context**
This is useful for when our data is an object that does not implement value equality, or if devs would prefer to only compare specific values, for whatever reason.

This would allow us to avoid having to custom-implement == and hashcode for every object we need

**Comment by thanhdatvo** [comment]
Currently rivepod using identical(a,b) from dart:core to detect change.
But for some class, we expect to compare some attribute to decide equality. This could save some comparison computation between complex object values.
I wonder if we could in introduce a hook to modify updateShouldNotify() behavior for each provider at runtime

**Comment by TekExplorer** [comment]
> Currently rivepod using identical(a,b) from dart:core to detect change. But for detecting changes of values from some specific class, we expect to compare few attributes to decide equality, not all. This also could help to save some comparison computation between complex object values. I wonder if we could in introduce a hook to modify updateShouldNotify() behavior for each provider at runtime

I believe it is using `==`

**Comment by klondikedragon** [comment]
This use case is also relevant for me. For `StateNotifier` it is using `identical(a,b)` to determine if the value has changed. In some cases, I'm generating complex state, which if it changes can trigger the rebuild of large trees of widgets. So it is far less computationally expensive if it would be possible to customize operator == (or tell the provider some custom function to use for comparison).

**Comment by rrousselGit** [comment]
You can override updateShouldNotify when using the class syntax. That should be good enough
