### ISSUE TITLE
App Localization Arabic alignment not changing

### ISSUE THREAD

**Issue by steniljoseph** [rrousselGit/riverpod#2082]
Widget alignments are not proper in App localization (Arabic)

**Comment by rrousselGit** [comment]
Where/When?

**Comment by steniljoseph** [comment]
When we you with providerscope the arabic language is not changing from right to left

**Comment by rrousselGit** [comment]
I have no idea what you're talking about.

Please share a minimal reproducible example

**Comment by rrousselGit** [comment]
In the lack of a reply, I'll close this
