### ISSUE TITLE
how to use AsyncNotifierProvider.family?

### ISSUE THREAD

**Issue by xantocoder** [rrousselGit/riverpod#2087]
**Describe what scenario you think is uncovered by the existing examples/articles**
final filterFamilyNotifierProvider =
    AsyncNotifierProvider.family<FilterController, TaskFilterModel, String>(
        FilterController.new);

**Describe why existing examples/articles do not cover this case**
: Error: Type argument 'FilterController' doesn't conform to the bound 'FamilyAsyncNotifier<T, Arg>' of the type variable 'NotifierT' on 'AsyncNotifierProviderFamilyBuilder.call'.
package:organosheet2/…/task_manage_page/filter_controller.dart:37
- 'FilterController' is from 'package:organosheet2/app/controllers/pages/task_manage_page/filter_controller.dart' ('lib/app/controllers/pages/task_manage_page/filter_controller.dart')..

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
You need to subclass FamilyAsyncNotifier instead of AsyncNotifier

**Comment by xantocoder** [comment]
> 

thansk for your quick reply.
