### ISSUE TITLE
Golden test throws error when ref.read is being called inside dispose method

### ISSUE THREAD

**Issue by danieljosua1** [rrousselGit/riverpod#2091]
I have the following problem when I want to run a golden test:
I was able to reproduce the problem in the following test project: [https://github.com/danieljosua1/riverpod_golden_test](url)

I have created a very simple provider that contains only one string.

`final testProvider = Provider<String>((ref) => 'Test String');`

Then I wrote a golden test for the following MyHomePage widget.
When the dispose method in the test is run, and ref.read is accessed in it, an error is thrown

 ```
class MyHomePage extends ConsumerStatefulWidget {
  const MyHomePage({super.key});

  @override
  ConsumerState<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends ConsumerState<MyHomePage> {
  @override
  void dispose() {
    print(ref.read(testProvider));
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Title'),
        ),
        body: const Center(
          child: Text(
            'You have pushed the button this many times:',
          ),
        ));
  }
}
```

The test looks like this:
````
void main() {
  testGoldens('Test', (tester) async {
    final builder = DeviceBuilder()..addScenario(name: 'test', widget: const ProviderScope(child: MyHomePage()));

    await tester.pumpDeviceBuilder(builder);

    await screenMatchesGolden(tester, 'riverpod_golden');
  });
}
````

Maybe you could help me solve the problem

**Comment by rrousselGit** [comment]
That's logical. You're not allowed to call ref.read inside dispose (or any other context-based API, which Ref is)

**Comment by Letalus** [comment]
okay perfect gotchu. Thanks for the quick response
