### ISSUE TITLE
[Request] instead of reusing "read" method for both reading and updating value of a provider, have new seperated method for updating

### ISSUE THREAD

**Issue by thanhdatvo** [rrousselGit/riverpod#2092]
**Is your feature request related to a problem? Please describe.**
It does not related to any technical problem. It's just about Developer Experience
Currently, we are using this to update value of a provider: 
```
ref.read(provider.notifier).update((state) => newState);
```
Because we are using "read" as a function name for a value modification, it confuses new developers.
For developers who already knew that "read" is for either reading value or updating value, everytime they see the "read" method in Flutter code, they have to double check if parameter container ".notifier" to understand that  "read" is for updating, not for reading value

**Describe the solution you'd like**
A clear and concise description of what you want to happen:
Instead of using "read" to update, could we have precise "update" method, something like this
```
ref.updateState(provider.notifier, (state) => newState);
```
or just like this
```
ref.updateState(provider, (state) => newState);
```
**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by thanhdatvo** [comment]
I think we can do it in either of 2 ways:
1. Introduce an ModifiableProvider class that enforce "update" method that require all Providers using notifier attribute have to implement this class, so that in ConsumerStatefulElement we can introduce new update method:
```
  @override
   update<T>(ModifiableProvider<T> provider, T Function(T) update) {
    return ProviderScope.containerOf(this, listen: false).read(provider.notifier).update(update);
  }
```
2. Introduce "update" as an extention method. This is easier, however we are only able to check if provider has notifier or not at runtime, we cannot check using lint so this approach is prone to error.

**Comment by rrousselGit** [comment]
This is voluntarily not a thing, because only some providers are modifiable from outside. Not all of them

Such an API would allow modifying any provider, or would only work with some providers.

To begin with this syntax is bound to change with #1660

**Comment by rrousselGit** [comment]
Closing as this is voluntary. I do not want providers to expose a way of mutating them without explicitly defining methods.

This makes business logic much more maintainable as ensures all the logic for maintaining it is in one place: The notifier
