### ISSUE TITLE
`AsyncNotifier` doesn't clear old value if `state` is set after invalidating

### ISSUE THREAD

**Issue by tomgilder** [rrousselGit/riverpod#2097]
**Describe the bug**

After calling `ref.invalidate`, if an `AsyncNotifier` has its `state` to an error or loading state, then the previous value is maintained. This creates a race condition.

I feel that when calling `ref.invalidate`, the current value should be obliterated no matter what, so for example it can't be read via `.valueOrNull`.

We had a real-world case where a provider would error on log out. Because we were using `valueOrNull`, the old user object would hang around, effectively breaking log-out.

This behaviour changed in v2.1.2.

**To Reproduce**

Given this provider:

```dart
final counterProvider = AsyncNotifierProvider<CounterNotifier, int>(CounterNotifier.new);

class CounterNotifier extends AsyncNotifier<int> {
  @override
  FutureOr<int> build() {
    return 0;
  }

  void increment() {
    update((value) => value + 1);
  }

  /// Example method to trigger error state
  void error() {
    state = AsyncValue.error('Dummy error', StackTrace.current);
  }
}
```

Calling the methods in this order results in `valueOrNull` resetting to 0:

```dart
ref.read(counterProvider.notifier).error();
ref.invalidate(counterProvider);
```

But in the reverse order, the old state is still available:

```dart
ref.invalidate(counterProvider);
ref.read(counterProvider.notifier).error();
```

To me, this is surprising behaviour, seeing as the docs for `invalidate` say it will "cause the provider to be disposed immediately". It means you can't trust that `invalidate` will always clear the cached value.

The same happens if you set state to `AsyncLoading`.

**Expected behavior**

When invalidating any provider, any cached value is permanently unavailable.

**Comment by rrousselGit** [comment]
That's desired. Riverpod always tries to preserve the previous state in 2.0, with 2.1 and 2.1.2 covering more cases.  
There's nothing unexpected in what you shared.


You can either use `AsyncValue.unwrapPrevious()` or the farious flags of `when` or even the `AsyncValue.isReloading`/`AsyncValue.isRefreshing` flags to control how the consumer behaves

**Comment by tomgilder** [comment]
Hi Remi, thanks for the quick reply. Would you be open to have a way for AsyncNotifier to prevent a previous value being available?

I appreciate that preserving the previous value is great for most providers, but any app with log-in will want to completely clear the user provider state on log out.

If I have one `userProvider` and I’m consuming it in 30 places, it’s not ideal that we have to make sure every one of those 30 places is using it correctly, otherwise there could be a major bug.

**Comment by rrousselGit** [comment]
Feel free to make a feature request
