### ISSUE TITLE
`AsyncError.copyWithPrevious` is broken when used in AsyncNotifier

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#2102]
**Describe the bug**
When using `AsyncError.copyWithPrevious(AsyncData "or any AsyncValue")`, It'll not override previous data with the data passed using copyWithPrevious.

Reason for this, `AsyncTransition` extension already calling `copyWithPrevious` internally to preserve prev data/error. and it's called after the external copyWithPrevious is executed (Race condition), so it override the data passed with prev data again.

This should happen with `AsyncLoading.copyWithPrevious..` too but I think it's not happening because AsyncLoading has some mapping internally which cause some delay.

**To Reproduce**
https://dartpad.dev/?id=d13ba60290ea6912ed56c6294c57479b

**Expected behavior**
Possible solution is that `AsyncTransition` extension shouldn't override newState with prevState when the newState is already called with `copyWithPrevious`. I'll push a PR that should solve this.

**Comment by rrousselGit** [comment]
You're not supposed to manually call `copyWithPrevious` in AsyncNotifier though
The AsyncNotifier already does this for you

**Comment by AhmedLSayed9** [comment]
I noticed the behavior due to some of my projects got some issues:
```
  Future<void> signIn(..) async {
    state = const AsyncLoading<Availability>()
        .copyWithPrevious(const AsyncData(Availability.notAvailable));

    final result = await signIn(..);
    result.fold(
      (failure) {
        state = AsyncError<Availability>(failure, failure.stackTrace)
            .copyWithPrevious(const AsyncData(Availability.canSubmit));
      },
      (user) async {
        state = const AsyncData(Availability.success);
      },
    );
  }
```

**Comment by AhmedLSayed9** [comment]
I admit that my sample above can/should be refactored to another approach without using `copyWithPrevious`, but I think manually using `copyWithPrevious` might be helpful in some other use cases.

**Comment by AhmedLSayed9** [comment]
Unrelated thing:

`maintainPrevious` can also be used with `AsyncValue` to control whether it preserve previous state or not (default is true).
This might be helpful feature to solve some use cases like: https://github.com/rrousselGit/riverpod/issues/2097

It'll be possible to do:
```
state = AsyncValue.error('Dummy error', StackTrace.current, maintainPrevious: false);
```
I can implement it, if you agree.

**Comment by rrousselGit** [comment]
Before that, I'd like to know more about the use-case.

**Comment by AhmedLSayed9** [comment]
Other cases will be the same idea (emitting an AsyncError & overriding prev value at same time).

To clarify what the above use-case is doing: It emits an error state so I can show some error snackbar while also I need to override prev data to be `canSubmit` so user can re-try signing in.

Another scenario is when some remote data fail, you can emit error and override prev data with some cached data, so user can get new cached data while also get notified that an error occurred.

**Comment by AhmedLSayed9** [comment]
I think if it's possible to add the ability to control maintaining prev state by `AsyncValue`, this can be solved without updating `AsyncTransition` to automatically ignore `copyWithPrevious` if it's externally used (what my PR is doing).

So, the default behavior will be always maintain prev state unless it's manually controlled in `AsyncValue`.

In that case, I'll be able to solve my use-case with:
```
state = AsyncError<Availability>(failure, failure.stackTrace, maintainPrevious: false)
            .copyWithPrevious(const AsyncData(Availability.canSubmit));
```
and also the other mentioned issue will be able to do the same to reset prev value.

**Comment by rrousselGit** [comment]
For now, I'll classify the behavior as intended

I'm not sure I want folks to manually call `copyWithPrevious` in `AsyncNotifier`
It's something Riverpod does.

If you want to manually handle the `AsyncValue`, you can use `Notifier<AsyncValue<T>>`
