### ISSUE TITLE
The `AsyncLoading.whenData` does not propagate the value.

### ISSUE THREAD

**Issue by KyoheiG3** [rrousselGit/riverpod#2113]
**Describe the bug**

The `AsyncLoading.whenData` does not propagate the value.

**To Reproduce**

If `AsyncValue` is `AsyncLoading` with a value, it does not propagate the value when `whenData` is called.

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() {
  test('AsyncValue.whenData', () {
    const data = AsyncValue.data(1);

    // In AsyncNotifier, `isRefresh` is often `false`.
    final loading = const AsyncLoading<int>().copyWithPrevious(data, isRefresh: false);
    expect(loading, isA<AsyncLoading<int>>());
    expect(loading.value, 1);

    final whenData = loading.whenData((v) => v);
    expect(whenData, isA<AsyncLoading<int>>());
    expect(whenData.value, 1); // Failed -> Expected: <1> Actual: <null>
  });
}
```

**Expected behavior**

The `AsyncLoading.whenData` method may propagate the value.

**Comment by rrousselGit** [comment]
That is expected for two reasons:
- the `value` can't be passed to the new AsyncValue, as the generic type may not be the same:
  ```dart
  AsyncValue<int> a;
  AsyncValue<String> b = a.whenData<String>(...);
  ```

- One workaround _could_ be to invoke the callback during "loading" to transform the value.
  But that could be very confusing, as `whenData` is used for performing a side-effect only in the "data" case of `when` (hence the name).

If you want to keep a previous value, you could do:

```dart
AsyncValue<int> a;
AsyncValue<int> b = a.whenData(...).copyWithPrevious(b);
```

**Comment by KyoheiG3** [comment]
It seems very difficult to change the generic type while keeping the previous value, for example:

```dart
AsyncValue<int> a;
AsyncValue<String> b = a.whenData(...).copyWithPrevious(a);
```

As long as the name is `when`, it's strange that it's called when it's `loading`. So can't it have something like `mapData`? This can be called in `loading` case.

**Comment by KyoheiG3** [comment]
To keep the previous value, how about for example the following as a workaround?

```dart
AsyncValue<R> mapData<R>(R Function(T value) cb) {
  return maybeMap(
    loading: (loading) {
      final AsyncValue<R>? previous;
      if (loading.hasValue) {
        previous = AsyncData(cb(requireValue));
      } else if (loading.hasError) {
        previous = AsyncError(loading.error!, loading.stackTrace ?? StackTrace.current);
      } else {
        previous = null;
      }

      final newValue = AsyncLoading<R>();
      return previous != null ? newValue.copyWithPrevious(previous, isRefresh: false) : newValue;
    },
    orElse: () => whenData((value) => cb(value)),
  );
}

AsyncValue<int> a;
AsyncValue<String> b = a.mapData<String>(...);
```

**Comment by rrousselGit** [comment]
I already explained why this wouldn't be desired. Cf my second point:

> One workaround could be to invoke the callback during "loading" to transform the value.
But that could be very confusing, as whenData is used for performing a side-effect only in the "data" case of when (hence the name).


People sometimes perform network requests inside `whenData`.
Such a change would be a huge breaking change

**Comment by KyoheiG3** [comment]
The proposed workaround requires keeping the result of `whenData` to run `copyWithPrevious` even if `a` has the previous value.

**Comment by rrousselGit** [comment]
The problem is that to do that, you invoked `cb(value)` again. That's not something reasonable.
