### ISSUE TITLE
StreamProvider.future adds spurious Loading rebuilds

### ISSUE THREAD

**Issue by plammens** [rrousselGit/riverpod#2119]
**Describe the bug**
When using `FutureProvider` and `streamProvider.future` to build a provider that depends on a `StreamProvider` (see #2052), the behaviour is different than when using a bare `Provider` and manually dealing with the `AsyncValue` from the stream provider. Namely, the former approach introduces spurious `AsyncLoading` states between `AsyncData` states. See the reproducible example below for details.

**To Reproduce**

First we define a stream provider we will depend upon. In this example, the stream emits objects of a `Dummy` class, and the dependant provider will extract an `int` property of the object and integer-divide it by 2.
```dart
class Dummy {
  final int x;
  Dummy(this.x);
}

final streamProvider = StreamProvider<Dummy>(
  (ref) => Stream.periodic(const Duration(seconds: 1), (count) => Dummy(count)),
);
```
As a baseline, define the dependent provider as a simple `Provider` that handles the `AsyncValue` from the stream provider manually (by using `.whenData`):
```dart
final dependentProvider = Provider((ref) {
  return ref.watch(streamProvider).whenData((dummy) => dummy.x ~/ 2);
});
```
We can test this by displaying the following widget:
```dart
class TestWidget extends ConsumerWidget {
  const TestWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final asyncValue = ref.watch(dependentProvider);
    print("rebuild, asyncValue = $asyncValue");
    return Text(
      asyncValue.when(
        data: (data) => data.toString(),
        error: (_, __) => "error",
        loading: () => "loading",
      ),
    );
  }
}
```
If we do this, the counter increments every other second.
The console will show one rebuild for every _distinct_ value of `dummy.x`, besides the initial loading state:
```plaintext
flutter: rebuild, asyncValue = AsyncLoading<int>()
flutter: rebuild, asyncValue = AsyncData<int>(value: 0)
flutter: rebuild, asyncValue = AsyncData<int>(value: 1)
flutter: rebuild, asyncValue = AsyncData<int>(value: 2)
...
```

So far so good.

Now, if we replace the definition of `dependantProvider` with what seems to be the more idiomatic approach (see #2052):
```dart
final dependentProvider = FutureProvider((ref) async {
  final dummy = await ref.watch(streamProvider.future);
  return dummy.x ~/ 2;
});
```

And re-test with the same widget above. Now every time the stream emits a new data event the counter briefly changes to the "loading" state. This also means that the counter is rebuilt even though the data won't change, just because of the switch from data to loading and vice-versa. This is confirmed by looking at the console output:

```plaintext
flutter: rebuild, asyncValue = AsyncLoading<int>()
flutter: rebuild, asyncValue = AsyncData<int>(value: 0)
flutter: rebuild, asyncValue = AsyncLoading<int>(value: 0)
flutter: rebuild, asyncValue = AsyncData<int>(value: 0)
flutter: rebuild, asyncValue = AsyncLoading<int>(value: 0)
flutter: rebuild, asyncValue = AsyncData<int>(value: 1)
flutter: rebuild, asyncValue = AsyncLoading<int>(value: 1)
flutter: rebuild, asyncValue = AsyncData<int>(value: 1)
flutter: rebuild, asyncValue = AsyncLoading<int>(value: 1)
flutter: rebuild, asyncValue = AsyncData<int>(value: 2)
flutter: rebuild, asyncValue = AsyncLoading<int>(value: 2)
flutter: rebuild, asyncValue = AsyncData<int>(value: 2)
flutter: rebuild, asyncValue = AsyncLoading<int>(value: 2)
...
```
These rebuilds are spurious and make the UI look ugly because of the intermittent loading.

**Expected behavior**
Both approaches produce the same result (the first of the two explained above).

I don't know whether this is intended, but I expected `streamProvider.future` not to introduce unnecessary `AsyncLoading` states.

**Comment by rrousselGit** [comment]
This is expected, because your provider is async.  
Using async/await never completes synchronously, so there's a frame or two of delay in your provider, which shows up here.

Nothing wrong with that per say.
Your UI can skip those loading states if you with using `AsyncValue.when(skipLoadingOnReload: true, ...)`

You don't see this loading with `Provider` because in that scenario your logic is fully synchronous. There's no await and therefore the value is available immediately.

All in all, everything is expected
