### ISSUE TITLE
A disposed Provider that previously used ref.keepAlive always preserve data/error even if no more listeners

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#2124]
**Describe the bug**
1. An Async Provider (AutoDisposable) watches some dependency and uses ref.keepAlive.
2. The Provider no longer used in the tree.
3. The dependency change.
4. The Provider is disposed due to dependency's change.
5. The Provider's old data/error still there (unexpected).

**To Reproduce**

https://dartpad.dev/?id=fe1c0335656512ada8090a1d0014cdff

Steps:
1. Push to ScreenB and wait for AsyncData
2. Back to ScreenA
3. Press `Sign out user` button
4. Push again to ScreenB (old data still there)

**Comment by rrousselGit** [comment]
Note to self:

This is likely about how keepAliveLink.cancel() doesn't cause autoDispose providers to be destroyed

**Comment by rrousselGit** [comment]
The issue at its root is in fact https://github.com/rrousselGit/riverpod/issues/2729

So closing as duplicate. I'll fix https://github.com/rrousselGit/riverpod/issues/2729 soon
