### ISSUE TITLE
Provider/StateNotifierProvider overrides in SliverList does not update correctly

### ISSUE THREAD

**Issue by keithcwk** [rrousselGit/riverpod#2127]
**Describe the bug**
It is common to use a `Provider`/`StateNotifierProvider` which is unimplemented initially, and as the list builds, the provider is overriden to contain specific values. Then the same provider is listened in the widget for UI purposes, or in more complex implementations, carry out specific logic using `StateNotifierProvider`.

When using either a `Provider`, removing `1` in `list` would result in an incorrect `SliverList` contents being returned. The expected result is that `1` is removed, however, what happens instead is `5` being removed.

![Screenshot 2023-02-03 at 7 24 03 AM](https://user-images.githubusercontent.com/65481917/216473597-e0749b09-7f8e-42dd-8ddb-45900c5f261f.png)

**To Reproduce**
1. Create a page containing `FakeListTest` widget as provided in the snippets below
2. Run `StateNotifierProvider` code snippet in `riverpod 2.0.0-dev.9` and remove the value `1` in `list` and observe the changes
3. Run `Provider` code snippet in `riverpod 2.0.0-dev.9` and remove the value `1` in `list` and observe the changes
4. Repeat 2 but in `riverpod 2.1.3`
5. Repeat 3 but in `riverpod 2.1.3`

**Note**
Do make changes in the `overrideWith` part of the code snippet as per the breaking changes from version 2.0 onwards

<details>
<summary>StateNotifierProvider code snippet</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class FakeState extends StateNotifier<String> {
  final String fakeId;

  FakeState({required this.fakeId}) : super('');
}

final fakeProvider = StateNotifierProvider.autoDispose<FakeModel, FakeState>(
  (_) => throw UnimplementedError(),
);

class FakeModel extends StateNotifier<FakeState> {
  FakeModel(super.state);
}

class FakeListTest extends StatelessWidget {
  const FakeListTest({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final list = ['1', '2', '3', '4', '5'];

    return CustomScrollView(
      slivers: [
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (context, index) {
              return ProviderScope(
                overrides: [
                  fakeProvider.overrideWith(
                    (ref) => FakeModel(
                      FakeState(
                        fakeId: list[index],
                      ),
                    ),
                  ),
                ],
                child: const FakeListCard(),
              );
            },
            childCount: list.length,
          ),
        ),
      ],
    );
  }
}

class FakeListCard extends ConsumerWidget {
  const FakeListCard({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final fakeState = ref.watch(fakeProvider);
    return Text(fakeState.fakeId);
  }
}
```
</details>

<details>
<summary>Provider code snippet</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class FakeState extends StateNotifier<String> {
  final String fakeId;

  FakeState({required this.fakeId}) : super('');
}

final fakeProvider = Provider.autoDispose<FakeState>(
  (_) => throw UnimplementedError(),
);

class FakeListTest extends StatelessWidget {
  const FakeListTest({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final list = ['1', '2', '3', '4', '5'];

    return CustomScrollView(
      slivers: [
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (context, index) {
              return ProviderScope(
                overrides: [
                  fakeProvider.overrideWith(
                    (ref) => FakeState(
                      fakeId: list[index],
                    ),
                  ),
                ],
                child: const FakeListCard(),
              );
            },
            childCount: list.length,
          ),
        ),
      ],
    );
  }
}

class FakeListCard extends ConsumerWidget {
  const FakeListCard({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final fakeState = ref.watch(fakeProvider);
    return Text(fakeState.fakeId);
  }
}

```
</details>

**Expected behavior**
When removing `1` in the list and hot reloading, `1` should be removed instead of `5`

@rrousselGit 
Hope you can spend some time and look into this, do feel free to enlighten me should there be anything I missed or done incorrectly

**Comment by rrousselGit** [comment]
Hello!
This isn't specific to Riverpod. You need to specify the `key` parameter on your list item.
