### ISSUE TITLE
`_$_ProviderNameHash() => r'hash'` changes too often

### ISSUE THREAD

**Issue by dJani97** [rrousselGit/riverpod#2132]
**Describe the bug**

When running `flutter packages pub run build_runner build`, the hash values contained in the `part "something.g.dart"` files' `_$_ProviderNameHash() => r'hash'` functions change too often:

![image](https://user-images.githubusercontent.com/22769564/216639369-20b883e6-af18-4774-8c00-f4800cd39adc.png)

These changes occur even when I didn't modify any of the `@riverpod` definitions.

This is a problem because all of a sudden I see 20+ files changed in the GIT repository, so the actual changes become harder to find. I can decide to commit them, or discard them, but in this case I'm only delaying the problem, and the hash values will change again the next time when `build_runner` is executed.

**To Reproduce**

I didn't find the cause yet. Maybe it happens after `pubspec.yaml` is updated. I'll update this issue if I find something.

**Expected behavior**

I would expect these hash values to be generated once, and either never change, or only change when the related `@riverpod` definition was also updated.

**Comment by rrousselGit** [comment]
Without clear steps, I cannot tell if it is indeed "too often".

It could very well be a logical change which you didn't think of.
In fact there are many cases where it doesn't change but should.

**Comment by rrousselGit** [comment]
To begin with, what's the issue with it changing?

**Comment by rrousselGit** [comment]
You probably shouldn't review generated files. Maybe you don't even have to commit them.
So in that sense, it shouldn't be a big deal

**Comment by rrousselGit** [comment]
Closing as there are not action steps I can take.

As I mentioned, you probably shouldn't review generated files.
