### ISSUE TITLE
Initializing an AsyncNotifier with dependency inversion

### ISSUE THREAD

**Issue by wfleischer** [rrousselGit/riverpod#2139]
Initializing an AsyncNotifier from  a repository provider can be easily done by watching the repository provider within the build method. This however is not desirable, if the AsyncNotifier is at a higher level in the software architecture. For instance, although a business object may logically depend on a repository to be intialized, it should not import and watch a repository provider, which is at an outer/lower level.

To achieve dependency inversion, I am using the pattern of an "incomplete" async notifier, which waits to build until it gets initialized:

```dart
class IncompleteAsyncNotifier<T> extends AsyncNotifier<T> {
  final Completer<T> _completer = Completer();

  @override
  build() => _completer.future;

  void init(T state) {
    if (!_completer.isCompleted) {
      _completer.complete(state);
    }
  }
}
```

Could this be added either as a separate provider class or something like an .incomplete modifier?

Let me know, if I am missing something and this could be achieved with the onboard methods.

**Comment by rrousselGit** [comment]
What you're doing is not what Riverpod tries to achieve.

Riverpod is about making your logic declarative, when you purposefully made it imperative. That's not something I want to do.

**Comment by wfleischer** [comment]
Hm. [Clean Architecture] like several other software architecture patterns for good reason enforce business logic and even application logic to be independent of layers used for data persistence, like database or API access.

Business rules are on a higher level as they are independent of automation. Application logic should not change, for instance, just because the way the data is stored changes to shared preferences, a different database, flat file, API, etc. Mixing these in one layer makes the architecture less flexible and maintainable.

[Clean Architecture]: https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

**Comment by rrousselGit** [comment]
The logic which wants to read the repository is an AsyncNotifier though. It's associated to a provider and therefore should have access to the other providers.

You should most certainly be able to watch the repository provider from within it.

**Comment by wfleischer** [comment]
Thank you. 

The concern is not about accessing a repository provider from within an AsyncNotifier. It is rather about importing a repository provider to an inner level, which makes the latter dependent on the repository. The dependency rule though states that the repository should be able to change without affecting the business logic. (Actually, the business logic should know nothing about the repositories.)

**Comment by rrousselGit** [comment]
Providers already have some dependency inversion mechanism anyway.
You can override providers if you wish to.

So that should be fine naturally?

**Comment by AhmedLSayed9** [comment]
> The concern is not about accessing a repository provider from within an AsyncNotifier. It is rather about importing a repository provider to an inner level, which makes the latter dependent on the repository. The dependency rule though states that the repository should be able to change without affecting the business logic. (Actually, the business logic should know nothing about the repositories.)

I guess you can depend on repo interfaces rather than implementations by using function generator, something like this:
```
@Riverpod(keepAlive: true)
IRepo repo(RepoRef ref) {
  return Repo();
}

class Repo implements IRepo {
...
}
```

**Comment by rrousselGit** [comment]
Closing as there's no actionable steps
