### ISSUE TITLE
Add afterFirstBuild function to Notifier code gen

### ISSUE THREAD

**Issue by todoFixIt** [rrousselGit/riverpod#2141]
**Is your feature request related to a problem? Please describe.**
I want to have some kind of initializer in a Notifier, it should be executed only once.

**Describe the solution you'd like**
Any way to achieve it inside the `Notifier` itself would be fine, for example a function `afterFirstBuild()`

**Additional context**
A use case in which I need this and can't use it or at least I don't know how:

```dart
@riverpod
class Notifier extends _$Notifier {
  @override
  NotifierState build() {
    ref.listenSelf((previous, next) {
      if (previous.foo != next.foo) {
        // Update bar with some logic involving foo
        // As expected this gives an error for trying to read the state before the first build
        // The error: Unhandled Exception: Bad state: Tried to read the state of an uninitialized provider
        state = NotifierState(..., bar: ...)
      }
    });
    return NotifierState();
  }
}

**Comment by rrousselGit** [comment]
If your issue is that your provider is uninitialized, what about initializing it?

```dart
@riverpod
class Notifier extends _$Notifier {
  @override
  NotifierState build() {
    ref.state = NotifierState();
   reflistenSelf(...);
   return ref.state;
  }
```

**Comment by todoFixIt** [comment]
@rrousselGit for whatever reason I didn't think `state` could be initialized manually before the `build()` call, thank you.
