### ISSUE TITLE
Pub example throws 'cancelled' exception when typing in the search bar fast enough

### ISSUE THREAD

**Issue by ppiekars** [rrousselGit/riverpod#2144]
I was playing with your pub example and trying to understand the code.

What seems odd to me is that we use a global cancelToken (at least that's what I understand) and we throw an exception when this cancelToken is cancelled.

This way, if the user writes fast enough and inputs the next character within 250ms the exception is thrown. On the other hand, if the user writes slowly, each new character results in a new request that never gets cancelled.

https://github.com/rrousselGit/riverpod/blob/309150b69a8193f04b20f2191224505b1dcbbf81/examples/pub/lib/search.dart#L37

**Comment by rrousselGit** [comment]
That's fine. This is expected

The error should be considered caught and not show up – although the IDE might pause on it.

**Comment by ppiekars** [comment]
You're right, when not run in debug mode it works fine. Thanks for clarification!
