### ISSUE TITLE
select and ref.listen did not listen to changes as expected

### ISSUE THREAD

**Issue by lizhuoyuan** [rrousselGit/riverpod#2147]
I have a User with two attributes of name and id. When the id is modified, it cannot be monitored
I expect to be able to listen for changes normally
Below is my code:
```
class User {
  String? name;
  String? id;

  ...

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          id == other.id;

  @override
  int get hashCode => name.hashCode ^ id.hashCode;
}
```
```
    ref.listenManual<String?>(userProvider.select((value) => value.id),
        (previous, next) {
      debugPrint('user listen');
      if (previous != next) {
        debugPrint('user change');
      }
    });
```

i use this function to change id
```
             if (ref.watch(userProvider).id == '123') {
               ref.watch(userProvider).id = '124';
            } else {
              ref.watch(userProvider).id = '123';
             }
```

To avoid the provider not recognizing the user's changes, I rewrote ==, but still can not listen to the changes

**Comment by lizhuoyuan** [comment]
```
class UserNotifier extends StateNotifier<User> {
  UserNotifier() : super(User());

  Future<void> refresh() async {
    state = await Api.fetchUser() ?? User();
  }

  void setUser(User user) {
    state = user;
  }

  void changeId(String id){
    state.id = id;
  }
}
```
Should I use setUser instead of changeId?
Let the state point to the new reference without modifying the property directly?

**Comment by rrousselGit** [comment]
You cannot simply mutate the object. You need to invoke `state=` somehow.

Hence why the `state` is supposed to be immutable. So doing `ref.watch(userProvider).id = '124';` is not enough to notify listeners.

You need to clone your `User` class with a different ID
