### ISSUE TITLE
Generic families

### ISSUE THREAD

**Issue by Zekfad** [rrousselGit/riverpod#2150]
**Is your feature request related to a problem? Please describe.**
It would be neat to add support of generics to families via generic provider executor.

**Describe the solution you'd like**
API like:
```dart
final provider = FutureProvider.autoDispose.family.generic<Res, Arg, TBase>(<T extends TBase>(Ref ref, Arg arg) { /*...*/ })
```

**Describe alternatives you've considered**
Don't see any other good solutions.

**Additional context**
Here's some code that I come up trying to figure out if it's even possible with dart type system:

<details>
<summary>Details</summary>

```dart
typedef FN<Res, Arg, T> = Res Function<_T extends T>(Arg argument);
class Sample {
  FN<Res, Arg, T> call<Res, Arg, T>(FN<Res, Arg, T> fn) => fn;
}

class Person {
  Person(this.id);
  final int id;
  int get typeId => 1;
}
class Author extends Person {
  Author(super.id);
  @override int get typeId => 2;
}
class Reader extends Person {
  Reader(super.id);
  @override int get typeId => 3;
}

T getPerson<T extends Person>(int id) {
  if (T == Author) return Author(id) as T;
  if (T == Reader) return Reader(id) as T;
  throw 'Not found';
}

void main() {
  final s = Sample();
  final _getPerson = s<Person, int, Person>(<T extends Person>(int id) => getPerson<T>(id));
  
  final person = _getPerson<Author>(1) as Author;
  print(person.id);
  print(person.typeId);
}
```

</details>

**Comment by rrousselGit** [comment]
If we want generic providers, it'd most definitely be code-gen only.

The syntax proposed would be really not ideal. As opposed to a plain:

```dart
@riverpod
Future<Res> provider<T extends TBase>(ProviderRef ref, Arg arg) {

}
```

**Comment by Zekfad** [comment]
I've used Riverpod without code-gen, so for me it would be nice to have it in plain Riverpod, but code-gen is fine as well, it it will be possible at all.

**Comment by rrousselGit** [comment]
Flagging as breaking as it'd require removing the type arg from `Family<T>` and removing the various "override" methods from the interface (as they depend on the generics)

This is due to the fact that if we write:

```dart
@riverpod
T example<T>(ExampleRef ref) => ...;
```

then there is no way to generate a valid output as we can't do:

```dart
class ExampleFamily extends Family<T> {
  ExampleProvider<T> call<T>() => ...;
}
```

**Comment by smiLLe** [comment]
@rrousselGit 
So generic families will only be available in riverpod 3.0?

**Comment by rrousselGit** [comment]
Yes. They require a breaking change for it to work.

**Comment by rrousselGit** [comment]
This has been implemented some times ago. A dev release will be made at some point.
