### ISSUE TITLE
[riverpod_graph] Supports outputs other than Mermaid.js

### ISSUE THREAD

**Issue by utamori** [rrousselGit/riverpod#2159]
**Is your feature request related to a problem? Please describe.**

riverpod_graph is very useful ! 

However, when many relationships, the lines can become intricate and the diagram difficult to understand.
This seems to be a problem with the dagre layout engine used by mermaid.js.

- https://github.com/dagrejs/dagre/issues/256
- https://github.com/mermaid-js/mermaid/issues/1969

**Describe the solution you'd like**
- support other diagram tool format output
- I personally think [D2](https://github.com/terrastruct/d2) is better, the syntax is almost identical to mermaid.

https://d2lang.com/tour/intro/

**Describe alternatives you've considered**

- https://github.com/eclipse-sprotty/sprotty also support elk
- https://plantuml.com/en/elk  PlantUML is so popular

**Additional context**

Creating the images in this repository with D2 would result in the following

https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_graph

![devtool_graph](https://user-images.githubusercontent.com/59682979/218271096-e512a384-00ba-4537-9c7f-0cd51a02497c.png)

```
ProviderNodeItem.shape: circle
_StateInspectorSettingsDialog.shape: circle
ProviderScreenBody.shape: circle

_hasErrorProvider -> ProviderScreenBody
_showInternals -> _StateInspectorSettingsDialog: {style.stroke-width: 5}
_showInternals -> _StateInspectorSettingsDialog: {style.stroke-dash: 3}
_showInternals -> _StateInspectorSettingsDialog: {style.stroke-dash: 3}
_showInternals -> ProviderScreenBody: {style.stroke-width: 5}
_selectedProviderNode -> ProviderScreenBody: {style.stroke-width: 5}
selectedProviderIdProvider -> ProviderNodeItem: {style.stroke-width: 5}
selectedProviderIdProvider -> ProviderNodeItem: {style.stroke-dash: 3}
selectedProviderIdProvider -> ProviderScreenBody: {style.stroke-width: 5}
selectedProviderIdProvider -> _selectedProviderNode: {style.stroke-width: 5}
selectedProviderIdProvider -> _hasErrorProvider: {style.stroke-width: 5}
sortedProviderNodesProvider -> selectedProviderIdProvider
sortedProviderNodesProvider -> _selectedProviderNode: {style.stroke-width: 5}
sortedProviderNodesProvider -> _hasErrorProvider: {style.stroke-width: 5}
_rawProviderIdsProvider -> sortedProviderNodesProvider: {style.stroke-width: 5}
_providerListChanged -> _rawProviderIdsProvider: {style.stroke-width: 5}
hotRestartEventProvider -> _rawProviderIdsProvider: {style.stroke-width: 5}
hotRestartEventProvider -> instanceProvider: {style.stroke-width: 5}
hotRestartEventProvider -> _rawProviderNodeProvider: {style.stroke-width: 5}
ProviderEvalProvider -> _rawProviderNodeProvider: {style.stroke-width: 5}
ProviderEvalProvider -> _rawProviderIdsProvider: {style.stroke-width: 5}
serviceProvider -> _providerChanged: {style.stroke-width: 5}
serviceProvider -> _providerListChanged: {style.stroke-width: 5}
serviceProvider -> libaryEvalProvider: {style.stroke-width: 5}
libaryEvalProvider -> instanceProvider: {style.stroke-width: 5}
instanceProvider -> instanceProvider: {style.stroke-width: 5}
evalProvider -> instanceProvider: {style.stroke-width: 5}
instanceProvider -> estimatedChildCountProvider: {style.stroke-width: 5}
isExpandedProvider -> estimatedChildCountProvider: {style.stroke-width: 5}
instanceProvider -> _hasErrorProvider: {style.stroke-width: 5}

```

**Comment by rrousselGit** [comment]
That's certainly more organized

I don't really care about what underlining syntax is used. If an alternate package renders more readable graphs, let's use that


Fancy doing the update?

**Comment by utamori** [comment]
Yes. I would be happy to submit a pull request for the feature.
