### ISSUE TITLE
Using private vars to cheat the final requirement

### ISSUE THREAD

**Issue by dgaedcke** [rrousselGit/riverpod#216]
Rather than importing standalone vars with provider names I don't remember, is it ok to use this trick I was previously using with GetIt?

```
// created outside of provider to keep alive
// for duration of the app
// only accessible through _authBlocProvider
AuthFlowBloc _globalAuthFlowBloc;
// not final but private;  avail from static getter below
Provider<AuthFlowBloc> _authBlocProvider;

class SlhState {
  // source of all events
  static Provider<AuthFlowBloc> get authBlocProv => _authBlocProvider;

  static void createGlobalProviders() {
    // creating _globalAuthFlowBloc outside to force state retention
    _globalAuthFlowBloc = AuthFlowBloc(AuthFlowState.initial);
    _authBlocProvider = Provider<AuthFlowBloc>((ref) {
      return _globalAuthFlowBloc;
    });
  }
}
```

**Comment by rrousselGit** [comment]
I don't understand. What is the benefit? Why not create the instance directly in your provider?

**Comment by dgaedcke** [comment]
Thanks for the response Remi!!
There are two points here:
1.  I was referring to the ABSENCE of "final" in front of:   AuthFlowBloc _globalAuthFlowBloc;   will that break anything with Riverpod?
2.  Docs issue .... I'm unclear **if and when** the provider will dispose of my object ... how long will this object exist WITHOUT a listener BEFORE Provider disposes of it??   By creating it outside, I was imagining (probably delusion-ally) that I could prevent the provider from disposing of it  (I need it to be immortal)

**Comment by dgaedcke** [comment]
Another area in which the docs are a bit contradictory

About "Provider", you say:

"Provider is the most basic of all providers. It exposes an object that **never changes**."

And then below this example using Provider, you say:
`final cityProvider = Provider((ref) => 'London');`
"One interesting aspect of this code is, **if city ever changes**, this will automatically call fetchWeather again and update the UI accordingly."

I would assume that City can change ... for clarity, you may want to use another type on that "London" example ...

**Comment by dgaedcke** [comment]
Another docs issue:
Doc text say NOT to "read()" a provider within another provider.
But this diagram contradicts that rule.

![image](https://user-images.githubusercontent.com/1172930/100285072-d6e47280-2f35-11eb-8cbf-63c1e19ee73b.png)

**Comment by dgaedcke** [comment]
I'm also confused by this image ... if I'm NOT inside a build method, from where do I get the context??  Yes, I could use a stateful Widget, but a major advantage of Riverpod is not having to do that ...
![image](https://user-images.githubusercontent.com/1172930/100644210-a66b5280-3300-11eb-9084-12159c1bf65f.png)

**Comment by dgaedcke** [comment]
If you give me clear explanation of the points above, I'd be happy to update the docs and send you a PR!!

**Comment by rrousselGit** [comment]
There is a lint covering this from what I remember, and it is litteraly not possible to define a provider as a property of an object with codegen.

So closing :)
