### ISSUE TITLE
Allow Custom Async value

### ISSUE THREAD

**Issue by HoussemBousmaha** [rrousselGit/riverpod#2166]
Hi! i think the new riverpod syntax is absolutely genius! i really love it.

My request is very simple! it is related to the AsyncNotifier/AutoDisposeAsyncNotifier class & Async Initialization.

Can you allow Custom Async Values!

For instance in my build function i want to have 4 states: initial,loading,loaded and error and at the same time i want to initialize the my state asyncronisally.

or if for instance in the regular async value error state, i want to have my previous state and not alter the current state, just show some snackbar.

**Comment by rrousselGit** [comment]
If you want custom async values, use Notifier. You can set whatever you want there.

I do not plan to enable AsyncNotifier to use something other than AsyncValue.

AsyncValue is likely going to be migrated to a sealed class when dart 3 lands. You wouldn't be able to subclass AsyncValue anymore.
