### ISSUE TITLE
riverpod_lint doesnt work

### ISSUE THREAD

**Issue by AdalWay** [rrousselGit/riverpod#2180]
**Describe the bug**
I just installed the riverpod_lint but int doesnt work
**To Reproduce**
Installed the riverpod_lint and custom_lint an try to run it manuallly dart run custom_lint
<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>
dart run custom_lint
Building package executable... (6.6s)
Built custom_lint:custom_lint.
Failed to start plugins
The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Bad state: Failed to start the plugins.
at:
#0      _SocketCustomLintServerToClientChannel._checkInitializationFail.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:332:11)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#3      Future.any.onValue (dart:async/future.dart:612:5)
<asynchronous suspension>

**Expected behavior**

**Comment by rrousselGit** [comment]
Could you share the complete log file, and possibly a github repository to reproduce the problem?

**Comment by AdalWay** [comment]
Here is the log file
[custom_lint.log](https://github.com/rrousselGit/riverpod/files/10751891/custom_lint.log)

**Comment by rrousselGit** [comment]
The log file is sadly unhelpful.
Could your share a git repository to reproduce the problem?

**Comment by AdalWay** [comment]
here is the link to the repo, https://github.com/AdalWay/test_riverpod_lint. 
Thanks you

**Comment by AdalWay** [comment]
I forgot to tell you I'm using a Ubuntu 22.04.1 LTS

**Comment by rrousselGit** [comment]
I cloned your project and everything is working for me. 

Could you try again after running after upgrading your Dart/Flutter SDK and running `dart pub upgrade`?

**Comment by garysm** [comment]
I've seen several people and myself encounter this exact issue, all running on Ubuntu. I also followed the steps you outlined above. Could be Linux-specific? I've yet to test on another device.

**Comment by austinried** [comment]
Same issue and error here, I'm just trying out `riverpod_lint` for the first time though and couldn't say if it's ever worked in the past but I'm on Linux as well.

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 22.04.2 LTS 5.19.0-35-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

Looks to be related to the issue with custom lint: https://github.com/invertase/dart_custom_lint/issues/115

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/invertase/dart_custom_lint/issues/115
