### ISSUE TITLE
Add the way to cache the previous provider's data on FutureProvider

### ISSUE THREAD

**Issue by ykaito21** [rrousselGit/riverpod#2185]
I'm trying to build infinite scroll pagination ui with FutureProvider. I checked [the official pub client example](https://github.com/rrousselGit/riverpod/tree/master/examples/pub) and it shows how can I make. But the problem is if the user scroll back to the top, it refetch the previous data again.

I understand FutureProvider is not for holding the data, and I can build with StateNotifier like this [example](https://github.com/tbm98/flutter_loadmore_search/blob/master/lib/post_provider.dart). 

It would be nice if we could use FutureProvider like [React-Query's infinite queries style](https://tanstack.com/query/v4/docs/react/guides/infinite-queries ).

**Comment by rrousselGit** [comment]
This behaviour is because the provider doesn't set a "cacheTime" in RQ terms.

There are ways to set a cacheTime in Riverpod, using ref.keepAlive + a timer. 

I'll close this in favour of https://github.com/rrousselGit/riverpod/issues/1664

**Comment by ykaito21** [comment]
I found `ref.keepAlive()` and it works well without StateNotifier.

**Comment by ykaito21** [comment]
> This behaviour is because the provider doesn't set a "cacheTime" in RQ terms.
> 
> There are ways to set a cacheTime in Riverpod, using ref.keepAlive + a timer.
> 
> I'll close this in favour of #1664

I got it. Thanks
