### ISSUE TITLE
Lint proposal: Avoid passing BuildContext to providers

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2187]
```dart
@riverpod
int fn(FnRef ref, BuildContext context) {} // KO

@riverpod
class MyNotifier extends _$MyNotifier {
  int build() => 0;

  void event(BuildContext context) {} // KO
}
```

**Comment by dhruv1710** [comment]
I can work on it. I am working on my first contribution

**Comment by dhruv1710** [comment]
I should create a new file in riverpod_lint/lib/src/lints and create a DartLintRule right?

**Comment by rrousselGit** [comment]
Yes

**Comment by dhruv1710** [comment]
I have made a PR and there is a problem. The flutter format command is deprecated can you pls check.

**Comment by rrousselGit** [comment]
You can either change the CI to use `dart format` or ignore the error for now.

**Comment by jeiea** [comment]
I didn't know I should not do that. Is there any resources, discussion or discord message about this?

**Comment by dhruv1710** [comment]
There are no docs except pub.dev page on custom_lint. You need to find everything yourself.

**Comment by rrousselGit** [comment]
This was implemented in a previous PR
