### ISSUE TITLE
Is the overridden provider not disposed?

### ISSUE THREAD

**Issue by ykaito21** [rrousselGit/riverpod#2198]
i'm trying to wrap the each item of the ListView with ProviderScope and override provider for that. 

The problem is that when using an override provider, it is not possible to check whether the override provider has been instantiated and disposed.

**If I scrolled to the bottom of the list and then back to the top,
this is the result without using override and it is expected.**
```
flutter: initState TestTile
flutter: init indexProvider
flutter: addListener indexProvider
flutter: dispose TestTile
flutter: removeListener indexProvider
flutter: dispose indexProvider
flutter: initState TestTile
flutter: init indexProvider
flutter: addListener indexProvider
```

**but this is the result with override.** 
```
flutter: initState TestTile
flutter: dispose TestTile
flutter: initState TestTile
```

**Code:**
```dart
@riverpod
int index(IndexRef ref) {
  print('init indexProvider');
  ref.onAddListener(() {
    print('addListener indexProvider');
  });
  ref.onRemoveListener(() {
    print('removeListener indexProvider');
  });
  ref.onDispose(() {
    print('dispose indexProvider');
  });
  return 0;
}

class TestList extends ConsumerWidget {
  const TestList({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ListView.builder(
        itemCount: 100,
        itemBuilder: (BuildContext ctxt, int index) {
          if (index == 0) {
            return ProviderScope(
              overrides: [
                indexProvider.overrideWithValue(index),
              ],
              child: const TestTile(),
            );
          }
          return TestTileWithIndex(index: index);
        });
  }
}

class TestTile extends ConsumerStatefulWidget {
  const TestTile({super.key});

  @override
  ConsumerState<TestTile> createState() => _TestTileState();
}

class _TestTileState extends ConsumerState<TestTile> {
  @override
  void initState() {
    print('initState TestTile');
    super.initState();
  }

  @override
  void dispose() {
    print('dispose TestTile');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final index = ref.watch(indexProvider);
    return ListTile(
        leading: DecoratedBox(
          decoration: const BoxDecoration(
            color: Colors.indigo,
            //border:StadiumBorder(),
            borderRadius: BorderRadius.all(Radius.circular(16)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(index.toString(),
                style: Theme.of(context)
                    .textTheme
                    .titleMedium!
                    .copyWith(color: Colors.white)),
          ),
        ),
        title: Text(index.toString(),
            style: Theme.of(context).textTheme.titleMedium),
        onTap: () {});
  }
}

class TestTileWithIndex extends StatelessWidget {
  final int index;
  const TestTileWithIndex({super.key, required this.index});

  @override
  Widget build(BuildContext context) {
    return ListTile(
        leading: DecoratedBox(
          decoration: const BoxDecoration(
            color: Colors.indigo,
            //border:StadiumBorder(),
            borderRadius: BorderRadius.all(Radius.circular(16)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(index.toString(),
                style: Theme.of(context)
                    .textTheme
                    .titleMedium!
                    .copyWith(color: Colors.white)),
          ),
        ),
        title: Text(index.toString(),
            style: Theme.of(context).textTheme.titleMedium),
        onTap: () {});
  }
}
```

**The main question is whether this is the expected behavior or whether the overridden provider is actually disposed?** 

I also have a few related questions.
**1.** Is there any way to know when a provider has been overridden and disposed?
**2.** Does this override use one provider or does it create many providers corresponding to each list item?
**3.** If there is a corresponding provider for each item, will there be a negative impact on performance or a positive impact due to using `const` with the item?
**4.** Can I make the overridden provider in this case, `indexProvider`, keepalive? Would it also affect performance?
**5.** If the code with [you](https://github.com/rrousselGit/riverpod/discussions/2017#discussioncomment-4466753) or [Code with Andrea](https://codewithandrea.com/articles/flutter-state-management-riverpod/), in the example, said the scoping with in the ListView is fine, Is this still the recommended way or is there a better way?
 if I make overriden provider with keepalive, does it also affecct performance? shoudn't it? 

Thank you for your tremendous effort and this wonderful package!

**Comment by rrousselGit** [comment]
When you override a provider, the original function of a provider is no-longer used. The new behavior completely takes over.  
As such it is logical that you don't see your prints


If you want to do such a thing, your logic has to be placed inside the override.
You can do:

```dart
ProviderScope(
  overrides: [
    provider.overrideWith((ref) {
      print('init');
       ref.onDispose(() => print('dispose');
    }),
  ],
  child: ...,
)
```

> Does this override use one provider or does it create many providers corresponding to each list item?

One per item

>  If there is a corresponding provider for each item, will there be a negative impact on performance or a positive impact due to using const with the item?

It depends. Do a benchmark for your individual cases :) 

> . Can I make the overridden provider in this case, indexProvider, keepalive? Would it also affect performance?

That's fine. It'll get disposed when the ProviderScope is unmounted


> If the code with https://github.com/rrousselGit/riverpod/discussions/2017#discussioncomment-4466753 or [Code with Andrea](https://codewithandrea.com/articles/flutter-state-management-riverpod/), in the example, said the scoping with in the ListView is fine, Is this still the recommended way or is there a better way?

I do not recommend scoping. It's fine as a way to reduce widget rebuild, but is fairly advanced.
For beginners, stick to passing the index by hand.
