### ISSUE TITLE
update provider listenable only `on` certain conditions

### ISSUE THREAD

**Issue by bar360now** [rrousselGit/riverpod#2199]
**Related Problem**
I have a provider that provides the current logged in user, when a user logged out, it providers `null`. In other parts of the app I have `FutureProvider`s that makes requests based on the logged in user, when the user is logged out, I don't want them to update their value. 

**Describe the solution you'd like**
In essence, I want a way for providers that depends on other providers to update only on certain conditions.
I've thought of adding a new method, `on(bool Function(prevValue, value))` that when called on a provider, returns a new one that only updates itself when the function returns `true`.

example:
```dart
final userProvider = StateProvider<User?>((ref) {
  // ...
});

final authenticatedRequestProvider = FutureProvider((ref) {
    var user = ref.watch(userProvider.on((prevValue, value) => value != false));
    // ...
})

final complexProvider = Provider((ref) {
    var user = ref.watch(userProvider.on((prevValue, value) => value.name != prevValue.name));
    // ...
})
```

**Describe alternatives you've considered**
An alternative is using `select` with a class implementing equality, or using `StateProvider` or `StreamProvider` and managing the dependency logic manually. 

**Additional context**
The proposed solution also relates with #2081  and #2035, and offer a new solution from a different perspective.

**Comment by rrousselGit** [comment]
A ref.watch expression that receives the previous+new value at the same time doesn't make sense.  
When using watch, only the current value is available as the previous value isn't kept in memory.

That would mean on first execution, the `on` check wouldn't be executed, rendering something like `(prev, value) => value != false)` flawed as there's no guarantee `value` won't be `false` on the first execution.

Also I want to avoid introducing something reliant on an == check.
== checks are very error-prone.


____


For the problem you described, there are alternative solutions. If you want a provider to do a network request only if the user is logged in, you can do:

```dart
final provider = FutureProvider((ref) async {
  final user = ref.watch(authrpovideer);
  // If not logged in, wait until the user is logged in.
  if (user == null) return ref.future;

  // Code here can safely depend on the user being logged in.
  return fetchSomething();
});
```

**Comment by rrousselGit** [comment]
I have no plan to add such a feature for now. So closing
