### ISSUE TITLE
NotifierBase.state setter should be @protected

### ISSUE THREAD

**Issue by cc-nogueira** [rrousselGit/riverpod#2204]
AsyncNotifierBase and StateNotifier have protected state setters.
But NotifierBase has it public.

``` dart
  // While AsyncNotifierBase has:
  @protected
  set state(AsyncValue<State> newState) {
    // ...
  }

  // NotifierBase has:
  set state(State value) {
     // ...
  }
```

Expected all Notifiers to protect state setter.

**Comment by rrousselGit** [comment]
This has been fixed recently in 333cd8c9be36e105e9e5673ef0a97cbcfd59c955, and has yet to be published
