### ISSUE TITLE
Warn against AsyncNotifier.update misuses

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2205]
```dart
class Example extends AsyncNotifier<int> {
 ...

  void fn() {
    state = AsyncLoading(); // KO, "update" will likely never complete
    update((data) => ...);
  }

  void fn() {
    update((data) {
      state = AsyncLoading(); // OK
       ...
    });
  }


  void fn() {
    update((unused) => ...); // the parameter should be used. Otherwise use AsyncValue.guard
  }

}
```

**Comment by yknevenky** [comment]
@rrousselGit 

I am trying to update the state of a FamilyAsyncNotifier partially, I just want to know whether I am doing it right. Also in this case of updating a asyncvalue partially, I want to know what's differences in using whenData, AsyncGuard.value and update method . It would be a immense help, if you provide some clarity on this.



update((state) async {
      List<Student> students =
          await ref.read(collegeProvider).getCollegeById(id: this.arg);
      return state.copyWith(students: students);
});

**Comment by rrousselGit** [comment]
With mutations, this is really low-priority. Closing
