### ISSUE TITLE
riverpod_lint throws when a non-existent family provider is ref.anything'd

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#2206]
**Describe the bug**
When riverpod_lint is used with a family provider (and it is family-specific) and the family is misspelled somewhere, the linter throws

**To Reproduce**
demo.dart
```dart
final xProvider = Provider.autoDispose((ref) {
  ref.watch(nonexistant()); // <<< throws if a parameter list is provided i guess?
});
```

spell it correctly, press backspace once or add an extra character and see it instantly throw

the log file for this specific bug: [custom_lint.log](https://github.com/rrousselGit/riverpod/files/10788483/custom_lint.log)
(i deleted the file, triggered the exception, and uploaded the file it created)

**Expected behavior**
It shouldn't throw. Not sure what is supposed to be happening here besides that.

**Comment by rrousselGit** [comment]
This was fixed by fixing another issue

Thanks for the report though!
