### ISSUE TITLE
riverpod_lint throws when an already generated class/function provider is being renamed

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#2207]
**Describe the bug**
riverpod_lint throws when an already generated class/function provider is being renamed and the generator is not yet re-run.

**To Reproduce**
demo.dart
```dart
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'demo.g.dart';

@riverpod
void function(FunctionRef ref) {}

@riverpod
class ClassP extends _$ClassP {
  @override
  build() {}
}

final failure = Provider.autoDispose((ref) {
  ref.watch(classPProvider);
  ref.watch(functionProvider);
});
```
1. create this file
2. run the generator to completion,
3. alter the name of either or both the class or function (without running build_runner) to see the linter throw

log (altered both class and function so its in there twice): [custom_lint.log](https://github.com/rrousselGit/riverpod/files/10788543/custom_lint.log)

**Expected behavior**
ideally, linters don't throw

**Comment by TekExplorer** [comment]
this is distinct from #2206 because in this case, the actual provider does exist, but the source notifier or function does not.

**Comment by TekExplorer** [comment]
simply: it throws when the source notifier or function does not exist (ex. when being renamed without using a refactor)

**Comment by rrousselGit** [comment]
Got it. Thanks a ton for tracing back what the problem was.

It helped a lot!
