### ISSUE TITLE
riverpod_generator: file ".g" is not generated when @riverpod annotations are in a part file

### ISSUE THREAD

**Issue by julienlebren** [rrousselGit/riverpod#2225]
I can't get my ".g" files generated when the @riverpod annotations are in part files.
No error in the build output, it's like riverpod_generator does not detect that there are some @riverpod stuff to build.

Example (voluntary reduced in code)

❌ Case 1: this code never generates `layout_builder.g.dart`:

**File layout_builder.dart**
```dart
library layout_builder;

import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'theme/theme_providers.dart';

part 'layout_builder.g.dart';
```
**File theme/theme_providers.dart**
```dart
part of layout_builder;

@Riverpod(keepAlive: true)
AppTheme appTheme(AppThemeRef ref) => throw UnimplementedError();
```

✅ Case 2: this code generates `layout_builder.g.dart`:

**File layout_builder.dart**
```dart
library layout_builder;

import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'layout_builder.g.dart';

@Riverpod(keepAlive: true)
AppTheme appTheme(AppThemeRef ref) => throw UnimplementedError();
```

**Comment by rrousselGit** [comment]
This is fixed already but not released yet
