### ISSUE TITLE
Add StreamProvider to riverpod_generator

### ISSUE THREAD

**Issue by julienlebren** [rrousselGit/riverpod#2231]
Everything is in the title, do you plan to add StreamProvider to riverpod_generator?

I just explain why this is a blocking feature to me:
Yes, we can still define a StreamProvider with the "old" method, but when you have providers depending on providers depending on providers... all the providers need to be created with @riverpod annotation to be in the dependencies parameter.
And since a StreamProvider cannot be created with @riverpod annotation, then none of the providers depending on it can be created with @riverpod annotation.

**Comment by AhmedLSayed9** [comment]
WIP https://github.com/rrousselGit/riverpod/pull/2229

**Comment by julienlebren** [comment]
Damn, however I searched before post it. Thanks.
