### ISSUE TITLE
StateProvider not rebulding checkbox

### ISSUE THREAD

**Issue by dhruv1710** [rrousselGit/riverpod#2232]
**Describe the bug**
This code below updates the checkbox when clicked but checkbox is only updating when hot reload happens. The state is getting changed but UI stays the same

**To Reproduce**

import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:rallyrun/models/ModelProvider.dart';

final playerSelector = StateProvider((ref) => {'Dhruv': true});

class CreateTournament extends ConsumerWidget {
  CreateTournament({super.key});
  TextEditingController _name = TextEditingController();
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final players = ref.watch(playerSelector);
    return Scaffold(
        body: Column(
      children: [
        TextField(
          controller: _name,
        ),
        Expanded(
            child: ListView(children: [
          CheckboxListTile(
              title: Text('Dhruv'),
              value: players['Dhruv'],
              onChanged: (val) {
                print(val!);
                ref.read(playerSelector.notifier).update((state) {
                  state['Dhruv'] = val!;
                  return state;
                });
              }),
        ])),
        ElevatedButton(
          child: Text('Submit'),
          onPressed: () async {
            final newTournament = Tournament(name: _name.text, logo: '(/)');
            players.forEach((key, value) async {
              var player = await Amplify.DataStore.query(Player.classType,
                  where: Player.NAME.eq(key));
              var PlayTour = PlayerTournament(
                  player: player[0], tournament: newTournament);
              await Amplify.DataStore.save(PlayTour);
            });
            await Amplify.DataStore.save(newTournament);
          },
        )
      ],
    ));
  }
}

**Expected behavior**
Checkbox needs to be unticked

**Comment by AhmedLSayed9** [comment]
You need to format your code by adding \```dart  before and \``` after your code.

Your issue is that you're mutating your state, instead you need to emit a new state so that the listeners get notified:
```
ref.read(playerSelector.notifier).update((state) {
return {'Dhruv': val};
});
```

**Comment by dhruv1710** [comment]
Can I make a copy of state, change it then emit because this Map is supposed to be dynamic with many more people

**Comment by rrousselGit** [comment]
You can do `return {...state, 'Dhruv': val}`
