### ISSUE TITLE
Variant of AsyncValue.whenData that preserves other attributes (AsyncValue.mapValue)

### ISSUE THREAD

**Issue by derolf** [rrousselGit/riverpod#2233]
**Is your feature request related to a problem? Please describe.**

I am using whenData to massage the value of an AsyncValue. But if the AsyncValue is in error or loading state, the data is not mapped. So refreshing/reloading doesn't propagate.

**Describe the solution you'd like**

Create a variant that allows to map the value for all possible states.

**Comment by rrousselGit** [comment]
The previous data cannot be mapped as the new AsyncValue generic can be incompatible with the input data

**Comment by derolf** [comment]
If T is input and R is output, the result would be AsyncData<R>, AsyncError<R>, or AsyncLoading<R>. Basically, the private constructors are already capable of getting the transformed (T->R) value.

**Comment by rrousselGit** [comment]
No because `T data` is not compatible with `R data`

**Comment by derolf** [comment]
Sure, but you just send data through the mapper in EVERY case.

**Comment by derolf** [comment]
```
extension AsyncValueX<T> on AsyncValue<T> {
  AsyncValue<R> mapValue<R>(R Function(T value) f) {
    final value = hasValue ? f(requireValue) : null;
    return map(
        data: (v) => AsyncData._(..., value: value),
        error: (v) => AsyncError._(..., value: value),
        loading: (v) => AsyncLoading._(..., value: value),
      );
  }
}
```

**Comment by rrousselGit** [comment]
That doesn't work. T is not assignable to R

**Comment by derolf** [comment]
Which line actually doesn't work?

**Comment by rrousselGit** [comment]
This would invoke `f` during loading/error state. This is undesired. See https://github.com/rrousselGit/riverpod/issues/2233#issuecomment-1448111504

**Comment by derolf** [comment]
Yes, this is why it's NOT called whenData, but mapValue.

**Comment by rrousselGit** [comment]
But you're asking for changes on whenData

**Comment by derolf** [comment]
If you want to propagate a refreshable/reloadable AsyncValue down the widget tree, but need to transform the value, then you need something like this.

**Comment by derolf** [comment]
> But you're asking for changes on whenData

Sorry, title modified :-)

**Comment by rrousselGit** [comment]
I see I got confused. I thought you effectively asked for a breaking change on whenData.

When/why do you need this then? I've never had the need for this.

**Comment by derolf** [comment]
> *Describe the solution you'd like*
>Create a variant that allows to map the value for all possible states.

I am getting a list of movies from a provider. But my widget wants only movies that are PG13 rated, so I need to filter them. But I want to preserve error and loading states.

**Comment by rrousselGit** [comment]
Why does this need such utility?
You should be able to do:

```dart
final allMoviesProvider = FutureProvider(...)

final pg13MoviesProvideer = FutureProvider<LIst<Movie>>((ref )async {
  final allMovies = await ref.watch(allMoviesProvider.future);
  return allMovies.where((e) => e.ispg13).toList();
});
```

Alternatively, you should expose an extension on `List<Movie>` to filter things in the UI

**Comment by derolf** [comment]
I tried to avoid chaining `FutureProvider`s since invalidating doesn't propagate through them (another interesting topic btw).

**Comment by rrousselGit** [comment]
> I tried to avoid chaining `FutureProvider`s since invalidating doesn't propagate through them (another interesting topic btw).

What do you mean? It should work.

**Comment by rrousselGit** [comment]
For now I'd suggest using an extension. I don't plan on implementing such feature
