### ISSUE TITLE
The examples in the Changelog for riverpod_generator 2.0.0 may be incorrect.

### ISSUE THREAD

**Issue by K9i-0** [rrousselGit/riverpod#2235]
https://pub.dev/packages/riverpod_generator/changelog#200

When I tried the below code, code generation failed.
```
@riverpod
int count();
```

I received the following message.
```
This builder requires Dart inputs without syntax errors.
However, package:flutter_k9i_portfolio/features/settings/settings.dart (or an existing part) contains the following errors.
settings.dart:32:12: A function body must be provided.
```

By following the example in this file and adding the external keyword, I was able to generate the code successfully.

https://github.com/rrousselGit/riverpod/blob/720d43c8af6cd852272f846ef6fabdd4a23c8075/packages/riverpod_generator/test/integration/scopes.dart#L1-L6

In addition, I received a lint warning when I did not include Ref as an argument.

Considering these factors, I was able to successfully generate the code by writing it in the following way.

```
@riverpod
external int count(CountRef ref);
```

**Comment by rrousselGit** [comment]
Will fix those.
The external keyword is indeed needed

The warning shouldn't be happening though

**Comment by K9i-0** [comment]
The explanation of the situation in which the warning occurred may have been insufficient.

A warning about stateless_ref appeared in a project that depended on riverpod_lint. 
However, this may be expected behavior.
![SCR-20230301-ncs](https://user-images.githubusercontent.com/90010509/222076813-cd23b25c-3f77-4056-90bf-069d953952a9.png)

**Comment by rrousselGit** [comment]
This warning is incorrect. It shouldn't be happening, I'll fix it. Don't worry about it
