### ISSUE TITLE
[riverpod_lint 1.1.1] removing "dependencies" on @Riverpod with keepAlive breaks code

### ISSUE THREAD

**Issue by julienlebren** [rrousselGit/riverpod#2237]
Initial code with useless dependencies:
```dart
@Riverpod(keepAlive: true, dependencies: [anotherProvider])
```
riverpod_lint allow you to remove it by a quick fix.
But if the parameter keepAlive is also present, the fixed code is incorrect:
```dart
@Riverpod(keepAlive: true, 
```

**Comment by rrousselGit** [comment]
Oopsy, will fix. Give me a minute
