### ISSUE TITLE
Can't invalidate FutureProvider.future

### ISSUE THREAD

**Issue by derolf** [rrousselGit/riverpod#2255]
**Describe the bug**

```
final futureProvider = ...
ref.refresh(futureProvider.future);     // compiles
ref.invalidate(futureProvider.future);  // does not compile
```

**Scenario**

I have two FutureProviders, where the second one uses the result of the first one. I'd like to invalidate upstream:

```
@riverpod
Future<Foo> first(FirstRef ref, String key) => ...

@riverpod
Future<Foo> second(SecondRef ref) {
  final provider = firstProvider("test");
  if (ref.state.isRefreshing) {
    ref.refresh(provider.future);     // shows warning (useResult)
    ref.invalidate(provider.future);  // does not compile
  }
  return ref.watch(provider.future);
}
```

**Remarks**

1. Can we have a function on `ref` to register a callback that is triggered when the providers is being invalidated?
2. Could `FutureProvider.provider` return the underlying `FutureOr`, since my solution flickers even if `first` is a `FutureOr`-value.

**Comment by rrousselGit** [comment]
Closing as this was answered

**Comment by derolf** [comment]
read is not watch

**Comment by rrousselGit** [comment]
There's no reason to invalidate ".future"
Invalidate the provider itself.

**Comment by derolf** [comment]
I tried but that threw an exception.

**Comment by rrousselGit** [comment]
That's a different issue. Please open a new one and share it
