### ISSUE TITLE
Lints do not correctly handle renamed providers

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#2262]
**Describe the bug**
![image](https://user-images.githubusercontent.com/30291302/222982056-08b63d83-5f3b-4435-a281-bd8f76a435dd.png)
![image](https://user-images.githubusercontent.com/30291302/222982073-4564d026-5e74-440a-a829-cbafb4df2241.png)
As you can see, renamed providers trigger this lint. This is possibly a wider issue that might be affecting other lints, and making it so we dont see lint hints when we should.

**To Reproduce**
As shown above, simply create a generated provider, and alias it. then attempt to use it in another generated provider
**Expected behavior**
I should not see the lint, as the provider is, in fact, a generated provider.

**Comment by rrousselGit** [comment]
This isn't supported and won't be.  
The proper solution is to wait for static metaprogramming.

Then we'd be able to do:

```dart
class Foo {
  @riverpod
  int fn(FnRef ref) => 0;
}
```
