### ISSUE TITLE
'debugGetCreateSourceHash' is deprecated and shouldn't be used. How do I not use this? 

### ISSUE THREAD

**Issue by davidgtu** [rrousselGit/riverpod#2270]
**Describe the bug**
In my pipeline, I have a step that will run `flutter analyze lib` for any listing errors. When this runs, all of the providers that I generated will return `'debugGetCreateSourceHash' is deprecated and shouldn't be used.`. How do I remove this, or rather, not use this at all?

I am on flutter_riverpod: ^2.1.1.

**To Reproduce**

Run `flutter analyze lib` 

**Expected behavior**
Either the error is a warning or not failing the pipeline

**Comment by rrousselGit** [comment]
Your generated code is out of date. Upgrade Riverpod_generator and run it again
That should fix it.

**Comment by rrousselGit** [comment]
Closing as this was answered

**Comment by davidgtu** [comment]
Forgot to update you -- that was definitely it. Thank you @rrousselGit
