### ISSUE TITLE
[riverpod_lint] - Pub.dev - Incorrect install command 

### ISSUE THREAD

**Issue by Harishwarrior** [rrousselGit/riverpod#2282]
The install command might be incorrect it should be like the below because lints are dev_dependencies

`dart pub add riverpod_lint --dev`
instead of 
`dart pub add riverpod_lint`

`flutter pub add riverpod_lint --dev`
instead of
`flutter pub add riverpod_lint`

```
dev_dependencies:
  riverpod_lint: ^1.1.2
```

instead of

```
dependencies:
  riverpod_lint: ^1.1.2
```

Also it is missing install command for custom_lint

Refer: https://pub.dev/packages/flutter_lints/install

I don't know where to report this issue. Hope this was the correct place.

**Comment by rrousselGit** [comment]
The pub.dev "install" tab is not customizable. Even though it's incorrect, there's nothing I can do.
