### ISSUE TITLE
[riverpod_lint] Rename symbol when converting generated provider between stateless to stateful

### ISSUE THREAD

**Issue by KinectTheUnknown** [rrousselGit/riverpod#2297]
**Is your feature request related to a problem? Please describe.**
Whenever I convert generated providers between stateless and stateful using refactor, I have to change the name everywhere it is being referenced due to Dart's different naming conventions between classes and functions (PascalCase and camelCase).

**Describe the solution you'd like**
I would like the refactor option to rename the provider for me.

**Describe alternatives you've considered**
I can rename the symbol myself before converting. It's an extra step, but gets the job done.

**Additional context**
Stateless:
```dart
@Riverpod(dependencies: [])
int foo(FooRef ref) => 0;

@Riverpod(dependencies: [foo])
int bar(BarRef ref) => ref.watch(fooProvider) + 1;
```
Stateful:

```dart
@Riverpod(dependencies: [])
class Foo extends _$Foo {
  int build() => 0;
}

@Riverpod(dependencies: [Foo])
int bar(BarRef ref) => ref.watch(fooProvider) + 1;
```
Notice that `foo` must change to `Foo` in the `dependencies` of `bar`

**Comment by rrousselGit** [comment]
It's a bit tedious to do I won't lie. But understandable

**Comment by rrousselGit** [comment]
I think it'd be more reasonable to take the extra step of having generated providers be `const`

Then we could have `@Riverpod(dependencies: [fooProvider])` instead of passing the class/function. This would solve the renaming issue indirectly.

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/rrousselGit/riverpod/issues/2998
