### ISSUE TITLE
do not lint on ThisNotifier build() => this in generated code

### ISSUE THREAD

**Issue by RandalSchwartz** [rrousselGit/riverpod#2302]
**Describe the bug**
riverpod_lint is complaining for notifiers that are of their own type, useful when you want to migrate a changenotifier to not
have a separate state instance.  This causes `ThisProvider build() => this;` to be linted, even though everything works.

**To Reproduce**

```
@Riverpod(keepAlive: true)
class RubberDuck extends _$RubberDuck {
  @override
  RubberDuck build() => this;
}
```

and of course the proper imports and build structure.

**Expected behavior**

The RubberDuck type, a derived class of Notifier, would be accepted and supported as the return type.

**Comment by rrousselGit** [comment]
Honestly you probably shouldn't do that though

**Comment by RandalSchwartz** [comment]
It's the easiest thing possible when porting over a ChangeNotifier to the new framework.  There's no specific State type object to work with, and using the Notifier itself shortens the mutate methods.  If there's a way to accomplish those easier, I'm listening...

**Comment by rrousselGit** [comment]
Moving all the properties to a mutable state class is decently simple too.
