### ISSUE TITLE
AsyncNotifier isRefreshing state is replaced by isReloading state

### ISSUE THREAD

**Issue by Velkamhell97** [rrousselGit/riverpod#2304]
**Describe the bug**
When i refresh an `AsyncNotifierProvider` the `isRefreshing` state is false and the `isReloading` state is true, this does not happen with a `FutureProvider` o `StreamProvider` where the `isRefreshing` state and `isReloading` state can be differenciated.

**To Reproduce**
You can verify this bug, simply creating a `AsynNotifierProvider`, and listen it's changes, when you refresh the provider, the `isRefreshing` state will be false an the `isReloading` state will be true.

however this is the code i was testing:

https://dartpad.dev/?id=37afadb52ad56d5e65cea378e0ca763f

And this code is with a `FutureProvider`

https://dartpad.dev/?id=62036901e0ec94b0cbc3a22d0e9fddfd

**Expected behavior**
When i refresh the provider i expect that  `isRefreshing` state will be false, and `isReloading` state will be true, on the other hand, when i add a new todo, i expect that `isRefreshing` be false and `isReloading` state be true, this is the behavior that have `FutureProvider` and `StreamProvider` has.

**Comment by rrousselGit** [comment]
Hello!

Your code doesn't compile. Could you make a code sample that compiles?

**Comment by Velkamhell97** [comment]
Hi, sorry, i forgot put a piece of code, however i already edit the post with a new code where show better what is the problem that i having. thanks for your help! 

https://dartpad.dev/?id=d98be07005e41da85b1c3e69f8f1c880

**Comment by rrousselGit** [comment]
No worries!
Sounds like this is the same issue as:
https://github.com/rrousselGit/riverpod/discussions/2327

Closing in favour of https://github.com/rrousselGit/riverpod/issues/2329

**Comment by Velkamhell97** [comment]
@rrousselGit Thanks!, i had not thought about that.
