### ISSUE TITLE
`onDispose()` called on `Notifier`s seemingly without reason.

### ISSUE THREAD

**Issue by ccrusius** [rrousselGit/riverpod#2309]
**Describe the bug**

`onDispose` seems to be called for notifiers even though there are active subscriptions on them. A full description and example of the behavior is [here](https://aschilken.medium.com/experiments-with-the-new-riverpod-2-0-notifier-d65bc2c51a57), and the gist of it is that logic like the one below will result in expensive dispose/initializations to happen all the time:

```dart
class MyNotifier extends Notifier<int> {
  bool initialized = false;

  @override
  int build() {
    if(!initialized) {
      some_expensive_initialization();
      ref.onDispose(() { some_expensive_dispose(); initialized=false; });
      initialized = true;
    }
    auto value = ref.watch(someDependency);
    return value;
  }
}
```

The above will result in calls to `onDispose` being made every time `build` is called due to an update in `someDependency`, irrespective of whether there are active subscriptions to it. In my case, the init/dispose logic sets up processes that really should only be started/finished with the coming and going of first/last subscribers.

**To Reproduce**

Contrived example that shows the problem: an "increment" provider and an "accumulator" provider. The accumulator resets, I think wrongly, all the time.

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:mockito/mockito.dart';

part 'riverpod_test.g.dart';

@riverpod
class Increment extends _$Increment {
  @override
  int build() {
    return 0;
  }

  void set(int i) {
    state = i;
  }
}

@riverpod
class Accumulator extends _$Accumulator {
  int _cachedState = 0;

  @override
  int build() {
    ref.onDispose(() {
      _cachedState = 0;
    });
    _cachedState += ref.watch(incrementProvider);
    return _cachedState;
  }
}

class Listener extends Mock {
  void call(int? previous, int value);
}

void main() {
  test('Too many onDispose calls', () async {
    final container = ProviderContainer();
    addTearDown(container.dispose);
    final listener = Listener();

    container.listen<int>(accumulatorProvider, listener, fireImmediately: true);
    verify(listener(null, 0)).called(1);

    container.read(incrementProvider.notifier).set(1);
    await container.pump();
    verify(listener(0, 1)).called(1);

    container.read(incrementProvider.notifier).set(2);
    await container.pump();
    verify(listener(1, 3)).called(1); // Called with (1,2) instead, because dispose() was called.
  });
}
```

**Expected behavior**

`dispose` is not called until the notifier is truly not needed.

**Comment by rrousselGit** [comment]
This is the expected behavior. `onDispose` is called before `build` re-execute.  
Through ref.watch you cause `build` to re-execute, so `onDispose` was invoked.


There's no such thing as "perform logic on last dispose" in Riverpod.
We could implement such a thing. But that's a separate issue (as this is a bug report).
If you want such a feature, please make a feature request explaining your use-case.
