### ISSUE TITLE
unsupported_provider_value should not warn

### ISSUE THREAD

**Issue by Kiruel** [rrousselGit/riverpod#2322]
**Describe the bug**

Take an example, this code pass the linter:
```dart
@riverpod
FirebaseMessaging firebaseMessaging(FirebaseMessagingRef ref) =>
    FirebaseMessaging.instance;
```

The instance look like this:
```dart
 static FirebaseMessaging get instance {
    FirebaseApp defaultAppInstance = Firebase.app();
    return FirebaseMessaging._instanceFor(app: defaultAppInstance);
  }
```

But this code not:
```dart
@riverpod
FirebaseRemoteConfig firebaseRemoteConfig(FirebaseRemoteConfigRef ref) =>
    FirebaseRemoteConfig.instance;
```
The instance look like this:
```dart
static FirebaseRemoteConfig get instance {
    return FirebaseRemoteConfig.instanceFor(app: Firebase.app());
  }
```

I got this warning on the linter:
```
The riverpod_generator package does not support ChangeNotifier values.dart(unsupported_provider_value)
```

**Expected behavior**
Should not warn on the second example.

**Comment by rrousselGit** [comment]
Why shouldn't it?
ChangeNotifierProvider is not supported. You created a ChangeNotifier. It's therefore not supported :)

**Comment by rrousselGit** [comment]
Feel free to ignore/disable the lint if you dislike it.

**Comment by Kiruel** [comment]
The strange thinks is that the first example pass the linter. But not the second one, that is almost the same. No ?

**Comment by Kiruel** [comment]
With `@Riverpod(keepAlive: true)` you can @ebsangam but still got the error linter.

**Comment by rrousselGit** [comment]
>  The strange things is that the first example pass the linter. But not the second one, that is almost the same. No ?

The first doesn't create a ChangeNotifier but the second does.

**Comment by rrousselGit** [comment]
This is expected, so closing :)

**Comment by ebsangam** [comment]
> The strange things is that the first example pass the linter. But not the second one, that is almost the same. No ?

It is because `FirebaseRemoteConfig` extends `ChangeNotifier` and `riverpod_generator` does not support `ChangeNotfier`.
