### ISSUE TITLE
Undefined name 'Provider' inside generated files

### ISSUE THREAD

**Issue by dario-digregorio** [rrousselGit/riverpod#2332]
**Describe the bug**
I use the Riverpod Generator and when it is generating the files some dependencies are not generated correctly. Running the app or tests I get the the error:
`Error: Undefined name 'selectedPlaceProvider'.
selected.viewmodel.g.dart:1050
    selectedPlaceProvider,`

Looking in the file I see transitiveDependencies where some of them don't have a type:
<img width="537" alt="Screenshot 2023-03-16 at 22 31 50" src="https://user-images.githubusercontent.com/32966133/225757597-437aa134-05c0-4dac-9830-7392a2cbbe6c.png">

I use Riverpod Lint and I have no linting errors. The only way to fix it is to define the transitive Providers as a direct dependency.

**To Reproduce**
Not sure how to reproduce it. Regenerating the files still create this error.

**Expected behavior**
The generated files should not contain errors.

**Comment by dario-digregorio** [comment]
I think the problem is that the dependencies originate from a different file which also originate from another. So the original file does not have the import and also does not know that it needs it.

**Comment by rrousselGit** [comment]
Sounds like you're missing an import. You need to import the provider

**Comment by dario-digregorio** [comment]
That is correct. But I would expect that the linter would warn me when an import is missing. It can be very tedious to add them all manually when have over 50 providers in scattered over different files. The only way to find out there is a problem is by running or testing my app. Do you think there is another way?

**Comment by rrousselGit** [comment]
I agree. I'll make a separate issue specific to the linter

**Comment by rrousselGit** [comment]
It is weird that you had this issue though. How did you end-up with this exactly? Because the `@riverpod fn` and the generated provider should be part of the same library.

So if you import one (for specifying `dependencies`) then the other should be available
