### ISSUE TITLE
Don't trigger scoped_providers_should_specify_dependencies outside of `main` on runApp calls.

### ISSUE THREAD

**Issue by sabin26** [rrousselGit/riverpod#2340]
While looking through the readme of 'riverpod_lint', it states the following:

**scoped_providers_should_specify_dependencies**
_Providers that do not specify "dependencies" shouldn't be overridden in a ProviderScope/ProviderContainer **that is possibly not at the root of the tree**._

Good
```dart
void main() {
  runApp(
    ProviderScope(
      // This is the main ProviderScope. All providers can be overridden there
      overrides: [
        rootProvider.overrideWith(...),
        scopedProvider.overrideWith(...),
      ],
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      // This ProviderScope is not the root one, so only providers with "dependencies"
      // can be specified.
      overrides: [
        scopedProvider.overrideWith(...),
      ],
      child: Container(),
    );
  }
}
```

**But I am getting warnings for root ProviderContainer/ProviderScope**

Screenshot:
![bootstrap](https://user-images.githubusercontent.com/61322712/225917154-3a9cd7c6-72c4-49f3-bae5-e0be0eb148a9.PNG)

It is considering the ProviderScope as non-root.

**Comment by rrousselGit** [comment]
Right. You're outside the `main`.
