### ISSUE TITLE
`done` callback for `ref.watch(streamProvider).when()` 

### ISSUE THREAD

**Issue by andrei-toterman** [rrousselGit/riverpod#2344]
**Is your feature request related to a problem? Please describe.**
I'd like a way for a watched `StreamProvider` to notify when the underlying stream is done emitting new values.

Consider the following minimal example
```dart
final provider = StreamProvider((_) => const Stream.empty());

// inside consumer widget
ref.watch(provider).when(
    data: (_) => print('data'),
    error: (_, __) => print('error'),
    loading: () => print('loading'),
);
```

This will print `loading` twice, which is misleading, since nothing is loading anymore and no new value will be emitted.

**Describe the solution you'd like**
When watching a `StreamProvider`, return something similar to `AsyncValue<T>` which has some stream-specific API, like a `when` method which takes a `void Function(T?, Object?, StackTrace?) done` callback which gets called when the stream is done emitting values with possibly the latest value/error emitted by the stream.

**Describe alternatives you've considered**
The desired effect can be achieved through a classic `StreamBuilder` which provides an `AsyncSnapshot<T>` with a `ConnectionState` that usually goes from `waiting` to `active` to `done`, thus differentiating the states.
The same `AsyncSnapshot<T>` is also used by a `FutureBuilder`, and the `ConnectionState` usually goes from `waiting` to `done`. So maybe the existing `when` method could be modified to take in 4 callbacks, and in the case of a watched `FutureProvider` simply to never call the one corresponding to `ConnectionState.active`.

**Comment by rrousselGit** [comment]
There is no such thing. To begin with, providers are never done. The provider could get refreshed at any time either with ref.refresh or ref.watch.

**Comment by rrousselGit** [comment]
Providers can also modify their own state with ref.state=
There's also the new StreamNotifier with even more ways to modify themselves.

So I don't think this makes sense.

**Comment by rrousselGit** [comment]
> This doesn't mean that once an AsyncDone is emitted the provider cannot provide new values, only that the particular asynchronous operation that was waited on is done.


But that's not the case. 


Your streamProvider could very well do:

```dart
final p = StreamP<String>((ref) {
  ref.listen(anotherProvider, (_, value) => ref.state = AsyncData('Received some value');
  return Stream.empty();
})
```

So the stream emitting "done" doesn't mean the provider is done.

**Comment by andrei-toterman** [comment]
Then I guess I'll have to create a wrapper for this kind of 'done' value that I want to detect and use that as the data type of the provider. I was hoping for an `AsyncDone<T>` alongside `AsyncData<T>` instead of just using `AsyncData<Done<T>>`, since that's a little more cumbersome. But now I understand why my request cannot be generalized to all use cases, so thanks for the explanation!
