### ISSUE TITLE
Complete list of provider kinds?

### ISSUE THREAD

**Issue by PiN73** [rrousselGit/riverpod#235]
At the moment all provider kinds are mentioned in docs, however there isn't a compete list, which makes discovering them harder.

Is it a good idea to add a table containing name, description and canonical usage example for each provider kind?

**Comment by Marco87Developer** [comment]
In my opinion it would be very useful.

**Comment by rrousselGit** [comment]
This list is available in riverpod.dev under "API reference / all providers"
