### ISSUE TITLE
Riverpod generator doesn't reflect namespaced packages

### ISSUE THREAD

**Issue by hamishjohnson** [rrousselGit/riverpod#2351]
I'm using riverpod with Supabase. When using 

```
@Riverpod(keepAlive: true)
SupabaseClient supabase(SupabaseRef ref) {
  return Supabase.instance.client;
}
```

I had an issue with the generated file because Supabase has it's own Provider object which clashes with riverpod. So, I tried 

```
@Riverpod(keepAlive: true)
sb.SupabaseClient supabase(SupabaseRef ref) {
  return sb.Supabase.instance.client;
}
```

And unfortunately that doesn't work either because the generated code does not use the namespace.

<img width="616" alt="Screenshot 2023-03-19 at 20 57 05" src="https://user-images.githubusercontent.com/9589803/226180925-c92efd9c-9375-4388-bd7c-5a57c53fff5d.png">

My expectation would be that riverpod generator namespaces the modules.

In my specific case, I've been able to fix it by using ref.keepAlive() instead of @Riverpod(keepAlive: true) but that won't apple to everyone experiencing this issue.

**Comment by rrousselGit** [comment]
This is a known issue, but won't be supported until we have static metaprogramming.
The maintenance cost would otherwise be too high
