### ISSUE TITLE
[riverpod_lint]Multiple plugins can't be enabled

### ISSUE THREAD

**Issue by motucraft** [rrousselGit/riverpod#2354]
**Describe the bug**
I don't think it's a riverpod_lint issue...but
When I try to set multiple "plugins" in analysis_options.yaml, it points out "Multiple plugins can't be enabled". 
Is there any workaround?

**To Reproduce**
I tried to set [dart_code_metrics](https://pub.dev/packages/dart_code_metrics) and riverpod_lint.

![image](https://user-images.githubusercontent.com/35750184/226252775-0eec11a3-3e92-4bf8-992a-afaff4d51d02.png)

**Expected behavior**
I want both "plugins" to work.

**Comment by rrousselGit** [comment]
No. Pick one :) 

Nothing I can do.
But custom_lint support any number of custom_lint_plugin technically dart_code_metrics could be implemented with it
