### ISSUE TITLE
Test lints related to ProviderScopes with tester.pumpWidget

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2355]
- missing ProviderScope
- root overrides
- scoping (when done)

**Comment by lockieRichter** [comment]
@rrousselGit you looking for contributions on this one?

**Comment by rrousselGit** [comment]
Sure, if you will like fixing it, go ahead.

We'd likely want to update the lint to consider "pumpWidget" the same as "runApp"

**Comment by lockieRichter** [comment]
Opened https://github.com/rrousselGit/riverpod/pull/3056 in Draft status right now, I've asked on Discord, but wondering how I run the tests locally for the `riverpod_lint` package?

**Comment by rrousselGit** [comment]
`dart test` in `riverpod_lint_flutter_test`

**Comment by lockieRichter** [comment]
ahh good one, I was using `flutter test`
