### ISSUE TITLE
Add Support for ChangeNotifier

### ISSUE THREAD

**Issue by iapicca** [rrousselGit/riverpod#2365]
#### description

at the time of writing [riverpod_lint](https://pub.dev/packages/riverpod_lint) warns
> The riverpod_generator package does not support ChangeNotifier values.dart(unsupported_provider_value)

please add support for [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html)

#### use cases

```dart
@Riverpod(dependencies: [])
GoRouter router(RouterRef ref) {
  return GoRouter(
    ...
  );
}
```

```dart
@Riverpod(dependencies: [])
ValueNotifier<int> router(RouterRef ref) {
  return ValueNotifier(0);
}
```

#### possible solutions

```dart
typedef OnDispose = void Function(VoidCallback);

@Riverpod(dependencies: [])
ValueNotifier<int> router(RouterRef ref, OnDispose onDispose) {
  final notifier = ValueNotifier(0);
  onDispose(notifier.dispose);
  return notifier
}
```
#

```dart
@Riverpod(dependencies: [])
ValueNotifier<int> router(RouterRef ref) {
  final notifier = ValueNotifier(0);
  ref.onDispose(notifier.dispose);
  return notifier
}
```

**Comment by rrousselGit** [comment]
Feel free to disable the lint if you don't like it.

The point of this lint is that consumers won't rebuild when notifyListeners is invoked.
Nor will it invoke notifier.dispose.

If you don't care about this, you don't need to use the lint.

**Comment by rrousselGit** [comment]
I have no plan to add support for listening to ChangeNotifiers for now.

**Comment by iapicca** [comment]
@rrousselGit 
I'm confused

[here](https://github.com/rrousselGit/riverpod/issues/2365#issuecomment-1478187931) you say 

> If you don't care about this, you don't need to use the lint.

which makes me thing that is just a "best practice", but then [here](https://github.com/rrousselGit/riverpod/issues/2365#issuecomment-1478189002)

> I have no plan to add support for listening to ChangeNotifiers for now.

what issue will I encounter if I use it this way?

```dart
@Riverpod(dependencies: [])
// ignore: unsupported_provider_value
GoRouter router(RouterRef ref) {
  final router = GoRouter(
    ...
  );
  ref.onDispose(router.dispose);
  return router;
```

**Comment by rrousselGit** [comment]
As I said before, the provider will not listen to notifyListeners and not naturally dispose the notifier.  
The generated provider is not a ChangeNotifierProvider, just a Provider.

The lint is here to warn about this fact.  
If you don't care about this, disable the lint either locally or globally.

**Comment by iapicca** [comment]
> As I said before, the provider will not listen to notifyListeners and not naturally dispose the notifier. The generated provider is not a ChangeNotifierProvider, just a Provider.
> 
> The lint is here to warn about this fact. If you don't care about this, disable the lint either locally or globally.

that's good enough then, thank you
I'll close this for now
