### ISSUE TITLE
[riverpod_lint] Add an only_select_provider

### ISSUE THREAD

**Issue by gaetschwartz** [rrousselGit/riverpod#2375]
**Is your feature request related to a problem? Please describe.**
It would be pretty useful to have a riverpod rule that ensures you only listen to a specific provider by selecting it.

**Describe the solution you'd like**

```dart
@riverpod
@onlySelectProvider
class SettingsModel extends _$SettingsModel {
   // This class has a lot of attributes and is updated as soon as one changes.
}

Widget build(BuildContext context) {
  // Good
  final username = ref.watch(settingsModelProvider.select((s) => s.username));
  // Bad, updates way too frequently 
  final thememode = ref.watch(settingsModelProvider).thememode;
}
```

**Describe alternatives you've considered**
Well just manually checking it.

**Comment by rrousselGit** [comment]
About your proposal, I'm not sure about the proposed API (the annotation).  
`select` isn't necessarily faster. It often is, but it's supposed to be on a case-by-case basis. 

Sometimes a widget is so cheap to rebuild that the added cost of `select` isn't worth it.

**Comment by rrousselGit** [comment]
Another scenario where using `select` is less "debatable" would be inside providers. As rebuilding too often can clear the state

So:

```dart
final provider = FutureProvider((ref) async {
  final user = ref.watch(userProvider); // Bad, use select
  return fetch('api/${user.name}');
});
```

This wouldn't involve an annotation

**Comment by rrousselGit** [comment]
Ah yes you were faster :P

**Comment by gaetschwartz** [comment]
Ive been looking at implementeing it, but I'm still stuck on a few design choices, if you are available we can have a chat on twitter ?

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/rrousselGit/riverpod/issues/2996
