### ISSUE TITLE
[riverpod_generator] Generating codes with generic parameters

### ISSUE THREAD

**Issue by KiritaniAyaka** [rrousselGit/riverpod#2389]
I'm working on a simple Todo demo with riverpod. There's my code of provider:

```dart
part 'task.g.dart';

@riverpod
class Task extends _$Task {
  @override
  List<TaskData> build() => [];
}
```

Generated code:

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'task.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$taskHash() => r'7d1cece618951137856487a392f88a3eee18d744';

/// See also [Task].
@ProviderFor(Task)
final taskProvider = AutoDisposeNotifierProvider<Task, List<dynamic>>.internal(
  Task.new,
  name: r'taskProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$taskHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$Task = AutoDisposeNotifier<List<dynamic>>;
// ignore_for_file: unnecessary_raw_strings, subtype_of_sealed_class, invalid_use_of_internal_member, do_not_use_environment, prefer_const_constructors, public_member_api_docs, avoid_private_typedef_functions
```

I noticed that the generated code uses `dynamic` as the type for generic parameters. This means that when I use elements of collections, I have to explicitly specify their types.

I'm not familiar with Dart code generation. Is this by design, a limitation of Dart code generation, or a feature that was not considered before?

**Comment by KiritaniAyaka** [comment]
I'm sorry for missing that. TaskData is an entity class generated by Drift.

I guess it may be that the type cannot be obtained while code generating.

Is it possible to resolve this problem?

**Comment by KiritaniAyaka** [comment]
I try to add a `build.yaml` to order builders:

```yml
global_options:
  drift_dev:
    runs_before:
      - riverpod_generator
```

No warning was given by build_runner. But nothing helped also.

**Comment by rrousselGit** [comment]
> TaskData is an entity class generated by Drift.

That's a pretty important information 😊

The generator does not support return values that contains other generated classes.
This is a limitation of build_runner which is difficult to work around.

Wait until static metaprogramming and the problem should fix itself
