### ISSUE TITLE
Code-Gen FutureProvider gets called every time Its listened to

### ISSUE THREAD

**Issue by Abdullah104** [rrousselGit/riverpod#2393]
**Describe the bug**
When creating a FutureProvider using riverpod_generator, the provider logic gets called again every time I listen to it

**To Reproduce**
Create the following provider
```dart
part 'entities_provider.g.dart';
@riverpod
Future<Either<EntitiesRetrievalFailure, List<Entity>>> getEntities(
  GetEntitiesRef _,
) {

  return getIt<EntitiesRepository>().getEntities();
}
```

**Expected behavior**
The expected behavior is that the provider's logic gets called once when its first listened to, and then have this value stored for future use

When I changed the provider to not use code-gen, it produced this expected behavior, here is my provider without code-gen
```dart
final getEntitiesProvider =
    FutureProvider((ref) => getIt<EntitiesRepository>().getEntities());
```

**Comment by rrousselGit** [comment]
Your two snippets aren't identical.

Codegen defaults to making providers autoDispose, while your second snippet didn't make the provider autoDispose. That's likely your issue.

Make sure to ref.watch your providers. You likely used ref.read

**Comment by Abdullah104** [comment]
I used ```ref.watch```

Is there a way to make Codegen providers not autoDispose?

**Comment by rrousselGit** [comment]
@Riverpod(keepAlive: true)

**Comment by Abdullah104** [comment]
Thank you.
