### ISSUE TITLE
Making _FutureProviderBase<T> public

### ISSUE THREAD

**Issue by markusrut** [rrousselGit/riverpod#2396]
Im trying to solve duplication in my codebase when watching FutureProvider and having default behaviour for easy reuse

The solution i have come up with is to make a generic widget that takes in a provider and a builder and use them to wrap do a normal ref.watch and using the builder in the data param, and using this generic widget to implement all the default behaviour i want, like loading state, formatted error and refresh indicator.

The problem with this that i'm facing is that having a mix of `FutureProvider<T> `and `AutoDisposeFutureProvider<T>` is forcing me to have multiple parameters and using the correct one depending on the given provider like this
```
    final realProvider = provider ?? autoDisposeProvider;

    if (realProvider == null) {
      throw ArgumentError.notNull("provider");
    }
```

`realProvider` is then typed as `_FutureProviderBase<T>? `
It would be really nice to not have to do this workaround by having _FutureProviderBase as public to enable this as a parameter directly instead

I have considered using `ProviderBase<AsyncValue<T>>` but then i wont have access to `provider.future` that i want to use in RefreshIndicator.onRefresh so that the indicator is shown the correct time while the provider is being refreshed.

**Comment by rrousselGit** [comment]
I have no plan to do this. This isn't something you're meant to do.  There are way too many combinations of common interfaces between providers for this to be reliable, and it'll get worse over time.

For example what if you wanted to support `StreamProvider` too? Or AsyncNotifierProvider ...

Passing providers is generally discouraged. And even if you were to pass providers, you shouldn't rely on their concrete type. Instead, the only thing you should rely on is `ProviderListenable<T>`.

if you want a widget to receive both the provider and .future you could do:

```dart
class MyWidet 
  final ProviderListenable<AsyncValue<T>> provider;
  final ProviderListenable<Future<T>> future;
...
}

// used as:

MyWidget(provider: futureProvider, future: futureProvider.future)
```

**Comment by rrousselGit** [comment]
No problem. Have a great day!
