### ISSUE TITLE
Example of reflecting state updates across screens

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/riverpod#24]
The todos example shows adding and dismissing todos on a single screen.  It is quite clear how the state of the todo list is manipulated in this example.

Suppose however that the main todo list screen only shows todos coming up in the next week.  The state notifier TodoList only loads this subset of todos from the data source for performance reasons.

Suppose further that the user can push another screen on to the navigation stack to show a different list of todos where there might be some overlap with the first list – some of those todos might be in the main screen's TodoList, some might not.  This presumably requires another TodoList state notifier instance which loads that second set of todos.

The question arises of how to update state on the first screen when a todo is changed on the second screen.  The second screen's TodoList state notifier will update its state and thus reflect the state change on the second screen.

What would be the best practise to propagate this state change to the TodoList's of both screens?  Or is this thinking about it the wrong way and that you would instead have a single TodoList that changes its internal list according to the screen navigation?

I appreciate that this question relates more to state notifiers than provider, but I thought to pose it here as StateNotifier seems an important part of Riverpod.

**Comment by scopendo** [comment]
A similar question would be reflecting state changes when both the TodoList and Todo are state (or change) notifiers.  It might be that the action of updating a todo's data belongs in a Todo state notifier so that subscribed widgets for that todo can rebuild, but we also need the todo state within the TodoList to be updated.

**Comment by rrousselGit** [comment]
The important thing is to have a single source of truth. So you should make sure that both todo-lists obtain their todos from same source.

This could be done by having a "family" for all todos.
Since you want them to be editable, you could use a `StateNotifierProviderFamily`, and have the argument be the todo ID:

```dart
class TodoNotifier extends StateNotifier<Todo> {
  TodoNotifier(String id): super(Todo(id: id));

  void updateDescription(String description) {
    state = state.copyWith(description: description);
  }
}

final todoFamily = StateNotifierProviderFamily<TodoNotifier, String>((ref, id) {
  return TodoNotifier(id);
});
```

From there, the provider for your home and for the other screen should both use `todoFamily` to obtain their todos.
In the ideal world, they should both be a Computed. Otherwise, you can make them a state/change notifier, and they should use `TodoNotifier.addListener` to keep track of changes on individual todos.

This way, both lists obtain their todos from the same source, which means that when a todo is updated, both lists will have the update.

**Comment by rrousselGit** [comment]
To expand on the previous point of having a single source of truth, it would make sense for your "home" and "other screen" lists to only store the id of a todo, not the todo itself.

So we would have:

```dart
final homeList = StateNotifierProvider((ref) => HomeList());

class HomeList extends StateNotifier<List<String>> {
  HomeList(this.ref): super([]);

  final ProviderReference ref;

  void addTodo(String description) {
    final newTodoId = _uuid.v4();

    // Initialize the new todo
    final todoNotifier = ref.read(todoFamily(newTodoId));
    todoNotifier.updateDescription(description);

    // update the UI
    state = [...state, newTodoId];
  }
}
```


Then the list of IDs can be combined with `todoFamily` to obtain a the todos. This could be done either in a `Computed` or inside a Consumer directly.

```dart
final ids = read(homeList.state);

final todos = [
  for (final id in ids)
    read(todoFamily(id).state)
];
```

Which would automatically update the UI both when the id list changes or when the content of a todo changes

**Comment by scopendo** [comment]
Thank you for these detailed answers @rrousselGit – I'm going to have to spend a bit of timing understanding them, especially as I'm still using Provider rather than Riverpod.

**Comment by devon** [comment]
> To expand on the previous point of having a single source of truth, it would make sense for your "home" and "other screen" lists to only store the id of a todo, not the todo itself.
> 
> So we would have:
> 
> ```dart
> final homeList = StateNotifierProvider((ref) => HomeList());
> 
> class HomeList extends StateNotifier<List<String>> {
>   HomeList(this.ref): super([]);
> 
>   final ProviderReference ref;
> 
>   void addTodo(String description) {
>     final newTodoId = _uuid.v4();
> 
>     // Initialize the new todo
>     final todoNotifier = ref.read(todoFamily(newTodoId));
>     todoNotifier.updateDescription(description);
> 
>     // update the UI
>     state = [...state, newTodoId];
>   }
> }
> ```
> 
> Then the list of IDs can be combined with `todoFamily` to obtain the todos. This could be done either in a `Computed` or inside a Consumer directly.
> 
> ```dart
> final ids = read(homeList.state);
> 
> final todos = [
>   for (final id in ids)
>     read(todoFamily(id).state)
> ];
> ```
> 
> Which would automatically update the UI both when the id list changes or when the content of a todo changes

We cannot use `audoDispose` in this case, right?

So, how to dispose of the object if we are pretty sure we don't need it on any screen anymore?

**Comment by JuI3s** [comment]
> To expand on the previous point of having a single source of truth, it would make sense for your "home" and "other screen" lists to only store the id of a todo, not the todo itself.
> 
> So we would have:
> 
> ```dart
> final homeList = StateNotifierProvider((ref) => HomeList());
> 
> class HomeList extends StateNotifier<List<String>> {
>   HomeList(this.ref): super([]);
> 
>   final ProviderReference ref;
> 
>   void addTodo(String description) {
>     final newTodoId = _uuid.v4();
> 
>     // Initialize the new todo
>     final todoNotifier = ref.read(todoFamily(newTodoId));
>     todoNotifier.updateDescription(description);
> 
>     // update the UI
>     state = [...state, newTodoId];
>   }
> }
> ```
> 
> Then the list of IDs can be combined with `todoFamily` to obtain the todos. This could be done either in a `Computed` or inside a Consumer directly.
> 
> ```dart
> final ids = read(homeList.state);
> 
> final todos = [
>   for (final id in ids)
>     read(todoFamily(id).state)
> ];
> ```
> 
> Which would automatically update the UI both when the id list changes or when the content of a todo changes

Would you provide an example of how to delete a todo item by its ID? Suppose we have two lists that fetch data from remote API but contain some overlapping todo items, and the user wants to delete an item so the change will be reflected in multiple todo lists. 

Sorry I’m new to river-do and couldn’t seem to find a solution in the doc.
