### ISSUE TITLE
Using hasListeners to check listener returns true even when no listeners are active.

### ISSUE THREAD

**Issue by TitanKing** [rrousselGit/riverpod#2400]
**Describe the bug**
Checking for a listener with `StateNotifier<SomeState>.hasListeners` always returns true, whether a listener have been added with  `StateNotifier<SomeState>.addListener((state){})` has been added or not.

**To Reproduce**
Before creating a listener, check if one exists with `StateNotifier<SomeState>.hasListeners`, it will return true.

**Expected behavior**
When no listeners have been explicitly assigned via `StateNotifier<SomeState>.addListener((state){})` then `StateNotifier<SomeState>.hasListeners` should return false. 

This used to be the behaviour. Recently discovered it is not working any more.

PS: Thanks for the wonderful state engine, have been using it for years now.

**Comment by rrousselGit** [comment]
That's logical. Riverpod listens to the StateNotifier. So there is one listener, the provider.

You can use ref.onCancel/ref.onResume for similar thing

**Comment by TitanKing** [comment]
I understand the logic. Thank you for responding.
