### ISSUE TITLE
3 or more nested ProviderScopes change the behavior of an autodisposable family provider

### ISSUE THREAD

**Issue by victorcatn** [rrousselGit/riverpod#2403]
**Describe the bug**
When there are 3 or more nested `ProviderScope`s, an auto-disposal family provider exhibits different (and wrong) rebuild behavior compared with 1 or 2 nested `ProviderScope`s.

**To Reproduce**
Execute this widget inside 3 nested `ProviderScope`s and use a debugger/ProviderObserver
```dart
class MyApp extends HookConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final family = useState<String>('a');

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              TextField(onSubmitted: (text) => family.value = text),
              Text(ref.watch(myFamilyProvider(family.value))),
            ],
          ),
        ),
      ),
    );
  }
}

@riverpod
String myFamily(Ref ref, String frozen) {
  return '$frozen family';
}
```
Alternatively, clone this repo and execute this test: [https://github.com/victorcatn/riverpod_issue/blob/main/test/bug_test.dart](https://github.com/victorcatn/riverpod_issue/blob/main/test/bug_test.dart)

The test basically uses a `TextField` to change the parameter of a family provider but the version with 3 nested `ProviderScope`s makes different events, I tried to debug it and saw a weird behavior, It seems to get cached results despite having disposed the providers before, and also tries to dispose already disposed providers by recreating them and disposing them immediately.

**Expected behavior**
riverpod should behave the same no matter the number of nested `ProviderScope`s

**Comment by rich-j** [comment]
Sounds like a duplicate of #1943 (over 4 months ago) which has a possible fix #2341 (we haven't tried this yet). Our workaround has been to control the lifetime of our providers using `keepAlive` (which is a major pain).

**Comment by CATAV009** [comment]
Thanks @rich-j 
This is indeed a duplicate, and the PR #2341 fixes it for me

**Comment by victorcatn** [comment]
Thanks @rich-j 
This is indeed a duplicate, and the PR #2341 fixes it for me
