### ISSUE TITLE
[riverpod_generator] Support generate for abstract class

### ISSUE THREAD

**Issue by ninhngadev** [rrousselGit/riverpod#2404]
my old notifier

```dart
abstract class IapNotifier extends StateNotifier<IapState> {
  IapNotifier(
    this.ref, {
    List<String> consumableIds = const [
      'consum1',
      'consum2',
      'consum3',
      'consum4',
      'consum5',
      'consum6',
    ],
    List<String> subscriptionIds = const [
      'sub1',
      'sub2',
      'sub3',
      'sub4',
      'sub5',
    ],
  }) : super(IapState(
          consumableIds: consumableIds,
          subscriptionIds: subscriptionIds,
        )) {
    Future(reloadDiamonds);
  }
  final Ref ref;

  Future<void> useDiamonds([int diamonds = 10]) async {
    final purchase = await checkPurchase();

    if (!purchase) {
      await IapStorageHelper.useDiamonds(diamonds);
    }
    reloadDiamonds();
  }

  Future<void> buyDiamondsIfNeed(String storeId) async {
    switch (storeId) {
      case 'consum1':
        buyDiamonds(100);
        break;
      case 'consum2':
        buyDiamonds(200);
        break;
      case 'consum3':
        buyDiamonds(300);
        break;
      case 'consum4':
        buyDiamonds(400);
        break;
      case 'consum5':
        buyDiamonds(500);
        break;
      case 'consum6':
        buyDiamonds(600);
        break;
    }
  }

  Future<void> buyDiamonds(int diamonds) async {
    await IapStorageHelper.buyDiamonds(diamonds);
    reloadDiamonds();
  }

  Future<void> reloadDiamonds() async {
    final diamonds = await IapStorageHelper.getDiamonds();
    state = state.copyWith(diamonds: diamonds);
  }

  Future<void> restorePurchase();

  Future<void> fetchProducts();

  Future<bool> checkPurchase({String storeId = ''});

  Future<void> makePurchase(String storeId);

  Widget buyScreen({String title = 'Buy options', bool showAppbar = true});
}

```

convert to generator

```dart


@Riverpod(keepAlive: true)
abstract class Iap extends _$Iap {
  @override
  IapState build() {
    throw UnimplementedError();
  }

  Future<void> useDiamonds([int diamonds = 10]) async {
    final purchase = await checkPurchase();

    if (!purchase) {
      await IapStorageHelper.useDiamonds(diamonds);
    }
    reloadDiamonds();
  }

  Future<void> buyDiamondsIfNeed(String storeId) async {
    switch (storeId) {
      case 'consum1':
        buyDiamonds(100);
        break;
      case 'consum2':
        buyDiamonds(200);
        break;
      case 'consum3':
        buyDiamonds(300);
        break;
      case 'consum4':
        buyDiamonds(400);
        break;
      case 'consum5':
        buyDiamonds(500);
        break;
      case 'consum6':
        buyDiamonds(600);
        break;
    }
  }

  Future<void> buyDiamonds(int diamonds) async {
    await IapStorageHelper.buyDiamonds(diamonds);
    reloadDiamonds();
  }

  Future<void> reloadDiamonds() async {
    final diamonds = await IapStorageHelper.getDiamonds();
    state = state.copyWith(diamonds: diamonds);
  }

  Future<void> restorePurchase();

  Future<void> fetchProducts();

  Future<bool> checkPurchase({String storeId = ''});

  Future<void> makePurchase(String storeId);

  Widget buyScreen({String title = 'Buy options', bool showAppbar = true});
}


```
but got error

![image](https://user-images.githubusercontent.com/122073248/228797268-afcdcdc4-a16b-4866-9c94-0bc97afd2a6a.png)

**Comment by rrousselGit** [comment]
What is this supposed to do?

**Comment by ninhngadev** [comment]
I want to create a provider base and depending on the platform there will be providers implemented for each of those platforms.
example

```dart

iapProvider.overrideWith(
      (ref) {
        if (isDesktop) {
          return WindowsIapNotifier(ref);
        } else {
              return GoogleIapNotifier(ref);
        }
      },
    ),
```

**Comment by assemblethis** [comment]
I'm doing the exact same thing: using overrideWith() in my ProviderScope to implement providers per platform (Web, Android, iOS) and per application. I thought I'd try riverpod_generator and came here to see if anyone had attempted it.

**Comment by rrousselGit** [comment]
You can throw in the unimplemented methods or make a constructor which throws

```dart
@riverpod
abstract class MyNotifier extends _$MyNotifier {
  MyNotiifer._();
  factory MyNotifier() {
    throw UnimplementedError();
  }
}

class Impl extends MyNotifier {
  Impl(): super._();
}

...

myNotifierProvider.overrideWith(Impl.new);
```

**Comment by assemblethis** [comment]
> You can throw in the unimplemented methods or make a constructor which throws
> 
> ```dart
> @riverpod
> abstract class MyNotifier extends _$MyNotifier {
>   MyNotiifer._();
>   factory MyNotifier() {
>     throw UnimplementedError();
>   }
> }
> 
> class Impl extends MyNotifier {
>   Impl(): super._();
> }
> 
> ...
> 
> myNotifierProvider.overrideWith(Impl.new);
> ```

This example works fine if you want your derived class to live in the same file as your abstract class, but I was trying to separate the abstract class from the implementation. So I'm not able to use the private constructor _() and instead used MyNotifier() and got rid of the factory constructor. This causes an error in the generated code by RiverpodGenerator on **MyNotifier.new**: "**A generative constructor of an abstract class can't be torn off. Try tearing off a constructor of a concrete class, or a non-generative constructor.**"



```
/// See also [MyNotifier].
@ProviderFor(MyNotifier)
final myNotifierProvider =
    AutoDisposeAsyncNotifierProvider<MyNotifier, void>.internal(
  MyNotifier.new,
  name: r'myNotifierProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$myNotifierHash,
  dependencies: null,
  allTransitiveDependencies: null,
);
```

I'm using the latest riverpod_annotation: ^2.1.1

@rrousselGit, can you think of a solution to this?

Thanks for your time with this issue!

**Comment by assemblethis** [comment]
Ok, got it to work by renaming **MyNotifier._()** to **MyNotifier.internal()**;

File 1:
```
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'my_notifier.g.dart';

@riverpod
abstract class MyNotifier extends _$MyNotifier {
  MyNotifier.internal();

  @override
  Future<void> build() async {}

  factory MyNotifier() {
    throw UnimplementedError();
  }
}
```

File 2:

```
class Impl extends MyNotifier {
  Impl() : super.internal();
}
```

**Comment by assemblethis** [comment]
@rrousselGit, this workaround for the original issue has a bit of a code smell to it. I wonder if this is maybe not the best approach? It works for now though.

**Comment by tbm98** [comment]
> You can throw in the unimplemented methods or make a constructor which throws
> 
> ```dart
> @riverpod
> abstract class MyNotifier extends _$MyNotifier {
>   MyNotiifer._();
>   factory MyNotifier() {
>     throw UnimplementedError();
>   }
> }
> 
> class Impl extends MyNotifier {
>   Impl(): super._();
> }
> 
> ...
> 
> myNotifierProvider.overrideWith(Impl.new);
> ```

although it might work, the `Impl` class cannot access the `ref` and `state` properties.
it has almost no effect.

**Comment by rrousselGit** [comment]
> @rrousselGit although it might work, the `Impl` class cannot access the `ref` and `state` properties.
> it has almost no effect.

What do you mean? It should be able to.

**Comment by tbm98** [comment]
> > @rrousselGit although it might work, the `Impl` class cannot access the `ref` and `state` properties.
> > it has almost no effect.
> 
> What do you mean? It should be able to.

No it can not.
I have tried.

**Comment by rrousselGit** [comment]
And I have tried too. It can.

**Comment by tbm98** [comment]
> And I have tried too. It can.
@rrousselGit What version have you tried on?
I tried on the latest stable version of riverpod and it doesn't work.
can you give me the example code you used?

**Comment by mattermoran** [comment]
@tbm98 the latest version. he already provided the code above that you said doesn't work even though it clearly does. 
```dart
@riverpod
abstract class MyNotifier extends _$MyNotifier {
  MyNotifier._();
  factory MyNotifier() {
    throw UnimplementedError();
  }

  @override
  int build();
}

class Impl extends MyNotifier {
  Impl() : super._();

  @override
  int build() {
    return 0;
  }

  test() {
    ref.read(myNotifierProvider);
    state == 0;
  }
}
```

**Comment by rrousselGit** [comment]
> @tbm98 the latest version. he already provided the code above that you said doesn't work even though it clearly does.
> 
> ```dart
> @riverpod
> abstract class MyNotifier extends _$MyNotifier {
>   MyNotifier._();
>   factory MyNotifier() {
>     throw UnimplementedError();
>   }
> ```

Don't throw UnimplementedError in the factory, but yes.



@tbm98 I would assume that what you tried is not exactly what I shared. For example, maybe you used `implements MyNotifier` instead of `extends MyNotifier`

**Comment by dunbs** [comment]
I noticed that in version 2.3.9 of riverpod_generator, a [validation.dart](https://github.com/rrousselGit/riverpod/commit/b527c077b91f77177ff9243256f32faaad7f2d2c?short_path=31e4579#diff-9937f6627eaad3f0fc058d225fb5ade4624fed1928b38070a43fdca3e2d9728e) file is added to assert if a Notifier is abstract. 

I wonder if abstract class is not recommended for riverpod?
