### ISSUE TITLE
DependencyNotifier?

### ISSUE THREAD

**Issue by meg4cyberc4t** [rrousselGit/riverpod#2405]
I want to leave this here as a discussion about one convenient notifier.

For example, the task: We need to take the user's repository and get the data from there asynchronously, whether the user is registered or not. We know for sure that we will call initialization on the splash screen, and fully control the behavior. If we find an error when executing future, we will make sure that the user is not logged in.

In the case of riverpod, we could use:
- AsyncNotifier, but then we need to check it for the presence of data every time we receive the notifier state (that there is no loading or error). As an option, it will work, but it makes no sense to do a check every time if we know for sure that there can be no error there.

- Notifier. It already sounds better, because we can create an initAsync method, use it, and change the synchronous state after loading. However, it remains possible for the developer to use ref.watch() and when rebuilding the class, we do not initialize it asynchronously again.

@rrousselGit , how do you like the idea of making a DependencyNotifier? Its main differences will be that.
- **You can't use ref.watch** in order to avoid rebuilding the class.
- The state will always be synchronous.
- If the user has not initialized the dependency but wants to get a state, return an error to him.

I see the most widespread option as follows:

logged_notifier.dart
```dart
class LoggedNotifier extends DependencyNotifier<LoggedState> {
   @override
    Future<LoggedState> build() async {
        return await ref.read(userRepositoryProvider).getState();
    }

   @override
   LoggedState onBuildError() => LoggedState.notLogged();


```
and 

splash_screen.dart
```dart
Future<void> initDependency(ref) async {
    await ref.read(loggedNotifierProvider); // StateException: The state is not initialized, use build!
    await ref.read(loggedNotifierProvider.notifier).build();
    await ref.read(loggedNotifierProvider); // LoggedState:logged(...)
}
```

**Comment by rrousselGit** [comment]
> AsyncNotifier, but then we need to check it for the presence of data every time we receive the notifier state (that there is no loading or error). As an option, it will work, but it makes no sense to do a check every time if we know for sure that there can be no error there.

That's no issue. This is what's recommended.  
It's the safest approach as if there's ever a mistake, the error message will be much better. And it doesn't involve funky shenanigans to set it up.

AsyncValue has its `requireValue` property if you want to assume that the data is present. No need for `when`. You can do:

```dart
print(ref.watch(asyncNotifierProvider).requireValue);
```

If there's data, it'll print it. And if your assumption is false, it'll clearly tell you so (such as rethrowing the error if the async request failed).
