### ISSUE TITLE
Family with map<String, dynamic> infinite loop

### ISSUE THREAD

**Issue by Naografix** [rrousselGit/riverpod#2416]
Hello

I don't know if it's a bug and I don't understand why I have this behavior in my code, but I got an infinite loop just with my map. I never hit data:

```
@override
Widget build(BuildContext context, WidgetRef ref) {
  final testData = {"id": "1"};
  final testAsync = ref.watch(myProvider(testData));

  return Scaffold(
    body: testAsync.when(
      loading: () => Text(""),
      error: (error, stack) => Text(""),
      data: (data) {
        return Text("");
      },
    ),
  );
}
```
```
final myProvider = FutureProvider.family<bool?, Map<String, dynamic>>((ref, arguments) async {
    return null;
});
```

If I use a Tuple2 it works perfecly but not with a Map, why?

Thanks

**Comment by rrousselGit** [comment]
This is expected.
You didn't respect the rule which says that family arguments needs a consistent hashCode/== 

See https://riverpod.dev/docs/concepts/modifiers/family#parameter-restrictions

**Comment by Naografix** [comment]
Ok this is why with a Tuple2 it works good. Just because everytime I create my map, a new hashcode is generated. Thanks
