### ISSUE TITLE
ref.read vs ref.watch vs ref.listen (racing condition)

### ISSUE THREAD

**Issue by eli1stark** [rrousselGit/riverpod#2426]
**Describe what scenario you think is uncovered by the existing examples/articles**
https://riverpod.dev/docs/concepts/reading
<img width="972" alt="Screenshot 2023-04-04 at 1 27 07 PM" src="https://user-images.githubusercontent.com/57593530/229912506-7daab49c-cd92-4877-9499-a7c1477754ef.png">

**Describe why existing examples/articles do not cover this case**
Section "Reading a Provider" doesn't cover case of using a state derived from `ref.watch` inside the callback.
The screenshot I attached above says that the code below is bad:
```dart
onPressed: () {
  final value = ref.watch(provider);
},
```
But it doesn't explain why approach below is bad:
```dart
Widget build(BuildContext context, WidgetRef ref) {
  final value = ref.watch(provider);

  return TextButton(
    onPressed: () {
      final product = value * 2; // value can be outdated if user pressed button fast
      ref.read(provider.notifier).state = product;
    },
  );
}
```

**Additional context**

<details>

<summary> Code sample to illustrate the problem (Press Test button) </summary>

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

final inProgressPod = StateProvider<bool>(
  (ref) {
    ref.listenSelf((prev, curr) {
      print('$time - (listenSelf): $curr');
    });

    return false;
  },
);

void main() => runApp(const ProviderScope(child: MyApp()));

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

GlobalKey _key = GlobalKey();

class Home extends ConsumerWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final inProgress = ref.watch(inProgressPod);

    print('$time - (build): $inProgress');

    ref.listen(inProgressPod, (prev, curr) {
      print('$time - (listen): $curr');
    });

    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: TextButton(
              key: _key,
              onPressed: () {
                // * Option #1
                final value = inProgress;

                // * Option #2
                // final value = ref.read(inProgressPod);

                print('$time - (buy-btn): Tap $value');

                if (value) {
                  return print('$time - (buy-btn): In progress, ignore');
                }

                print('$time - (buy-btn): Start');

                ref.read(inProgressPod.notifier).state = true;
              },
              child: const Text('Buy'),
            ),
          ),
          Center(
            child: TextButton(
              onPressed: () async {
                print('$time - (test-btn): Tap');

                final position = getPosition();

                simulateTap(position);
                simulateTap(position);
              },
              child: const Text('Test'),
            ),
          ),
        ],
      ),
    );
  }
}

String get time {
  return '[${DateTime.now().toString().substring(14)}]';
}

Offset getPosition() {
  final box = _key.currentContext!.findRenderObject() as RenderBox;
  return box.localToGlobal(Offset.zero);
}

void simulateTap(Offset position) {
  WidgetsBinding.instance.handlePointerEvent(PointerDownEvent(
    pointer: 0,
    position: position,
  ));

  WidgetsBinding.instance.handlePointerEvent(PointerUpEvent(
    pointer: 0,
    position: position,
  ));
}
```

</details>

<details>

<summary> Output when using 1st option from code sample </summary>

```bash
flutter: [38:27.043261] - (test-btn): Tap
flutter: [38:27.047580] - (buy-btn): Tap false
flutter: [38:27.047810] - (buy-btn): Start
flutter: [38:27.050318] - (listenSelf): true
flutter: [38:27.050832] - (listen): true
flutter: [38:27.052381] - (buy-btn): Tap false
flutter: [38:27.052544] - (buy-btn): Start
flutter: [38:27.054045] - (build): true
```

</details>

<details>

<summary> Output when using 2nd option from code sample </summary>

```bash
flutter: [39:01.603597] - (test-btn): Tap
flutter: [39:01.608699] - (buy-btn): Tap false
flutter: [39:01.608857] - (buy-btn): Start
flutter: [39:01.610732] - (listenSelf): true
flutter: [39:01.611108] - (listen): true
flutter: [39:01.613014] - (buy-btn): Tap true
flutter: [39:01.613179] - (buy-btn): In progress, ignore
flutter: [39:01.614075] - (build): true
```

</details>

**Comment by rrousselGit** [comment]
Note that none of the example do what you're doing (using a value dereferenced from earlier and using it inside an onPressed).

Examples either invoke `ref.read(provider.notifier).update(...)` or call a custom notifier method

**Comment by eli1stark** [comment]
Yes, this is why I created this issue, to cover this specific case in the docs. That `ref.watch` updates are usually lagging compared to `ref.read` on callback if it happens fast. This is why using state derived from `ref.watch` value instead of requesting the latest snapshot via `ref.read` can lead to problems with outdated value inside `onPressed` for example. I illustrated this in 2 samples. Do you agree with this statement?

**Comment by rrousselGit** [comment]
I don't think it being in the docs makes a lot of sense.  
That's some fairly advanced and niche topic. The docs are already too complex than they should be. 

Also, it's mainly an issue because of StateProvider, but using StateProvider is generally discouraged.   
This wouldn't happen with a StateNotifier & other notifier variants, as they would have access to the current `state` property directly.

So I don't think there's a lot of value in this.

**Comment by rrousselGit** [comment]
As mentioned before, I don't see a good place to mention this that wouldn't add clutter to the docs.

Ultimately I think this is a general programming concept and not specific to Riverpod.
