### ISSUE TITLE
Add new method to ProviderScope that will reset/zap all providers

### ISSUE THREAD

**Issue by davoutuk** [rrousselGit/riverpod#2439]
Problem:
I have a web app that is built with Flutter and Riverpod.
User 'A' logs into my Flutter web app, and views some data where RiverPod providers are part of the data model.   User 'A' logs out, and the web app returns to show the authentication scree.  User 'B' then logs in.  There is a danger that user 'B' will be able to view data held by providers created during the user 'A' session  

Solution required
When the first user logs out, I would like a facility to reset/zap all RiverPod providers, perhaps something like:

   ProviderScope.clear()

Describe alternatives you've considered
I have thought about injecting a ref.watch(autenticationProvider)  link into all the other providers, so that when a new user session is started the data views are refreshed, but this seems like a very inefficient option

**Comment by rrousselGit** [comment]
This is voluntarily not a thing. It's considered anti-pattern as would often reset too many things.

The correct way to do this is to use `ref.watch` inside the providers you want to reset, such that when the user changes, those providers will reset.
