### ISSUE TITLE
[ChangeNotifierProvider] documentation and example incorrect.

### ISSUE THREAD

**Issue by Nomeleel** [rrousselGit/riverpod#2453]
Regarding the document of ChangeNotifierProvider, the content looks more like that of StateNotifierProvider.

See [ChangeNotifierProvider](https://github.com/rrousselGit/riverpod/blob/master/packages/flutter_riverpod/lib/src/change_notifier_provider/base.dart#L15-L78)
See [StateNotifierProvider](https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/state_notifier_provider/base.dart#L12-L75)

For the TodosNotifier in the example of ChangeNotifierProvider, it can be changed to the following, refer to the case in the [riverpod dev](https://docs-v2.riverpod.dev/docs/providers/change_notifier_provider).

```dart
class TodosNotifier extends ChangeNotifier {
  final todos = <Todo>[];

  void add(Todo todo) {
    todos.add(todo);
    notifyListeners();
  }

  void remove(String todoId) {
    todos.remove(todos.firstWhere((element) => element.id == todoId));
    notifyListeners();
  }

  void toggle(String todoId) {
    for (final todo in todos) {
      if (todo.id == todoId) {
        todo.completed = !todo.completed;
        notifyListeners();
      }
    }
  }
}
```

Other parts trouble the author to make changes to make it more suitable for ChangeNotifierProvider.

**Comment by docweirdo** [comment]
I was about to open an issue on the same topic. In the [documentation on riverpod.dev](https://docs-v2.riverpod.dev/docs/providers/change_notifier_provider), the same code snippet includes calls to `notifyListeners()`. But the package docs seem incorrect to me as well.

**Comment by rrousselGit** [comment]
Oopsy. Let me fix that right now.

**Comment by rrousselGit** [comment]
Done. Will be fixed on pub.dev when the next version is published

**Comment by Nomeleel** [comment]
> Oopsy. Let me fix that right now.

I think it should be deleted  [here](https://github.com/rrousselGit/riverpod/blob/master/packages/flutter_riverpod/lib/src/change_notifier_provider/base.dart#L18) to avoid confused.
```
/// This provider is used in combination with `package:state_notifier`.
```
