### ISSUE TITLE
Incorrect code generated for AutoDisposeFamilyNotifier

### ISSUE THREAD

**Issue by simc** [rrousselGit/riverpod#2461]
**Describe the bug**
The generated code for `AutoDisposeFamilyNotifier` causes the following exception:
<img width="1001" alt="Screenshot 2023-04-13 at 14 37 29" src="https://user-images.githubusercontent.com/13610195/231663557-99776463-d75f-47fa-bd08-f15405d7b801.png">

**To Reproduce**

The following code is generated:
```dart
/// See also [ViewerNotifier].
class ViewerNotifierProvider extends AutoDisposeNotifierProviderImpl<ViewerNotifier, TaskViewers> {
  /// See also [ViewerNotifier].
  ViewerNotifierProvider(
    this.arg,
  ) : super.internal(
      () => ViewerNotifier()..arg = arg,
      from: viewerNotifierProvider,
      name: r'viewerNotifierProvider',
      debugGetCreateSourceHash:
          const bool.fromEnvironment('dart.vm.product')
              ? null
              : _$viewerNotifierHash,
      dependencies: ViewerNotifierFamily._dependencies,
      allTransitiveDependencies:
          ViewerNotifierFamily._allTransitiveDependencies,
    );
// ...
```

**Expected behavior**
If I change the code so that `arg` is passed to the super constructor instead of the `ViewerNotifier` it works correctly:
```dart
/// See also [ViewerNotifier].
class ViewerNotifierProvider extends AutoDisposeNotifierProviderImpl<ViewerNotifier, TaskViewers> {
  /// See also [ViewerNotifier].
  ViewerNotifierProvider(
    this.arg,
  ) : super.internal(
      () => ViewerNotifier(),
      argument: arg,
      from: viewerNotifierProvider,
      name: r'viewerNotifierProvider',
      debugGetCreateSourceHash:
          const bool.fromEnvironment('dart.vm.product')
              ? null
              : _$viewerNotifierHash,
      dependencies: ViewerNotifierFamily._dependencies,
      allTransitiveDependencies:
          ViewerNotifierFamily._allTransitiveDependencies,
    );

// ...
```

**Comment by rrousselGit** [comment]
What's the code that triggered this?

Generated providers aren't relying on AutoDisposeFamilyNotifier. As you can see in the generated code, they use AutoDisposeNotifierProviderImpl instead which is different.

So I don't see how you ended up using AutoDisposeFamilyNotifier

**Comment by simc** [comment]
```dart
@riverpod
class ViewerNotifier extends AutoDisposeFamilyNotifier<TaskViewers, String> {
  @override
  TaskViewers build(String arg) {
    return '';
  }
}
```

riverpod_generator v2.1.6

**Comment by rrousselGit** [comment]
That's not how you're supposed to use the generator. Don't manually specify an "extends".  
Instead do:

```dart
@riverpod
class ViewerNotifier extends _$ViewerNotifier {
  @override
  TaskViewers build(String arg) {
    return TaskViewers();
  }
}
```

**Comment by rrousselGit** [comment]
The generator doesn't rely on non-generated interfaces. It generates new interfaces.

This is how it enables a family to work with any parameter:

```dart
@riverpod
class ViewerNotifier extends _$ViewerNotifier {
  @override
  TaskViewers build({required String namedParametersAreFine, String? another = 'you can use default values too!'}) {
    return TaskViewers();
  }
}
```

**Comment by simc** [comment]
Oh wow that's so cool thanks!! Don't know how I missed that in the docs 🤯

**Comment by rrousselGit** [comment]
Also, this mistake should've been caught by the riverpod_lint package

There's a warning for spotting incorrect `extends`, with a quick fix.

**Comment by gengiscb** [comment]
Why the example code show this warning "Notifiers should not have public properties/getters. Instead, all their public API should be exposed through the `state` property." with riverpod_lint  ?
```
@riverpod
class ViewerNotifier extends AutoDisposeFamilyNotifier<TaskViewers, String> {
  @override
  TaskViewers build(String arg) {
    return TaskViewers();
  }
}
```
