### ISSUE TITLE
fireImmediately for listen method

### ISSUE THREAD

**Issue by Amir-P** [rrousselGit/riverpod#2472]
Hey. In my case I have a `StateProvider` and it's value can be set before or during listening to it and I need to react to that value no matter when it's set (show a `SnackBar`). Right now it's not possible and I need to use `listenManual` which is more verbose and needs more care to use or use `read` in `initState` to get it's current value and `listen` in the build for later updates. It would be much cleaner to handle these cases with `fireImmediately` in `Ref/WidgetRef.listen`. Is there any reason for not having it? 

Sample:

```dart
void main() {
  runApp(ProviderScope(
    child: MyWidget(),
  ));
}

final fooProvider = StateProvider<bool>((_) => false);

class MyWidget extends ConsumerWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.listen(fooProvider, (a, b) {
      // it doesn't get called unless provider's value gets changed during the lifecycle of this widget.
      print('a: $a, b: $b');
    });
    return const Placeholder();
  }
}
```

**Comment by rrousselGit** [comment]
This cannot be here, for the simple fact that listeners may get re-added when the widget rebuilds.

If you want `fireImmediately`, use `ref.listenManual`
