### ISSUE TITLE
how to invalidate the entire container 

### ISSUE THREAD

**Issue by maxzod** [rrousselGit/riverpod#2474]
**Describe what scenario you think is uncovered by the existing examples/articles**
instead of ref.invalidate(foo) and ref.invalidate(ba)
i might forgot to add one or more providers to dispose i need some thing like ref.invalidateAll() 
 
**Additional context**
after a user sign out i need to reset every thing from the container !

**Comment by rrousselGit** [comment]
You don't. There's no plan to support such a thing.

You're supposed to only invalidate what changed.
