### ISSUE TITLE
riverpod annotation warning

### ISSUE THREAD

**Issue by agufagit** [rrousselGit/riverpod#2479]
**Describe the bug**
a warning "The riverpod_generator package does not support ChangeNotifier values. dart(unsupported_provider_value)
GoRouter router(ProviderRef<GoRouter> ref)" displayed

**To Reproduce**
```dart
@Riverpod(keepAlive: true)
GoRouter router(RouterRef ref) {
  return GoRouter(...)
```
warning will display under `router(...)`

**Expected behavior**
no warning

**Comment by moxiaov587** [comment]
In version 2.3.5, you can

```dart
@riverpod
Raw<GoRouter> router(RouterRef ref) {
  final GoRouter router = GoRouter(...);
  ref.onDispose(router.dispose);
  return router;
}

```
See [here](https://twitter.com/remi_rousselet/status/1648295952334159875).

**Comment by rrousselGit** [comment]
This was answered, so I'll close this

**Comment by utamori** [comment]
In version 9, GoRouter no longer extends ChangeNotifier, so there is no need to use Raw.

https://pub.dev/packages/go_router/changelog#900
