### ISSUE TITLE
Can't resolve all transitive dependencies for providers due to missing imports

### ISSUE THREAD

**Issue by Reprevise** [rrousselGit/riverpod#2490]
**Describe the bug**
Let's say we have three providers: `aValue`, `bValue`, and `cValue` where `bValue` depends on `aValue`, and `cValue` depends on `bValue`.

The chain looks like `aValue <-- bValue <-- cValue`

If the `cValue` provider doesn't import the file that `aValue` provider is defined in, then the generated file returns an error because `aValueProvider` is defined in the transitive dependencies of `cValueProvider` but since there's no import, it cannot be resolved.

**To Reproduce**
Repository here: https://github.com/Reprevise/riverpod_transitive_dep_issue

**Expected behavior**
Not sure what I'd recommend here as it seems a list of transitive dependencies is required but it's not like the generator can add imports in `part` files.

**Comment by rrousselGit** [comment]
Oopsy! 

Looks like it's been around for a bit of time, so it's probably not too critical.
You can get around it by importing the necessary providers if you can.

I'll likely bundle a proper fix for this in the upcoming 3.0

If this gets a decent amount of :+1:  I can also make a quick-fix for this in 2.0 too. Although for now, I'd prefer not to.

**Comment by Reprevise** [comment]
Would love to see a patch for this in 2.0 for what it's worth.

**Comment by rrousselGit** [comment]
I guess I'll fix it in 2.0.0 then :P
