### ISSUE TITLE
codegen fails when types have prefixes

### ISSUE THREAD

**Issue by RandalSchwartz** [rrousselGit/riverpod#2491]
**Describe the bug**
codegen picks up the unprefixed name for types, which of course fails in the generated code

**To Reproduce**
This fails compilation:
```
import 'dart:math' as math;

import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'd_ba690e95_3da5_4ba0_97c1_05d0c375b936.g.dart';

void main(List<String> arguments) {
  print('Hello world from d_ba690e95_3da5_4ba0_97c1_05d0c375b936!');
}

@riverpod
math.Point origin(OriginRef ref) {
  return const math.Point(0, 0);
}

```
The generated file contains `Point`, not `math.Point`, which is of course missing.

**Expected behavior**
The generated code would also use `math.Point`.

**Comment by rrousselGit** [comment]
That's always been the case. Prefixes aren't supported



I have no plan to support them before Metaprogramming
