### ISSUE TITLE
[linter] avoid_manual_providers_as_generated_provider_dependency

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/riverpod#2495]
I sometimes use an abstract class to create a collection of providers. Doing this will result in a linter error `avoid_manual_providers_as_generated_provider_dependency`  for `Bar._foo2`.
Adding `@ProviderFor(_foo)` around  `ProviderCollection.foo` does not resolve the issue.

```dart
@riverpod
bool _foo(_FooRef ref) {
  return true;
}

abstract class ProviderCollection {
  static final foo = _fooProvider;
}

@riverpod
class Bar extends _$Bar {
  late final _foo = ref.watch(_fooProvider);
  late final _foo2 = ref.watch(ProviderCollection.foo);

  @override
  Bar build() => this;
}
```

![image](https://user-images.githubusercontent.com/655296/234280919-8544ab9f-bc8f-48a5-bf7a-660b15eb6869.png)

**Comment by rrousselGit** [comment]
That's expected.

That `static final foo = _fooProvider ` is not something supported.

If you want providers as static properties of abstract classes, that'll have to wait until Metaprogramming.
