### ISSUE TITLE
Data caching not working if regular provider calls keep alive provider

### ISSUE THREAD

**Issue by johanlantz** [rrousselGit/riverpod#2498]
This might be due to me having the wrong expectations but here it goes anyway. Minimal reproducible example attached.

I am reading daily data from a repository, if I am looking at the current day (today) then I do not want to use riverpod data caching because the data changes in realtime. However if the date selected is in the past, I want to use riverpod caching because that data is static and I benefit from the caching.

So, to solve this I have a Provider with a condition. It checks if the currently selected day is today and if then, it forwards the call to the Provider that just uses @riverpod while if the currently selected day is in the past, it forwards the call to a provider using @Riverpod(keepAlive: true).

The issue is that this does not work. Even if the Provider marked with @Riverpod(keepAlive: true) is called for a date I have already watched, the repository is called. If I mark the top level provider with @Riverpod(keepAlive: true) it does work as expected and the repository is only called the first time but I can't do that because I want the specific behaviour if we are looking at todays date.

I have created a minimal example that I attach. It reproduces what I was hoping to do. 

My expectation is that if I start on 2023-04-26 and move two days back to 2023-04-24 and then one day forward again to 2023-04-25, then the repository should not be called for 2023-04-25 because I already fetched the data for that date when I moved two days back.

[riverpod_test.zip](https://github.com/rrousselGit/riverpod/files/11335458/riverpod_test.zip)

**Comment by rrousselGit** [comment]
> My expectation is that if I start on 2023-04-26 and move two days back to 2023-04-24 and then one day forward again to 2023-04-25, then the repository should not be called for 2023-04-25 because I already fetched the data for that date when I moved two days back.

Why would that be the behavior?

You're only keeping the state of the current day. So days other than today wouldn't be kept in memory if they aren't used anymore, and therefore re-visiting those pages would refetch them.

Am I missing something?

**Comment by johanlantz** [comment]
Thanks @rrousselGit 

Much more likely that I am missing something. Let me see if I can add something to clarify. 

In a simpler scenario similar to the attached example but without the extra steps, I can read directly from a repo like this:
```
@riverpod
Future<SomeData> fetchDataForDate(
    FetchDataForDateRef ref, DateTime date) async {
  return ref.watch(someRepositoryProvider).fetchData();
}
```

For each date, the repo is called. No caching and we get the 1 second delay

On the other hand if I use keepAlive: true:
```
@Riverpod(keepAlive: true)
Future<SomeData> fetchDataForDate(
    FetchDataForDateRef ref, DateTime date) async {
  return ref.watch(someRepositoryProvider).fetchData();
}
```

Then if I have previously fetched data for that date, it is already cached by riverpod, the repo is not called, there is no delay and the data is instantly available. This all works great.

In my sample code, I was trying to do a combination of these two behaviours depending on if it is today or a day in the past. So the widget always would use the same provider but internally that provider would decide if it should use _fetchDataForDateWithoutCache() or _fetchDataForDateWithCache().

It is completely possible that I am missing something fundamental here but it did not seem that unreasonable?

```
@riverpod
Future<SomeData> _fetchDataForDateWithoutCache(
    FutureProviderRef ref, DateTime date) async {
  return ref.watch(someRepositoryProvider).fetchData();
}

@Riverpod(keepAlive: true)
Future<SomeData> _fetchDataForDateWithCache(
    FutureProviderRef ref, DateTime date) async {
  return ref.watch(someRepositoryProvider).fetchData();
}

@riverpod
Future<SomeData> _dataForDate(FutureProviderRef ref, DateTime date) async {
  if (date.isToday()) {
    return _fetchDataForDateWithoutCache(ref, date);
  } else {
    return _fetchDataForDateWithCache(ref, date);
  }
}

@riverpod
Future<SomeData> fetchDataForDate(
    FetchDataForDateRef ref, DateTime date) async {
  return await ref.watch(_dataForDateProvider(date).future);
}
```

**Comment by rrousselGit** [comment]
> I was thinking that the _fetchDataForDateWithCacheProvider would always be kept alive for the lifetime of the application, internally caching all the repository responses but I might be completely off.

It should be. I'm pretty sure that if you put a print in it, it won't be re-executed for the same date.

Also do note that you don't need that many providers for this. You can do:

```dart
@riverpod
Future<SomeData> _fetchDataForDate(
    FutureProviderRef ref, DateTime date) async {
  if (data.isToday) ref.keepAlive();
  return ref.watch(someRepositoryProvider).fetchData();
}
```

and remove all the other providers.

**Comment by johanlantz** [comment]
Fantastic suggestion. Helped me understand a bit more about how things work behind the scenes. Lot's to learn still.

Lunch's on me and big thanks again for your support and hard work, it is highly appreciated.
