### ISSUE TITLE
[riverpod_generator] Request: support generate StateProvider.

### ISSUE THREAD

**Issue by Nomeleel** [rrousselGit/riverpod#2504]
**Is your feature request related to a problem? Please describe.**
When I tried code generation to replace the following code, I found that StateProvider is not supported.
```dart
final productSortTypeProvider = StateProvider<ProductSortType>(
  // We return the default sort type, here name.
  (ref) => ProductSortType.name,
);
```
If I don't use code generation, it's easy to trigger [avoid_manual_providers_as_generated_provider_dependency](https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_lint#avoid_manual_providers_as_generated_provider_dependency) lint when using this provider.

**Describe the solution you'd like**
Similar to [Raw](https://github.com/rrousselGit/riverpod/pull/2473), with [State] mean want to use StateProvider.

```dart
@riverpod
State<Foo> foo(FooRef ref) => Foo();
```

Future or Stream must ignore [State]

***Bad***
```dart
@riverpod
State<Future<Foo>> foo(FooRef ref) async => Foo();

@riverpod
State<Stream<Foo>> foo(FooRef ref) async* {
  yield Foo();
}
```

**Describe alternatives you've considered**
Actively add the State(or others) suffix to indicate that you want to use StateProvider.

```dart
@riverpod
Foo fooState(FooStateRef ref) => Foo();
```

**Comment by rrousselGit** [comment]
I'd suggest refactoring to a more conventional "notifier" approach (so making a class).

**Comment by Nomeleel** [comment]
> I'd suggest refactoring to a more conventional "notifier" approach (so making a class).

Thank you for your reply, I understand.

**Comment by nilsreichardt** [comment]
> I'd suggest refactoring to a more conventional "notifier" approach (so making a class).

Maybe it's worth adding this sentence to the info box at https://docs-v2.riverpod.dev/docs/providers/state_notifier_provider

**Comment by Reprevise** [comment]
Curious as to why there are no plans to support generating a `StateProvider`. I understand that you want people to migrate to `Notifier`s however sometimes they're just not needed and it causes unnecessary boilerplate code. Not being able to generate a `StateProvider` is preventing me from using riverpod_lint effectively as in almost every provider I have depends on an un-generated `StateProvider` which makes the annotated dependency lint break as well as it causes another lint itself.

**Comment by rrousselGit** [comment]
For now, I'm looking at reducing the API surface.
The code-generator is voluntarily more opinionated to reduce the overabundance of possibilities; which is a common complaint.

StateProvider is only here to slightly reduce the number of lines typed. You can do everything with a normal Notifier.


Combined with the fact that StateProvider is often discouraged (cf its docs), it's not a priority for me.
If it's truly necessary, we can always add something back in the future.
