### ISSUE TITLE
There's no explanation for how the "Why Immutability" page directly relates to Riverpod

### ISSUE THREAD

**Issue by kwilliams3** [rrousselGit/riverpod#2521]
**Describe what scenario you think is uncovered by the existing examples/articles**
The concepts within the "Why Immutability" page are entirely fascinating! However, there is no explanation for how this directly relates to Riverpod. It would be nice if we could explain the purpose for discussing immutability, as it relates to Riverpod. Otherwise, it may appear to newcomers as an unrelated discussion about an arbitrary best practice within Dart.

**Describe why existing examples/articles do not cover this case**
There doesn't appear to be any contextual explanation for the "Why Immutability" page being present among Riverpod documentation.

**Additional context**

**Comment by tadaspetra** [comment]
I really like this page too as it gives a more concrete reason why you should *most of the time* not use ChangeNotifierProvider. I like the idea of keeping this article general, because it's about immutability in general, but maybe in the [ChangeNotifierProvider](https://docs-v2.riverpod.dev/docs/providers/change_notifier_provider) page, where it says to use `NotifierProvider` or the sentence below we could link to the Why Immutability page, for people to understand more deeply why they should or shouldn't use it

**Comment by kwilliams3** [comment]
@tadaspetra I like the idea of linking Why Immutability inside the NotifierProvider. I think we should also provide context on the relationship from within the Why Immutability page itself as well in case someone starts reading that page before they read about the NotiferProvider.

Is there any other reason why immutability is being discussed within Riverpod's documentation? I'd be happy to formally write something for the Why Immutability page that gives more context. However, I'm pretty new to Riverpod myself, so I'm not sure how immutability directly relates to the values that Riverpod shares.

**Comment by rrousselGit** [comment]
Riverpod generally recommends immutability. It enables better tooling and makes certain optimizations simpler.

For example, `provider.select` assumes that the returned value is immutable. If returning a mutable object, select won't cause the object to rebuild when said object is mutated.

Using mutable state on a notifier is also necessary if you want ref.listen's "previous" to work. Using mutable state, the "previous" and "next" values on change could end-up being the same if an object is mutated.

Also: It's not implemented yet, but immutability would empower the upcoming state devtool too. Through immutability, it would be possible to implement what we call "time travel" during a state inspection.

**Comment by kwilliams3** [comment]
> Riverpod generally recommends immutability. It enables better tooling and makes certain optimizations simpler.
> 
> For example, `provider.select` assumes that the returned value is immutable. If returning a mutable object, select won't cause the object to rebuild when said object is mutated.
> 
> Using mutable state on a notifier is also necessary if you want ref.listen's "previous" to work. Using mutable state, the "previous" and "next" values on change could end-up being the same if an object is mutated.
> 
> Also: It's not implemented yet, but immutability would empower the upcoming state devtool too. Through immutability, it would be possible to implement what we call "time travel" during a state inspection.

I'm almost positive this question is a bit naive, but I'd like to better understand this concept. Should we strive for immutability everywhere? Should every object be immutable, or are there limited exceptions? It might be important for us to provide the answer to this question in the Why Immutability page so people understand the degree to which they should strive for immutability.

**Comment by rrousselGit** [comment]
Ideally use immutability everywhere, yes.

You might want to use mutability in specific cases for possible performance optimization, after careful benchmarking to make sure it's worth it.

**Comment by rrousselGit** [comment]
There's https://docs-v2.riverpod.dev/docs/concepts/why_immutability

It will be moved out of the "concepts" in the future, but it is here
