### ISSUE TITLE
[riverpod_generator] Ability to generate scoped `[Async]Notifier` providers

### ISSUE THREAD

**Issue by Reprevise** [rrousselGit/riverpod#2531]
**Is your feature request related to a problem? Please describe.**
I have a `Notifier` class that can only be scoped and the generated code is throwing a compile-time error because it doesn't match the `_createNotifier` type signature as my `TimerNotifier` takes a named parameter.

**Describe the solution you'd like**
I want a way for the generator to write `() => throw UnimplemtedError()` or similar to denote that this provider must be scoped.

**Describe alternatives you've considered**
In theory I could just _not_ use a generated provider however this provider is depended on by other generated providers.

**Additional context**

Here's my `TimerNotifier` class:

```dart
@Riverpod(keepAlive: true, dependencies: [])
class TimerNotifier extends _$TimerNotifier {
  TimerNotifier({required this.initial});

  final int initial;

  @override
  int build() {
    // ...
  }

  void update(int newTo) => state = newTo;
}
```

**Comment by rrousselGit** [comment]
You can throw inside `build`.

**Comment by Reprevise** [comment]
@rrousselGit Yes, however I need `build` implemented so I can't just throw inside the `build` method. 

This is how it's used:

`timerNotifierProvider.overrideWith(() => TimerNotifier(initial: 180))`

**Comment by rrousselGit** [comment]
You can also do:

```dart
class TimerNotifier extends _$TimerNotifier {
  factory TimerNotifier() => throw UnimplementedError();

  TimerNotifier.withInitial({required this.initial});
...
```

**Comment by FireJuun** [comment]
> You can also do:
> 
> ```dart
> class TimerNotifier extends _$TimerNotifier {
>   factory TimerNotifier() => throw UnimplementedError();
> 
>   TimerNotifier.withInitial({required this.initial});
> ...
> ```

@rrousselGit, do you have a slightly longer example this within Riverpod annotations? Would that also include the factory constructor?

**Comment by rrousselGit** [comment]
This was answered above, so closing https://github.com/rrousselGit/riverpod/issues/2531#issuecomment-1536436218
