### ISSUE TITLE
`invalidate()` & `refresh()` throws if used in `dispose` method of a widget that does not watch that provider.

### ISSUE THREAD

**Issue by hasanmhallak** [rrousselGit/riverpod#2538]
When using `invalidate()` or `refresh()` on a Provider in a `StatefullWidget` in which its `WidgetRef` does not register a listener (watch that provider) will throws `Looking up a deactivated widget's ancestor is unsafe.` 

Even if you use a `Consumer` will still throws. The only way to get this to work if the same `WidgetRef` instance used to `watch` a provider calls `invalidate` only then things work as expected.

Note:
I can not count on `autoDispose` as at some point during  one  flow the provider will not be watched but at one page, but must be invalidate when the user exit that particular flow completely.

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final numberProvider = StateNotifierProvider<NumberNotifier, int>((ref) {
  ref.onDispose(() {
    print('disposing');
  });

  return NumberNotifier();
});

class NumberNotifier extends StateNotifier<int> {
  NumberNotifier() : super(0);

  void update() {
    state = state + 1;
  }
}

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, ref) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerStatefulWidget {
  const MyHomePage({super.key});

  @override
  ConsumerState<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends ConsumerState<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Text(
          ref.watch(numberProvider).toString(),
          style: Theme.of(context).textTheme.headlineMedium,
        ),
      ),
      floatingActionButton: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          FloatingActionButton(
            heroTag: 'Increment',
            onPressed: ref.read(numberProvider.notifier).update,
            child: const Icon(Icons.add),
          ),
          const SizedBox(width: 10),
          FloatingActionButton(
            heroTag: 'go',
            onPressed: () {
              Navigator.of(context)
                  .push(MaterialPageRoute(builder: (_) => const NextPage()));
            },
            child: const Icon(Icons.arrow_forward_ios_outlined),
          ),
        ],
      ),
    );
  }
}

class NextPage extends ConsumerStatefulWidget {
  const NextPage({super.key});

  @override
  ConsumerState<NextPage> createState() => _NextPageState();
}

class _NextPageState extends ConsumerState<NextPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const Body(),
      floatingActionButton: const BackFab(),
    );
  }
}

class BackFab extends ConsumerStatefulWidget {
  const BackFab({
    super.key,
  });

  @override
  ConsumerState<BackFab> createState() => _BackFabState();
}

class _BackFabState extends ConsumerState<BackFab> {
  // @override
  // void dispose() {
  //   ref.invalidate(numberProvider); // <------------- here
  //   super.dispose();
  // }

  @override
  Widget build(BuildContext context) {
    // ref.watch(numberProvider); // <------------- here
    return FloatingActionButton(
      heroTag: 'back',
      onPressed: () {
        Navigator.of(context).pop();
      },
      child: const Icon(Icons.arrow_back_ios),
    );
  }
}

class Body extends ConsumerStatefulWidget {
  const Body({
    super.key,
  });

  @override
  ConsumerState<Body> createState() => _BodyState();
}

class _BodyState extends ConsumerState<Body> {
  // @override
  // void dispose() {
  //   ref.invalidate(
  //       numberProvider); // <------------- working fine here as there is a listener.
  //   super.dispose();
  // }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(
        '${ref.watch(numberProvider)}', // <-------------  listener.
      ),
    );


    /*
     return Center(
      child: Consumer(builder: (context, r, _) {
        return Text(
          '${r.watch(numberProvider)}', // <-------------  this will also throws. you must the widgetRef
        );
      }),

    */
  }
}
```

**Expected behavior**
Should be able to call `invalidate` or `refresh` whether there is a listener or not.

**Comment by rrousselGit** [comment]
Using ref inside `onDispose` is generally not allowed. Especially ref.invalidate/refresh.   
The fact that sometimes you do not get an error is the bug here. It should never work.

I'll make separate issues to:
- investigate why sometimes there's no error
- improve the error message
- document why this is not allowed
- add a warning if ref is used inside State.dispose.

**Comment by hasanmhallak** [comment]
@rrousselGit so how can I dispose a provider if I cant use ref in dispose?

**Comment by hasanmhallak** [comment]
@rrousselGit you mean I should invalidate the provider in the `onWillPop` maybe?
The problem is i saw a lot of issue about this call back not been triggered when the user press the device back button.

**Comment by rrousselGit** [comment]
onWillPop could be a good place. 

But honestly you probably should be using autoDispose

**Comment by rrousselGit** [comment]
You may also want to do it next to your `pop()`

**Comment by hasanmhallak** [comment]
@rrousselGit I love autoDispose but the problem is the I have a form of like 6 pages and the user can go forward and backward as he pleased while I should maintain the data he provided. 

The only way to use autoDispose is to add a `consumer` at the first form with nothing but `SizedBox.shrink` to keep a listener registered during the whole form thing. But I find weird to do this as it looks like a hack.

**Comment by rrousselGit** [comment]
Not sure why a SizedBox.shrink is necessary here.

Just ref.watch your provider inside a widget that's mounted during the entire form flow.

**Comment by hasanmhallak** [comment]
@rrousselGit silly me, I thought the tree would be rebuilt, but that's not the case if the tree was not showing on the screen.
Thanks for the help.

**Comment by hasanmhallak** [comment]
I never thought of this. it is actually very neat!.  thanks again.
