### ISSUE TITLE
Improve error message on error because using `WidgetRef` inside `State.dispose`

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2541]
related to https://github.com/rrousselGit/riverpod/issues/2538

**Comment by rrousselGit** [comment]
This was done in a previous release. The current message is:

> Cannot use "ref" after the widget was disposed.

**Comment by Faiz-rhm** [comment]
I am facing the same issue, and still not found what is the main cause.

**Comment by hasanmhallak** [comment]
@Faiz-rhm you can manually dispose a provider using `ProviderContainer` like this:

```dart
  late final ProviderContainer _providerContainer;

  @override
  void initState() {
    _providerContainer = ProviderScope.containerOf(context, listen: false);
    super.initState();
  }

  @override
  void dispose() {
    _providerContainer
      .invalidate(provider);
    super.dispose();
  }
```
