### ISSUE TITLE
riverpod_lint cannot be added with Flutter 3.3

### ISSUE THREAD

**Issue by Markus43** [rrousselGit/riverpod#2548]
I have a project where I am stuck with flutter 3.3.10, and I cannot add riverpod_lint in that project. I would like to be able to use riverpod_lint also in that project ;-)

**To Reproduce**
Here is the VS code output when I try to add riverpod_lint to a fresh counter example project:

[test_rpl_33] flutter pub add riverpod_lint --dev
The current Dart SDK version is 2.18.6.

Because riverpod_lint <1.0.1 depends on custom_lint_builder ^0.2.7 and riverpod_lint >=1.1.4 <1.1.7 depends on custom_lint_builder ^0.3.2, riverpod_lint <1.0.1-∞ or >=1.1.4 <1.1.7-∞ requires custom_lint_builder ^0.2.7 or ^0.3.2.
And because riverpod_lint >=1.1.3 <1.1.4 depends on custom_lint_builder ^0.3.1 and riverpod_lint >=1.1.0 <1.1.3 depends on custom_lint_builder ^0.2.12, riverpod_lint <1.0.1-∞ or >=1.1.0 <1.1.7-∞ requires custom_lint_builder >=0.2.7 <0.3.0 or >=0.3.1 <0.4.0.
And because riverpod_lint >=1.0.1 <1.1.0 depends on custom_lint_builder ^0.2.9 and custom_lint_builder >=0.2.0 <0.2.11 depends on analyzer >=5.4.0 <5.5.0, riverpod_lint <1.1.7 requires analyzer >=5.4.0 <5.5.0 or custom_lint_builder >=0.2.11 <0.3.0 or >=0.3.1 <0.4.0.
And because analyzer >=5.3.1 <5.7.1 depends on collection ^1.17.0 and every version of flutter from sdk depends on collection 1.16.0, if riverpod_lint <1.1.7 and flutter from sdk then custom_lint_builder >=0.2.11 <0.3.0 or >=0.3.1 <0.4.0.
And because riverpod_lint >=1.1.7 depends on custom_lint_builder >=0.2.11 which requires SDK version >=2.19.0 <3.0.0, flutter from sdk is incompatible with riverpod_lint.
So, because test_rpl_33 depends on both flutter from sdk and riverpod_lint any, version solving failed.
pub finished with exit code 65
exit code 65

**Comment by rrousselGit** [comment]
On it

**Comment by Markus43** [comment]
Thanks for the quick response! Unfortunately, the issue is not fixed. Isn't the issue that custom_lint, custom_lint_builder and custom_lint_core all require SDK version >=2.19.0 <3.0.0 ?
=>Dart 2.19.0 means flutter 3.7.0, and this issue is about making the plugins run with flutter 3.3 :-)
=>This would have to be 2.18 for dart 3.3 .

Here my log again for completeness:
C:\dev\flutter_test\rpl_test>flutter pub add riverpod_lint --dev
The current Dart SDK version is 2.18.6.

Because riverpod_lint <1.0.1 depends on custom_lint_builder ^0.2.7 and riverpod_lint >=1.1.7 <1.3.2 depends on custom_lint_builder ^0.3.3, riverpod_lint <1.0.1-∞ or >=1.1.7 <1.3.2-∞ requires custom_lint_builder ^0.2.7 or ^0.3.3.
And because riverpod_lint >=1.1.4 <1.1.7 depends on custom_lint_builder ^0.3.2 and riverpod_lint >=1.1.3 <1.1.4 depends on custom_lint_builder ^0.3.1, riverpod_lint <1.0.1-∞ or >=1.1.3 <1.3.2-∞ requires custom_lint_builder ^0.2.7 or >=0.3.1 <0.4.0.
And because riverpod_lint >=1.1.0 <1.1.3 depends on custom_lint_builder ^0.2.12 and riverpod_lint >=1.0.1 <1.1.0 depends on custom_lint_builder ^0.2.9, riverpod_lint <1.3.2 requires custom_lint_builder >=0.2.7 <0.3.0 or >=0.3.1 <0.4.0.
Because custom_lint_builder >=0.2.0 <0.2.11 depends on analyzer >=5.4.0 <5.5.0 which depends on collection ^1.17.0, custom_lint_builder >=0.2.0 <0.2.11 requires collection ^1.17.0.
Thus, riverpod_lint <1.3.2 requires collection ^1.17.0 or custom_lint_builder >=0.2.11 <0.3.0 or >=0.3.1 <0.4.0.
And because every version of flutter from sdk depends on collection 1.16.0, if riverpod_lint <1.3.2 and flutter from sdk then custom_lint_builder >=0.2.11 <0.3.0 or >=0.3.1 <0.4.0.
And because riverpod_lint >=1.3.2 depends on custom_lint_builder >=0.2.11 which requires SDK version >=2.19.0 <3.0.0, flutter from sdk is incompatible with riverpod_lint.
So, because rpl_test depends on both flutter from sdk and riverpod_lint any, version solving failed.
pub finished with exit code 65

C:\dev\flutter_test\rpl_test>

**Comment by rrousselGit** [comment]
Oh I thought you wanted the latest version of Flutter

Older SDK versions won't be supported. Feel free to uninstall riverpod_lint or pick a lower compatible version if any.
