### ISSUE TITLE
How to return error or loading states for function annotated with @riverpod?

### ISSUE THREAD

**Issue by jeremiahwstan** [rrousselGit/riverpod#2559]
Hi, I've been trying to find example on how to return error or loading states for function annotated with @riverpod [1]. I can see that the provider's when of the github example is handling the different states (error, loading, and data) as well [2].

Hope someone can help me with this. Thanks!

[1] https://github.com/rrousselGit/riverpod/blob/b83441dbb9841d3693dd80ffdb6300211696612c/examples/pub/lib/detail.dart#L29-L39

[2]
https://github.com/rrousselGit/riverpod/blob/b83441dbb9841d3693dd80ffdb6300211696612c/examples/pub/lib/detail.dart#L110-L123

**Comment by jeremiahwstan** [comment]
Hi @rrousselGit, do you know how to resolve this issue?

**Comment by rrousselGit** [comment]
To return error states, have the function throw. The error will be caught and sent as an AsyncError to the UI.

Loading states are automatically handled by Riverpod. You have nothing to do. If your function returns a Future, a loading state will automatically be emitted until the future resolves.

**Comment by jeremiahwstan** [comment]
it works, thanks for the clarification!
