### ISSUE TITLE
How to replace update() of LocatorMixin?

### ISSUE THREAD

**Issue by negitorogithub** [rrousselGit/riverpod#256]
Hi.

I know I can't use LocatorMixin, and should use constructor instead of initState().
However, I wasn't able to replace update() to ref.watch(), because a constructor of controller(which extends StateNotifier<T>) are sometimes called more than once if I use ref.watch().
Could you tell me how to replace update() of LocatorMixin?

Thank you.

**Comment by negitorogithub** [comment]
I've found that listening to a stream in the constructor of controller usually can replace update() of LocatorMixin.

**Comment by rrousselGit** [comment]
Riverpod now has `ref.listen` which would typically be used for this
