### ISSUE TITLE
Add type for Error to AsyncValue

### ISSUE THREAD

**Issue by MiniSuperDev** [rrousselGit/riverpod#2573]
Hello,
A lot of people use an `Either` or `Result` type from different libraries or created by them to have functional error handling and normally this Error type is a union class, and for this Error class we have localizations and widgets for each type.

I think it would be a good idea if you allowed to assign the type of the error, which can be possible with pattern matching, and in case of not, the error should be `unknownError`

```dart
class AsyncValue<T, E> {
  // when method
  R whenOrNull<R>({
    //...
    required R Function(T value) data,
    required R Function() loading,
    required R Function(E error) error,
    required R Function(Object error, StackTrace stackTrace) unknownError,
  }){
    // something like this
    switch (asyncValue) {
      case AsyncData(:value?) => data(value),
      case AsyncLoading() => loading(),  
      case AsyncError(error: E error) => error(error),
      case AsyncError() => unknowError(error, stackTrace),
    }
  }
}
```

Widget build
```dart
  value.when(
    data: buildDateWidget,
    loading: buildLoadingjwidget,
    error: buildErrorWithLocalizationsWidget,
    unknownError: buildUnknownErrorWidget,
  );
```

This would allow the widgets or listeners to have the type of the error without having to cast

```
AsyncValue<Model, AppError>
```

In case of not having any specific class of error, Object would be assigned

```
AsyncValue<Model, Object>
```

Another alternative would be to remove `unknownError` and leave only error, and throw an exception in case no matches are found.

```dart
class AsyncValue<T, E> {
  // when method
  R whenOrNull<R>({
    //...
    required R Function(T value) data,
    required R Function() loading,
    required R Function(E error) error,
    required R Function(Object error, StackTrace stackTrace) unknownError,
  }){
    // something like this
    switch (asyncValue) {
      case AsyncData(:value?) => data(value),
      case AsyncLoading() => loading(),  
      case AsyncError(error: E error) => error(error),
      case AsyncError() =>throw NoErrorMatchingException(),
    }
  }
}
```

Widget build
```dart
  value.when(
    data: buildDateWidget,
    loading: buildLoadingjwidget,
    error: buildErrorWithLocalizationsWidget,
  );
```

**Comment by rrousselGit** [comment]
Throwing on un matching error would be unreasonable. That goes directly against the purpose of AsyncValue.

As such we can't type AsyncValue.error as the generic error type and would have to type it as Object? still.

So the generic would only be used for "when".
But "when" is doomed to disappear now that we have Dart 3.


A Riverpod version with Dart 3 feature will soon land.
You should then be able to write:

```dart
AsyncValue<int> asyncValue;
switch (asyncValue) {
  case AsyncData(:final value): print(value);
  case AsyncError(:AppError error): print('my error');
  case AsyncError(): print('unknown error') 
  case AsyncLoading(): print('loading')
}
```

In which case the generic has no effect.


Considering how this proposal would be heavily breaking, I'm not sure that's valuable.

**Comment by rrousselGit** [comment]
Closing as this isn't planned now that we have patterns
