### ISSUE TITLE
Add AsyncInitial and AsyncValue.initial to AsyncValue

### ISSUE THREAD

**Issue by MiniSuperDev** [rrousselGit/riverpod#2577]
Hi, is a very common case for a `AsyncNotifier` is pressing a button that performs an action, such as submit a form, auth, a crud operation, etc. it always has an initial state, which is different from loading, in which the action hasn't been performed yet.
 
 Currently a common solution is to set the data type to nullable, or use an union type like Option or similar. 
 https://github.com/rrousselGit/riverpod/discussions/985#discussioncomment-1898820
 
 Without AsyncInitial
 
 ```dart
 @riverpod
class Submit extends _$Submit {
  @override
  FutureOr<bool?> build() {
    return null;
  }

  Future<void> submit(String data) async {
    state = const AsyncValue.loading();
    state = AsyncValue.guard(() => ref.read(someService).someMethod(data))
  }
}

void _build(AsyncValue<bool?> value) {
  value.when(
    data: (data) {
      switch (data) {
        case null:
          // initial;
          break;
        case bool():
          // data
      }
    },
    loading: () {},
    error: (err, stack) {},
  );
}
 ```
 
 With AsyncInitial
 
 ```dart
 @riverpod
class Submit extends _$Submit {
  @override
  FutureOr<bool> build() {
    return AsyncValue.initial();
  }

  Future<void> submit(String data) async {
    state = const AsyncValue.loading();
    state = AsyncValue.guard(() => ref.read(someService).someMethod(data))
  }
}

void _build(AsyncValue<bool?> value) {
  value.when(
    initial: () {},
    data: (data) {},
    loading: () {},
    error: (err, stack) {},
  );
}
 ```
 
Apart from reducing the boilerplate to know if it is in an initial state, it is much easier to understand that the state is initial and the wanted data type is `bool` instead of `bool?` of `Option<bool>`, since being nullable or option is not very clear.

**Comment by rrousselGit** [comment]
This has been requested before, but it makes no sense. The issue is here:

> ```dart
>  @override
>  FutureOr<bool> build() {
>    return AsyncValue.initial();
>  }
> ```

That doesn't work. You'd get a compilation error. An AsyncValue is not a bool.

An "initial" status is not something logical with AsyncValue. Providers are always initialized when read. That "initial" status is something you made up on your own for your personal logic. It's not a legitimate life-cycle for providers.


To begin with, I would discourage from returning `null` inside `build` like you're doing. If you don't want to initialize a provider yet, don't read it.

You're free to do:

```dart
Widget build(context) {
  AsyncValue<T>? value;
  // Only watch the provider if it was clicked.
  if (clicked) value = ref.watch(provider);
}
```

This makes more sense. In that case, `value == null` or  `!clicked` would be your "initial".

**Comment by MiniSuperDev** [comment]
@rrousselGit Hi

> That doesn't work. You'd get a compilation error. An AsyncValue is not a bool.

What do you mean by compilation error?
If the `AsyncInitial` was implemented, I would think that I would have `T? data` same as implementation of `AsyncLoading`, in this case T is bool.

> An "initial" status is not something logical with AsyncValue. Providers are always initialized when read. That "initial" status is something you made up on your own for your personal logic. It's not a legitimate life-cycle for providers.

A mean for "initial" status as the same of "NotStarted" or "Unsettled" or "Idle" or "Untriggered" for a `Task` of other languages or like in [fpdart Task](https://pub.dev/documentation/dartz/latest/dartz/Task-class.html), that is an wrapper of future , but execute the after call run.

 ```dart
Widget build(context) {
  AsyncValue<T>? value;
  // Only watch the provider if it was clicked.
  if (clicked) value = ref.watch(provider);
}
```

This is cleaner than returning null, but now I would have to create another provider for the clicked state or store it in the widget state, and since it's a very common case, do you have any suggestions to make it simpler?
Since it is used so much, that is why I was interested to add `AsyncInitial`(or other name) in the AsyncValue

For example there are some examples when if `AsyncInitial` exist, should be more clear and we can have a simple handler in the UI.

* https://github.com/coyksdev/flutter-bloc-library-v1-tutorial/blob/2beb1b95bb8695b1ee864277f5506dfdc9310ec1/lib/providers/weather_provider.dart#L7-L12
* https://github.com/bizz84/starter_architecture_flutter_firebase/blob/f6d0c7a892df70ed1ec2f2c9e17bccad4eb261f1/lib/src/features/onboarding/presentation/onboarding_controller.dart#L8-L20


* https://github.com/VeriFi-World/App/blob/96663925998947aa1cab3ac00bdcbeb89ade13d2/lib/src/features/authentication/presentation/sms_code/sms_code_screen_controller.dart#L6-L35

Thanks.

**Comment by rrousselGit** [comment]
> A mean for "initial" status as the same of "NotStarted" or "Unsettled" or "Idle" or "Untriggered" for a `Task` of other languages or like in [fpdart Task](https://pub.dev/documentation/dartz/latest/dartz/Task-class.html), that is an wrapper of future , but execute the after call run.

Sure, but like I said, there's never such a state with a FutureProvidder/AsyncNotifier.
As soon as the provider is read, it started. You can't read a provider that isn't initialized yet. And by initialized I mean "build was called". If build was called, the provider is not in an "uninitialized" state.




> What do you mean by compilation error?
> If the `AsyncInitial` was implemented, I would think that I would have `T? data` same as implementation of `AsyncLoading`, in this case T is bool.

You'd be trying to assign `AsyncInitial<bool>` to `FutureOr<bool>`. Those types are incompatible
