### ISSUE TITLE
Add extension for Nullable AsyncValue to diff the idle state add later add weakWatch or a generator for a "lazy future provider"

### ISSUE THREAD

**Issue by MiniSuperDev** [rrousselGit/riverpod#2579]
Hi, is a very common case in apps pressing a button that performs an action, such as submit a form, auth, a crud operation, etc. it always has an idle/initial state, which is different from loading, in which the action hasn't been performed yet.

## 1. Add extension methods to nullable AsyncValue

One solution I currently use based on [this](https://github.com/rrousselGit/riverpod/issues/2577#issuecomment-1556216782) is to create a notifier that has in the state a Nullable AsyncValue `AsyncValue<T>?`.

For example

```dart
@riverpod
class AsyncDuplicate extends _$AsyncDuplicate {
  @override
  AsyncValue<int>? build() {
    return null;
  }

  void run({required int number}) async {
    state = const AsyncValue.loading();
    state = AsyncValue.data(number * 2);
  }
}
```

This works fine, but to make it easy to use you must create some extension methods in `AsyncValue<T>?` that add the idle "status/state" to all methods, which would ideally be almost the same as `AsyncValue` has.
for example:

```dart
extension NullableAsyncValueExtension<T> on AsyncValue<T>? {
  R when<R>({
    bool skipLoadingOnReload = false,
    bool skipLoadingOnRefresh = true,
    bool skipError = false,
    required R Function() idle,
    required R Function(T data) data,
    required R Function(Object error, StackTrace stackTrace) error,
    required R Function() loading,
  }) {
    if (this == null) {
      return idle();
    }
    return this!.when(
      skipError: skipError,
      skipLoadingOnRefresh: skipLoadingOnRefresh,
      skipLoadingOnReload: skipLoadingOnReload,
      data: data,
      error: error,
      loading: loading,
    );
  }

  R maybeWhen<R>({
    bool skipLoadingOnReload = false,
    bool skipLoadingOnRefresh = true,
    bool skipError = false,
    R Function()? idle,
    R Function(T data)? data,
    R Function(Object error, StackTrace stackTrace)? error,
    R Function()? loading,
    required R Function() orElse,
  }) {
    return when(
      skipError: skipError,
      skipLoadingOnRefresh: skipLoadingOnRefresh,
      skipLoadingOnReload: skipLoadingOnReload,
      idle: idle ?? orElse,
      data: data ?? (_) => orElse(),
      error: error ?? (err, stack) => orElse(),
      loading: loading ?? () => orElse(),
    );
  }

  bool get isIdle {
    return this == null;
  }
}
```

For example, in a widget it would be used like this:

```dart
class SubmitWidget extends ConsumerStatefulWidget {
  const SubmitWidget({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _SubmitWidgetState();
}

class _SubmitWidgetState extends ConsumerState<SubmitWidget> {
  int? numberFromAForm;

  @override
  Widget build(BuildContext context) {
    final value = ref.watch(asyncDuplicateProvider);

    return Column(
      children: [
        Text(
          value.when(
            idle: () => 'idle',
            data: (data) => data.toString(),
            loading: () => 'loading',
            error: (error, stackTrace) => 'error',
          ),
        ),
        MaterialButton(
          onPressed: value.maybeWhen(
            loading: () => null,
            orElse: () => () {
              numberFromAForm = 5; // simulate a number from a form
              ref
                  .read(asyncDuplicateProvider.notifier)
                  .run(number: numberFromAForm!);
            },
          ),
          child: const Text('SUBMIT'),
        ),
      ],
    );
  }
}
```
And if the extension is added it should also be useful if a `weakWatch` / `weakListen` is added in the future, like https://github.com/rrousselGit/riverpod/issues/2398#issuecomment-1487362025

```dart
@riverpod
Future<int> asyncDuplicate(Ref ref, {required int number}) async {
  return number * 2;
}
```
```dart
class SubmitWidget extends ConsumerStatefulWidget {
  const SubmitWidget({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _SubmitWidgetState();
}

class _SubmitWidgetState extends ConsumerState<SubmitWidget> {
  int? numberFromAForm;

  @override
  Widget build(BuildContext context) {
    // Return AsyncValue<T>?
    final value =
        ref.weakWatch(asyncDuplicateProvider(number: numberFromAForm!));

    return Column(
      children: [
        Text(
          value.when(
            idle: () => 'idle',
            data: (data) => data.toString(),
            loading: () => 'loading',
            error: (error, stackTrace) => 'error',
          ),
        ),
        MaterialButton(
          onPressed: value.maybeWhen(
            loading: () => null,
            orElse: () => () {
              numberFromAForm = 5; // simulate a number from a form
              ref.read(AsyncDuplicateProvider(number: numberFromAForm!));
            },
          ),
          child: const Text('SUBMIT'),
        ),
      ],
    );
  }
}
```

At the moment since there is no `weakWatch` or similar also I have a mixin that can help reduce the bolilerplate

```dart
mixin NullableAsyncNotifierRunMixin<T, Params> {
  set state(AsyncValue<T>? value);

  Future<T> fun(Params params);

  Future<void> run(Params params) async {
    state = AsyncValue<T>.loading();
    state = await AsyncValue.guard(() => fun(params));
  }
}
```
This saves a bit of code.
```dart
@riverpod
class AsyncDuplicate extends _$AsyncDuplicate
    with NullableAsyncNotifierRunMixin<int, int> {
  @override
  AsyncValue<int>? build() {
    return null;
  }

  @override
  Future<int> fun(int params) async {
    return params * 2;
  }
}
```
or if https://github.com/rrousselGit/riverpod/issues/2574 would be possible
```dart
mixin NullableAsyncNotifierRunMixin<T, Params> {
  set state(AsyncValue<T>? value);

  AsyncValue<T>? build() {
    return null;
  }

  Future<T> fun(Params params);

  Future<void> run(Params params) async {
    state = AsyncValue<T>.loading();
    state = await AsyncValue.guard(() => fun(params));
  }
}
```
And more simple
```dart
@riverpod
class AsyncDuplicate extends _$AsyncDuplicate
    with NullableAsyncNotifierRunMixin<int, int> {
  @override
  Future<int> fun(int params) async {
    return params * 2;
  }
}
```
## 2. Add weakWatch and weakListen
https://github.com/rrousselGit/riverpod/issues/2398#issuecomment-1487362025
> ref.watch/ref.listen optionally be "weak" (as in don't trigger a build if non-existent).
This would be compatible with all providers rather than be a new kind of provider.

## 3. Add a generator for a "lazy future provider"
Initially this made sense but reading of a possible weakWatch, I think that would be better. https://github.com/rrousselGit/riverpod/issues/2398#issuecomment-1487362025

Since it is a very common case, it would be nice to have a generator for this case.

I don't know if that is the correct name, but the idea is that it allows the future to be executed when the user call `run` and not when the provider is read.

I imagine the syntax would be the same as that of a FutureProvider with the difference that its return value is nullable `Future<T>?`

```dart
@riverpod
Future<int>? asyncDuplicate(Ref ref, {required int number}) async {
  return number * 2;
}
```

This should generate an Notifier with this behavior:

```dart
@riverpod
class AsyncDuplicate extends _$AsyncDuplicate {
  @override
  AsyncValue<int>? build() {
    return null;
  }

  void run({required int number}) async {
    // here somehow will call the function of the future with the family params :p
    state = const AsyncValue.loading();
    state = AsyncValue.data(number * 2);
  }
}
```

I don't know if it is possible or there may be a better syntax or better generated code.

Thank you

___

The important thing is that I think that the Nullable AsyncValue extension would work both for the current version of riverpod, and in the future if you add a `weakWatch` or something like that. and would not make any breaking change.

**Comment by rrousselGit** [comment]
> Hi, is a very common case in apps pressing a button that performs an action, such as submit a form, auth, a crud operation, etc. it always has an idle/initial state, which is different from loading, in which the action hasn't been performed yet.

Not according to Riverpod's best practices.

The recommendation is to not read the provider. 
Alternatively, the recommendation is to not use AsyncNotifier nor AsyncValue, and instead Notifier + a custom model class.

AsyncValue is a representation of the various life cycles of Riverpod's async providers.
They do not contain an "initial" state,
As such, Riverpod will not offer accommodations for such a life-cycle considering it's not an official life-cycle but a user-defined one.

To begin with, AsyncValue.when is bound to disappear now that Dart 3 is here. You should now use pattern matching. So such an extension would be adding code that is already out of date by today's standards.

Do:

```dart
AsyncValue<bool?> value;
switch (value) {
  case AsyncData(value: null): print('initial');
  case AsyncData(:final value): print('data: $value');
  case AsyncError(): print('error');
  case _: print('loading');
} 
```

**Comment by rrousselGit** [comment]
The lazy provider thing is something that has been requested before, but it's not something that I want to implement.


The expected solutions is #1660

**Comment by MiniSuperDev** [comment]
@rrousselGit 
Thanks, 
### 1.
With the implementation of [query mutation](https://github.com/rrousselGit/riverpod/issues/1660) the [weakWatch or weakListen](https://github.com/rrousselGit/riverpod/issues/2398#issuecomment-1487362025) would they be discarded? Maybe it's not necessary anymore, but I'd like to know.

### 2.
And I ask for your advice, and while implementing [query mutation](https://github.com/rrousselGit/riverpod/issues/1660) do you recommend me to use the `AsyncNotifier<T>?` for the cases in which I want to have an idle state as shown in my Example above where null is idle, or should I decouple from using AsyncValue and define my own model?

The idea of not using my own model is to not reinvent the wheel, since the `AsyncValue` already has everything that is usually used (and tested by you :p), and it must be taken into account that **I'm going to migrate all that code to `@mutation` when it is available**, so if I created  a model for this case it would be deprecated as soon as I can use `@mutation`, but I want to know what path you recommend to follow while it is implemented :)

**Comment by rrousselGit** [comment]
> With the implementation of [query mutation](https://github.com/rrousselGit/riverpod/issues/1660) the [weakWatch or weakListen](https://github.com/rrousselGit/riverpod/issues/2398#issuecomment-1487362025) would they be discarded? Maybe it's not necessary anymore, but I'd like to know.

These are fundamentally different things.
 But I doubt I'll implement "weakWatch", at least not before a while.

> should I decouple from using AsyncValue and define my own model?

Yes do that if you want a custom logic.

>  I'm going to migrate all that code to @mutation when it is availabl

Mutations won't be using AsyncValue anyway. They'd have their own custom sealed class, because mutations _do_ have an initial state ;)

**Comment by MiniSuperDev** [comment]
Thanks @rrousselGit , I'm looking forward to it being implemented :).

In the meantime, in case it helps anyone for now, I create a `TaskState` which is basically the same as an `AsyncValue` but has initial state for these cases.
**TaskState**: https://gist.github.com/MiniSuperDev/9b63f6c2026927a5dfeb37a73ac1a9ca
then you can use it like this:
```dart
@riverpod
class AsyncDuplicate extends _$AsyncDuplicate with TaskNotifierMixin<int, int> {
  @override
  TaskState<int> build() {
    return const TaskState.initial();
  }

  @override
  Future<int> fun(int params) async {
    await Future<void>.delayed(const Duration(milliseconds: 500));
    return params * 2;
  }
}
```
```dart
class SubmitWidget extends ConsumerStatefulWidget {
  const SubmitWidget({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _SubmitWidgetState();
}

class _SubmitWidgetState extends ConsumerState<SubmitWidget> {
  int? numberFromAForm;

  @override
  Widget build(BuildContext context) {
    final value = ref.watch(asyncDuplicateProvider);

    return Column(
      children: [
        Text(
          value.when(
            initial: () => 'initial',
            data: (data) => data.toString(),
            loading: () => 'loading',
            error: (error, stackTrace) => 'error',
          ),
        ),
        MaterialButton(
          onPressed: value.maybeWhen(
            loading: () => null,
            orElse: () => () {
              numberFromAForm = 5; // simulate a number from a form
              ref.read(asyncDuplicateProvider.notifier).run(numberFromAForm!);
            },
          ),
          child: const Text('SUBMIT'),
        ),
      ],
    );
  }
}
```

**Comment by rrousselGit** [comment]
Great! I'll close this for now then :)
