### ISSUE TITLE
Can we have a sample application with CRUD example without generator

### ISSUE THREAD

**Issue by Faiyyaz** [rrousselGit/riverpod#2580]
Hi,

Thank you for such a great library.

I have one request, can we have implementation of some rest api with MVC pattern using the provider type which are not legacy.

So that it will be easy to understand the implementation and we will have a unique lmplementation.

**Comment by rrousselGit** [comment]
That should naturally happen as examples are migrated to code-gen. I'll migrate all examples over time. So closing :)

**Comment by Faiyyaz** [comment]
But i want without code-gen one too if possible.

Thanks!

**Comment by rrousselGit** [comment]
That's planned ;) 

Docs allow dynamically enabling/disabling code-gen
