### ISSUE TITLE
Update the minimum dart version to 3.0.2 to match Flutter 3.10

### ISSUE THREAD

**Issue by fisforfaheem** [rrousselGit/riverpod#2581]
this will make project better in the long run

**Comment by rrousselGit** [comment]
What dependency are you talking about?

**Comment by fisforfaheem** [comment]
pubspec.yaml. also you can try flutter pub upgrade

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/23/23,
02:23:29 PM

**Comment by rrousselGit** [comment]
I don't understand what you're talking about. All dependencies are up-to-date for me.

Could you be more specific and mention the name of the outdated packages and which version is not supported?

**Comment by fisforfaheem** [comment]
i meant to say that please add flutter 3.10 recomend.nded updates

**Comment by rrousselGit** [comment]
I have no clue what this is about.

Please be a bit more explicit. There's nothing I can do otherwise.

**Comment by fisforfaheem** [comment]
Brother, but I wanted to convey was that can you please do a flutter pub
upgrade command on your project and then push it. This will update a lot of
background dependencies which always results in performance improvements
and bug fixes in countless other fixes and also updating your pubspec file
would make sure that All the packages are updated.

**Comment by rrousselGit** [comment]
pubspec.lock files aren't commited nor published. So I don't see what me running `pub upgrade` locally on my machine would do.

**Comment by fisforfaheem** [comment]
Oh ok, got it, but pubspec.yamk does...

**Comment by rrousselGit** [comment]
Right, but afaik the pubspec.yaml is up-to-date.

Again, if there's a specific issue, please say so. So far you've been quite broad. So if you found an outdated dependency, you need to tell me which one it is.

**Comment by fisforfaheem** [comment]
I see that everything is fine now, but if you Update the minimum dart version to 3.0.2, this will force people to use the DART 3 and get benefits, otherwise use older version of package

**Comment by rrousselGit** [comment]
The minimum Dart version will naturally be bumped as Riverpod evolves.
