### ISSUE TITLE
The following assertion was thrown building UncontrolledProviderScope:

### ISSUE THREAD

**Issue by iHamza7** [rrousselGit/riverpod#2587]
**i am working on project and using Riverpod for my state management but the following error appears i don't understand the issue.
everything is fine but still getting that error.**
**this is my project repository:**  https://github.com/iHamza7/Authentication-using-riverpod

![Screenshot 2023-05-27 205450](https://github.com/rrousselGit/riverpod/assets/69922336/2c0c45bf-1df8-4830-b3c2-189cedae9269)

![Screenshot 2023-05-27 205522](https://github.com/rrousselGit/riverpod/assets/69922336/d2b89d98-447f-42b2-a3a3-e1e285c7ffd0)

**Comment by Hamza-Imran75** [comment]
Could you please isolate the error?

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/riverpod/issues/1874

You have a thrown exception and Flutter doesn't like how Riverpod tried to add more information in the stacktrace
