### ISSUE TITLE
Offer Notifier.stateOrNull and have Notifier.state throw a custom Exception instead of a StateError

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2589]
~~Currently reading `.state` throws if used on the first build. It's probably way more logical to return null instead.~~

~~But FutureProvider & such shouldn't do so, as the value is never null but instead initialized as AysncLoading.~~

Outdated. New idea:
We could offer alternatives instead. Like stateOrNull, or have state throw an Exception instead of an Error
This would be a less intrusive change for something that's overall fairly niche.

**Comment by AhmedLSayed9** [comment]
Won't this increase the chance to have unpredicted bugs in the code?

i.e:
```dart
@riverpod
int foo(FooRef ref) => 0;

@riverpod
class Bar extends _$Bar {
  @override
  int build() {
    return (state ?? 0) + ref.watch(fooProvider);
  }
}
```
If fooProvider state changes, we might expect `state` to be prev state (which is not) and it'll reset to zero again.

While the throw behavior can predict this (discussed before at https://github.com/rrousselGit/riverpod/discussions/2476):

```dart
@riverpod
int foo(FooRef ref) => 0;

@riverpod
class Bar extends _$Bar {
  bool _firstBuild = true;

  @override
  int build() {
    if(_firstBuild){
      state = 0;
      _firstBuild = false;
    }
    
    return state + ref.watch(fooProvider); //Will throw when re-build
  }
}
```

imo, it's very common that providers depend on other providers and allowing ref.state to be initially null without allowing it to preserve prev state on rebuild may lead to unpredicted issues.
On the other hand, It's very rare when user want to read `state` inside build for a provider that won't rebuild again (which is the case for this change).

**Comment by rrousselGit** [comment]
The previous state would of course be preserved.

**Comment by jascodes** [comment]
In my patched version of riverpod, I was actually doing something like, But I think it bit wanky to throw state error and second this purposal.
```
@internal
abstract class NotifierBase<State> {
  NotifierProviderElement<NotifierBase<State>, State> get _element;

  void _setElement(ProviderElementBase<State> element);

  @protected
  State get state {
    _element.flush();
    // ignore: invalid_use_of_protected_member
    return _element.requireState;
  }

  @protected
  State? get stateOrNull {
    _element.flush();
    // ignore: invalid_use_of_protected_member, invalid_use_of_visible_for_testing_member
    return _element.getState()?.stateOrNull;
  }

  @protected
  set state(State value) {
    // ignore: invalid_use_of_protected_member
    _element.setState(value);
  }

...
```

**Comment by rrousselGit** [comment]
Trying to implement this change, honestly it feels like a pain.

``dart
void increment() => state++;
```

Becomes:

```dart
void increment() => setState(state! + 1);
```

That's a significant downgrade.

**Comment by rrousselGit** [comment]
We could offer alternatives instead. Like `stateOrNull`, or have `state` throw an Exception instead of an Error
This would be a less intrusive change for something that's overall fairly niche.
