### ISSUE TITLE
Get both state and notifier in one line with new dart 3 records feature

### ISSUE THREAD

**Issue by definev** [rrousselGit/riverpod#2606]
Usually, I always need to get both `notifier` and `state` and become 2 lines:
```dart
final bookingForm = ref.watch(bookingControllerProvider);
final bookingController = ref.watch(bookingControllerProvider.notifier);
```

**Solution**
With Dart 3 records feature, we can have an extension for providers like
```dart
final (bookingForm, bookingController) = ref.watch(bookingControllerProvider.stateNotifier);
```

**Current workaround**
```dart
extension on WidgetRef {
   (BookingForm, BookingController) watchStateNotifier(provider) => (ref.watch(provider), ref.watch(provider.notifier));
}

final (bookingForm, bookingController) = ref.watchStateNotifier(bookingControllerProvider);
```

**Comment by rrousselGit** [comment]
I don't think there's a lot of value in doing this.

To begin with, reading the notifier is not that common once we have mutations.

**Comment by definev** [comment]
How does mutation work? I want to read it about it. I think the `stateNotifier` getter is a "nice to have" feature 😃

**Comment by rrousselGit** [comment]
Closing as I have no plan to implement such a feature
