### ISSUE TITLE
invalidate withouth refreash future provider

### ISSUE THREAD

**Issue by vrman** [rrousselGit/riverpod#2608]
is this possible to dispose a future provider without refreshing that ? if i use invalidate to dispose or clear a future provider, its automatically refreshing that too . so its try to call the API again , but i just want to dispose that provider and try again only if that use again in next pages.

**Comment by rrousselGit** [comment]
You need to make sure that the provider is no-longer used anywhere. If it's still in use in some places, it'll end-up refreshing
