### ISSUE TITLE
Make an example for dealing with side-effects

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2625]
Users commonly want to listen to the status of a side effect. This triggers a common mistake, with is described in the "AVOID using providers for performing "side effects"." section of https://github.com/rrousselGit/riverpod/issues/2624

No matter whether we have [mutations](https://github.com/rrousselGit/riverpod/issues/1660) or not, it would still be valuable to showcase how to officially do this.

TL;DR The idea is to do:

```dart
@riverpod
class CRUDExample extends _$CRUDExample {
  @override
  Future<Model> build() async {
    return Model.fromJson(await http.get('api/model'));
  }
  
  Future<Model> updateModel(Model newModel) async {
    // We don't set the state as loading on purpose.
    // We don't catch errors and set the state as error either.
    // The UI should track the returned Future instead

    await http.post(newModel.toJson());    
    state = AsyncData(newModel);
  }
}
```

Then the UI could do:

```dart
class UI extends HookConsumerWidget {
  @override
  Widget build(context, ref) {
    // track the side-effect in the UI.
    // Alternatively use a StatefulWidget and have this be a property of the State
    final updateFuture = useState<Future<Model>?>(null);
    // Listen to the future, if any
    // Alternatively use a FutureBuilder
    final updateSnapshot = useFuture(updateFuture.value);

    // The UI can then listen to the AsyncSnapshot of the side-effect future.
    return switch (updateSnapshot) {
      // The side-effect is done
      AsyncSnapshot(:final data?) => Text('Updated with $data'),
      // The side-effect is still running
      AsyncSnapshot(
        connectionState: ConnectionState.none || ConnectionState.waiting
      ) =>
        const Text('Updating...'),
      // The side-effect failed
      AsyncSnapshot(:final error?) => Text('Failed with $error'),
      // No side-effect has been triggered yet
      // We can show a button to start the side-effect
      _ => ElevatedButton(
          // This will store the future locally, rebuild the widget accordingly, and start listening to said future
          onPressed: () => updateFuture.value =
              ref.read(CRUDExampleProvider.notifier).updateModel(Model()),
          child: Text('Start the side-effect'),
        ),
    };
  }
}
```

## Optimistic updates considerations

Sometimes instead of showing a spinner, we want to immediately show the likely change while it's pending. Then, if the operation failed, revert.

This is a matter of slightly tweaking `updateModel`.

Instead of:

```dart
  Future<Model> updateModel(Model newModel) async {
    await http.post(newModel.toJson()); 
    // Update the state once the network request has succeded
    state = AsyncData(newModel);
  }
```

We can do:

```dart
  Future<Model> updateModel(Model newModel) async {
     final previousState = state;
     // Immediately update the state before the network-request is performed.
     state = AsyncData(newModel);
     try {
      await http.post(newModel.toJson());
    } catch (_) {
      // Optional sanity check. This verifies that there's no race-condition. Such that we're not reverting
      // changes which were made while the operation was pending. 
      if (state != AsyncData(newModel)) throw StateError('The state changed again while an operation was pending.');
  
      // If the request failed, revert to the previous state.
      state = previousState;
      rethrow;
    }
  }
```

## Life-cycle considerations

The page explaining side-effects would likely be the page where all "Notifier" logic is explained.

In this case, some content from https://github.com/rrousselGit/riverpod/issues/2630 should be forked/adapted to this page.

Related to https://github.com/rrousselGit/riverpod/issues/1767

## Async/Notifiers properties explanations

- [ ] We should explain what `this.state` is.
   More importantly, we should note that `state` is protected and should not be accessed outside of the notifier.
- [ ] We should explain what `AsyncNotifier.future` is.
   This is equivalent to `ref.read(provider.future)`. 
   It is different from awaiting `build`. Instead it waits for the first data/error available.
   This matters if your `build` somehow calls `state = ` to possibly emit multiple values.
   
- [ ] Note that it is safe to call `this.future` inside `AsyncNotifier.build`. This will effectively cause the provider to wait until some state has changed before continuing.
  This can be used to expose state only if a user is logged in, for instance.
  ```dart
  Future<User> build() async {
    String? userToken = ref.watch(authProvider);
    if (userToken == null) return this.future; // wait for the user to be logged in.
    return http.get('api/users', header: {'token': userToken});
  }
  ```

- [ ] Let's talk about `AsyncNotifier.update`
   This is syntax sugar for awaiting `this.future` and handling only "data".
   This should only be used if we care about the previous "state".
   We should not set "loading" _before_ "update", but inside instead.
  `update` does **not** set the state to loading/error if the update fails.

**Comment by problematicconsumer** [comment]
Thanks for the example, this approach makes sense.
I believe the switch part doesn't address null data. If future returns null or void, it's not considered data here (can return smt like Unit to mitigate).
Also was curious if you think doing it this way makes sense?

```dart
// custom mutation class with idle state
@freezed
class AsyncMutation with _$AsyncMutation {
  const AsyncMutation._();

  const factory AsyncMutation.idle() = Idle;
  const factory AsyncMutation.inProgress() = InProgress;
  const factory AsyncMutation.fail(Object error, StackTrace stackTrace) = Fail;
  const factory AsyncMutation.success() = Success;

  bool get isInProgress => this is InProgress;
}

// all in one hook that returns a record with callbacks etc.
({
  AsyncMutation state,
  ValueChanged<Future<void>> setFuture,
  ValueChanged<void Function(Object error)> setOnFailure,
}) useMutation({
  void Function(Object error)? initialOnFailure,
}) {
  final mutationUpdate = useState<Future<void>?>(null);
  final mutationState = useFuture(mutationUpdate.value);
  final failureCallBack =
      useValueNotifier<void Function(Object error)?>(initialOnFailure);

  final mapped = useMemoized(
    () => switch (mutationState) {
      AsyncSnapshot(:final data?) => const Success(),
      AsyncSnapshot(connectionState: ConnectionState.waiting) =>
        const InProgress(),
      AsyncSnapshot(:final error?, :final stackTrace?) =>
        Fail(error, stackTrace),
      _ => const Idle(),
    },
    [mutationState],
  );

  // one-off callback in failure
  useMemoized(
    () {
      if (mapped case Fail(:final error)) {
          failureCallBack.value?.call(error),
      }
    },
    [mapped, failureCallBack.value],
  );

  return (
    state: mapped,
    setFuture: (future) => mutationUpdate.value = future,
    setOnFailure: (onFailure) => failureCallBack.value = onFailure,
  );
}

```

**Comment by rrousselGit** [comment]
For null values, you could do:

```dart
AsyncSnapshot(:final data, hasData: true)
```

**Comment by rrousselGit** [comment]
That's an interesting consideration though. It's worth making a note in the docs about it.

And maybe a lint rule for it too

**Comment by problematicconsumer** [comment]
> For null values, you could do:
> 
> ```dart
> AsyncValue(:final data, hasData: true)
> ```

This won't match `void` though. From [AsyncSnapshot's hasData docs](https://api.flutter.dev/flutter/widgets/AsyncSnapshot/hasData.html):

> Returns whether this snapshot contains a non-null [data](https://api.flutter.dev/flutter/widgets/AsyncSnapshot/data.html) value.
> This can be false even when the asynchronous computation has completed successfully, if the computation did not return a non-null value. For example, a [Future<void>](https://api.flutter.dev/flutter/dart-async/Future-class.html) will complete with the null value even if it completes successfully.

**Comment by rrousselGit** [comment]
That's for AsyncSnapshot. I'm talking about AsyncValue.

AsyncValue.hasData doesn't rely on `data!= null`

**Comment by problematicconsumer** [comment]
oh, you're right. but my question is about `AsyncSnapshot` and the example you've written.

```dart
 return switch (updateSnapshot) {
      // The side-effect is done
      AsyncSnapshot(:final data?) => Text('Updated with $data'), <--- here!
      // The side-effect is still running
      AsyncSnapshot(
        connectionState: ConnectionState.none || ConnectionState.waiting
      ) =>
        const Text('Updating...'),
      // The side-effect failed
      AsyncSnapshot(:final error?) => Text('Failed with $error'),
      // No side-effect has been triggered yet
      // We can show a button to start the side-effect
      _ => ElevatedButton(
          // This will store the future locally, rebuild the widget accordingly, and start listening to said future
          onPressed: () => updateFuture.value =
              ref.read(CRUDExampleProvider.notifier).updateModel(Model()),
          child: Text('Start the side-effect'),
        ),
    };
```

You're assuming `AsyncSnapshot(:final data?)` means mutation is done but if data is null or void it will be matched with `_ =>`
for a button, it's not a big deal but if we want to show user some sort of snackbar or indication that action was successful (like what I'm doing [here](https://github.com/rrousselGit/riverpod/issues/2625#issuecomment-1621572113)) this won't work

**Comment by rrousselGit** [comment]
You wouldn't use AsyncSnapshot in Riverpod. You'd use AsyncValue

**Comment by mboyamike** [comment]
Loving the addition to the docs

I think adding the case for dialogs/snackbars in the docs would also be helpful

**Comment by rrousselGit** [comment]
The page is available here https://docs-v2.riverpod.dev/docs/essentials/side_effects#going-further-showing-a-spinner--error-handling, so closing 

More examples are planned in other pages
