### ISSUE TITLE
Are there any callback methods in Rivepod similar to the onInit, onReady, and onClose methods in GetxService?

### ISSUE THREAD

**Issue by greyfreedom** [rrousselGit/riverpod#2627]
I am migrating my project from GetX to Riverpod. In GetX, I used GetxService to initialize some global variables (possibly asynchronous in the onInit method) and release resources (in the onClose method). I would like to know how to achieve these operations in Riverpod. Here is an example code:
```
class GlobalService extends GetxService with WidgetsBindingObserver {
  static GlobalService get to => Get.find();
  static String version = '';
  final isDarkModel = false.obs;

  @override
  Future<void> onInit() async {
    super.onInit();
    await asyncInitOp();
    WidgetsBinding.instance.addObserver(this);
  }
  
   Future<String> asyncInitOp() async {
    .....
  }


  @override
  void onClose() {
    super.onClose();
    WidgetsBinding.instance.removeObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    logger('didChangeAppLifecycleState $state');
    switch (state) {
      case AppLifecycleState.detached: 
        _close();
        break;
    }
  }

  Future<void> _close() async {
    // release resources
  }
}
```

**Comment by rrousselGit** [comment]
The equivalent would be:

```dart
final provider = FutureProvider<Whatever>((ref) async {
  ref.onDispose(() => print('onClose'));

  print('onInit');

  await <initialize your object>;

  print('onReady');
});
```

**Comment by greyfreedom** [comment]
> 
However, if there are other providers that FutureProvider depends on in its create method, the create method will be called again whenever the values of the dependent providers change. What I expect is that the initialization code should only be called once in the entire app lifecycle.
```
final provider = FutureProvider<Whatever>((ref) async {
  ref.onDispose(() => print('onClose'));

 ref.watch(anotherProvider); // add dependency

  print('onInit');

  await <initialize your object>;

  print('onReady');
});
```

**Comment by rrousselGit** [comment]
No that's voluntary. That's the whole point of `ref.watch`

Maybe you're looking for `ref.listen` in your case?

**Comment by greyfreedom** [comment]
I have another question. I have many observable variables in GetxController, and when used, I only need to get the controller to observe them in the widget. If I want to migrate GetxController to Riverpod, do I need to change all the variables to separate Providers?
```
class MyController extends GetxController with WidgetsBindingObserver {
  static StartLiveController get to => Get.find();
  final one= false.obs;
  final two= 123.obs;
  .....Around 20 variables...
 .....Methods to modify variable values......
}
```
Should I write it like this:
```
final oneProvider = Provider.....
final twoProvider = Provider.....
.....Around 20 providers...
```
and where should methods to modify variables be placed?

**Comment by rrousselGit** [comment]
That's up to you to decide. There's no clear rule for this.

**Comment by greyfreedom** [comment]
> That's up to you to decide. There's no clear rule for this.

Thank you.
