### ISSUE TITLE
Improvements on the "Riverpod for Provider users page"

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2629]
The "Riverpod for Provider users" page

This page has a few responsibilities:

- Explain why Riverpod was created when Provider exists
- Explain the difference in principle (Provider was merely an InheritedWidget wrapper. Riverpod now is branded as "cache solution").
  ^ This also should be mirrored on the Provider README. It should link to Riverpod.
- Explain how to migrate from Provider to Riverpod
- Explain why it was necessary to make a new package

---- 

## Why Riverpod was created

Riverpod has gone a long way from the reasons behind its initial creation. But if you're wondering why it exists, here are the reasons:

Provider has fundamental issues due to being restricted by the InheritedWidget API

- Unable to have two providers with the same "type"
- providers reasonably emit only one value at a time.
- Combining providers is very difficult. We may be tempted to enable the usage of `context.watch` inside provider's `create`. But this would be unreliable as `didChangeDependencies` may be triggered even if no dependency has changed (such as when there's a GlobalKey involved in the widget tree).
- There's a lack of type safety. It's common to end-up with a ProviderNotFoundException during refactors/large changes.
- If we wanted to implement something similar to Riverpod's "family", parameters would have to be untyped.
- We have to rely on scoping providers to dispose the state when it stops being used. But it gets tricky when state is shared between pages.
  Riverpod solves this with `autoDispose` vs `keepAlive`. But there's no way to implement this with raw InheritedWidgets.
- Not being able to implement `autoDispose` effectively prevents the implementation of `family` too, as they go hand-in-hand. And `family` enables enormous simplification of logic.

- [ ] We should link two Flutter issues: "lack of removeDependency" and "widgets never stop listening to InheritedElements"

----

## Random stuff to order

- [ ] Riverpod was created because the alternative of making a breaking change in Provider was deemed "too breaking" and controversial due to having to subclass `ConsumerWidget` instead of `StatelessWidget`.
   It was instead decided to make a separate package to:
    - ease the migration by enabling to use both approaches at the same time temporarily.
    - allow folks to stick to Provider if they dislike Riverpod in principle.
- [ ]  Riverpod should be used instead of Provider. Riverpod is the more modern approach and Provider currently is lacking in many areas with no way forward.
- [ ] It should be clear that Riverpod is recommended over the older Provider package.
- [ ] Riverpod works around technical limitations of InheritedWidgets, such as:
  - not being able to have an "onChange" listener
     This is problematic for navigation, such as for snackbars/modals/...
  - widgets never stopping to listen to an InheritedWidget/aspect (link Flutter issue)
     This could cause significant memory leaks if some provider states may be "dynamically mounted"
     (cf passing parameters to providers / family)
  - InheritedWidgets being enable to react when a consumer stops listening to them
     This prevents the ability for providers to automatically destroy their state when no-longer used
- [ ] Riverpod solves multiple-providers-with-same-type
      This sounds benign but is a significant hurdle to refactoring and composition.
      By removing this limitation, we can freely split logic into tiny pieces of logic.
      Like having one `Provider<List<Item>>` for all items, one for sorted items, one for recently deleted items, ...
- [ ] When not using code-geenration, migrating from Riverpod to Provider is very straightforward.
   It's all about moving your provider definition outside if `MultiProvider` and storing it in a global final variable instead.
   Providers from pkg:provider have a strict equivalent in Riverpod.
    In particular, you'll find ChangeNotifierProvider.
    Although this provider is not recommended when writing new code and is not the best way to use Riverpod, this is a very easy way to start your migration from pkg:Provider to Riverpod.
- [x] If you have an existing app, don't try to migrate all your providers at once.
  Don't immediately try to change ChangeNotifiers into the more modern AsyncNotifiers from Riverpod.
   This will requite a bit of a paradigm shift, so it may be difficult to do initially.
   The important first is to get yourself familiar with Riverpod. It's fine to keep using ChangeNotifier using Riverpod and not use the latest fancy Riverpod features.
- [x] You can migrate `ProxyProviders` using a normal ref.listen in Riverpod.
- [x] It is entirely possible to use both Provider and Riverpod at the same time.
  In the long-run, you should strive toward moving all your application to Riverpod. But don't burn yourself out. Do it one provider at a time.
- [ ] We should show how, using import aliases, folks can use both Riverpod and Provider at once.
- [ ] Scoping providers is kind of discouraged using Riverpod.
   In pkg:Provider, this was used for two things:
   - destroying state when leaving a page
   - having custom state per page
   
   The problem is that this didn't work well over large applications. For example, state often is created in one page, but destroyed later in a different page after navigation.
     Similarly the "custom state per page" becomes difficult if that state needs to be shared with another part of the widget tree, like modals or a multi-step form.
   Riverpod takes a different approach. Instead, it is now possible for providers to automatically destroy their state when they stopped being used. As in, when the last widget removing a provider is unmounted, Riverpod will detect this and destroy the provider.
   Similarly. it is now possible to pass parameters to providers.
   And when passing parameters, a unique state is created per unique parameter.  This solves the "custom state per page", as those pages can now pass information unique to said page to the provider, which leads to a unique state for that page.
   At the same time, the state is no-longer bound to one specific page. If a different page tries to access the same state, it will be able to do so by reusing the parameters.
       
   In many ways, passing parameters to providers is equivalent to a `Map` key. If the key is the same, the value obtained is the same. If it's a different key, a different state will be obtained.

**Comment by lucavenir** [comment]
Has #2676 exhaustively satisfied this issue?

**Comment by rrousselGit** [comment]
Ill check that later.

Although I remember that there are some todos in those pages (due to missing pages)

It could be worth adding an empty page for those missing pages. And fix the to-do links in the migration guide.

Otherwise I'm sure I'll forget to check those 😜

**Comment by lucavenir** [comment]
I recall writing a TODO about "how to write aliases efficiently" but I can't remember anything else.

> It could be worth adding an empty page for those missing pages
Sure!
