### ISSUE TITLE
Filter AsyncValues with .whereAsync

### ISSUE THREAD

**Issue by Ostabo** [rrousselGit/riverpod#2635]
**Is your feature request related to a problem? Please describe.**
I'd like to have an option to filter my API requests on null values (or any other filters on the async value itself), wich is currently only possible on the AsyncValue<T> since .where only allows a bool function

**Describe the solution you'd like**
Currently my workaround is this:
```dart
extension IterableExtension<E> on Iterable<E> {
  Iterable<E> whereAsync(AsyncValue<bool> Function(E element) selector) {
    final List<E> result = <E>[];
    forEach((E x) {
      selector(x).whenData((bool value) {
        if (value) {
          result.add(x);
        }
      });
    });
    return result;
  }
}
```
using it like this:
```dart
ref.watch(someProvider
        .whereAsync((AsyncValue<Foo> element) => element.whenData(
            (Foo value) => value.someField.isNotEmpty))
```

**Additional context**
![grafik](https://github.com/rrousselGit/riverpod/assets/34040518/a2e885b3-6ebe-46f3-abde-9520a1763036)

**Comment by rrousselGit** [comment]
Generally, `List<AsyncValue>` is not something recommended.

But anyway, you can do `list.where((e) => e is AsyncData<T> && e.value.genres.isNotEmpty)`.   
whenData is not really made for this :)
