### ISSUE TITLE
Adding after build callback in riverpod generator 

### ISSUE THREAD

**Issue by shehabmohamed0** [rrousselGit/riverpod#2638]
when using Riverpod generator for asyncNotifier and notifier, in some cases we want to initialize our state by getting data asynchronously. when dealing with a complex state it requires more code to change it, because we can only access the state by using asyncValue.data or asyncValue.requiredValue if we assume that we know asyncValue has data.
```
final currentState = state.requiredValue;
state = AsyncValue.data(state.requiredValue.copyWith(
    value1: currentState.value1 +1,
    value2: currentState.value2 +2
));

```
more boilerplate code.

 we can solve this problem by making a normal  Notifier or stateNotifier and calling a function from the UI in initState.
```
@override 
void initState(){
    WidgetBinding.instance.addPostFrameCallback((_) {
         ref.read(someStateNotifierProvider).initialize();
     });
}
```

another solution by not using the generator and providing the state manually then calling any method before providing the state
```
final someProvider = StateNotifierProvider<OurStateNotifier, OurState>(
(ref) {
     return OurStateNotifier()..initialize(); 
    }
)
```
 but here we have lost generator features. It will be better to add the logic of initiating the provider in the provider itself with the generator api.

Solution:
in the Riverpod generator, we can add a callback function to run immediately after the build method which we can override its behavior or not.
```
void postBuildCallback(OurState state){ 
     initialize(); 
}
```
if there is any other way I don't know to achieve this please tell me

**Comment by rrousselGit** [comment]
> another solution by not using the generator and providing the state manually then calling any method before providing the state
> 
> ```
> final someProvider = StateNotifierProvider<OurStateNotifier, OurState>(
> (ref) {
>      return OurStateNotifier()..initialize(); 
>     }
> )
> ```

If that works, why can't you call `initialize()`inside the `build`method of providers?

**Comment by rrousselGit** [comment]
> @override
>   SomeState build() {
>     const state = SomeState(asyncName: AsyncLoading());
>     initialize(state);
>     return state;
>   }

Sounds like you want `return this.state`

**Comment by quyenvsp** [comment]
+1, because document recommend use `NotifierProvider` so I am converting old `StateNotifierProvider`. But can not make this work.

before
```
StateNotifierProvider
...
return PagesNotifier()..getPage();
```

now
```
AutoDisposeFamilyNotifier
...
  @override
  BaseState<T> build(Arg arg) {
    ref.onDispose(dispose);
    ref.listenSelf((previous, next) {
      if (previous == null) init();
    });
    return BaseState();
  }
```

`init` line 1 `state = state.loading()` so `Tried to modify a provider while the widget tree was building.` The only way is set delay, but I do not feel good with delay.

Could someone confirm `StateNotifierProvider` will never got deprecated so I can continue using it?

**Comment by rrousselGit** [comment]
I have no plan to add a post-build callback.

You can do:

```dart
build() {
  this.state = Something();
  init();
  return this.state;
}
```

Therefore I'll close this
