### ISSUE TITLE
Invalidate family calls FutureProvider more than once

### ISSUE THREAD

**Issue by devbrisk** [rrousselGit/riverpod#2641]
**Describe the bug**
I have a listview to render items and a FutureProvider.family to load items by api. When the FutureProvider loaded three times by user scroll, then call invalidate family, FutureProvider.family calls twice or more to reset items!

**To Reproduce**
```
final loadJobsProvider = FutureProvider.family<Paginated<JobsItem>, int>(
    (ref, int pageIndex) async {
          var selectedCatId = ref.read(selectedCatProvider);

          final data = await CategoryApi().getJobs(pageIndex, selectedCatId);

          return data;
    },
  );
```

`ref.invalidate(loadJobsProvider);
`

**Expected behavior**
For example when I want to change category, I pass selected category id to selectedCatId and I expected to reload items with new categoryId once, but I see the api calls twice or more...
finally when the list reloaded, changing category is correct until scroll the listview again.

**Comment by rrousselGit** [comment]
Can you please share a complete example? The provider alone isn't enough to reproduce.

To begin with, what do you mean exactly by "calls twice or more the API"? Are you sure that those calls are made with the same parameters?  
When doing `ref.invalidate(family)`, this will cause all the active parameters to refresh. Chances are that's what happens here.

**Comment by devbrisk** [comment]
Those calls are same but only pageIndex is 0, 2, 3. or ...
Let me describe more. I have a list with a category filter. I click on first category with id 100, first 20 items loaded, I scroll more to see more items, then pageIndex increased to 1 and api called with category id 100 and pageIndex 1, scroll more to see more items, category id 100 and pageIndex 2. everything is okay.
Now I want to change the category, I click on another category with id 101, then I see futureprovider called two or three times like this:
categoryid: 101, pageIndex: 0
categoryid: 101, pageIndex: 2

because the last pageIndex was 2, changing category has issue. after invalidate family, futureprovider calls twice or more with pageIndex 0 and last pageIndex. invalidate family should call only pageIndex 0.

Note that there is no issue if I click only on the categories without scroll. 

This is a simplified example:

```
class _Category extends ConsumerState<Category> {
  final selectedCatProvider = StateProvider<int>((ref) => 0);

  late final loadJobsProvider = FutureProvider.family<Paginated<JobsItem>, int>(
    (ref, int pageIndex) async {
      final selectedCatId = ref.read(selectedCatProvider);

      final data = await CategoryApi().getJobs(pageIndex, selectedCatId);

      print("selectedCatId = $selectedCatId, pageIndex = $pageIndex");

      return data;
    },
  );

  late final jobsCountProvider = Provider<AsyncValue<Paginated>>((ref) {
    return ref.watch(loadJobsProvider(0)).whenData((Paginated<JobsItem> pageData) {
      return pageData;
    });
  });

  @override
  Widget build(BuildContext context) {
    final data = ref.watch(jobsCountProvider);

    return Scaffold(
        body:
            body(data.hasValue && !data.isRefreshing ? data.value! : Paginated(total: 3)));
  }

  Widget body(Paginated item) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        JobsCategory(widget.id, changeCategory),
        JobsBody(item, loadJobsProvider),
      ],
    );
  }

  invalidateProvider() {
    ref.invalidate(loadJobsProvider);
  }

  changeCategory(id) {
    ref.read(selectedCatProvider.notifier).state = id;

    invalidateProvider();
  }
}

----------

class JobsCategory extends ConsumerWidget {
  final int categoryId;
  final Function changeCategory;

  const JobsCategory(this.categoryId, this.changeCategory, {super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final homeData = ref.watch(homeDataProvider);

    return categorySection(ref, homeData);
  }

  Widget categorySection(WidgetRef ref, home) {
    final categories = home.value!.building!.cats!;

    return Container(
      height: 90,
      child: ListView.builder(
        shrinkWrap: true,
        scrollDirection: Axis.horizontal,
        itemCount: categories.length,
        itemBuilder: (BuildContext context, int index) {
          final item = categories[index];

          return ChoiceChip(
              label: Column(
                children: [
                  SvgPicture.network(item.icon!, width: 24, height: 24),
                  Text(item.name!),
                ],
              ),
              selected: false,
              onSelected: (value) => **changeCategory(item.id!)**);
        },
      ),
    );
  }
}

----------

class JobsBody extends ConsumerWidget {
  final Paginated item;
  final FutureProviderFamily<Paginated<JobsItem>, int> provider;

  const JobsBody(this.item, this.provider, {super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Expanded(
        child: ListView.builder(
      shrinkWrap: true,
      cacheExtent: 2000,
      itemCount: item.total,
      itemBuilder: (context, index) {
        final currentFavoriteItemFromIndex =
            ref.watch(provider(index ~/ item.limit)).whenData((value) {
          return value.results[index % item.limit];
        });

        return ProviderScope(
          overrides: [currentJobItemProvider.overrideWithValue(currentFavoriteItemFromIndex)],
          child: const CategoryListItem(),
        );
      },
    ));
  }
}
```

**Comment by rrousselGit** [comment]
> Those calls are same but only pageIndex is 0, 2, 3. or ...

So they aren't the same ;)
If the pageIndex for the calls is different, that's not the same request.

For now there's not much Riverpod can do to change this behavior.


What _you_ can do is cancel your network request if the provider stops being used.

**Comment by rrousselGit** [comment]
What you likely want to do here is, when you change category, you want to reset the scroll/page offset. Then, Riverpod will only fetch the first page.

Otherwise since the scroll/page offset is preserved by default, Riverpod will fetch data up to the currently selected offset.

You could do that with a ScrollController
