### ISSUE TITLE
"Bad state: Tried to use StateNotifier after dispose was called." when StateNotifier is initialized with async call

### ISSUE THREAD

**Issue by ramtinq** [rrousselGit/riverpod#2644]
I have a StateNotifier witch loads its initial state from server:

```
class EditPostInputsStateNotifier extends StateNotifier<InputsState> {
  int postId;

  EditPostInputsStateNotifier({required this.postId})
      : super(const InputsState(
          {
            // some (gapless) initializations
          },
        )) {
    loadCurrentValues(postId); // this loads initial values from server
  }

  void loadCurrentValues(int postId) async {
    state = state.copyWithIsLoading(true);

    var response = await Api.get('posts/$postId/edit');
    if (response != null && response.statusCode == 200) {
      Map<String, String> initialValuesMap = jsonDecode(response.body);
      state = state.copyWithValues(initialValuesMap);
    }
    state = state.copyWithIsLoading(false);
  }
}

final editPostInputsStateProvider = StateNotifierProvider.autoDispose
    .family<EditPostInputsStateNotifier, InputsState, ProductId>(
        (ref, id) => EditPostInputsStateNotifier(postId: id));

class EditPostView extends ConsumerStatefulWidget {
  final int postId;
  const EditPostView({super.key, required this.postId});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _EditPostViewState();
}

class _EditPostViewState extends ConsumerState<EditPostView> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final inputsStateProvider = ref.watch(editPostInputsStateProvider(widget.postId)); // ----> this seems to be required! <----
    return Column(
      children: [
        TextField(
          onChanged: (value) => ref
              .read(editPostInputsStateProvider(widget.postId).notifier)
              .setField('title', value),
        )
      ],
    );
  }
}
```
Everything worked fine with this code, until I noticed that I'm not using `inputsStateProvider` anywhere in my build method, so I removed the `final inputsStateProvider = ref.watch(editPostInputsStateProvider(widget.postId));` line, and got this error:

`Bad state: Tried to use StateNotifier after dispose was called.`

Was it the current way, just calling `ref.watch(editPostInputsStateProvider(widget.postId));` in a widget's `build` method whenever the widget uses this `StateNotifier` (just as above)?

couldn't be any cleaner way? Should I use `(Async)NotifierProvider` instead?

**Comment by rrousselGit** [comment]
Since your provider is _autoDispose_, you need something which watches the provider. Otherwise the provider will clear its state, disposing the notifier.


That's why your `ref.watch` fixes the issue, because it prevents the notifier from getting destroyed while `_EditPostViewState` is mounted.

Notifiers should cancel their pending work on dispose. Hence why you have an error, because your notifier got disposed, but it kept trying to do work.

**Comment by ramtinq** [comment]
Thank you so much for your clear and informative response. Just one another question: in the docs of StateNotifierProvider, it is mentioned that:
```
// This class should not expose state outside of its "state" property, which means
// no public getters/properties!
```
However, sometimes. we might want to have some public variables which store the initial state. In the example above, I have added a public `Map<String, TextEditingController> controllers = {};`, and in the `loadCurrentValues` function which is only called in the initialization, I add `TextEditingController(text: {{{initial_value_loaded_from_server}}}` to this Map, so that later in the UI, I can use:

```
                TextField(
                  controller: ref
                      .read(editPostInputsStateProvider(widget.postId).notifier)
                      .controllers['title'],

```
I it a bad practice? I'm both violating the comments in the documentation and, using `ref.read ...` outside function bodies.
What would be the alternative appropriate solution?
