### ISSUE TITLE
Providers and Listeners aren't reacting when screen is off

### ISSUE THREAD

**Issue by HosamHasanRamadan** [rrousselGit/riverpod#2645]
**Describe the bug**
Flutter version : stable , `3.10.4`
Fluter riverpod: `2.3.6`

Provider and listeners doesn't react when screen locked while app running .

**To Reproduce**
Steps:
1- run the app
2- Press start button
3- Check  console 
```bash
I/flutter (10342): [1] [Stream] 27
I/flutter (10342): [2] isEvenProvider
I/flutter (10342): [3] FirstStateNotifier
I/flutter (10342): [4] SecStateNotifier
```
4- press lock screen button on your phone and check the console
```bash
I/flutter (10342): [1] [Stream] 54
I/flutter (10342): [1] [Stream] 55
I/flutter (10342): [1] [Stream] 56
```
<details>
  <summary>Code</summary>
  
  ```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final firstStateNotifierProvider = StateNotifierProvider<FirstStateNotifier, bool>((ref) {
  return FirstStateNotifier(false, ref);
});

final secStateNotifierProvider = StateNotifierProvider<SecStateNotifier, bool?>((ref) {
  return SecStateNotifier(null, ref);
});

final classHolderProvider = Provider((ref) {
  return ClassHolder();
});

final counterStreamProvider = StreamProvider((ref) {
  return ref.watch(classHolderProvider).counterStream;
});

final isEvenProvider = Provider((ref) {
  final value = ref.watch(counterStreamProvider);
  print('[2] isEvenProvider');
  return value.valueOrNull?.isEven ?? false;
});

class SecStateNotifier extends StateNotifier<bool?> {
  final Ref ref;
  ProviderSubscription? _connectionSubscription;

  SecStateNotifier(super.state, this.ref);
  void startSub() {
    _connectionSubscription ??= ref.listen(firstStateNotifierProvider, (previous, next) {
      print('[4] SecStateNotifier');
      state = next;
    });
  }

  void stopSub() {
    _connectionSubscription?.close();
    _connectionSubscription = null;
  }

  @override
  void dispose() {
    stopSub();
    super.dispose();
  }
}

class FirstStateNotifier extends StateNotifier<bool> {
  final Ref ref;
  late final ProviderSubscription _connectionSubscription;

  FirstStateNotifier(super.state, this.ref) {
    ref.listen(isEvenProvider, (previous, next) {
      print('[3] FirstStateNotifier');
      state = next;
    });
  }
  @override
  void dispose() {
    _connectionSubscription.close();
    super.dispose();
  }
}

class ClassHolder {
  ClassHolder();

  late Stream<int> counterStream = Stream.periodic(
    const Duration(seconds: 2),
    (computationCount) {
      print('[1] [Stream] $computationCount');
      return computationCount;
    },
  );
}

void main() {
  runApp(
    ProviderScope(
      child: MaterialApp(
        theme: ThemeData(primarySwatch: Colors.blue),
        home: const MyHomePage(),
      ),
    ),
  );
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(secStateNotifierProvider);
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              const Text('State changes'),
              Text(
                '$value',
                style: Theme.of(context).textTheme.headline4,
              ),
            ],
          ),
        ),
        floatingActionButton: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            FloatingActionButton(
              onPressed: () => ref.read(secStateNotifierProvider.notifier).startSub(),
              child: const Text('Start'),
            ),
            FloatingActionButton(
              onPressed: () => ref.read(secStateNotifierProvider.notifier).stopSub(),
              child: const Text('Stop'),
            ),
          ],
        ),
      ),
    );
  }
}

  ```
</details>

**Expected behavior**
The out before and after locking the screen should be the same.
The output of `Step 4` should be the same as `Step 3`.

**Comment by rrousselGit** [comment]
Your code contains deprecated materials (the `.stream`).
Chances are that's your problem.


Could you reproduce the issue without that deprecated element?

**Comment by HosamHasanRamadan** [comment]
Actually `stream` here is a field inside  `ClassHolder`. i can rename it in the code to avoid confusion , new name `counterStream`

**Comment by rrousselGit** [comment]
Oh, my bad. Let me look into it.

**Comment by HosamHasanRamadan** [comment]
I tried to trace the problem inside the lib what I found out:
I commented this line, everything works as expected.
https://github.com/rrousselGit/riverpod/blob/d5dc172419db20f19f46ff8ff1a379a86be6263b/packages/flutter_riverpod/lib/src/framework.dart#L308
it seems like using the `_defaultVsync` instead of `_flutterVsync` solves this problem .
by the way,  the same issue happens if you run the example on `web` and switched focus to other tab :

- Example that uses scope that has issue:
https://dartpad.dev/?id=ca3fc0aaebda0810e2359a2e1bad075e
- Example that doesn't use scope , and works as expected
https://dartpad.dev/?id=6b560245e8f214dafd8c03326206752e

Any idea on how to overcome this issue  ?

**Comment by rrousselGit** [comment]
Oh, right, I understand what this issue is about now. Got confused by the example quite a bit.

It's voluntary in a way. It pauses work when the app isn't running. The same goes for how providers stop if they aren't listened. 
There are variants of this that are coming, to pause providers in even more situations. Like https://github.com/rrousselGit/riverpod/issues/1207#issuecomment-1053584327

But a case could be made that `ref.listen` should bypass this, and this should be unique to ref.watch.
Will make a proper issue about this.


In any case, one workaround is to manually read the provider.

**Comment by rrousselGit** [comment]
You could listen to app life cycles, and when the app is detected to be off-screen, you can manually ref.read a provider every few ms.
Obviously, that's nowhere near perfect. It's a workaround though

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/riverpod/issues/2671

It's probably going to take a bit of time before you see a proper fix. I have a big backlog of tasks to do for the 3.0 version. But I'll do it.
