### ISSUE TITLE
Please add more real-world details (e.g. pagination, limits) into the NotifierProvider (remote TODOs) doc

### ISSUE THREAD

**Issue by arnab** [rrousselGit/riverpod#2648]
**Describe what scenario you think is uncovered by the existing examples/articles**

Please add some real-world concerns into the [(Async)NotifierProvider | Riverpod](https://docs-v2.riverpod.dev/docs/providers/notifier_provider) example, such as how pagination should be managed with the `state` of the Notifier. See details below:

**Describe why existing examples/articles do not cover this case**

The current [(Async)NotifierProvider | Riverpod](https://docs-v2.riverpod.dev/docs/providers/notifier_provider) doc provides a simple and easy-to-understand example with `Todos`:

```dart
@riverpod
class AsyncTodos extends _$AsyncTodos {
  Future<List<Todo>> _fetchTodo() async {
    final json = await http.get('api/todos');
    final todos = jsonDecode(json) as List<Map<String, dynamic>>;
    return todos.map(Todo.fromJson).toList();
  }

  @override
  FutureOr<List<Todo>> build() async {
    // Load initial todo list from the remote repository
    return _fetchTodo();
  }
...
}
```

However, in the real world, all the Todos will not be fetched from the API in one go, and instead it'll typically be the first page (and with limits and offsets). 

It's not clear how `state` should be handled for such cases, when the 2nd page (or after) need to be loaded and what the effect would be.

**Comment by rrousselGit** [comment]
>  instead it'll typically be the first page (and with limits and offsets).

Pass limits/offsets as parameter to "build" then. 



In any case, such examples are already planned. So I'll close this as duplicate :)

**Comment by arnab** [comment]
Thanks @rrousselGit !

**Comment by coffeechain23** [comment]
@rrousselGit When I passed a arg in `build` I get an warning of `'AsyncTodosNotifier.build' ('Future<List<PageItemData>> Function(int)') isn't a valid override of 'AsyncNotifier.build' ('FutureOr<List<PageItemData>> Function()').`
