### ISSUE TITLE
Update links to automatically pick-up the title

### ISSUE THREAD

**Issue by kwilliams3** [rrousselGit/riverpod#2655]
**Describe what scenario you think is uncovered by the existing examples/articles**
Reference-style links to other documentation pages should automatically retrieve the current title of the documentation page instead of using a hard-coded value.

**Describe why existing examples/articles do not cover this case**
As it stands, the process for referencing another documentation page is to use a reference-style link with the title of the linked page manually typed out.
Example: \[Title of Page\](linktowebpage)

Instead, the page title should be a programmatic value which would always reflect the current title of the page. This would allow for any future changes to a page's title to stay synced with any other documentation pages that reference it.

**Additional context**
See: https://github.com/rrousselGit/riverpod/pull/2526#discussion_r1224342581

**Comment by rrousselGit** [comment]
Sounds reasonable. Although we need to care about translation.

Fancy doing it?

**Comment by kwilliams3** [comment]
Sounds good 👍

**Comment by rrousselGit** [comment]
Done in https://github.com/rrousselGit/riverpod/pull/2740
