### ISSUE TITLE
Provider not reloading after BottomSheet is closed prematurely

### ISSUE THREAD

**Issue by furkansoylemez** [rrousselGit/riverpod#2659]
Hello, I have a provider that I use to fetch and display data:

```
 part 'favorites_provider.g.dart';
@riverpod
Future<List<UserFavoritedChargePointDto>> favorites(FavoritesRef ref) async {
  final response = await ref.read(getFavoritesUseCaseProvider).call();
  return response;
}
```

I only use this provider on this page:

```
class FavoritesModal extends ConsumerWidget {
  const FavoritesModal({
    super.key,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final favorites = ref.watch(favoritesProvider);

    ref.listen(favoritesProvider, (_, state) {
      context.showSnackBarOnErrorState(state);
    });

    return Column(… in somewhere this page i use favorites.when to manage widgets also
```

This page is displayed in a BottomSheet like this:

```
void _showFavoritesBottomSheet() {
    context.showBottomSheet(
      height: 690.h,
      child: const FavoritesModal(),
    );
  }
```

When I open the BottomSheet, the provider fetches the data as expected and if there's an error, it's caught in the listen callback and a snackbar is displayed. If I wait for the snackbar to disappear and then close the BottomSheet, the next time I open it, it fetches the data again. This is the behavior I want.

However, if I close the BottomSheet before the snackbar disappears, the next time I open it, it doesn't fetch the data. I see it remains in the error state. Since I'm not listening to this provider anywhere else and I close the BottomSheet, I expect the state to reset.

What am I missing here?

**Comment by rrousselGit** [comment]
Are you reopening the bottom sheet while the snack-bar is visible?

That would cause autoDispose to assume that the provider is still visible.


There's a separate issue to deal with such scenario. I'm on mobile, so don't have a link. But it's about refreshing data when new listeners are added

**Comment by furkansoylemez** [comment]
@rrousselGit not really. The same problem persists, even if I wait for the snackbar to disappear to reopen after closing it while the snackbar is visible.

**Comment by rrousselGit** [comment]
You'll have to give a complete example then. I can't help otherwise. It any case, it sounds like it should be a "discussion" or a question on StackOverflow/Discord

**Comment by furkansoylemez** [comment]
@rrousselGit ok thanks for ur time
