### ISSUE TITLE
[Proposal] Add a "riverpod_utilities" package to the environment

### ISSUE THREAD

**Issue by lucavenir** [rrousselGit/riverpod#2686]
**Is your feature request related to a problem? Please describe.**
There's a fair amount of times we're asked to implement and / or show reusable Riverpod features. These include:
- Caching strategies (e.g. `cacheFor`, `disposeDelay`, `aliveUntilDelistened`)
- Callbacks with `Ref`, e.g. `ref.run`
- Infinite scrollview mixins
- Any other mixin we could imagine
- etc.

Instead of just offering snippets or some well documented solutions / cookbooks, why not expose some well tested methods and / or getters?

**Describe the solution you'd like**
Putting these solutions "out of the box" within Riverpod would clutter the namespace.

I propose to create a separate package, e.g. `riverpod_collection`, which collects all sorts of utilities from this ecosystem. That would be great. I like the fact that these utilities are well tested and widely adopted.

Besides offering some out-of-the-box solutions, this approach would publicly disclose the best practices everyone is currently craving for in the documentation.

**Cons*
1. #2576, until approved, prevents implementing mixins "reliably" or rather "easily"
2. Evaluate what's actually needed by the community. These utilities might not be requested, but they come in handy to solve real problems out there. Maybe raise a separate RFC system?
3. These utilities need their own (small) in-line documentation, testing, maintenance
4. This package should be kept in-sync with `riverpod`

**Additional context**
I've been thinking about this for a while, but I see an increasing demand of these utilities, both in Discord and internally.

**Comment by rrousselGit** [comment]
I'm very skeptical about this.

Making such an official package effectively means I would have to maintain all these small utilities. The whole point about those various utilities is that they are a workaround until a proper official solution is made.  

I see little value in having this be an official package. If someone from the community wants to make their own, that's fine. But as an official package, it'd be equivalent to working on soon-to-be-deprecated features, while delaying the actually useful features.

**Comment by lucavenir** [comment]
> soon-to-be-deprecated features

I have no clue of what Riverpod's going to be. I rest my hands and faith into you.

> they are a workaround until a proper official solution is made

A small note. I never knew these were "workarounds". I thought they were meant to be like that, as if stuff like `ref.keepAlive` was made to explore different possibilities.

I'll go ahead and close this for now. If anything, I've discovered that most of the utilities I re-write for my projects aren't meant to be, they're workarounds (while waiting for something bigger I guess?). Thanks again for the quick reply.

**Comment by rrousselGit** [comment]
Well the utilities you cited are mostly workarounds, yes.  
Most of these have associated feature requests to have them be official in some shape or form.

It's just that the associated issues are usually fairly technical, with an available workaround. So there are more important issues to work on generally.
But yes, I do want to implement things like cacheTime/staleTime officially.
