### ISSUE TITLE
How to turn off skipLoadingOnRefresh

### ISSUE THREAD

**Issue by Silfalion** [rrousselGit/riverpod#2687]
**Describe what scenario you think is uncovered by the existing examples/articles**
As mentioned in a previous issue(https://github.com/rrousselGit/riverpod/issues/1411), maintaining the loading state after the first time a result is returned can be quite useful, especially in the case of a "An error occured" and retry button. 

Without the loading state, and while only mapping the state, the user may tap the button multiple times, causing unexpected behavior without a debouncer.

But back to the point, listing or mentioning that that behavior can be enabled through the .when function would be super helpful.

And an extra question if that's ok, you mentioned in the issue above(https://github.com/rrousselGit/riverpod/issues/1411) that one can use "unwrapPrevious", but from the little testing that I did, it works fine even without it. Was that a remnant from the dev version or is it actually necessary to it, please?

**Describe why existing examples/articles do not cover this case**

It's mentioned on a couple of posts on stackoverflow:
https://stackoverflow.com/a/74934407/8568263

And I believe also in the api reference(although I couldn't find it as I'm writing this)

However, it seems like it would deserve a little section somewhere on the official website's docs, maybe even part of the pull-to-refresh example?

**Additional context**

**Comment by rrousselGit** [comment]
Technically speaking, "when" itself is going to disappear. So the flag will go away too.

But I do plan to make a page to show various implementations of spinners/error handling

**Comment by Silfalion** [comment]
oh, true, I totally forgot about that. Is there a plan to put that flag somewhere else?

And the spinners implementations sounds awesome, if you have a rough draft somewhere, maybe people, myself included, could make code snippets or part of it.

**Comment by rrousselGit** [comment]
It's on my to-do list of things to draft. There should be one in the following days

**Comment by Silfalion** [comment]
Got it. Thank you

**Comment by rrousselGit** [comment]
I'll close this in favor of the upcoming draft (should be coming somewhere this week)
