### ISSUE TITLE
Algolia search does not index v2 documentation

### ISSUE THREAD

**Issue by cbenhagen** [rrousselGit/riverpod#2690]
**Describe the bug**
It is not possible to search the v2 docs as they are currently not indexed by Algolia.

**To Reproduce**
Search for "generation" on https://docs-v2.riverpod.dev

**Expected behavior**
You should find a lot of pages talking about code generation

The best fix for this would be to just move or drop v1 docs and use v2 by default.

**Comment by rrousselGit** [comment]
That's just a side-effect of it being in development (the docs-v2 prefix)
Both branches use the same Algolia project. So the search is synched with master

I've looked into this before, but I don't think there's an easy fix.

**Comment by rrousselGit** [comment]
I guess I should sort out the small things remaining to do it.

**Comment by rrousselGit** [comment]
I'll close this and instead find a way to merge the branches

**Comment by cbenhagen** [comment]
Ok thanks! :)
