### ISSUE TITLE
Simplify selecting from AsyncValue providers

### ISSUE THREAD

**Issue by dvoloshyn** [rrousselGit/riverpod#2692]
**Is your feature request related to a problem? Please describe.**

The code below does not work as I expect it to work because `whenData` propagates `isLoading` and, as the result, ListView is always rebuilt 2 times even if count didn't actually change.
```
// I have an async provider of items that could be invalidated/refreshed
final items = FutureProvider();
// and a provider with the number of those items
final count = items.select((value) => value.whenData((items) => items.length));
...
// that are used to rebuild the ListView when changed during refresh
RefreshIndicator(
  onRefresh: () async => ref.invalidate(items)
  child: ListView(itemCount: count),
)
```

**Describe the solution you'd like**
Add configuration parameters to `AsyncValueX.whenData()` in a similar way as it's done for `AsyncValueX.when()`.
But I would welcome any better solution from your side as well.

**Describe alternatives you've considered**
Reimplementing `whenData()` myself with customized behavior

**Comment by rrousselGit** [comment]
Rebuilding on loading _is_ expected, since you selected it too by returning an AsyncValur.

Are you maybe looking for `select((v) => v.data)`?

**Comment by dvoloshyn** [comment]
But, If I use `when()` instead of `whenData()` it will  not trigger rebuilds on refresh because it will drop `isLoading` and always return `AsyncData` with the same value. I just expected the same behavior from `whenData()` as well. Is it possible to add a parameter like it's done for `when()`?

**Comment by rrousselGit** [comment]
> But, If I use when() instead of whenData() it will not trigger rebuilds on refresh because it will drop isLoading 

But you asked for this, by complaining how the UI rebuilds twice.


I don't understand what you're asking for then

**Comment by dvoloshyn** [comment]
I'll try to be more precise.
The code of the `select` below triggers rebuild only when length of the list actually changes.
```
final count = list.select(
  (value) => value.when(
    data: (list) => AsyncValue.data(list.length),
    error: AsyncValue<int>.error,
    loading: AsyncValue<int>.loading,
  ),
);
```
I want to be able to write it as a short one liner with something like `whenData()`

**Comment by rrousselGit** [comment]
What you shared is what `whenData` does.

**Comment by dvoloshyn** [comment]
Unfortunately, no, `whenData` is not based on `when`, it's based on `map`. Source code is below. Notice, that `isLoading, d.error, d.stackTrace` is also copied into `AsyncData` making it trigger rebuilds.
```
AsyncValue<R> whenData<R>(R Function(T value) cb) {
    return map(
      data: (d) {
        try {
          return AsyncData._(
            cb(d.value),
            isLoading: d.isLoading,
            error: d.error,
            stackTrace: d.stackTrace,
          );
        } catch (err, stack) {
          return AsyncError._(
            err,
            stackTrace: stack,
            isLoading: d.isLoading,
            value: null,
            hasValue: false,
          );
        }
      },
      error: (e) => AsyncError._(
        e.error,
        stackTrace: e.stackTrace,
        isLoading: e.isLoading,
        value: null,
        hasValue: false,
      ),
      loading: (l) => AsyncLoading<R>(),
    );
  }
```

**Comment by rrousselGit** [comment]
> Unfortunately, no, whenData is not based on when, it's based on map.

When and Map are the same thing pretty much. That doesn't matter.

The exact same implementation could use when instead

> Notice, that isLoading, d.error, d.stackTrace is also copied into AsyncData making it trigger rebuilds. 

What's wrong with that?

**Comment by rrousselGit** [comment]
Honestly I don't get which rebuild you apparently want to avoid.

When I gave you a way to avoid the rebuild, you then complained that the widget doesn't rebuild in a specific case. So I don't understand what you're talking about.

**Comment by dvoloshyn** [comment]
Aha, I think my comment after
> Are you maybe looking for select((v) => v.data)?

might have confused you. It was not meant as a reply to your suggestion but to provide more details.

Let me compare both solutions:
- `select((v) => v.items?.length)` will rebuild only when the length changes (what I need), but I loose the ability to show initial loading indicator and error messages
- `select((v) => v.whenData((items) => items.length))` allows me to show initial loading indicator and error messages but would unnecessarily rebuild 2 times on every refresh/invalidate even if the length didn't change because `AsyncData.isLoading` will change to `true` and then to `false` (I want to avoid this)

If you think that my use case is too rare and supporting it directly in `riverpod` will not benefit the community I am fine to close this conversation.

**Comment by rrousselGit** [comment]
You could do:

```dart
final (:isInitialLoading, :data) = ref.watch(provider.select((v) => (
    isInitialLoading: v.isLoading && !v.isRefreshing && !v.isReloading, 
    data: v.data,
 ),
);
```

**Comment by rrousselGit** [comment]
You can alternatively do it in two lines using two ref.watch to select the isInitialLoading & data separately

**Comment by dvoloshyn** [comment]
Thank you, both options you mentioned will work.
I also found a third one that works as well:
```
select(
  (value) => value.when(
    data: (items) => AsyncValue.data(items.length),
    error: AsyncValue<int>.error,
    loading: AsyncValue<int>.loading,
  ),
)
```

**Comment by rrousselGit** [comment]
I'd discourage using AsyncValue here, because its properties wouldn't quite bit set realistically.
isRefreshing/isReloading wouldn't be set, nor would `AsyncLoading.error` if refreshing after an error.

In any case, there's a solution. So I'll close this :)

**Comment by est7** [comment]
@dvoloshyn I used to have the same problem, Probably use StateNotifier<PageState> is enough

**Comment by danielAsaboro** [comment]
> @dvoloshyn I used to have the same problem, Probably use StateNotifier is enough

StateNotifier is actively being discourage for Riverpod going forward
