### ISSUE TITLE
Breaking change with ref.refresh / ref.listen  from riverpod 1.x -> 2.x

### ISSUE THREAD

**Issue by sperochon** [rrousselGit/riverpod#2704]
**Describe the bug**
Hello,

Today, I'm migrating my existing code from riverpod 1.0.4 to 2.3.6

My code is using the working behavior in riverpod 1.0.4 that refreshing a StateProvider as

`ref.refresh(myStateProvider);`

and listening it with:

```
ref.listen<int>(myStateProvider, (_, __) {
  print('!!! into the listener !!!');
});
```

should ALWAYS force a "refresh" of the provider and the listener is ALWAYS called (= **even with same value**)

But in riverpod 2.3.6, this behavior is not working anymore. I suspect this issue:
https://github.com/rrousselGit/riverpod/issues/1560
and your fix to be the reason:
https://github.com/rrousselGit/riverpod/commit/ac155eb259e9bd55ea0135b7dd8f837343ab9716

But your "fix" of this "issue" (which is not one IMO) on riverpod 2.0 appears to be a big BREAKING CHANGE, not a simple fix as mentioned onto the changelog page:
https://pub.dev/packages/flutter_riverpod/changelog#200

So, either this fix is a regression (compare to v1.x) and should be reverted,

or this is the real new intended behavior in v2.x and so it should be clearly indicated as a BREAKING CHANGE into the changelog/doc (and if so, could you tell me the way to force the refresh in all cases)

**To Reproduce**

Use the code below with riverpod v1.0.4 and tap several times onto the 'INVALIDATE' button to see the behavior (= see the print into the console)
Then, switch riverpod package version to v2.3.6 and tap several times onto the 'INVALIDATE' button and see the new behavior (= see the missing print into the console)

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

final myStateProvider = StateProvider((ref) => 0);

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final a = ref.watch(myStateProvider);
    ref.listen<int>(myStateProvider, (_, __) {
      print('!!! into the listener !!!');
    });
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            Text("Value : $a"),
            ElevatedButton(
              onPressed: () {
                ref.refresh(myStateProvider);
              },
              child: Text("INVALIDATE"),
            ),
            ElevatedButton(
              onPressed: () {
                ref.read(myStateProvider.notifier).state++;
              },
              child: Text("INCREMENT"),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Expected behavior**
The same as v1.x   ;-)

Thanks a lot!

**Comment by kietcthe** [comment]
I think this tends to be a bug fix instead of a breaking change.
and you can achieve the old behavior with the below code:
```

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

final myStateProvider = StateProvider((ref) => 0);

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final a = ref.watch(myStateProvider);
    ref.listen<int>(myStateProvider, _listenCallback);
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            Text("Value : $a"),
            ElevatedButton(
              onPressed: () {
                final afterRefreshState = ref.refresh(myStateProvider);
                _listenCallback(a, afterRefreshState);
              },
              child: Text("INVALIDATE"),
            ),
            ElevatedButton(
              onPressed: () {
                ref.read(myStateProvider.notifier).state++;
              },
              child: Text("INCREMENT"),
            ),
          ],
        ),
      ),
    );
  }

  void _listenCallback(int? previous, int next) {
    print('!!! listen with previous = $previous & next = $next !!!');
  }
}

```

I hope it will help.

**Comment by rrousselGit** [comment]
This is a bug fix, yes.

The fact that refresh forcibly notified listeners was a bug. It should've respected the notification filters.

**Comment by sperochon** [comment]
Ok then, Thanks for your both replies @kietcthe and @rrousselGit
