### ISSUE TITLE
Deprecated terminal command at the Getting started V2 documentation page

### ISSUE THREAD

**Issue by DemX86** [rrousselGit/riverpod#2706]
The documentation page at https://github.com/rrousselGit/riverpod/edit/docs-v2/website/docs/getting_started.mdx has the line:
```Run the code-generator with flutter pub run build_runner watch.```

When I run this command with Flutter 3.10.5 I get the warning:
```Deprecated. Use dart run instead.```

I think it's a good idea to change the command to recommended:
```dart run build_runner watch```

**Comment by rrousselGit** [comment]
This was fixed. Thanks!
