### ISSUE TITLE
getting error "StateError (Bad state: Future already completed)"

### ISSUE THREAD

**Issue by LaserDevWork** [rrousselGit/riverpod#2710]
**Describe the bug**
getting error "StateError (Bad state: Future already completed)" when reading ref.read(authControllerProvider.notifier).googleSignIn(); on click
**To Reproduce**
@riverpod
// 4. extend like this
class AuthController extends _$AuthController {
  // 5. override the [build] method to return a [FutureOr]
  @override
  FutureOr<UserInfoModel> build() {
    // 6. return a value (or do nothing if the return type is void)
    return UserInfoModel.empty();
  }

  Future<void> googleSignIn() async {
    state = const AsyncValue.loading();
    // Add the new todo and reload the todo list from the remote repository
    state = await AsyncValue.guard( signInWithGoogle);

  }
}

**Expected behavior**
user provider based userinfo model, uses google auth to sign in

**Comment by rrousselGit** [comment]
Your provider likely got disposed immediately.
You probably want to `ref.watch/listen` the `authControllerProvider` provider somewhere

**Comment by LaserDevWork** [comment]
Thank you, do you mean in a widget? Because I am in a few widgets

**Comment by LaserDevWork** [comment]
resolved
