### ISSUE TITLE
How to override State of provider

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/riverpod#2723]
My code

```dart
@Riverpod(keepAlive: true)
class UserNotifier extends _$UserNotifier {
  @override
  UserState build() {
    return const UserState(token: '');
  }

  void load() {
    state = state.copyWith(loading: true);
  }

  void unload() {
    state = state.copyWith(loading: false);
  }
}
```

How can I override this provider with a custom UserState ?

**Comment by rrousselGit** [comment]
Use `overrideWithNotifier` to return a custom `UserNotifier` with a unique `build` implementation that returns whatever you want.

A simpler way to do this will be available at some point. But for now, that's the way to do

**Comment by tbm98** [comment]
> Use `overrideWithNotifier` to return a custom `UserNotifier` with a unique `build` implementation that returns whatever you want.
> 
> A simpler way to do this will be available at some point. But for now, that's the way to do

Can i pass data through UserNotifier constructor and get it from build function ? 
Never tried

**Comment by tbm98** [comment]
> > Use `overrideWithNotifier` to return a custom `UserNotifier` with a unique `build` implementation that returns whatever you want.
> > A simpler way to do this will be available at some point. But for now, that's the way to do
> 
> Can i pass data through UserNotifier constructor and get it from build function ? Never tried

Just tried and it works :D
