### ISSUE TITLE
hooks_riverpod ^2.3.6 incompatible with flutter_hooks ^0.19.0 

### ISSUE THREAD

**Issue by tusharbhambere** [rrousselGit/riverpod#2724]
**Describe the bug**
Resolving dependencies...
Because hooks_riverpod 2.3.6 depends on flutter_hooks ^0.18.0 and no versions of hooks_riverpod match >2.3.6 <3.0.0, hooks_riverpod ^2.3.6 requires flutter_hooks ^0.18.0

flutter_hooks ^0.19.0 and hooks_riverpod ^2.3.6, version solving failed

**To Reproduce**

Added Latest Version of packages

hooks_riverpod ^2.3.6
flutter_hooks ^0.19.0

**Expected behavior**
Need  hooks_riverpod latest version working with flutter_hooks package

**Comment by rrousselGit** [comment]
Done in a PR. Thanks!
