### ISSUE TITLE
`ref.exists` return `true` after invalidating a provider.

### ISSUE THREAD

**Issue by hasanmhallak** [rrousselGit/riverpod#2729]
**Describe the bug**
basically the title.   

Is this behavior intended?  

If you try Calling invalidate on a provider and then reuse it, the `onResume` method gets called, which weird as the docs says *A life-cycle for when a provider is listened again after it was paused (and [onCancel] was triggered).* but `onCancel` never gets called.

Does this means that invalidate method will force the provider to pause and return to its original state, thus when we try to listen to it again its build method gets called simulating that the provider is disposed but never actually remove it from the hash map where the providers gets stored?  

The thing here is when using `autoDispose` provider everything works as expected.

**To Reproduce**
<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'main.g.dart';

@Riverpod(keepAlive: true)
int fetchItem(FetchItemRef ref) {
  ref.onDispose(() => print('dispose'));
  ref.onCancel(() => print('onCancel'));
  ref.onResume(() => print('onResume'));
  return 5;
}

void main() {
  runApp(
    const ProviderScope(child: MaterialApp(home: MyHomePage())),
  );
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(onPressed: () {
        print(ref.exists(fetchItemProvider));
      }),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.of(context)
                .push(MaterialPageRoute(builder: (_) => MyHomePage2()));
          },
          child: Text('next'),
        ),
      ),
    );
  }
}

class MyHomePage2 extends ConsumerStatefulWidget {
  const MyHomePage2({super.key});

  @override
  ConsumerState<MyHomePage2> createState() => _MyHomePage2State();
}

class _MyHomePage2State extends ConsumerState<MyHomePage2> {
  ProviderContainer? _container;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _container!.invalidate(fetchItemProvider);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _container = ProviderScope.containerOf(context);
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(onPressed: () {
        print(ref.exists(fetchItemProvider));
      }),
      body: Center(
        child: Text(ref.watch(fetchItemProvider).toString()),
      ),
    );
  }
}

```

</details>
<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**
I think there should be a clear way to manually dispose a provider completely aside form `autoDispose`  because in some use cases using auto dispose could create a problem of losing the data.

**Comment by AhmedLSayed9** [comment]
I face the same behavior.

Hence that if the provider disposed because of a dependency change, it'll still return true for `ref.exists` but `onResume` will not trigger:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'main2.g.dart';

@Riverpod(keepAlive: true)
int fetchItem(FetchItemRef ref) {
  ref.watch(depProvider);
  print('build');
  ref.onDispose(() => print('dispose'));
  ref.onCancel(() => print('onCancel'));
  ref.onResume(() => print('onResume'));
  return 5;
}

@Riverpod(keepAlive: true)
class Dep extends _$Dep {
  @override
  int build() => 0;

  increase() => state = state + 1;
}

void main() {
  runApp(
    const ProviderScope(child: MaterialApp(home: MyHomePage())),
  );
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print(ref.exists(fetchItemProvider));
        },
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextButton(
              onPressed: () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const MyHomePage2()));
              },
              child: const Text('next'),
            ),
            TextButton(
              onPressed: () {
                ref.read(depProvider.notifier).increase();
              },
              child: const Text('increase dep'),
            ),
          ],
        ),
      ),
    );
  }
}

class MyHomePage2 extends ConsumerWidget {
  const MyHomePage2({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(onPressed: () {
        print(ref.exists(fetchItemProvider));
      }),
      body: Center(
        child: Text(ref.watch(fetchItemProvider).toString()),
      ),
    );
  }
}
```

**Comment by hasanmhallak** [comment]
hey @AhmedLSayed9, thank you for the input. However I don't see how this is relevant.  

In the snippet you provided, the `fetchItemProvider` will never be disposed because of `@Riverpod(keepAlive: true)` but rather `canceled` when no other listener is registered. Which is as expected.

If you meant that overall when using `autoDispose` and a dependency changed the `onDispose` will be called and `build` will be called immediately after it, it's the normal behavior as riverpod will replace the old instance of the provider with the new one, thus calling `ref.exists` should return `true`. 

What I was talking about the is how `invalidate` behave. See in this issue #1295, @rrousselGit  said that  `invalidate` should dispose the provider manually. in other words it should call the dispose method to close any resources and then remove the provider instance form `_stateReaders` hash map (which is where the providers are being cached) just like `autoDispose` does, so when we call `ref.exists` we just checking if the provider instance is still in that hash map or not.
```dart
  bool exists(ProviderBase<Object?> provider) {
    final element = _stateReaders[provider]?._element;

    return element != null;
  }
```  

Now the problem here if we set `@Riverpod(keepAlive: false)` everything works as expected and the provider instance will be removed form `_stateReaders` when there is no listeners, but if we set it to `true` and try to handle disposing the providers ourself by using `invalidate` as suggested here #1295  even if there is no listeners the provider won't be disposed properly but rather just *resets its state*, the `dispose` method will be called but the provider will never be removed form `_stateReaders`.

**Comment by rrousselGit** [comment]
It's been around for a while but I never bothered to fix it. Will do for 3.0

**Comment by hasanmhallak** [comment]
@rrousselGit you mean how `invalidate` behave or `ref.exists` ?

**Comment by rrousselGit** [comment]
`ref.invalidate` will be updated to destroy the element of keepAlive providers if they have no listener.

**Comment by AhmedLSayed9** [comment]
> hey @AhmedLSayed9, thank you for the input. However I don't see how this is relevant.

> In the snippet you provided, the fetchItemProvider will never be disposed because of @Riverpod(keepAlive: true) but rather canceled when no other listener is registered. Which is as expected.

It's the exact issue :)
`fetchItemProvider` will be disposed when a dependency change that's how `ref.watch` works. and If that provider has no listeners, it'll not build again (which is the case when you press `increase dep` button in my sample) , but `ref.exists` somehow return true.

**Comment by hasanmhallak** [comment]
hey @rrousselGit, it seems like this issue still exist in `flutter_riverpod: ^2.5.1` and can be reproduced with the same code sample I attached in the original issue.

I will also provide code snippet for when not using the code generation.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    const ProviderScope(
      child: MaterialApp(
        home: MyHomePage(),
      ),
    ),
  );
}

class MyWidget extends ConsumerStatefulWidget {
  const MyWidget({super.key});

  @override
  ConsumerState<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends ConsumerState<MyWidget> {
  late final ProviderContainer container;

  @override
  void initState() {
    container = ProviderScope.containerOf(context, listen: false);
    super.initState();
  }

  @override
  void dispose() {
    container.invalidate(sProvider);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(sProvider);
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Text('You have pushed the button this many times: $state'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          ref.read(sProvider.notifier).add();
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class MyHomePage extends ConsumerStatefulWidget {
  const MyHomePage({super.key});

  @override
  ConsumerState<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends ConsumerState<MyHomePage> {
  void _incrementCounter() async {
    await Navigator.of(context)
        .push(MaterialPageRoute(builder: (_) => MyWidget()));

    await Future.delayed(const Duration(seconds: 1));
    print('does exist: ${ref.exists(sProvider)}');
    print('internal state: ${ref.read(sProvider.notifier).internalState}');
    print('notifier state: ${ref.read(sProvider)}');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Center(
        child: Text('first Page'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: const Icon(Icons.arrow_forward),
      ),
    );
  }
}

class SNotifier extends Notifier<int> {
  int internalState = 0;
  @override
  build() {
    return 0;
  }

  void add() {
    state = state + 1;
    internalState = state;
  }
}
final sProvider = NotifierProvider<SNotifier, int>(SNotifier.new);
```
</details>

when using `AutoDisposeNotifier` the `internalState` will be set back to 0 indicating that the `SNotifier` instance is a new one and the old one was removed from memory.

**Comment by rrousselGit** [comment]
Please open new issues.

And explain what exactly the issue with this snippet is. I'd need more information :)
