### ISSUE TITLE
Allow for awaiting the completion of `build()`in generated AsyncNotifiers

### ISSUE THREAD

**Issue by timcreatedit** [rrousselGit/riverpod#2733]
I find myself writing a lot of `AsyncNotifier`s where I would want a method on the Notifier to make sure that the current state of the  Provider is `AsyncData` to perform some operation. Consider this example:

```dart
@riverpod
class Test extends _$Test {
  @override
  Future<String> build() async {
    await Future.delayed(const Duration(seconds: 1));
    return "Hello World";
  }

  /// Meaningless example of an operation that depends on the state
  Future<void> writeToDatabase() async {
    if (state case AsyncData(:value)) {
      await ref.read(databaseProvider).write(value);
    }
  }
}
```

However, this option has the problem of silently failing when `writeToDatabase()` is called too early.

**Describe the solution you'd like**
I would like an easy way of awaiting the provider I'm in, similar to `ref.watch(testProvider.future)` for `FutureProvider` and `StreamProvider`. This could look something like:

```dart
@riverpod
class Test extends _$Test {
  @override
  Future<String> build() async {
    await Future.delayed(const Duration(seconds: 1));
    return "Hello World";
  }

  /// Meaningless example of an operation that depends on the state
  Future<void> writeToDatabase() async {
    final value = await state.future;    
    await ref.read(databaseProvider).write(value);
  }
}
```

I don't actually think `AsyncValue` is the right place for it, but it could also be a method on `Ref`, similar to `ref.listenSelf()`.

**Describe alternatives you've considered**
1. Make sure there is a value before calling `writeToDatabase()`, but that moves a lot of logic into the UI, since `ref.watch(testProvider.notifier)` doesn't contain any information about the state.
2. Throw a `StateError` or something similar instead of failing silently, but that ends up having the same problem as 1, since the UI would have to deal with it.
3. Add a `Completer` to the `AsyncNotifier`. This works obviously, but it's a bit of error-prone overhead imo for a very common usecase.

**Comment by rrousselGit** [comment]
Are you looking for `this.future`?

```dart

  /// Meaningless example of an operation that depends on the state
  Future<void> writeToDatabase() async {
    final value = await future;    
    await ref.read(databaseProvider).write(value);
  }
```

**Comment by timcreatedit** [comment]
I think there is still a small opportunity for improvement with non-generated async providers for doing this in a `ref.listen` callback, but maybe that's too specific or I have overlooked something again

**Comment by catalunha** [comment]
Very well said @timcreatedit 

>   I thought I had understood the ins and outs of riverpod,

I'm a Riverpod evangelist in Brazil. And there really is still a lot to discover about Riverpod. I'm studying and trying to gather as much documentation and cases as possible to help colleagues who are new to this river of possibilities.
