### ISSUE TITLE
Build method overriding AutoDisposeAsyncNotifierProviderFamily is called endlessly

### ISSUE THREAD

**Issue by HirokiIshimori** [rrousselGit/riverpod#2745]
**Describe the bug**
Build method overriding AutoDisposeAsyncNotifierProviderFamily is called endlessly.
(version: 2.3.6)

**To Reproduce**

```dart
final todoListProvider =
  AutoDisposeAsyncNotifierProviderFamily<TodoListAsyncNotifier, Category, Map<String, Object>>(TodoListAsyncNotifier.new);

class TodoListAsyncNotifier extends AutoDisposeFamilyAsyncNotifier<Category, Map<String, Object>> {

  @override
  FutureOr<Category> build(Map<String, Object> arg) async {
    final list = await ref.read(todoListRepositoryProvider).fetch();
    print(list);
    return Category(id: arg['id'] as String, name: arg['categoryName'] as String, items: list, updatedAt: arg['date'] as DateTime);
  }
}
```

Category is a freezed generated Model class.
When you watch this provider, print will be called infinitely...

**Expected behavior**
Never call build indefinitely.

**Comment**
I apologize if my usage is incorrect.

**Comment by rrousselGit** [comment]
The problem is unlkely to be the provider.
Rather, it's the consumer.

You most likely did not respect the parameter restriction of family https://riverpod.dev/docs/concepts/modifiers/family#parameter-restrictions

Instead of a Map, you should use a Tuple

**Comment by HirokiIshimori** [comment]
thanks.

I tried it with Tuple.

```dart
final todoListProvider =
AutoDisposeAsyncNotifierProviderFamily<TodoListAsyncNotifier, Category, Tuple3<String, String, DateTime>>(TodoListAsyncNotifier.new);

class TodoListAsyncNotifier extends AutoDisposeFamilyAsyncNotifier<Category, Tuple3<String, String, DateTime>> {

  @override
  FutureOr<Category> build(Tuple3<String, String, DateTime> arg) async {
    final list = await ref.read(todoListRepositoryProvider).fetch();
    print(list);
    return Category(id: arg.item1, name: arg.item2, items: list, updatedAt: arg.item3);
  }
}
```

It seems that this bug occurs when there is a Datetime parameter.

What should I do when using Datetime?

**Comment by HirokiIshimori** [comment]
thanks.

> If you only care about minutes, you should have milliseconds set to 0

As you say, I was able to do this successfully by setting the milliseconds and below to 0.

But why is this?

Do you know what the reason is?

**Comment by rrousselGit** [comment]
You always pass a different value to the provider. So you always get a new result.
