### ISSUE TITLE
Code-generated NotifierProviderFamily always passes Null argument

### ISSUE THREAD

**Issue by arrowsmith001** [rrousselGit/riverpod#2746]
**Describe the bug**

When using a generated provider for a class that extends FamilyNotifier, the family argument is received as Null and the error 

`type 'Null' is not a subtype of type '[whatever]' in type cast` 

is thrown. This is also true of FamilyAsyncNotifier.

**To Reproduce**

I have provided a minimal example app that runs the same widget with a hand-made provider vs a generated one. I have included the generated file, but run build_runner again if you like. Tested on web and desktop.

https://github.com/arrowsmith001/riverpod-family-example/tree/master

![Screenshot 2023-07-17 093059](https://github.com/rrousselGit/riverpod/assets/68137859/3479b1e6-1b82-4925-8559-bec58db405ef)

**Expected behavior**

The two widgets running side-by-side should function the same, but the ungenerated version doesn't throw the error while the generated version does. In short, the generated family notifier provider does not behave the same as a hand-made one.

**Comment by rrousselGit** [comment]
You're using the code-generator incorrectly.

You shouldn't define that `ungeneratedNotifierProvider `

And your `StringFromIntFamilyNotifier ` should extend `_$StringFromIntFamilyNotifier `
