### ISSUE TITLE
Providing a more visual description of how some of the examples fit together.

### ISSUE THREAD

**Issue by freemansoft** [rrousselGit/riverpod#2761]
**Describe what scenario you think is uncovered by the existing examples/articles**
The examples would be better training documents if they had diagrams.  I can submit a PR with a couple of png diagrams for examples if you are interested.  Currently have diagrams for counter, random_number and todo. 

**Describe why existing examples/articles do not cover this case**
The examples have good comments but not great entry points prior to the code.

**Additional context**
I created diagrams for the examples to help me understand how they go together.  _Random number_ and _counter_ are essentially the same application with completely different approaches. The Todo application has a lot more moving parts. I intend to create a video using the diagrams so they won't go to waste if you don't want them in the repo.

![Riverpods Todo Example](https://github.com/rrousselGit/riverpod/assets/1217160/22244885-49f0-4cb0-be3d-e9dc81a2fb3a)

Here is a video using similar drawings to explain the Counter and Random Number examples. [Explaining Riverpod on Flutter using two examples from the Riverpod repository](https://youtu.be/ZEzy9eWDdT4)

Here is a video using this drawing to explain how [the Todo example uses Riverpod](https://youtu.be/P9s3yG1vtgs)

**Comment by rrousselGit** [comment]
Hello!

If we want to add diagrams, I'd use Riverpod_graph for this.
If that's not readable enough, the package should be updated accordingly
