### ISSUE TITLE
unexpected behavior of StreamProvider

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [rrousselGit/riverpod#2762]
**Describe the bug**

As you can see from the videos StreamBuilder keeps the last result. Although I did `skipLoadingOnRefresh: true, skipLoadingOnReload: true,` StreamProvider every time refreshing. 

### StreamBuilder

[Video 1](https://github.com/rrousselGit/riverpod/assets/49102327/388e3f25-dbb7-48f4-9d5a-99975e823b64)

### StreamProvider with .`when`

[Video 2](https://github.com/rrousselGit/riverpod/assets/49102327/a0651279-7be8-4714-9c9b-f0e31a62aad5)

minimal reproducible example: https://github.com/Shahmirzali-Huseynov/riverpod_streamprovider_example

**Expected behavior**
I don't want to show loading every time. I want to do what StreamBuilder does.

**Comment by rrousselGit** [comment]
Reusing the previous value when changing a "family" parameter is not supported.

You'll have to manually keep track of it in the widget. Iy should be simple with Flutter_hooks

**Comment by Shahmirzali-Huseynov** [comment]
@rrousselGit  can you give an example code or some tips ? and in this situation what do you suggest using SteamBuilder ?

**Comment by rrousselGit** [comment]
Using StreamBuilder you'd need to find a way to cache the stream, which is quite error prone.


You could have:

```dart
AsyncValue<T> useWithPrevious(AsyncValue<T> value) {
  final prev = useRef<AsyncValue<T>>();
  if (prev.value == null) return prev.value = value;

  return prev.value = value.copyWithPrevious(prev.value!);
}
```

You can then do:

```dart
final result = useWithPrevious(ref.watch(search(text));
```

The previous state should be preserved by doing so.

**Comment by Shahmirzali-Huseynov** [comment]
```
 HookConsumer(
                    builder: (context, ref, child) {
                     final previousSearchResult = useState<AsyncValue<List<BookModel>>>(AsyncValue.loading());
                      final searchResult = ref.watch(searchResultStreamProvider(searchText.value)).copyWithPrevious(previousSearchResult.value);
                      previousSearchResult.value = searchResult;
```

I did like this before you write. I will try yours too thanks for the quick reply/answer to my question.

**Comment by Shahmirzali-Huseynov** [comment]
> Using StreamBuilder you'd need to find a way to cache the stream, which is quite error prone.
> 
> You could have:
> 
> ```dart
> AsyncValue<T> useWithPrevious(AsyncValue<T> value) {
>   final prev = useRef<AsyncValue<T>>();
>   if (prev.value == null) return prev.value = value;
> 
>   return prev.value = value.copyWithPrevious(prev.value!);
> }
> ```
> 
> You can then do:
> 
> ```dart
> final result = useWithPrevious(ref.watch(search(text));
> ```
> 
> The previous state should be preserved by doing so.

it is custom hook?

**Comment by Shahmirzali-Huseynov** [comment]
your solution working good too thanks 👍
