### ISSUE TITLE
FutureProvider with Generic Type

### ISSUE THREAD

**Issue by thanhdatvo** [rrousselGit/riverpod#2769]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to implement GenericType to FutureProvider
```
final provider = FutureProvider.family.autoDispose<void, T>((ref, data) async {
```

The only way is to wrap it in a class
```
class Wrapper<T>{
   final provider = FutureProvider.family.autoDispose<void, T>((ref, data) async {
   ...
}
```

**Describe the solution you'd like**
Allow implementing GenericType to FutureProvider

**Comment by rrousselGit** [comment]
Generics are part of the upcoming 3.0 version, and are only with the code-generator syntax
