### ISSUE TITLE
Support import aliases

### ISSUE THREAD

**Issue by nosmirck** [rrousselGit/riverpod#2777]
**Describe the bug**
When using a named import (for instance `import 'package:http/http.dart' as http;`) the riverpod generator ignores the named import.

**To Reproduce**
```
// import named http
import 'package:http/http.dart' as http;
...
@riverpod
http.Client httpClient() => http.Client();
```

**Expected behavior**
Generated file should use the named import and not have errors.

**Comment by AndreiBadescu** [comment]
Any updates regarding this issue?

**Comment by rrousselGit** [comment]
This is planned. But there are other things before in the queue (docs & bug fixes).

**Comment by Tulleb** [comment]
I am still facing this issue using the latest Riverpod versions . Am I the only one?

Extract of my `.podspec.yaml`:
>   hooks_riverpod: ^2.3.7
>   riverpod_annotation: ^2.6.1
> 
> dev_dependencies:
>   riverpod_generator: ^2.6.3
>   riverpod_lint: ^2.6.3
