### ISSUE TITLE
Set `debugState` for tests

### ISSUE THREAD

**Issue by MuTe33** [rrousselGit/riverpod#2778]
**Is your feature request related to a problem? Please describe.**

During tests I need some certain state in order to test other methods logic. Since I often have an initialisation method that sets the state. 

For that reason, currently I have to mock the initialisation logic first (prepare the state) in order to test my other method. At some places that is super cumbersome. 

**Describe the solution you'd like**

We currently have access to the getter `debugState`. Can we also have a setter like `setDebugState` that wraps the setter `state` under the hood but that is not marked as protected? 

It's a quick solution that would work. I'm open for other suggestions and happy to contribute in any way.

**Additional context**

**Comment by rrousselGit** [comment]
Sounds reasonable. It's a low priority for me though. Fancy making a PR?

**Comment by MuTe33** [comment]
Awesome! Yes, for sure. I'll be opening the PR anytime this week

**Comment by rrousselGit** [comment]
`Notifier.state` is now `@visibleForTesting` – both the getter and setter.
