### ISSUE TITLE
GoRouter Riverpod Extension

### ISSUE THREAD

**Issue by moshOntong-IT** [rrousselGit/riverpod#2783]
**Is your feature request related to a problem? Please describe.**
GoRouter is good to use especially for deep linking and nested navigation when we are implementing a path , we have to do this
``` dart
   GoRoute(
            path: "/",
            redirect: (context, state) {
              return "/home";
            },
            builder: (context, state) => const HomeScreen(),
          ),
```

We can only use a riverpod here in the HomeScreen widget (if the widget is extend either ConsumerWidget or ConsumerStatefuleWidget), but I would like to request that in GoRoute builder/redirect function paramater will also have `ref` here. This is so useful in the redirect parameter for example is that

``` dart
   GoRoute(
            path: "/",
            redirect: (context, state,ref) {
              final isAuthenticated = ref.read(authenticationProvider).isAuthenticated;
              if(isAuthenticated) return "/home";
      
              return "/login";
            },
            
          ),
```

This will become convenient when we have `ref` here. Is it possible to create a new package that is gorouter_riverpod

**Comment by Hamza-Imran75** [comment]
You can do something like this to get access to ref:




```dart
final goRouterProvider = Provider<GoRouter>((ref) {

  return GoRouter(
    initialLocation: '/',
    debugLogDiagnostics: false,
    redirect: (context, state) async {
      return null;
    },
    routes: [
      GoRoute(
        path: '/',
        name: AppRoute.home.name,
        builder: (context, state) => const MainScreen(),
      ),
    ],
  );
});
```

And then call it like this:
```dart
...
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final goRouter = ref.watch(goRouterProvider);
    return MaterialApp.router(
      routerConfig: goRouter,
      ....
```

**Comment by rrousselGit** [comment]
A router package is doable, but I don't plan on doing it.

There are workaround, cf above.
So I'll close this

**Comment by nosmirck** [comment]
@moshOntong-IT if what you care about is reading the provider inside the redirector, simply get the ref from context like this:

```dart
final ref = ProviderScope.containerOf(context);
```

You can add a handy extension to BuildContext like this:

```dart
extension BuildContextRef on BuildContext {
  T read<T>(ProviderListenable<T> provider) {
    return ProviderScope.containerOf(this).read(provider);
  }
}
```

and simply use context as the good old provider did:

```dart
  final isAuthenticated = context.read(authenticationProvider).isAuthenticated;
```

**Comment by rrousselGit** [comment]
^ `ProviderScope.containerOf` isn't something you should rely on. Especially not to implement your own `context.read`


The approach mentioned earlier about making a separate provider is best.
I'd suggest a small tweak: using `ref.listen`


```dart
final goRouterProvider = Provider<GoRouter>((ref) {
  late final authentication = ref.listen(authenticationProvider, (_, __) {});

  return GoRouter(
    redirect: (context, state) {
      if (authentication.read().isAuthenticated) {...}
    },
    routes: [
      ...
    ],
  );
});

```

This small change ensures that `authenticationProvider` will not "auto dispose" while `goRouterProvider` is in use.
