### ISSUE TITLE
ConsumerBuilder support nullable return type

### ISSUE THREAD

**Issue by a1573595** [rrousselGit/riverpod#2784]
**Is your feature request related to a problem? Please describe.**
When I use FloatingActionButton with the Consumer widget, I can't return null when I want to hide FloatingActionButton, I know I can return another widget like SizedBox, but this way no animation of the button will appear.

**Describe the solution you'd like**
Nullable consumerBuilder?

**Describe alternatives you've considered**
Return SizedBox but no animation of the button.

**Comment by rrousselGit** [comment]
this makes no sense.

Although the parameter expected by FloatingButton is nullable, thr return value expected by StatelessWidget.build isn't.

That is not feasible
