### ISSUE TITLE
Error when reload data with overrides ProviderScope

### ISSUE THREAD

**Issue by phucdth12a** [rrousselGit/riverpod#2785]
I see one demo so great. it dont render when add new item to list. But when refresh data or change data with new length less than old length it show error Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1.

This is demo: https://github.com/rei-codes/advanced_list_riverpod?ref=flutterawesome.com

**Comment by rrousselGit** [comment]
It would help if you could give a reproduction example and steps to run the example; along with a stacktrace of the error.

**Comment by rrousselGit** [comment]
Note that I'm not responsible for this demo. This is a third-party example. As such, I'll close this

You should instead create this issue on the github repository linked.
