### ISSUE TITLE
Document what is a provider dependency

### ISSUE THREAD

**Issue by woprandi** [rrousselGit/riverpod#2794]
I've often seen this term but I don't know what it means and no mention in the docs.
Does it avoid to do a ```ref.watch``` when you don't need the returned value but still want to rebuild the provider when another changed ?

**Comment by catalunha** [comment]
I've also found vague dependency stuff.
I would love to know how to use this feature.
I've been through some State Managers and because I respect Remi a lot, I'd like to stop at Riverpod and really understand how things work to develop good codes with Riverpod and be able to help other colleagues, like Remi does with us.

**Comment by rrousselGit** [comment]
It's a general programming term. The meaning is the same as in DI (Dependency Injection).  
If a provider uses something, that something is a dependency of the provider, no matter how the object is used.

watch vs listen vs read does not matter in this discussion. In fact, Riverpod doesn't matter either.    
Widgets have dependencies too for example. Say you call Theme.of in a widget, then your widget has a dependency on ThemeData.

**Comment by rrousselGit** [comment]
The IDE documentation covers this

https://pub.dev/documentation/riverpod_annotation/latest/riverpod_annotation/AutoDisposeFutureProviderFamily/dependencies.html
https://pub.dev/documentation/riverpod/latest/riverpod/AutoDisposeStateNotifierProviderFamily/dependencies.html

**Comment by catalunha** [comment]
Sorry.
I understand the theory.
But let's go.
There is a simple and clear example of using dependency.
