### ISSUE TITLE
riverpod_lint 2.0.0 claims Dart 2.17 support but cannot satisfy this

### ISSUE THREAD

**Issue by babbage** [rrousselGit/riverpod#2799]
**Describe what scenario you think is uncovered by the existing examples/articles**
The Changelog on pub.dev for riverpod_lint states 'Support analyzer 6.0.0' but in fact this should state 'Requires analyzer 6.0.0'. Furthermore, Analyzer 6.0.0+ requires Dart 3.0 therefore riverpod_lint also now requires Dart 3.0, not the Dart 2.17 support stated on pub.dev.  

**Describe why existing examples/articles do not cover this case**
This should be updated to allow users to avoid unnecessary upgrade-warnings of incompatible versions-downgrade cycles.

**Comment by rrousselGit** [comment]
> not the Dart 2.17 support stated on pub.dev.

Where is such statement coming from?

I don't see anywhere saying riverpod_lint is <3.0.0 compatible

**Comment by rrousselGit** [comment]
> to avoid unnecessary upgrade-warnings of incompatible versions-downgrade cycles.

What warning is this?

**Comment by babbage** [comment]
pub.dev under the versions tab lists the Min Dart SDK for each package, and for riverpod_lint 2.0.0 it is listed as Dart 2.17:
&nbsp;
<img width="856" alt="Screenshot 2023-08-07 at 1 23 10 PM" src="https://github.com/rrousselGit/riverpod/assets/376937/40f68603-488a-480d-91ff-9300c2380a8e">
&nbsp;

I see the source of this will be the environment setting in riverpod_lint/pubspec.yaml, which is:

> environment:
>  sdk: ">=2.17.0 <3.0.0"

Attempting to enable riverpod_lint: ^2.0.0 in a Dart 2.18 code base resulted in the following warnings for me from `melos bootstrap`:

> Because riverpod_lint >=2.0.0 depends on analyzer ^6.0.0 and freezed 2.3.2 depends on analyzer ^5.2.0, riverpod_lint >=2.0.0 is incompatible with freezed 2.3.2.
> So, because [my_module] depends on both freezed 2.3.2 and riverpod_lint ^2.0.0, version solving failed.

I can resolve this issue, no problem. I just wanted to let you know that the compatibility for riverpod_lint is being incorrectly reported. 👍🏼

**Comment by babbage** [comment]
The same issue is present in Riverpod Generator.

**Comment by rrousselGit** [comment]
Constraints are updated for the Riverpod v3 version. It'll be fixed naturally in due time
