### ISSUE TITLE
Unusual Behavior in Riverpod Flutter: Double Execution When Using ref.invalidate and read

### ISSUE THREAD

**Issue by joicodev** [rrousselGit/riverpod#2803]
**Describe the bug**
I have noticed a disparity in behavior between using a provider without autodispose and one with autodispose in my application.

In particular, I am using the AsyncNotifier with the "@Riverpod(keepAlive: true)" annotation and not using autodispose.

On startup, when I make the first call to the provider after loading the app, everything works fine. Only a single call is made and the value is set like this:

![image](https://github.com/rrousselGit/riverpod/assets/31873662/2073e114-f693-45e4-aca2-3724b67c9c3a)

However, when I leave this page and use ref.invalidate to then go to the login screen, the following happens:

"♻️[registerUserProvider] disposed👋" (this is fine, since I'm printing the onDispose of a provider.)

Then, on my second visit to the registration page, I call the provider again and notice a change in their status. Here it is executed twice:

![image](https://github.com/rrousselGit/riverpod/assets/31873662/3058c9b8-71f9-4933-947c-c73d4184cf2e)

It is important to note that the value of "previousValue" is initially null and then changes to "isLoading: true, value: null", finally returning to "value: null".

Here when I do the invalidate of the provider:

![image](https://github.com/rrousselGit/riverpod/assets/31873662/a8f89cbd-203a-450c-8a5f-a657b4da1bcc)

Here when I send him to call

![image](https://github.com/rrousselGit/riverpod/assets/31873662/e903f2e9-fbe5-4eb2-91af-927d42793bb0)

**Comment by rrousselGit** [comment]
I see nothing wrong here. Your provider rebuild, and since its async, its loading state needs to be handled. Therefore two values are emitted

The provider didn't rebuild twice. It emitted two values. That's not quite the same

**Comment by joicodev** [comment]
Okay I understand. I was adding async in the build, so it was returning the future.

But when I do ref.invalidate, apparently it is not being invalidated correctly, it continues to keep the previous value and when I ask (before calling it again after invalidating it), it tells me that it exists. => ref.exist
