### ISSUE TITLE
Reading a Provider | ref.read both suggested and discouraged for the same use-case

### ISSUE THREAD

**Issue by TDuffinNTU** [rrousselGit/riverpod#2809]
**Describe what scenario you think is uncovered by the existing examples/articles**
[Current page](https://riverpod.dev/docs/concepts/reading)

Across the document it discourages using ref.watch() to assign callbacks to classes such as buttons:
![image](https://github.com/rrousselGit/riverpod/assets/43959652/40a112e9-21a1-430d-a516-9f0612aa47f6)

Later on, it explicitly discourages ref.read() in the same scenario, and encourages using ref.watch to assign a callback to a button:
![image](https://github.com/rrousselGit/riverpod/assets/43959652/e7a720aa-ffdf-42dd-8b7f-c2c0bdb91bec)

Considering how ref.watch is encouraged to avoid stale references to providers, and the implication that you can infact use ref.watch to assign callbacks to other widgets, should there be _any_ suggestion in the docs at all of using ref.read() within the build() method of widget? From what I can tell that's the one case where ref.read() shouldn't be used, much like how you shouldn't use it within the build() method of a provider.

**Comment by rrousselGit** [comment]
> Across the document it discourages using ref.watch() to assign callbacks to classes such as buttons:

No that's not what it says.  
It discourages using ref.watch inside event handlers. 
The following is fine:

```dart
Button(
  onPressed: () => ref.watch(...)
)
```

Which is different from the follow (not fine):

```dart
final increment = ref.watch(notifier).increment);

Button(
  onPressed: () => increment(),
)
```



That's the same logic for ref.read, but reversed.   
Using ref.read, the first case is discouraged and the second is fine.

**Comment by TDuffinNTU** [comment]
Ah that makes more sense, thanks :)
