### ISSUE TITLE
StreamNotifier does not keep its watched providers alive (infinite re-build loop)

### ISSUE THREAD

**Issue by penguisnt** [rrousselGit/riverpod#2829]
AsyncNotifier is not being kept alive when being `watch()`'ed  during `build()` of a StreamNotifier, causing infinite rebuilds of the StreamNotifier. 

Using `keepAlive: true` on the AsyncNotifier OR `watch`ing the AsyncNotifier from the UI fixes the issue (by keeping the AsyncNotifier alive).

**To Reproduce**
```
@riverpod
class Name extends _$Name {
  @override
  Future<String> build() async {
    print("NameProvider: building name provider");
    return "Alice";
  }
}

@riverpod
class NameStreamTransformer extends _$NameStreamTransformer {
  @override
  Stream<String> build() async* {
    print("NameStream: building stream transformer");
    final alice = ref.watch(nameProvider).when(
          data: (data) => data,
          loading: () => "Loading",
          error: (error, stackTrace) => "Error",
        );

    print("NameStream: name value is $alice");


    while (true) {
      print("NameStream: emitting from infinite loop");
      // yield from some callback, for now, just emit.
      yield "a value";
      await Future.delayed(1.seconds);
    }
  }
}
```
**Widget (Note that we are NOT observing the `nameProvider` **
```
 Text(ref.watch(nameStreamTransformerProvider).when(
                        data: (data) => data,
                        error: (error, stackTrace) => "error",
                        loading: () => "Loading",
                      ))

```

** Logs **
```
NameProvider: building name provider
NameStream: name value is Loading
NameStream: emitting from infinite loop
NameStream: building stream transformer
NameProvider: building name provider
NameStream: name value is Loading
NameStream: emitting from infinite loop
NameStream: building stream transformer
NameProvider: building name provider
NameStream: name value is Loading
NameStream: emitting from infinite loop
NameStream: building stream transformer
```

**Expected behavior**

Expected behavior is that StreamProvider keeps its dependencies alive, since they are being watched, in line with AsyncNotifier watching an AsyncNotifier.

[**Discussion on discord**](https://discord.com/channels/765557403865186374/801938753877704774/1142856047858552872)

**Comment by rrousselGit** [comment]
This is technically """expected""".
It's a side-effect of `async*`  not invoking the function synchronously when the stream is listened. The logic is delayed by a frame, which is enough to cause your dependencies to get disposed.

This wouldn't happen if you used `ref.watch(provider.future)` or `ref.listen`

Should get fixed by https://github.com/rrousselGit/riverpod/issues/1253, so closing in favour of that other issue

**Comment by penguisnt** [comment]
Thanks for the response, looking forward to the change.

Followup, (ack to the `if you used ref.watch(provider.future)`), but what would you recommend if it's not a AsyncNotifier and there is no `.future`?

An example I am using is to simply fetch Host and Port from SharedPrefs, which is done synchronously. 
In the `build() async*`, I use

`      final HostAndPortData hostAndPort = ref.watch(hostAndPortProvider);` to get this synchronous data, but it rebuilds on loop unless I mark hostAndPortProvider with `keepAlive: true`, which I don't want to do because it could leak info outside the intended Widget tree

**Comment by rrousselGit** [comment]
You might want to increase the "cacheTime". It's another way of doing it https://github.com/rrousselGit/riverpod/issues/1664
There are some code snippets in that issue to do so.
