### ISSUE TITLE
Flutter Riverpod Provider does not update widgets outside of widget where target action took place

### ISSUE THREAD

**Issue by windmillcode0** [rrousselGit/riverpod#2835]
**Describe the bug**
Project resources here. [Github project repo](https://github.com/MichaelOdumosu57/songs_flutter_app)
[Video repro](https://www.youtube.com/watch?v=4DqqabyLnLk_
I have also tried setState and StateNotifierProvider to no avail. Greetings everyone quick issue in in my songdescwidget I have an onTap method
```
      onTap: () {
        songDetailRP.song = widget.song;
      },
```
and in my songdetailpage widget I have an updatePageMethod
  ```
void updatePage(RP, defaultLayoutRP) {
    RP.song = widget.song ?? RP.song;
    defaultLayoutRP.title = RP.song.title;
    defaultLayoutRP.shuffleIsPresent = false;
    print("updating page");
  }
```
and its its build method I have
```
final RP = ref.watch(SongDetailRiverpodProvider); 
return  Consumer(builder: (context, ref, child) {
                return PlaySongBox(RP.song.mainColor, paramHeight: 270);
              })),      
```                                                                                      
Can someone help explain why I hit onTap the songDetailPage does not update?

The screen should update as inteded 

**Addtl resources**
[Github project repo](https://github.com/MichaelOdumosu57/songs_flutter_app/tree/riverpod_exteral_widget_issue)
[Video repro](https://www.youtube.com/watch?v=4DqqabyLnLk_

Please dont close the ticket I will update with a minimal repro when I have time

**Comment by AhmedLSayed9** [comment]
You're setting the same oldSong value again:
```dart
var newValue = SongDetailRiverpodProviderValue(song: oldSong);  // oldSong should be widget.song
```

Also, StateProvider/StateNotifierProvider/ChangeNotifierProvider are legacy.
You should use the modern [NotifierProvider/AsyncNotifierProvider](https://docs-v2.riverpod.dev/docs/providers/notifier_provider) instead.

**Comment by windmillcode0** [comment]
I am using regular Provider, and this is the onTap method
```
      onTap: () {
        setState(() {
          songDetailRP.song = widget.song;
        });
      },
```

**Comment by windmillcode0** [comment]
I have attempted to use the Notifier provider example but still to no avail, you can see the example here https://github.com/MichaelOdumosu57/songs_flutter_app/tree/riverpod_external_widget_issue_with_notifierprovider

**Comment by AhmedLSayed9** [comment]
You should make a minimal sample that reproduces the issue.

**Comment by rrousselGit** [comment]
None of the code snippets you included in the issue contain `obj.state = something`.   
Riverpod relies on the `state` setter to be invoked to notify listeners. If you did not invoke `.state =`, nothing happens.

Neither your onTap nor your updatePage do so.

You might want to read the upcoming side-effect docs page https://deploy-preview-2740--river-pod.netlify.app/docs/essentials/side_effects

**Comment by windmillcode0** [comment]
Were at a conference still working on the widget values

**Comment by windmillcode0** [comment]
we ended using AsyncNotifier
