### ISSUE TITLE
riverpod with flutter_hooks may use StatelessWidget

### ISSUE THREAD

**Issue by tomasweigenast** [rrousselGit/riverpod#2849]
`flutter_hooks` was created to avoid the cost of creating StatefulWidgets, but `HookConsumerWidget` is a `StatefulWidget`. Can it be changed?

**Comment by davidmartos96** [comment]
It's not so much about the "cost" of creating StatefulWidgets, but about the ability to reuse stateful logic.
StatefulWidget is also a very lightweight structure.
