### ISSUE TITLE
asData?.value should be always mapped to null when loading

### ISSUE THREAD

**Issue by 23doors** [rrousselGit/riverpod#2850]
**Describe the bug**

provider.asData?.value is returning previous value even if isLoading is true.

**To Reproduce**

```dart
// declare some basic provider (reproduced with Family provider but I guess it should occur without Family as well)
@riverpod
Future<int?> someData(SomeDataRef ref, {required int something}) async {
    await Future.delayed(Duration(seconds: 10));
    return something;
}

...
// in build:

final data = ref.watch(someDataProvider(0));
print("${data.isLoading} ${data.asData?.isLoading} ${data.asData?.value != null}");

...
// invalidate provider somewhere else
ref.invalidate(someDataProvider(0));
```

Once value is there, after invalidate `isLoading` will be = `true`, but `data.asData?.value` will still be holding a value (it will not map it to null as expected). So before new value is loaded you get `true true true` as output (which in theory should never happen).

Even with .map you get:
```dart
    data.map(
      data: (v) {
        print("hasData and yet isLoading=${data.isLoading}");
        return null;
      },
      error: (v) {
        print("hasError");
        return null;
      },
      loading: (v) {
        print("isLoading");
        return null;
      },
    );
```

```
flutter: hasData and yet isLoading=true
flutter: hasData and yet isLoading=false
```

`loading` is never fired in this case.

**Expected behavior**

When isLoading = true, asData?.value should be null (which is how docs describe it as well).

**Comment by rrousselGit** [comment]
That's the expected behavior of AsyncData.
During a refresh, an AsyncData with isLoading=true is returned.

What you can do is `asyncValue.unwrapPrevious().value`

**Comment by 23doors** [comment]
```
  /// If you do not want to return previous value during loading/error states,
  /// consider using [asData] :
  ///
  /// ```dart
  /// ref.watch(provider).asData()?.valueOrNull;
  /// ```
```

```
  /// Upcast [AsyncValue] into an [AsyncData], or return null if the [AsyncValue]
  /// is in loading/error state.
```

If that's expected behavior, than it is completely different from what docs describe it to be.

**Comment by rrousselGit** [comment]
Good call, I've fixed this on master.

**Comment by AhmedLSayed9** [comment]
@rrousselGit `valueOrNull` docs should be updated too
https://github.com/rrousselGit/riverpod/blob/6031730a580eef328f08186000774e0695ed7499/packages/riverpod/lib/src/common.dart#L516
