### ISSUE TITLE
Error: Undefined name 'mustBeOverridden'

### ISSUE THREAD

**Issue by stephane-couget** [rrousselGit/riverpod#2853]
**Describe the bug**
with  flutter_riverpod: 2.3.9, compilation displays :

../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/auto_dispose.dart:94:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/auto_dispose.dart:94:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/auto_dispose.dart:100:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/auto_dispose.dart:100:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/base.dart:138:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/base.dart:138:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/base.dart:144:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/async_notifier/base.dart:144:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/stream_notifier/auto_dispose.dart:97:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/stream_notifier/auto_dispose.dart:97:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/stream_notifier/base.dart:115:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/stream_notifier/base.dart:115:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/auto_dispose.dart:89:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/auto_dispose.dart:89:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/auto_dispose.dart:95:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/auto_dispose.dart:95:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/base.dart:158:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/base.dart:158:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/base.dart:164:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/base.dart:164:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/stream_provider/base.dart:125:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/bin/hosted/pub.dev/riverpod-2.3.9/lib/src/stream_provider/base.dart:125:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/user/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1157

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/user/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**To Reproduce**
flutter doctor -v                                                                                                                    1 ✘  4s  15:48:14 
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F82 darwin-x64, locale fr-FR)
    • Flutter version 3.7.12 on channel stable at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (il y a 4 mois), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • SM T970 (mobile) • R52R40AJJ6R • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 116.0.5845.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by rrousselGit** [comment]
I forgot to bump the minimum `meta` version needed

Make sure to run `flutter pub upgrade`

**Comment by Guillaume-Fortin** [comment]
Ok, I have this problem because i have some projects use flutter 3.7. (meta 1.8.0)
After migration to flutter 3.10, the error disappear because @MustBeOverridden flag is known

**Comment by rrousselGit** [comment]
I'll pull down the version using riverpod:>=1.4.0 and update the constraint to >=1.9.0

**Comment by Guillaume-Fortin** [comment]
It works with my projects  which use flutter 3.7.
flutter_riverpod blocked to version 2.3.7

Thank you

**Comment by stephane-couget** [comment]
Perfect. Thanks you gentlemen

**Comment by 2018dayanan** [comment]
If you want to temporarily replace all @mustBeOverridden annotations with @override, you can do it quickly using a find and replace operation in your IDE or text editor.
