### ISSUE TITLE
error @MustBeOverridden

### ISSUE THREAD

**Issue by randy1023** [rrousselGit/riverpod#2854]
**Describe the bug**
hello i am running riverpod in a counter exercise but when i applied the flutter_riverpod package the application runs and i get the following error  ../../../../.pub-cache/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/base.dart:158:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/riverpod-2.3.9/lib/src/notifier/base.dart:158:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden

**To Reproduce**
this is my code import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:widget_app/presentation/providers/counter_provider.dart';

class CounterScreen extends ConsumerWidget {
  static const name = 'counter_screen';
  const CounterScreen({super.key});

 @override
  Widget build(BuildContext context, WidgetRef ref) {
    final int counterValue = ref.watch(counterProvider);
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Counter Screen',
          style: Theme.of(context).textTheme.titleLarge,
        ),
      ),
      body: Center(child: Text('Valor: $counterValue')),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

**Expected behavior**

**Comment by randy1023** [comment]
yes you have reason, i was using an old flutter version but i already update it and my code working thanks

**Comment by 2018dayanan** [comment]
If you want to temporarily replace all @mustBeOverridden annotations with @override, you can do it quickly using a find and replace operation in your IDE or text editor.
