### ISSUE TITLE
(Multi)AsyncValueWidget

### ISSUE THREAD

**Issue by thunderbug1** [rrousselGit/riverpod#2858]
**Is your feature request related to a problem? Please describe.**
I have found this blog post [here](https://codewithandrea.com/articles/async-value-widget-riverpod/) which is about a widget that allows us to replace the repetitive definition of loading and error handlers inside of '.when' with a single widget that does that.

Is a widget like this available in the riverpod library itself which I haven't found?

I also tried to extend this concept to a MultiAsyncValueWidget, which can wait for multiple riverpod providers and their values, similar to the MultiProvider widget from the Provider package. Without a widget like this, one ends up with ugly nested .when calls.
What is the recommended solution for that?

**Describe the solution you'd like**

```import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class MultiAsyncValueWidget extends ConsumerWidget {
  final List<FutureProvider> providers;
  final Widget Function(List) builder;

  const MultiAsyncValueWidget({
    Key? key,
    required this.providers,
    required this.builder,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    List<dynamic> data = [];
    bool allDataLoaded = true;
    bool anyError = false;
    String? errorMsg;

    for (var provider in providers) {
      final value = ref.watch(provider);

      if (value.isLoading) {
        allDataLoaded = false;
      } else if (value.hasError) {
        anyError = true;
        errorMsg = value.error.toString();
        break;
      } else if (value.hasValue) {
        data.add(value.value);
      }
    }

    if (anyError) {
      return Center(
        child: Text(
          errorMsg ?? "An error occurred",
          style: const TextStyle(color: Colors.red),
        ),
      );
    }

    if (!allDataLoaded) {
      return const Center(child: CircularProgressIndicator());
    }

    return builder(data);
  }
}
```

**Additional context**
In many cases we need values from multiple providers to render the page but with the .when function we need to redefine the handling of loading and errors again and again. I think that there must be an elegant solution for this.

**Comment by rrousselGit** [comment]
The issue for this is https://github.com/rrousselGit/riverpod/issues/67.   
I'm trying to avoid the idea of a MultiAsyncValueWidget, as providers should generally not passed as parameter to widgets.
