### ISSUE TITLE
Combining requests section

### ISSUE THREAD

**Issue by Silfalion** [rrousselGit/riverpod#2867]
**Describe what scenario you think is uncovered by the existing examples/articles**
This is not exactly about a new problem, but just asking if I can start a PR about this section of the documentation, if nobody's working on it(is it the right place to ask?):

https://docs-v2.riverpod.dev/docs/essentials/combining_requests

**Describe why existing examples/articles do not cover this case**

**Additional context**

**Comment by rrousselGit** [comment]
Hello!
Sure, sounds good :)
