### ISSUE TITLE
riverpod_generator v2.3.0 issues

### ISSUE THREAD

**Issue by j-fritsch** [rrousselGit/riverpod#2869]
After upgrading to riverpod_generator v2.3.0, I started seeing at least two new bugs.

### First issue:

```
Could not build the precompiled application for the device.
Error (Xcode): {my_path}/databases.g.dart:176:19: Error: Duplicated parameter name 'name'.
```

This one occurs because we have a parameter by the name of `name`, which clashes with the new parameter named `name`. Changing our parameter to something else does workaround the issue.

Our code looks like this
```
@riverpod
Future<MyUserDatabase> _userDatabaseImpl(_UserDatabaseImplRef ref, String name) async {
  ...
}
```

Here is the generated output with the two parameters named `name`:

```
_UserDatabaseImplProvider._internal(
  super._createNotifier, {
  required super.name,
  required super.dependencies,
  required super.allTransitiveDependencies,
  required super.debugGetCreateSourceHash,
  required super.from,
  required this.name,
}) : super.internal();
```

This is the new code I think is causing the issue:
https://github.com/rrousselGit/riverpod/commit/41f020d6181c25268556fcadd95837386b5f7197#diff-1feebb3c0c7ab334096f2a887eb87e0d749e7c21c0752ad8729ba2289d3f1957R187

### Second issue

```
Could not build the precompiled application for the device.
Error (Xcode): {my_path}/controller.g.dart:115:19: Error: An optional named parameter can't start with '_'.
```

Some generated files seem to be including constructors that look like this:

```
MyProvider._internal(
  super._createNotifier, {
  required super.name,
  required super.dependencies,
  required super.allTransitiveDependencies,
  required super.debugGetCreateSourceHash,
  required super.from,
  required this.myId,
}) : super.internal();
```

That `super._createNotifier` parameter seems to be the issue. Removing the underscore fixes it. I don't think the "optional" part of that message is correct. I think this might be the dart issue for that: https://github.com/dart-lang/sdk/issues/51472

**Comment by j-fritsch** [comment]
I added another code block from the generated code for the first issue. The problems seem to come from the generated files. Is that what you are looking for?

**Comment by j-fritsch** [comment]
OK, no problem. We can use a different name for the parameter to workaround the naming collision.

The second issue is also seen with the provider I mentioned in the first issue. Here is that code, with the parameter now updated to "databaseName" instead:

```
/// See also [_userDatabaseImpl].
class _UserDatabaseImplProvider
    extends AutoDisposeFutureProvider<MyUserDatabase> {
  /// See also [_userDatabaseImpl].
  _UserDatabaseImplProvider(
    String databaseName,
  ) : this._internal(
          (ref) => _userDatabaseImpl(
            ref as _UserDatabaseImplRef,
            databaseName,
          ),
          from: _userDatabaseImplProvider,
          name: r'_userDatabaseImplProvider',
          debugGetCreateSourceHash:
              const bool.fromEnvironment('dart.vm.product')
                  ? null
                  : _$userDatabaseImplHash,
          dependencies: _UserDatabaseImplFamily._dependencies,
          allTransitiveDependencies:
              _UserDatabaseImplFamily._allTransitiveDependencies,
          databaseName: databaseName,
        );

  _UserDatabaseImplProvider._internal(
    super._createNotifier, {
    required super.name,
    required super.dependencies,
    required super.allTransitiveDependencies,
    required super.debugGetCreateSourceHash,
    required super.from,
    required this.databaseName,
  }) : super.internal();

  final String databaseName;

  @override
  Override overrideWith(
    FutureOr<MyUserDatabase> Function(_UserDatabaseImplRef provider) create,
  ) {
    return ProviderOverride(
      origin: this,
      override: _UserDatabaseImplProvider._internal(
        (ref) => create(ref as _UserDatabaseImplRef),
        from: from,
        name: null,
        dependencies: null,
        allTransitiveDependencies: null,
        debugGetCreateSourceHash: null,
        databaseName: databaseName,
      ),
    );
  }

  @override
  AutoDisposeFutureProviderElement<MyUserDatabase> createElement() {
    return _UserDatabaseImplProviderElement(this);
  }

  @override
  bool operator ==(Object other) {
    return other is _UserDatabaseImplProvider &&
        other.databaseName == databaseName;
  }

  @override
  int get hashCode {
    var hash = _SystemHash.combine(0, runtimeType.hashCode);
    hash = _SystemHash.combine(hash, databaseName.hashCode);

    return _SystemHash.finish(hash);
  }
}
```

**Comment by rrousselGit** [comment]
I'm not looking for the generated code. I'm looking for your provider, what you wrote.

**Comment by simjounhax** [comment]
> I'm not looking for the generated code. I'm looking for your provider, what you wrote.

I have same issue. I can provider source code I actually wrote.

@Riverpod(keepAlive: true)
Future<Map<String, dynamic>> collectionGroup(
  CollectionGroupRef ref,
  {
    required String name,
    String? child
  }
) async {
  var response = await ref.watch(dioClientProvider).post(
    "https://${ref.watch(firebaseRegionProvider)}-${ref.watch(projectIdProvider)}.cloudfunctions.net/GetCollectionGroup",
    data: {"name": name, "child": child},
  );

  if (200 != response.statusCode) {
    throw HttpException("[${response.statusCode}] ${response.statusMessage}");
  }

  var data = response.data as Map<String, dynamic>;

  return data;
}

in this code, name parameter 'name' is duplicated to 'name' variable in auto-generated code.

**Comment by problematicconsumer** [comment]
The problem occurs when an argument of a provider has the same name as a reserved provider property (like name).
```dart
class ProfileDetailNotifier extends _$ProfileDetailNotifier {
  @override
  Future<String> build(
    String id, {
    String? name, // generated provider will have 2 "name" properties
  }) async {
    return "";
  }
}
```
For now, renaming conflicting arguments solves the problem. I'd suggest adding a lint rule to warn is such cases.

**Comment by rrousselGit** [comment]
It's a temporary issue. V3 could make a breaking change to have provider.overrideWith  defined as `(ref, params) => value)` for providers with arguments.

That would remove the name clash

**Comment by j-fritsch** [comment]
Here is an example of some code that causes the second issue.
```
class MyUserDatabase {}

@riverpod
Future<MyUserDatabase> _userDatabaseImpl2(_UserDatabaseImpl2Ref ref, String _) async {
  return MyUserDatabase();
}
```
It turns out the issue was actually caused by our code and our usage of the underscore in our parameter. The intent was to denote that it was unused, but that was poor naming on our part for a few reasons. Since it worked in previous versions, it wasn't immediately obvious that could be the issue.

So the solution to both of the issues is better naming on our end.

Apologies for taking your time but I appreciate the quick responses, thank you!
