### ISSUE TITLE
AutoDisposeFutureProvider invalidating as many as calling ref.invalidate

### ISSUE THREAD

**Issue by Abduraimbek** [rrousselGit/riverpod#2872]
riverpod_annotation: ^2.1.4
flutter_riverpod: ^2.3.10
riverpod_generator: ^2.3.1

**AutoDisposeFutureProvider** invalidating as many as calling ref.invalidate, here is my code:

```dart
var invalidateCount = 0;

@riverpod
FutureOr<Object?> fetchForTest(FetchForTestRef ref) async {
  invalidateCount++;

  // fetch api
  await Future.delayed(const Duration(seconds: 3));

  throw invalidateCount;
}

class BuildTestBody extends ConsumerWidget {
  const BuildTestBody({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final asyncValue = ref.watch(fetchForTestProvider);

    return asyncValue.when(
      data: (data) {
        return Center(
          child: Text(data.toString()),
        );
      },
      error: (error, stackTrace) {
        final time = DateFormat('hh:mm:ss').format(DateTime.now());
        print('Invalidate count: $error, Time: $time');

        return Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(error.toString()),
              TextButton(
                onPressed: () {
                  ref.invalidate(fetchForTestProvider);
                },
                child: const Text('Refresh'),
              ),
            ],
          ),
        );
      },
      loading: () {
        return const Center(
          child: CircularProgressIndicator.adaptive(),
        );
      },
    );
  }
}
```

Above code throws an error as an integer. But if I press **Refresh** button after 2 seconds it'll wait another 3 seconds, summary it'll wait 5 seconds from the first pressing. 
I think it should not call the second press when it is loading. If a user presses this button every 2 seconds he/she will not see the result never.

Here console:

```bash
I/flutter (32181): Invalidate count: 1, Time: 07:50:35
I/flutter (32181): Invalidate count: 6, Time: 07:50:45
```
I've pressed **Refresh** button 5 times after initialization about in every 2 seconds and the result shown after 10 seconds.

If I missunderstood anything please any ideas?
Thanks, for reply.

**Comment by rrousselGit** [comment]
Sounds expected. Why would invoking `invalidate` _not_ invalidate the provider?

**Comment by Abduraimbek** [comment]
I think it is invalidating correctly. Is my following view correct: it should not reinvalidate while loading state?

**Comment by rrousselGit** [comment]
The problem with not invalidating during loading states is, that could cause the result to be out of date.   
You may call "invalidate" because something changed which should be reflected in the provider. So if the provider didn't refresh accordingly, it may still be using old data.


Generally you would want to:
- debounce the provider
- cancel pending network requests when a new one is performed

**Comment by Abduraimbek** [comment]
In my real app, I have cancel pending network as you mentioned. And in situtation that internet is slow or something (also backend can send error), I'm throwing an error in my ```AutoDisposeFutureProvider```. And __when.Error__ I show to user as above code. User presses **Refresh** button continuosly and app cannot fetch data from server at all.
How can I solve this, should I invalidate when only __AsyncValue.loading==false__ ?

**Comment by rrousselGit** [comment]
You could do that if you want.

**Comment by Abduraimbek** [comment]
Thanks! But it is a workaround or it should work like this?

**Comment by rrousselGit** [comment]
That's your call. I don't really have an answer to give you here.

**Comment by Abduraimbek** [comment]
Ok, thanks very much!
