### ISSUE TITLE
Key not used inside consumer

### ISSUE THREAD

**Issue by Naveed-dev30** [rrousselGit/riverpod#2874]
**Describe the bug**
Key that is passed to consumer widget is not being used in Consumer Widget.

**To Reproduce**
1. Make a Consumer Widget
2. Send a key to Consumer Widget
3. Find widget by key
4. Widget is not found.

`Consumer(
    key: _key,
    builder: (BuildContext context, WidgetRef ref, Widget? child) {
      return SizedBox();
    },
  );`

**Expected behavior**
The widget cannot be find or tracked using the provided key.

**Comment by rrousselGit** [comment]
This is working fine for me. Tests are passing on my side, and the value is correctly passed. Sounds like the issue is on your side
