### ISSUE TITLE
The generated notifier typedef is AutoDisposeNotifier<dynamic>

### ISSUE THREAD

**Issue by serhii-k** [rrousselGit/riverpod#2875]
```
@riverpod
class Test extends _$Test {
  @override
  AppLocalizations? build() => null;
}
```

**Problem**
For some reason:
```typedef _$Test = AutoDisposeNotifier<dynamic>;```

**Details**
AppLocalizations is a class generated by following the default [Internationalizing Flutter apps](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization) instructions.

It is located here:
.dart_tool/flutter_gen/gen_l10n/app_localizations.dart

To generate this file, it seems sufficient to complete only Steps 1-4 from the [Adding your own localized messages](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#adding-your-own-localized-messages) section, and to add the `flutter_localizations` dependency.

**Comment by rrousselGit** [comment]
There are quite a few issues about it. This is a known problem, and not much can be done about it.

**Comment by serhii-k** [comment]
Thank you for the explanation, Remi. It's not a big deal.
