### ISSUE TITLE
ref.watch not working with parameterized provider

### ISSUE THREAD

**Issue by agufagit** [rrousselGit/riverpod#2880]
**Describe the bug**
ref.watch not triggered with parameterized provider

**To Reproduce**

```dart
@riverpod
Stream<void> watchTest(WatchTestRef ref, String id) {
  return Stream<void>.periodic(const Duration(seconds: 1), (x) => x).take(2);
}

@riverpod
String? getTest(GetTestRef ref, String id) {
  ref.watch(watchTestProvider(id));
  print("test");
  return id;
}
```
```dart
class TestWidget extends ConsumerWidget {
  const TestWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.watch(getTestProvider("1"));
    print("watch");
    return Container();
  }
}
```

this prints
"test"
"watch"
"watch"
"test"
"test"

**Expected behavior**
Expecting printing
"test"
"watch"
"test"
"watch"
"test"
"watch"

**Comment by rrousselGit** [comment]
The result of `getTest` didn't change. At all points, it returns "1".
Therefore the associated widget wasn't rebuilt.


If anything, the surprising part is that you see "watch" twice.
But I've just tested and I correctly see "watch" only once. Chances are something else on your side triggered that second "watch".

So all is fine :)

**Comment by agufagit** [comment]
If I comment out line `ref.watch(watchTestProvider(id));` in `getTest`, it prints out `test` two times, is it normal?  I'm expecting only 1 time.
