### ISSUE TITLE
Comparing two same AsyncValue objects always returns false

### ISSUE THREAD

**Issue by minhnt3** [rrousselGit/riverpod#2884]
**Describe the bug**
The current implementation of the `==` operator in the `AsyncValue` class is like this:
```
@override
  bool operator ==(Object other) {
    return runtimeType == other.runtimeType &&
        other is AsyncValue<T> &&
        other.isLoading == isLoading &&
        other.hasValue == hasValue &&
        other.error == error &&
        other.stackTrace == stackTrace &&
        other.valueOrNull == valueOrNull;
```

When I write Unit tests:
```
expect(actualAsyncError, AsyncError('any error', StackTrace.current));
```

It never returns true, even if two errors are equal because the StackTrace of the actual error is always different from the StackTrace in Unit Tests.

Also, when I compare two same `AsyncData<List<T>>`, it always returns `false` as well
```
expect(AsyncData([1]), AsyncData([1]));
```

**Expected behavior**
I think the `==` operator should be implemented like this. If you have the same point as me, I can create a pull request to update it and its tests.
```
@override
  bool operator ==(Object other) {
    return runtimeType == other.runtimeType &&
        other is AsyncValue<T> &&
        other.isLoading == isLoading &&
        other.hasValue == hasValue &&
        other.error == error &&
        const DeepCollectionEquality().equals(other.valueOrNull, valueOrNull);
  }
```

**Comment by rrousselGit** [comment]
There's nothing wrong with that. The stacktrace is different, therefore the AsyncError is different.

Maybe you don't want a full comparison and only want to check a few properties.
You can do:

```dart
expect(
  value,
  isA<AsyncError<List<int>>>()
    .having((e) => e.error, 'error', 'any error'),
);
```

**Comment by minhnt3** [comment]
@rrousselGit It's OK but when I compare two same AsyncData<List<T>>, it always returns false as well. Is this a bug?
```
expect(AsyncData([1]), AsyncData([1]));
```

**Comment by rrousselGit** [comment]
It's because [1] == [1] is false.
If you use `const [1]` == `const [1]`, only then it will be true.

You can either use a constants or use a list which overrides ==
