### ISSUE TITLE
Why don't Ref and WidgetRef extend a common base class?

### ISSUE THREAD

**Issue by AbdullahSLM** [rrousselGit/riverpod#2891]
Sometimes it is necessary to pass `Ref` or `WidgetRef` instances to functions to perform certain operations. For example, I have an `AuthService` class that handles all authentication tasks in my app, and it includes a `login` function.

```dart
Future<User?> login(Ref ref, String username, String password) async {
  // Perform login and retrieve user information
  ...
  return user;
}
```
Currently, I cannot directly pass a `WidgetRef` to this function, which can be problematic if I want to replace the usage of `Ref` with `WidgetRef`.

To work around this limitation, I have resorted to the following approach:

```dart
Future<User?> login(Ref ref, String username, String password) async {
  assert(ref is Ref || ref is WidgetRef);

  // Perform login and retrieve user information
  ...
  
  // Update the user state based on the type of ref
  if (ref is Ref) {
    ref.read(userProvider.notifier).state = user;
  }
  
  if (ref is WidgetRef) {
    ref.read(userProvider.notifier).state = user;
  }
  
  return user;
}
```
However, it would be more convenient if both `Ref` and `WidgetRef` extended a common base class, let's say `BaseRef`. This would simplify the handling of these instances.

**Comment by rrousselGit** [comment]
There are a bunch of similar issues. This has already been answered before:  Code should never use one or the other.

If you have code which conditionally uses Ref and WidgetRef, refactor those WidgetRefs to move the logic in a provider such that you now use a Ref.

Relying on WidgetRef is equivalent to putting your logic in the UI. And Ref vs WidgetRef have different behaviours/life-cycles
