### ISSUE TITLE
watching auto-disposable providers inside keep-alive providers.

### ISSUE THREAD

**Issue by Hadit1993** [rrousselGit/riverpod#2893]
### Discussed in https://github.com/rrousselGit/riverpod/discussions/2892

<div type='discussions-op-text'>

<sup>Originally posted by **Hadit1993** September 11, 2023</sup>
Hi folks. How can I watch or listen to auto-disposable providers inside keep-alive providers and vice versa with riverpod generator?
the generated providers have type mismatch.</div>

**Comment by rrousselGit** [comment]
This is currently not allowed because it makes no sense. Your "auto-disposable" provider would not be disposable anymore once the keep-alive one watches your provider.
