### ISSUE TITLE
[FutureProvider.autoDispose] would dispose of its dependencies when updating its dependencies' states

### ISSUE THREAD

**Issue by SimonWang9610** [rrousselGit/riverpod#2896]
**Describe the bug**
When a `FutureProvider.autoDispose` is watched by a widget, it would be disposed of and then rebuilt if we update its dependencies' states.  Consequently, its dependencies would also be disposed of.

In the below code, if we invoke `add()` for the second or the third provider, the first provider cannot update its state as we expected. Its state was always the initialized state since the second and third providers would be disposed of and rebuilt again.

If we also watched the second and third provider in our widgets, the first widget would update as we expected.

This was fine and may make sense. 

However, if the first provider is `StateProvider.autoDispose`, it would not cause its dependencies to dispose of when we updated its dependencies' states.

In general, does it make sense a `FutureProvider` would cause its dependencies to dispose of when we are trying to update its dependencies' states?

**To Reproduce**
```dart
import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'test.g.dart';

@riverpod
class First extends _$First {
  @override
  Future<String> build() async {
    await Future.delayed(const Duration(milliseconds: 100));

    final second = await ref.watch(secondProvider.future);
    final third = ref.watch(thirdProvider);

    ref.onDispose(() {
      print("dispose first");
    });

    return "$second/$third";
  }
}

@riverpod
class Second extends _$Second {
  @override
  Future<int> build() async {
    ref.onDispose(() {
      print("dispose Second");
    });
    return 0;
  }

  void add() {
    state = AsyncValue.data(state.asData!.value + 1);
  }
}

@riverpod
class Third extends _$Third {
  @override
  int build() {
    ref.onDispose(() {
      print("dispose Third");
    });

    return 0;
  }

  void add() {
    state++;
  }
}

```
```dart
class ProviderTest extends ConsumerWidget {
  const ProviderTest({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(firstProvider);
    // final _ = ref.watch(secondProvider);
    return Scaffold(
      body: Center(
        child: Text("$value"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          ref.read(secondProvider.notifier).add();
          ref.read(thirdProvider.notifier).add();
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**
When invoking ` ref.read(secondProvider.notifier).add()` and/or `ref.read(thirdProvider.notifier).add();`, the second and/or thrid providers should not be disposed of. The first provider should update its state correctly according to the updated dependencies' states.

**Comment by AhmedLSayed9** [comment]
That's expected. while you're awaiting for `ref.watch(secondProvider.future)` there's no listeners to thirdProvider for a few frames so it get disposed. check https://github.com/rrousselGit/riverpod/issues/1253

**Comment by rrousselGit** [comment]
Your problem is the awaits. For some amount of time, your provider is unused and therefore gets destroyed.

You can rely on keepAlive to maintain your state for longer than a single unused frame https://github.com/rrousselGit/riverpod/issues/1664

There's also an issue for changing a bit how dependencies are tracked on rebuilds to alleviate such an issue. https://github.com/rrousselGit/riverpod/issues/1253
