### ISSUE TITLE
const providers

### ISSUE THREAD

**Issue by serhii-k** [rrousselGit/riverpod#2903]
I've noticed that for family providers the generated provider is const. But a regular providers is final.

For example:
```
@riverpod
int test(TestRef ref) => 0;
```
The generated code:
```
/// See also [test].
@ProviderFor(test)
final testProvider = AutoDisposeProvider<int>.internal(
  test,
  name: r'testProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$testHash,
  dependencies: null,
  allTransitiveDependencies: null,
);
```
But it could be:
```
/// See also [test].
@ProviderFor(test)
const testProvider = …
```
However, I'm not sure if there are some limitations that prevent making it const in any situation.

**Comment by rrousselGit** [comment]
That is not possible at the moment, no.

There are solutions being experimented to see if this is doable. There are already issues about it. In any case, this isn't a bug :)
