### ISSUE TITLE
Configuration for provider

### ISSUE THREAD

**Issue by amevee** [rrousselGit/riverpod#2904]
**Is your feature request related to a problem? Please describe.**
I'd like to dispose/invalidate all providers related to logged in view, when a user sign out, so we don't hold any user data after sign out.

**Describe the solution you'd like**
A configuration property which can then be used to get all providers belonging to that config.

**Describe alternatives you've considered**
With existing implementation, I can leverage name to contain specific word or have dependency to some void provider. Going with former because in later scoped providers need to be explicitly defined in dependency when used elsewhere increasing the work.

**Comment by rrousselGit** [comment]
You should generally use ref.watch for this.

Is there any reason why this wouldn't work for you?

**Comment by amevee** [comment]
In most cases we are using ref.watch only, but still there are certain providers which are in keepAlive.

**Comment by rrousselGit** [comment]
What what's the issue?

**Comment by amevee** [comment]
There isn't an issue, it's just a feature to find out all providers with some config so they can be collectively disposed. We can't just rely on provider auto dispose through tracking live widgets, and would need some way to dispose group of providers collectively.

**Comment by rrousselGit** [comment]
I'm just failing to understand the problem & proposal here. Some example of what you're currently doing vs what you'd like would help

**Comment by rrousselGit** [comment]
Closing as this issue is unclear. Please open a new issue with a more precise proposal if you still want something done :)
