### ISSUE TITLE
A false provider_dependencies warning for scoped family providers.

### ISSUE THREAD

**Issue by serhii-k** [rrousselGit/riverpod#2909]
I have a scoped provider `testProvider`, which I need to watch in a family provider. When I specify `test` in the dependencies of the family provider, Android Studio shows a false `provider_dependencies` warning :(

```
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'providers.g.dart';

@Riverpod(dependencies: [])
int test(TestRef ref) => 0;

@Riverpod(dependencies: [test])
int dep(DepRef ref, int p) {
  final test = ref.watch(testProvider);
  return test * p;
}
```

info: If a provider depends on providers which specify "dependencies", they should themselves specify "dependencies" and include all the scoped providers.  (provider_dependencies at [riverpod2test] lib/providers.dart:8)

**Comment by rrousselGit** [comment]
I wonder why. I'll investigate

**Comment by rrousselGit** [comment]
Note for self: here's some regression test

```dart
// Regression for https://github.com/rrousselGit/riverpod/issues/2909
@Riverpod(dependencies: [dep])
int familyDep(FamilyDepRef ref, int p) {
  final test = ref.watch(depProvider);
  return test * p;
}

@Riverpod(dependencies: [familyDep])
int familyDep2(FamilyDep2Ref ref, int p) {
  final test = ref.watch(familyDepProvider(0));
  return test * p;
}

```

**Comment by serhii-k** [comment]
Awesome! Thank you!
