### ISSUE TITLE
Bootstrap file

### ISSUE THREAD

**Issue by LeonardoRosaa** [rrousselGit/riverpod#2919]
The first time I opened the repository on my machine, I had to manually run the `flutter pub get` command for each package in this repository. It takes some time and is a boring task.

Let's create a **bootstrap** file to run the `flutter pub get` command for each package through one single command.

**Comment by rrousselGit** [comment]
There's the melos.yaml if you want https://github.com/rrousselGit/riverpod/blob/master/melos.yaml

You can run `melos boostrap`.
I won't maintain extra files that I do not use.

VScode already handles running pub get everywhere anyway :)
