### ISSUE TITLE
Riverpod code generator generating InvalidType when provider state return type is a freezed union type

### ISSUE THREAD

**Issue by chrisdrobison** [rrousselGit/riverpod#2920]
**Describe the bug**
Riverpod code generator generating InvalidType when provider state return type is a freezed union type.

**To Reproduce**

```
@freezed
class Exam with _$Exam {
  const Exam._();

  const factory Exam.look({
    required String id,
    ...
  }) = LookExam;

  const factory Exam.move({
    required String id,
    ...
  }) = MoveExam;

  const factory Exam.stand({
    required String id,
    ...
  }) = StandExam;

  const factory Exam.tap({
    required String id,
    ...
  }) = TapExam;
}

@riverpod
class LookGraphResults extends _$LookGraphResults {
  @override
  Future<LookExam> build(String examId) async {
    return await loadExam(examId);
  }
}
```

For me, the output of the generator is this:

```
abstract class _$LookGraphResults
    extends BuildlessAutoDisposeAsyncNotifier<InvalidType> {
  late final String examId;

  Future<InvalidType> build(
    String examId,
  );
}
```

**Expected behavior**
In the example above, the generated output of _$LookGraphResults shows the resultant type to be `InvalidType`. If I change the return type of `build()` to be `Future<Exam>`, the resultant output is correctly `Exam`.

**Comment by rrousselGit** [comment]
Duplicate of https://github.com/rrousselGit/riverpod/issues/2273

Cf https://github.com/rrousselGit/riverpod/issues/2359

**Comment by bkkoluch** [comment]
> **Describe the bug** Riverpod code generator generating InvalidType when provider state return type is a freezed union type.
> 
> **To Reproduce**
> 
> ```
> @freezed
> class Exam with _$Exam {
>   const Exam._();
> 
>   const factory Exam.look({
>     required String id,
>     ...
>   }) = LookExam;
> 
>   const factory Exam.move({
>     required String id,
>     ...
>   }) = MoveExam;
> 
>   const factory Exam.stand({
>     required String id,
>     ...
>   }) = StandExam;
> 
>   const factory Exam.tap({
>     required String id,
>     ...
>   }) = TapExam;
> }
> 
> @riverpod
> class LookGraphResults extends _$LookGraphResults {
>   @override
>   Future<LookExam> build(String examId) async {
>     return await loadExam(examId);
>   }
> }
> ```
> 
> For me, the output of the generator is this:
> 
> ```
> abstract class _$LookGraphResults
>     extends BuildlessAutoDisposeAsyncNotifier<InvalidType> {
>   late final String examId;
> 
>   Future<InvalidType> build(
>     String examId,
>   );
> }
> ```
> 
> **Expected behavior** In the example above, the generated output of _$LookGraphResults shows the resultant type to be `InvalidType`. If I change the return type of `build()` to be `Future<Exam>`, the resultant output is correctly `Exam`.

Same here, seems the generated freezed union types stopped workigng, I don't get the output anymore, but get a `log output for riverpod_generator on <path> E InvalidTypeException: The type is invalid and cannot be converted to code.` message.

This stopped working after updating to riverpod 3.0.0 (and 3.0.1 still does not allow it).
