### ISSUE TITLE
[riverpod_generator] Generate providers from part files

### ISSUE THREAD

**Issue by julienlebren** [rrousselGit/riverpod#2923]
Could you make @riverpod annotation work with 'part' files so the class marked with @riverpod can be part of another file, like @freezed does. 
It would be very useful for code organization in libraries.

**Comment by rrousselGit** [comment]
This works fine for me. I have a test checking this specific scenario https://github.com/rrousselGit/riverpod/blob/78ee4a0e1f173c15d9ba90ef0510325d45703821/packages/riverpod_generator/test/integration/split.dart

You'll have to be more specific and maybe share a repository to reproduce the issue.

**Comment by julienlebren** [comment]
You are right, it works on a simple example... but it still not works in my big project.
I will dig into this and I'll let you know.

**Comment by julienlebren** [comment]
It works now... probably an error in my code 🤷‍♂️
Sorry
