### ISSUE TITLE
[riverpod_lint] Bad state: Unknown provider type StreamNotifierProviderImpl

### ISSUE THREAD

**Issue by ubergaijin** [rrousselGit/riverpod#2937]
Seems like LegacyProviderType is missing support for StreamNotifierProvider*. Are they being deprecated?

**Comment by rrousselGit** [comment]
Please provide a way to reproduce the issue. That short title is not enough for me to understand the problem

**Comment by rrousselGit** [comment]
I assume your riverpod_lint and riverpod versions got out of sync.
From my test, the current riverpod_lint version handles StreamNotifiers just fine. So closing.

If you still have the problem, please open a new isssue
