### ISSUE TITLE
I want to get WidgetRef, using useWidgetRef hook.

### ISSUE THREAD

**Issue by Jaew00Shin** [rrousselGit/riverpod#2945]
I request to make new hook, useWidgetRef.
There is useContext() in flutter hook which returns BuildContext.

Like this, I want to use useWidgetRef hook which returns WidgetRef.
Then, this hook should be used in only HookConsumerWidget.

**Comment by rrousselGit** [comment]
You can do `WidgetRef useWidgetRef() => useContext as WidgetRef;`

**Comment by rrousselGit** [comment]
I don't plan on adding such a hook for now. This can be revisited in the future though

**Comment by LowLevelSubmarine** [comment]
Maybe a useRiverpod() hook which returns the WidgetRef could be a neat alternative to to the HookConsumerWidget?
