### ISSUE TITLE
Version solving fail

### ISSUE THREAD

**Issue by cntoss** [rrousselGit/riverpod#2950]
riverpod_generator >=2.3.3 <3.0.0-dev.1 depends on riverpod_analyzer_utils ^0.3.4 which doesn't match any versions, riverpod_generator >=2.3.3 <3.0.0-dev.1 is forbidden.
So, because ocw_flutter depends on riverpod_generator ^2.3.3, version solving failed.

**Comment by josh-burton** [comment]
Why was this closed? it seems the `riverpod_analyzer_utils ^0.3.4` dependency is not published, so the latest riverpod generator version fails to resolve.

**Comment by rrousselGit** [comment]
3.0.0-dev.1 should've been pulled down. Seems like I forgot.
I pulled it down correctly.

**Comment by marcotta** [comment]
@rrousselGit  I am seeing this error:
```
Because riverpod_generator >=2.3.3 <3.0.0-dev.2 depends on riverpod_analyzer_utils ^0.3.4 which doesn't match any versions, riverpod_generator >=2.3.3 <3.0.0-dev.2 is forbidden.
``` 
Should `3.0.0-dev.2` be pulled down?

**Comment by josh-burton** [comment]
yeah I'm getting the same error. It seems I can't use the latest stable version of riverpod_generator and riverpod_lint together

**Comment by rrousselGit** [comment]
Could you make a repo to reproduce the issue?

**Comment by josh-burton** [comment]
> Could you make a repo to reproduce the issue?

Sure, here's a repo that reproduces the conflict: https://github.com/josh-burton/riverpod_dependency_conflict

`riverpod_lint: ^2.1.1` works fine, but `riverpod_lint: ^2.3.0` results in the error:

```
Because no versions of riverpod_generator match >2.3.3 <3.0.0 and riverpod_generator 2.3.3 depends on riverpod_analyzer_utils ^0.3.4, riverpod_generator ^2.3.3 requires riverpod_analyzer_utils ^0.3.4.
And because riverpod_lint >=2.3.0 depends on riverpod_analyzer_utils ^0.4.1, riverpod_generator ^2.3.3 is incompatible with riverpod_lint >=2.3.0.
So, because riverpod_dependency depends on both riverpod_lint ^2.3.0 and riverpod_generator ^2.3.3, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Try upgrading your constraint on riverpod_generator: flutter pub add dev:riverpod_generator:^3.0.0-dev.3
* Consider downgrading your constraint on riverpod_lint: flutter pub add dev:riverpod_lint:^2.1.1
```
