### ISSUE TITLE
AsyncNotifier naming confusion

### ISSUE THREAD

**Issue by jezsung** [rrousselGit/riverpod#2955]
The `AsyncNotifier` has a `state` which is the type of `AsyncValue`. While the inner state of this `AsyncValue` is called `value`. This `value` is the type of the passed generic type which is named `State`.

I think the naming is a bit messy. Wouldn't it be better to rename the current `AsyncNotifier.state` to `AsyncNotifier.value` to match its type `AsyncValue`? And the `AsyncValue.value` to `AsyncValue.state`.

**Comment by rrousselGit** [comment]
I doubt that's worth making a breaking change

**Comment by rrousselGit** [comment]
I have no plan to make such a change due to the lost value and high cost
