### ISSUE TITLE
Circular dependency is not spotted for code generated providers

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#2968]
**To Reproduce**
```dart
@riverpod
int foo(FooRef ref) {
  ref.watch(barProvider);
  return 0;
}

@riverpod
int bar(BarRef ref) {
  ref.watch(fooProvider);
  return 0;
}
```

This can be produced using riverpod 2.4.3

**Comment by rrousselGit** [comment]
How does that differ from non generated code?

**Comment by rrousselGit** [comment]
Yeah that's on purpose actually. The non-code-gen error is more of a Dart issue than a Riverpod feature. Codegen voluntarily solves this

It's quite useful when providers have arguments. It's not uncommon for a provider to watch itself with different args
