### ISSUE TITLE
using ref.refresh throw error

### ISSUE THREAD

**Issue by dat02092k1** [rrousselGit/riverpod#2972]
**Describe the bug**
I'm a newbie. I'm using riverpod to manage state but got error when try to use ref.refresh to refresh state. 
In widget SystemTab, I have a list of notifications that will be pushed to listNoti array and display, but the problem is, each time i scroll to get more notifications(which means i get more notifications with page++), it will get the data with corresponding page and pushed to listNoti, it works fine, but i have a widget to manage notifications to delete notifications and check notifications as read, and i will also display notifications here with the way i did in SystemTab, but it will push the data with corresponding page (for ex: it will display data with page 3 if i scroll to page 3 in SystemTab). This is not correct, so i tried to use ref.refresh in initState so that it can be reset state, but i got the error below
Error: 
"errors.dart:288 Uncaught (in promise) Error: setState() or markNeedsBuild() called during build.
This SystemTab widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  SystemTab
The widget which was currently being built when the offending call was made was: eyedSubtree-[<0>]
    at Object.throw_ [as throw]..."
i 
**To Reproduce**
// SystemTab.dart
List<n.Notification> listNoti = [];

@override
  void initState() {
    ref.refresh(notiProvider);

    _scrollController.addListener(() async {
      if (_scrollController.position.pixels ==
          _scrollController.position.maxScrollExtent) {
        if (!isLoading && listNoti.isNotEmpty) {
          await _loadData();
        }

      }
    });

    super.initState();
  }

 Future<void> _loadData() async {
    final requestData = <String, dynamic>{
      'limit': _visibleNotiCommonCount,
      'page': page,
      'userId': widget.user.id,
    };

    final request = NotiDataRequest.fromJson(requestData);

    // await ref.read(notiProvider.notifier).getNoti(request);
    Future(() {
      ref.read(notiProvider.notifier).getNoti(request);
    });
  }

@override
  Widget build(BuildContext context) {
    late final finboxColors = Theme.of(context).extension<FinboxColors>()!;
    var mapTicker = <String, TickerDetailModel>{};
    final listTicker = <String>[];
 
    final notiDataState = ref.watch(notiProvider);
    final user = ref.watch(userDataProvider);

    if (isFirstLoad) {
      isFirstLoad = false;

      _loadData();
    }

    notiDataState
      ..whenOrNull(
        listNotiLoaded: (loadedNotis) {
          isFirstLoad = false;
          page++;
          print('page::${page}');
          for (final loadedNoti in loadedNotis) {
            if (!listNoti.contains(loadedNoti)) {
              listNoti = [...listNoti, loadedNoti];
            }
          }
        },
      )
...
// ManageNoti.dart 
@override
  void initState() {
    ref.refresh(notiProvider);
super.initState();
"
Notes: the code is so long, so i just give a sample of it
**Expected behavior**
Can you help me with this problem ? Any available solutions, i was stuck in this problem for so long

**Comment by rrousselGit** [comment]
Calling ref.refresh inside initState is not allowed, as there may have some already built widget depending on said provider

You should find a different location to call that refresh. It cannot be called while the widget tree is building

**Comment by dat02092k1** [comment]
> Calling ref.refresh inside initState is not allowed, as there may have some already built widget depending on said provider
> 
> You should find a different location to call that refresh. It cannot be called while the widget tree is building

Can you recommend me where to put ref.refresh ? Excuse me if it bothers because i'm newbie
