### ISSUE TITLE
Allow generating public Providers for private Notifier

### ISSUE THREAD

**Issue by yousefak007** [rrousselGit/riverpod#2979]
Hi,

![image](https://github.com/rrousselGit/riverpod/assets/46021584/4170aa0d-ff47-472d-a6b5-4fa627ac76a8)

the previous code will generate a private provider called: _localizationProvider

I want to generate it as public to exposit outside the file without needing to make the Notifier class public

Thank you

**Comment by rrousselGit** [comment]
That makes no sense, because if the provider is public, then the notifier can be accessed using "ref.read(provider.notifier)"

So the notifier should also be public

**Comment by yousefak007** [comment]
and you can access it even if it's private

like this:
ref.read(localizationProvider.notifier).changeLocale();

that will be very helpful if you have many notifiers and you avoid avoid naming conflicts

**Comment by rrousselGit** [comment]
import alias is there to avoid naming conflict.

If the notifier can be obtained from a public API, it should be public.

IMO this would only make sense if ".notifier" was also private.

**Comment by yousefak007** [comment]
I thought it would help improve the development experience instead of dealing with import alias

Thanks
