### ISSUE TITLE
Add a `where` method to filter provider state changes

### ISSUE THREAD

**Issue by gmkado** [rrousselGit/riverpod#2981]
**Is your feature request related to a problem? Please describe.**
I may be missing something, I have tried finding similar issues in this repo.  Maybe the closest thing is this [issue about debounce](https://github.com/rrousselGit/riverpod/issues/352), but the solution doesn't really apply here.  

When I care about all of my provider changes riverpod works great and makes it very easy to combine and watch changes.  

My issue is when I want to apply some filtering to a provider, for example only give me non-null values:

```dart
@riverpod
class AggregateWorkoutStates extends _$AggregateWorkoutStates {
  @override
  AggregateWorkoutState build() {
    final workoutState = ref.watch(workoutStateProvider);
    
    // sensorProvider state can be null, but I only want aggregateWorkoutStatesProvider to emit when it is non-null AND when workoutState is "active" (see desired syntax below)
    final reading = ref.watch(sensorProvider); 

    return AggregateWorkoutState(
        reading: reading,
        workoutState: workoutState);
  }
}
```
I had come across another similar sounding issue (can't seem to find it now) which was closed and referred to the `select` method as the new way to do this.  I understand how in the simple case it can prevent rebuilds, but if your criteria is combined with other state and not just the provider's state itself, I couldn't figure out a straightforward way to return the previously emitted value.

**Describe the solution you'd like**
Similar to the `select` method, can we have a `where` method that will make that provider only emit when it meets the filter function criteria?  Coming from the Rx and Linq world, this syntax is very familiar and could be chained with `select` to get only the state changes I care about:

```dart
@riverpod
class AggregateWorkoutStates extends _$AggregateWorkoutStates {
  @override
  AggregateWorkoutState build() {
    final workoutState = ref.watch(workoutStateProvider);
    final reading = ref.watch(sensorProvider.where((data)=>workoutState==WorkoutState.active && data!=null));

    return AggregateWorkoutState(
        reading: reading,
        workoutState: workoutState);
  }
}
```

**Describe alternatives you've considered**
I tried creating my own but can't seem to wrap my head around getting the state updates correct.  Here's what I have currently.  I've gone through  various iterations of this before throwing in the towel, but the gist is I'm trying to use `_FilterNotifier` that keeps track of the last state that meets the filter criteria, and returning that when the current state doesn't meet the criteria.  

```dart
extension ProviderListenableExtension<T> on ProviderListenable<T> {
  ProviderListenable<T> where(
      {required bool Function(T) filter, required T initialValue}) {
    final notifier = _FilteredNotifier<T>(
        provider: this, filter: filter, initialValue: initialValue);
    return NotifierProvider.autoDispose(() => notifier);
  }
}

class _FilteredNotifier<T> extends AutoDisposeNotifier<T> {
  late T previousReading;
  final T initialValue;
  final ProviderListenable<T> provider;
  final bool Function(T) filter;

  _FilteredNotifier(
      {required this.provider,
      required this.initialValue,
      required this.filter}) {
    previousReading = initialValue;
  }

  @override
  T build() {
    ref.watch(provider.select((data) {
      return _applyFilter(data);
    }));

    return _applyFilter(ref.read(provider));
  }

  T _applyFilter(T data) {
    if (filter(data)) {
      previousReading = data;
    }
    return previousReading;
  }
}
```
The above currently doesn't work, it creates a new FilterNotifier every time `where` is called.  I tried this approach with a family too in an attempt to cache the notifier provider but it has the same issue, I still "new" the notifier on each call to `where`.  I think maybe the issue could be resolved [by supporting generics](https://github.com/rrousselGit/riverpod/issues/1119)?  I started to feel this was overcomplicating things so decided to take a step back and ask the experts :)

I feel like I may be missing something because this seems like it should be fairly straightforward.  Any feedback would be much appreciated!

**Comment by gmkado** [comment]
@rrousselGit thanks for the quick response!

In my example above I pass `where` an `initialValue` in the event that the provider's current state does not meet `filter`.  Would something like that work?

Also, if this does not make sense with riverpod's patterns, is there a more appropriate way to accomplish the same thing?

**Comment by rrousselGit** [comment]
Few cases would appreciate having to specify an initial value.


In your case you likely could do:

```dart
inal reading = 
workoutState == active ? ref.watch(sensorProvider) : null;
```

**Comment by gmkado** [comment]
Nice and simple, and I think it will work in my use case.

Just wanted to point out though that it's not really the same thing.  For example, it does not preserve the last sensor reading when workout state goes inactive, just swaps it with null.

I could probably come up with some other examples where a declarative filter would be desirable, but my guess is this won't get too much traction.  Feel free to close and thanks for your help!

**Comment by rrousselGit** [comment]
No problem. Will close for now 😊

**Comment by gmkado** [comment]
I keep finding useful tidbits in an issue discussion and losing it when I try to go back and find it.  Somewhere in one of these issues is a comment from @rrousselGit about how riverpod fundamentally treats state as a single instant and not a stream of states.  That alone helped me wrap my head around why `"A where function does not make much sense in the scope of Riverpod."`

However, I am able to get more flexible logic around when a state is emitted by temporarly converting a future provider back to a stream provider like so:

```dart
@riverpod
Stream<double> workoutAwareSensorStream(
    WorkoutAwareSensorStreamRef ref) async* {
  final reading = await ref.watch(sensorProvider.future);
  final state = ref.watch(currentWorkoutProvider).state;
  if (state == WorkoutState.active && reading != null) {
    yield reading;
  }
}
```
