### ISSUE TITLE
Perhaps it is possible to record the source of the error so that it can be consistent with loading.

### ISSUE THREAD

**Issue by sososdk** [rrousselGit/riverpod#2985]
Expect the `error` to be consistent with the `loading` state. When skipping `loading`, it is expected to skip `error`, and vice versa.

Perhaps it is necessary to add `isFromRefreshing` and `isFromReloading` to record the source of the error.
```dart
R when<R>({
    bool skipLoadingOnReload = false,
    bool skipLoadingOnRefresh = true,
    bool skipErrorOnReloaded = false,
    bool skipErrorOnRefreshed = true,
    required R Function(T data) data,
    required R Function(Object error, StackTrace stackTrace) error,
    required R Function() loading,
  }) {
    if (isLoading) {
      bool skip;
      if (isRefreshing) {
        skip = skipLoadingOnRefresh;
      } else if (isReloading) {
        skip = skipLoadingOnReload;
      } else {
        skip = false;
      }
      if (!skip) return loading();
    }

    if (hasError) {
      bool skip;
      if (isFromRefreshing) {
        skip = skipErrorOnRefreshed;
      } else if (isFromReloading) {
        skip = skipErrorOnReloaded;
      } else {
        skip = false;
      }
      if (!skip) error(this.error!, stackTrace!);
    }

    return data(requireValue);
  }
```

**Comment by AhmedLSayed9** [comment]
This has been discussed when skip flags were introduced. check https://github.com/rrousselGit/riverpod/issues/1570#issuecomment-1292042878

**Comment by sososdk** [comment]
@AhmedLSayed9 thanks for your reply.

When dependencies changed, the previous data may not apply.

An example, when reload (PostType changed), previous data is inappropriate, we need show error. When refresh, previous data is good, we need show data.
```dart
@riverpod
class PostTypes extends _$PostTypes {
  @override
  int build() {
    return 0;
  }

  void increment() => state++;
}
```

```dart

@riverpod
class Posts extends _$Posts with Disposes {
  int _offset = 0;

  @override
  FutureOr<PostsData> build() async {
    final type = ref.watch(postTypesProvider);

    print(
      'Reloading($type): ${state.isReloading}  Refreshing: ${state.isRefreshing}',
    );
    final array = _gen(type, 0);
    await Future.delayed(const Duration(seconds: 1));
    if (state.isRefreshing || state.isReloading) {
      throw StateError('test error');
    }
    _offset = array.length;
    return PostsData(title: 'Posts', items: array);
  }
}
```

**Comment by AhmedLSayed9** [comment]
> An example, when reload (PostType changed), previous data is inappropriate, we need show error. When refresh, previous data is good, we need show data.

User will see data then when the provider rebuild you'll show him error while data is loading? I think this is bad UX.
but anyway, this can be handled using switch and pattern matching which will replace .when anyway.

**Comment by sososdk** [comment]
> User will see data then when the provider rebuild you'll show him error while data is loading?

When reload we show loading, and then error we show error.
When  refresh we show previous data, and then error we show previous data too.

**Comment by AhmedLSayed9** [comment]
This is different from the proposed flags
You want to skip errors only if the prev loading was caused by ref.watch `reload`
The proposed flags express skipping errors during loading.

**Comment by sososdk** [comment]
The point is that `skipError` is configurable for different source of error.

**Comment by AhmedLSayed9** [comment]
You can do:
```dart
final shouldSkipError = useState<bool>(false);
ref.listen(
      postTypesProvider,
      (previous, next) async {
        switch (previous) {
          case AsyncValue(isLoading: true):
            shouldSkipError.value = false;
        }
        switch (next) {
          case AsyncData():
            shouldSkipError.value = true;
        }
      },
    );

return ref.watch(postTypesProvider).when(
        skipError: shouldSkipError.value,
        ...
);
```

**Comment by AhmedLSayed9** [comment]
@sososdk 
First switch check if the prev state was `reloading by ref.watch`, if so you'll not skip the following errors.
Second switch will set skip errors back to true when you get new data.

**Comment by sososdk** [comment]
> You can do:
> 
> ```dart
> final shouldSkipError = useState<bool>(false);
> ref.listen(
>       postTypesProvider,
>       (previous, next) async {
>         switch (previous) {
>           case AsyncValue(isReloading: true):
>             shouldSkipError.value = false;
>         }
>         switch (next) {
>           case AsyncData(isLoading: false):
>             shouldSkipError.value = true;
>         }
>       },
>     );
> 
> return ref.watch(postTypesProvider).when(
>         skipError: shouldSkipError.value,
>         ...
> );
> ```
> 
> _Note:_ `useState` from Hooks, you can do the same using StatefulWidget.

Yes, that's what we do. However, if we can do it with `skipErrorOnReloaded`, the code will be greatly simplified.

**Comment by rrousselGit** [comment]
I'm not sure I understand what this is about.  
What's inconsistent exactly?

Also keep in mind that "when" is considered out of date, now that we have pattern matching in Dart

**Comment by sososdk** [comment]
> > User will see data then when the provider rebuild you'll show him error while data is loading?
> 
> When reload we show loading, and then error we show error. 
> When refresh we show previous data, and then error we show previous data too.

@rrousselGit I just want a simple way to implement this functionality.

**Comment by AhmedLSayed9** [comment]
> However, if we can do it with `skipErrorOnReloaded`, the code will be greatly simplified.

What you want is different from `skipErrorOnReload`. This meant to be for skipping errors during loading.
You want to skip errors when the last loading was from reload, which need to be preserved at some state as I showed you.

**Comment by rrousselGit** [comment]
> > > User will see data then when the provider rebuild you'll show him error while data is loading?
> > 
> > 
> > When reload we show loading, and then error we show error.
> > When refresh we show previous data, and then error we show previous data too.
> 
> @rrousselGit I just want a simple way to implement this functionality.

```dart
switch (value) {
  AsyncValue<Data>(:final valueOrNull?) => Text('data $valueOrNull'),
  AsyncValue(:final error?) => Text('error $error'),
  _ => Text("loading"),
}
```

**Comment by sososdk** [comment]
> > > > User will see data then when the provider rebuild you'll show him error while data is loading?
> > > 
> > > 
> > > When reload we show loading, and then error we show error.
> > > When refresh we show previous data, and then error we show previous data too.
> > 
> > 
> > @rrousselGit I just want a simple way to implement this functionality.
> 
> ```dart
> switch (value) {
>   AsyncValue<Data>(:final valueOrNull?) => Text('data $valueOrNull'),
>   AsyncValue(:final error?) => Text('error $error'),
>   _ => Text("loading"),
> }
> ```

@rrousselGit  I don't think this does what I want. 

I need:
- When reload caused by `ref.watch`, show loading when `isLoading`, and then show error when `hasError`, the previous data is ignored.
- When refresh caused by `ref.refresh`, show previous data when `isLoading`, and then show previous data too when `hasError`.

**Comment by rrousselGit** [comment]
You can achieve whatever you want using pattern matching with combinations of "AsyncValue(isLoading: true/false)" or the same for isRefeshing/isReloading

**Comment by sososdk** [comment]
@rrousselGit I need a field to indicate where the `error` comes from, reload or refresh?

**Comment by rrousselGit** [comment]
You mean after the reload/refresh has completed?

**Comment by sososdk** [comment]
@rrousselGit Yes, I mean after the reload/refresh has completed, and it has an error.

We can use `isRefeshing` and `isReloading` in loading, I hope there is a field that can determine whether the error comes from refresh or reload.

**Comment by rrousselGit** [comment]
There's no such thing yet no.

**Comment by sososdk** [comment]
@rrousselGit So, can this function be added? I think this is very useful. When reload fails, the previous data may be invalid due to changes in dependencies. At this time, we should display an error. However, when refresh fails, it can display previous data.

**Comment by sososdk** [comment]
> You can do:
> 
> ```dart
> final shouldSkipError = useState<bool>(false);
> ref.listen(
>       postTypesProvider,
>       (previous, next) async {
>         switch (previous) {
>           case AsyncValue(isReloading: true):
>             shouldSkipError.value = false;
>         }
>         switch (next) {
>           case AsyncData(isLoading: false):
>             shouldSkipError.value = true;
>         }
>       },
>     );
> 
> return ref.watch(postTypesProvider).when(
>         skipError: shouldSkipError.value,
>         ...
> );
> ```
> 
> _Note:_ `useState` from Hooks, you can do the same using StatefulWidget.

@rrousselGit This works. I hope to add flags to `AsyncValue` to make the code simpler.

**Comment by AhmedLSayed9** [comment]
You can use an extension if you need a simpler reusable code:

```dart
extension WidgetRefExtension on WidgetRef {
  void shouldSkipErrorListen<T>(
    ProviderListenable<AsyncValue<T>> provider, {
    required ValueNotifier<bool> shouldSkipErrorNotifier,
  }) {
    return listen(
      provider,
      (previous, next) async {
        switch (previous) {
          case AsyncValue(isReloading: true):
            shouldSkipErrorNotifier.value = false;
        }
        switch (next) {
          case AsyncData(isLoading: false):
            shouldSkipErrorNotifier.value = true;
        }
      },
    );
  }
}

Widget build(BuildContext context, WidgetRef ref) {
  final shouldSkipError = useState<bool>(false);
  ref.shouldSkipErrorListen(postTypesProvider, shouldSkipErrorNotifier: shouldSkipError);
  
  return ref.watch(postTypesProvider).when(
          skipError: shouldSkipError.value,
          ...
  );
```

**Comment by sososdk** [comment]
Thanks. But forget it.
