### ISSUE TITLE
Riverpod 3.0 plans

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2994]
Internal issue for tracking what's needed for 3.0

- [ ] Fix all TODOs
- [ ] Revamp the scheduler mechanism to remove `ProviderElement.flush` in favour of rebuilding all dirty providers when interacting with any provider
- [x] ~~Dissociate `Ref` from `ProviderElement`~~ An alternative was found
- [ ] ~~Enable only a single root ProviderContainer to be active~~ Would not work with projects using component viewers such as widgetbook
- [x] ^ Use this to optimize non-scoped providers
- [x] Make providers consts
- [x] Rework ProviderListenable interface to be usable by mere mortals 😛

**Comment by ciriousjoker** [comment]
We're just now starting to migrate from the old FutureProvider/etc. classes to the new decorators & classes.

Would you suggest migrating to Riverpod 2 or wait for Riverpod 3 before doing anything here? Will there be any huge breaking changes that require long refactors or is the new syntax stable in this regard?

**Comment by eugenio-tesio-ueno** [comment]
Could you add some way to create your own provider? We needed FutureProvider that works with function programing, for instance `Either` from `fpdart` package. We end up creating this extension to solve the problem of returning `AsynError` twice (one for `Left<Either>` and the other for the Riverpod error in self)

```dart
extension FnAsyncValue<T> on AsyncValue<Either<ApiException, T>> {
  R mapEither<R>({
    required R Function(AsyncData<T> d) data,
    required R Function(AsyncError<T> e) error,
    required R Function(AsyncLoading<T> l) loading,
  }) {
    return map(
      data: (fpData) {
        return fpData.value.fold(
          (left) => error(
            AsyncError(left.message, left.stackTrace ?? StackTrace.current),
          ),
          (right) => data(AsyncData(right)),
        );
      },
      error: (fpError) {
        return error(AsyncError(fpError.error, fpError.stackTrace));
      },
      loading: (fpLoading) {
        return loading(const AsyncLoading());
      },
    );
  }
}
```

We would like that `map` Provider method handles all this without creating a `mapEither`.

**Comment by rrousselGit** [comment]
Points listed are done. Todos will be sorted separately
