### ISSUE TITLE
AsyncError.value should return null instead of throwing

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2999]
And valueOrNull should be removed

This is to better support pattern matching, as folks are bound to mistakenly use `value` instead of `valueOrNull`

**Comment by navaronbracke** [comment]
Currently when someone uses `AsyncValue.value` the error recovery is poor sometimes if `valueOrNull` should have been used. (the value _was null_ at runtime) Will the removal of `valueOrNull` from `AsyncValue/AsyncError` fix this?

**Comment by rrousselGit** [comment]
I'm not exactly sure what you're referring to. But if "valueOrNull" should've been used instead of "value", then yes.
This issue is effectively about deleting the old `value` and renaming `valueOrNull` -> `value`.

**Comment by navaronbracke** [comment]
That was indeed what I was implying yes.

**Comment by rrousselGit** [comment]
Was implemented in the dev branch
