### ISSUE TITLE
There will be a parameter prompt regarding code generation

### ISSUE THREAD

**Issue by dt-wonder** [rrousselGit/riverpod#3001]
![image](https://github.com/rrousselGit/riverpod/assets/30770373/cf9fcc79-e610-45ea-80ed-3323409fc92c)

**Comment by lucavenir** [comment]
When opening a Github issue, please follow the template and read other issues if you need guidance.

Copy pasting a random screenshot is just going to waste everyone's time; please add: content, code, expected behavior, actual behavior if you think something is wrong.
