### ISSUE TITLE
command line parsed wrongly, please fix

### ISSUE THREAD

**Issue by archsolar** [rrousselGit/riverpod#3006]
Hi, I was following the getting started guide online and I realized that there's something wrong with the way this is parsed:

https://riverpod.dev/docs/introduction/getting_started#installing-the-package
This is the correct command you'd have to paste in cmd: `flutter pub add flutter_riverpod dev:custom_lint dev:riverpod_lint riverpod_annotation dev:build_runner dev:riverpod_generator`
This is the command that's written on the website (which just makes things more difficult for no reason):
`flutter pub add \
  flutter_riverpod \
  riverpod_annotation \
  dev:riverpod_generator \
  dev:build_runner \
  dev:custom_lint \
  dev:riverpod_lint`

Here is the documentation source:
https://github.com/rrousselGit/riverpod/blob/cf29f4d569adf58b21f3d898ec8187e5946940e9/website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/getting_started/pub_add.tsx#L3

**Comment by rrousselGit** [comment]
What's wrong with it?

Using \ is the official way to use new lines in commands

**Comment by archsolar** [comment]
Well boss, when I paste the command in terminal it says Not a valid package name: "null". 

```
> flutter pub add \ flutter_riverpod \ riverpod_annotation \ dev:riverpod_generator \ dev:build_runner \ dev:custom_lint \ dev:riverpod_lint
Not a valid package name: "null"
```

**Comment by rrousselGit** [comment]
what terminal?

**Comment by archsolar** [comment]
The one in vscode I'm on windows 11... it should be powershell

**Comment by rrousselGit** [comment]
I see. The \ is for Bash, so that's your issue.

I wanted to format it using multiple lines to make it clearer what's installed. But if necessary, we can remove those \

**Comment by archsolar** [comment]
Ah I did not know this.
Well, it would support powershell as well, but I don't mind either way. Most people will figure it out anyway,
