### ISSUE TITLE
[riverpod_generator] 3.0.0-dev.3 - No notifier generated when passing arguments to the request.

### ISSUE THREAD

**Issue by odifis** [rrousselGit/riverpod#3021]
Hello,

first of all thank you for this nice project.

**Describe the bug**

I'm trying to generate the code after defining a notifier, passing argument to the request. The notifier attribute on the provider is not generated.

I'm using the example
https://github.com/bizz84/flutter-tips-and-tricks/blob/main/tips/0097-riverpod-notifier-build-argument/index.md

```
@riverpod
class ItemController extends _$ItemController {
  @override
  FutureOr<void> build({required String itemId}) {
    // no-op
  }

  Future<void> deleteItem() async {
    final repository = ref.read(itemsRepositoryProvider);
    await repository.deleteJob(itemId: itemId);
  }
}

```
Generating the code via dart run build_runner build is successful on no error is in the logs.

But The following attribute is not available :
itemController.notify

I would like to call:
`ref.read(itemControllerProvider.notifier).deleteItem()`

It's working when the build method has no attribute.

**To Reproduce**

```
flutter create test
cd test
flutter pub add riverpod riverpod_annotation dev:build_runner dev:riverpod_generator:3.0.0-dev.3
dart run build_runner build
```

**Expected behavior**

To have access to itemControllerProvider.notify

N.B : I could'nt test on the last version 3.0.0-dev.4 because of #3005 .

Thank you,

**Comment by rrousselGit** [comment]
You need to pass the parameters

```
ref.read(itemControllerProvider(itemId: 42).notifier).deleteItem()
```
