### ISSUE TITLE
appflowy_editor dependency erorr 

### ISSUE THREAD

**Issue by BGM-109** [rrousselGit/riverpod#3037]
**Describe the bug**

Hello bros

When I add Appflowy_editor package , I encounter this error :(

Because riverpod_lint >=2.2.1 depends on analyzer ^6.0.0 and intl_utils >=2.8.0 depends on analyzer ^5.0.0, riverpod_lint >=2.2.1 is incompatible with intl_utils >=2.8.0.
And because appflowy_editor 1.5.0 depends on intl_utils ^2.8.2 and no versions of appflowy_editor match >1.5.0 <2.0.0, riverpod_lint >=2.2.1 is incompatible with appflowy_editor ^1.5.0.
So, because notion_clone depends on both appflowy_editor ^1.5.0 and riverpod_lint ^2.3.2, version solving failed.

If i do not fix the version, version 0.0.4 is installed and will not run.

Is it possible to modify it?

**Comment by rrousselGit** [comment]
riverpod_lint required analyzer 6.0, so no. The analyzer version is up-to-date on my side.

You could ask intl_utils to support >=5.0.0<7.0.0.
