### ISSUE TITLE
Being able to invalidate/refresh family providers conditionally

### ISSUE THREAD

**Issue by busslina** [rrousselGit/riverpod#3038]
Similar to `select` feature, being able to `invalidate`/`refresh` a family provider based on a function that returns a boolean and receives as parameters the family param(s)/key(s)

**Comment by rrousselGit** [comment]
I'm not sure what the syntax for this would be.

We can't use `ref.invalidate(family(arg: value))` because some args may be required or have default values. We'd need something else

**Comment by busslina** [comment]
I will try to study the code so I could propose a more feasible solution (if possible)

**Comment by TekExplorer** [comment]
This feels like we'd need some way to programmatically select a specific set of arguments, based on what family instances already exist.

perhaps something like
```dart
ref.invalidate(family.selectWhere((arguments) => switch (arguments) {
      (_, 'foo', id: 1) => true,
      (false, 'bar', id: 2) => true,
      _ => false,
   },
));
```
which would invalidate `family(true, 'foo', id: 1)`,  `family(false, 'foo', id: 1)`, and `family(false, 'bar', id: 2)` if they exist

This would presumably require querying the container for all existing providers for the family, and running it's arguments record through the selector, and acting that way.

One would have to wonder what would happen when you tried to read this selector. would you get a list of values?

**Comment by rrousselGit** [comment]
I do not want to expose a way to iterate over the existing arguments available, so I don't want such an API

**Comment by rrousselGit** [comment]
Closing as I don't want to expose a way to iterate over arguments (as this could very easily be misused)

**Comment by TekExplorer** [comment]
i dont think that "completed" is what this should have been closed as, but eh
