### ISSUE TITLE
scoped_providers_should_specify_dependencies lint gets triggered in tests

### ISSUE THREAD

**Issue by lockieRichter** [rrousselGit/riverpod#3047]
**Describe the bug**
The `scoped_providers_should_specify_dependencies` lint from the `riverpod_lint` warning gets triggered when running unit tests with `ProviderScope`.

**To Reproduce**
This happens for the example test from the docs.

```Dart
testWidgets('override repositoryProvider', (tester) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        // Override the behavior of repositoryProvider to return
        // FakeRepository instead of Repository.
        repositoryProvider.overrideWithValue(FakeRepository())
        // We do not have to override `todoListProvider`, it will automatically
        // use the overridden repositoryProvider
      ],
      child: MyApp(),
    ),
  );
});
```

**Expected behavior**
No warning should be generated as this is the reccomended way to override behaviour during a test.

**Comment by lockieRichter** [comment]
Closing as this is not a bug now that I look a little closer, this is more of an issue that I need to specify the dependencies in the test file. Just need to figure out how to do that now 🤔

**Comment by lockieRichter** [comment]
Have raised https://github.com/rrousselGit/riverpod/discussions/3048, as I couldn't find the answers I was looking for

**Comment by rrousselGit** [comment]
This _is_ a bug
The issue is https://github.com/rrousselGit/riverpod/issues/2355
