### ISSUE TITLE
What does "this" mean for provider?

### ISSUE THREAD

**Issue by bisgardo** [rrousselGit/riverpod#3060]
The readme states:

> See the [FAQ](https://github.com/rrousselGit/riverpod#FAQ) if you have questions about what this means for [provider](https://github.com/rrousselGit/provider).

The FAQ link points to a section in the readme that isn't there.

I assume that "this" means "the existence of riverpod", but it isn't really clear from the wording.

And I would like to know what that does mean for provider :)

**Comment by bisgardo** [comment]
After a little digging I see that the section was there until https://github.com/rrousselGit/riverpod/commit/dbf47a3953f449cfb57736355ea4afb6cd4eaaa5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L137.

As someone who is just getting started with Flutter and in the process of deciding what state management library to use, this information is very valuable to me.

**Comment by rrousselGit** [comment]
Looks like I forgot to remove this line

**Comment by rrousselGit** [comment]
> As someone who is just getting started with Flutter and in the process of deciding what state management library to use, this information is very valuable to me.

There are various pages related to provider vs riverpod in the docs already
