### ISSUE TITLE
A way to pass a custom comparator to provider families

### ISSUE THREAD

**Issue by joachimbulow** [rrousselGit/riverpod#3081]
**Is your feature request related to a problem? Please describe.**
We want to create a provider, let us call it `getFoosByIds`. It is a family provider, ideally just taking a `List<String>`
This provider may be called multiple times with separate reference `Lists` with the same content, in which case separate providers will be instantiated doing the exact same logic, because `Lists`. are compared by reference, not by content

We seem to have two primary options: 
1. Join the list to a string, to use as family, and split the string back into a `List` inside the provider
or
2. Create a specialized object with a field containing the `List`, and override the compare function to compare on values inside the list.

Neither seem very sleek.

**Describe the solution you'd like**
It would be nice, if we could pass a compare function, perhaps a lambda like `(a, b) => boolean`

**Describe alternatives you've considered**
I am not sure how to implement the compare function in a sleek way. Could be a named parameter reflected to the name of the family parameter for example.

**Additional context**
N/A

**Comment by rrousselGit** [comment]
I don't think that's really something I want to implement.

I'd suggest using a custom List implementation. There are a few packages with it.

**Comment by joachimbulow** [comment]
Yeah - i do not see a way to make a pretty implementation of that anyway
