### ISSUE TITLE
Update documentation for State Inspection in Flutter DevTools

### ISSUE THREAD

**Issue by kumamotone** [rrousselGit/riverpod#3087]
<img width="1111" alt="CleanShot 2023-11-02 at 19 16 56@2x" src="https://github.com/rrousselGit/riverpod/assets/8403570/7139f10c-a860-420d-9be2-ba0a12721b9d">

I have a question regarding the `Inspect your state in the devtool` feature advertised on the [Riverpod website](https://riverpod.dev/). The website mentions that `Using Riverpod, your state is visible out of the box inside Flutter's devtool.` However, I am unable to find this functionality in my current setup.

### Related Discussion

I found a discussion in issue #1039 about adding a dedicated Riverpod tab in the Flutter devtool to inspect the state (which is an exciting development). I understand this to correspond with the `Furthermore, a full-blown state-inspector is in progress` section(please correct me if my understanding is incorrect).

As shown in the documentation, I expected to see the content of `configurationProvider` within `ProviderScope` in the Flutter devtool, but it was not present. Additionally, it seems that other developers I've talked with on X might also not be aware of this feature([post1](https://twitter.com/K9i_apps/status/1720014240877301973) / [post2](https://twitter.com/ma_freud/status/1719960873547014516)) ). Could we be overlooking something?

### Request for Clarification or Documentation Update

If the feature to display the state in Flutter's devtool is not currently available, I suggest removing or updating the information on the documentation page to prevent confusion. Alternatively, if there is an equivalent feature available, I would greatly appreciate guidance on how to use it.

Thank you for your assistance and the continuous development of Riverpod.

**Comment by rrousselGit** [comment]
This is referring to the widget tree inspector. In there, find a ProviderScope. And when clicking on it, the ProviderScope exposes its state.

**Comment by kumamotone** [comment]
<img width="1120" alt="CleanShot 2023-11-02 at 23 05 58@2x" src="https://github.com/rrousselGit/riverpod/assets/8403570/fb4ba567-2dd9-43c6-8282-5e19770317cc">

Thank you for your prompt response.

For example, when I looked at the widget detail tree using the todo sample in this repository and clicked on ProviderScope, I could not see the Provider contents (contents of the todo list) as shown in the documentation snapshot.

**Comment by muzammil-git** [comment]
The provider package shows clear state while riverpod doesn't show its state in provider tab. Although I found Riverpod such a great package. Just need state in provider tab. Any workaround to show ?


<img width="958" alt="image" src="https://github.com/rrousselGit/riverpod/assets/54685589/391125ad-063e-41c3-aa6c-7e3cd9463afc">

**Comment by rrousselGit** [comment]
The provider page is unrelated to Riverpod. There will be one for Riverpod though.

@kumamotone Sounds like there's an issue somewhere.
Riverpod does serialize the app state into something humanly readable. Maybe the devtool doesn't show it anymore.
But a full-blown inspector is coming by the end of the year anyway

**Comment by rrousselGit** [comment]
I'll close this in favour of https://github.com/rrousselGit/riverpod/issues/1033 because https://github.com/rrousselGit/riverpod/issues/1033 is coming soon

**Comment by kumamotone** [comment]
Thank you for answering. I am looking forward to the release of #1033.
