### ISSUE TITLE
AVOID using providers for local widget state.

### ISSUE THREAD

**Issue by wph144** [rrousselGit/riverpod#3090]
<img width="874" alt="image" src="https://github.com/rrousselGit/riverpod/assets/10491866/50a4a937-32f2-44d6-be64-f0394d5e1a1a">

I'm struggling to fully grasp what "local widget state" means.

1. Does "local widget state" refer to "all states that are only used within a single route"?
2. Besides the following four types, there are likely many other kinds of local states - are we only talking about these four, or does it 
include all other local widget states as well?
<img width="650" alt="image" src="https://github.com/rrousselGit/riverpod/assets/10491866/c3d57658-b5d1-4411-9e9b-8bff2cbac23d">

The phrase “such state is often scoped to a route” seems to suggest we’re discussing all states that are used only within a route. Does that mean Riverpod should only be used for variables that span multiple screens? Indeed, some people interpret it this way and use Riverpod solely for very few app-global states, relying on Flutter’s StatefulWidget for everything else. Is this a misconception, or a correct understanding of Riverpod?

Considering “Failing to do so could break your app’s back button, due to a new page overriding the state of a previous page”, it appears to be addressing problems arising when a state, which is supposed to be independent in screen A, is used independently in screen B as well, but is treated globally with the same Provider, causing issues. If this is the point trying to be made, perhaps the entire paragraph needs to emphasize that it's discussing state that should be used independently in two or more routes. As it stands, the aforementioned “such state is often scoped to a route” or "AVOID using providers for local widget state" could potentially lead to confusion.

**Comment by Maxim-Filimonov** [comment]
I'm also wondering about this as there is [cookbook example](https://riverpod.dev/docs/cookbooks/search_as_we_type) which breaks that best practise and stores local widget state in the provider. Is cookbook example obsolete ? And if it's not recommended approach which one is ?

**Comment by rrousselGit** [comment]
This is obsolete yes.
The cookbook should be updated to respect good practices

**Comment by wph144** [comment]
@rrousselGit 

1. Riverpod doc seems to define "local widget state" as "all states that are only used within a single route". This scope is so broad. Almost state should not be used with riverpod. In fact, flutter doc define the scope as "in a single widget", but riverpod defines "in a route"

2. What does means "Failing to do so could break your app’s back button, due to a new page overriding the state of a previous page"?

3. For example, a route have data list, search keyword(String) and type filter. What is local widget state as described in riverpod doc?

**Comment by rrousselGit** [comment]
In short, everything that could be a query parameter in a URL shouldn't be in a provider.

For example, don't store the "currently selected book ID" in a notifier. Because that's typically stored in the route path instead (`/books/:id`).

Because apps usually want to support a navigation history such as:

```
/books
/books/42
/books/21
```

where going back by one goes to `/books/42`. But if the currently selected ID was stored in a provider instead of the route path for instance, then chances are that when pressing the back button, the currently selected ID wouldn't revert to the previous value

**Comment by wph144** [comment]
> In short, everything that could be a query parameter in a URL shouldn't be in a provider.
> 
> For example, don't store the "currently selected book ID" in a notifier. Because that's typically stored in the route path instead (`/books/:id`).
> 
> Because apps usually want to support a navigation history such as:
> 
> ```
> /books
> /books/42
> /books/21
> ```
> 
> where going back by one goes to `/books/42`. But if the currently selected ID was stored in a provider instead of the route path for instance, then chances are that when pressing the back button, the currently selected ID wouldn't revert to the previous value


Why don't you add this as a new item to the DO/DON'T ? This content seems to lack relevance to the earlier part of the local widget state section. Title is "DON'T use providers for everything that could be a query parameter in a URL"


Additionally, I wonder about 1 and 3, too

> @rrousselGit
> 
> 1. Riverpod doc seems to define "local widget state" as "all states that are only used within a single route". This scope is so broad. Almost state should not be used with riverpod. In fact, flutter doc define the scope as "in a single widget", but riverpod defines "in a route"
> 2. What does means "Failing to do so could break your app’s back button, due to a new page overriding the state of a previous page"?
> 3. For example, a route have data list, search keyword(String) and type filter. What is local widget state as described in riverpod doc?

**Comment by Reprevise** [comment]
> In short, everything that could be a query parameter in a URL shouldn't be in a provider.

Does this apply to scoped providers too? If inside of a "book details" route, I have a scoped `Provider<int>` like `bookIdProvider`, is that bad? The alternative would be that I'd have to do something like `RouteData.of(context).pathParameters['id']` and parse that as an integer everywhere.

**Comment by Maxim-Filimonov** [comment]
> In short, everything that could be a query parameter in a URL shouldn't be in a provider.
> 
> For example, don't store the "currently selected book ID" in a notifier. Because that's typically stored in the route path instead (`/books/:id`).
> 
> Because apps usually want to support a navigation history such as:
> 
> ```
> /books
> /books/42
> /books/21
> ```
> 
> where going back by one goes to `/books/42`. But if the currently selected ID was stored in a provider instead of the route path for instance, then chances are that when pressing the back button, the currently selected ID wouldn't revert to the previous value

So you woud recommend against using provider to wrap access to currently selected book even if provider gets it from within router? Or is it specifically for global providers.

**Comment by mboyamike** [comment]
I think if you're using a family provider then that should be fine

The issue @rrousselGit is referring to is if the id is provided by a notifier, and you have something like mybooknotifier.setBookId(id)

Let the URL be the source of truth for the id
