### ISSUE TITLE
first request documentation update

### ISSUE THREAD

**Issue by rohitbhoite** [rrousselGit/riverpod#3094]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.
Current switch-based dart code gives error while adding provider as per the documentation.
It can be replaced with  .when( block.
**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rohitbhoite** [comment]
https://github.com/rrousselGit/riverpod/pull/3093
Raised a pr to fix it.

**Comment by rrousselGit** [comment]
No the switch is correct.

Either your dart version is out of date or you need to update your pubspec.yaml.

There is nothing wrong with the code shown :)
