### ISSUE TITLE
Perfect Chinese translation

### ISSUE THREAD

**Issue by laterdayi** [rrousselGit/riverpod#3100]
Perfect Chinese translation

At present, there is no Chinese translation in many parts of the document, can you supplement it, or can you use gpt and other methods

**Comment by yang-lile** [comment]
I want to start this translation, have somebody together?

**Comment by laterdayi** [comment]
Look forward to your participation, or you can try a part, I believe there will be more people participate

**Comment by rrousselGit** [comment]
Feel free to have a go.
I can't do anything myself though, so I'll close this. But I encourage you to raise a PR :)

**Comment by laterdayi** [comment]
For example: I have A page, A controller, in A controller store a lot of data and update data methods (string Boolean model class, update string update model class to get data), such a structure with the latest syntax generator should be how to achieve, Could the official provide a similar example in the document


@rrousselGit
