### ISSUE TITLE
Markup explanation about the document

### ISSUE THREAD

**Issue by laterdayi** [rrousselGit/riverpod#3104]
Markup explanation about the document

![image](https://github.com/rrousselGit/riverpod/assets/122137647/add86f8c-b8da-474f-b9ff-cc70f95f4027)

As for the meaning of old, does it mean that these subsequent use are not recommended? Can you indicate what the new is

**Comment by mboyamike** [comment]
Oh in this case old just means it's the old version of the documentation.  The use is still recommended but kept there as a way of easily finding that particular documentation.

**Comment by rrousselGit** [comment]
Correct. I plan to update that this week with a more descriptive alternative

**Comment by laterdayi** [comment]
Expect to improve riverpod's documentation, which seems a little incomprehensible

**Comment by rrousselGit** [comment]
What's incomprehensive?

**Comment by laterdayi** [comment]
1. The latest riverpod syntax generation has no introduction or examples
2. The old document has more information than the new one
3. The latest example of riverpod has a mix of old syntax and new syntax that makes it hard to understand

**Comment by rrousselGit** [comment]
> The latest riverpod syntax generation has no introduction or examples

What do you mean? All pages showcase both the old and new syntax at the same time. There's a toggle to switch between them on the top-right of the site

> The old document has more information than the new one


Which information are you referring to?

> The latest example of riverpod has a mix of old syntax and new syntax that makes it hard to understand

Which example are you referring to?

**Comment by laterdayi** [comment]
You should provide as many descriptions and examples of the latest syntax generators as possible, but I've seen a lot of documentation about older documentation

**Comment by laterdayi** [comment]
Whether it can include the difference and performance with other state management can make everyone better choice

**Comment by laterdayi** [comment]
Also, I have seen some flutter_hooks in the documentation that are not consistent with flutter philosophy, but riverpod recommends using them with flutter_hooks, which is confusing
