### ISSUE TITLE
Migrating from StateNotifier to Notifier

### ISSUE THREAD

**Issue by shashkiranr** [rrousselGit/riverpod#3105]
I use a lot of mixins on StateNotifier and this helps me add and remove features(mixins) to StateNotifier and keeps my code very organised.  Before I used the following code

```
mixin StateLogic1Mixin<T> on StateNotifier<T> {

 void multiUseMethod1(){
     state = state.copyWith(update1:true);
 }

 void multiUseMethod2(){
     state = state.copyWith(update2:true);
 }

}

```

I was able to use this mixin with multiple state notifier whether autodispose/family and add and remove mixin.

Now with the new Notifier i have to use a typedef and call mixin on that.
```
typedef NotifierDef<T> = Notifier<T>;

mixin StateLogic1Mixin<T> on NotifierDef<T> {

 void multiUseMethod1(){
     state = state.copyWith(update1:true);
 }

 void multiUseMethod2(){
     state = state.copyWith(update2:true);
 }

}
```

To use this mixin on Family, Async, keep alive notifier I would need to replicate StateLogic1Mixin for each since 

1. `typedef NotifierDef<T> = Notifier<T> | Family<T> ` (Union types) is not support in dart. 
2.  **BuildlessNotifier** and **NotifierBase** are internal
3.  If i remove the on NotifierDef<T> then I can't access the state.

Is there a way I can apply this StateLogic1Mixin on all riverpod notifiers so I can write logic once and apply to all kinds of Notifiers whenever it is required?

**Comment by rrousselGit** [comment]
Currently the recommended solution is to not use the `on` clause:

```dart
mixin Example<T> {
  Ref<T> get ref;
  abstract State<T> state;
}

class MyNotifier extends Notifier<int> with Example<int> {

}
```

There are plans to enable using `on` by removing AutoDisposeNotifier https://github.com/rrousselGit/riverpod/issues/2576

So closing in favour of that issue

**Comment by shashkiranr** [comment]
Ok I will wait for the other issue to be fixed. Just want to know how to resolve the `State` since it only refers to State present in StatefulWidget and not the State present in riverpod. Which import should I use?

**Comment by rrousselGit** [comment]
Sorry that was a mistake. Updated

**Comment by shashkiranr** [comment]
Thank you for confirming. I just want to update what you added since `Ref<T> get ref;` throws error `('Ref<T> Function()') isn't a valid override of 'BuildlessNotifier.ref'`

```
mixin Example<T> {
  Ref<T> get mixinRef;
  abstract T state;
}

class MyNotifier extends Notifier<int> with Example<int> {
  @override
  Ref<int> get mixinRef => super.ref;  // still shows Notifiers should not have public properties/getters. Instead, all their public API should be exposed through the `state` property 
}
```
