### ISSUE TITLE
Unable to run mulltiple ProviderScopes side by side  -> Only one task can be scheduled at a time

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/riverpod#3118]
**Describe the bug**
This issue is created based on this discussion: https://github.com/rrousselGit/riverpod/discussions/2494

Running multiple provider scopes side by side causes a 'Only one task can be scheduled at a time' error to be thrown.

It seems this commit was meant to fix the issue, but it didn't and now that vsyncOverride has been removed, the workaround no longer works: https://github.com/rrousselGit/riverpod/commit/dd3c7df6a6b309fbd2bd1ed70f9155b8eeefac1a#diff-c076f630a06d1dea3d897982a89bb148676e0d6db0c408c3b29b4a157b91c87e

**To Reproduce**

I've created a test that will reproduce the issue: https://github.com/rrousselGit/riverpod/pull/3117

**Comment by Colton127** [comment]
After upgrading to 2.4.6, I am getting this error throughout my app. I have one root provider scope but do override a specific provider in parts of my code. However, this error is thrown independent of provider scope overrides.

**Comment by ubergaijin** [comment]
> After upgrading to 2.4.6, I am getting this error throughout my app. I have one root provider scope but do override a specific provider in parts of my code. However, this error is thrown independent of provider scope overrides.

same problem for me, works fine after downgrading to 2.4.5

**Comment by sarakisar97** [comment]
Any update?

**Comment by Reprevise** [comment]
I guess I'll have to stay on 2.4.5 until this gets fixed.

**Comment by rrousselGit** [comment]
Although this is a bug, to be clear my plan for 3.0 was to remove the ability to have multiple "root" providerContainers.
The main motivation is that we could massively improve performances by disallowing this.

Although this is a regression, this seems to be specific to that scenario.

Could you explain why you need to run multiple ProviderScopes side-by-side? Because otherwise even if I fix this, you're bound to encounter the error again as I remove support for it.

**Comment by josh-burton** [comment]
> Although this is a bug, to be clear my plan for 3.0 was to remove the ability to have multiple "root" providerContainers. The main motivation is that we could massively improve performances by disallowing this.
> 
> Although this is a regression, this seems to be specific to that scenario.
> 
> Could you explain why you need to run multiple ProviderScopes side-by-side? Because otherwise even if I fix this, you're bound to encounter the error again as I remove support for it.

I'm essentially running multiple apps within 1 parent app.

I have a storybook type application that renders my app multiple times in different configurations, so each app instance has an independent providerscope.

**Comment by rrousselGit** [comment]
You could run two side-by-side apps using overrides instead

**Comment by rrousselGit** [comment]
Storybook is a good call. I guess I'll have to find a non-breaking way to implement this performance improvement.

In any cases, I'll fix this as that's a regression for the moment.

**Comment by Reprevise** [comment]
> Could you explain why you need to run multiple ProviderScopes side-by-side?

AFAIK, unless I'm misunderstanding your meaning, I'm only using multiple ProviderScopes for scoping my providers. I have just one `UncontrolledProviderScope` at the root of my application and I was encountering this issue.

**Comment by rrousselGit** [comment]
@Reprevise Scoping providers is out of the scope of this issue (pun intended).
I'm referring to having multiple non-scoped ProviderScope

Like;

```dart
runApp(
  Column(
    children: [
      ProviderScope(...),
      ProviderScope(...),
    ],
  ),
);
```

**Comment by Reprevise** [comment]
@rrousselGit Yeah that's that what our app does. We have an UncontrolledProviderScope above where Column is in your example, and encountered the issue, albeit only on hot-reload.

**Comment by Colton127** [comment]
> @Reprevise Scoping providers is out of the scope of this issue (pun intended). I'm referring to having multiple non-scoped ProviderScope
> 
> Like;
> 
> ```dart
> runApp(
>   Column(
>     children: [
>       ProviderScope(...),
>       ProviderScope(...),
>     ],
>   ),
> );
> ```

I am experiencing the same issue and only have a single root ProviderScope for my entire app.

On a page within my app, there is a listview builder that uses ProviderScope to override the values of a specific provider to prevent unnecessary rebuilds of children widgets. But this error is thrown at numerous locations of my app outside of this particular listview.

**Comment by Genhain** [comment]
im encountering the issue trying to use goldenkit's device builder, although there is ways around this, i would like it to work without this issue

```dart
final widget = ProviderScope(
        overrides: [dbProvider.overrideWithValue(realm)],
        child: MaterialApp(home: Scaffold(body: LayoutBuilder(builder: (a, b) {
          return Column(
            children: [
              const Spacer(),
              Row(
                children: [
                  const SizedBox(
                    width: 20,
                  ),
                  Expanded(
                      child: InstrumentActivationGraph(
                    width: b.maxWidth - 40,
                    caseModelId: id,
                  )),
                  const SizedBox(
                    width: 20,
                  ),
                ],
              ),
              const Spacer()
            ],
          );
        }))));

    final builder = DeviceBuilder()
      ..overrideDevicesForAllScenarios(devices: [
        Device.iphone11,
        Device.phone,
      ])
      ..addScenario(
          widget: widget,
          onCreate: (key) async {
            final sut = find.byKey(key);
            final widget = find.descendant(
                of: find.byKey(key),
                matching:
                    find.byKey(const ValueKey('activation_graph_slider')));

            final initialPosition = tester.getCenter(widget);
            final gesture = await tester.startGesture(initialPosition);
            await gesture.moveBy(Offset(tester.getSize(sut).width / 2, 0));
            await tester.pumpAndSettle();
            await gesture.up();
          });

    await tester.pumpDeviceBuilder(builder);

    await screenMatchesGolden(tester, 'activation_graph');
```

**Comment by hazzo** [comment]
Still not fixed for our app. We have two `UncontrolledProviderScope` with the same container. One for the app and the other to use this package [screenshot](https://pub.dev/packages/screenshot) to take a screenshot from a widget outside of the current app. So we reuse the container with a new `UncontrolledProviderScope` and we get this error. Downgrading to 2.4.5 fixed the issue. I'll try to create a reproducible example.
