### ISSUE TITLE
 Nested ProviderScope does not call child Observer

### ISSUE THREAD

**Issue by chrg1001** [rrousselGit/riverpod#3122]
**Describe the bug**

If a ProviderObserver is passed to each nested ProviderScope, only the parent Observer's function will be triggered and child's will not.

**To Reproduce**.

You can reproduce it with the following commented out test

https://github.com/rrousselGit/riverpod/blob/d9f1881e7260db5180f2b0eb645e349d6033e44e/packages/riverpod/test/framework/provider_observer_test.dart#L72-L114

**Additional info**

Even if Observer was not passed to the parent Container, the child Observer was not invoked. It may be that only the Observer passed to the top-level Container is functioning.

**Expected behavior**

All Observer functions are called

Was this feature intentionally removed? Or is it a test case that will be made available again in the future, but currently ignored in terms of priority, etc.?

**Comment by chrg1001** [comment]
My use case is to use `ProviderObserver` to catch network errors generated inside `FutureProvider` / `AsyncNotifier` to show SnackBar or screen transitions.

To do this, I need to place an additional `ProviderScope` in the part that can pass `context`, but for the reasons mentioned above, my `ProviderObserver` here is not working.

Specifically, I am passing the following `ProviderObserver`.

```dart
class NetworkExceptionProviderObserver extends ProviderObserver {
  const NetworkExceptionProviderObserver({
    required BuildContext context,
  }) : _context = context;

  final BuildContext _context;

  @override
  void providerDidFail(
    ProviderBase<Object?> provider,
    Object error,
    StackTrace stackTrace,
    ProviderContainer container,
  ) {
    if (error is NetworkException) {
      switch (error.code) {
        case NetworkExceptionCode.unexpected:
          Future.delayed(
            Duration.zero,
            () => _context.goNamed(...),
          );
          return;
        case ...
          ...
      }
    }
  }
}
```

**Additional information**

I am using riverpod 2.4.6, which fixes the following problems

- #1580

**Comment by rrousselGit** [comment]
The commented out test is working fine. It was commented out due to the lack of an overrideWithValue after it was removed.
I've restored the test by using overrideWith instead, and didn't see a problem.

You'd have to share more about your setup to know if there's an issue.

Note that nested scopes only have their observers invoked for the providers associated with this scope. In particular, your observer will only get called if you also scope providers. Then, when those scoped providers update, the observer will be notified accordingly.

For non-scoped providers, the scoped observer will **not** be notifier. Because that provider is not part of said scope.

**Comment by chrg1001** [comment]
@rrousselGit 

> Note that nested scopes only have their observers invoked for the providers associated with this scope. In particular, your observer will only get called if you also scope providers. Then, when those scoped providers update, the observer will be notified accordingly.

I may be slightly mistaken on this point. Wouldn't a Provider that is first watched inside a ProviderScope be the ScopedProvider for that Scope?

Specifically, in the following simple example, I thought that a change in `providerB` would be notified to both `ParentObserver` and `ChildObserver`.

https://dartpad.dev/?id=046caa0b9e646eaa12e73cd3bbb6b33d

That is, if the `Change` button is pressed in the above example

Expected behavior is

```bash
[Child] didUpdateProvider: providerB
[Parent] didUpdateProvider: providerA
[Parent] didUpdateProvider: providerB
```

but actual behavior was

```bash
[Parent] didUpdateProvider: providerA
[Parent] didUpdateProvider: providerB
```

**Comment by chrg1001** [comment]
> Note that nested scopes only have their observers invoked for the providers associated with this scope. In particular, your observer will only get called if you also scope providers. Then, when those scoped providers update, the observer will be notified accordingly.

I misunderstood this part a little. I thought that the first Provider watched on a Scope would be the ScopedProvider of that Scope. But after carefully reading the documentation, it does say that. Thank you very much.

> _If the provider has not been overridden in any Widget subtrees the lookup defaults to the [ProviderContainer](https://pub.dev/documentation/riverpod/latest/riverpod/ProviderContainer-class.html) in the root [ProviderScope](https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ProviderScope-class.html)._
