### ISSUE TITLE
For AsyncNotifier allow setting its state with several state parts at the same time

### ISSUE THREAD

**Issue by rivella50** [rrousselGit/riverpod#3133]
**Is your feature request related to a problem? Please describe.**
In my current project i use an `AsyncNotifier` for guiding the user through a 3-step process of creating a new document.
The state stores the current step. Each step may fail, where i then set the state to `AsyncError`. At the same time i would like to set the state's data part to the first step since the user has to restart the process.
But apparently this doesn't seem possible, i.e. setting the `AsyncError` _and_ `AsyncData` at the same time, leading to just one new state emit.

**Describe the solution you'd like**
In its simplest way i would suggest a new factory constructor for `AsyncValue`:
```
const factory AsyncValue.fromStateParts({
  AsyncData? data,
  AsyncLoading? loading,
  AsyncError? error,
});
```
which allows setting more than one state at the same time and therefore leading to just one new emit.
In my opinion other parts involved (like `when` function) wouldn't need to be updated since loading would still beat error and data.
If a developer would use the new suggested approach he'd know that he probably has to react differently for his watchers/listeners.
I'm pretty sure that other combinations (e.g. loading and data) would also make sense to be updated at the same time for certain scenarios.

**Describe alternatives you've considered**
Randal Schwartz suggested using `AsyncValue.copyWithPrevious` or using cascading of state parts, but both didn't work.
I also tried writing an extension for `AsyncValue` but since all constructors are private this didn't work either.

If my approach could already be achieved without changing Riverpod please let me know.

**Comment by rrousselGit** [comment]
I'm not sure which problem you're trying to solve exactly.

Normally the previous state/error should be fully managed by Riverpod .
Maybe you don't want an AsyncNotifier and want to handle AsyncValue on your own

**Comment by rivella50** [comment]
I would like to avoid an unnecessary 2nd emit of state update by combining the set state call for the mentioned `AsyncError` and `AsyncData` parts.

At Discord user _TekExplorer_ summarized it like that: "...he wants to transition from an AsyncData(value: a) to AsyncError(value: b, error) and riverpod has internal transitions that block that, unless he was willing to accept 2 rebuilds, 1 to shift to initial, and another to shift to error."

I'm totally fine with `AsyncNotifier`.

**Comment by rrousselGit** [comment]
> he wants to transition from an AsyncData(value: a) to AsyncError(value: b, error) a

But why?

**Comment by rrousselGit** [comment]
AsyncNotifier comes with automatic transition. You seem to not want that so you probably shouldn't be using it

**Comment by rivella50** [comment]
Again: Just to save one unnecessary new state emit.
The transition to error is completely ok, but i would like to have the changed data value as will within that transition.
Since `AsyncValue` is capable of containing the information about multiple state at once i thought applying that multiple state in one setter call should be ok too.

**Comment by lucavenir** [comment]
Hey @rrousselGit after discussing with @rivella50 about this issue on [discord](https://discord.com/channels/765557403865186374/765557404766830614/1175812719228747848) it turns out that something doesn't add up, or at least we're surely confused about `copyWithPrevious` (or its implicit use when transitioning state).

Given that `asyncTransition` handles transitions for us, and that it's still not enough for @rivella50 (he has to inject handmade state instead), why are the following tests failing?

Example:
```dart
// example error
class SomeError implements Exception {
  const SomeError();
}

final myNotifierProvider = AsyncNotifierProvider.autoDispose<MyNotifier, int>(MyNotifier.new);

class MyNotifier extends AutoDisposeAsyncNotifier<int> {
  @override
  FutureOr<int> build() => 0;

  Future<AsyncValue<int>> mutate({required bool crashIt}) async {
    final result = await AsyncValue.guard(() async => crashIt ? throw SomeError() : 1);
    if (result case AsyncError()) {
      const handmadeData = AsyncData(2);
      final newState = handmadeData.copyWithPrevious(result);
      state = newState;
      return newState;
    }
    state = result;
    return result;
  }

  @override
  set state(AsyncValue<int> newState) {
    super.state = newState;
  }
}
```
Tests:
```dart
void main() {
  test('testing my notifier', () async {
    final container = ProviderContainer();
    addTearDown(container.dispose);
    final listener = container.listen(myNotifierProvider, (previous, next) {});
    addTearDown(listener.close);

    final init = listener.read();
    expect(init.requireValue, 0);

    var result = await container.read(myNotifierProvider.notifier).mutate(crashIt: false);
    final after = listener.read();
    expect(result.requireValue, 1);
    expect(after.requireValue, 1);

    result = await container.read(myNotifierProvider.notifier).mutate(crashIt: true);
    final crashed = listener.read();
    expect(result.requireValue, 2);
    expect(result.error, const SomeError());  // this unexpectedly fails! didn't I copied this..?
    expect(crashed.requireValue, 2);
    expect(crashed.error, const SomeError());  // this is failing too as a result!
  });
}
```

**Comment by AhmedLSayed9** [comment]
A possible fix and an alternative have been discussed here https://github.com/rrousselGit/riverpod/issues/2102

**Comment by rivella50** [comment]
Btw. this is what i tried and we discussed as well:
```
final newValue = AsyncError<AddPlanConfig>(ImageException('my error'), StackTrace.current)
    .copyWithPrevious(AsyncData(state.value!.copyWith(
    nextStep: AddPlanStep.init
)));
state = newValue;
```
`newValue` actually contains both the `AsyncError` and the new `AsyncData` value, but the problem comes when trying to apply `newValue` to `state`.
First we encountered 3 different implementations of `copyWithPrevious`. When looking at the one for `AsyncError` it seems ok, but when debugging we see that in `asyncTransition` it does a `copyWithPrevious` itself where the `AsyncData` part gets cut away if the state had a previous version.

**Comment by AhmedLSayed9** [comment]
> newValue actually contains both the AsyncError and the new AsyncData value, but the problem comes when trying to apply newValue to state.

This is expected. You still use `.copyWithPrevious`.

The alternative is to do:
```dart
state = AsyncError<AddPlanConfig>(ImageException('my error'), StackTrace.current);
state = AsyncData(state.value!.copyWith(nextStep: AddPlanStep.init));
```

As discussed at the mentioned issue, `copyWithPrevious` is not safe to be used externally.

**Comment by rivella50** [comment]
@AhmedLSayed9 But this leads to 2 separate state emits which i wanted to avoid.

**Comment by AhmedLSayed9** [comment]
There's no issue with it.
They're called synchronously, consumers will not be notified twice :)

**Comment by rrousselGit** [comment]
> Again: Just to save one unnecessary new state emit.

No that's a side-effect of the solution you''re trying to implement.

I'm asking for the root of the problem. What are you trying to implement, regardless of how many rebuilds are involved.

**Comment by rivella50** [comment]
Well, the solution i'm trying to implement (which doesn't seem to be safe at all) doesn't work. Therefore there isn't any side effect happening ;-)

The root of the problem is the same as what @AhmedLSayed9 also tried to figure out and implement: Combining several parts of AsyncValue into a new version of it and then apply it in one step to the AsyncNotifier's state, which then should lead to only one state update emit.

But it seems that this is not intended to be possible - above all not by using the existing copyWithPrevious methods.

**Comment by rrousselGit** [comment]
> Combining several parts of AsyncValue into a new version of it and then apply it in one step to the AsyncNotifier's state, which then should lead to only one state update emit.

Could you be more specific? I'm not sure what that means.

**Comment by rivella50** [comment]
This is the code i tried: https://github.com/rrousselGit/riverpod/issues/3133#issuecomment-1817890464

**Comment by rivella50** [comment]
If `copyWithPrevious` is not supposed to be used
- couldn't that be documented (because i'm sure that other devs also will try to use that method and encounter similar problems)?
- couldn't there be another approach which allows devs to do what @AhmedLSayed9 and i try to do (i'll mention again my naive approach of the factory constructor [here](https://github.com/rrousselGit/riverpod/issues/3133#issue-2000762851))?

**Comment by rrousselGit** [comment]
> This is the code i tried: [#3133 (comment)](https://github.com/rrousselGit/riverpod/issues/3133#issuecomment-1817890464)

Again, you're talking about what you're trying to implement.
I want to know what problem you're trying to solve with this.

Cf https://xyproblem.info/

**Comment by rivella50** [comment]
I can only repeat myself: https://github.com/rrousselGit/riverpod/issues/3133#issuecomment-1817809947
In my opinion those two state updates belong together and therefore it would make sense to group them together.
It's not a problem that i get an error or crash, it's just a semantical problem of how to look at a certain state update built with two aspects.

**Comment by AhmedLSayed9** [comment]
> I can only repeat myself: [#3133 (comment)](https://github.com/rrousselGit/riverpod/issues/3133#issuecomment-1817809947)
> In my opinion those two state updates belong together and therefore it would make sense to group them together.
> It's not a problem that i get an error or crash, it's just a semantical problem of how to look at a certain state update built with two aspects.

Remi wants to know the real use-case you need this feature for.
Maybe, there's a better solution for your use-case and then, we don't need implement a new feature 😃

**Comment by rivella50** [comment]
Please read again the first part of my initial message: https://github.com/rrousselGit/riverpod/issues/3133#issue-2000762851

**Comment by AhmedLSayed9** [comment]
Sorry. Your previous link was redirecting to another comment.

**Comment by AhmedLSayed9** [comment]
It's up to Remi then.

imo, `copyWithPrevious` shouldn't be exposed if it's not working as expected. Therefore, you'll be forced to do:
```dart
state = AsyncData(state.value!.copyWith(nextStep: AddPlanStep.init));
state = AsyncError<AddPlanConfig>(ImageException('my error'), StackTrace.current);
```

**Comment by AhmedLSayed9** [comment]
Btw, for your use-case, I think you should somehow restart the process by using `ref.invalidate` i.e: at the retry button that's used when the process fails.

**Comment by rivella50** [comment]
That's all possible, yes. To me it would just be cleaner to reset the data part right along the occurring error instead of letting the data part stay at a non-current value and wait until the user starts the process again.

**Comment by AhmedLSayed9** [comment]
What's the problem with my alternative above?

**Comment by rivella50** [comment]
No problem, i've just another point of view for when to reset the state.

**Comment by rrousselGit** [comment]
> Please read again the first part of my initial message: [#3133 (comment)](https://github.com/rrousselGit/riverpod/issues/3133#issue-2000762851)

No as I keep saying, that message isn't the problem. That's the solution you're trying to implement.

Don't talk about providers/notifiers here. Take a step back. What UI pattern are you trying to implement?

**Comment by rrousselGit** [comment]
You should be able to formulate your problem in a way that's almost completely independent from Riverpod.

For example rather than "I want to recompute a provider and while it's loading show previous data/error", say "I want users to do a pull-to-refresh, but during the refresh I don't want the data/error to disappear from the UI". 

The former is what you're trying to do. The latter is the actual problem. They can be related, but may not be.

**Comment by rivella50** [comment]
I slightly have to disagree here: Since it's AsyncValue's nature to consist of up to 3 state parts at the same time (which is also useable in the UI for various purposes) i only came to the idea of being able to apply more than one of these state parts in the same state setter call in order to only emit one state update to its consumers, if those state parts somehow belong together.

I don't know if without Riverpod such a construct actually exists, therefore my feature request targets Riverpod and i cannot formulate it in a more general way.

Regarding the actual problem you wanna know: I don't want my UI consumers having to receive more than one state update for AsyncValue state parts which belong together (e.g. an AsyncError and the corresponding data part change which is implicated by that error).

**Comment by rrousselGit** [comment]
Saying that AsyncValue consists about 3 parts at the same time is misleading.
AsyncValue is about one state, and optionally gives you access to the previous one.

I keep asking to know more about your use-case because you do not seem to respect that rule. You don't want the previous state. You want something else. This is not what AsyncValue is intended to be.
As such, without more information about what you're doing, I'm helpless in understanding the problem we're trying to solve.

At the moment, the only possible conclusion for this issue to me is to view this feature request as "improper usage of AsyncValue, likely should use a different mechanism". To change my mind I need more information

**Comment by rivella50** [comment]
Ok, perhaps that's the misunderstanding we have here: For an `AsyncError` and `AsyncLoading` you internally mix it with the previous data part (using `copyWithPrevious`) so that we have the possibility to use that data together with new error or loading state.
What @AhmedLSayed9 and i independently tried is to do the same but with a new data part.
Since you already mentioned that `copyWithPrevious` shouldn't be used from outside Riverpod the only question was if there couldn't be another possibility for us to pass a new data part along an `AsyncError` or `AsyncLoading` state update which does the same as `copyWithPrevious` but uses the new instead of the previous data part for creating the combined `AsyncValue` object and as a result only emits _one_ state update to its consumers.

Together with @AhmedLSayed9 's [use cases](https://github.com/rrousselGit/riverpod/issues/2102#issuecomment-1399093482) you were presented [one more from me](https://github.com/rrousselGit/riverpod/issues/3133#issue-2000762851). That's three use cases in sum, i cannot tell you more here, sorry.

**Comment by rrousselGit** [comment]
> What @AhmedLSayed9 and i independently tried is to do the same but with a new data part.

What I keep asking is _why_?

Why do you want to have the "previous data" not be the actual previous data?

**Comment by rrousselGit** [comment]
Please stop linking the messages you previously wrote in this issue.

They clearly aren't enough for me to understand why you want this feature request. Linking them back only adds frustration.

I want new information, not a link to what I already read before.

**Comment by rrousselGit** [comment]
To begin with, calling `state =` twice in a row wouldn't rebuild widget twice.

ref.watch triggers only a single widget rebuild, no matter how many times a provider updates within a single frame.

**Comment by rivella50** [comment]
All understood. "previous data" may be untouched, i'm not interested in that data at all, i'm just interested in having the possibility to let a new AsyncValue being created which represents state to be AsyncError and at the same time allows me to insert new data.
But the more i read from you i guess that's not possible and also not intended.

Btw. i use ref.listen here and the handler gets invoked twice.

**Comment by rrousselGit** [comment]
From what you describe, this is not intended yes.

**Comment by AhmedLSayed9** [comment]
@lucavenir 
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    const ProviderScope(child: MyApp()),
  );
}

class AsyncTodosNotifier extends AsyncNotifier<List<String>> {
  @override
  Future<List<String>> build() async {
    return [];
  }

  Future<void> addTodo() async {
    state = const AsyncData(['todo']);
    state = const AsyncError('error', StackTrace.empty);
  }
}

final asyncTodosProvider =
    AsyncNotifierProvider<AsyncTodosNotifier, List<String>>(() {
  return AsyncTodosNotifier();
});


class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.listen(asyncTodosProvider, (_, next) {
      print(next);
    });
    return Scaffold(
      appBar: AppBar(
        title: const Text('Riverpod example'),
      ),
      body: const SizedBox(),
      floatingActionButton: FloatingActionButton(
        key: const Key('increment_floatingActionButton'),
        onPressed: () => ref.read(asyncTodosProvider.notifier).addTodo(),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by lucavenir** [comment]
But the side effect in that example is asynchronous, that's the catch I guess

**Comment by AhmedLSayed9** [comment]
You can just ignore that `Future<void>` & `async`, I just copied them from the samples.

**Comment by rrousselGit** [comment]
ref.listen is invoked immediately on `state=`, so if you call it twice, you will get two notifications yes.

**Comment by lucavenir** [comment]
> You can just ignore that `Future<void>` & `async`, I just copied them from the samples.

Yeah okay I get it, it doesn't matter much as they both gets executed synchronously in there. Thank you!
