### ISSUE TITLE
Differentiate between AsyncError and other errors at ProviderObserver.providerDidFail

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/riverpod#3145]
The updated ProviderObserver.providerDidFail version now handles Exceptions from asynchronous providers but there's no way to know if the exception received at providerDidFail is coming from asynchronous provider or not.

This is needed for the ability to ignore reporting errors that come from async providers.

**There're 2 options in my mind:**
1- providerDidFail can receive `AsyncError` not the error itself, but we'll get duplicated `StackTrace`.
2- providerDidFail can receive a new boolean argument `isAsyncError`. I prefer this one. 

I'd like to open a PR but I need to know your take first.

**Comment by rrousselGit** [comment]
You have access to the provider causing the error. So you could do something like:

```dart
if (provider is ProviderListenable<AsyncValue>)
```

**Comment by rrousselGit** [comment]
Either of your proposals would be breaking and would be unlikely to land because of it. The value is not that big compared to the approach given above

**Comment by AhmedLSayed9** [comment]
I agree as there's already a workaround, Thanks!
