### ISSUE TITLE
Autodispose reset provider state

### ISSUE THREAD

**Issue by agufagit** [rrousselGit/riverpod#3151]
**Describe the bug**
Autodispose reset provider state

**To Reproduce**

minimal reproduce repository [https://github.com/agufagit/riverpod_test](https://github.com/agufagit/riverpod_test)

1. `dart pub get`
2. `dart run build_runner build`
3. `dart run`

result is 

```
beforeloading true
loading true
after action false
afterloading false
```

**Expected behavior**
```
beforeloading false
loading true
after action true
afterloading false
```

**Comment by rrousselGit** [comment]
That has nothing to do with autoDispose. You issue is that your `build` has the `async` keyword.

So it completes asynchronously, which happens during your `await`.
And when it completes, that stops the loading state (because that's what async builds do).

**Comment by rrousselGit** [comment]
If you do:

```dart
  @override
  FutureOr<void> build(int? msgLocalId) {}
```

(without `async` keyword), there's no issue
