### ISSUE TITLE
whenData() should preserve the value of AsyncLoading()

### ISSUE THREAD

**Issue by knaeckeKami** [rrousselGit/riverpod#3159]
**Is your feature request related to a problem? Please describe.**

Consider this gist:
https://dartpad.dev/?id=ba69a9c1066bed38ea72ec8dd185f44d

This example consists of:

- a FutureProvider `userProvider` that loads user data
- an intermediary provider `firstNameProvider` that uses .selectAsync to extract the first name 
- a final provider `greetingProvider` that watches the intermediary provider and returns a greeting for the user

When the `userProvider` is invalidated, the UserProvider becomes an `AsyncData(<old value>, isLoading:true)` 
and finally switches to `AsyncData(<new value>)`.
The `firstNameProvider` however becomes a AsyncLoading<String>(value: <old value>) for one frame when the `userProvider` updates, since `.selectAsync` returns a future which is only resolved on the next tick of the event loop.
And the greeting provider, which uses .whenData() on `firstNameProvider`, will be `AsyncLoading()` without any value.

See this print of the values of these providers in the given sample:

```
AsyncData<({String firstName, String id, String lastName})>(value: (firstName: Abigail 902, id: 902, lastName: Miller)) 
AsyncLoading<String>(value: Abigail 538)
AsyncLoading<String>()
```

The first line is the `userProvider` with the new, updated value.
The second line is the `firstnameProvider` which still has the old name as value, because the future returned by .selectAsync still has to resolve, indicated by the `AsyncLoading` type.
The third line however does not have any value at all and is just an AsyncLoadin(), because it calls `.whenData` on an `AsyncLoading()` which does not preserve the value.

This causes a one-frame loading state on the widget that reads the greeting provider.

**Describe the solution you'd like**

I would propose a change to `.whenData((data) => mapper(data))` to transform an `AsyncLoading(value)` to an `AsyncLoading(mapper(value))` instead of an `AsyncLoading()` without value.

**Comment by knaeckeKami** [comment]
Would you be open to an additional method on AsyncValue or parameters similar to `skipLoadingOnRefresh` or `skipLoadingOnReload`? 

We can make or own `whenData` as extension methods on AsyncValue, but extensions are not as powerful;

`AsyncData` does not have a public constructor that allows setting the `isLoading` field, and `AsyncLoading` does not have a public constructor that allows setting any fields.

I would like to have a method that just maps any present value on the AsyncValue and keeps the rest as is, I don't think this is possible with the current public API.

**Comment by rrousselGit** [comment]
> AsyncData does not have a public constructor that allows setting the isLoading field, and AsyncLoading does not have a public constructor that allows setting any fields.

Use copyWithPrevious for that purpose.

For now, I am unsatisfied with "whenData". I don't like it ,and don't like extending it more or adding variants.
I'd rather find a solution to the root of the problem and remove whenData entirely

**Comment by knaeckeKami** [comment]
Understood.

Actually, I might just avoid `.selectAsync()` as the additional asynchronicity caused by  `Future` returned by it is the source of my problem. 

Have you though about a synchronous counterpart with similar semantics, which does not return Future but an AsyncValue?

**Comment by rrousselGit** [comment]
> Have you though about a synchronous counterpart to `.selectAsync` with similar semantics, which does not return Future but an AsyncValue?

That's just `select`

**Comment by knaeckeKami** [comment]
The function passed to `.select()` receives an `AsyncValue<T>` though, not an unwrapped `T` like `.selectAsync()`. 

So filtering rebuilds is not straightforward just with `.select`, also due to the possible transitions with `AsyncData(loading: true)` or  `AsyncLoading(<oldValue>)`.

But I cansee  that there's so straightforward solution that fits all use cases here...

**Comment by saibotma** [comment]
@knaeckeKami you can implement this kind of select as an extension function. Nevertheless, I support your point that this should be part of Riverpod.

```dart
extension<T> on ProviderListenable<AsyncValue<T>> {
  ProviderListenable<AsyncValue<Selected>> selectData<Selected>(
    Selected Function(T data) selector,
  ) {
    return this.select((value) => value.whenData(selector));
  }
}
```

**Comment by saibotma** [comment]
Alright, it seems like we have got different use cases then.
`selectData` does indeed avoid rebuilds in [my case](https://dartpad.dev/?id=4199dc6ed8f74ab0cf58b9cf9d43b796).

**Comment by knaeckeKami** [comment]
True, in cases like this it works. In my use case, the provider rebuilds because it is invalidated or its dependencies update.

**Comment by rrousselGit** [comment]
I don't think I'll go with this change. It could be breaking apps silently, which is a no-go for me.

Considering it is easy to add your own extension, I'd suggest doing that.

**Comment by claudius-kienle** [comment]
If anyone is looking for a way to also map the `value` of `AsyncLoading`, following code worked for me:

```dart
  AsyncValue<R> mapData<R>(R Function(T) mapFunction) {
    return when(
        data: (data) => AsyncValue.data(mapFunction(data)),
        error: (e, stackTrace) => AsyncValue.error(e, stackTrace),
        loading: () {
          final data = valueOrNull;
          final AsyncValue<R> dataAsync;
          if (data is T) {
            dataAsync = AsyncData(mapFunction(data));
          } else {
            dataAsync = const AsyncLoading();
          }
          return AsyncValue<R>.loading()
              .copyWithPrevious(dataAsync, isRefresh: false);
        });
  }
```

I do know that this is most probably against the guidelines of riverpod, but I found no other solution to filter the data of an `AsyncValue` without loosing information like `isRefreshing` or `isLoading`.
