### ISSUE TITLE
Undesirable Dispose behavior when combining asynchronous Providers

### ISSUE THREAD

**Issue by szk2s** [rrousselGit/riverpod#3174]
# Overview

Providers are disposed undesirably when combined with another asynchronous provider.

# Details

There is a provider for fetching a stream of stock prices from an API. This provider uses `family` and `autoDispose`.

```dart
final stockPriceStreamProvider = StreamProvider.autoDispose.family((
  ref,
  String symbol,
) {
  final client = ref.watch(clientProvider);
  final stream = client.subscribeStockPrices();

  ref.onDispose(() {
    client.cancelStream();
  });

  return stream;
});
```

When retrieving the stock symbol from another asynchronous provider and passing it to `stockPriceStreamProvider`, the provider gets disposed every time the stock prices update.

```dart
// Simulates another API response
final stockSymbolProvider = FutureProvider.autoDispose((ref) async {
  Future<void>.delayed(const Duration(seconds: 1));
  return "SBUX";
});

// Combining the two providers
final stockInfoProvider = FutureProvider.autoDispose((ref) async {
  final symbol = await ref.watch(stockSymbolProvider.future);
  final price = await ref.watch(stockPriceStreamProvider(symbol).future);
  return "$symbol @ $price";
});
```

The full code is [here](https://github.com/szk2s/riverpod_issue/blob/main/lib/issue_reproduction.dart).

# Workaround

Modifying `stockInfoProvider` as follows appears to avoid this problem, but: 

- It introduces another issue of screen flashing.
- A more readable and elegant solution would be preferable.

```dart
final stockInfoProvider = FutureProvider.autoDispose((ref) async {
  var symbol = ref.watch(stockSymbolProvider).valueOrNull;
  symbol ??= await ref.watch(stockSymbolProvider.future);
  final price = await ref.watch(stockPriceStreamProvider(symbol!).future);
  return "$symbol @ $price";
});
```

The full code is [here](https://github.com/szk2s/riverpod_issue/blob/main/lib/possible_solution.dart)

# To Reproduce

I made a [repository](https://github.com/szk2s/riverpod_issue). Please compare the behaiviors of `simple_example_with_no_issues.dart` and `issue_reporoduction.dart`.

Thanks in advance.

**Comment by AhmedLSayed9** [comment]
That's expected. Check https://github.com/rrousselGit/riverpod/issues/1253

A better workaround:
```dart
final stockInfoProvider = FutureProvider.autoDispose((ref) async {
  final symbolFuture = ref.watch(stockSymbolProvider.future);
  final priceFuture = ref.watch(stockPriceStreamProvider(symbol).future);
  final symbol = await symbolFuture;
  final price = await priceFuture;
  return "$symbol @ $price";
});
```

**Comment by szk2s** [comment]
Thanks for your responsiveness! It's been so helpful.
However the UI is still flashing even with your suggested workaround.
Though it might be better to file a new issue, this flash is not seen before combining the providers. 
What are your thoughts on this?

**Comment by AhmedLSayed9** [comment]
Sorry my workaround above still needs `symbol`, so your workaround is the one to go.

For the flashing issue, the provider goes for loading state for a moment because `stockPriceStreamProvider` emits a new value which makes `stockInfoProvider` rebuilds (which emits a loading state initially as it's a future call).

You can avoid the loading flash by setting `skipLoadingOnReload` to true at `.when`, this will show the previous data when a provider rebuilds.

If you don't want the widget to rebuild entirely when the stream emit a new value, you can use `ref.listen`:
```dart
final stockInfoProvider = FutureProvider.autoDispose((ref) async {
  final symbol = await ref.watch(stockSymbolProvider.future);
  ref.listen(stockPriceStreamProvider(symbol), (previous, next) {
    next.whenOrNull(
      data: (value) => ref.state = AsyncData("$symbol @ $value"),
      error: (error, stack) => ref.state = AsyncError(error, stack),
    );
  });
  return ref.future; // This keep the provider in loading state as we'll manually emit states inside ref.listen callback.
});
```

**Comment by szk2s** [comment]
Thanks, that solution worked perfectly for my situation. I'm closing this issue since this behavior is expected and not a bug.

For anyone facing similar issues, the disposeDelay implementation mentioned here fits well for such cases: https://github.com/rrousselGit/riverpod/issues/1664#issuecomment-1264608305.
