### ISSUE TITLE
Can I use the generic type <T>?

### ISSUE THREAD

**Issue by Patrick386** [rrousselGit/riverpod#3176]
To support various data types and use the class flexibly, I need to use the <T> generic.

Ex>
```
@riverpod
class TestController<T> extends _$TestController {
  @override
  FutureOr<List<T>> build(){
    state = const AsyncLoading();
    // fetch data
    // var items = await AsyncValue.guard(_fetchItems);
    // state = items;
    return state.value ?? <T>[];
  }
}
```
<img width="677" alt="Screenshot 2023-12-02 at 9 37 21 PM" src="https://github.com/rrousselGit/riverpod/assets/49754877/149bbf3d-fac7-4f75-bbd2-c524442bd17f">

**Comment by rrousselGit** [comment]
It is available, but this requires using the 3.0 dev release
