### ISSUE TITLE
Generate listener typedef

### ISSUE THREAD

**Issue by vasilich6107** [rrousselGit/riverpod#3183]
**Is your feature request related to a problem? Please describe.**
I'm extracting listeners to separate function for better readability. 

```
ref.listen(
  someProvider,
  someListener(context, param1),
);
```

```
SomeListenerType someListener(
    BuildContext context,
    Param1 param1,
  ) =>
      (_, next) async => next.when();
```

I have to write the `typedef SomeListenerType` for each provider manually which is a little bit time consuming.

**Describe the solution you'd like**
It would be nice to generate `typedef` for listeners.

**Describe alternatives you've considered**
Writing listeners manually.

```
typedef SomeListenerType = void Function(
  AsyncValue<Param1?>? previous,
  AsyncValue<Param1?> next,
);
```

**Additional context**
No other context.

**Comment by rrousselGit** [comment]
I'd prefer avoiding that, as it pollutes the global namespaces and creates opportunity for name conflict.

I'd suggest using a reusable generic typedef:

```dart
typedef ProviderListener<T> = void Function(T? previous, T next);
```

**Comment by rrousselGit** [comment]
You can make your own typedef, so there's not a lot of value here.

I've avoided making public typedefs, because they again take up some useful names.

**Comment by rrousselGit** [comment]
I prefer not polluting the global namespace for now.

Feel free to :+1: the issue. I haven't closed it yet :)

**Comment by rrousselGit** [comment]
For now, I don't plan on adding such a typedef. Lately, I'm trying to do everything I can to remove types from the public API. This would go against it.
