### ISSUE TITLE
Request for Option to Skip AsyncLoading When Setting State from AsyncData to AsyncData in AsyncNotifier

### ISSUE THREAD

**Issue by sheat-git** [rrousselGit/riverpod#3184]
**Is your feature request related to a problem? Please describe.**

Yes, the issue arises when setting the `state` of an `AsyncNotifier` in Riverpod. Currently, when transitioning the state from one `AsyncData` to another `AsyncData`, the implementation unavoidably passes through an `AsyncLoading` state. To illustrate this with an example, consider a scenario involving `AsyncValue<ArticleData>`, where `ArticleData` is defined as:
```dart
abstract class ArticleData {
  String get content;
  bool get isFavorite;
}
```
In this case, a change in a property like `isFavorite` within `AsyncValue<ArticleData>` ideally should be a simple state transition from one `AsyncData` to another `AsyncData`. However, the current behavior introduces an unnecessary intermediate `AsyncLoading` state, even for such minor updates, leading to an unwanted brief loading screen.

**Describe the solution you'd like**

I propose an enhancement to `AsyncNotifier` that allows bypassing the `AsyncLoading` state during transitions between `AsyncData` states, especially in contexts like `AsyncValue<ArticleData>`. This would streamline the user experience by avoiding unnecessary loading phases for minor data updates.

**Comment by rrousselGit** [comment]
> leading to an unwanted brief loading screen.

Riverpod doesn't cause this loading screen. The data is still available even if during that loading transition.
So it is your UI that decided to render this brief loading screen, not Riverpod.

Cf `AsyncValue.isRefreshing/isReloading` or `AsyncValue.when(skipLoadingOnReload/Refresh)`

**Comment by sheat-git** [comment]
I agree that trying to do `skipLoadingOnRelaod/Refreshing` would eliminate the need to go through loading in the UI.
Also, I have no problem using this skip for the project I am currently working on.

However, wouldn't the momentary state of `AsyncLoading` when I want to change from `AsyncData` to `AsyncData` still be unnecessary?
For example, if there is a case where we want to change from `AsyncData` to `AsyncData` while both `skipLoadingOnRelaod/Refreshing` are `false`, there is no solution in the current Riverpod and we are stuck.
I would like to have a way to avoid forcing `AsyncLoading` to go through, since there could be a case where neither refresh nor reload is applicable to updating data.

**Comment by rrousselGit** [comment]
You can directly call `state = AsyncData(...)`

You can even do that at the start of your provider's initialization method to remove the built in loading state.

**Comment by sheat-git** [comment]
Sorry, my mistake, I was talking about something very misguided.
I found a mistake in the code and will close it.
Thank you very much for your kindness!
