### ISSUE TITLE
Add `provider_name_prefix` as well

### ISSUE THREAD

**Issue by ciriousjoker** [rrousselGit/riverpod#3189]
**Is your feature request related to a problem? Please describe.**
Providers are suffixed by default. We'd prefer to use a prefix instead:
`someDataProvider` -> `provSomeData`

This makes it so the provider is still uppercase and by writing "prov", intellisense will automatically only list providers. Essentially it just allows filtering search results to just the providers immediately as opposed to filtering based on the usecase and then looking for which of the results has "Provider" at the end which might even be cut off depending on font size.

**Describe the solution you'd like**
Add a new option: `provider_name_prefix` (similar to `provider_name_suffix`). Ideally both can be used simultaneously.

**Describe alternatives you've considered**
Use the suffix and be slightly annoyed.

**Additional context**
Definitely low prio but hopefully also low enough effort to still be worth implementing.

Would PRs be welcome in this regard?

**Comment by rrousselGit** [comment]
Sure, PR welcomed
