### ISSUE TITLE
Stream Deprecation Alternative For Use Case

### ISSUE THREAD

**Issue by mcmah309** [rrousselGit/riverpod#3197]
StreamProviders `stream` field is deprecated and planned to be removed in 3.0.0. We currently have something like this. What is the alternative for combining stream providers?
```
final realtimeObeliskDocumentProvider = StreamProvider.autoDispose<ObeliskDocument>((ref) {
  ObeliskDocument obeliskDocument = ref.watch(obeliskDocumentProvider);
  DocumentInfo originalInfo = obeliskDocument.info;
  if (originalInfo.collectionPath == null || originalInfo.id == null) {
    Logging.e("Document should always have an path and id for: $obeliskDocument");
    return Stream.value(obeliskDocument);
  }
  final String collectionPath = originalInfo.collectionPath!;
  final String docId = originalInfo.id!;
  return ref.watch(realtimeDocumentInfoProvider((collectionPath, docId)).stream).map((info) {
    if (info != null) {
      obeliskDocument.info = info;
    }
    return obeliskDocument;
  });
});

final realtimeDocumentInfoProvider = StreamProvider.autoDispose.family<DocumentInfo?, (String, String)>((ref, path) {
  return FirebaseFirestore.instance.collection(path.$1).doc(path.$2).snapshots().asyncMap((snapshot) async {
    DocumentInfo? info = await snapshot.toFirestoreEntity(DocumentInfo.fromJson);
    if (info == null) {
      Logging.e("Was unable to get document info for collection ${path.$1} with id ${path.$2}");
    }
    return info;
  });
});
```

**Describe the solution you'd like**
A solution that is ergonomic without `stream` or removing the deprecation on `stream`.

**Describe alternatives you've considered**
`listen` doesn't seem like the best solution for this use case. Switching the first provider to `Future` and using `.future` instead of `.stream` will cause the screen to go to the loading widget callback. Adding `skipLoadingOnReload: true` to the `.when` statement in the widget fixes this, but it causes all user interactions on screen to disappear immediately. With the original `.stream` user interactions such as selections do not disappear until the new widget is ready, which is desired.

**Comment by rrousselGit** [comment]
> dding skipLoadingOnReload: true to the .when statement in the widget fixes this, but it causes all user interactions on screen to disappear immediately.

What does that mean exactly? It isn't clear to me what this is referring to. I see nothing that would be cleared with the code given when using `.future` here

**Comment by SoftMemes** [comment]
I ran into the same (or similar) issue and was going to post essentially this question!

In my case, I have a StreamProvider that I want to observe all changes on in another provider, and take some action when certain types of events occur on the stream (such as playing audio).

I need to observe _all_ events here, not just the latest when the provider is re-built, so `.whenData` does not work for this case. This works now with a watch on `.stream` and a regular `.listen`.

Why is this considered bad and what is the recommended way of doing this without relying on .steam?

**Comment by timcreatedit** [comment]
> In my case, I have a StreamProvider that I want to observe all changes on in another provider, and take some action when certain types of events occur on the stream (such as playing audio).

This sounds like a prime usecase for `ref.listen(yourStreamProvider, ...)`. Have you tried that and if so, why doesn't it work?

**Comment by rrousselGit** [comment]
> I need to observe all events here, not just the latest when the provider is re-built, so .whenData does not work for this case. This works now with a watch on .stream and a regular .listen.

Then instead of `Stream<Event>`, in your StreamProvider emit a `Stream<List<Event>>`.   
If you want to keep using the previously emitted value, you need to store them somewhere.



`.stream` is removed because it introduced too many hard-to-catch bugs.
You could easily end-up in a situation where opening a screen, closing it, then reentering would break your page – because the previously emitted values are no-longer readily available.

**Comment by SoftMemes** [comment]
> > In my case, I have a StreamProvider that I want to observe all changes on in another provider, and take some action when certain types of events occur on the stream (such as playing audio).
> 
> This sounds like a prime usecase for `ref.listen(yourStreamProvider, ...)`. Have you tried that and if so, why doesn't it work?

Ah, yes this does look like the right way! There are still cases where using the .stream directly is more convenient, e.g. to create a provider from another stream provider with some filtering / mapping applied. Is the go-to approach here to combine ref.listen with a local StreamController for these use cases?

**Comment by SoftMemes** [comment]
> > I need to observe all events here, not just the latest when the provider is re-built, so .whenData does not work for this case. This works now with a watch on .stream and a regular .listen.
> 
> Then instead of `Stream<Event>`, in your StreamProvider emit a `Stream<List<Event>>`. If you want to keep using the previously emitted value, you need to store them somewhere.
> 
> `.stream` is removed because it introduced too many hard-to-catch bugs. You could easily end-up in a situation where opening a screen, closing it, then reentering would break your page – because the previously emitted values are no-longer readily available.

Apologies, I didn't mean that I had to be able to access historical values, only that I will need to be notified on every event on the stream, but it sounds like .listen() is the right tool for this.

**Comment by rrousselGit** [comment]
>  There are still cases where using the .stream directly is more convenient, e.g. to create a provider from another stream provider with some filtering / mapping applied

This is the very reason why .stream is removed:
It looks like we can use it for that, but it actually doesn't work.

If your provider that filters/maps the stream is initialized too late, chances are it'll be in a perpetual loading state

Normal ref.listen/ref.watch don't have this issue as they can obtain the current value at any time

**Comment by rrousselGit** [comment]
Closing as this was answered
