### ISSUE TITLE
Document how to test Notifiers

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/riverpod#3199]
With `StateNotifier`, testing was pretty easy - I would create an instance (including with some 'seeded' state for testing), do some stuff with it, grab its `stream`, and validate the events using the standard tool like https://pub.dev/documentation/test/latest/test/emitsDone.html and so on.

I have recently migrated to `Notifier`, not without effort, and sadly now my tests are broken as I cannot get hold of the stream. I read https://riverpod.dev/docs/essentials/testing and it is very vague about how to actually test stuff, e.g. it doesn't show how to validate multiple state changes. I think I need to do `container.listen(myProvider)` and collect the states, and compare them afterwards (EDIT: The page actually does mention this approach, sorry for this). Are there any other options?

For comparison:

With `StateNotifier`:
1. Create an instance of the notifier.
2. Invoke methods.
3. Verify the state using `.stream` and standard tools for `Stream` verifications.

With `Notifier`:
1. Create an instance of the notifier. If you want to seed the notifier, things get interesting as the state is created using `build` - I need to add code to build to use my seeded values in tests, or create a 'standard' instance.
2. Create a `ProviderContainer` and pass an override of the provider for this notifier to use the seeded one. Remember to dispose (by hand or automatically).
3. Create a list to collect states.
4. `container.listen(myProvider, callbackAddingStatesToList)`.
5. Invoke methods.
6. Verify the list of states.

I don't want to sound like a grandpa, but IMHO 'it used to be better'. It has all become much more complex, feels like a step backwards. Notice how the list of steps to perform is now twice as long. Are there any plans on making that more streamlined, like a helper that does all of this (I did write one for my project, and possibly more people wrote theirs as well). I'm not sure what you think of the Bloc package, but Felix also provides `bloc_test` which makes it very straightforward to test Blocs. Or have I simply missed it?

Also, before, it was possible to test the notifier alone, without the container and overrides and providers - I could focus on the logic of the things that has the logic. Now I always need the container.

**Comment by rrousselGit** [comment]
With regards to using .stream and stream test matchers, I've never recommended using those.
IMO they cause tests to be brittle because those matchers are not precise enough.

The way I do it is use Mockito or something similar, and use its `verify`/`verifyInOrder`. That's also what the documentation suggests.
Combined with the `createContainer` utility I share in the same docs.

So you end-up with:

```dart
test('', () async {
  final container = createContainer();
  final listener = ListenerMock<MyState>();
  
  container.listen(provider, listener.call);

  container.read(provider.notifier).method();

  verify(listener(any(), value));
});
```


`ListenerMock` depends on your mock package, but for mockito it is:

```dart
class ListenableMock<T> extends Mock {
  void call(T? value, T next);
}
```


You could even share the first few lines between tests if you wanted to. I don't like the idea of using `setup`/`tearDown` to share mocks & stuff, but you could.

**Comment by rrousselGit** [comment]
Ultimately whatever approach you use, you can create utilities to make it more reusable for your case.

For example, nothing prevents you from making an util that uses a `ProviderContainer` + `ref.listen` and create a Stream out of it for testing purposes.

**Comment by wujek-srujek** [comment]
Thanks.
I have never had issues with the test stream matchers, to be honest, but I do acknowledge code that does wild things with streams - mine never does - could expose issues.

I did something similar (an example for one notifier, my helper is a bit more complex as it is 'generic'):
```dart
    final notifier = MyNotifier(optionalSeedValue);

    final container = ProviderContainer(
      overrides: [
        myNotifierProvider.overrideWith(() => notifier),
      ],
    );
    addTearDown(container.dispose);

    final states = <MyState>[];
    container.listen(
      myNotifierProvider,
      (previous, next) => states.add(next),
    );

    notifier
      ..doStuff()
      ..doMoreStuff();

    expect(
      states,
      expectedStates,
    );
```

But that's the point - how many people will write something like this? Is it even correct? I don't know, e.g. I'm not getting the notifier form the container, I'm using the instance that I created directly.

I believe creating a package with such helpers would help a lot - there would be one way to write tests. Again, `bloc_test` is a very nice example. Or at least document it more, because right now the docs kind of mention some of this stuff, omit some other relevant parts. Ideally there would be more code, like a full example. Your snippets from this thread are helpful and I believe they are not included in the docs.

**Comment by wujek-srujek** [comment]
So the question is: will there ever be a package? I guess this issue could be copied as feature request.

Please close this if you believe the docs are good enough, and there will never be a package with test helpers.

**Comment by rrousselGit** [comment]
There won't be a separate package.
 But the main package may receive more utilities as time goes.

It's more a matter of what utility we'd want.

One thing for certain is that notifiers will have a custom "override" that enables overriding their "build" directly instead of the whole object.

I'll also likely offer a unique constructor on ProviderContainer that works only in tests and autoDispose the container.

**Comment by rrousselGit** [comment]
Although à syntax like bloc_test is achievable, I won't do it personally.
IMO the reliance on stream matchers and defining variables out of the test promotes bad practices.

If there are specific painpoints or if you have unique suggestions though, I'm happy to look into it

**Comment by wujek-srujek** [comment]
Well, `bloc_test` doesn't rely on the stream marchers you don't like (last time I checked, it's been a while).

The helpers you mention make sense, can't wait to get them. In the meantime, I still need to migrate to code generation ;)

**Comment by MiniSuperDev** [comment]
> There won't be a separate package. But the main package may receive more utilities as time goes.
> 
> It's more a matter of what utility we'd want.
> 
> One thing for certain is that notifiers will have a custom "override" that enables overriding their "build" directly instead of the whole object.
> 
> I'll also likely offer a unique constructor on ProviderContainer that works only in tests and autoDispose the container.

Hi, is there any progress of common utilities for tests?
I have custom utilities or use [riverpod_test](https://pub.dev/packages/riverpod_test), but ever is better to use official utilities :).
