### ISSUE TITLE
Code generation assumes Notifiers have a public unnamed no-parameter constructor

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/riverpod#3202]
**Describe the bug**
Code generation expects Notifiers to have a public unnamed no-parameter constructor as a call to it is included in the generated code.
I don't want to have a public constructor as I don't even want to make it possible to instantiate them outside of the library they are defined in. I often do it like this:
```dart
@riverpod
class ExampleNotifier extends _$ExampleNotifier {
    ExampleNotifier._();
    // ...
}
```
The code generates fine but the app doesn't compile as Riverpod generator generates this:
```dart
final exampleNotifierProvider =
    NotifierProvider<ExampleNotifier, ExampleState>.internal(
  ExampleNotifier.new,
  ...
```

**Expected behavior**
The generator is more flexible with constructors and doesn't force me to write code the way I don't to.

**Comment by rrousselGit** [comment]
Not a bug. That's part of the protocol.

At best, the generator should throw a custom error. But an error is expected.

**Comment by wujek-srujek** [comment]
Not really clear to me what 'protocol' and why this is necessary. Everything works just fine when I edit the generated code myself (just for the sake of testing). Or is it impossible to make it more flexible?
I any case, the library is very opinionated, that's fine, but it also kind of forces me to write code in a specific way, that's pretty invasive.

**Comment by rrousselGit** [comment]
The generator currently expects an empty default constructor.

Sounds like you want something else. Rather than a bug report, you should make a feature request and explain why you want such a flexibility.
At the moment, there's nothing wrong going on.

**Comment by wujek-srujek** [comment]
Well, the generator did generate invalid code that didn't compile, and it neither warned about it, nor failed, it just blindly generated broken code. I think this is a bug, I'll create another ticket.
The documentation doesn't mention explicitly that a public constructor is a requirement, either (if it does, I'm sorry, I must have missed it).

**Comment by rrousselGit** [comment]
I've already made an issue about improving the error handling. But this is still part of the specs.
