### ISSUE TITLE
Update `@Riverpod(dependencies)` dartdoc to explain what "dependencies" is

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/riverpod#3205]
I have just migrated my Notifiers to code generation, and it seems that the app works just the same when I specify dependencies, or not. The documentation at https://riverpod.dev/docs/concepts/about_code_generation doesn't mention this property at all. Please document what it is for, what will happen when a Notifier has dependencies and we forget one (I guess there is a lint for it?), what happens when we specify something that is not really a dependency.

**Comment by rrousselGit** [comment]
There's a decent description here: https://pub.dev/documentation/riverpod_annotation/latest/riverpod_annotation/ProviderFamily/dependencies.html

There are also some lint explanations:
- https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_lint#scoped_providers_should_specify_dependencies-generator-only
- https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_lint#provider_dependencies-riverpod_generator-only


And an old doc about scoping (which needs to be updated to support codegen): https://riverpod.dev/docs/concepts/scopes


It isn't the responsibility of "about codegen" to explain `@Riverpod(depencencies)`. It only introduces codegen, and cannot realistically talk about everything.

**Comment by rrousselGit** [comment]
The dartdoc in the annotation should be updated to match https://pub.dev/documentation/riverpod_annotation/latest/riverpod_annotation/ProviderFamily/dependencies.html

Repurposing this issue to do that.

**Comment by wujek-srujek** [comment]
Thanks for the links, I will read all of them.

Agreed, the generation can't talk about everything, but it can at least link to pages that explain what the @Riverpod parameters mean. How am I supposed to know that I should go to a document about 'families' to learn about dependencies? It could also explain it in dartdoc, which it doesn't in the latest version (not sure about main).

You will already know that, but the learning curve of Riverpod is very high; not because it is hard, it's because the docs are all over. I don't even know what to read because it is either 'under construction', or I get recommended to look at some samples, then in other issues I learn that some samples are outdated and don't comply with best practices, FAQ and DO/DON'T are also apparently not up to date. This makes it very hard.

**Comment by rrousselGit** [comment]
You're looking specifically at a field documentation. You shouldn't even go on riverpod.dev to begin with. Your IDE documentation is here for that purpose.

I've already updated the annotation's dartdoc to have the same amount of information than the non-codegen variant.

<img width="886" alt="Screenshot 2023-12-10 at 18 48 37" src="https://github.com/rrousselGit/riverpod/assets/20165741/1aa3a191-9ac3-4f52-8093-5ade9b231306">

**Comment by wujek-srujek** [comment]
Yes, I've just seen the PR. Thanks.
