### ISSUE TITLE
Riverpod generates code that doesn't compile when Notifier has no public constructor that can be called without arguments

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/riverpod#3207]
Code generation expects Notifiers to have a public unnamed constructor that can be called without any arguments, as a call to it is included in the generated code. If this is not the case, the generated code doesn't compile. For example:

```dart
@riverpod
class ExampleNotifier extends _$ExampleNotifier {
    ExampleNotifier._();
    // ...
}
```

The code generates fine but the app doesn't compile as Riverpod generator generates this:

```dart
final exampleNotifierProvider =
    NotifierProvider<ExampleNotifier, ExampleState>.internal(
  ExampleNotifier.new,
  ...
```

**Expected behavior**
The generator aborts generation as the notifier doesn't satisfy its requirements (about the constructor).
OR
The generator is more flexible and allows specifying the constructor, or is able to deduct it itself (might actually be impossible if there are more named constructors - how would the generator know? So we are back at letting us specify the one to use).

**Comment by rrousselGit** [comment]
Thanks for the issue, but there's already an issue about it :)

**Comment by rrousselGit** [comment]
For what it's worth, fixed in https://github.com/rrousselGit/riverpod/pull/3208

**Comment by wujek-srujek** [comment]
Thank you, this will be very useful.
