### ISSUE TITLE
Add a non-initializing listener for multi-source aggregation

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#3215]
**Is your feature request related to a problem? Please describe.**
I spewed out a bunch of words in the title there, but basically there are cases where a certain piece of data might be acquired from multiple providers. The issue is, I don't want my aggregating provider to actually initialize these other sources - only update if any of them do, so we have the freshest data no matter where its from (ie, websocket, rest api, whatever)
like:
```dart
@riverpod
Future<List<Todo>> todosFuture(ref); // api call

@riverpod
Stream<List<Todo>> todosStream(ref); // websocket connection?

// exposes the latest state from either source
@riverpod
Future<List<Todo>> todos(ref) {
  void listener(_, next) => ref.state = next;
  // problem, we dont want to actually initialize either, as making 10 api calls is fine, but opening 10 websockets is decidedly less so.
  ref.listen(todosFutureProvider, listener);
  ref.listen(todosStreamProvider, listener);
  return future;
}
```
The reason this is useful is because while we may call the api endpoint at least once every time, the stream might have provided newer data.
And we dont want to always have the stream active (perhaps on a specific page only) but we *do* want future uses of the data to get the most up-to-date one, weather we invalidated the future at some point, or went back to the stream for a moment.

If the stream's page is never accessed, the stream provider should never initialize

The problem is, there's no way to do this without forcing those providers alive or using unpleasant indirection

**Describe the solution you'd like**
Perhaps a `subscribe` flag? I'm not sure. it would need to be a sort of "weak" listener that does nothing if the provider isnt alive, subscribes when the provider is watched/listened/read elsewhere, and does not prevent disposal.

It would only be possible with `listen` as a callback can simply be not called.

i can imagine that calling ProviderSubscription.read() would act like a regular ref.read if the provider is not alive

perhaps a `maybeListen` or `weakListen` (`weaklyListen`?) if we wanted a dedicated method? or a flag in listen() (like `fireImmediately`) otherwise.

`listenSelf` already acts this way, so perhaps something like it but external and resubscribes when it's initialized again?

**Describe alternatives you've considered**
It may be possible to do something with `ref.exists`, but as it doesnt subscribe to the existence of a provider, you'd need to poll. and even then, once we start listening, we lose the ability to unsubscribe, as i do not believe we have access to the listener count.

It may be possible to bootleg such a thing - perhaps by storing callbacks in an intermediary provider that the source providers add to `listenSelf` - but It's not great.

I've worked around it by introducing the indirection of a StreamController that remains alive, and the actual stream emits to it only when its alive

```dart
@riverpod
StreamController<List<Todo>> _todosStreamController(ref) => StreamController<List<Todo>>();

// in the page we want the stream to be active, we can put a ref.listen for this provider to activate it
@riverpod
Stream<List<Todo>> todosStreamActivator(ref) {
  final controller = ref.watch(_todosStreamControllerProvider);
  ref.listenSelf((_, next) {
     if (next is AsyncData) controller.add(next.value);
     if (next is AsyncError) controller.addError(next.error, next.stackTrace);
  });
  return getTodosStream();
} 
// or
@riverpod
void todosStreamActivator(ref) {
  final stream = getTodosStream();
  ref.onDispose(stream.close);
  ref.watch(_todosStreamControllerProvider).addAll(stream);
} 
// indirected stream. watching this is safe and does nothing.
@riverpod
Stream<List<Todo>> _todosStream(ref) => ref.watch(_todosStreamControllerProvider).stream;

@riverpod
Future<List<Todo>> _todosFuture(ref) => getTodos();

// aggregate results
@riverpod
Future<List<Todo>> todos(ref) {
  void listener(_, next) => ref.state = next;
  // the stream isnt initializing anything, as we're watching a StreamController.stream
  ref.listen(_todosStreamProvider, listener);
  // we do initialize the future, but thats fine because having it be called the once is okay, but isnt perfect.
  // we could do the same indirection with a Completer, but it rapidly approaches unmaintainability
  // ref.listen(_todosFutureProvider, listener);
  // return future;
  return ref.watch(_todosFutureProvider.future);
}
```

**Comment by rrousselGit** [comment]
Dupp of https://github.com/rrousselGit/riverpod/issues/2398

**Comment by rrousselGit** [comment]
For what it's worth, this is part of Riverpod 3.0

I'll do that `ref.listen` will not invoke "build" of providers.

**Comment by TekExplorer** [comment]
ah, that issue isnt titled clearly

I assume you mean it will be an option on listen?
