### ISSUE TITLE
页面销毁后立刻重新进入页面，可能继承ChangeNotifier的provider还没销毁

### ISSUE THREAD

**Issue by lzxyh0227** [rrousselGit/riverpod#3219]
**Describe the bug**
页面销毁后立刻重新进入页面，可能继承ChangeNotifier的provider还没销毁，导致这个provider的一些状态不能正常获取

flutter 版本：^3.7.12
dart版本：^2.19.6
flutter_riverpod：^1.0.1

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by rrousselGit** [comment]
Hello!

I don't speak this language. Please open a new issue in English
