### ISSUE TITLE
⚡️ Enhance Riverpod with SWR (Stale-While-Revalidate) Support for Improved Offline Data Handling

### ISSUE THREAD

**Issue by simplenotezy** [rrousselGit/riverpod#3227]
Current implementations in Async Riverpod lack a straightforward and reusable approach to apply the [SWR (Stale-While-Revalidate)](https://datatracker.ietf.org/doc/html/rfc5861) strategy. This limitation affects the efficiency of serving non-frequently-changing content in our application, particularly under poor network conditions. By integrating SWR, we can instantly deliver cached content during recurring user sessions, significantly enhancing the user experience.

> The name “SWR” is derived from stale-while-revalidate, a HTTP cache invalidation strategy popularized by [HTTP RFC 5861](https://tools.ietf.org/html/rfc5861). SWR is a strategy to first return the data from cache (stale), then send the fetch request (revalidate), and finally come with the up-to-date data.

## Background

SWR is a cache invalidation strategy that optimizes data fetching by initially serving stale data from the cache, followed by a revalidation request to update with the latest information. This approach is particularly useful for applications needing to display data quickly, even when offline or under poor network conditions. It has been successfully implemented in [various web frameworks](https://swr.vercel.app/) and has a growing popularity in the developer community.

## Proposal
I propose an API enhancement for Riverpod that incorporates SWR while maintaining backward compatibility. The key aspect of this enhancement is the addition of new properties without altering existing structures. This can be achieved with the following API design:

```dart
@riverpod
class Test extends _$Test {
  @override
  /// A method to fetch fresh data from sources like APIs.
  /// Called during the first initialization of the provider, returning [AsyncValue<SomeDataFromAPI>]
  /// Overrides the default [AsyncValue<SomeDataFromAPI>] returned by [cached()]
  /// with [AsyncValue.isValidating = false], indicating fresh data.
  Future<SomeDataFromAPI> build() async {
    // fetch from API...
  }

  @override
  /// An optional method to build the provider from cached data (e.g., localStorage).
  /// Called during the first initialization of the provider, returning [AsyncValue<SomeDataFromAPI>]
  /// with [AsyncValue.isValidating = true], indicating data from cache.
  Future<SomeDataFromAPI> cached() async {
    // Fetch data from local storage solutions like SQLite.
  }
}

/// Extension of AsyncValue to support SWR
class AsyncValue {
  /// Indicates if a revalidation request is in progress.
  bool isValidating;

  /// Inherited properties from [AsyncValue<T>], such as data/loading state.
  /// bool isLoading, etc..
}
```
## Additional context
Given Riverpod's widespread use in mobile application development and the popularity of SWR in similar contexts (e.g., React's implementation), integrating this feature could significantly elevate Riverpod's utility.

For indie developers competing with larger organizations, tools like Riverpod that offer powerful functionalities with minimal effort are invaluable. Implementing SWR in Riverpod could be a game-changer, providing a much-needed edge in application optimization and user experience.

**Comment by bizz84** [comment]
I think your proposal is interesting, though further extending the API surface of `AsyncNotifier` and `AsyncValue` may make them harder to use (I'll let @rrousselGit comment on that).

Alternatively, maybe you could use `StreamNotifier` to load from the cache first, then emit a new state when the server responds? I haven't really thought much about the details, so I may be off-mark here.

**Comment by rrousselGit** [comment]
SWR is covered by https://github.com/rrousselGit/riverpod/issues/1040 (even if the description is lacking).

You can have it today with:

```dart
@override
build() {
  ref.onAddListener(() => ref.invalidateSelf());
}
```

Riverpod already preserves the previous state when a new state is loading.  
And AsyncValue already differentiates "isReload" from "isRefresh".

**Comment by simplenotezy** [comment]
I am trying to wrap my head around this, and I've tried doing a few different examples, however it's still not clear to me.

Can you provide a more hands-on example with both fetching as well as where in the process we fetch from and save to cache?

**Comment by rrousselGit** [comment]
Well you're asking for multiple different things in that issue.  
SWR and offline are not necessarily coupled. You can do offline without SWR and SWR without offline.

The code I gave is what's needed for SWR. But you have to deal with offline on your own.

With that snippet, say your home does a network request. Then, when you open a new page, the page will show the previous network request's state. But a new request will be made in the background. And when that new state is available, the UI will update.

**Comment by simplenotezy** [comment]
Sorry if I am not totally clear here, but what I'd like to achieve with Riverpod here is a way to use providers "as they're meant", but also work "offline" or pre-fill them with local cached data, before the network requests succeeds. This is what I suggested could be achieved more natively with the addition of `cached` method.

**Comment by rrousselGit** [comment]
Offline is tracked here https://github.com/rrousselGit/riverpod/issues/1032

**Comment by simplenotezy** [comment]
Aha, now we're talking. That's exactly what I have been looking for.
