### ISSUE TITLE
Allow creating public Providers with private functions/classes

### ISSUE THREAD

**Issue by esenmx** [rrousselGit/riverpod#3237]
**Is your feature request related to a problem? Please describe.**
Right now, providers created as:
```dart
/// public provider
@riverpod
Controller controller(ControllerRef ref) {
  return Controller();
}

/// private provider
@riverpod
Controller _controller(ControllerRef ref) {
  return Controller();
}
```

Since these functions are only used in their generated file, it doesn't make any sense to expose them publicly, and there is always a auto-completion overlap between the provider and the underlying function.

**Describe the solution you'd like**
This way we will have more flexibility:
```dart
/// public provider with public function
@riverpod
Controller controller(ControllerRef ref) {
  return Controller();
}

/// public provider with private function
@riverpod
Controller _controller(ControllerRef ref) {
  return Controller();
}

/// private provider with private function
@riverpod
Controller __controller(ControllerRef ref) {
  return Controller();
}
```

**Describe alternatives you've considered**
`@riverpod` annotation can include a feature for preventing IDE indexing for suggestions(similarly what `@visibleForTesting` or `@internal` do at package level).

**Additional context**
[functional_widget](https://github.com/rrousselGit/functional_widget?tab=readme-ov-file#private-vs-public-widgets) has this feature and it provides that flexibility with no drawback.

**Comment by rrousselGit** [comment]
I don't think it matters too much for Riverpod. Because the function takes in a Ref, and you can't randomly create that.
It's quite difficult to use the function instead of the provider

This would also be breaking.

And once we have metaprogramming, the generator could annotate the function with `@internal` automatically – which should be more than enough.


A possible solution for now is to manually add that `@internal`:

```dart
@internal
@riverpod
void fn(Ref ref) {}
```

**Comment by rrousselGit** [comment]
I have no plan on making such a change for now. It'd be too breaking
