### ISSUE TITLE
Unexpected `avoid_manual_providers_as_generated_provider_dependency` lint 

### ISSUE THREAD

**Issue by urusai88** [rrousselGit/riverpod#3245]
Hi!
I am trying to store family provider in variable(getter) for using it in different places without modify the family name everywhere, but faced a lint
Is it expected behavior?

![image](https://github.com/rrousselGit/riverpod/assets/13536462/c8aa680f-fbed-4b11-ab8d-bd18eaaeeee8)

**Comment by rrousselGit** [comment]
Yes, it is.

You can't do something like `MyProvider get alias => another`
