### ISSUE TITLE
Call provider by its generated 'name

### ISSUE THREAD

**Issue by abnerh69** [rrousselGit/riverpod#3246]
**Is your feature request related to a problem? Please describe.** No.

**Describe the solution you'd like**
A new function to read/write/listend (and other possible calls to providers) using its generated String "name".
Samples:
final myProvider = ref.watchByName("mySpecialProvider")
final myProviderNotifier = ref.readByName("mySpecialProvider").notifier;

**Describe alternatives you've considered**
As ProviderObserver has the feature to look at inside the providers, then, maybe it is possible to dynamically call providers by its generated "name".

**Additional context**
What about PR on it?

**Comment by rrousselGit** [comment]
That is technically not feasible, and goes directly against what Riverpod tries to achieve.

If you want such a thing, I'd suggest that you build a `Map<String, Provider>` yourself:

```dart
final providers = {
  "foo": Provider(..),
  "bar": StreamProvider(...)
};

ref.watch(providers['foo']);
```
