### ISSUE TITLE
Contradictory comments for `AsyncValue.value`

### ISSUE THREAD

**Issue by gmkado** [rrousselGit/riverpod#3255]
Looking at the comments for `AsyncValue.value` says both "It will return the previous value during loading/error state" and "This will return null during loading/error states".  These seem contradictory.

https://github.com/rrousselGit/riverpod/blob/11244e40a380147d1823ad6efc61b6cc3ec84d4b/packages/riverpod/lib/src/common.dart#L183C3-L194C57

**Comment by snapsl** [comment]
The comment is very descriptive. `AsyncValue.value` will return the previous value during loading/error state if a previous value exists.
If you do not want to to return the previous value during these states, use `ref.watch(provider).unwrapPrevious().valueOrNull` as stated in the comment.
