### ISSUE TITLE
AsyncLoading and infinite list 

### ISSUE THREAD

**Issue by g-apparence** [rrousselGit/riverpod#3260]
**Is your feature request related to a problem? Please describe.**
I am making an infinite list. 
So I want each time the user gets to the end of the list to load and add new items. 
The entire list should not reload and I want only to show loading animation to the end of the list.

**Describe the solution you'd like**
Today I have to put a "loading" property, or creating a type to my state as AsyncLoading doesn't let me set the value. 
I would like to be able to put a value to AsyncLoading so I can only check the loading state using Riverpod. 

```dart
state = AsyncLoading.loadMore(previous: state);
```

ps: love your work on Riverpod. 🙏🏻

**Comment by rrousselGit** [comment]
Can you be more specific?

AsyncLoading already includes the previous state. You don't need to add it by hand
And I don't see how that's related to infinite lists

**Comment by g-apparence** [comment]
Oh sorry for this. 
I completely skipped that. 

You made this too easy, sorry 🤘
