### ISSUE TITLE
Map-like overview for providers

### ISSUE THREAD

**Issue by joachimbulow** [rrousselGit/riverpod#3264]
**Is your feature request related to a problem? Please describe.**
As a production application grows in complexity, and multiple developers collaborate on a project, maintaining an overview of the various providers can become a quite cumbersome task. 

E.g. watch relationships modifying the lifetime of otherwise autodisposed providers can be hidden in "small" sub-providers, sometimes causing you to have to search through every usage of a provider with grep.

**Describe the solution you'd like**
A map-like overview showing the network of Providers and how they are interconnected, including which types of relationships, e.g. read vs watch.

**Describe alternatives you've considered**
I have no alternatives considered.

**Additional context**
I am aware this may be for an additional package, and not directly inside Riverpod. Posting here as maybe someone from the community would be interested in doing it. I would be interested, however i am not sure about the technical feasibility.

I made a similar project a few years back for Java Spring based microservices, in which we mapped endpoints in services to provide an overview in complex microservice architectures. That looked smth like:

<img width="1881" alt="image" src="https://github.com/rrousselGit/riverpod/assets/43139346/d816e913-0f93-4b84-8be4-91132ab7ecf5">

**Comment by rrousselGit** [comment]
There you go https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_graph :)
