### ISSUE TITLE
Possibly memory leaks when listening `StreamProvider.future` inside `FutureProvider` .

### ISSUE THREAD

**Issue by Kurogoma4D** [rrousselGit/riverpod#3272]
**Describe the bug**
I confirmed that listening StreamProvider with `future` property in FutureProvider may causes memory leaks.

**To Reproduce**

Prepare project with `flutter_riverpod` ver.2.4.9, then run below gist code.
https://gist.github.com/Kurogoma4D/9e73da0988ab35581723c87a6c2c9cd3

Then see devtool memory page, There you will find a `_Listener` object that keeps increasing with each button press.

https://github.com/rrousselGit/riverpod/assets/13596653/6682a255-9298-4d0f-9a4f-d55573119087

Instance creation status at that time:

<img width="1027" alt="instance_trace" src="https://github.com/rrousselGit/riverpod/assets/13596653/ee22539d-b049-4158-b9eb-881d509dc88b">

**Expected behavior**

No memory leaks on that situation.

**Comment by Kurogoma4D** [comment]
Workaround: use `selectAsync` instead.

```dart
final countFuture = FutureProvider.autoDispose((ref) {
  return ref.watch(baseStream.selectAsync((data) => data));
  // return ref.watch(baseStream.future);
});
```

**Comment by rrousselGit** [comment]
Thanks for the report. I'll admit I'm working on a significant refactoring of Riverpod for the 3.0 and would rather work on that than a fix for something that's going to disappear anyway.

If you want to look into this, I'd love it. Otherwise this may have to wait a bit

**Comment by Kurogoma4D** [comment]
Thanks for confirming.
I'd like to take a look at it when I get some time, but it looks like the work-around method is fine for production code, so I'll probably stay with it for a while :)

**Comment by rrousselGit** [comment]
Thanks again for the detailed reproduction!

This has been fixed by fixing the `selectAsync` bug. Some ProviderSubscriptions weren't closed, which caused this leak.
