### ISSUE TITLE
Introduction of a `@keepAliveRiverpod` shorthand

### ISSUE THREAD

**Issue by Zfinix** [rrousselGit/riverpod#3278]
When using Riverpod for state management in Flutter, it is essential to ensure that your code is efficient and easy to read. One way to improve the readability and brevity of your code is to use a shorthand annotation, `@keepAliveRiverpod`, instead of `@Riverpod(keepAlive: true)`.

The `@keepAliveRiverpod` annotation is a concise way to indicate that a provider should remain active even when not being listened to. It is a simple and clear declaration that is easy to understand and write:

```dart
@keepAliveRiverpod
final myProvider = Provider((ref) => MyService());
```

Using `@keepAliveRiverpod` makes the intention of your code immediately clear to anyone who is reading it. It is more intuitive than the `@Riverpod` parameter and can be easily identified. So, by using `@keepAliveRiverpod`, you can improve the readability and brevity of your code.

**Comment by rrousselGit** [comment]
Hello again!

I'll admit I'm skeptical.
- The gain between `@Riverpod(keepAlive: true)` vs `@keepAliveRiverpod` is minimal.
- Folks can define `const keepAliveRiverpod = Riverpod(keepAlive: true)` in their apps. There is no requirement for it to be in Riverpod itself
- keepAlive is not something I want to promote too much. This is more of a workaround until a better solution is found.
  Ideally we should never have to "always keep alive some state". So I'm not sure I'd like pushing more APIs around it

**Comment by Zfinix** [comment]
Okay, I understand that but currently using `@riverpod` automatically marks all providers as auto disposable, which might not be the need for some people, It's just a shorthand to make it easy for those people who want to easily mark one or two providers to be kept alive. Sometimes a provider might not have any listener but you still do not want to throw away a the state because a listener could be added at a future state or screen.

**Comment by rrousselGit** [comment]
> currently using @riverpod automatically marks all providers as auto disposable, which might not be the need for some people

That is intended.
The goal is to have folks always use autoDispose in the long run. 

> Sometimes a provider might not have any listener but you still do not want to throw away a the state because a listener could be added at a future state or screen.

There are various ways to deal with this that do not require keepAlive. I'd prefer discussing what the use-case is and deal with that instead.
For example there are some issues related to "cache time / stale time".

**Comment by Zfinix** [comment]
I see them I guess this issue can be closed
