### ISSUE TITLE
Support to specify exception type on `AsyncValue.guard`

### ISSUE THREAD

**Issue by ggirotto** [rrousselGit/riverpod#3291]
**Is your feature request related to a problem? Please describe.**

We are facing some unexpected situations when using `AsyncValue.guard`. We do not want to guard exceptions that we would like the application to crash, like a null pointer exception. For these exceptions we want that the application crash and the error gets propagated to the upper layers, like our crash tool layer.

**Describe the solution you'd like**
We would like an way to specify what type of exception to guard, like:

```dart
static Future<AsyncValue<T>> guard<T, E extends Object>(Future<T> Function() future) async {
    try {
      return AsyncValue.data(await future());
    } on E catch (err, stack) {
      return AsyncValue.error(err, stack);
    }
  }
```

**Describe alternatives you've considered**
We can't use Dart extensions because we can't define static methods for extensions. What we are considering to do is to create a global function that does the job, something like:

```dart
Future<AsyncValue<T>> exceptionGuard<T, E extends Object>(Future<T> Function() future) async {
  try {
    return AsyncValue.data(await future());
  } on E catch (err, stack) {
    return AsyncValue.error(err, stack);
  }
}
```

and instead of doing `state = await AsyncValue.guard(future);` we do `state = await exceptionGuard(future);`

We also face a similar issue with the `build` method in `AsyncNotifier` classes. The function automatically capture exceptions that happen on its body execution, but what if we want that some of these exceptions is thrown?

Let me know your thoughts about this feature request.

**Comment by rrousselGit** [comment]
That would be breaking, so that specific change specifically is a no-go.

Generally, this is done by having an optional "test" callback:

```dart
AsyncValue.guard(..., (err) => err is T);
```


This is low priority for me. So if you want that, feel free to make a PR.

**Comment by ggirotto** [comment]
Thanks for the suggestion @rrousselGit. It seems that @utamori already created a PR for this, so let's use it to make further discussions.
Following the same issue that we are facing with `guard`, the `build` function from `AsyncNotifier` also has a "built-in" guard on it, which means that errors thrown inside its implementation are also automatically captured. From my understanding this looks like a convenience for the dev to avoid `try {...} catch {...}` boilerplate but it also raises the same problem that we are having with `guard`: what if we want the error to be rethrown? For the `guard` function the callback will probably do the job, but what do you suggest that we could do for the `build`?

**Comment by rrousselGit** [comment]
I don't plan on adding any specific API for this in AsyncNotifier. Because there are more ramifications, such as what happens on uncaught errors when another provider depends on the failing provider.

If you want to customize error catching here, I'd suggest making your own `AsyncNotifier` by subclassing `Notifier<AsyncValue>`

**Comment by ggirotto** [comment]
> Because there are more ramifications, such as what happens on uncaught errors when another provider depends on the failing provider.

I understand your concerns, but isn't it what happens with `StateNotifierProvider`? In my case I recently migrated all the controllers from my codebase from `StateNotifierProvider` to respective `AsyncNotifier` and `Notifier` and noticed this exception handling issue. Previously I had an `init` function in my `StateNotifierProvider` that was responsible for loading all dependencies, something like:

```dart
final controller = StateNotifierProvider.autoDispose<Controller, State>(
  (ref) => Controller(ref.read(depA), ref.read(depB)),
  dependencies: [depA, depB],
  name: 'controller',
);

class Controller extends StateNotifier<State> {
  Controller(this._depA, this._depB) {
    unawaited(_init());
  }

  final DependencyA _depA;
  final DependencyB _depB;

  Future<void> _init() async {
    try {
      // Load dependencies....
      if (mounted) state = <new_state>
    } on BaseException catch (exception) {
      state = <failed_state>
    }
  }
}
```

And now I'm missing the error handling behavior that we had in `_init`, since now all the code from it we moved to the `Notifier.build` method. As you said, it's necessary to handle when another dependent providers fail, but how this was handled by `StateNotifierProvider` when other providers were used on its creation? Ex:

```dart
final controller = StateNotifierProvider.autoDispose<Controller, State>(
  (ref) {
    final anotherProvider = ref.watch(secondController); // This may fail
    return Controller(ref.read(depA), ref.read(depB), anotherProvider.data);
  },
  dependencies: [depA, depB, secondController],
  name: 'controller',
);
```

It feels strange to me that the `Notifier` automatically encapsulate all kinds of issues in a `AsyncError` making that error automatically handled because the controllers are placed in the upper layers of our application, just behind the UI layer. Every error that happens in below layers will not be forwarded to the upper layers, where these can be handled accordingly. Our errors are handled before the application is initialized in the `main` Flutter function

```dart
void main() {
  FlutterError.onError = (details) {
    // Handle error
  }
  ....
}
```

And since all errors will be captured by the Notifiers, they'll never reach this place. Sorry about all the contexts, just wanted to expose our use-case so this discussion can be useful for others in the future. Also would appreciate your thoughts about it.

About your suggestion I'm thinking about doing a middleware Notifier that is capable of capture these exceptions and forward them to the appropriate handling. Would appreciate your input about it as well:

```dart
abstract class MiddlewareAutoDisposeAsyncNotifier<T> extends AutoDisposeAsyncNotifier<T> {
  @override
  FutureOr<T> build() async {
    try {
      final result = await init();
      return result;
    } catch (exception, stack) {
      FlutterError.reportError(FlutterErrorDetails(exception: exception, stack: stack));
      rethrow; // This will follow the same behavior of today, but the error will be handled above
    }
  }

  FutureOr<T> init(); // This will be the "new" build method that should be implemented by the controllers
}
```

This is simpler than writing an entire new implementation for `AsyncNotifier`. It's not our dreams solution but if riverpod doesn't provide a better way of handling these exceptions we'll probably will go with this solution.

**Comment by rrousselGit** [comment]
> I understand your concerns, but isn't it what happens with `StateNotifierProvider`?

Yes, and StateNotifierProvider is deprecated :)

---


Maybe you want a ProviderObserver with its providerDidFail?

**Comment by ggirotto** [comment]
@rrousselGit `ProviderObserver` is exactly what I was looking for, no need to subclass `AsyncNotifier`. Thanks for the insight!
