### ISSUE TITLE
Behavior on production differ from on development

### ISSUE THREAD

**Issue by ThatPham2000** [rrousselGit/riverpod#3298]
**Describe the bug**
Context: I pressed the submit button, and there was an exception.
In the development environment, the exception was shown on the screen (expected behavior).
![image](https://github.com/rrousselGit/riverpod/assets/57900109/dc87208a-4c41-4644-a5ba-6ca573e85ece)
In the production environment, the submit button was loading all the time instead of showing exception.
![image](https://github.com/rrousselGit/riverpod/assets/57900109/f1182f72-2f57-412a-b708-3e8b1cebcbf6)

**To Reproduce**
**Flutter version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.6.1 22G313 darwin-arm64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Code:**
class UpdateSettingDialog extends HookConsumerWidget {
  const UpdateSettingDialog({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = context.l10n;

    final entry = ref.watch(selectedSettingProvider);
    final keyController = useTextEditingController(text: entry.key);
    final valueController = useTextEditingController(text: entry.value);

    final editFunction = useState<Future<void>?>(null);
    final formKey = useMemoized(GlobalKey<FormState>.new, const []);

    return AlertDialog(
      scrollable: true,
      title: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            l10n.setting_title,
            style: Theme.of(context).textTheme.titleLarge,
          ),
          const Divider(),
        ],
      ),
      content: SelectionArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CustomTextField(
              width: 330,
              controller: keyController,
              readOnly: true,
              labelText: l10n.setting,
            ),
            const SizedBox(height: 12),
            Form(
              key: formKey,
              child: NumberField(
                width: 330,
                labelText: l10n.value,
                controller: valueController,
                validator: (value) {
                  if (value.isEmptyOrNull) return l10n.required;
                  if (double.tryParse(value!) == null) {
                    return l10n.number_field_validator;
                  }
                  return null;
                },
              ),
            ),
          ],
        ),
      ),
      actions: [
        FutureBuilder(
          future: editFunction.value,
          builder: (context, snapshot) {
            final isError = snapshot.hasError &&
                snapshot.connectionState != ConnectionState.waiting;
            final isLoading =
                snapshot.connectionState == ConnectionState.waiting;
            return Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                if (isError) ...[
                  Text(snapshot.error.toString()),
                  const SizedBox(width: 8),
                ],
                CustomButton(
                  width: 100,
                  text: l10n.cancel,
                  onPressed: Navigator.of(context).pop,
                ),
                const SizedBox(width: 8),
                Stack(
                  alignment: AlignmentDirectional.center,
                  children: [
                    CustomButton(
                      width: 100,
                      text: l10n.apply,
                      onPressed: isLoading
                          ? null
                          : () {
                              if (formKey.currentState?.validate() ?? false) {
                                final filter = ref.read(settingFilterProvider);
                                final future = ref
                                    .read(
                                      settingRepositoryProvider(filter)
                                          .notifier,
                                    )
                                    .editData(
                                      key: entry.key,
                                      value: num.parse(valueController.text)
                                          .toString(),
                                    )
                                    .then((_) => Navigator.of(context).pop());
                                editFunction.value = future;
                              }
                            },
                    ),
                    if (isLoading) const CircularProgressIndicator(),
                  ],
                ),
              ],
            );
          },
        ),
      ],
    );
  }
}

**Expected behavior**
Behavior is the same for production and development environment.

**Comment by rrousselGit** [comment]
I'll need a minimal reproducible example. I can't run the code given, so it's useless to me.

**Comment by ThatPham2000** [comment]
You can mock with any API. Then checking with FutureBuilder again. Thanks.

**Comment by rrousselGit** [comment]
That's not how issue reporting works :)


I cannot use your code as there are way too many missing elements. You should provide a complete minimal sample.
If not, I'll close this as non-actionable on my end.

**Comment by rrousselGit** [comment]
In the lack of a proper reproducible example, I'll close this
