### ISSUE TITLE
Plz clarify `is no-longer used` in `autoDispose`

### ISSUE THREAD

**Issue by trietbui85** [rrousselGit/riverpod#330]
**Describe what scenario you think is uncovered by the existing examples/articles**
I notice in `autoDispose` documentation:
>To tell Riverpod to destroy the state of a provider when it is no-longer used, simply append .autoDispose to your provider

However, I'm not sure to understand `no-longer used` correctly. Can you update the documentation with some examples?

I notice in [this repo](https://github.com/ttlg/riverpod_todo/blob/master/lib/provider/todo_providers.dart#L37), the author clears data when `dispose()`, is it correct behavior?

**Describe why existing examples/articles do not cover this case**
Documentation is here: https://riverpod.dev/docs/concepts/modifiers/auto_dispose/

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by wujek-srujek** [comment]
I played around with it today and I think I can help: suppose you have page A and page B, and pressing a button on A pushes B. B watches/listens a provider, and then, when you go back, the widget that listened to a provider is gone, so nobody listens to it any more. This is when `autoDispose` will kick in and dispose the provider. Without `autoDispose`, the state, whatever it is, would still be kept even though nobody is interested.

**Comment by rrousselGit** [comment]
"no-longer used" simply means "everything that uses `watch` was removed"

**Comment by ManuLpz4** [comment]
What if I need to provide a `PageController` or a custom `Object` within the widget tree?
Sometimes I use only `context.read()` and it disposes my provider

**Comment by TimWhiting** [comment]
You should only be using `context.read` in callbacks in the widget tree. Elsewhere in the widget tree you should always `watch` providers.

**Comment by ManuLpz4** [comment]
I'm using `context.read` in callbacks in a page of a `PageView` that needs to access to the `PageController` :/

**Comment by TimWhiting** [comment]
But you are watching it where you are using it for the page view?

**Comment by ManuLpz4** [comment]
@TimWhiting my bad, I was reading instead of watching. Sorry :)

**Comment by rrousselGit** [comment]
The new page regarding state destruction explains that Riverpod is tracking listeners.

Instead of "no longer used", it now says "when all listeners are removed", which is much more explicit

https://docs-v2.riverpod.dev/docs/essentials/auto_dispose
