### ISSUE TITLE
Getting "Providers parameters should have a consistent ==" when using Equatable

### ISSUE THREAD

**Issue by arrowxpr** [rrousselGit/riverpod#3302]
**Describe the bug**
I have a class mixin with EquatableMixin which extends a base abstract class. I use that instance in the build method of my notifiers. When reading a notifier and passing any of the relevant classes, the riverpod lint treats my class as if it does not have consistent equality.

Define a class with Equatable
``` 
class UserFromId extends UserFetchBase with EquatableMixin {
  final String userId;

  UserFromId(this.userId);

  @override
  List<Object?> get props => [userId];
}
```

Riverpod notifier
```
@Riverpod(keepAlive: true)
class UserViewNotifier extends _$UserViewNotifier {
  @override
  FutureOr<User> build(UserFetchBase userFetchBase) async {
  }
}
...
```

```
 final user = ref.watch(userViewNotifierProvider(
                UserFromId('userId'), // warning here
       ));
  //warning: Providers parameters should have a consistent ==. Meaning either the values should be cached, or the parameters should override ==

```

**To Reproduce**
As described above.

**Expected behavior**
While my class already uses Equatable to override equality, this behavior should not be expected.

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

**Comment by rrousselGit** [comment]
My guess is that it's a mixin issue. I'll look into it.
