### ISSUE TITLE
Example of GoRouter usage with codegen replacement for ChangeNotifier

### ISSUE THREAD

**Issue by hajajmaor** [rrousselGit/riverpod#3314]
Using GoRouter, using `refreshListenable: ref.watch(userStateProvider),` must be a `Listenable`object.
Using Firebase auth, as a demo, the userStateProvider will look something like this:

```dart
final ChangeNotifierProvider<UserNotifier> userStateProvider =
    ChangeNotifierProvider<UserNotifier>(
  (ChangeNotifierProviderRef<Object?> ref) => UserNotifier(ref),
);

class UserNotifier extends ChangeNotifier {
  Ref ref;
  UserNotifier(this.ref) {
    _init();
  }

  void _init() {
    FirebaseAuth.instance.authStateChanges().listen((User? user) {
      _user = user;
      if (user != null) {
      /// perform something
      } else {
      /// perform something else
      }
      notifyListeners();
    });
  }
```

GoRouter

```dart
import './routes.dart';

part 'router.g.dart';

@Riverpod(keepAlive: true)
GoRouter goRouter(GoRouterRef ref) {
  return GoRouter(
    routes: $appRoutes,
    debugLogDiagnostics: true,
    refreshListenable: ref.watch(userStateProvider),
  );
}


```

With codegen, an `info` is showing:
`Generated providers should only depend on other generated providers. Failing to do so may break rules such as "provider_dependencies".dart(avoid_manual_providers_as_generated_provider_dependency)`

How should the 'userStateProvider' be generated to use with GoRouter's `refreshListenable` field?

**Describe why existing examples/articles do not cover this case**
There is no example of using GoRouter with the use of the `refreshListenable` field with the codegen provider.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
See https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_lint#unsupported_provider_value-riverpod_generator-only
