### ISSUE TITLE
How do you cause a streamProvider returning firebase.instance.authStateChanges()

### ISSUE THREAD

**Issue by MilanLabuss** [rrousselGit/riverpod#3326]
A common use case of streamProvider is for it to return firebase.instance.AuthStateChanges so your UI can dynamically react to authentication state changes, but after chatting with Firebase support I found that a common use case does not trigger this authStatechanges. when a anonymous user converts to a permanent user authStateChanges is not called and therefore the streamProvider won't update and your UI can't tell the difference until you restart your application.

Firebases reply:
"The behavior you're describing is expected because authStateChanges() doesn't distinguish between different sign-in methods; it simply emits a change whenever the authentication state changes. However, there's no built-in method to specifically detect an upgrade from anonymous to permanent user status."

@riverpod
class UserAuth extends _$UserAuth {
  @override
  Stream<User?> build() {
    return FirebaseAuth.instance.authStateChanges();
  }
}

Is there a way to manually trigger this stream to emit this since Firebase does not have a build in function to know if an anonymous user converts to a permanent user, perhaps a way to reload the stream without having to reload the entire UI?

**Comment by rrousselGit** [comment]
Hello! This is not directly related to Riverpod.
For general help request, I'd suggest asking on Discord or StackOverflow.

Issues are for bug reports and feature requests :)
