### ISSUE TITLE
Linter incorrectly detecting manual provider

### ISSUE THREAD

**Issue by chrisdrobison** [rrousselGit/riverpod#3329]
**Describe the bug**
I'm 100% using generated providers. However, with the latest update, the linter is warning for specific providers:

```
Generated providers should only depend on other generated providers. Failing to do so may break rules such as "provider_dependencies".
```

**To Reproduce**

```dart
@Riverpod(keepAlive: true)
class LaunchDarkly extends _$LaunchDarkly {
  @override
  LDClient? build() {
    return null;
  }

  void set(LDClient? client) {
    state = client;
  }
}

@riverpod
class AdministerExamFlag extends _$AdministerExamFlag {
  @override
  bool build() {
    var client = ref.watch(launchDarklyProvider);
    return false;
  }
}
```

It's flagging `var client = ref.watch(launchDarklyProvider);`.  My guess is that the linter isn't correctly detecting @Riverpod() annotations vs @riverpod annotations?

**Expected behavior**
Shouldn't be flagging this.

**Comment by rrousselGit** [comment]
Try pressing `alt` in VScode and hovering a type. Or try opening the generated code.

My guess is that this is the following analyzer bug: https://github.com/dart-lang/sdk/issues/54113

**Comment by chrisdrobison** [comment]
Yeah, looks like doing that helped it go away. Thanks for your response.

**Comment by rrousselGit** [comment]
Hopefully that issue will be fixed when possible
