### ISSUE TITLE
How are disposed Provider's declared as field of a class

### ISSUE THREAD

**Issue by kaminoan-dev** [rrousselGit/riverpod#3349]
**Describe what scenario you think is uncovered by the existing examples/articles**

The standard use case of providers as indicated in the documentation is to declare them as top-level or global variables, which will be used to interact with our corresponding providers. Riverpod will track whether a provider has listeners or not. Then, if the provider has no listeners for a full frame, the state will be destroyed.

However, since they are just objects (or functions) they could also be declared as fields of a class, which in that case it is not completely clear how their internal states is disposed.

**Additional context**

I am migrating a project that was using ReactiveX to Riverpod, which has several "service" classes which have two resposabilities:
* Provide (reactively) some entities
* Manipulate those entities

In order to keep the same behaviour and avoid unexpected side-effects if I would split those two responsibilities into two parameters when passed to widgets (the provided value and the notifier/service) I have migrated as follows,

From:
```dart
class TodoListService {
  final BehaviorSubject<List<Todo>> todosSubject = BehaviorSubject.seeded(const []);

  void addTodo(final Todo todo) {
    todosSubject.add([...todosSubject.value, todo]);
  }
}
```

To:
```dart
class TodoListService extends AutoDisposeNotifier<List<Todo>> {
  late final AutoDisposeNotifierProvider<TodoListService, List<Todo>> todosProvider =
      AutoDisposeNotifierProvider(() => this);

  @override
  List<Todo> build() {
    return [];
  }

  void addTodo(final Todo todo) {
    state = [...state, todo];
  }
}
```

This way I can keep my code as it was where a service instance was passed as an argument to a widget, and within that widget where it was listening to changes in the `BehaviorSubject` now it will just be replaced by a `watch` on the provider field of the service instance.

**Comment by rrousselGit** [comment]
Definitely do not do this. Providers should always be "global" variables. Your code will stop working as Riverpod evolves and macros land in Dart

**Comment by rrousselGit** [comment]
If you want to pass a "service", either make a separate class, or return `ref.watch(provider.notifier)`. That should count as a service.

**Comment by kaminoan-dev** [comment]
What do you mean by "make a separate class"?

I understand that the normal use case is accessing separatly the notifier (the _service_) and the provided value as bellow, but this could lead to having a widget MyWidget which is passes a "service" and "data" which could not be necessarily linked to each other since nothing is preventing this.

```
Widget build(context) {
  final service = ref.read(myprovider.notifier);
  final value = ref.watch(myprovider.notifier);

  return MyWidget(service: service, data: value);
}
```

**Comment by rrousselGit** [comment]
>   final value = ref.watch(myprovider.notifier);

The value isn't this. It's `final value = ref.watch(myprovider);`

Your value is a `List<Todo>`, not a Notifier instance.

**Comment by kaminoan-dev** [comment]
Yes, it was a typo my apologies. I have corrected my comment.

What do you mean by "make a separate class"?

**Comment by kaminoan-dev** [comment]
> > final value = ref.watch(myprovider.notifier);
> 
> The value isn't this. It's `final value = ref.watch(myprovider);`
> 
> Your value is a `List<Todo>`, not a Notifier instance.

Yes, it was a typo my apologies. I have corrected my comment.

What do you mean by "make a separate class"?
