### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by catalunha** [rrousselGit/riverpod#3352]
In my dev community we had a debate these days about memory leaks and the use of Riverpod.

I do not have the necessary knowledge to create this documentation. But I suggest that this topic be an important highlight in the documentation.

Clarifying that if the Riverpod is used well this is not a problem.

And this memory leak would also occur in other state managers. Since it is the state that contains the memory and not the manager.

**Comment by rrousselGit** [comment]
There's already https://riverpod.dev/docs/essentials/auto_dispose

I'm not sure what else to add. If you have any specific recommendation, I'm happy to look into it. But as it is, the request is a bit too broad for me to do anything about it.

**Comment by catalunha** [comment]
Thanks.
I'm on a big, long project.
Trying to approve Riverpod as a State Manager.
But the word "Memory Leak" needs to appear in the documentation. Even if it is the same thing as in the documentation. These are important words.
Success and thank you for Riverpod 3.
We are looking forward to it.
