### ISSUE TITLE
Stutter on pull to refresh (Flutter 3.19.1)

### ISSUE THREAD

**Issue by fritsvt** [rrousselGit/riverpod#3358]
**Describe the bug**
Pull to refresh causes application UI on iOS to stutter.

**To Reproduce**

```
RefreshIndicator(
        onRefresh: () async {
          HapticFeedback.lightImpact();
          await ref.refresh(eventsBetweenProvider(
                  start: dateTimeRange.start,
                  end: dateTimeRange.end,
                  notClockedIn: false)
              .future);
        },
)

```
**Expected behavior**
With previous versions of Flutter it didn't stutter. When I remove the ref.refresh call and replace with a Future.delayed the animation looks fine.

Edit: just downgraded to 3.16.9 and can confirm it was not an issue in this version.

**Comment by rrousselGit** [comment]
Please share a minimal reproducible example. The snippet given isn't enough to reproduce the issue.

**Comment by fritsvt** [comment]
@rrousselGit may I ask why you removed the bug label? As far as I know it is unexpected behaviour from Riverpod right or am I missing something?

**Comment by fritsvt** [comment]
Closing as it appears to be a Flutter issue.
