### ISSUE TITLE
Best practice for checking if a Future or Stream Provider has already a value and, if not, await the value inside another dependent provider

### ISSUE THREAD

**Issue by elkSal** [rrousselGit/riverpod#3359]
Based on some research [(this](https://stackoverflow.com/questions/59213196/what-is-the-purpose-of-futureor) & [this](https://github.com/rrousselGit/riverpod/discussions/2864#discussioncomment-6874481) ) I discovered that async and await will make Dart treat a`FutureOr` function as a Future.

Question:
**How do we synchronously access the data of a Future/Stream Provider from another provider if it has already been cached and, if not, await the provider value?** 

Let's assume that I have a provider A that gets asynchronously some data. I have another provider B that needs provider's A data.
Below code will be run provider B asynchronously even if provider A has already cached data:

```
@riverpod
Future<ModelA> providerA(ProviderARef ref) async{
return await something();
}

@riverpod
FutureOr<ModelB> providerB(ProviderBRef ref) async{
final rawData = await ref.watch(providerAProvider.future);
final mapper = ref.read(mapperProvider);
return mapper(rawData);
}
```

Below code instead will allow provider B to run sync if provider A already has data
```
@riverpod
Future<ModelA> providerA(ProviderARef ref) async{
return await something();
}

@riverpod
FutureOr<ModelB> providerB(ProviderBRef ref){
 final mapper = ref.read(mapperProvider);
 final rawDataAsyncValue = ref.read(providerAProvider);
 final rawDataStream = ref.watch(providerAProvider.future);
 if(rawDataAsyncValue.valueOrNull != null){
  return mapper(rawDataAsyncValue.valueOrNull!);
 } else {
  return rawDataStream.then((rawData) => mapper(rawData));
 }
}
```

I haven't seen any documentation on this topic (only [this](https://stackoverflow.com/questions/76519374/how-to-skip-asyncloading-with-futureprovider-in-riverpod)). Is the above example the recommended approach? What if provider B depended on 3 others providers whose data might be already cached, would it be necessary nesting with all these `providerXStream.then((providerXData) => ...)` in case they are not cached yet?

I saw that with [this enhancement](https://github.com/rrousselGit/riverpod/issues/2797) everything should be easily implemented (I assume), I was curious on how are you handling this at the moment.

**Comment by rrousselGit** [comment]
I'll close this as this should be covered by https://github.com/rrousselGit/riverpod/issues/2797
But TL;DR, at the moment you can read the AsyncValue; and if absent, use the .future

```dart
enum _Status {
  loading, data, error,
}

extension on Ref {
  FutureOr<T> syncWatch<T>(ProviderBase<T> provider) {
    final hasResult  = ref.watch(provider.select((v) => v.hasData || v.hasError));

   if (!hasResult) return ref.watch(provider.future);

  return SynchronousFuture(ref.watch(provider).requireValue);
);
```

**Comment by elkSal** [comment]
thanks a lot @rrousselGit ,the above code is clean and is the solution I was looking for.

I tried to import it (I have flutter_riverpod: ^2.4.10) but it doesn't compile as:
1) `watch(provider.select ` causes: The argument type 'ProviderListenable<bool>' can't be assigned to the parameter type 'AlwaysAliveProviderListenable<dynamic>'
2) v, the result of the select, is of type T and doesn't have the hasData and hasError getters
3) `provider.future` causes: The getter 'future' isn't defined for the type 'ProviderBase<T>'
3) `watch(provider)` causes: The argument type 'ProviderBase<T>' can't be assigned to the parameter type 'AlwaysAliveProviderListenable<dynamic>'

```
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

extension SyncWatch on Ref {
  FutureOr<T> syncWatch<T>(ProviderBase<T> provider) {
    final hasResult = watch(provider.select((v) => v.hasData || v.hasError));

    if (!hasResult) return watch(provider.future);

    return SynchronousFuture(watch(provider).requireValue);
  }
}
```

**Comment by elkSal** [comment]
I created in the end two methods, one for the StreamProvider and one for the FutureProvider as follows:

```
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

extension SyncWatch on Ref {
  FutureOr<T> streamSyncWatch<T>(StreamProvider<T> provider) {
    final hasResult = watch(provider.select((v) => v.hasValue || v.hasError));

    if (!hasResult) return watch(provider.future);

    return SynchronousFuture(watch(provider).requireValue);
  }

  FutureOr<T> futureSyncWatch<T>(FutureProvider<T> provider) {
    final hasResult = watch(provider.select((v) => v.hasValue || v.hasError));

    if (!hasResult) return watch(provider.future);

    return SynchronousFuture(watch(provider).requireValue);
  }
}

```

The question now is: **how to access the FutureOr value inside the syncWatch method?** I saw you raised few concerns to the Dart team in these regards (like [this](https://github.com/dart-lang/language/issues/2033)) but I didn't see any update.
FutureOr doesn't allow a then method like Future and using async or await would turn it into asyncrounous code, defying the whole point of the caching system.

**Comment by elkSal** [comment]
Finally managed to arrange a solid workaround after hours of attempts, I hope it can be helpful.

[hasResult](https://github.com/rrousselGit/riverpod/issues/3359#issuecomment-1960513591) in syncwatch should be read and not watch as otherwise it would rebuild the linked provider when Async Value hasData or hasError changes even though we are already listening to changes as we return watch. Also returning a `SynchronousFuture` doesn't help for this workaround, so we just return the simple `.requireValue.`

```
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

extension SyncWatch on Ref {
  FutureOr<T> streamSyncWatch<T>(StreamProvider<T> provider) {
    final hasResult = read(provider.select((v) => v.hasValue || v.hasError));

    if (!hasResult) return watch(provider.future);

    return watch(provider).requireValue;
  }

  FutureOr<T> futureSyncWatch<T>(FutureProvider<T> provider) {
    final hasResult = read(provider.select((v) => v.hasValue || v.hasError));

    if (!hasResult) return watch(provider.future);

    return watch(provider).requireValue;
  }
}
```

I implemented this extension on FutureOr based on some inputs received [here](https://github.com/dart-lang/language/issues/3625#issuecomment-1961773955) to allow accessing a FutureOr value synchronously whenever possible with this method. 

```
import 'dart:async';

extension Then<T> on FutureOr<T> {
  FutureOr<R> then<R>(
    FutureOr<R> Function(T value) onValue,
  ) {
    if (this is T) {
      return onValue(this as T);
    } else {
      return (() async => onValue(await this))();
    }
  }
}
```

Finally the example code from the question would be:
```
@riverpod
Future<ModelA> providerA(ProviderARef ref) async{
return await something();
}

@riverpod
FutureOr<ModelB> providerB(ProviderBRef ref){
 final mapper = ref.read(mapperProvider);
 final rawDataValue = ref.futureSyncWatch(providerAProvider);
 return rawDataValue.then((rawData)=> mapper(rawData));
}
```
