### ISSUE TITLE
Delay listen(fireImmediately: true) execution until build() complete

### ISSUE THREAD

**Issue by jeiea** [rrousselGit/riverpod#3360]
**Is your feature request related to a problem? Please describe.**

When I run the provided code snippet
```dart
ref.listen(rpcBridgeProvider, (_, __) { print('b'); }, fireImmediately: true);
print('a');
```
It prints 'b' before 'a' and attempting to access the provider's state inside the listener throws an exception.

It seems logical for the listener execution to occur after the build() method completes. Since build() is typically intended to be (relatively) pure, while the listener may involve impure actions, mixing their execution could lead to inconsistencies.

**Describe the solution you'd like**
I propose delaying the execution of the listener until after the build() method completes.

**Describe alternatives you've considered**
Leave it as is. Though I'll be curious about the reason.

**Additional context**

**Comment by rrousselGit** [comment]
That's not quite "immediately" anymore though. There are cases where it matters for the notification to be synchronous.
I'm not sure that's reasonable

**Comment by jeiea** [comment]
If locating the case isn't too difficult, it would be appreciated if you could share it.
