### ISSUE TITLE
Why riverpodGeneratorAsyncNotifierProvider returns FutureOr?

### ISSUE THREAD

**Issue by forsytalnd** [rrousselGit/riverpod#3366]
When i run generator for async provider i get template like this
```dart
@riverpod
class  |  extends _$ {
  @override
  FutureOr<> build() async {
    return ;
  }
}

```
Why build method returns FutureOr but [not Future itself](https://dart.dev/effective-dart/design#types:~:text=of%20void.-,AVOID%20using%20FutureOr%3CT%3E%20as%20a%20return%20type,a%20function%20that%20can%20be%20either%20is%20hard%20to%20use%20correctly.,-good)?

**Comment by rrousselGit** [comment]
Why not? 😛 

I do not manage any template. Sounds like you're using one that uses Future instead of FutureOr, when they also add `async`.

But anyway, Riverpod supports returning FutureOr because it enables skipping a "loading" in cases where no async task was performed.
