### ISSUE TITLE
riverpod_graph outputs empty graph on github action runner

### ISSUE THREAD

**Issue by bakicelebi** [rrousselGit/riverpod#3374]
Running dart run riverpod_graph <path> -f d2 in github actions runner does not output the correct graph.

1. Clone riverpod repository
2. cd to riverpod/packages/riverpod_graph
3. dart run riverpod_graph <path> -f d2

The github workflow yml uses checkout@v4 and setup-dart@v1. The full yml can be found [here](https://github.com/bakicelebi/paintroid-flutter/blob/PAINTROID-669/.github/workflows/main.yml).

Output is:

Analyzing paintroid-flutter ...
Analyzing paintroid-flutter/packages/database ...
Analyzing paintroid-flutter/packages/io_library ...
Analyzing paintroid-flutter/packages/command ...
Analyzing paintroid-flutter/packages/tools ...
Analyzing paintroid-flutter/packages/component_library ...
Analyzing paintroid-flutter/packages/features/workspace_screen ...
Analyzing paintroid-flutter/packages/features/onboarding_screen ...
Analyzing paintroid-flutter/packages/features/landing_page_screen ...
Analyzing paintroid-flutter/packages/l10n ...
Legend: {
  Type: {
    Widget.shape: circle
    Provider: rectangle
  }
  Arrows: {
    "." -> "..": read: {style.stroke-dash: 4}
    "." -> "..": listen
    "." -> "..": watch: {style.stroke-width: 4}
  }
}

Expected output is (output after running locally):

Analyzing paintroid-flutter ...
Analyzing paintroid-flutter/packages/database ...
Analyzing paintroid-flutter/packages/io_library ...
Analyzing paintroid-flutter/packages/command ...
Analyzing paintroid-flutter/packages/tools ...
Analyzing paintroid-flutter/packages/component_library ...
Analyzing paintroid-flutter/packages/features/workspace_screen ...
Analyzing paintroid-flutter/packages/features/onboarding_screen ...
Analyzing paintroid-flutter/packages/features/landing_page_screen ...
Analyzing paintroid-flutter/packages/l10n ...
Legend: {
  Type: {
    Widget.shape: circle
    Provider: rectangle
  }
  Arrows: {
    "." -> "..": read: {style.stroke-dash: 4}
    "." -> "..": listen
    "." -> "..": watch: {style.stroke-width: 4}
  }
}

LoadImageFromPhotoLibrary.provider: "LoadImageFromPhotoLibrary.provider"
LoadImageFromPhotoLibrary.provider.shape: rectangle
IImageService.provider: "IImageService.provider"
IImageService.provider.shape: rectangle
IPermissionService.provider: "IPermissionService.provider"
IPermissionService.provider.shape: rectangle
IPhotoLibraryService.provider: "IPhotoLibraryService.provider"
IPhotoLibraryService.provider.shape: rectangle
LoadImageFromFileManager.provider: "LoadImageFromFileManager.provider"
LoadImageFromFileManager.provider.shape: rectangle
IFileService.provider: "IFileService.provider"
IFileService.provider.shape: rectangle
SaveAsCatrobatImage.provider: "SaveAsCatrobatImage.provider"
SaveAsCatrobatImage.provider.shape: rectangle
SaveAsRasterImage.provider: "SaveAsRasterImage.provider"
SaveAsRasterImage.provider.shape: rectangle
brushToolProvider: "brushToolProvider"
brushToolProvider.shape: rectangle
brushToolProvider.tooltip: "See also [brushTool]."
brushToolStateProvider: "brushToolStateProvider"
brushToolStateProvider.shape: rectangle
brushToolStateProvider.tooltip: "See also [BrushToolState]."
commandManagerProvider: "commandManagerProvider"
commandManagerProvider.shape: rectangle
commandManagerProvider.tooltip: "See also [commandManager]."
commandFactoryProvider: "commandFactoryProvider"
commandFactoryProvider.shape: rectangle
commandFactoryProvider.tooltip: "See also [commandFactory]."
graphicFactoryProvider: "graphicFactoryProvider"
graphicFactoryProvider.shape: rectangle
graphicFactoryProvider.tooltip: "See also [graphicFactory]."
toolBoxStateProvider: "toolBoxStateProvider"
toolBoxStateProvider.shape: rectangle
toolBoxStateProvider.tooltip: "See also [ToolBoxState]."
eraserToolProvider: "eraserToolProvider"
eraserToolProvider.shape: rectangle
eraserToolProvider.tooltip: "See also [eraserTool]."
handToolProvider: "handToolProvider"
handToolProvider.shape: rectangle
handToolProvider.tooltip: "See also [handTool]."
IDeviceService.sizeProvider: "IDeviceService.sizeProvider"
IDeviceService.sizeProvider.shape: rectangle
IDeviceService.provider: "IDeviceService.provider"
IDeviceService.provider.shape: rectangle
RenderImageForExport.provider: "RenderImageForExport.provider"
RenderImageForExport.provider.shape: rectangle
canvasStateProvider: "canvasStateProvider"
canvasStateProvider.shape: rectangle
canvasStateProvider.tooltip: "See also [CanvasState]."
CanvasDirtyState.provider: "CanvasDirtyState.provider"
CanvasDirtyState.provider.shape: rectangle
WorkspaceState.provider: "WorkspaceState.provider"
WorkspaceState.provider.shape: rectangle
toolOptionsVisibilityStateProvider: "toolOptionsVisibilityStateProvider"
toolOptionsVisibilityStateProvider.shape: rectangle
toolOptionsVisibilityStateProvider.tooltip: "See also [ToolOptionsVisibilityState]."
CanvasPainter.shape: circle
BackgroundLayer.shape: circle
PaintingLayer.shape: circle
ExitFullscreenButton.shape: circle
ToolOptions.shape: circle
BottomNavBar.shape: circle

canvasStateProvider -> CanvasPainter: {style.stroke-width: 4}
canvasStateProvider -> BackgroundLayer: {style.stroke-width: 4}
canvasStateProvider -> PaintingLayer: {style.stroke-width: 4}
commandManagerProvider -> PaintingLayer: {style.stroke-width: 4}
CanvasDirtyState.provider -> PaintingLayer: {style.stroke-width: 4}
toolBoxStateProvider -> ExitFullscreenButton: {style.stroke-width: 4}
WorkspaceState.provider -> ExitFullscreenButton: {style.stroke-dash: 4}
toolOptionsVisibilityStateProvider -> ToolOptions: {style.stroke-width: 4}
toolBoxStateProvider -> ToolOptions: {style.stroke-width: 4}
toolBoxStateProvider -> BottomNavBar: {style.stroke-width: 4}
IImageService.provider -> LoadImageFromPhotoLibrary.provider: {style.stroke-width: 4}
IPermissionService.provider -> LoadImageFromPhotoLibrary.provider: {style.stroke-width: 4}
IPhotoLibraryService.provider -> LoadImageFromPhotoLibrary.provider: {style.stroke-width: 4}
IImageService.provider -> LoadImageFromFileManager.provider: {style.stroke-width: 4}
IFileService.provider -> LoadImageFromFileManager.provider: {style.stroke-width: 4}
IPermissionService.provider -> LoadImageFromFileManager.provider: {style.stroke-width: 4}
IFileService.provider -> SaveAsCatrobatImage.provider: {style.stroke-width: 4}
IPermissionService.provider -> SaveAsCatrobatImage.provider: {style.stroke-width: 4}
IImageService.provider -> SaveAsRasterImage.provider: {style.stroke-width: 4}
IPermissionService.provider -> SaveAsRasterImage.provider: {style.stroke-width: 4}
IPhotoLibraryService.provider -> SaveAsRasterImage.provider: {style.stroke-width: 4}
brushToolStateProvider -> brushToolProvider: {style.stroke-width: 4}
commandManagerProvider -> brushToolProvider: {style.stroke-width: 4}
commandFactoryProvider -> brushToolProvider: {style.stroke-width: 4}
graphicFactoryProvider -> brushToolProvider: {style.stroke-width: 4}
graphicFactoryProvider -> brushToolStateProvider: {style.stroke-width: 4}
brushToolProvider -> toolBoxStateProvider: {style.stroke-width: 4}
brushToolStateProvider -> eraserToolProvider: {style.stroke-width: 4}
commandManagerProvider -> eraserToolProvider: {style.stroke-width: 4}
commandFactoryProvider -> eraserToolProvider: {style.stroke-width: 4}
graphicFactoryProvider -> eraserToolProvider: {style.stroke-width: 4}
brushToolStateProvider -> handToolProvider: {style.stroke-width: 4}
commandManagerProvider -> handToolProvider: {style.stroke-width: 4}
commandFactoryProvider -> handToolProvider: {style.stroke-width: 4}
IDeviceService.provider -> IDeviceService.sizeProvider: {style.stroke-width: 4}
graphicFactoryProvider -> RenderImageForExport.provider: {style.stroke-width: 4}
commandManagerProvider -> RenderImageForExport.provider: {style.stroke-width: 4}
IDeviceService.sizeProvider -> canvasStateProvider: {style.stroke-width: 4}
commandManagerProvider -> canvasStateProvider: {style.stroke-width: 4}
graphicFactoryProvider -> canvasStateProvider: {style.stroke-width: 4}
commandManagerProvider -> WorkspaceState.provider: {style.stroke-width: 4}

**Comment by rrousselGit** [comment]
The package isn't released afterall :)
