### ISSUE TITLE
which syntax highlighter was used?

### ISSUE THREAD

**Issue by amills-vibeirl** [rrousselGit/riverpod#3385]
I love this syntax highlighter here:
https://riverpod.dev/docs/introduction/why_riverpod

<img width="856" alt="Screenshot 2024-03-04 at 4 19 37 AM" src="https://github.com/rrousselGit/riverpod/assets/150489986/185c0aa4-24a7-4d0e-98fc-898e95147a31">

which theme was used? ^^ excellent
I am just looking for the name of that style - would love to use it with Jetbrains or VSCode, etc

**Comment by rrousselGit** [comment]
Whatever's the default offered by Docusaurus. I'd suggest looking on your own. I don't know on top of my head what this is
