### ISSUE TITLE
flutter_riverpod: ^2.4.10 error

### ISSUE THREAD

**Issue by yanashenyang** [rrousselGit/riverpod#3396]
error in flutter_riverpod: ^2.4.10

Resolving dependencies...
Because riverpod depends on flutter_riverpod ^2.4.10 which depends on riverpod 2.5.0, riverpod 2.5.0 is required.
So, because riverpod is 1.0.0+1, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on flutter_riverpod: flutter pub add flutter_riverpod:^1.0.0-dev.11
Process finished with exit code 1

**Comment by rrousselGit** [comment]
You need to edit your pubspec.yaml to change your `riverpod` verrsion

**Comment by yanashenyang** [comment]
in pubspec.yaml
flutter_riverpod: ^2.4.10

**Comment by yanashenyang** [comment]
@rrousselGit 

> You need to edit your pubspec.yaml to change your `riverpod` verrsion

it does not work

**Comment by yanashenyang** [comment]
> You need to edit your pubspec.yaml to change your `riverpod` verrsion
how to integrated

**Comment by yanashenyang** [comment]
> You need to edit your pubspec.yaml to change your `riverpod` verrsion

how to integrated

**Comment by joechan-cq** [comment]
I think the reason is that you may create the flutter project or module which was named "riverpod", so yaml can't solve the dependencies correctly.

**Comment by yanashenyang** [comment]
> I think the reason is that you may create the flutter project or module which was named "riverpod", so yaml can't solve the dependencies correctly.

thank you very much
