### ISSUE TITLE
^2.4.10 ERROR ERROR ERROR

### ISSUE THREAD

**Issue by yanashenyang** [rrousselGit/riverpod#3399]
<img width="1487" alt="image" src="https://github.com/rrousselGit/riverpod/assets/18659370/74a26928-5ab5-4e88-9c18-db6707c8a926">

**Comment by rrousselGit** [comment]
Don't make multiple issues for the same thing

**Comment by yanashenyang** [comment]
> Don't make multiple issues for the same thing

how to solve
