### ISSUE TITLE
StreamControllerProvider

### ISSUE THREAD

**Issue by derolf** [rrousselGit/riverpod#340]
Assume we have a TodoList app and we want to access a Todo by its ID using todoProvider = StreamProvider.autoDispose.family(...).

Now, we have “remote updates” that inject updates to a todo from somewhere:

- Deleting the Todo should close the stream
- Updating the Todo should emit the updated Todo through the corresponding todoProvider in case that it exists (someone is listening)

A workaround could be a StateNotifier, but that requires the Todo to be available synchronously. So, if loading a Todo requires async work, we need a StreamController.

**Comment by Nolence** [comment]
Just wanted to add to this. I recently really wanted a type of `StateNotifierProvider` but for a stream as well. I was working on a pagination notifier where I hoped the stream to be the state and the notifier to hold methods that added to the stream sink or whatever.

I found making my own provider was pretty tough so gave up that avenue. In the end I just went with a StateNotifier.

```dart
// The reason I'm using an AsyncSnapshot is to have this notifier not depend on riverpod
// where AsyncValue is defined
class PaginatedQueryNotifier<T> extends StateNotifier<AsyncSnapshot<Iterable<QuerySnapshot<T>>>>
```

However,  I found that I had to listen to the stream at each point and manually map the stream to an AsyncSnapshot that I then set the state with which was kind of weird.

```dart
void _updateSubscription() {
    _subscription?.cancel();
    state = state.inState(ConnectionState.waiting);
    _subscription = _querySnapshotsStream.listen(
      _handleStateChanges,
      onError: (Object error, StackTrace stackTrace) {
        state = AsyncSnapshot.withError(
          ConnectionState.none,
          error,
          stackTrace,
        );
      },
    );
  }
```

It'd be great if there was something like a `StreamControllerProvider` that let you both get the `stream` and the `notifier`.

**Comment by rrousselGit** [comment]
As a comeback to this, I am personally opposed to this because this would decentralise the logic.

The logic that decides how and when to call `controller.add` would be placed within widgets, which will end-up spread all over the application over time.

This is different from `StateNotifier` which promotes adding methods on our `StateNotifier` subclass to implement the logic, centering it in one place.

**Comment by rrousselGit** [comment]
Closing as I don't plan on implementing this
