### ISSUE TITLE
Minor - Notifier Dependency must be `keepAlive:true` if watched by a parent that is `keepAlive:true`

### ISSUE THREAD

**Issue by zacharypuulsedev** [rrousselGit/riverpod#3413]
**Describe the bug**
Watching a dependency with `ref.watch` should work regardless of keepAlive setting on a "parent" provider.

```
Error: The argument type 'AutoDisposeNotifierProviderImpl<ChildNotifier, int>' can't be assigned to the parameter type
'AlwaysAliveProviderListenable<dynamic>'
```

**To Reproduce**
```
@riverpod 
class ChildNotifier extends _$ChildNotifier {
  @override
  int build() {
    return 5;
  }
}

@Riverpod(keepAlive: true)
int parent(ParentRef) {
  // final childVal = ref.read(childNotifierProvider); // Okay
  final childVal = ref.watch(childNotifierProvider); // Error, unless child annotation is changed to `@Riverpod(keepAlive: true)`
  return childVal + 1;
}
```

**Expected behavior**
A parent being set to `keepAlive: true` should not cause it's dependencies to be explicitly set to `keepAlive: true`. Implicitly, any dependencies would be kept alive, but this implementation detail shouldn't be forced down to the child as it breaks composition and re-usability (code shared across projects in particular).

`ref.watch` should also behave the same as `ref.read`, and work in this case.

The expected behavior can be achieved by annotating the offending provider regularly and eagerly initializing the provider at the app root.

```
class _EagerInitialization extends ConsumerWidget {
  const _EagerInitialization({required this.child});
  final Widget child;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Eagerly initialize providers by watching them.
    // By using "watch", the provider will stay alive and not be disposed.
    ref.watch(parentProvider);
    return child;
  }
}
```

**Comment by rrousselGit** [comment]
That is not a bug, this is voluntary

Cf https://riverpod.dev/docs/concepts/modifiers/auto_dispose#the-argument-type-autodisposeprovider-cant-be-assigned-to-the-parameter-type-alwaysaliveproviderbase
