### ISSUE TITLE
Riverpod annotation in large scale applications

### ISSUE THREAD

**Issue by AlexMichels** [rrousselGit/riverpod#3418]
### Discussed in https://github.com/rrousselGit/riverpod/discussions/3417

<div type='discussions-op-text'>

<sup>Originally posted by **AlexMichels** March 12, 2024</sup>
Hello @rrousselGit ,
I really enjoy using Riverpod. Currently, I am using Riverpod in projects with over 100k lines of code and for hundreds of thousands of users. We are using Riverpod annotation, Feature First, and each feature consists of UI -> controller (Notifier) -> service. The Riverpod providers are the glue between our layers. The problem we have on a large scale is that the build runner takes 3-5 minutes to run. That means if I change the branch or work on a provider, it takes 4 minutes until it is done. This costs each engineer about 30 minutes per day.

What is your recommendation? I was thinking maybe to push the generated files so at least we do not need to wait so long each time we change the branch.

Are there better solutions to improve the use of annotation for large projects?

Thanks in advance.</div>

**Comment by rrousselGit** [comment]
> The problem we have on a large scale is that the build runner takes 3-5 minutes to run. That means if I change the branch or work on a provider, it takes 4 minutes until it is done. This costs each engineer about 30 minutes per day.


That's the fault of your app. This is typically a sign that the files of your providers are importing too many things, which essentially re-generate the whole app on change.
The fewer and more specifics the imports are, the faster code-generation will be.


And yes, the best solution is static metaprogramming.
