### ISSUE TITLE
@protected annotation not compatible with linter rule avoid_public_notifier_properties

### ISSUE THREAD

**Issue by WurliMonkhaven** [rrousselGit/riverpod#3419]
**Describe the bug**
If you mark an abstract member of a mixin as `@protected`, then use that mixin on a notifier marked with `@riverpod` and then `@override` the protected member, the linter will complain regarding rule `avoid_public_notifier_properties`.

**To Reproduce**

```dart
mixin FooMixin{
    @protected
    abstract final String fooValue;
}
```

```dart
@riverpod
class FooNotifier extends _$FooNotifier with FooMixin{
    //This line will cause the linter to complain regarding
    //rule: avoid_public_notifier_properties
    @override
    final String fooValue = "foo";
    
    @override
    FutureOr<Foo> build(){
        return Foo();
    }
}
```

**Expected behavior**
For the linter to leave me alone plz i am so tired

**Comment by rrousselGit** [comment]
I thought you overrode `state` at first.

This case is desired. Notifiers shouldn't have public properties outside of `state`

**Comment by WurliMonkhaven** [comment]
Am I misunderstanding `@protected`? I thought the idea was that these properties wouldn't be public.

**Comment by rrousselGit** [comment]
> Edit: Problem understood. @protected doesn't change anything concrete, it just provides data for analysis. The members are still public. Dang.

The point is, your field is **not** protected. You overrode it, and removed the protected status.

`@protected` isn't inherited. You have to place it on overrides too, otherwise the override is no-longer protected.

**Comment by WurliMonkhaven** [comment]
> > Edit: Problem understood. @Protected doesn't change anything concrete, it just provides data for analysis. The members are still public. Dang.
> 
> The point is, your field is **not** protected. You overrode it, and removed the protected status.
> 
> `@protected` isn't inherited. You have to place it on overrides too, otherwise the override is no-longer protected.

I have a very small brain. It's like a peanut in a bucket. Rattling around.
