### ISSUE TITLE
Infinite loop when combining two Future providers in a specific way

### ISSUE THREAD

**Issue by saibotma** [rrousselGit/riverpod#3425]
**Describe the bug**
A Future provider gets created and disposed infinitely when combined with another Future provider, where the first provider gets awaited and the second one not.
It is better to have a look at the example, as this is hard to explain in words.

**To Reproduce**
- Run the example
- Notice that provider2 gets disposed and created infinitely
- Have a look at several in code comments which give insights on how the infinite loop can be avoided

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'infinite_loop_bug.g.dart';

@riverpod
Future<String> provider1(Provider1Ref ref) async {
  print("Running provider1");
  ref.onDispose(() {
    print("Disposing provider1");
  });
  return "test";
}

@riverpod
Future<String> provider2(Provider2Ref ref) async {
  // There is no infinite loop when this provider returns
  // String instead of Future<String>.
  print("Running provider2");
  ref.onDispose(() {
    print("Disposing provider2");
  });
  return "test";
}

@riverpod
Future<String> vm(VmRef ref) async {
  // There is only an infinite loop when the first
  // provider future gets awaited, and the second one not.
  // There is no infinite loop the other way round.
  await ref.watch(provider1Provider.future);
  ref.watch(provider2Provider);
  return "test";
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      child: MaterialApp(
        home: InfiniteLoopWidget(),
      ),
    );
  }
}

class InfiniteLoopWidget extends ConsumerWidget {
  const InfiniteLoopWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // There is no infinite loop when uncommenting the following line.
    // ref.watch(provider2Provider);
    ref.watch(vmProvider);
    return const Placeholder();
  }
}
```

**Expected behavior**
provider2 should not be created and disposed infinitely.

Versions:
- flutter_riverpod: 2.5.1
- Flutter: 3.19.1 
Running on iPhone simulator.

**Comment by rrousselGit** [comment]
This isn't quite a bug, but rather an unfortunate side-effect of the combination of async/await+autoDispose.

There's an issue tracking possible improvements on that area. See https://github.com/rrousselGit/riverpod/issues/1253

So I'm going to close this issue in favour of the other one :)

**Comment by saibotma** [comment]
After reading through #1253, a possible workaround and rule of thumb is to always have `await ref.watch(provider1Provider.future)` after `ref.watch(provider2Provider)`.

```dart
@riverpod
Future<String> vm(VmRef ref) async {
  ref.watch(provider2Provider);
  await ref.watch(provider1Provider.future);
  return "test";
}
```

**Comment by rrousselGit** [comment]
It's also probably better to use `ref.watch(provider.future)` for all dependencies, instead of one using it and another not.

This way they have a similar rebuild pattern
