### ISSUE TITLE
[riverpod_lint] avoid_manual_providers_as_generated_provider_dependency

### ISSUE THREAD

**Issue by SheepYang1993** [rrousselGit/riverpod#3470]
**Describe the bug**
`vipTypeListInfoProvider.notifier`will show lint `avoid_manual_providers_as_generated_provider_dependency`

**To Reproduce**
This is my code
```
import 'package:qlzm_color_flutter/model/response/vip_type_list_response.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../network/api/pay_api.dart';
import '../util/app_util.dart';
import '../util/storage_util.dart';

part 'vip_riverpod.g.dart';

@riverpod
Future<void> refreshVipTypeList(RefreshVipTypeListRef ref) async {
  VipTypeListResponse response = await PayApi.getVipTypeList();
  List<VipTypeListData>? vipTypeList = response.data;
  await StorageUtil().write(StorageUtil.keyVipTypeList, vipTypeList);
  ref.read(vipTypeListInfoProvider.notifier).set(vipTypeList);
}

@Riverpod(keepAlive: true)
class VipTypeListInfo extends _$VipTypeListInfo {
  @override
  List<VipTypeListData>? build() {
    List<VipTypeListData>? vipTypeList = StorageUtil()
        .read<List<VipTypeListData>>(StorageUtil.keyVipTypeList,
            fromJson: (jsonList) {
      if (jsonList is List) {
        return jsonList.map((json) {
          return VipTypeListData.fromJson(json);
        }).toList();
      }
      return <VipTypeListData>[];
    });
    return vipTypeList;
  }

  set(List<VipTypeListData>? vipTypeList) {
    state = vipTypeList;
    AppUtil().saveVipTypeList(vipTypeList);
  }
}
```

**Expected behavior**
I'm not sure if it's a code issue or a Lint error

**Comment by rrousselGit** [comment]
Generally, it's just the IDE that's out of date.
You're most likely facing https://github.com/dart-lang/sdk/issues/54113.

Does the warning disappear if you restart the IDE or open the generated file?

**Comment by SheepYang1993** [comment]
> Generally, it's just the IDE that's out of date. You're most likely facing [dart-lang/sdk#54113](https://github.com/dart-lang/sdk/issues/54113).
> 
> Does the warning disappear if you restart the IDE or open the generated file?

When I added a parameter and `run build_runner build`, Lint disappeared.
```
@riverpod
Future<void> refreshVipTypeList(
  RefreshVipTypeListRef ref, {
  bool showLoading = false,
})
```

My Flutter version is 3.19.3, and AndroidStudio version is Android Studio Flamingo | 2022.2.1 Patch 2.
flutter_riverpod: 2.5.1
riverpod_annotation: 2.3.5
riverpod_generator: 2.4.0
riverpod_lint: 2.3.10

I haven't tried the method of upgrading IDE and Flutter yet, but I will try it out in the future.

**Comment by friend-code-dev** [comment]
Updating IntelliJ + plugins resolved the issue for me, thanks

**Comment by SheepYang1993** [comment]
> Updating IntelliJ + plugins resolved the issue for me, thanks
