### ISSUE TITLE
ref.invalidate() does not make another request to the server

### ISSUE THREAD

**Issue by jasonkang14** [rrousselGit/riverpod#3472]
**Describe the bug**
I am building a web service with Flutter && riverpod.
When `ref.invalidate(PROVIDER)` is called, I cannot see the new GET request to the server in the network tab

**To Reproduce**
```dart
onPressed: () async {
    final todoNotifier = ref.read(todoProvider.notifier);
    await todoNotifier.createTask({
        'title': title,
        'description': description,
    });
    ref.invalidate(todoProvider);
}
```

**Expected behavior**
The `FutureProvider` which gets invalidated does get updated with the update data from the database. however, I cannot see whether a new GET request has been made. Is this a bug? if not could you explain this behavior?

**Comment by rrousselGit** [comment]
You'll have to produce a full example. As it is, I cannot know what's going on.

It could be that your provider isn't listened, so it doesn't rebuild naturally
