### ISSUE TITLE
AsyncValue Issue

### ISSUE THREAD

**Issue by LokiEvilOne** [rrousselGit/riverpod#3481]
When utilizing the balanceProvider, the balance.when() method does not consistently enter the loading state as expected. Instead, it either directly throws an error or fails to update the value properly, resulting in unexpected behavior.

balance.when(
  data: (balance) {
    setState(() {
      userBalance = balance;
    });
    return customText(
      average: widget.average,
      value: "Balance: ${balance.floor()}",
      fontSize: topTextFontSize,
      fontColor: Colors.black,
      fontWeight: topTextFontWeight,
    );
  },
  error: (e, s) {
    return const Text("-");
  },
  loading: () {
    debugPrint("Running");
    return const SizedBox(
      width: 50.0,
      child: LinearProgressIndicator(),
    );
  },
),

**Comment by rrousselGit** [comment]
Without a complete example there's not much I can do.

**Comment by LokiEvilOne** [comment]
![Screenshot 2024-04-08 172508](https://github.com/rrousselGit/riverpod/assets/121927577/a01193cb-cfb7-495b-8a44-6cfed11c6f19)
above attached image , i want to fetch the balance that time loading not working directly comes the value.

**Comment by gdurandrexel** [comment]
>  , i want to fetch the balance that time loading not working directly comes the value.

We would at least need the code of balanceProvider.

**Comment by rrousselGit** [comment]
Closing in the lack of a minimal reproducing example
