### ISSUE TITLE
Provider Read Set State in Other Provider Throws Error

### ISSUE THREAD

**Issue by searchy2** [rrousselGit/riverpod#349]
**Describe the bug**
Setting the state of another provider in a provider throws an error. Unable to set state of provider in a provider.
When `ref.read(homePageCounterProvider).state = 0;` is added to a provider in the below code, the following error is thrown.

> An exception was thrown while building ChangeNotifierProvider<HomePageModel>#00002(name: IntroPageModel).
> 
> Thrown exception:
> Instance of 'Error'
> 
> Stack trace:
> #0      StateNotifier.state= (package:state_notifier/state_notifier.dart:173:7)
> #1      StateController.state= (package:riverpod/src/state_provider.dart:22:31)
> #2      homePageChangeProvider.<anonymous closure> (package:flutter_riverpod_sample/main.dart:14:37)
> #3      ProviderElement._runStateCreate (package:riverpod/src/framework/base_provider.dart:873:46)
> #4      ProviderElement.mount (package:riverpod/src/framework/base_provider.dart:801:7)
> #5      ProviderContainer.readProviderElement.<anonymous closure> (package:riverpod/src/framework/container.dart:308:13)
> #6      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
> #7      ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:287:35)

```dart
final homePageCounterProvider = StateProvider<double>((ref) {
  return 0;
}, name: 'HomePageScrollOffset');

final homePageChangeProvider = ChangeNotifierProvider<HomePageModel>((ref) {
  >>ref.read(homePageCounterProvider).state = 0;<<
  return HomePageModel();
}, name: 'IntroPageModel');
```

**To Reproduce**
<details>
  <summary>Reproducible Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(ProviderScope(child: MyApp()));
}

final homePageCounterProvider = StateProvider<double>((ref) {
  return 0;
}, name: 'HomePageScrollOffset');

final homePageChangeProvider = ChangeNotifierProvider<HomePageModel>((ref) {
  ref.read(homePageCounterProvider).state = 0;
  return HomePageModel();
}, name: 'IntroPageModel');

class HomePageModel extends ChangeNotifier {}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Riverpod Sample',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, watch) {
    final HomePageModel model = watch(homePageChangeProvider);
    return Scaffold(
      appBar: AppBar(
        title: Text('Home Page'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '0',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: null,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>

**Expected behavior**
Set the state of a provider inside a provider without throwing an error.

**Flutter Version**
Flutter (Channel beta, 1.26.0-17.7.pre, on Microsoft Windows [Version 6.1.7601], locale en-US)

**Comment by TimWhiting** [comment]
Try:
```dart
final homePageCounterProvider = StateProvider.family<double, double>((ref, initialValue) {
  return initialValue;
}, name: 'HomePageScrollOffset');

final homePageChangeProvider = ChangeNotifierProvider<HomePageModel>((ref) {
  ref.read(homePageCounterProvider(0));
  return HomePageModel();
}, name: 'IntroPageModel');

```
or this:
```dart
final homePageCounterProvider = StateProvider<double>((ref) {
  return 0;
}, name: 'HomePageScrollOffset');

final homePageChangeProvider = ChangeNotifierProvider<HomePageModel>((ref) {
  Future.delayed(Duration(milliseconds: 10), () => ref.read(homePageCounterProvider).state = 0);
  return HomePageModel();
}, name: 'IntroPageModel');
```

It depends on what you are trying to do, but this error is intentional. I'm not sure that Remi has plans on allowing synchronous changes to a provider within another provider that is being created. My understanding is that if he allowed that it could cause infinite loops potentially depending on how the providers depended on each other.

**Comment by rrousselGit** [comment]
Updating a provider from the "build" of another provider is indeed a bad idea. The initialization of a provider should have no effect on other providers. 

Most of the time that's a sign of logic in the wrong place. Try moving the logic that mutates a provider A into A itself.

For example you could do:


```dart
/// The currently selected product
///
/// Will initialize to the first product in the list of products.
final StateProvider<String> selectedProduct = StateProvider<String>((ref) {
  StreamSubscription sub;
  sub = ref.watch(productList.stream).listen((products) {
    if (products.isNotEmpty) {
      ref.read(selectedProduct).state = products.first.id;
    }
    sub.cancel();
  });

 ref.onDispose(sub.cancel);

  return null;
});

final productList = StreamProvider<List<Product>>(...);
```

**Comment by searchy2** [comment]
Thanks for the explanation. Is there any action item needed for this issue? 
Otherwise, I can close.

**Comment by TimWhiting** [comment]
I'll make sure to include this error in the documentation I working on right now, because I'm sure most people run into this issue at some point.

**Comment by rrousselGit** [comment]
A better error message was added some time ago, therefore I think this can be closed

For reference, the error is currently:

```
Providers are not allowed to modify other providers during their initialization.

The provider ChangeNotifierProvider<HomePageModel> modified StateProvider<double> while building.
```
