### ISSUE TITLE
 Experimentation with macros

### ISSUE THREAD

**Issue by Dispersia** [rrousselGit/riverpod#3492]
**Is your feature request related to a problem? Please describe.**
 Not a problem, but as title stated, I was curious if there has been any experimentation with the new macros library. I saw that you had a tweet debating for v3.0 to try with it or getting it out, and as macros has now been promoted from an internal package to a (slightly less internal) public package, I was just curious if there was any momentum in getting it in its current form supported. If not, I am interested in experimenting with it but didn't want to reinvent the wheel

**Describe the solution you'd like**
 A version of the code generation that uses Macros instead of build_runner

**Comment by Linkadi98** [comment]
Since macros is out now as experimental version, it's time to move from build_runner to macros to test riverpod annotations like @rrousselGit wrote on his riverpod's docs. Can't wait to see when macros will be applied to reduce so many boillerplate codes.

**Comment by rrousselGit** [comment]
There are lots of bugs and missing features with macros still. I'm playing around with them, but it's possibly not realistic to publish a package with it.

**Comment by rrousselGit** [comment]
Macros are lacking too many features to use them to implement Riverpod for now.

I'll try again in a few months. But in the meantime, I'll close this.

**Comment by joachimbulow** [comment]
Any news on this, here a few months later? ⚡

**Comment by nrbnlulu** [comment]
see https://github.com/GregoryConrad/rearch-dart that is akin to riverpod but uses macros

**Comment by rrousselGit** [comment]
As I said, macros are lacking features.

I'd much rather finish Riverpod 3.0 for now. The macro version will be available when it's possible :)

**Comment by gumbarros** [comment]
Any news on this, here a few months later? ⚡
