### ISSUE TITLE
Add WidgetRef documentation

### ISSUE THREAD

**Issue by snapsl** [rrousselGit/riverpod#3502]
**Make riverpod onboarding easier.**

WidgetRef is a core functionality of riverpod. Currently the documentation mention WidgetRef in various places but never introduces it. ([link](https://riverpod.dev/docs/essentials/combining_requests), [link](https://riverpod.dev/docs/from_provider/provider_vs_riverpod#reading-providers-buildcontext))
It should be given its own starting page to showcase its usage.

The documentation should contain:

- what is WidgetRef (the WidgetContext for riverpod)
- accessing the state of a provider
   - ref.watch() /ref.read()
- accessing the notifier of a provider
- listen to changes using .listen()
- maybe other methods (e.g. .exists(), ... )

_If needed, I can contribute to the docs._

**Comment by rrousselGit** [comment]
There's https://riverpod.dev/docs/concepts/reading already

**Comment by snapsl** [comment]
I knew I had missed something.😅
