### ISSUE TITLE
What is the recommended way of watching derived values of state exposed through methods ? There's no mention of this in docs

### ISSUE THREAD

**Issue by nateshmbhat** [rrousselGit/riverpod#3513]
subscribing for derived values or getting derived values from latest state is one of the frequent use cases in state management.
Was looking for this in the docs but coudn't find any information there.

consider below provider
```
@riverpod
class Myint extends _$Myint {
  @override
  int build(){
       return 1;
  }
  increment() { state = state+1; }
  int get squared => state * state ;
}
```

In one of the widgets i want to only watch the state value , but in another widget i only need the derived value ( squared ) . 
so i was thinking of just selecting the method `squared` method like `ref.watch( myIntProvider.select(v=>v.squared))` but since it only allows me to select the state, i can't watch for just derived value. it's fine but still i believe managing derived values can be documented.

**Comment by rrousselGit** [comment]
It is explicitly a bad practice: https://pub.dev/packages/riverpod_lint#avoid_public_notifier_properties

As such, you're not supposed to do it.
