### ISSUE TITLE
Alternatives to AVOID initializing providers in a widget

### ISSUE THREAD

**Issue by MiniSuperDev** [rrousselGit/riverpod#3518]
Respecting this don't in [AVOID initializing providers in a widget](https://riverpod.dev/docs/essentials/do_dont#avoid-initializing-providers-in-a-widget).
```dart
class WidgetState extends State<MyWidget> {
  @override
  void initState() {
    super.initState();
    // Bad: the provider should initialize itself
    ref.read(provider).init();
  }
}
```

I have seen these 2 other ways to initialize a provider apart from [Eager initialization](https://riverpod.dev/docs/essentials/eager_initialization).

I would like clarification if these 2 cases are okay or could lead to possible race conditions and unexpected behavior.

I've used before and seems to work fine, but I would like you to clarify this please.

Thanks.

**Case 1: Initializing with `addPostFrameCallback` in `initState`**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'main.g.dart';

@Riverpod(keepAlive: true)
class TextNotifier extends _$TextNotifier {
  @override
  String build() => 'build';
  void init() async {
    state = 'loading';
    await Future.delayed(Duration(seconds: 2));
    state = 'initiated';
  }
}

void main() {
  runApp(
    ProviderScope(
      child: MaterialApp(home: HomePage()),
    ),
  );
}

class HomePage extends ConsumerStatefulWidget {
  @override
  ConsumerState<HomePage> createState() => _HomePageState();
}

class _HomePageState extends ConsumerState<HomePage> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(textNotifierProvider.notifier).init();
    });
  }

  @override
  Widget build(BuildContext context) {
    final text = ref.watch(textNotifierProvider);
    return Center(child: Text(text));
  }
}


```

**Case 2: Initializing in the main and `UncontrolledProviderScope`**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'main.g.dart';

@Riverpod(keepAlive: true)
class TextNotifier extends _$TextNotifier {
  @override
  String build() => 'build';
  void init() async {
    state = 'loading';
    await Future.delayed(Duration(seconds: 2));
    state = 'initiated';
  }
}

void main() {
  final container = ProviderContainer();
  container.read(textNotifierProvider.notifier).init();
  runApp(
    UncontrolledProviderScope(
      container: container,
      child: MaterialApp(home: HomePage()),
    ),
  );
}

class HomePage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = ref.watch(textNotifierProvider);
    return Center(child: Text(text));
  }
}
```

**Comment by rrousselGit** [comment]
> Case 1: Initializing with addPostFrameCallback in initState


That's still initialising providers in a widget. You just added a delay, which confuses Flutter/Riverpod and therefore silences the possible warning.
You didn't solve the inherent problem of widget initialization, which is that it causes a possible bad state in the UI for a few frames.

> Case 2: Initializing in the main and UncontrolledProviderScope


That's "alright". But the way it is presented in the doc is preferred. Relying on the main like that is a bit hard to test and requires various escape hatches to be able to access the state correctly in the main.
