### ISSUE TITLE
Provider container loses data in widget test

### ISSUE THREAD

**Issue by Colman** [rrousselGit/riverpod#3529]
**Describe the bug**
Provider state is lost during widget test even though it's keep alive

**To Reproduce**
Test code:
```dart
void main() {
  testWidgets('Some test', (WidgetTester tester) async {
    final container = ProviderContainer();
    addTearDown(container.dispose); //This line doesn't change the result

    final subscription = container.listen(
      testProvider,
      (_, __) {},
      fireImmediately: true,
    );
    container.read(testProvider.notifier).updateWith(7);

    print('Inside test');
    print(container.read(testProvider).value);

    await tester.pumpWidget(
      UncontrolledProviderScope(
        container: container,
        child: Bug(),
      ),
    );

    subscription.close();
  });
}
```

TestWidget
```dart
class TestWidget extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(testProvider).value;
    print('Build');
    print(value);
    return Container();
  }
}
```

TestProvider
```dart
@Riverpod(keepAlive: true)
class Test extends _$Test {
  @override
  Future<int> build() async {
    return 5;
  }

  void updateWith(int value) {
    state = AsyncData(value);
  }
}
```

This will print the following:
```
Inside test
7
Build
5
```

**Expected behavior**
Should print:
```
Inside test
7
Build
7
```

How are we supposed to initialize AsyncNotifiers for tests? It's discouraged to mock notifiers according to the docs. I tried it anyway and got errors that I couldn't figure out how to fix. Now I'm trying to set the values of the notifiers before running the tests and Flutter clears them for some reason.

I thought maybe it had something to do with being outside of the pump widget function, so I tried passing a callback to the TestWidget that gets called inside of a postFrameCallback in its initState. In that callback, it would initialize these notifiers for me. This works, but as soon as the widget builds again, the values are cleared.

**Comment by rrousselGit** [comment]
What's the "bug" widget?

**Comment by Colman** [comment]
> What's the "bug" widget?

Sorry I meant TestWidget. I've just updated it.

**Comment by rrousselGit** [comment]
Your `TestNotifier.build` is to blame.

It is marked as async, which makes the initialisation, well, async. So you're effectively setting the state to 7 _before_ it is initialised to 5.
Essentially you're setting the state during `AsyncLoading`.

Remove the `async` and you're good to go.

```dart

@Riverpod(keepAlive: true)
class Test extends _$Test {
  @override
  FutureOr<int> build() {
    return 5;
  }

  void updateWith(int value) {
    state = AsyncData(value);
  }
}
```

**Comment by rrousselGit** [comment]
An alternative is to await for the state to be initialized before modifying it.
You can do:

```dart
    await container.read(testProvider.future);
    container.read(testProvider.notifier).updateWith(7);
```
