### ISSUE TITLE
AutoDisposeNotifierProvider causing state loss

### ISSUE THREAD

**Issue by LeonardoRosaa** [rrousselGit/riverpod#3535]
**Describe the bug**
The AutoDisposeNotifierProvider leads to a state loss when performing an operation that triggers a state change in the notifier and attempts to retrieve the state afterward.

The initial state of **`providerAProvider`** is **`State.initial`**, and the expected behavior is for the **`await ref.read(providerAProvider.notifier).change();`** operation to transition the state to **`State.success`** rather than staying at **`State.initial`**. For instance:

```dart
await ref.read(providerAProvider.notifier).change();

if (kDebugMode) {
    print(ref.read(providerAProvider)); // Expect State.success
} 
```

**To Reproduce**
Run the code in the link below:

https://github.com/LeonardoRosaa/riverpod-state-loss

**Expected behavior**
It's expected that the Riverpod keeps the state while the widget is alive.

**Comment by rrousselGit** [comment]
Isn't that the whole point of autoDispose?
You need to ref.watch a provider to preserve the state

**Comment by LeonardoRosaa** [comment]
I understand - but would preserving the state while the widget is alive be a good approach? There may be cases where the `ref.watch` is unnecessary.
