### ISSUE TITLE
Add a DevTools extension for riverpod

### ISSUE THREAD

**Issue by kenzieschmoll** [rrousselGit/riverpod#3541]
Creating this issue to track the effort of adding a DevTools extension for riverpod, similar to the extension provided for `package:provider`. @adsonpleal originally pushed up [this PR](https://github.com/flutter/devtools/pull/4210) in the DevTools codebase before the DevTools extensions framework was available.

Per @rrousselGit's comment [here](https://github.com/flutter/devtools/pull/4210#issuecomment-1778870008), it sounds like this is already on his radar, but I couldn't find a tracking issue to track this effort, so I created this one.

**Comment by rrousselGit** [comment]
There's a tag for tracking it. https://github.com/rrousselGit/riverpod/issues?q=is%3Aopen+is%3Aissue+label%3Adevtool

It is planned but likely won't be coming before the 3.0 release, because I have some specials plans for it.

**Comment by kenzieschmoll** [comment]
Great, thanks for the link to track!
