### ISSUE TITLE
Broken update

### ISSUE THREAD

**Issue by dbergan** [rrousselGit/riverpod#3543]
build_runner works fine when I set these versions in my pubspec.yaml file:
 riverpod_generator: 2.4.0
 riverpod_analyzer_utils: 0.5.1

It breaks with:
 riverpod_generator: 2.4.1
 riverpod_analyzer_utils: 0.5.2

The static analysis reports at pub.dev explain why:
https://pub.dev/packages/riverpod_generator/score
https://pub.dev/packages/riverpod_analyzer_utils/score

Thanks for all you do. This is a fantastic resource!

**Comment by rrousselGit** [comment]
Only analyzer ^6.5.0 is supported. Looks like I forgot to bump the minimum version number. I'll update it and retract the new released.

**Comment by dbergan** [comment]
Thank you! Fixed in 10 minutes, impressive!
