### ISSUE TITLE
Ref onError callback

### ISSUE THREAD

**Issue by snapsl** [rrousselGit/riverpod#3555]
The idea is to provide a similiar `.onError()` callback that also a future would provide when something went wrong. 
This could enable custom error handling or logging for a single provider.

Exemplary use case for logging:

```dart 
@riverpod
int some(SomeRef ref) {
  ref.onError((error, stackTrace) => log(error));

  return 0;
}
```

**Comment by rrousselGit** [comment]
There's `ref.listenSelf` already.
