### ISSUE TITLE
Multiple invalidation of Providers

### ISSUE THREAD

**Issue by MichaelLucca** [rrousselGit/riverpod#3571]
**Describe the bug**
The bug concerns the invalidation of multiple providers, which leads to incorrect state management and unexpected behaviors in the application. When attempting to invalidate multiple providers, only the last one is invalidated correctly.

**To Reproduce**

1. Create a screen with two Widgets, each depending on a different provider.
2. Call the invalidate method for both providers.
3. Observe that only the last provider, affiliatedRestaurantsProvider, is triggered for invalidation.

Here is an example:
![image](https://github.com/rrousselGit/riverpod/assets/89570547/3273de0d-ea72-4d48-9fce-af52faa76cf0)

**Expected behavior**
All the providers must be invalidated and rebuilded.

**Comment by myxzlpltk** [comment]
Can you show us how you defined your riverpod?

**Comment by rrousselGit** [comment]
A complete example is necessary to reproduce this.   
As it is, I am capable of invalidating multiple providers at once. So there's likely something more to what you're saying here.

**Comment by rrousselGit** [comment]
Closing in the lack of a minimal reproducing example
