### ISSUE TITLE
Can't copy code snippet from main landing page in website

### ISSUE THREAD

**Issue by warioddly** [rrousselGit/riverpod#3578]
![RiverpodCopyIssue](https://github.com/rrousselGit/riverpod/assets/53710487/ad851e83-e08d-4abe-81eb-096b120b2efd)

Chrome:
Version 125.0.6422.78, (64x)

**Comment by rrousselGit** [comment]
Interesting. Thanks for the report!

**Comment by warioddly** [comment]
I found the reason, the reason is in the z-index. Since the selector ".snippet__title_bar" has a z-index of 10, and the selector ".ButtonGroup__atx" there is no z-index at all and therefore hover was triggered only for content and when I tried to copy it, it could not because hover was triggered for ".snippet__title_bar". I will fix it and open the pull request soon🙌
