### ISSUE TITLE
Infinitely call child's `useEffect` when parent and child both `extends HookConsumerWidget`

### ISSUE THREAD

**Issue by toknT** [rrousselGit/riverpod#3581]
I am using scollController in a child component , build a list watch in provider like this.

```dart
  final scrollController = ScrollController();
  @override
  Widget build(BuildContext context, WidgetRef ref) {
     useEffect(() {
      scrollController.addListener(fireLoadMore);
      initData();
      return () {
        scrollController.removeListener(fireLoadMore);
        scrollController.dispose();
      };
    }, [scrollController]);
   return ListView.builder()//...
  }
```

If I put this child in a parent `extends HookConsumerWidget` the `initData()` is infinitely called. But if parent is normal `StatefulWidget` it no happen.

**Comment by rrousselGit** [comment]
Whenever your widget rebuilds, a new ScrollController is created. And since your effect is using `[scrollController]`, then the effect will recompute whenevr the scrollController changes. So whenever the widget rebuilds.

You should create that scrollController using a hook instead. See `useScrollController`.

**Comment by toknT** [comment]
> Whenever your widget rebuilds, a new ScrollController is created. And since your effect is using `[scrollController]`, then the effect will recompute whenevr the scrollController changes. So whenever the widget rebuilds.
> 
> You should create that scrollController using a hook instead. See `useScrollController`.

Sorry , he already answred it int https://stackoverflow.com/questions/63832051/safe-usage-for-usescrollcontroller-flutter-hooks
,lol. And it's my misstake , should use the `ScrollController` not `useScrollController` .
