### ISSUE TITLE
Would separating asyncValue into its own package be useful?

### ISSUE THREAD

**Issue by Silfalion** [rrousselGit/riverpod#3583]
**Is your feature request related to a problem? Please describe.**
Not precisely an issue, but if AsyncValue is a standalone package it could be used without needing riverpod. Riverpod dependencies are very few so it clashing with other packages seems a bad reason to bring forward for this. But in the rare cases where it does and for decoupling it further, it seems it would be useful.

If one really doesn't want to import riverpod they could just copy paste the class but in that case they'd miss on changes and improvements made to it in the future. There wouldn't be as many as for say riverpod of course, so it's just a what-if scenario.

**Describe the solution you'd like**
Just a new package on this repo for AsyncValue.

**Describe alternatives you've considered**
Importing riverpod to use it.

**Additional context**

**Comment by rrousselGit** [comment]
I have no plan to do so, as it is closely related to Riverpod.

Riverpod is a pure Dart package. You can easily depend on it anyway.
