### ISSUE TITLE
Provider delegates onCancel and onDispose aren't invoked after invalidation when there are no remaining listeners

### ISSUE THREAD

**Issue by masterwok** [rrousselGit/riverpod#3596]
**Describe the bug**

The `onDipose` and `onCancel` delegates aren't being invoked after `ref.invalidate` is invoked at any point on an auto dispose provider even after the provider removes all subscribers.

I noticed #2729 and wonder if this could be related. We're using riverpod `2.5.1` in our project.

**To Reproduce**

In the following recording I have `allTransactionsProvider` on the dashboard screen. On user logout the dashboard screen is popped and the following ref delegates are invoked as expected:

1. onRemoveListener
2. onCancel
3. onDispose 

However, if `ref.invalidate(allTransactionsProvider)` is invoked while the provider still has listeners, then the following is observered:

1. onDispose
2. onResume

When the user logs out of the application the `onRemoveListener` delegate is invoked as expected. However, the `onCancel` and `onDispose` delegates aren't invoked and the provider is never disposed and remains in memory.

**Expected behavior**

If a disposable provider is invalidated and at any point all subscribers are removed, then the `onCancel` and `onDipose` delegates should be invoked and the provider removed from memory.

**Comment by rrousselGit** [comment]
It's a bit difficult to understand videos.
Please share a minimal reproducible example. That's be much simpler for me.

**Comment by masterwok** [comment]
Thanks, working on that now.

**Comment by masterwok** [comment]
@rrousselGit I pushed up a basic sample project [here](https://github.com/masterwok/riverpodbugdebug/blob/main/lib/main.dart). Luckily, I was **not** able to reproduce the issue in this sample project. All of the delegates are invoked as expected so we can close this issue. Sorry about that. I greatly appriciate you responding quickly.

I'm really not sure why the project containing the issue would exhibit the behavior where `onCancel` and `onDispose` aren't invoked. The provider is disposable and shouldn't have any subscribers upon user logout. I'll do some more digging. Thanks again.
