### ISSUE TITLE
how to use NotifierProvider.family, always  wrong

### ISSUE THREAD

**Issue by qiuweilu** [rrousselGit/riverpod#3603]
**Describe the bug**
how to use NotifierProvider.family, always  wrong.
The official document is not clear enough. If there is any outdated use, please discard it. After reading the official document, all six providers may be discarded.
![微信图片_20240609153604](https://github.com/rrousselGit/riverpod/assets/58357633/22bd4ccf-34a4-47af-b69f-f403841a5ff7)

'''
final storeProvider = NotifierProvider.family<StoreProvider, List<UserStoreResp>, ShareModel>((ref, model) {
  return StoreProvider(model);
});

///StoreProvider
class StoreProvider extends Notifier<List<UserStoreResp>> {

  final ProviderModel model;

  StoreProvider(this.model);

  @override
  List<UserStoreResp> build() {
    return state;
  }
}
'''

**Comment by qiuweilu** [comment]
and try this model and can't success， please give me a full demo
final provider = NotifierProvider.family(MyNotifier.new);

class MyNotifier extends FamilyNotifier<Value, Param>

**Comment by qiuweilu** [comment]
Can someone write a separate example document for everyone to learn and use? If there are outdated interfaces, please mark and clean them up

**Comment by qiuweilu** [comment]
Can someone write a separate example document for everyone to learn and use? If there are outdated interfaces, please mark and clean them up. I asked GPT and GMini, but none of them could write correctly.

This model and can't success too， please give me a full demo.
final provider = NotifierProvider.family(MyNotifier.new);
class MyNotifier extends FamilyNotifier<Value, Param>

**Comment by charlescyt** [comment]
The family parameter should be defined in the `build` method.

Here's a few things that you may find it useful

- no constructor should be declared in `Notifier`
- use auto dispose with family
- consider using riverpod with code gen

```dart
class StoreNotifier extends AutoDisposeFamilyNotifier<Store, String> {
  @override
  Store build(String arg) {
    return Store(name: arg);
  }
}

final storeProvider = NotifierProvider.family.autoDispose<StoreNotifier, Store, String>(StoreNotifier.new);
```

**Comment by qiuweilu** [comment]
![1](https://github.com/rrousselGit/riverpod/assets/58357633/bc9661c0-44c6-482d-ae26-e373faef020c)
![2](https://github.com/rrousselGit/riverpod/assets/58357633/af3ef388-053e-457a-aa36-86929ac6b67f)
@charlescyt    thank you, but still prompting an error.

**Comment by qiuweilu** [comment]
@charlescyt  thank you very much.
