### ISSUE TITLE
FamilyAsyncNotifying non-stop loop calling issue

### ISSUE THREAD

**Issue by qiuweilu** [rrousselGit/riverpod#3606]
![1](https://github.com/rrousselGit/riverpod/assets/58357633/f45ce339-fac5-4ff5-8529-d6fc947f21b7)
![2](https://github.com/rrousselGit/riverpod/assets/58357633/9ce6885e-1943-401e-95b5-461cf8f68c07)
![3](https://github.com/rrousselGit/riverpod/assets/58357633/d90405ae-5861-4059-b563-640ee985b451)
![4](https://github.com/rrousselGit/riverpod/assets/58357633/007777b8-032e-47da-97b3-b27f100ccb8b)
![5](https://github.com/rrousselGit/riverpod/assets/58357633/a6b91e40-610b-43a9-b1ad-c4f5dca8ab3a)

**Describe the bug**
The backend has returned data, familyAsyncNotifying non-stop loop calling issue

**To Reproduce**

**Expected behavior**
The page cannot load data and is constantly in a loop call.

**Comment by rrousselGit** [comment]
See https://riverpod.dev/docs/concepts/modifiers/family#parameter-restrictions

Your `ProviderModel` should override == if you wish to use your provider like you did.
