### ISSUE TITLE
Migrate old StateProvider to riverpod generator

### ISSUE THREAD

**Issue by Add00w** [rrousselGit/riverpod#3610]
I have the following provider 

 `final completeProfileImageProvider = StateProvider.autoDispose<File?>((ref) {
  return null;
});
` 

and update its value like

 `ref.read(completeProfileImageProvider.notifier).state = file;` 

now I get warning 

> Generated providers should only depend on other generated providers. Failing to do so may break rules such as "provider_dependencies".

To solve this I tried to use @riverpod generator but I couldn't update the value
I know I think I can use class based generator approach but I have more providers like this which I dont want to convert to clases what is  the solution here?

**Comment by rrousselGit** [comment]
The solution _is_ to use a class.
I am considering a slightly simpler syntax for this case. But at the moment, you'll have to write a class.

There are already issues for improving the StateProvider syntax, and docs about its migration.
So I'll close this :)
