### ISSUE TITLE
ref.listen being triggered twice from screen and detail screen

### ISSUE THREAD

**Issue by LScodeblack** [rrousselGit/riverpod#3612]
I have a auth controller listener inside a build method which is listening to errors and showing a snack bar.

Screen 1 enters phone number (build method is listening to auth controller and shows error if necessary)

Screen 2 which is detail view, enters code received and verifies it (build method is listening to auth controller and shows error if necessary also).

if error occurs on screen 2 the listener call back is being called twice, from Screen 1 and Screen 2, resulting in snackbar showing twice. I am checking !isLoading && hasError before showing snack bar.

Whats the correct way around this @rrousselGit 

*also after abit of digging it seems to only be the case in a cosumer statefull widget were the listener is being kept alive after navigating

**Comment by rrousselGit** [comment]
That's logical. All listeners are notified upon change.

It is your responsibility to only listen to the provider once if need to.
