### ISSUE TITLE
Please simplify the Provider APIs

### ISSUE THREAD

**Issue by hugetiny** [rrousselGit/riverpod#3628]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
(Async)Notifier for complex state management(read and methods to change)

(Async)StateNotifier for simple state management（read and change）

StreamNotifier for streams

**Describe alternatives you've considered**
There are too many kinds of Providers and hard to choose for noobs like me.
old APIs is ok to keep and mark deprecated

**Additional context**

**Comment by rrousselGit** [comment]
Use codegen. See https://riverpod.dev/docs/concepts/about_code_generation
