### ISSUE TITLE
Add stateOrNull to generated providers

### ISSUE THREAD

**Issue by gabrielmcreynolds** [rrousselGit/riverpod#3641]
**Is your feature request related to a problem? Please describe.**
I have a generated provider in that needs to access `stateOrNull` from my ref as accessing `ref.state` is throwing "Tried to read the state of an uninitialized provider".

It looks like that was added in [this PR](https://github.com/rrousselGit/riverpod/pull/2862) for Notifiers, but not generated providers as my ref object has no `stateOrNull` property.

**Describe the solution you'd like**
Add `stateOrNull` to generated providers.

Example:
```dart
@riverpod
AsyncValue<Position> locationChangedService(
  LocationChangedServiceRef ref,
  num distanceThresholdMeters,
) {
  final locationAsync = ref.watch(locationServiceProvider);

  return locationAsync.when(
    data: (currentPosition) {
      // Store the last emitted position using stateOrNull
      final lastPosition = ref.stateOrNull;
     // ... process that value and return a new value
    },
    loading: () => const AsyncLoading(),
    error: (error, stackTrace) => AsyncError(error, stackTrace),
  );
}
```

**Describe alternatives you've considered**
Right now I'm considering trying to wrap my `ref.state` in a try/catch to catch this error and return a dummy value at least for the first render.

## Edit:
It looks like calling `ref.state` in this context always returns a StateError, not just on the first build

**Comment by rrousselGit** [comment]
You can refactor functions to classes. Then you should have access to `this.stateOrNull`

**Comment by gabrielmcreynolds** [comment]
> You can refactor functions to classes. Then you should have access to `this.stateOrNull`

Thanks for the quick reply and workaround. Would it be possible to add this functionality into the generated provider?

**Comment by rrousselGit** [comment]
Classes _are_ generated providers.
If you're asking about having it on Ref itself, maybe. It's low priority, but I'm not against it.

**Comment by gabrielmcreynolds** [comment]
Sorry for mis-calling it but yeah the idea is to have it on the ref itself. I understand if it's low priority but it would be nice, especially as I'm not sure if there is a case where calling 'ref.state' in this situation doesn't throw an error which can be confusing.

**Comment by rrousselGit** [comment]
ref.state is usable freely inside async providers.

Inside sync ones, the state needs to be initialized first. So either:

- after the provider has returned
- after calling ref.state=
