### ISSUE TITLE
ref.listen doesn't work as expected

### ISSUE THREAD

**Issue by diasmalibekov** [rrousselGit/riverpod#3642]
**Describe the bug**
ref.listen doesn't react to observable provider's state changes.
in the build method I listen to two providers and attach callbacks to changes in these providers in the future (callbacks react to changes and reconnect the sip registration when any data changes)
![image](https://github.com/rrousselGit/riverpod/assets/67695163/144d994a-6790-44cc-afdf-9954fa2cfa3b)
and the problem is that these callbacks at some point simply stop responding to state changes
But! if you move ref.listen in the build method of a separate provider that is not watch-ing any other providers, then everything works well, and the callbacks react to every state change
![image](https://github.com/rrousselGit/riverpod/assets/67695163/3280a21e-1a18-43d3-9b6f-d0d7579b1dd9)

**To Reproduce**
the easiest way to reproduce is to listen some provider in build method and make this provider refresh

**Expected behavior**
ref.lilsten reacts to the every state changes.

**Comment by rrousselGit** [comment]
A complete example would be great (and not an image. The source should be copy-pastable).

**Comment by diasmalibekov** [comment]
after a little investigating I found that watching the same provider that you are listening to leads to this error
Here's my code:
```
import 'package:mobile_app/features/authentication/authentication.dart';
import 'package:mobile_app/features/sip/sip.dart';
import 'package:mobile_app/features/sip_settings/sip_settings.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'sip_settings_update_listener_provider.g.dart';

/// Listens sip settings changes and updates dependent providers
@riverpod
class SipSettingsUpdateListener extends _$SipSettingsUpdateListener {
  @override
  Future<void> build() async {
    ref

      /// Reacting to changes in sip settings configuration
      ..listen(
        userSipSettingsHandlerProvider,
        handleSipSettingsUpdating,
      )

      /// Reacting to active ws url changes
      ..listen(wSUrlsHandlerProvider, handleWSUrlUpdating)
      // uncommenting the next line leads to the previous listener stop reacting to the state changes
      //..watch(wSUrlsHandlerProvider);
  }

  /// Handles sip settings updating and restarts the sip service if needed
  Future<void> handleSipSettingsUpdating(
    AsyncValue<UserSipSettings>? prevState,
    AsyncValue<UserSipSettings> newState,
  ) async {
    final prevSettings = prevState?.value;
    final newSettings = newState.value;
    final isSipRegistered = isSipAccountRegistered();

    if (newSettings is! UserSipSettingsSaved) {
      unregisterSipIfRegistered(isRegistered: isSipRegistered);

      await ref
          .read(userSipSettingsHandlerProvider.notifier)
          .updateSipSettings();

      return;
    }

    if (prevSettings is! UserSipSettingsSaved) {
      await ref
          .read(wSUrlsHandlerProvider.notifier)
          .handleNewWSUrls(newSettings);

      return;
    }

    if (prevSettings.sip.sipLogin != newSettings.sip.sipLogin ||
        prevSettings.sip.sipPassword != newSettings.sip.sipPassword ||
        prevSettings.sip.sipHost != newSettings.sip.sipHost) {
      unregisterSipIfRegistered(isRegistered: isSipRegistered);
      ref.invalidate(sipAccountRepositoryProvider);
    }

    final prevWSUrls = Set<String>.from(prevSettings.sip.webrtcUrls);
    final newWSUrls = Set<String>.from(newSettings.sip.webrtcUrls);
    final isWSUrlsListChanged = prevWSUrls.length != newWSUrls.length ||
        !newWSUrls.containsAll(prevWSUrls);

    if (isWSUrlsListChanged) {
      await ref
          .read(wSUrlsHandlerProvider.notifier)
          .handleNewWSUrls(newSettings);

      return;
    }

    final activeWSUrl = await ref.read(activeWSUrlHandlerProvider.future);

    if (activeWSUrl is ActiveWSUrlSaved) return;

    await ref.read(wSUrlsHandlerProvider.notifier).clearFailedWSUrls();
    await ref
        .read(wSUrlsHandlerProvider.notifier)
        .calculateActiveWSUrl(newSettings);
  }

  /// Handles updating acitve ws url and restarts the sip service if needed
  Future<void> handleWSUrlUpdating(
    AsyncValue<ActiveWSUrl>? prevState,
    AsyncValue<ActiveWSUrl> newState,
  ) async {
    final prevWSUrl = prevState?.value;
    final newWSUrl = newState.value;
    final hasError = newState.hasError;
    final isSipRegistered = isSipAccountRegistered();

    if (hasError && newState.error is ActiveWSUrlsError) {
      unregisterSipIfRegistered(isRegistered: isSipRegistered);
      await ref
          .read(userSipSettingsHandlerProvider.notifier)
          .updateSipSettings();

      return;
    }

    if (prevWSUrl is! ActiveWSUrlSaved || !isSipRegistered) return;

    if (newWSUrl is! ActiveWSUrlSaved || prevWSUrl.wsUrl != newWSUrl.wsUrl) {
      unregisterSipIfRegistered(isRegistered: isSipRegistered);
      ref.invalidate(sipAccountRepositoryProvider);
    }
  }

  /// Checks if a sip account is registered
  bool isSipAccountRegistered() {
    final accountStatus = ref.read(
      sipUaHandlerProvider.select((state) => state.value?.accountState),
    );

    return accountStatus == SipAccountState.registered;
  }

  /// Unregisters the sip if connected
  void unregisterSipIfRegistered({required bool isRegistered}) => isRegistered
      ? ref.read(sipAccountRepositoryProvider.notifier).unregisterSipAccount()
      : null;
}
```

As you can see I use indicating error in provider's state to update settings, and it works perfectly if I don't watch the same provider and line
**_..watch(wSUrlsHandlerProvider);_**
if commented
But if I uncomment this line of code, right after providers state changes to error, callback in ref.listen doesn't react to state changes anymore

**Comment by diasmalibekov** [comment]
so I think to reproduce this error you need to put watching and listening provider-A in provider's-B build method and change provider-A state to the error at some point of time, after that even you change provider-A state it won't fire a callback in ref.listen

**Comment by rrousselGit** [comment]
Any chance you could make a minimal reproduction example? There's too much unknown in what you shared. I need something short and that I can run.

**Comment by snapsl** [comment]
In this way, you can't listen to changes of a provider. Using ref.watch(providerB) in provider A causes a rebuild of A if the state of B changes. This negates ref.listen(providerB) in the build method of provider A.

You need to rethink how to structure this. Also, a provider is a reactive component thus it should provide a state (return type of SipSettingsUpdateListener is void).

This is not an issue.

**Comment by diasmalibekov** [comment]
ok, I'll find a way for you @rrousselGit, to run this error somehow!

**Comment by JagdishOnGH** [comment]
what happened after? sudden close?
