### ISSUE TITLE
enable override the update condition of ref.watch

### ISSUE THREAD

**Issue by CardosoShlomo** [rrousselGit/riverpod#3647]
**Is your feature request related to a problem? Please describe.**
```dart
final list = ref.watch(listProvider);

ListView(
  children: [
    for (int i = 0; i < list.length; i++) ProviderScope(
      overrides: [
        itemProvider.overrideWithValue(list[i])
      ],
      child: const ListItem(),
    ),
  ],
);
```

This simple code is the suggested way, by the official todo list example, to watch a list.
scoping the ListItem widget to make it constant help us to lower amount of builds trigger on the items of the list.
but we still trigger the build of the ListView even if only one item of the list changed.

The solution I came up with is to build the ListView only when the length of the list is changed and override the value of itemIdProvider instead of itemProvider.

```dart
static final itemIdProvider = Provider<String>((ref) => throw UnimplementedError());
static final itemProvider = Provider((ref) {
  final id = ref.watch(itemIdProvider);
  return ref.watch(listProviderFamily(id));
}, dependencies: [itemIdProvider]);
```
```dart
itemIdProvider.overrideWithValue(list[i].id)
```
```dart
final list = useState(ref.read(listProvider));
    
ref.listen(listProvider, (previous, next) {
  if (previous.length != next.length) {
    list.value = next;
  }
});
```

**Describe the solution you'd like**
My suggested solution is to combine ref.listen and ref.watch using code similar to provider.select
to make it more intuitive and flexible:
```dart
final list = ref.watch(listProvider.where((previous, next) {
  return previous.length != next.length;
}));
```
or
```dart
final list = ref.watchWhen(listProvider, (previous, next) {
  return previous.length != next.length;
});
```

**Additional context**
This feature is practically overriding the condition to update a provider which can be helpful with notifiers that use Identical
instead of deep equality.
And as this feature is similar use of updateShouldNotify in InheritedWidget and buildWhen in BlocBuilder.
adding it will ease the migration for Bloc user.

**Comment by rrousselGit** [comment]
This is voluntarily not a thing. Because that's error prone. Using `select`, it's way less likely to write code where the UI does not update when it needs to.   
Using a "when"-like pattern, if there's a bug in your == logic, it'd be very difficult to spot.

**Comment by rrousselGit** [comment]
An alternative way of doing it is:

```dart
final length = ref.watch(listProvider.select((list) => list.length));

ListView(
  children: [
    for (int i = 0; i <length; i++) ProviderScope(
      overrides: [
        itemIndexProvider.overrideWithValue(i)
      ],
      child: const ListItem(),
    ),
  ],
);
```

**Comment by CardosoShlomo** [comment]
@rrousselGit 
what about adding a namedParameter to the select that determine if you want to get the selected value or the original provider's value

something like:

```dart
final list = ref.watch(listProvider.select((list) => list.length, getOriginal: true));
```

**Comment by rrousselGit** [comment]
That's not doable with generics.
And it still goes against the purpose of `select` instead of `when`

**Comment by CardosoShlomo** [comment]
ok thanks, I think you can close this issue as this is a nice to have request
