### ISSUE TITLE
Why do you still generate _SystemHash in each file instead of using Object.hash/hashAll?

### ISSUE THREAD

**Issue by darkstarx** [rrousselGit/riverpod#3648]
Hello, guys!

I noticed that each generated file has this code:
```dart
/// Copied from Dart SDK
class _SystemHash {
  _SystemHash._();

  static int combine(int hash, int value) {
    // ignore: parameter_assignments
    hash = 0x1fffffff & (hash + value);
    // ignore: parameter_assignments
    hash = 0x1fffffff & (hash + ((0x0007ffff & hash) << 10));
    return hash ^ (hash >> 6);
  }

  static int finish(int hash) {
    // ignore: parameter_assignments
    hash = 0x1fffffff & (hash + ((0x03ffffff & hash) << 3));
    // ignore: parameter_assignments
    hash = hash ^ (hash >> 11);
    return 0x1fffffff & (hash + ((0x00003fff & hash) << 15));
  }
}
```

Why?

There are `Object.hash` and `Object.hashAll` for that, aren't they?

**Comment by rrousselGit** [comment]
Object.hash has a limited number of fields you can pass.
Object.hashAll requires an array ; which is a bit slow.

That SystemHash thing enables generating a hash regardless of how many fields an object has, and without that array allocation

**Comment by darkstarx** [comment]
Alright, I see. But why not to implement this class somewhere outside and import from there instead of having lots of copies in each generated class?

**Comment by rrousselGit** [comment]
I didn't want to add a new public API on freezed_annotation.

With macros, the generated code will be able to add imports. So then, we wouldn't need to generate it everytimes.
But as it is, I'd have to make the class public.

I've made the mistake before with other types. Some folks started importing freezed_annotation for things that should only be used by the code-generator.

**Comment by rrousselGit** [comment]
Closing as this was answered :)

**Comment by darkstarx** [comment]
Ok, thanks for the clarification.
I just wander to know for myself, what the negative consequences were of someone importing that public class for their own needs?
