### ISSUE TITLE
Unable to test build method of notifier provider if it changes during first camputation

### ISSUE THREAD

**Issue by diasmalibekov** [rrousselGit/riverpod#3654]
**Describe the bug**
I need to test a provider that depend on two another providers (watches them). So when the first computation is in progress and some of the providers I'm watching in build method changes I get an error:
**Bad state: The provider sipAccountRepositoryProvider:AutoDisposeAsyncNotifierProviderImpl<SipAccountRepository, SipState>#ba9e8 was disposed during loading state, yet no value could be emitted.**
Provider that I am testing: 
class SipAccountRepository extends _$SipAccountRepository {
  @override
  Future<SipState> build() async {
    ref.watch(sipSettingsUpdateListenerProvider);

    final activeWSUrl = await ref.watch(wSUrlsProvider.future);
    final sipSettings = await ref.watch(userSipSettingsHandlerProvider.future);

    if (sipSettings is UserSipSettingsSaved &&
        activeWSUrl is ActiveWSUrlSaved) {
      await _registerSipAccount(sipSettings, activeWSUrl);
    }

    return await ref.watch(sipUaProvider.future);
  }
}
Test code:
test('Not strating sip service if no current active ws url', () async {
      when(() => mockAccessTokenStorageRepository.isUserAuthenticated())
          .thenAnswer((_) async => false);

      await container.read(sipAccountRepositoryProvider.future);
});

**Expected behavior**
I understand that it happens because I try to read .future, but in this case I need to watch this provider, and unfortunately there's no any way to await the provider return its final value.

**Comment by rrousselGit** [comment]
Your provider is autoDispose, so you need to listen to it or it's going to get disposed.

Use:

```dart
final sub = container.listen(sipAccountRepositoryProvider.future, (p, n) {});
await sub.read();
```

**Comment by diasmalibekov** [comment]
thanks a lot - it works!

**Comment by diasmalibekov** [comment]
hi, it's me again
I think I found new trouble, I am still writing tests and my test calls two functions:
```
 Future<void> handleNewWSUrls(UserSipSettingsSaved newSipSettings) async {
    await clearFailedWSUrls();
    final activeWSUrl = await ref.read(**currentWSUrlProvider**.future);
    print('current ws url - $activeWSUrl');

    if (activeWSUrl is! ActiveWSUrlSaved ||
        !newSipSettings.sip.webrtcUrls.contains(activeWSUrl.wsUrl)) {
      await calculateActiveWSUrl(newSipSettings);
    }
  }
```
```
  /// Calculates active ws url
  Future<void> calculateActiveWSUrl(UserSipSettings sipSettings) async {
    state = const AsyncLoading();

    if (sipSettings is! UserSipSettingsSaved) {
      state = AsyncValue.error(const ActiveWSUrlsError(), StackTrace.current);

      return;
    }

    final blockedWSUrls =
        await ref.read(failedWSUrlsStorageDataSourceImplProvider).read();
    final availableWSUrls = sipSettings.sip.webrtcUrls
        .where((url) => !blockedWSUrls.urls.contains(url))
        .toList();

    if (availableWSUrls.isEmpty) {
      state = AsyncValue.error(const ActiveWSUrlsError(), StackTrace.current);

      return;
    }

    print('new url - ${availableWSUrls.first}');

    await ref
        .read(**currentWSUrlProvider**.notifier)
        .setActiveUrl(ActiveWSUrl.saved(wsUrl: availableWSUrls.first));

    print('active ws url updated');
    ref.invalidateSelf();
    await future;
  }
```

so, despite in my tests I listen to **currentWSUrlProvider** like this:
`container.listen(currentWSUrlProvider, (_, __) {});`
right after this line 
 final activeWSUrl = await ref.read(**currentWSUrlProvider**.future);
 print('current ws url - $activeWSUrl');
 in handleNewWSUrls - currentWSUrlProvider disposed and I see such an error
 **Bad state: Tried to read a provider from a ProviderContainer that was already disposed**
 this is my currentWSUrlProvider
```
 class CurrentWSUrl extends _$CurrentWSUrl {
  @override
  Future<ActiveWSUrl> build() async {
    ref.onDispose(() => print('bye everyone'));
    ref.onAddListener(() => print('new listener'));
    ref.onRemoveListener(() => print('remove listener'));
    final wsUrl =
        await ref.watch(activeWSUrlStorageDataSourceImplProvider).read();
    return wsUrl;
  }
}
```
and I see such logs also, so I assume that provider still has at least one listener:
**new listener
new listener
current ws url - ActiveWSUrl.saved(wsUrl: mock_ws_url)
bye everyone
new url - mockWebrtcUrl1
Bad state: Tried to read a provider from a ProviderContainer that was already disposed**
