### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by clawvyrin** [rrousselGit/riverpod#3656]
Hey, i'm trying to use riverpod for my app but i can't move forward because of the outdated documentation can you please update it?

**Comment by rrousselGit** [comment]
There's a separate issue for it.
I'll update it when I'm done with 3.0 features

**Comment by clawvyrin** [comment]
Thanks for your quick replay, any idead on when that'll be ?

**Comment by rrousselGit** [comment]
Probably a few months unfortunately. There's quite a lot to do.

But those "out of date" docs still should be quite useful regardless
