### ISSUE TITLE
Is it possible to do eager-initialisation of ProviderScopes?

### ISSUE THREAD

**Issue by davebound** [rrousselGit/riverpod#3662]
I'm using a PageView to display several pages. Each page is of the same type, and displays a pile of data from several (chained) providers. These providers all depend on a Root provider that is specific to each page, so it makes sense to use a different ProviderScope for each page and override the Root provider in each scope.

This all works, except it takes say 5 secs to calculate the providers in each ProviderScope and therefore when I swipe to a different page, I have to wait 5 secs for the page to render (because PageView does not support [cacheExtent)](https://github.com/flutter/flutter/issues/45632)

I would therefore like to eagerly initialise each ProviderScope, so that when I swipe, I don't have to wait for the providers supplying the UI to calculate.

Is there a way to do this please?

**Comment by rrousselGit** [comment]
You'll have to mount those widgets for them to be able to initialize.
It's not really Riverpod-specific knowledge then. You can rely on widgets such as `Offstage` to mount a widget without rendering it.
