### ISSUE TITLE
examples/pub dependencies and auth problems

### ISSUE THREAD

**Issue by Chematronix** [rrousselGit/riverpod#3663]
Howdy.  I'm falling for Flutter, and Riverpod seems like a worthy addition to the batter.  I took a look at the examples, and [pub](https://github.com/rrousselGit/riverpod/tree/master/examples/pub) seemed simple enough to get started, but complete enough for real life applications.  Took a bit of trial and error to get running though, and I can't figure out where to get `userToken` from.

I'm on Windows with the latest stable Flutter:
```
D:\Dev\Flutter\riverpod>flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 days ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

`flutter pub get` failed at first with 
```
Because analyzer >=6.5.1 depends on meta ^1.15.0 and analyzer >=6.5.0 <6.5.1 depends on meta ^1.14.0, analyzer >=6.5.0 requires meta
  ^1.14.0.
And because every version of riverpod_analyzer_utils from path depends on analyzer ^6.5.0 and every version of flutter from sdk depends
  on meta 1.12.0, riverpod_analyzer_utils from path is incompatible with flutter from sdk.
So, because pub_app depends on both flutter from sdk and riverpod_analyzer_utils from path, version solving failed.
```

I could make dependencies happy by removing analyzer's version pin from packages/*/pubspec.yaml, but then `dart run build_runner build -d` failed.  I ended forcing flutter to download all packages:
```
D:\Dev\Flutter\riverpod\examples\pub>mv pubspec_overrides.yaml pubspec_overrides.yaml.orig
D:\Dev\Flutter\riverpod\examples\pub>perl -pi -e "s/^\s+path/#$&/" pubspec.yaml
D:\Dev\Flutter\riverpod\examples\pub>fluttter pub get
[...]
* flutter_riverpod 2.5.1 (was 2.5.1 from path ..\..\packages\flutter_riverpod)
* hooks_riverpod 2.5.1 (was 2.5.1 from path ..\..\packages\hooks_riverpod)
* riverpod 2.5.1 (was 2.5.1 from path ..\..\packages\riverpod)
* riverpod_analyzer_utils 0.5.1 (was 0.5.3 from path ..\..\packages\riverpod_analyzer_utils) (0.5.3 available)
* riverpod_annotation 2.3.5 (was 2.3.5 from path ..\..\packages\riverpod_annotation)
* riverpod_generator 2.4.0 (was 2.4.2 from path ..\..\packages\riverpod_generator) (2.4.2 available)
* riverpod_lint 2.3.10 (was 2.3.12 from path ..\..\packages\riverpod_lint) (2.3.12 available)
```

This allowed the app to be built.

1.  Is the app outdated, or something missing from the instructions?
2.  Where to get `userToken` to play with the Like functionality?  I tried pub.dev's `user_session` token, with no luck.
3. If I examine a response's object type, say `packagesResponse.packages.first.runtimeType`, I get `_$SearchPackageImpl` instead of the expected `SearchPackage`.  Is this normal, AKA Freezed dark magikz?
4. And while I'm here, seems Dart has no simple way to iterate through the keys of an object.  In [this Stack question](https://stackoverflow.com/questions/53629646/flutter-iterate-through-object-keys-and-values), consensus seems to be to convert it to Json.  Freezed helps do exactly this, but it's wacky to play ping pong like that.  Is there any alternative way, or plans for it?

Thanks in advance!

**Comment by rrousselGit** [comment]
Flutter is what's out of date here. The stable branch uses some old dependencies. The issue will fix itself when a new stable version is released.

> Where to get userToken to play with the Like functionality? I tried pub.dev's user_session token, with no luck.

It was hardcoded, for the sake of having a simple example.

> If I examine a response's object type, say packagesResponse.packages.first.runtimeType, I get _$SearchPackageImpl instead of the expected SearchPackage. Is this normal, AKA Freezed dark magikz?

Normal

> And while I'm here, seems Dart has no simple way to iterate through the keys of an object. In [this Stack question](https://stackoverflow.com/questions/53629646/flutter-iterate-through-object-keys-and-values), consensus seems to be to convert it to Json. Freezed helps do exactly this, but it's wacky to play ping pong like that. Is there any alternative way, or plans for it?

That's unrelated to Riverpod. And no there's no plan for it, either here nor in Freezed :)
