### ISSUE TITLE
The subclass of AutoDisposeNotifier can always obtain internationalization, even if the phone's system Settings are Chinese, and finally English

### ISSUE THREAD

**Issue by wangzhipeng-vicky** [rrousselGit/riverpod#3665]
The subclass of AutoDisposeNotifier can always obtain internationalization, even if the phone's system Settings are Chinese, the final is English, like this code below, I always get English

 S.of(context).maintainInfo("")

`import 'package:flutter/cupertino.dart';
import 'package:indonesia_qs_management/vm/store_manage.dart';
import 'package:v_components/v_components.dart';

import '../../generated/l10n.dart';

/// FileName tabpage_notifier
///
/// @Author ThinkPad
/// @Date 2024/7/17 15:36
///
/// @Description 老铁 写下你的备注哦

class TabState {
  final List<String> tabTitle;//详情的
  final List<String> listTabTitle;//list的  怕一个模块的详情里把list的影响了
  bool isNeedRefresh = false;

  TabState({
    required this.tabTitle,
    required this.listTabTitle,

    this.isNeedRefresh = false,
  });

  TabState.initial() : tabTitle = [],listTabTitle=[];

  TabState copyWith({
    List<String>? tabTitleArr,
    List<String>? listTabTitleArr,
    bool? isNeedRefresh,
  }) {
    return TabState(
      tabTitle: tabTitleArr ?? tabTitle,
      listTabTitle: listTabTitleArr ?? listTabTitle,
      isNeedRefresh: isNeedRefresh ?? this.isNeedRefresh,
    );
  }
}

class CommonTabNotifier extends AutoDisposeNotifier<TabState> with PageMixins {
  @override
  TabState build() {
    return TabState.initial();
  }

  set isNeedRefresh(int code) {
    state = state.copyWith(isNeedRefresh: !state.isNeedRefresh);
  }

  set tabTitle(List<String> tabTitle) {
    state = state.copyWith(tabTitleArr: tabTitle);
  }

  set listTabTitle(List<String> tabTitle) {
    state = state.copyWith(listTabTitleArr: tabTitle);
  }

  // 维修详情
  initWXDetailTabs(BuildContext context){
    state=state.copyWith(tabTitleArr: [
      S.of(context).maintainInfo(""),
      S.of(context).repairGroup(S.of(context).scheme),
      S.of(context).maintainName+ S.of(context).event,
    ]);
  }
  // 租赁详情
  initLeaseDetailTabs(BuildContext context){
    state=state.copyWith(tabTitleArr: [
      S.of(context).leaseDispatch,
      S.of(context).applyOrderEvent,
    ]);
  }
  // 出车单详情
  initVehicleInvoiceDetailTabs(BuildContext context){
    state=state.copyWith(tabTitleArr: [
      S.of(context).leaseDispatch,
      S.of(context).vehicleInvoiceEvent,
    ]);
  }

  // 镍矿转运计划列表
  initNickelOrePlanTabs(BuildContext context){
    final locale = read(localeProvider);
    state=state.copyWith(listTabTitleArr: [
      S.of(context).tab_all(""),
      S.of(context).tab_ddd(""),
      S.of(context).tab_in_execution(""),
      S.of(context).tab_finished(""),
    ]);
  }

}`

**Comment by rrousselGit** [comment]
For general help requests, please go on Discord or StackOverflow. This is for bug reports.

**Comment by wangzhipeng-vicky** [comment]
> For general help requests, please go on Discord or StackOverflow. This is for bug reports.

Are you telling me that the solution is better? Do you think that's funny
