### ISSUE TITLE
Add something like `ref.watchStream(...)`

### ISSUE THREAD

**Issue by timcreatedit** [rrousselGit/riverpod#3683]
**Is your feature request related to a problem? Please describe.**
You must be a bit tired of questions about `StreamProvider.stream`. However, in my heavy day-to-day riverpod use, I still find myself often wishing for a way to easily use Stream – especially `rxdart` – APIs with riverpod.

Especially for use cases like buffering, `rxdart`s API is just extremely composable, and achieving the same using `ref.watch()` is often verbose and error-prone.

**Describe the solution you'd like**
Use the mental model of `ref.listen()` and create a riverpod-esque `.stream` alternative. Similar to `.listen()` we would always want the latest value to be pushed into the Stream to prevent race conditions. It would also be usable with all providers, both sync and async. This could supercharge the composition of providers, and make adoption easier for folks who spent a lot of time writing Rx code:

```dart
final rawDataProvider = Provider.autoDispose<int>((ref) {
  final t =
      Timer.periodic(const Duration(milliseconds: 500), (_) => ref.state++);
  ref.onDispose(t.cancel);
  return 0;
});

final buffered = StreamProvider.autoDispose.family(
  (ref, Duration bufferTime) => ref
      .watchStream(rawDataProvider)
      .bufferTime(bufferTime)
      .take(3),
);
```

**Describe alternatives you've considered**
You can often write notifiers to achieve things like buffering, however this approach is neither composable nor reusable. Granted, Writing mixins can help with this.

Another alternative would be to add more transformer-like APIs to riverpod (potentially as `Ref` extensions similar to the `.debounced` examples). This is the approach that `state_beacon` uses, however I think it muddles the API unnecessarily. A big reason why I fell in love with riverpod in the beginning was that it played so nicely with `Stream` APIs – or so I thought until I sometimes faced the issues that ultimately lead to the `.stream` deprecation.

**Additional context**
I have to say, I am not 100% familiar with the technical reasons behind why `.stream` needed to be deprecated and couldn't be "fixed" to match user's expectations more closely. In my experience, a large missing piece was that "missing" events could lead to race conditions and deadlocks, since they were not always available to new listeners. Maybe I'm not seeing the full picture, but I feel like emitting the most recent event to each new listener (similar to `BehaviorSubject` in `rxdart`) would resolve these issues.

**Comment by rrousselGit** [comment]
You can implement that yourself using an extension method, by relying on `ref.listen` and `ref.onDispose`.

I'm not sure there's a reason to include that in Riverpod itself.

**Comment by timcreatedit** [comment]
You are always ridiculously fast 😅

I'm aware, and I've done so in one of my projects, however there are also some footguns. Looking at questions about the `.stream` deprecations, a big reason people seemed to struggle with it seems to be that they wanted to use `Stream` APIs. First-party support in riverpod would allow for using these APIs without worrying about ones own implementation leading to weird edge-cases.

In general, it would add a lot of the stuff that's missing from riverpod (e.g. Buffering, debouncing) as an opt-in solution that wouldn't need to be maintained by riverpod.

**Comment by rrousselGit** [comment]
That's the thing: I don't want to push Stream operators. If I wanted those to be used, Riverpod would already natively integrate with it.   

I'd much rather have discussions about what's difficult to do without those Streams APIs and talk about how to do those in Riverpod.
For example, debouncing is just adding an `await duration` at the start of a provider.

**Comment by timcreatedit** [comment]
If that's the motivation, then I see why we are moving away from `Stream`s in riverpod in general.

Would you mind providing the reasoning for this? Or have you perhaps discussed it somewhere already that I didn't find? My feeling is that lots of packages and APIs depend on `Stream`, and while it's nice that `Stream<Provider/Notifier>` let you work with them, once you have "locked" a Stream in there, you have to be done with it.

Towards your other question, `buffer` is an operator that I couldn't easily get to work in a composable fashion. Having a rapidly changing value that we want to display without all of the noise happens semi-frequently where I work. Debounce doesn't cover this since the timer is reset every time the value updates.

Going off the rails even further: I think for many people it is not really feasible to _technically_ be able to implement such operations in riverpod, since that is not really approachable and opens up a lot of questions for beginners about when Providers/Notifiers recompute, which values and callbacks persist across rebuilds, etc. I've experienced a lot of difficulty onboarding devs to riverpod, and I think some more familiar APIs and "plug-and-play" features might help with that.
That's entirely outside of the scope of this issue though.

**Comment by rrousselGit** [comment]
It's definitely part of the motivation. IMO Stream APIs usually are "looks clever, but fails in subtle ways that won't be caught during review".

> Towards your other question, buffer is an operator that I couldn't easily get to work in a composable fashion. Having a rapidly changing value that we want to display without all of the noise happens semi-frequently where I work. 

Could you expand on what it is?
If you're talking about transforming Provider<T> into Provider<List<T>>, I typically do it by creating an intermediate provider and use ref.listen

>  I think for many people it is not really feasible to technically be able to implement such operations in riverpod

Sure. But it could be a package.
It's just not something I want to promote and have to document. If it's there, I'd have to start explain why folks should use it ; which would be counter productive as I don't want folks to rely on Stream APis.

**Comment by timcreatedit** [comment]
> It's definitely part of the motivation. IMO Stream APIs usually are "looks clever, but fails in subtle ways that won't be caught during review".

I do agree with this! Especially in Dart, there are a lot of pitfalls related to Streams, which is part of my motivation for this issue. I think riverpod providers, at their core, are much closer to what the average newbie expects a `Stream` to be (remembers and re-publishes latest value, disposes automatically, n listeners, e.t.c.). Where `Stream` APIs shine compared to riverpod IMO, is composability (and to some extent readability).

> Could you expand on what it is?

Sure, upon re-reading my last comment, I wasn't as clear as I thought I was at all.
What I basically want is `bufferTime` or `throttleTime` (depending on if intermediate values are important) from `rxdart`. The important part is that it is time-based.

Ideally, it would be an extension on `Ref` or something similar, so that it can be reused at will.

> If you're talking about transforming Provider into Provider<List>, I typically do it by creating an intermediate provider and use ref.listen

I've done this in a lot of cases as well and, while it works, it is a good example for one of the pains I'm referring to: This approach isn't reusable or composable. Every time I would want to do this, I would basically need to implement it from scratch. Any approaches to solving this using an extension on `Ref` that I can think of would have to rely on `ref.listen` and `ref.state` which would introduce side effects to the provider. 

> Sure. But it could be a package.

I also agree that riverpod should not introduce all these transformations, which is why I made the comparison to `state_beacon` in my original comment. However, building such things into a riverpod-specific package seems tricky to me, since building different transformations would require different paradigms (although smarter people than me might find ways to have a consistent API for them). Considering the example you mentioned:

```dart
// Untested, something like this could work?
extension RefBuffer<V> on ProviderRef<List<V>> {
  void buffer(AlwaysAliveProviderListenable<V> listenable) {
    listen(
      listenable,
      fireImmediately: true,
      (_, next) {
        state = [...state, next];
      },
    );
  }
}

// Used like this:
final bufferedProvider = Provider((ref) {
  ref.buffer(valueProvider);
  return [];
});
```

Consumers of this API would need to know that this calls the `.state` setter, and that anything they want to return in the build function of the provider will be overwritten by this for example. 

When you look at a `ref.debounce()` extension in comparison, it becomes clear that operations like this would be used in completely different ways, and it would be difficult to build a mental model around how they work.

I still believe that allowing the consumption of Providers as Streams allows people to benefit from the good parts of the Streams API, while avoiding most of the pain points that come with it. At the same time, it would greatly enhance the options that are available for composing riverpod Providers without introducing all the maintenance requirements and overhead.

**Comment by rrousselGit** [comment]
I think in general, what you want is an `extension<T> on ProviderListenable<T>` and make your subclass of `ProviderListenable`.
With 3.0 removing a bunch of interfaces, this should be easier to do.

So the end api would be

```dart
T ref.watch(provider.buffered(duration));
List<T> ref.watch(provider.throttled(duration));
Stream<T> ref.watch(provider.streamed);
```

(with the option of using ref.listen/ref.read if you wished)

Subclassing `ProviderListenable` is a bit technical, but doable.

**Comment by timcreatedit** [comment]
> I think in general, what you want is an `extension<T> on ProviderListenable<T>` and make your subclass of `ProviderListenable`.

Well you are certainly right, this is exactly what I want! I've actually tried implementing this in the past, but found it difficult, in part due to the Type Hierarchy.

It's also a little throwback for me to one of my first issues on here #1150 since this is exactly the kind of API I would have expected to use with riverpod.

Once 3.0 is shaping up, I would gladly contribute to writing transformers like this, even if they are in a separate package. I'm in the middle of assembling a `hooks_riverpod` [package](https://pub.dev/packages/rivership) that is meant to include such helpers, so if you don't want to endorse an implementation, I would start doing it in there :)

> And this is something that could be worth documenting and pushing.

Would you want me to open a new issue to track this?

---

Thanks for your time and insight, I believe your suggestion covers my needs quite well. Until 3.0, I'll keep using my homemade `ref.watchStream` :)

**Comment by rrousselGit** [comment]
> Would you want me to open a new issue to track this?

If you want :)

----

Overall, it's probably that I'll include _some_ operators directly in Riverpod. A throttle has been requested a few times.
For `buffer`, I'm not sure. I've needed it a few times before, but nobody requested it to me.

**Comment by nateshmbhat** [comment]
i would really love a throttle and streamed operators to the provider please 🥹 🥹 🥹
