### ISSUE TITLE
Error: 'LintCode' is imported from both 'package /src/dart/error/lint_codes.dart' and 'package /src/lint_codes.dart' on Flutter 3.24.0 with build_runner

### ISSUE THREAD

**Issue by hirosz** [rrousselGit/riverpod#3689]
When i try build_runner there is error on Flutter 3.24.0

flutter pub run build_runner build

Deprecated. Use `dart run` instead.
Building package executable... 
Built build_runner:build_runner.
[INFO] Generating build script completed, took 200ms
[WARNING] ../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.3/lib/src/lint_rule.dart:11:1: Error: 'LintCode' is imported from both 'package:analyzer/src/dart/error/lint_codes.dart' and 'package:custom_lint_core/src/lint_codes.dart'.
import '../custom_lint_core.dart';
^^^^^^^^
[INFO] Precompiling build script... completed, took 618ms
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

Flutter version:
Flutter 3.24.0-1.0.pre.486 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0a7f8af6d1 (44 minutes ago) • 2024-08-06 16:05:03 -0700
Engine • revision 206e86ee8a
Tools • Dart 3.6.0 (build 3.6.0-117.0.dev) • DevTools 2.38.0

**Comment by AlcoholicCoder** [comment]
You can override `analyzer` version in `pubspec.yaml` until `custom_lint` gets updated.
```yaml
dependency_overrides:
  analyzer: 6.7.0
```

**Comment by rrousselGit** [comment]
It's a duplicate. This is a known issue and is being worked on, among other things.

**Comment by kerridge** [comment]
I have this issue on the `riverpod_generator 3.0.0-dev.11` branch as I need the generic provider return types 3.0 offers, is there any chance of a cherrypick for that?

**Comment by rrousselGit** [comment]
No. I do not update the dev branch for now.
