### ISSUE TITLE
invalidate provider on widget dispose()

### ISSUE THREAD

**Issue by ShyshkovOleg** [rrousselGit/riverpod#3700]
**Describe the bug**
**Error: Bad state: Cannot use "ref" after the widget was disposed.**

Any suggestions on how I could invalidate provider on widget disposal ? My real world scenario a bit more complex as my provider depends on another provider and I need to invalidate first one in order to build() method to be called in next initialization, but I've added minimal code to reproduce the issue.

P.S. When I wrap `.invalidate(...)` with `if (context.mounted)` provider is not disposed.

Thanks in advance.

**To Reproduce**
````
class _TestState extends ConsumerState<Test> {
  @override
  void dispose() {
    ref.invalidate(testSliceProvider);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ref.watch(testSliceProvider);
    return Container();
  }
}

**Provider:**

@riverpod
class TestSlice extends _$TestSlice {
  @override
  String build() {
    ref.onDispose(() => print('Destroyed TEST SLICE'));
    return '';
  }
}
````

**Comment by rrousselGit** [comment]
You shouldn't call `invalidate` inside `State.dispose`, as this is a side-effect in a life-cycle called while the UI is building.

Instead call it in the place that causes your widget to be unmounted.
