### ISSUE TITLE
Why might Riverpod destroy a provider?

### ISSUE THREAD

**Issue by mauricev** [rrousselGit/riverpod#3702]
I have a provider declared as follows

```
final ChangeNotifierProvider<TanksLiveViewModel> gTanksLiveViewModelProvider = ChangeNotifierProvider<TanksLiveViewModel>((ref) {
  FacilitiesViewModel facilitiesViewModel = ref.watch(gFacilitiesViewModelProvider);
  GenoTypeViewModel genoTypeViewModel = ref.watch(gGenoTypeViewModelProvider);
  TankSizesViewModel tankSizesViewModel = ref.watch(gTankSizesViewModelProvider);
  ShelfTemplateViewModel shelfTemplateViewModel = ref.watch(gShelfTemplateViewModelProvider);
  TanksLineViewModel tankLineViewModel = ref.watch(gTankLineViewModelProvider);
  return TanksLiveViewModel(gDatabase: gDatabase, gRef: ref, gFacilitiesViewModel: facilitiesViewModel,gGenoTypeViewModel: genoTypeViewModel,gTankSizesViewModel: tankSizesViewModel,gShelfTemplateViewModel: shelfTemplateViewModel,gTankLineViewModel: tankLineViewModel);
});
```
During the course of running, a variable in facilitiesViewModel is changed and notifylisteners is called. This caused Riverpod to dispose the TanksLiveViewModel. Interestingly, if I change the .watches above to .read's, then this doesn't happen. 

What's the real difference between read and watch? 

When would it ever make sense for Riverpod on its own to dispose a provider?

**Comment by rrousselGit** [comment]
The whole point of "watch" is that it recomputes the provider when the value changes. So that causes a dispose too.
Nothing unexpected :)

**Comment by mauricev** [comment]
I am sorry but you're not making any sense and with apparent this lone exception it is not actually the case, which clearly acts like a bug.

First, I have over 40 references to .watch scattered about my program, and I put in debug statements to tell me if any providers are disposed of. So far, I'm not seeing any. Of course, if it did that as it does when the above references are .watch, all the provider's data would be destroyed when it is triggered by notifylisteners, and the program will promptly misbehave and crash. 

Can you please explain under what circumstance does it make sense for Riverpod to destroy the data it is managing?
