### ISSUE TITLE
Updating AsyncNotifier state if it contains error

### ISSUE THREAD

**Issue by diasmalibekov** [rrousselGit/riverpod#3704]
**Describe the bug**
I am wondering how to safety update state if it contains error?

**To Reproduce**

class IntegerProvider extends _$IntegerProvider {
  @ override 
  Future<int> build() => Future.value(0);
  
  void setStateError() {
    state = AsyncError(Exception('some exception'));
  }
  
  void incrementValue1() async {
    // If state contains .error, an Exception will be thrown
    final prevState = await future;
    state = AsyncData(prevState + 1);
  }
  
  void incrementValue2() {
    final prevState = state.value;
    state = AsyncData((prevState ?? 0) + 1);
  }
}

// State will be updated and will be equal to 1
await ref.read(integerProvider.notifier).incrementValue1();
  
// State now contains an error
await ref.read(integerProvider.notifier).setStateError();
  
// State will NOT be updated and the next call will throw an Exception
await ref.read(integerProvider.notifier).incrementValue1();
  
// State will always be updated even if it contains .error
await ref.read(integerProvider.notifier).incrementValue2();

**Expected behavior**
I am not sure about expected behaviour, just a question
If at any moment the state can contain an error (.error), 
is the only way to update the state based on its previous state.value 
without catching an error to use incrementValue2?

**Comment by rrousselGit** [comment]
It's expected for `await future` to throw if you're in error state.

If you want to handle errors, either catch the error thrown by `await future` or read `state.error`

**Comment by diasmalibekov** [comment]
so, if state contains error the only way to update state based on its previous value is:
```
void incrementValue2() {
  final prevState = state.value;
  state = AsyncData((prevState ?? 0) + 1);
  }
}
```

**Comment by diasmalibekov** [comment]
so, if state contains .error and .value that was before the error -- the only way to update state based on its previous value is:

```
void incrementValue2() {
  final prevState = state.value;
  state = AsyncData((prevState ?? 0) + 1);
  }
```
