### ISSUE TITLE
Publish new versions to pub.dev

### ISSUE THREAD

**Issue by lishaduck** [rrousselGit/riverpod#3709]
**Describe the bug**
The most recent patches to riverpod_lint (#3706) failed to release.

**To Reproduce**

https://pub.dev/packages/riverpod_lint

**Expected behavior**
It didn't display an analysis issue warning.

PS: Thanks for Riverpod! It's why Dart's my favorite language—it has Riverpod! 🙃

**Comment by rrousselGit** [comment]
My bad. Forgot to press one button.
Done
