### ISSUE TITLE
Provider throws "Bad state" error when ref.invalidate is called after ref.read

### ISSUE THREAD

**Issue by MosMercDev** [rrousselGit/riverpod#3714]
**Describe the bug**
`AutoDisposeStreamNotifierProvider` throws an error `Bad state: Cannot call onDispose after a provider was dispose` when `ref.invalidate` is called after `ref.read`. This behavior is different from `AutoDisposeAsyncNotifierProvider` and looks like a bug.

**Dependencies**

```yaml
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  riverpod_generator: 2.4.3
```

**To Reproduce**

```dart
@riverpod
class StreamTest extends _$StreamTest {
  @override
  Stream<int> build() async* {
    ref.onDispose(
      () {
        print('Stream disposed');
      },
    );
    yield 0;
  }
}

@riverpod
class FutureTest extends _$FutureTest {
  @override
  Future<int> build() async {
    ref.onDispose(
      () {
        print('Future disposed');
      },
    );
    return 0;
  }
}

class MainApp extends ConsumerWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      home: Scaffold(
        floatingActionButton: FloatingActionButton.extended(
          label: const Text('Run tests'),
          onPressed: () async {
            // This works fine (onDispose not called)
            ref.invalidate(streamTestProvider);

            // This works fine (onDispose prints text)
            await ref.read(streamTestProvider.future);
            ref.invalidate(streamTestProvider);

            // This works fine (onDispose prints text)
            ref.read(futureTestProvider).valueOrNull;
            ref.invalidate(futureTestProvider);

            // This throws error
            // Bad state: Cannot call onDispose after a provider was dispose
            ref.read(streamTestProvider).valueOrNull;
            ref.invalidate(streamTestProvider);
          },
        ),
      ),
    );
  }
}
```

**Expected behavior**
The `streamTestProvider` prints `Stream disposed` in the last case similar to `futureTestProvider`.

**Comment by rrousselGit** [comment]
async* is to blame.
It introduces a delay that async doesn't. That's like starting an async function  with `await null;`

In that sense, the error is expected. By the time ref.onDispose is called, your provider was already disposed due to the async delay and the fact that you're not using ref.watch

I'd suggest not using async*.

**Comment by MosMercDev** [comment]
@rrousselGit Thank you so much for getting back to me on my issue. 
Also, if I use `ref.watch` instead of `ref.read` in the last case, there are both error `Bad state: Cannot call onDispose after a provider was dispose` and print `Stream disposed`. Is this behavior expected?

**Comment by MosMercDev** [comment]
Oh, of course, it's expected because I put it in `onPressed`. Thank you so much for helping with my issue
