### ISSUE TITLE
AsyncValue stuck in AsyncLoading

### ISSUE THREAD

**Issue by DmitrySboychakov** [rrousselGit/riverpod#3719]
**Describe the bug**
I have a riverpod provider which stuck in the AsyncLoading state for weird reason. Should be AsyncData after AsyncValue.guard, but stays in AsyncLoading state indefinitely

**To Reproduce**

```
@riverpod
class SelectedAccount extends _$SelectedAccount {
  // ignore: avoid_public_notifier_properties
  late final logger = ref.read(loggerProvider("logger_tag"));

  @override
  FutureOr<Account> build() async => Future.any([]);

  Future<void> select(AccountSearchRecord account) async {
    state = const AsyncLoading();
    logger.info("selecting $account");
    logger.info("state $state"); // prints "state AsyncLoading<Account>()"

    state = await AsyncValue.guard(() async {
      final response = await ref.read(accountProvider(id: account.id).future);
      logger.info("$response"); // prints successful response 
      return response;
    });
    logger.info("state $state"); // prints "state AsyncLoading<Account>()" again
  }
}
```

**Expected behavior**
After AsyncValue.guard state should be either AsyncData or AsycnError, but stays in AsyncLoading

**Comment by rrousselGit** [comment]
I need a complete example that I can execute. As it is, I can't say what's the issue.

**Comment by DmitrySboychakov** [comment]
The issue was that provider is disposing since no readers and the select method was called like `ref.read(provider.notifier).select`
