### ISSUE TITLE
debug/logging -> can we print to console which code triggered a widget rebuild?

### ISSUE THREAD

**Issue by mark8044** [rrousselGit/riverpod#3740]
Is it possible to have a printout to console informing us which call triggered a widget rebuild?

This can help us debug excessive rebuilds by not well thought out .watch calls, or otherwise

for example if I have two lines of code with `.watch`, maybe only one of them was inadvertently updated and triggered an entire rebuild of a widget, this would help us isolate that bug

**Comment by rrousselGit** [comment]
A devtool is in progress. For logging, you can use ProviderObserver. It should enable you to log an event whenever a provider emits an update
