### ISSUE TITLE
TELA NÃO ATUALIZA DADOS COM PROVEDOR DENTRO DE OUTRO PROVEDOR

### ISSUE THREAD

**Issue by Mateus-IC1101** [rrousselGit/riverpod#3742]
Olá, pessoal. Quero reportar algo que talvez seja um bug.

Não consigo atualizar um provedor usando state, exemplo:

NÃO FUNCIONA: state = {...filter}

FUNCIONA: return filter.toSet();

As capturas mostram um parte do código comentado que não funciona, é preciso retornar o valor em na função e usar " ref.watch(userFilterNotifierProvider.notifier).state =
                            usersFilterLocal;" para que seja atualizado.
Lembrando que a chamada no método build está com watch: final allUsers = ref.watch(userFilterNotifierProvider);

![Captura de tela de 2024-09-13 07-47-28](https://github.com/user-attachments/assets/aba0fbdb-fb6b-4d31-830f-b96fd38bfaad)
![Captura de tela de 2024-09-13 07-47-10](https://github.com/user-attachments/assets/0f927841-8c4e-42fa-8dc7-b6826188551a)
![Captura de tela de 2024-09-13 07-46-50](https://github.com/user-attachments/assets/48f02aca-28ff-4890-81d5-cb7ec97d1767)

Isso seria um bug ? pq antes a lista estava usando userNotifierProvider e tudo funcionava, mas ao passar um provedor para outro e usar o userFilterNotifierProvider, a tela não atualiza com o state dentro do próprio provedor.

**Comment by rrousselGit** [comment]
Hello!
I do not speak this language. Please write your issue in English :)

Also, instead of screenshots, please use code snippets (using ```` ```dart ````)
