### ISSUE TITLE
Add Neq Class And Extensions For Performance Edge Cases

### ISSUE THREAD

**Issue by mcmah309** [rrousselGit/riverpod#3756]
Most of the time, the current riverpod implementation does exactly what you would want, only emit changes if the state has actually changed. Which is accomplished through the `==` operator. This seems to work fine until you get to large complex states, then this becomes a performance/usability bottleneck.

e.g. I currently have ephemeral virtual file system structures inside my state. Each time the file system changes, it would be ridiculous to copy the entire virtual file system structure.

To make this work with a virtual file system, as mentioned, I would have to copy the entire file system and possibly write traversing logic in the `==` operator determine if my state has changed. To resolve these scenarios, a not equal class (`Neq`) like

```dart
class Neq<T> {
  final T val;

  const Neq(this.val);

  @override
  bool operator ==(Object other) {
    return false;
  }

  @override
  int get hashCode => val.hashCode;

  @override
  String toString() => "Neq($val)";
}

extension NeqNotifyListeners<T> on NotifierBase<Neq<T>> {
  void notifyListeners() {
    state = state;
  }
}

extension NeqAsyncNotifyListeners<T> on AsyncNotifierBase<Neq<T>> {
  void notifyListeners() {
    state = state;
  }
}
```

should be added. Using such a class would be completely optional to users and reserved for these types of edge cases. It would also open the door to completely removing `ChangeNotifierProvider`, eliminating the need to maintain that code, while being more versatile as it works with all providers. Use:

```dart
@riverpod
class Example extends _$Example {
  @override
  Neq<Example> build() { ... }

  void method(...) {
    ...
   notifyListeners();
  }
}
```

### Alternatives Considered

One could override the `==` operator on the state object to always return false, but this is not a desired solution. This is abuse of `==`, since `==` would return false, indicating that the objects are different, but it does not actually mean they are different. This would be leaking/hiding emitter logic in the state, rather than the notifier and making use of `==` anywhere else in different contexts (like a hashmap of file system nodes) yield wrong results. Additionally, the resulting writing of `state = state` seems like a smell.

**Comment by rrousselGit** [comment]
There's ref.notifyListeners() instead
