### ISSUE TITLE
`The receiver is of type 'Never', and will never complete with a value.`

### ISSUE THREAD

**Issue by mark8044** [rrousselGit/riverpod#3761]
A while back I converted my code to use `.select` everywhere and I just noticed this warning in the IDE (Android studio):

`The receiver is of type 'Never', and will never complete with a value.`
`Dead code.`

The code in question:
```
      for(var v in ref.watch(threadProvider(widget.randomHash).select((obj) => obj.map["coredata"]["newsitem"]))) {
        _idToIndexList.add(v["thisid"]);
      }
```

The warning is referring to variable `v` returning with a type of `Never` and the Dead Code is referring to `"thisid"]);` after the `v` variable.  

The code executes just fine without problems, but I believe this occurs when I changed my selects from the old way which you had previously mentioned was wrong:

```
ref.watch(threadProvider(widget.randomHash).select((obj) => obj.map))["coredata"]["newsitem"] ==> ref.watch(threadProvider(widget.randomHash).select((obj) => obj.map["coredata"]["newsitem"]))
```

I *think* everything still runs fine, but wanted to check in on this

**Comment by rrousselGit** [comment]
I have no control over such a warning.

Just make sure that `v` is properly typed. It could be that type inference failed. In any case, I don't have nearly enough information to help here, and it's likely unrelated to Riverpod.

I'd suggest asking for help on Discord :)

**Comment by mark8044** [comment]
@rrousselGit Ok as per your suggestion I added a type within the for loop and the linter warnings disappeared.

This is so strange, but thank you :)

```dart
   for(var v in ref.watch(threadProvider(widget.randomHash).select((obj) => obj.map["coredata"]["newsitem"])) as Iterable) {
        _idToIndexList.add(v["thisid"]);
      }
```
