### ISSUE TITLE
FamilyProvider arguments is null for generated providers

### ISSUE THREAD

**Issue by w0rsti** [rrousselGit/riverpod#3770]
**Describe the bug**
I was trying to implement a simple logger to see in the console when a provider was initialized or disposed - something like:
"Provider 'providerName' was initialized"

When the provider is a family provider i want to display the arguments as well like:
"Provider 'familyProviderName' with 'id' .... was initialized"

I've noticed there is an `provider.argument` of the passed `ProviderBase<Object?> provider` but it seems to be null for generated providers since the used arguments are available directly on the object itself. 

This is not ideal though since i don't know which provider is being initialized and thus i don't know their parameters to log them.

The docs on `provider.argument` state: 
```dart
/// If this provider was created with the `.family` modifier, [argument] is
/// the variable that was used.
///
/// On generated providers, this will be a record of all arguments.
```

Which seems not be the case.

**To Reproduce**

```dart
import "package:riverpod_annotation/riverpod_annotation.dart";
import "package:hooks_riverpod/hooks_riverpod.dart";
import "package:logging/logging.dart";

@riverpod
String example(ExampleRef ref, String test) => test;

class RiverpodObserver extends ProviderObserver {
  @override
  void didAddProvider(
    ProviderBase<Object?> provider,
    Object? value,
    ProviderContainer container,
  ) {
    // provider.argument is null even though we 
    print("Initialized ${provider.name} with ${provider.argument} was initialized")
}

void main() {
 runApp(
    ProviderScope(
      observers: [if (kDebugMode) RiverpodObserver()],
      // Consume the provider somewhere so it will be initialized
      child: ...,
    ),
  );
} 
```

**Expected behavior**
The `provider.argument` variable should hold a Map or Record of all passed arguments so I can display them in the logs by simply iterating.

**Comment by rrousselGit** [comment]
Thats already how 3.0 behaves. Just wait a bit :)
