### ISSUE TITLE
Automatically add `import` when converting to `ConsumerWidget` or `ConsumerStatefulWidget`

### ISSUE THREAD

**Issue by minhqdao** [rrousselGit/riverpod#3777]
I wish `import 'package:flutter_riverpod/flutter_riverpod.dart';` would be automatically added to my Dart file when I'm converting a `StatelessWidget` or `StatefulWidget` to a `ConsumerWidget` or `ConsumerStatefulWidget` and the package import isn't already present.

Currently it's a two-step procedure: 1) Convert a `StatelessWidget` or a `StatefulWidget` to a `ConsumerWidget` or `ConsumerStatefulWidget`, followed by 2) Add the `import` statement. The conversion works even without the `import` statement. I think the process could be more seamless by automating the second step that everyone has to do anyways.

I'm using VSCode on macOS.

**Comment by rrousselGit** [comment]
Good idea.

**Comment by rrousselGit** [comment]
We should do the same for pretty much all quick-fixes.
