### ISSUE TITLE
Deprecate ref.state/.future/.notifier/.listenSelf and Ref sublasses. 

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#3784]
In 3.0, for the sake of simplifying the API, some functionalities currently accessible on `Ref` will instead move to `Notifier`s.

We should:
- make Ref's type argument optional
- Deprecate any Ref member that uses the type argument
- Deprecate Ref's type argument
- Deprecate Ref subclasses
- Mark Ref as `@sealed`
- Deprecate the `MyProviderRef` generated my riverpod_generator
- Update all reference to `Ref` in the docs accordingly
- add a Notifier.listenSelf

This should be done before 3.0, to help folks migrate

**Comment by nateshmbhat** [comment]
awesome

**Comment by rrousselGit** [comment]
We'll have to update the lints and quick-fixes too, while at it.

**Comment by mkhtradm01** [comment]
@rrousselGit  assume I had code like below, how can I migrate the `listenSelf`:

`final routerProvider = Provider<GoRouter>((ref) {
  ref.listenSelf((previous, next) {
    debugPrint("----------------- Router Changed -----------------");
    debugPrint('Changed from: $previous, next: $next');
  });
 });`

**Comment by B-Saeid** [comment]
@mkhtradm01 

For `(Async)Notifier`s you would use `listenSelf` directly as in [there](https://github.com/rrousselGit/riverpod/discussions/3830).

In your case you need to migrate to code generation. [see how](https://riverpod.dev/docs/concepts/about_code_generation).

 in oder to use `listenSelf` directly you can convert your provider to a class like so:


```
@riverpod
class MyRouterObserver extends _$MyRouterObserver {
  @override
  String build() {
    listenSelf(
      (previous, next) {
        debugPrint('----------------- Router Changed -----------------');
        debugPrint('Changed from: $previous, next: $next');
      },
    );
    return 'Home';
  }
}
```

No worries if you see such warnings and errors: 

<img width="683" alt="Image" src="https://github.com/user-attachments/assets/96eeb641-f11e-46c4-acb2-4fbfb5275ada" />


If you installed all the required packages [here](https://riverpod.dev/docs/introduction/getting_started#installing-the-package) you just need to run `dart run build_runner build` to get rid of this fuss.

Afterwards you can use `myRouterObserverProvider` as you would normally do.
