### ISSUE TITLE
None of the example projects will actually run

### ISSUE THREAD

**Issue by sfergu** [rrousselGit/riverpod#3785]
**Describe the bug**
I have attempted running all the example projects, as riverpod looks pretty useful. I receive from all of them 

```
Because every version of riverpod_analyzer_utils from path depends on analyzer ^6.9.0 which depends on collection ^1.19.0, every version of riverpod_analyzer_utils from path requires collection ^1.19.0.
And because every version of flutter from sdk depends on collection 1.18.0, riverpod_analyzer_utils from path is incompatible with flutter from sdk.
So, because stackoverflow depends on both flutter from sdk and riverpod_analyzer_utils from path, version solving failed.
```
```

$ flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (5 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3


```

**To Reproduce**

Try to run any of these projects with flutter. 

**Expected behavior**

I expect the example projects to run with flutter, or I can't really work with them. I have attempted to specify dependency_overrides for collection as a work around but it does not resolve the error.

**Comment by rrousselGit** [comment]
They run. The CI checks them all.

It's about using a Flutter version that is compatible with analyzer 6.9.0.
That may require you to switch channel :)

**Comment by sharpsan** [comment]
> They run. The CI checks them all.
> 
> It's about using a Flutter version that is compatible with analyzer 6.9.0. That may require you to switch channel :)

You want us to switch away from the stable channel to solve a dependency problem?  Do you not see the issue with that?
