### ISSUE TITLE
riverpod_annotation exports Ref type.

### ISSUE THREAD

**Issue by koji-1009** [rrousselGit/riverpod#3791]
**Is your feature request related to a problem? Please describe.**
It would be nice if riverpod_annotation would export the `Ref` for riverpod 2.6.0 support.

current (riverpod_annotaion v2.6.0)

```dart
import 'package:riverpod/riverpod.dart'; // ← Required for import of Ref
import 'package:riverpod_annotation/riverpod_annotation.dart';

@riverpod
Model foo(Ref ref) => ..
```

want

```dart
import 'package:riverpod_annotation/riverpod_annotation.dart';

@riverpod
Model foo(Ref ref) => ..
```

**Describe the solution you'd like**
Add the `Ref` type to the export list in `riverpod_annotation/riverpod_annotatino.dart`.

**Describe alternatives you've considered**
none.

**Additional context**
https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod_generator/CHANGELOG.md#260---2024-10-20

**Comment by rrousselGit** [comment]
It isn't exported on purpose.

The annotation package only exports what the generated code uses.
You're not meant to import riverpod_annotation as a replacement to Riverpod.
