### ISSUE TITLE
Add listenSelf to AsyncNotifier

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/riverpod#3795]
**Is your feature request related to a problem? Please describe.**
ref.listenSelf is now deprecated and Notifier.listenSelf should be used.

Can listenSelf be added to AsyncNotifier as well?

**Comment by rrousselGit** [comment]
I thought I added it. Dang it.
I'll add it.

**Comment by josh-burton** [comment]
> I thought I added it. Dang it. I'll add it.

thank you! 🙏
