### ISSUE TITLE
Lint-rule warning you when using AsyncValue.value inside a widget / build method

### ISSUE THREAD

**Issue by joachimbulow** [rrousselGit/riverpod#3799]
**Is your feature request related to a problem? Please describe.**
Not really, just something we have seen happen in production once or twice.
Essentially, you are trying to read a nullable `AsyncValue` value, with a fallback, but if the `AsyncValue` is in error state, you unintentionally throw the error e.g. in your build method.

**Describe the solution you'd like**
A lint rule in which you could specify that using e.g. `provider.value?.isEmpty ?? false`  is dangerous, and that you should prefer `provider.valueOrNull?.isEmpty ?? false` to avoid runtime errors.

**Describe alternatives you've considered**
I guess being more careful when reviewing code. The docs are pretty clear about this difference, but still it seems like a nice lint rule.

**Additional context**
N/A

**Comment by rrousselGit** [comment]
Rather than a lint rule, a breaking change is made in 3.0. `value` essentially becomes `valueOrNull`

**Comment by joachimbulow** [comment]
@rrousselGit 
We are using

```
flutter_riverpod: 3.0.0-dev.0
riverpod: 3.0.0-dev.0
riverpod_annotation: 3.0.0-dev.0
```

So, i suppose you mean it will be part of the official 3.0 release?

**Comment by rrousselGit** [comment]
The dev branch isn't up-to-date. I don't plan on updating the dev version for now.

But the current implementation of 3.0 already has an `AsyncValue.value` that doesnt throw.
