### ISSUE TITLE
FutureProvider | Lazy loading - Lazy error. Initial default values

### ISSUE THREAD

**Issue by EndersonPro** [rrousselGit/riverpod#3800]
**Is your feature request related to a problem? Please describe.**
Currently, I have created a FutureProvider which takes a couple of parameters. But I ran into the following case:

1. There is a button that will call this FutureProvider; however, the button has a "loading" property to disable it and show a small loading circle.
2. I tried to make a watch of the Provider to access the isLoading property. But for that, the watch method requires a ProviderListeable which is only returned when I call the future.

Example code with error:
```dart
Consumer(
  builder: (context, ref, _) {
    final doSomethingProvider = ref.watch(
      doSomethingServiceProvider(value1), // value1 is null
    );

    return CustomTextButton(
      color: CustomColor.cherry,
      loading: doSomethingProvider.isLoading,
      onPressed: () {},
      text: "Call method",
    );
  },
),
```

**Describe the solution you'd like**
The way I found to solve this was to create a stateful Provider. However, I was wondering if it was possible to do something like this:

```dart
final doSomethingProviderLoading = ref.watch(
    doSomethingServiceProvider.select(
      (defaultFutureProviderState) =>
          defaultFutureProviderState.isLoading,
    ), // Return default isLoading value = false
  );

final doSomethingProviderHasError = ref.watch(
  doSomethingServiceProvider.select(
    (defaultFutureProviderState) =>
        defaultFutureProviderState.hasError,
  ), // Return default hasError value = false
);

return CustomTextButton(
  color: CustomColor.cherry,
  loading: doSomethingProviderLoading,
  onPressed: () {
    // Call the FutureProvider with parameters
  },
  text: "Call method",
);
```

Do you think it would be useful?

**Comment by rrousselGit** [comment]
I don't quite understand what this is about.

Are you saying you want to know if a provider is loading without starting the operation if it isn't?

**Comment by EndersonPro** [comment]
> I don't quite understand what this is about.
> 
> Are you saying you want to know if a provider is loading without starting the operation if it isn't?

That's right, that's what I want to do.

**Comment by rrousselGit** [comment]
Nice. I'll close this then :)
