### ISSUE TITLE
NotifierProvider  causing error in UncontrolledProviderScope

### ISSUE THREAD

**Issue by alihassan143** [rrousselGit/riverpod#3802]
**Describe the bug**
E/flutter ( 6134): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_subscription@2452361930' has not been initialized.

**To Reproduce**
create any NotifierProvider
and call provider 
  container.read(myprovider);
in main method  

**Expected behavior**
Provide should be initialized like state notifier provider without any issue

**Comment by rrousselGit** [comment]
Please provide some code to reproduce. Notifiers are working fine for me.

**Comment by alihassan143** [comment]
That is provider code

**Comment by alihassan143** [comment]
` ref.onDispose(_subscription.cancel);`
that was causing the issue 
I want to listen to dispose and cancel subscription accordingly it better approach wo doing in build method

**Comment by rrousselGit** [comment]
Thanks, but I cannot run this. I need something I can run on my end.

**Comment by alihassan143** [comment]
```
@override
  SubscriptionModel build() {
    onInit();
    ref.onDispose(_subscription.cancel);
    return SubscriptionModel();
  }

```
the issue is with this code I want to cancel the stream when provider dispose is this better approach can you share your thought in that?
