### ISSUE TITLE
Notifier state is gone after app detached/sleeps

### ISSUE THREAD

**Issue by MarlonJD** [rrousselGit/riverpod#3808]
**Describe the bug**
I have an issue about the android app sleep/detached. After 15min, OS detaching flutter app, then I lost my notifier state/variables. I'm using pure Notifier<NotifierStateClass>
I have `UserModel` (ChangeNotifier), it shares user informations to `PostNotifierState` (Notifier), after sleep there is no UserState's `userId` and there is no `allPosts` in `PostNotifierState`, is there any solution for this? When I resumed app current page starts giving error, how can I recreate this wasted notifiers when I lost these notifiers? 

my notifiers: 
```
class AuthModel with ChangeNotifier {
    ...
}

final authNotifierProvider = ChangeNotifierProvider<AuthModel>(
  (ref) => AuthModel(),
);

// I'm using change notifier for go_router to easily manage user states

class SocialPostState {
    ... 
final List<Post?> allPosts;
    ...
}

class SocialPostNotifier extends Notifier<SocialPostState> {
    ....
    Future<void> getAllPosts()  async {
        ....
        userId = ref.watch(authNotifierProvider).userId;

       // fetch users posts
    }
}
```

I'm getting empty allPosts after app detached, how can I recreate notifier when it's gone?

**To Reproduce**
You can easily reproduce this with debug settings called "don't keep activities", activate this settings, then open app, go to home (android home), then go back to your app, your notifier variables will be gone. 

**Expected behavior**
It should recreate notifiers when data is gone

**Comment by rrousselGit** [comment]
Your app got killed by the OS, so any data stored in memory is no longer accessible.

If you want to keep the state even if the OS kills the app, you need to persist it somewhere in a datebase, and restore it on app start.

This isn't quite a bug in Riverpod and is how mobile apps work.

**Comment by MarlonJD** [comment]
> Your app got killed by the OS, so any data stored in memory is no longer accessible.
> 
> If you want to keep the state even if the OS kills the app, you need to persist it somewhere in a datebase, and restore it on app start.
> 
> This isn't quite a bug in Riverpod and is how mobile apps work.

No sir, please test it, it's a bug because it's becoming unusable buggy app when it's gone, I need how to initialize these notifiers again, I ask how can I trigger to initiate these again when it's destroyed?

**Comment by rrousselGit** [comment]
The whole app is destroyed. Your notifiers should be re-initializing from scratch. Even stateful widgets should be loosing their states here.

**Comment by MarlonJD** [comment]
How can I do this? I couldn't make re-initialize notifiers, I tried restart app when LifeCycle go back resumed from detached no luck. My riverpod `Notifier` getting data from with `ref.watch` from `AuthModel (ChangeNotifier)`.
I don't know but can be issue with `ChangeNotifier` to `Notifier`. Any ideas ?

**Comment by Trung15010802** [comment]
> How can I do this? I couldn't make re-initialize notifiers, I tried restart app when LifeCycle go back resumed from detached no luck (I couldn't make this works, and it's not right way to solve this issue), My riverpod `Notifier` getting data from with `ref.watch` from `AuthModel (ChangeNotifier)`. I don't know but can be issue with `ChangeNotifier` to `Notifier`. Any ideas ?

You should check `AppLifecycleListener`

**Comment by MarlonJD** [comment]
I tried restart the app when it's resumed after detached but I couldn't do this, I need to dispose and re-initialize notifier, but Notifier need ChangeNotifier's variable, if it's disposed and variable was gone, notifier should wait this. I don't know how can I do this

> > How can I do this? I couldn't make re-initialize notifiers, I tried restart app when LifeCycle go back resumed from detached no luck (I couldn't make this works, and it's not right way to solve this issue), My riverpod `Notifier` getting data from with `ref.watch` from `AuthModel (ChangeNotifier)`. I don't know but can be issue with `ChangeNotifier` to `Notifier`. Any ideas ?
> 
> You should check `AppLifecycleListener`

**Comment by Trung15010802** [comment]
> I tried restart the app when it's resumed after detached but I couldn't do this, I need to dispose and re-initialize notifier, but Notifier need ChangeNotifier's variable, if it's disposed and variable was gone, notifier should wait this. I don't know how can I do this
> 
> > > How can I do this? I couldn't make re-initialize notifiers, I tried restart app when LifeCycle go back resumed from detached no luck (I couldn't make this works, and it's not right way to solve this issue), My riverpod `Notifier` getting data from with `ref.watch` from `AuthModel (ChangeNotifier)`. I don't know but can be issue with `ChangeNotifier` to `Notifier`. Any ideas ?
> > 
> > You should check `AppLifecycleListener`
> 
> 

You can try ref.invalidate()
