### ISSUE TITLE
Consider making param type of widget to `StatefulWidget` in `ConsumerStatefulElement` constructor

### ISSUE THREAD

**Issue by tablet0ps** [rrousselGit/riverpod#3812]
**Is your feature request related to a problem? Please describe.**
There are some widgets such as some flutter widgets and widgets in external libraries which already extend `StatefulWidget`. As such there is no way to access `ref` in the lifecycle methods.

**Describe the solution you'd like**
 I read through the source [here](https://github.com/rrousselGit/riverpod/blob/master/packages/flutter_riverpod/lib/src/consumer.dart#L491) and if I understood it correctly I just need to override the `createElement` method of the `StatefulWidget` and return `ConsumerStatefulElement`. The only problem is that `ConsumerStatefulElement` constructor only allows a `ConsumerStatefulWidget` argument to be passed as widget and removing the constraint would make it work.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rrousselGit** [comment]
This constraint ensures the state is a ConsumerState.

If you want to extend ConsumerStatefulElement, why not also extend ConsumerStatefulWidget?

**Comment by tablet0ps** [comment]
> This constraint ensures the state is a ConsumerState.

From the code, I observed that the `ConsumerStatefulElement` class does not access `ref`, which is the only member added to `State<T>`. Is the constraint needed for someplace else?
https://github.com/rrousselGit/riverpod/blob/731e04876f4319ef9e782850a0f48e8ae9af37b2/packages/flutter_riverpod/lib/src/consumer.dart#L497-L501

> If you want to extend ConsumerStatefulElement, why not also extend ConsumerStatefulWidget?

I need to extend some widgets like `FormField` and add functionality of `ConsumerWidget` so that I can access `ref` inside builder. I have tried `extends FormField<T> implements ConsumerStatefulWidget` but I cannot get it to work as the `State` params are incompatible.

**Comment by rrousselGit** [comment]
> I need to extend some widgets like `FormField` and add functionality of `ConsumerWidget` so that I can access `ref` inside builder. I have tried `extends FormField<T> implements ConsumerStatefulWidget` but I cannot get it to work as the `State` types are incompatible.

Use composition instead of inheritance.

Make a new Form widget that extends ConsumerWidget and take as parameter all the FormField parameters, and have it return a FormField.

No need for this widget to be stateful either.

**Comment by tablet0ps** [comment]
I need to use `ref.watch(providerFamily(fieldState.value))` and `ref.listen(fieldState.value)` so I need to call it inside the builder method. Can I call these methods without adding additional `Consumer` inside the builder? I want to reduce indentation and boilerplate as much as I can. If possible, can you consider making a mixin which contains all the logic for `ConsumerStatefulElement`?

**Comment by rrousselGit** [comment]
I'd rather not.

I'd suggest doing:

```dart
class MyFormField<T> extends ConsumerWidget {
   MyFormField({this.param):
  final SomeParam param;
  @override
  Widget build(context, ref) {
     ref.watch(whatever);
     return FormField<T>(param: param);
  }
}
```

**Comment by tablet0ps** [comment]
> I need to use `ref.watch(providerFamily(fieldState.value))` and `ref.listen(fieldState.value)` so I need to call it inside the builder method. Can I call these methods without adding additional `Consumer` inside the builder? I want to reduce indentation and boilerplate as much as I can. If possible, can you consider making a mixin which contains all the logic for `ConsumerStatefulElement` just like `HookElement`?

Figured out a way to reduce boilerplate using composition. Thanks
