### ISSUE TITLE
How to cache data for a specific time on riverpod 2.6.1?

### ISSUE THREAD

**Issue by lunxinfeng** [rrousselGit/riverpod#3817]
### Discussed in https://github.com/rrousselGit/riverpod/discussions/3811

<div type='discussions-op-text'>

<sup>Originally posted by **lunxinfeng** October 25, 2024</sup>
this is official advice:
```dart 
extension CacheForExtension on AutoDisposeRef<Object?> {
  /// Keeps the provider alive for [duration].
  void cacheFor(Duration duration) {
    // Immediately prevent the state from getting destroyed.
    final link = keepAlive();
    // After duration has elapsed, we re-enable automatic disposal.
   Timer(duration, link.close);
  }
}


@riverpod
Future<Object> example(ExampleRef ref) async {
  ref.cacheFor(const Duration(minutes: 5));
  return http.get(Uri.https('example.com'));
}
```
but it will also cache when error, so do some change:
```dart
@riverpod
Future<Object> example(ExampleRef ref) async {
  var data = await http.get(Uri.https('example.com'));
  ref.cacheFor(const Duration(minutes: 5));
  return data;
}
```
but it cannot cache when only `ref.read`(no watch), so do some change like this:
```dart
extension CacheForExtension on AutoDisposeRef<Object?> {
  void cacheFor(Duration duration, {bool disposeOnError = true}) {
    final link = keepAlive();
    Timer(duration, link.close);

    if (disposeOnError) {
      listenSelf(
        (previous, next) {
          if (next is AsyncValue && next.hasError) {
            invalidateSelf();
          }
        },
        onError: (error, stackTrace) {
          invalidateSelf();
        },
      );
    }
  }
}
```
but when riverpod update to 2.6.1, `ref.listenSelf` is deprecated, here is no Notifier too. 

How do I achieve the above functionality， cache data for a specified time,  no cache when error, when only `ref.read` ? 

Hope to answer, thks</div>

**Comment by sabin26** [comment]
1. Try converting the example provider to class based AsyncNotifier

2. Use the extension on AsyncNotifier (replace AutoDisposeRef<Object?>).

3. Finally modify the extension implementation to use ref (eg: change keepAlive() to ref.keepAlive())

**Comment by lunxinfeng** [comment]
> 1. Try converting the example provider to class based AsyncNotifier
> 2. Use the extension on AsyncNotifier (replace AutoDisposeRef<Object?>).
> 3. Finally modify the extension implementation to use ref (eg: change keepAlive() to ref.keepAlive())

Yes, this method is theoretically possible. I will close this issue first. But it seems that using `AsyncNotifier` is a bit heavy for a simple http request? If there is another way, also welcome to answer

**Comment by lunxinfeng** [comment]
> 1. Try converting the example provider to class based AsyncNotifier
> 2. Use the extension on AsyncNotifier (replace AutoDisposeRef<Object?>).
> 3. Finally modify the extension implementation to use ref (eg: change keepAlive() to ref.keepAlive())

With riverpod_gen,  should extension `AsyncNotifierBase` or `BuildlessAutoDisposeAsyncNotifier ` , but it is `@internal`. 

Maybe the generated code should extend `AutoDisposeAsyncNotifier` ?

xx.g.dart: 
```dart
abstract class _$GetHeatMap extends BuildlessAutoDisposeAsyncNotifier
```
