### ISSUE TITLE
Namespacing generated providers

### ISSUE THREAD

**Issue by kerridge** [rrousselGit/riverpod#3828]
I am slowly moving my codebases towards generated providers, especially with the benefit of generic provider definitions and the looming nature of static metaprogramming + riverpod 3. One thing I have found that is frustrating to lose between the generated and custom definitions, is the ability to namespace providers that belong to a specific class. 

For example, I used to define all of my related providers on the abstract interface of a class I am registering with riverpod.

```dart
abstract class MenuRepository extends StateNotifier<Menu> {
  MenuRepository(super.state);

  Future<void> getMenu(String locationId);

  static final stateProvider = StateNotifierProvider.autoDispose<MenuRepository, Menu>(
    (ref) {
      return ConcreteMenuRepository(ref);
    },
    name: "MenuStateNotifierProvider",
  );
}
```

Then I could simply reference them under the namespace of `MenuRepository`. This is a huge win for large projects using riverpod for literally every part of their architecture like I am, and it makes referencing and definitions a lot more concise. 

Ideally, I would like to see some way of namspacing providers like this available in riverpod generator. Even if it meant defining a standalone class for it (not an interface with other members).

```dart
abstract class MenuRepositoryProviders {
  MenuRepositoryProviders();

  @riverpod
  static MenuRepository menuRepository(AutoDisposeRef ref) => ConcreteMenuRepository(ref);
}
```

Is there any way to achieve this behaviour with the current generator? Or do you have a syntactic solution for large-scale projects to be able to "group" related providers under a specific namespace? 

Thanks.

**Comment by rrousselGit** [comment]
This is not technically feasible.    
Code-generators cannot add static members to classes. And Dart doesn't have static extensions. So there's no mean for the generator to add that `YouNamespace.yourProvider`.


Macros will change that though, but that's for the future. It is planned that once we have macros, this will be implemented. But as it is, I cannot do anything :)
