### ISSUE TITLE
Ref.listenSelf replacement not available for StateNotifier 

### ISSUE THREAD

**Issue by navaronbracke** [rrousselGit/riverpod#3846]
**Describe the bug**
`listenSelf` is deprecated on `Ref`, but `StateNotifier` does not have access to the replacement.

Error message:
```
'listenSelf' is deprecated and shouldn't be used. Will be removed in 3.0. Use Notifier.listenSelf instead.
Try replacing the use of the deprecated member with the replacement.
```

**To Reproduce**

```dart
class LocaleNotifier extends StateNotifier<String?> {
  LocaleNotifier(Ref<String?> ref) : super('en') {
      ref.listenSelf((_,String? locale) { // LINT
        // ...
      });
  }
}
```

**Expected behavior**
`listenSelf` should be available on all types of `Notifier` subclasses. 

I'm using `flutter_riverpod: 2.6.1`

**Comment by rrousselGit** [comment]
StateNotifier isn't a Notifier subclass.

It's coming from a separate package independent from Riverpod, and is considered kind of deprecated.

I have no plan to add listenSelf there.

**Comment by navaronbracke** [comment]
@rrousselGit Then how are we supposed to migrate the use of `listenSelf` and/or the StateNotifier ?

**Comment by rrousselGit** [comment]
You should migrate to use Notifier
