### ISSUE TITLE
Get provider value without Ref object

### ISSUE THREAD

**Issue by EvgrafovBTW** [rrousselGit/riverpod#3849]
There is no way of using provider value without Ref instance. This could be intended, I need clarification of that.
**Case:**
For example, I have `userProvider` which manages current state of a user. Depending on current user state i want to route user either to _profile screen_ or _auth sreen_.

Example of routing logic with `AutoRoute` gurads:
```
class AuthGuardRoute extends AutoRouteGuard {
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {

    final user = /* insert current user state here */;

    if (user == null) {
      router.push(const AuthRoute());
      return;
    }

    resolver.next(true);
  }
}
```
But there is no way to get current user state directly from riverpod.

**Describe the solution you'd like**
Some form of snapshot of `ProviderContainer`. 
Something close to `intl` package: 
`S.of(context)` with counterpart `S.current`

The idea is something sort of: `ProviderContainer.current.read(...)`

**Describe alternatives you've considered**
Having some sort of singleton or global stream with always updating `User` object. This solution doesn't use `Riverpod` entirely.

**Comment by rrousselGit** [comment]
> This could be intended, I need clarification of that.

It is.

Riverpod's state isn't global. And making it global cause negatively impact maintenability, since the relationship between providers becomes all muddied

If your class doesn't have a Ref, give it one.

Either:
- wrap your navigation logic in a Consumer:
  ```dart
  class Guard {
    Guard(this.ref);
    final WidgetRef ref;
  }
  ...
  Consumer(builder: (context, ref, _) {
    Guard(ref); // TODO pass it to your router somehow
  })
  ```
- extract the instance of your class inside a Provider
  ```dart
  final guardProvider = Provider<Guard>((ref) => Guard(ref));
    ...
  Consumer(builder: (context, ref, _) {
    final guard = ref.watch(guardProvider); // TODO pass it to your router somehow
  })
  ```

If you don't have a ref, you should obtain one :)
