### ISSUE TITLE
need to make the _StateNotifierProviderBase public.

### ISSUE THREAD

**Issue by me-zo** [rrousselGit/riverpod#3850]
**Is your feature request related to a problem? Please describe.**

the request is related to  constriction problem. i wanted to check if a stateNotifierProvider is auto disposable or not but the only common class i had access to was ProviderBase but since it didn't have a notifier I'm having to cast to either AutoDisposeStateNotifierProvider or StateNotifierProvider. 

**Describe the solution you'd like**

Making the class _StateNotifierProviderBase public would allow me to get rid of the casting and end up simplifying the code.

I noticed many classes have autoDisposable variants so maybe this same thing can happen for those as well.

**Describe alternatives you've considered**
as mentioned above i tried casting to either AutoDisposeStateNotifierProvider or StateNotifierProvider.

**Comment by rrousselGit** [comment]
To begin with, AutoDispose variants are going away and StateNotifier is discouraged.
You also shouldn't rely on the type of a provider.

I don't think that's a reasonable request.

Do you mind explaining more about why you need that?

**Comment by me-zo** [comment]
We were trying to abstract a layer over state notifiers. Can you reference a documentation page where it says state notifiers are discouraged because we just migrated from change notifiers to them. Also about auto dispose variants whats going to replace them please point me there as well. I'm thinking we could be going about this the wrong way.

**Comment by rrousselGit** [comment]
https://riverpod.dev/docs/migration/from_state_notifier
https://github.com/rrousselGit/riverpod/issues/2576

**Comment by me-zo** [comment]
Hi @rrousselGit i had a look through the docs and i see what you meant by 
> StateNotifier is discouraged

The migration is basically towards code generation using the `@riverpod` annotation. the thing is we can't use code generation in our abstraction. do you think state notifiers are gonna keep being supported in the future or we're better off sticking with Provider if we want to keep our abstraction. 

Lastly, the migration to riverpod was because we thought there are performance improvements over provider. it seems we were misinformed and riverpod provides simplifications of work flow and coding practices. is that a correct assumption?

**Comment by rrousselGit** [comment]
Use Notifier regardless. Not StateNotifier

**Comment by me-zo** [comment]
sounds good, is it possible to remove `@internal` annotation from `NotifierBase` so we can check if a notifier is disposable or not?

**Comment by rrousselGit** [comment]
Not before 3.0
It's on its way
