### ISSUE TITLE
can not reach https://riverpod.dev/ page

### ISSUE THREAD

**Issue by indratrisnar** [rrousselGit/riverpod#3854]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
It works for me. Sounds like an issue on your end

**Comment by rrousselGit** [comment]
Closing as the site seems to be working fine
