### ISSUE TITLE
Support import aliases

### ISSUE THREAD

**Issue by Tulleb** [rrousselGit/riverpod#3856]
Are we sure #2777 is now supported?
I am still facing the issue but I can't reopen the ticket myself.

I've linked my [current podspec](https://github.com/rrousselGit/riverpod/issues/2777#issuecomment-2517666755) within the other issue. Maybe we could close this ticket and reopen the other one instead?

**Comment by rrousselGit** [comment]
In any case, if you do not give me some code to reproduce your issue, there's nothing I can do.

**Comment by rrousselGit** [comment]
Without any reproduction, I'll close this

**Comment by bgintzairspace** [comment]
@rrousselGit are you able to give an example of how it is supported?  I am still unable to use an alias, but maybe I am doing it wrong?

Thanks!
