### ISSUE TITLE
Enable providers parent classes for usage across app not internally

### ISSUE THREAD

**Issue by oldHarvester** [rrousselGit/riverpod#3874]
Remi Rousselet, please make the parent classes of providers public so that we can use them and create our own components and custom providers. This is something we are really missing. Classes such as AsyncNotifierBase, AutoDisposeAsyncNotifierProviderImpl, etc.

**Comment by rrousselGit** [comment]
Those are voluntarily not public. I have no plan to expose a way to make custom providers, as this would heavily restrict the evolution of Riverpod. That is because any new feature likely would mean a breaking change for folks who make custom providers.


Instead I'd suggest creating an issue explaining what you think is missing in Riverpod. We can then discuss how to implement those features without having to create custom providers.   
Riverpod is fairly flexible. You should be able to extend its featureset without having to create custom providers.

**Comment by oldHarvester** [comment]
Please take a look at this code. I created an extension that checks for errors in the provider before extracting data from it, because if an error has already occurred, it will keep returning it. However, since I don't have access to AutoDisposeAsyncNotifierProviderImpl, I couldn't make it more elegant, and as a result, I ended up with repetitions.

```dart
import 'package:flutter_riverpod/flutter_riverpod.dart';

extension RefExtension on Ref {
  Future<T> syncFutureProvider<T>(FutureProvider<T> provider) {
    if (exists(provider) && read(provider).hasError) {
      invalidate(provider);
    }
    return provider.future.read(container);
  }

  Future<T> syncAutoDisposeFutureProvider<T>(
      AsyncNotifierProvider<dynamic, T> provider) async {
    if (exists(provider) && read(provider).hasError) {
      invalidate(provider);
    }
    return provider.future.read(container);
  }

  Future<T> syncAsyncProvider<T>(
      AsyncNotifierProvider<dynamic, T> provider) async {
    if (exists(provider) && read(provider).hasError) {
      invalidate(provider);
    }
    return provider.future.read(container);
  }

  Future<T> syncAutoDisposeAsyncProvider<T>(
      AutoDisposeAsyncNotifierProvider<dynamic, T> provider) async {
    if (exists(provider) && read(provider).hasError) {
      invalidate(provider);
    }
    return provider.future.read(container);
  }

  Future<T> syncAutoDisposeAsyncProviderFamily<T, Z>(
      AutoDisposeAsyncNotifierProviderFamily<dynamic, T, Z> providerFamily,
      Z arg) async {
    final provider = providerFamily(arg);
    if (exists(provider) && read(provider).hasError) {
      invalidate(provider);
    }
    return provider.future.read(container);
  }

  Future<T> syncAsyncProviderFamily<T, Z>(
    AsyncNotifierProviderFamily<dynamic, T, Z> providerFamily,
    Z arg,
  ) async {
    final provider = providerFamily(arg);
    if (exists(provider) && read(provider).hasError) {
      invalidate(provider);
    }
    return provider.future.read(container);
  }
}
```

**Comment by oldHarvester** [comment]
Thank you for your response, we will be waiting.
