### ISSUE TITLE
deprecated_member_use ChangeNotifierProvider ref type

### ISSUE THREAD

**Issue by stephane-archer** [rrousselGit/riverpod#3893]
``` Dart
final lutPreviewImagesProvider =
    ChangeNotifierProvider<LutPreviewImagesChangeNotifier>((ref) {
  var previewGeneratorChangeNotifier = ref.watch(previewGeneratorProvider);
  var lutPreviewImagesChangeNotifier = LutPreviewImagesChangeNotifier(
      previewGeneratorChangeNotifier.previewGenerator);

  _initializeLutPreviewImages(ref, lutPreviewImagesChangeNotifier);

  return lutPreviewImagesChangeNotifier;
});

Future<void> _initializeLutPreviewImages(
   // ignore: deprecated_member_use
   ChangeNotifierProviderRef<LutPreviewImagesChangeNotifier>  ref, // this type is deprecated but exposed by ChangeNotifierProvider
  LutPreviewImagesChangeNotifier lutPreviewImagesChangeNotifier,
) async {
    ...
    }
}
```

**Comment by rrousselGit** [comment]
Not a bug. Use Ref

**Comment by stephane-archer** [comment]
@rrousselGit ref has his type deprecated, I'm surprised his type wasn't WidgetRef

**Comment by stephane-archer** [comment]
@rrousselGit i'm really sorry, but I can't understand your explanation 

ref is given to me by ChangeNotifierProvider<LutPreviewImagesChangeNotifier> I don't see how I can control this type.

How would you modify my code to be correct?

From my understanding ChangeNotifierProvider is exposing a deprecated type but I probably don't use ChangeNotifierProvider correctly.

Could you clarify how to use it correctly with some code? I'm missing something

**Comment by stephane-archer** [comment]
ref type is deprecated
<img width="1440" alt="Screenshot 2024-12-26 at 22 47 15" src="https://github.com/user-attachments/assets/4e5891c5-e8c7-47cd-906a-fc0c84b670ef" />

**Comment by Luckey-Elijah** [comment]
```diff
- ChangeNotifierProviderRef<LutPreviewImagesChangeNotifier> ref,
+ Ref ref,
```

**Comment by stephane-archer** [comment]
@Luckey-Elijah thanks! It works perfectly. 
Why is ChangeNotifierProvider not directly exposing ref of type Ref instead of the deprecated type?

**Comment by rrousselGit** [comment]
That'd be a breaking change, not a depreciation
