### ISSUE TITLE
How do you display an error message to the users from a `FutureProvider` or `ChangeNotifierProvider`?

### ISSUE THREAD

**Issue by stephane-archer** [rrousselGit/riverpod#3894]
looking at this page of the documentation https://riverpod.dev/docs/essentials/combining_requests

```
 final location = await ref.watch(locationProvider.future);
```
when combining requests, some requests can fail and throw an exception. by adding a try-catch around this line you can react accordingly but if you want to display a message to your users with a snacbar message for example. there is no sign of build context. How do you display an error message to the users from a `FutureProvider` or `ChangeNotifierProvider`?

**Comment by snapsl** [comment]
Read the docs😉
https://riverpod.dev/docs/essentials/side_effects
https://riverpod.dev/search?q=snackbar

**Comment by stephane-archer** [comment]
@snapsl do you see an error or a better way to do this?

``` Dart
  Widget build(BuildContext context, WidgetRef ref) {
    ref.listen(
      locationProvider,
      (prev, next) {
        if (!next.isLoading && next.hasError) {
          Object? error = next.error;
          ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Location error! : $error')),
      );
        }
      },
    );
```

**Comment by rrousselGit** [comment]
Looks about right

Overall, showing snackbars isn't the responsibility of providers. Do that in widgets.

As such, you don't need a try/catch in your provider
