### ISSUE TITLE
Refresh combined FutureProvider

### ISSUE THREAD

**Issue by stefangaller** [rrousselGit/riverpod#698]
Assuming I have a `FutureProvider` combining two other `FutureProvider`s.
Both `futureProvider1` and `futureProvider2` might throw an exception.

```
final futureProvider = FutureProvider<int>((ref) async {
  final future1 = await ref.watch(futureProvider1.future);
  final future2 = await ref.watch(futureProvider2.future);
  
  return future1 + future2;
});
```

Is there a convenient way to refresh the provider which causes the error?

`context.refresh(futureProvider)` would – of course – just refresh the combined `FutureProvider`, but not its dependencies.

The UI that uses the `futureProvider` does not know of `futureProvider1` and `futureProvider2`, so it would be a bit awkward to having to refresh one of those.

**Comment by rrousselGit** [comment]
A pattern for this would be to have all the providers you'd want to be refreshed to "watch" a common provider:

```dart
final myGroup = Provider<void>((ref) {});

final futureProvider1= FutureProvider((ref) {
  ref.watch(myGroup);
  ...
});
final futureProvider2= FutureProvider((ref) {
  ref.watch(myGroup);
  ...
});

...

ref.refresh(myGroup) // will refresh futureProvider1 and futureProvider2
```

**Comment by stefangaller** [comment]
That's an interesting approach. Thank you for your input :)

**Comment by hpoul** [comment]
How about adding a `onRefresh` event, so a provider could itself call `refresh` on its dependencies? I think It's weird when the user of a provider has to call `refresh` on a different provider? 🤔

**Comment by rrousselGit** [comment]
I think that's a fairly minor issue.

**Comment by hpoul** [comment]
I have another use case where something like a `onRefresh` might be useful (imho) - I am using `flutter_cache_manager` to cache network requests, it would be nice that when it is called with `ref.refresh(myProvider);` the provider can clear the network cache, so next time a new network request is sent.. other approaches would be to either add a parameter to the `onDispose` whether it's disposed due to a `refresh`..  or add a property to the `ref` which is passed into the provider initialisation whether it a "refresh" or a "normal" create.. would you accept a PR for any of those variants? 😅

i'm pretty sure I don't want the call side of my providers to know which http requests have to be cleared for `ref.refresh()`.

**Comment by rrousselGit** [comment]
Feel free to make a PR

**Comment by jarekb123** [comment]
I came up with idea to use `AsyncNotifier` for refreshable combined `FutureProvider`s.

I extended `AsyncNotifier` with async `refresh` method:

```dart
abstract class RefreshableAsyncNotifier<T> extends AsyncNotifier<T> {
  RefreshableAsyncNotifier();

  Future<void> refresh();
}
```

Example:

```dart
class CombinedFuturesNotifier
    extends RefreshableAsyncNotifier<FinanceOverview> {
  @override
  FutureOr<FinanceOverview> build() async {
    final result1 = await ref.watch(future1Provider.future);
    final result2 = await ref.watch(future2Provider.future);

    return FinanceOverview(
      result1: plafond,
      result2: _shouldShowResult2(result1) ? result2 : null,
    );
  }

  @override
  Future<void> refresh() async {
    await ref.refresh(future1Provider.future);
    await ref.refresh(future2Provider.future);
  }
}
```

To trigger refresh, eg. using `RefreshIndicator`:
```dart
   final result = ref.watch(financeOverviewProvider);

    return RefreshIndicator(
      onRefresh: () => ref.read(financeOverviewProvider.notifier).refresh(),
      child: result.when(
        skipLoadingOnReload: true,
// ... rest of the widget
```

**Comment by rrousselGit** [comment]
AsyncNotifier solves this.
It's a FutureProvider where you can add custom methods. You can therefore do:


```dart
final futureProvider = AsyncNotifierProvider<MyNotifier, int>(MyNotifier.new);

class MyNotifier extends AsyncNotifier<int> {
  @override
  Future<int> build() async {
    final future1 = await ref.watch(futureProvider1.future);
    final future2 = await ref.watch(futureProvider2.future);
  
    return future1 + future2;
  }

  Future<int> refresh() {
    ref.invalidate(futureProvider1);
    ref.invalidate(futureProvider2);
    return future;
  }
}
```

Used as `ref.read(futureProvider.notifier).refresh()`
