### ISSUE TITLE
Surface better errors in the migration tool

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/riverpod#704]
Just want to have this issue as a reminder that I should log in the migration tooling when a file fails to parse or fails to migrate, along with a link to a migration guide / changelog for the version change in case the tool errors out on a file and the user has to do a manual migration for that file. The link will be helpful even in the absence of errors because some changes do not have automatic migrations anyways.

**Comment by TimWhiting** [comment]
@rrousselGit 
I'd like to do this before you release the 1.0.0 of riverpod_cli.

**Comment by rrousselGit** [comment]
Why is the migration guide a requirement?

**Comment by TimWhiting** [comment]
Just need a valid link to redirect people to when errors occur with the tool and they have to do a manual migration on specific files or for unsupported migrations of the low level apis.

**Comment by rrousselGit** [comment]
You can expect the migration URL to be `https://riverpod.dev/docs/migration/0.14.0_to_1.0.0`

**Comment by rrousselGit** [comment]
I'll close this. I have no plan to fix the remaining bugs for the migration tool as it's been quite a while now since the breaking change happened.
