### ISSUE TITLE
State of DevTools for Riverpod

### ISSUE THREAD

**Issue by ebelevics** [rrousselGit/riverpod#798]
Right just before migrating from Bloc library to Riverpod, I found that Bloc which dependent to Provider package came with amazing tool in DevTools - separate Tab with state-inspector. I thought this was a phenomenal idea, to make better usage for DevTools in general. 

Unfortunately Riverpod doesn't have this tab 'yet', and only way how I personally manage to get information about state is by using print and RiverpodObserver, but it might fludge console really fast and not always all object have toString() implemented.
At the moment in DevTools it's hard to track state values in WidgetTree, and would love to see it implemented for Riverpod aswell.

When is it planned to be released? Maybe there are some workarounds how I can achieve it now? If not then I'll continue to use print() or inspect() methods.

**Comment by harkairt** [comment]
May I ask what is the priority of the aformentioned devtools tab or the "a full-blown state-inspector" which is in progress?
My problem is that I don't even see the providers in the devtools below the `ProviderScope` as it is depicted in riverpod.dev

![image](https://user-images.githubusercontent.com/32367206/160928880-62f8179c-ec31-4eb8-b25f-880bcdc4547b.png)

**Comment by rrousselGit** [comment]
I'm currently working on a linter

After that I'll complete the devtool

**Comment by rrousselGit** [comment]
Closing in favor of #1033 and #1039
