### ISSUE TITLE
Provide a warning about altering the state of the provider in ref.listen(provider, (_){...})

### ISSUE THREAD

**Issue by navaronbracke** [rrousselGit/riverpod#860]
When setting up a provider listener using `ref.listen(provider, (_){...})` and you _modify the state_ of the provider that is listened to, you are presented with a rather cryptic stacktrace. (My terminal doesn't even show it entirely)

It took me a while to figure out what caused it. The cause itself makes sense, it's just that the cryptic stacktrace didn't help.
Perhaps the documentation of `ref.listen()` could specifically mention that altering the state of the provider should not be done in the listener.

If a lint rule is a possibility that would be nice too.

**Comment by rrousselGit** [comment]
Hello

I don't understand what this is referring to. Could you clarify what error you encountered, in which situation (with a reproducible example)?

**Comment by TimWhiting** [comment]
I think this was already answered, and @navaronbracke just wanted us to put something in the docs about it.

The situation was something like this:

```dart
final provider = StateProvider((ref) => '');

final otherProvider = Provider((ref) {
   ref.listen<StateController<String>>(provider, (controller) {
      // Causes infinite loop or weird stacktrace 
      controller.state = 'some random string';
   });
});
```

**Comment by navaronbracke** [comment]
@TimWhiting That's exactly what I meant.

**Comment by rrousselGit** [comment]
You now get a stackoverflow and the stacktrace points to the `state =`. This should fix the problem
