### ISSUE TITLE
Refresh Family Provider

### ISSUE THREAD

**Issue by marinkobabic** [rrousselGit/riverpod#879]
I'm now working since a while with river_pod framework. I enjoy it fully and thanks for such a great framework. I'm trying always to build a loose coupled software. That's where I'm having an issue with refreshing state of the Family Provider. Here an example:

**Context:**
I have a list of bank transactions. User is able to configure the size of such a page. So in this case family provider is used to pass in the page size as parameter. All works like expected so far.
User can click on such a transaction and assign the category like food, hobby etc. Now I'm in the analytics part of the business. When the changes have been completed by the user, then I would like to refresh the transaction page. 

**Problem:**

1. In order to refresh the state of the transactions family provider I need now to put all this information together and pass them as parameter when executing context.refresh(transactionsFamilyProvider(xy)) In this simple example it's just the page size.
2. Analytics has to understand that transactions are using paging. This causes additional dependencies. So I'm delegating the refresh call to a function in transactions to not take care about such details.

**Describe the solution you'd like**
I would like to refresh all the states maintained by this provider. Ideally I would like to call context.refreshFamily(transactionsFamilyProvider) without passing in anything and the job is done.  In the paging example it may look simple, but there are more complex scenarios where the family parameter is a more complex object.

**Describe alternatives you've considered**
transactionsFamilyProvider uses transactionsRepository and is doing a watch on it. By doing refresh on transactionsRepository does not help at all. The code inside of the family provider is executed, but the state is not refreshed. Watching a state in a family provider should be threaded as an anti-pattern? But maybe I have here a wrong understanding of how the stuff is meant to be used.

Many thanks for your suggestions in advance.

**Comment by rrousselGit** [comment]
A temporary workaround would be:

```dart
final myGroup = Provider((_) {});

final family = Provider.family((ref, _) {
  ref.watch(myGroup); // bind the family to myGroup
})

ref.refresh(myGroup)
```

**Comment by marinkobabic** [comment]
Thanks a lot. Will test the proposal today. 

I just had another idea. What do you think about the ability to pass a string into the refresh method which is the name of the provider? So during the declaration of a provider we can define a name and using the name for the refresh.

Another option would be the ability to loop through the providers and then use them as a parameter for the refresh.

**Comment by rrousselGit** [comment]
I don't want to push strings, as that wouldn't be typed

**Comment by marinkobabic** [comment]
```dart
/// Builds a [AutoDisposeFutureProviderFamily].
class AutoDisposeFutureProviderFamilyBuilder {
  /// Builds a [AutoDisposeFutureProviderFamily].
  const AutoDisposeFutureProviderFamilyBuilder();

  /// {@macro riverpod.family}
  AutoDisposeFutureProviderFamily<T, Param> call<T, Param>(
    Future<T> Function(AutoDisposeProviderReference ref, Param param) create, {
    String? name,
  }) {
    return AutoDisposeFutureProviderFamily(create, name: name);
  }
}
```
I'm talking about the name here (String? name). The same name could be used for the refresh. It's a string. I was not talking about passing the type of the provider as string.

**Comment by rrousselGit** [comment]
Yes, but I don't want to rely on this property.

**Comment by Tienisto** [comment]
> A temporary workaround would be:
> 
> ```dart
> final myGroup = Provider((_) {});
> 
> final family = Provider.family((ref, _) {
>   ref.watch(myGroup); // bind the family to myGroup
> })
> 
> ref.refresh(myGroup)
> ```

I had to return a different object to make this work:
```dart
final myGroup = Provider((_) => DateTime.now());

final family = Provider.family((ref, _) {
  ref.watch(myGroup); // bind the family to myGroup
})

ref.refresh(myGroup)
```

**Comment by rrousselGit** [comment]
I don't plan on adding the ability to "refresh" a family, as it's unclear what the return value should be.

But I plan on adding the ability to "invalidate" a family (cf https://github.com/rrousselGit/riverpod/issues/1517).
This should cover most use cases. So I'll close this in favour of that other issue
