### ISSUE TITLE
What does ref.listen onError do?

### ISSUE THREAD

**Issue by mrheio** [rrousselGit/riverpod#914]
I've seen that in the 1.0.0 release the ProviderListener was replaced with ref.listen.

This new method has a named argument called onError, but for me it's not clear what it does, especially if it is used with AsyncValue. 

I am thinking that for side-effects I should use the listener function (prev, next) {...}, but if I want to display some error message on the same page, in a snackbar, for example, should I also do it here, or in the onError?

**Comment by rrousselGit** [comment]
That "onError" is for cases where you're _not_ using AsyncValue. Such as a `Provider` that threw

**Comment by DrgOv** [comment]
@rrousselGit I want to ask you some things about how to work with riverpod. Where can we chat?

**Comment by Agondev** [comment]
@DrgOv 

Discussions (https://github.com/rrousselGit/river_pod/discussions)

Discord:
Riverpod (https://discord.gg/rbEj2dnuBn)
FlutterDev (https://discord.gg/k57kGPh8GE).

Discord's where the community is most active.
