### ISSUE TITLE
Right place for ref.listen() in ConsumerStatefulWidget

### ISSUE THREAD

**Issue by topperspal** [rrousselGit/riverpod#915]
`This time, the "ref" isn't passed as parameter of the build method, but is rather a property of the ConsumerState object:`

But when I use ref.listen() in initState() it throws the following error :-

`ref.listen can only be used in build method of ConsumerState`

The question is that if I cannot use ref.listen() in init state then where I should place it in the class.

**Comment by daniellampl** [comment]
Place it at the beginning of the build method. It won't force your widget to rebuild if the provider updates its state. It just executes the callback you pass into it.

**Comment by topperspal** [comment]
It add a new listener each time when build metod is called.

**Comment by daniellampl** [comment]
`ConsumerWidget` actually takes care of closing previously opened provider listening subscriptions before it subscribes to them again. So when the widget rebuilds, the subscriptions get closed and resubscribed automatically.

@rrousselGit this should probably get mentioned in the documentation. What do you think?

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/riverpod/issues/1370 and https://github.com/rrousselGit/riverpod/issues/1034. The former should allow initState to listen to providers, while the later will catch bugs where `ref.listen` is misused.

**Comment by ciriousjoker** [comment]
Ah ok, so I guess for simple use cases like this, `listenManual` is the way to go. Unsubscribing & recreating the subscription seems like a waste to me even if it's done automatically.
