### ISSUE TITLE
Please do a coming back from app in background or browser refresh example

### ISSUE THREAD

**Issue by nyck33** [rrousselGit/riverpod#948]
For me the "no automatic saving of app state" is the toughest part about using Riverpod so far.  Everything else is so awesome.  
Can you do an example for this.
Right now it's trial and error whether I call a method where I do something like `ref.read(userProvider.notifer).initializeAppState(currentState)` where currentState is either user login info or state saved to shared preferences being loaded, in either `initState()` or `didChangeDependencies()` .  For one app it works only when I put it in `initState()`.  In my other app it only works when I put it in `didChangeDependencies()`, both being in the top level `myApp` after `runapp(ProviderScope(myApp));`
I feel like I am using Riverpod correctly so it's a mystery to me why one works sometimes and other times I have to try the other way.

**Comment by rrousselGit** [comment]
I think this can be closed in favor of https://github.com/rrousselGit/riverpod/issues/1032 and #1038
