### ISSUE TITLE
Improve documentation for autoDispose

### ISSUE THREAD

**Issue by venkatd** [rrousselGit/riverpod#96]
**Describe what scenario you think is uncovered by the existing examples/articles**

The autoDispose section of the article says the following:
> To tell Riverpod to destroy the state of a provider when it is no-longer used, simply append .autoDispose to your provider:

I was troubleshooting an app bug related to auto-dispose. When a user was logging out, some of the state for the logged in user wasn't getting destroyed.

It turned out that another provider was depending on it using `ref.watch` which was preventing the state from being destroyed.

It was unclear to me what "no-longer used means". I think clarifying how riverpod decides what is still in use could help. Maybe with some examples of gotchas.

**Describe why existing examples/articles do not cover this case**
I think the examples do cover autoDispose, but because there are some gotchas and details on provider lifecycle to be aware of. 

**Additional context**

I would like to confirm the following is the case:
- Something is used if it's being referenced by a widget with "useProvider" OR another provider is in use with `read` or `watch`
- If something is disposable, dispose will be called on it. (Would be good to in understand what cases river_pod will dispose something for you without manually calling dispose
- `ref.onDispose` is *additional* cleanup to whatever river_pod does. (It doesn't override river_pod dispose)

The troubleshooting steps I wish I had known when autoDispose isn't triggering onDispose
- Check that the provider isn't being referenced in any widgets
- Check that other active providers aren't referencing it

Another idea would be to list all dependencies (widgets+providers) that a provider currently depends on in the DevTools inspector so we can easily see why something is still alive when it should have been disposed.

I can help out with documenting this once my understanding of autoDispose improves.

**Comment by rrousselGit** [comment]
Agreed

I don't think documentation can help much here. What we are looking is for devtools instead. 

A devtool is planned and is my next step after making a few more examples.
It would include this scenario. 


But in the short term, the 0.7.0 version will have some improvements about common mistakes around ref.watch
You can see the changelog/doc for this

**Comment by venkatd** [comment]
Ok awesome! Feel free to mark this as closed then.

The main use cases for me are:

- What depends on provider A? (useful for knowing what is preventing autoDispose from being called, also includes Widgets in the widget tree)
- What does A depend on? (useful for knowing what will rebuild if A changes)

**Comment by rrousselGit** [comment]
I will keep this open as the devtool isn't technically here yet and the change made doesn't prevent all mistakes.

**Comment by venkatd** [comment]
Related to this in the meantime would be useful to have a helper like
`dependsOn(provider)` and `dependenciesOf`  (don't know the exact naming) so I can print them out while debugging. Does something like this exist in the API? One of my most common debugging scenarios is finding out why something isn't autoDisposed.

**Comment by rrousselGit** [comment]
You can do that. It's just not obvious

```dart
final provider = Provider(...);

ProviderContainer container = ProviderScope.containerOf(context);

container.debug*

final element = container.readProviderElement(provider);
print(element.dependents);
```

**Comment by dgaedcke** [comment]
Agreed!!  I love Riverpod and one improvement I'd like to see in the documentation is clarity on HOW LONG a provider will live, WITHOUT an active listener, before it will self-dispose / garbage-collect.

I'm probably inventing some bad practices because I don't understand this fully ...
https://stackoverflow.com/questions/64830479/flutter-riverpod-design-pattern-inhibit-garbage-collection

**Comment by rrousselGit** [comment]
> I'd like to see in the documentation is clarity on HOW LONG a provider will live, WITHOUT an active listener, before it will self-dispose / garbage-collect.

The provider will be disposed at the end of the current frame/event-loop.

Riverpod does something roughly equivalent to:

```dart
@override
void removeListener(listener) {
  _listener.remove(listener);
  if (!hasListeners) {
    Future(() {
      if (!hasListeners) {
       dispose();
      }
    });
  }
}
```

This is pseudo code, but should help understand what happens.

**Comment by dgaedcke** [comment]
That's very helpful ... thank you!!

a few clarifications please ...

Does this apply to ALL providers or ONLY those defined auto-dispose?

"watch" attaches a listener but "read" does not ... is that correct??  

So if I force a Provider to initialize with context.read(), but DO NOT watch it, then "removeListener" will never be called and this (non-autodispose) provider will live forever??

**Comment by rrousselGit** [comment]
If you call "read" and it no listener is attached, the state will still be disposed at the end of the frame

And that's only for autoDispose providers

**Comment by venkatd** [comment]
Following up on this thread. A very common source of debugging is understanding why a provider isn't disposed. So I'd love to see what values depend on a provider--what widgets and other providers are currently making use of *this* provider?

**Comment by rrousselGit** [comment]
This is planned for the devtool.

On top of inspecting the state, you will be able to inspect the links between objects. So you'd know what is listening to a provider

**Comment by venkatd** [comment]
That would be amazing :)

Happy to be a beta tester for the devtool, but we're usually on the bleeding edge of riverpod anyway :)

**Comment by mellowcello77** [comment]
Not sure of relevant for this topic, but calling .dispose() does not dispose a provider, correc? I can't find any other reference on how to manually dispose a non autodipose provider. Maybe my approach to the design is wrong and I'm overcomplicating it.

**Comment by otto-dev** [comment]
> It was unclear to me what "no-longer used means".

I totally agree with this, came here from google. As a developer coming to riverpod I need guarantees about when the `provider` will be destroyed, and when not. For two reasons: To make clear predictions about my applications behavior and to have assurance that `.autoDispose` is reliable.

As great as tooling is, documenting the guarantees and behavior `.autoDispose` should come first. It's hard to reason about your app when you are basing your expectations on assumptions.

**Comment by TimWhiting** [comment]
This PR https://github.com/rrousselGit/riverpod/pull/1689 is intended to address some of the documentation requests in this issue. If you want to leave feedback there, that would be helpful to understand whether there is more that needs to be explained.

**Comment by rrousselGit** [comment]
#1689 was merged, so this probably can be closed.
